import json

translations = {
"~z~and suddenly you've got...": "~z~ופתאום יש לך...",
"~z~drug addled degenerates,": "~z~מנוונים מסוממים,",
"~z~and spicy plantains.": "~z~ופלנטיין מתובל.",
"~z~But sometimes an ordinary Joe lets go,": "~z~אבל לפעמים בן אדם רגיל משתחרר,",
"~z~and hidden aliens embedded amongst us for the murder.": "~z~וחייזרים נסתרים שמוטמעים בינינו לביצוע הרצח.",
"~z~While some thugs obviously prefer four wheels,": "~z~בעוד שכמה בריונים מעדיפים כמובן ארבעה גלגלים,",
"~z~flooding our streets.": "~z~שמציפים את הרחובות שלנו.",
"~z~Or maybe you're just an over privileged poppycock": "~z~או אולי אתה סתם פלצן מיוחס מדי",
"~z~In a city where dreams too often become wet...": "~z~בעיר שבה חלומות הופכים לעיתים קרובות מדי לרטובים...",
"~z~Rumors are they get a new tattoo for every person they stab.": "~z~השמועות אומרות שהם עושים קעקוע חדש על כל אדם שהם דוקרים.",
"~z~When they're not running meth,": "~z~כשהם לא מריצים קריסטל מת',",
"~z~papaya juice,": "~z~מיץ פפאיה,",
"~z~and deluded desperados": "~z~ופושעים הוזים",
"~z~They're one of the largest Mexican street gangs in the city.": "~z~הם אחת מכנופיות הרחוב המקסיקניות הגדולות בעיר.",
"~z~God only knows what.": "~z~ורק אלוהים יודע מה עוד.",
"~z~living on daddy's pension and": "~z~שחי על הפנסיה של אבא ו",
"~z~women's liberation,": "~z~שחרור האישה,",
"~z~It's inspired film makers,": "~z~זה נתן השראה ליוצרי קולנוע,",
"~z~these are one of the nation's toughest": "~z~אלו הן אחת מהכנופיות הקשוחות במדינה",
"~z~and grade A Yay-Yo from Mexico": "~z~וקוקאין סוג א' ממקסיקו",
"~z~and entertainers dressed as cartoon characters,": "~z~ובדרנים לבושים כמו דמויות מצוירות,",
"~z~are fighting a war out here every day.": "~z~נלחמים כאן במלחמה כל יום.",
"~z~It turns out the Families love shooting each other,": "~z~מתברר שה-Families אוהבים לירות אחד בשני,",
"~z~The city of celluloid,": "~z~עיר הצלולואיד,",
"~z~or kill her themselves?": "~z~או שהם הרגו אותה בעצמם?",
"~z~we'll just keep picking up the pieces.": "~z~אנחנו פשוט נמשיך לאסוף את השברים.",
"~z~that the junkies are shooting in to their veins.": "~z~שהנרקומנים מזריקים לוורידים שלהם.",
"~z~it takes something particularly awful,": "~z~צריך משהו נורא במיוחד,",
"~z~almost as much as they love shooting Ballas.": "~z~כמעט כמו שהם אוהבים לירות ב-Ballas.",
"~z~or loan sharking,": "~z~או הלוואות בריבית,",
"~z~outlaw motorcycle gangs.": "~z~כנופיות אופנוענים מחוץ לחוק.",
"~z~and loses his shit after a pipe or two of pleasure dust.": "~z~ומאבד את זה אחרי איזו פייפ או שתיים של אבקת עונג.",
"~z~But not all crime is premeditated.": "~z~אבל לא כל פשע הוא מתוכנן מראש.",
"~z~and drugs.": "~z~וסמים.",
"~z~to cause serious criminal damage.": "~z~כדי לגרום לנזק פלילי רציני.",
"~z~Now the LSPD have had many run-ins with various Family sets over the years.": "~z~למשטרת לוס סנטוס היו הרבה התקלויות עם הפלגים השונים של ה-Families לאורך השנים.",
"~z~With the Ballas, the FIB take a more community outreach approach.": "~z~עם ה-Ballas, ה-FIB נוקטים בגישה יותר קהילתית.",
"~z~or so I hear a dangerous new drug on the streets called": "~z~או לפחות כך שמעתי, סם חדש ומסוכן ברחובות בשם",
"~z~Maybe drinking's your thing.": "~z~אולי שתייה זה הקטע שלך.",
"~z~And if they would have plucked up the courage,": "~z~ואם הם היו אוזרים אומץ,",
"~z~Illegal street racing,": "~z~מרוצי רחוב לא חוקיים,",
"~z~Blood thirsty 'Chicanos' with a predilection for": "~z~צ'יקאנוס צמאי דם עם נטייה ל",
"~z~With rumored connections to several major mafias.": "~z~עם שמועות על קשרים לכמה מאפיות גדולות.",
"~z~what happened to Leonora Johnson?": "~z~מה קרה לליאונורה ג'ונסון?",
"~z~Look at this drunken buffoon,": "~z~תראו את הליצן השיכור הזה,",
"~z~As long as the financial party continues,": "~z~כל עוד המסיבה הפיננסית נמשכת,",
"~z~In a town full of alien spotters,": "~z~בעיר מלאה בצופי חייזרים,",
"~z~Of course, Vinewood being Vinewood,": "~z~כמובן, כיוון שווינווד היא וינווד,",
"~z~the great orifice of American capitalism.": "~z~החור הגדול של הקפיטליזם האמריקאי.",
"~z~The Families love sports almost as much as they love banging.": "~z~ה-Families אוהבים ספורט כמעט כמו שהם אוהבים לירות.",
"~z~cocaine, and vice.": "~z~קוקאין ופשע.",
"~z~horny nerds have wondered,": "~z~חנונים חרמנים תהו,",
"~z~the mayor,": "~z~ראש העיר,",
"~z~adults dressed as zombies,": "~z~מבוגרים לבושים כמו זומבים,",
"~z~and terrorist cells in Chumash,": "~z~ותאי טרור בצ'ומאש,",
"~z~your toilet will be cleaned after you've smoked some of it.": "~z~השירותים שלך יהיו נקיים אחרי שתעשן קצת מזה.",
"~z~and run around naked.": "~z~ולרוץ מסביב עירומים.",
"~z~The second largest port in the world,": "~z~הנמל השני בגודלו בעולם,",
"~z~they love a good squabble.": "~z~הם אוהבים מריבה טובה.",
"~z~We've jumped from coast to coast,": "~z~קפצנו מחוף לחוף,",
"~z~and the Sheriff's Office": "~z~ומשרד השריף",
"~z~And we're giving up our national security for nothing?": "~z~ואנחנו מוותרים על הביטחון הלאומי שלנו בשביל כלום?",
"~z~Alright guys, let's go!": "~z~בסדר חבר'ה, בואו נזוז!",
"~z~Of course, to become truly popular,": "~z~כמובן, כדי להפוך לממש פופולרי,",
"~z~this is where it all begins.": "~z~כאן הכל מתחיל.",
"~z~to the gang bangers in Davis and Strawberry,": "~z~לחברי הכנופיות בדיוויס וסטרוברי,",
"~z~protesting about the unfairness of capitalism.": "~z~מוחים על חוסר ההגינות של הקפיטליזם.",
"~z~have blamed various celebrities,": "~z~האשימו סלבריטאים שונים,",
"~z~While half the battle out here is fought with guns,": "~z~בעוד שחצי מהמלחמה כאן בחוץ מתנהלת עם רובים,",
"~z~Or maybe the Chinese are slipping some of our": "~z~או אולי הסינים מגניבים כמה מה",
"~z~double identity theft,": "~z~גניבת זהות כפולה,",
"~z~and have spent more time in the Midwest": "~z~ובילינו יותר זמן במערב התיכון",
"~z~to bust the bad guys.": "~z~כדי לתפוס את החבר'ה הרעים.",
"~z~your murder has to be both unsolved and gruesome.": "~z~הרצח שלך צריך להיות גם לא מפוענח וגם מזוויע.",
"~z~than a tornado spotter.": "~z~מאשר צייד טורנדו.",
"~z~or even worse...": "~z~או אפילו גרוע מזה...",
"~z~From dead starlets in Vinewood,": "~z~מכוכבניות מתות בווינווד,",
"~z~Most of the time this illicit cargo makes it straight to the gangs.": "~z~לרוב המטען הלא חוקי הזה מגיע ישירות לכנופיות.",
"~z~And once it hits the hood,": "~z~וברגע שזה מגיע לשכונה,",
"~z~This isn't an exotic S&M party,": "~z~זו לא מסיבת סאדו מאזו אקזוטית,",
"~z~competitive and aggressive.": "~z~תחרותי ואגרסיבי.",
"~z~it's not all about leathery dudes trying to show off on their motorbikes,": "~z~זה לא רק גברים עטויי עור שמנסים להשוויץ על האופנועים שלהם,",
"~z~This is the town that made mass murder,": "~z~זו העיר שהפכה רצח המוני,",
"~z~high security weapons systems in with the recycling.": "~z~מערכות נשק באבטחה גבוהה ביחד עם המיחזור.",
"~z~that make up this...": "~z~שמרכיבות את...",
"~z~and cellulite removal.": "~z~והסרת צלוליטיס.",
"~z~they're smoking it,": "~z~הם מעשנים את זה,",
"~z~Now the Ballas fly the colors of the Los Santos Panic,": "~z~עכשיו ה-Ballas לובשים את הצבעים של לוס סנטוס פאניק,",
"~z~other desperados prefer two.": "~z~פושעים אחרים מעדיפים שניים.",
"~z~they're selling the dope": "~z~הם מוכרים את הסמים",
"~z~And not necessarily always in that order.": "~z~ולא בהכרח תמיד בסדר הזה.",
"~z~They are life long bitter enemies of the Ballas.": "~z~הם אויבים מושבעים לכל החיים של ה-Ballas.",
"~z~is one such case.": "~z~הוא מקרה אחד כזה.",
"~z~into nostalgia.": "~z~לנוסטלגיה.",
"~z~And it's definitely okay for your motorcycle momma": "~z~וזה בהחלט בסדר שאשת האופנוען שלך",
"~z~to show her breasts to your friends.": "~z~תראה את השדיים שלה לחברים שלך.",
"~z~proving that...": "~z~ומוכיח ש...",
"~z~never use PCP,": "~z~לעולם אל תשתמשו ב-PCP,",
"~z~Of course, like all families": "~z~כמובן, כמו כל המשפחות",
"~z~And hidden in over two million containers a day,": "~z~ומוסתר בלמעלה משני מיליון מכולות ביום,",
"~z~great city of lights.": "~z~עיר האורות הגדולה.",
"~z~When Ballas and the Families aren't shooting each other,": "~z~כשה-Ballas וה-Families לא יורים אחד בשני,",
"~z~Subdivided in to sets such as,": "~z~מחולקים לפלגים כמו,",
"~z~The famous unsolved murder of a Vinewood starlet": "~z~הרצח המפורסם והלא מפוענח של כוכבנית מווינווד",
"~z~garbage going out.": "~z~זבל יוצא.",
"~z~there doesn't always need to be criminal intent,": "~z~לא תמיד צריכה להיות כוונת זדון פלילית,",
"~z~Yes. Speed, snort and sex.": "~z~כן. ספיד, הסנפות וסקס.",
"~z~Wearing the colors of the Feud or the Corkers.": "~z~לובשים את הצבעים של ה-Feud או ה-Corkers.",
"~z~The FIB has been tracking the Lost for years.": "~z~ה-FIB עוקב אחרי ה-Lost כבר שנים.",
"~z~it makes you wanna punch cops,": "~z~זה גורם לך לרצות להרביץ לשוטרים,",
"~z~to speak to her,": "~z~לדבר איתה,",
"~z~or roided up gangbangers stuck in some nineties time warp.": "~z~או חברי כנופיות מפוצצים בסטרואידים שתקועים באיזו עיוות זמן משנות התשעים.",
"~z~to really catch people's attention.": "~z~כדי באמת למשוך את תשומת הלב של אנשים.",
"~z~Suck my dick, Steve fucking Haines.": "~z~תמצוץ לי, סטיב פאקינג היינס.",
"~z~It's time to take a look inside this": "~z~הגיע הזמן להסתכל פנימה לתוך",
"~z~The Families call themselves gang green.": "~z~ה-Families קוראים לעצמם כנופיה ירוקה.",
"~z~The alliterative threesome that helped hook America on": "~z~השלישייה האליטרטיבית שעזרה למכר את אמריקה ל",
"~z~A word to the wise kids,": "~z~מילה לחכמים ילדים,",
"~z~I'm decorated FIB agent Steven Haines.": "~z~אני סוכן FIB מעוטר, סטיבן היינס.",
"~z~to the drunken tourists in Del Perro Pier.": "~z~לתיירים השיכורים במזח דל פרו.",
"~z~and copycat killers.": "~z~ורוצחים חקיינים.",
"~z~Sometimes you need to become the bad guys,": "~z~לפעמים צריך להפוך לחבר'ה הרעים,",
"~z~H-hey guys, stay out of trouble now.": "~z~ה-היי חבר'ה, תישארו מחוץ לצרות עכשיו.",
"~z~A side of murder, hold the fries!": "~z~תוספת של רצח, בלי צ'יפס!",
"~z~the other half is with informants.": "~z~החצי השני הוא עם מודיעים.",
"~z~Maybe stock market manipulation is your bag?": "~z~אולי מניפולציות בבורסה זה הקטע שלך?",
"~z~with tears.": "~z~עם דמעות.",
"~z~The Cartels pay off some low level schlob,": "~z~הקרטלים משלמים לאיזה טמבל ברמה נמוכה,",
"~z~On our next episode,": "~z~בפרק הבא שלנו,",
"~z~badly cut crystal meth,": "~z~קריסטל מת' חתוך גרוע,",
"~z~short skirts,": "~z~חצאיות קצרות,",
"~z~cesspit of destroyed dreams,": "~z~בור שופכין של חלומות הרוסים,",
"~z~Military grade weapons,": "~z~נשק ברמה צבאית,",
"~z~Because they are the bruise on the face of this city.": "~z~כי הם החבורה על הפרצוף של העיר הזאת.",
"~z~Nah, hell no. Not again.": "~z~לא, לעזאזל לא. לא עוד פעם.",
"~z~I'm a death turd. I'm the turd of death... I'm a dead turd.": "~z~אני חרא של מוות. אני החרא של המוות... אני חרא מת.",
"~z~I want to know. Is is?": "~z~אני רוצה לדעת. האם זה?",
"~z~Why did I do that? Why? Why? Why?": "~z~למה עשיתי את זה? למה? למה? למה?",
"~z~Man, I've got to get some real fucking weed, asap - This shit is so fucking weak.": "~z~בן אדם, אני חייב להשיג קצת וויד אמיתי, דחוף - החרא הזה כל כך פאקינג חלש.",
"~z~which the fuck is it? Something is very dead.": "~z~איזה מהם זה לעזאזל? משהו מת מאוד.",
"~z~I always wanted to be an A and I'm just a fucking B. Man, I hate Bs!": "~z~תמיד רציתי להיות א' ואני רק פאקינג ב'. בן אדם, אני שונא ב'!",
"~z~I belong in hell! I don't belong in hell.": "~z~המקום שלי בגיהנום! המקום שלי לא בגיהנום.",
"~z~That stuff simply does nothing for me, no... nothing at all.": "~z~החומר הזה פשוט לא עושה לי כלום, לא... שום דבר בכלל.",
"~z~Man, that's good ass weed, man. Shit's strong... makes me feel good as a motherfucker...": "~z~בן אדם, זה חתיכת וויד טוב, אחי. החרא הזה חזק... גורם לי להרגיש פאקינג טוב...",
"~z~Is is? Is? I mean, seriously, is it?": "~z~האם זה? האם? כלומר, ברצינות, האם זה?",
"~z~Why do I keep doing this to myself? What is wrong with me?": "~z~למה אני ממשיך לעשות את זה לעצמי? מה לא בסדר איתי?",
"~z~I'm not stoned, hell no. I'm relaxed, nigga, that's what I am.": "~z~אני לא מסטול, לעזאזל לא. אני רגוע, אחי, זה מה שאני.",
"~z~Man, this stuff does nothing for me. Nothing at all. Fuck, I should get something": "~z~בן אדם, החומר הזה לא עושה לי כלום. שום דבר בכלל. פאק, אני צריך להשיג משהו",
"~z~She ain't my woman. She ain't shit to me. I ain't shit to me.": "~z~היא לא האישה שלי. היא שום דבר בשבילי. אני שום דבר בשביל עצמי.",
"~z~awful everything about existence really is...": "~z~כמה נורא כל מה שקשור לקיום באמת...",
"~z~Or B okay.  I'm not an A or a B. Or maybe I am a B.": "~z~או ב' זה בסדר. אני לא א' או ב'. או אולי אני ב'.",
"~z~Hell is me. That's right, me.  I belong in hell.": "~z~הגיהנום זה אני. נכון מאוד, אני. המקום שלי בגיהנום.",
"~z~Man, I am stoned as a motherfucker. My motherfucking mother... Man.": "~z~בן אדם, אני מסטול מת. אמא שלי... בן אדם.",
"~z~Are they fucking nuts? This is not fun. This... This is no fun.": "~z~הם פאקינג משוגעים? זה לא כיף. זה... זה לא כיף.",
"~z~Is it? Oh man, I'm fucking lost.": "~z~האם זה? או בן אדם, אני פאקינג אבוד.",
"~z~Uh uh. This... not... fun... what is fun anyway?": "~z~אה אה. זה... לא... כיף... מה זה כיף בכלל?",
"~z~at all fun... Whoo! I fucking love it!!!": "~z~בכלל כיף... ווהו! אני פאקינג מת על זה!!!",
"~z~stronger, man. It's doing nothing.": "~z~חזק יותר, בן אדם. זה לא עושה כלום.",
"~z~Uhh, I shoulda been a surgeon. That's what I shoulda been.": "~z~אה, הייתי צריך להיות מנתח. זה מה שהייתי צריך להיות.",
"~z~Because I don't feel any fucking thing. Because I'm empty,": "~z~כי אני לא מרגיש שום פאקינג דבר. כי אני ריק,",
"~z~Not a thing I'm totally fine. Fine and suicidal.": "~z~שום דבר אני בסדר גמור. בסדר ואובדני.",
"~z~I don't belong anywhere...": "~z~אני לא שייך לשום מקום...",
"~z~I'm as happy as you can be... when you're all alone and everyone hates you.": "~z~אני מאושר ככל האפשר... כשאתה לגמרי לבד וכולם שונאים אותך.",
"~z~I really hate me.": "~z~אני ממש שונא אותי.",
"~z~Is is is? Is it? Come on, somebody fucking help me!": "~z~האם האם האם? האם זה? קדימה, שמישהו פאקינג יעזור לי!",
"~z~Ohhhh. Why does everything hurt so much all the time?": "~z~אוווה. למה הכל כל כך כואב כל הזמן?",
"~z~I just smoked pot. I'm going to die. To die. To... Die.": "~z~הרגע עישנתי גראס. אני הולך למות. למות. ל...מות.",
"~z~and that's why I don't have any real fucking friends.": "~z~ובגלל זה אין לי שום חברים אמיתיים.",
"~z~my fucking lungs hurt right now. Man, my lungs is hurtin. My poor fucking lungs.": "~z~הריאות שלי כואבות עכשיו. בן אדם, הריאות שלי כואבות. הריאות המסכנות שלי.",
"~z~Silent. Deadly. A tough motherfucker who people don't fuck with.": "~z~שקט. קטלני. מניאק קשוח שאנשים לא מתעסקים איתו.",
"~z~That's the thing, man. Shit. Is it the way? Is the thing...": "~z~זה העניין, בן אדם. שיט. האם זו הדרך? האם הדבר...",
"~z~any way good... not remotely good... not": "~z~בשום דרך טוב... אפילו לא קרוב לטוב... לא",
"~z~I can't feel anything. Nothing.": "~z~אני לא מצליח להרגיש כלום. שום דבר.",
"~z~Shit, I could be a brain surgeon. Brain surgery, I could do that.": "~z~שיט, יכולתי להיות מנתח מוח. ניתוחי מוח, הייתי יכול לעשות את זה.",
"~z~It can't touch me. Nothing can touch me.": "~z~זה לא יכול לגעת בי. שום דבר לא יכול לגעת בי.",
"~z~Why do I hate my fucking lungs? Why do I hate my fucking self?": "~z~למה אני שונא את הריאות המזדיינות שלי? למה אני שונא את עצמי?",
"~z~all good.": "~z~הכל טוב.",
"~z~Man that weed is strong... strong... just like me... strong.": "~z~בן אדם הוויד הזה חזק... חזק... בדיוק כמוני... חזק.",
"~z~Oh man, I've got to stop doing stupid things.": "~z~או בן אדם, אני חייב להפסיק לעשות דברים טיפשיים.",
"~z~Why did I smoke that stuff? What is fucking wrong with me? Always the same, every time.": "~z~למה עישנתי את החומר הזה? מה פאקינג לא בסדר איתי? תמיד אותו דבר, כל פעם.",
"~z~Fun, ah! Fun is... fun is... death.": "~z~כיף, אה! כיף זה... כיף זה... מוות.",
"~z~I can't even feel my fucking toes right now. Man, my toes are fucking dead!": "~z~אני אפילו לא מצליח להרגיש את הבהונות שלי עכשיו. בן אדם, הבהונות שלי פאקינג מתות!",
"~z~Worth... less. Less worth. Oh man, I think my spine is melting. Fuck this.": "~z~חסר... ערך. פחות ערך. או בן אדם, נראה לי שעמוד השדרה שלי נמס. פאק זה.",
"~z~That's me, I'm a father and I'm taking fucking drugs. No wonder my kids take drugs.": "~z~זה אני, אני אבא ואני לוקח סמים. לא פלא שהילדים שלי לוקחים סמים.",
"~z~and Tanisha, and go live on an island some fucking where.": "~z~וטנישה, וללכת לגור על איזה אי באיזשהו מקום.",
"~z~Every fucking time. I'll be good. I'm bad. I'll be nice. I'm a cunt.": "~z~כל פאקינג פעם. אני אהיה טוב. אני רע. אני אהיה נחמד. אני חרא.",
"~z~I am gonna die, and that is fucking fun...": "~z~אני הולך למות, וזה פאקינג כיף...",
"~z~No wonder everybody hates me. They're right. I'm worthless.": "~z~לא פלא שכולם שונאים אותי. הם צודקים. אני חסר ערך.",
"~z~If only I wasn't such an asshole... to everyone...": "~z~אילו רק לא הייתי כזה חרא... לכולם...",
"~z~My toes are dead - or my soul -": "~z~הבהונות שלי מתות - או הנשמה שלי -",
"~z~I'm a baby and I hate myself and I always have. I always have and that's the truth...": "~z~אני תינוק ואני שונא את עצמי ותמיד שנאתי. תמיד, וזו האמת...",
"~z~that is not fucking fun.": "~z~שזה לא פאקינג כיף.",
"~z~Man, I just wish I could get a bigger bag of this good shit": "~z~בן אדם, הלוואי והייתי יכול להשיג שקית גדולה יותר מהחרא הטוב הזה",
"~z~Is... is it the why? Is the thing, the absolute thing?": "~z~האם... האם זה הלמה? האם הדבר, הדבר המוחלט?",
"~z~entirely wrong.": "~z~לגמרי לא נכון.",
"~z~I have a head but do I got a brain? I can't feel it. Shit. I can't feel shit.": "~z~יש לי ראש אבל האם יש לי מוח? אני לא מרגיש אותו. שיט. אני לא מרגיש כלום.",
"~z~If only I didn't... I didn't lie and cheat so much -": "~z~אילו רק לא הייתי... לא הייתי משקר ובוגד כל כך הרבה -",
"~z~Shit. Shit. I'm a father and I'm stoned.": "~z~שיט. שיט. אני אבא ואני מסטול.",
"~z~I'm sober as can be.": "~z~אני פיכח לגמרי.",
"~z~Why do I smoke so often? Why? Do I? Why?": "~z~למה אני מעשן כל כך הרבה פעמים? למה? אני מעשן? למה?",
"~z~That stuff is strong.": "~z~החומר הזה חזק.",
"~z~What isn't wrong with me?  I'm entirely wrong...": "~z~מה כן בסדר איתי? אני לגמרי לא בסדר...",
"~z~No wonder they hate me. It's a wonder they don't hate me more. I hate me more.": "~z~לא פלא שהם שונאים אותי. זה פלא שהם לא שונאים אותי יותר. אני שונא את עצמי יותר.",
"~z~I really should smoke more of that stuff, makes me realize what a great guy I could be...": "~z~אני באמת צריך לעשן עוד מהחומר הזה, גורם לי להבין איזה בחור נהדר הייתי יכול להיות...",
"~z~I could be on some motherfucking island motherfucker with this woman.": "~z~יכולתי להיות על איזה אי מזדיין, עם האישה הזאת.",
"~z~So why do I do it? Shit. Who do I smoke so often?": "~z~אז למה אני עושה את זה? שיט. למה אני מעשן כל כך הרבה פעמים?",
"~z~all it does is make me realize how": "~z~כל מה שזה עושה זה לגרום לי להבין כמה",
"~z~if they'd liked me. Fuck them. Fuck them. Fuck everybody. Nobody likes me. Nobody.": "~z~אם הם היו אוהבים אותי. שילכו להזדיין. שילכו להזדיין. שכולם ילכו להזדיין. אף אחד לא אוהב אותי. אף אחד.",
"~z~I'm completely not stoned. I'm straight. Completely straight. I could do anything.": "~z~אני לגמרי לא מסטול. אני נקי. נקי לגמרי. אני יכול לעשות הכל.",
"~z~What is of? Jeez. Oh fuck, I think my back hurts. Uhh...": "~z~מה זה של? אלוהים. או פאק, נראה לי שכואב לי הגב. אה...",
"~z~Oh man, oh man, oh man... I'm not tough at all. I'm just a baby.": "~z~או בן אדם, או בן אדם, או בן אדם... אני לא קשוח בכלל. אני סתם תינוק.",
"~z~Trevor 'Steel' Philips, they used to call me. Or they would have called me,": "~z~טרבור 'פלדה' פיליפס, ככה היו קוראים לי. או לפחות היו קוראים לי ככה,",
"~z~Why? Why? What is why? What is what?": "~z~למה? למה? מה זה למה? מה זה מה?",
"~z~I can't feel my legs. Or my head. Have I lost my head? No, wait. Here it is.": "~z~אני לא מצליח להרגיש את הרגליים שלי. או את הראש שלי. איבדתי את הראש? לא, רגע. הנה הוא.",
"~z~Oooooh, this is not good... not good at all... not at": "~z~אווו, זה לא טוב... לא טוב בכלל... לא ב",
"~z~Who nobody fucks with. Because nobody likes.": "~z~שאף אחד לא מתעסק איתו. כי אף אחד לא מחבב אותו.",
"~z~and it is all I deserve in this life. I was born to suffer.": "~z~וזה כל מה שמגיע לי בחיים האלה. נולדתי לסבול.",
"~z~I'm not stoned at all. Hell no, not at all. Completely not stoned.": "~z~אני לא מסטול בכלל. לעזאזל לא, ממש לא. לגמרי לא מסטול.",
"~z~That's decent weed right there - I feel nice. Ohh, I feel real good.": "~z~זה וויד סבבה לגמרי - אני מרגיש נחמד. אוה, אני מרגיש ממש טוב.",
"~z~I'm a sober sociopath. I'm a": "~z~אני סוציופת פיכח. אני",
"~z~I'm a stoned father. I'm a father. Yup.": "~z~אני אבא מסטול. אני אבא. כן.",
"~z~Ah, fuck, man. I'm the thing of why. The why of things.": "~z~אה, פאק, בן אדם. אני הדבר של הלמה. הלמה של הדברים.",
"~z~This stuff does nothing to me. I'm made of steel. Steel.": "~z~החומר הזה לא עושה לי כלום. אני עשוי מפלדה. פלדה.",
"~z~That's not real weed - does nothing for me. Shit.": "~z~זה לא וויד אמיתי - לא עושה לי כלום. שיט.",
"~z~Ohh! Oh, this is hell. Fuck me, I've done it again. I'm in hell.": "~z~אוו! או, זה גיהנום. לעזאזל איתי, עשיתי את זה שוב. אני בגיהנום.",
"~z~What is death? It's just a word. Like turd. Turd. Turd is a word.": "~z~מה זה מוות? זו רק מילה. כמו חרא. חרא. חרא זו מילה.",
"~z~This is completely horrible in every conceivable way": "~z~זה לגמרי נורא בכל דרך אפשרית",
"~z~Man, that stuff is pointless,": "~z~בן אדם, החומר הזה חסר תועלת,",
"~z~All over. Everything is okay. A okay.": "~z~בכל מקום. הכל בסדר. בסדר גמור.",
"~z~drug addict ass fool - just like I'm on drugs... shit.": "~z~טיפש מסומם חרא - בדיוק כמו שאני על סמים... שיט.",
"~z~Why is what. What is what and why is why?": "~z~למה זה מה. מה זה מה ולמה זה למה?",
"~z~sad, sober, sociopath. I'm a sad and silly sober sociopath.": "~z~סוציופת עצוב ופיכח. אני סוציופת פיכח, עצוב וטיפשי.",
"~z~I could shit myself - I hope I didn't shit myself. Did I?": "~z~אני יכול לחרבן על עצמי - אני מקווה שלא חירבנתי על עצמי. האם חירבנתי?",
"~z~clean... and relaxed. And happy. Yeah, man, I'm happy.": "~z~נקי... ורגוע. ושמח. כן, בן אדם, אני שמח.",
"~z~that's not good... not good at all... not in": "~z~זה לא טוב... לא טוב בכלל... לא ב",
"~z~Jesus, I've got to stop smoking so much fucking weed, man, my -": "~z~ישו, אני חייב להפסיק לעשן כל כך הרבה פאקינג וויד, בן אדם, ה-",
"~z~That stuff is real strong. I am weak but that is strong.": "~z~החומר הזה ממש חזק. אני חלש אבל זה חזק.",
"~z~I'm relaxed. Man, I am so relaxed and happy. Happy as a motherfucker.": "~z~אני רגוע. בן אדם, אני כל כך רגוע ושמח. שמח בטירוף.",
"~z~My fucking mother, man, I miss you. You fucking moron -": "~z~אמא שלי, בן אדם, אני מתגעגע אלייך. מטומטמת -",
"~z~Uhh, well, maybe Tanisha wouldn't hate me so much. She wouldn't hate me so much.": "~z~אה, ובכן, אולי טנישה לא הייתה שונאת אותי כל כך. היא לא הייתה שונאת אותי כל כך.",
"~z~I'm in hell. I'm all alone, in hell. Hell is no other people. Hell...": "~z~אני בגיהנום. אני לגמרי לבד, בגיהנום. הגיהנום הוא לא אנשים אחרים. הגיהנום...",
"While holding ~INPUTGROUP_SCRIPT_LSTICK_ALL~ and ~INPUTGROUP_SCRIPT_RSTICK_ALL~ in position,~n~release ~INPUT_SCRIPT_LT~ and ~INPUT_SCRIPT_RT~ to exhale.~n~": "בעודך מחזיק את ~INPUTGROUP_SCRIPT_LSTICK_ALL~ ו-~INPUTGROUP_SCRIPT_RSTICK_ALL~ במקומם,~n~שחרר את ~INPUT_SCRIPT_LT~ ו-~INPUT_SCRIPT_RT~ כדי לנשוף.~n~",
"Are you sure you want to quit Yoga?": "האם אתה בטוח שברצונך לפרוש מהיוגה?",
"While holding ~INPUTGROUP_SCRIPT_LSTICK_ALL~ and ~INPUTGROUP_SCRIPT_RSTICK_ALL~ in position,~n~press and hold ~INPUT_SCRIPT_LT~ and ~INPUT_SCRIPT_RT~ to inhale.~n~": "בעודך מחזיק את ~INPUTGROUP_SCRIPT_LSTICK_ALL~ ו-~INPUTGROUP_SCRIPT_RSTICK_ALL~ במקומם,~n~לחץ והחזק את ~INPUT_SCRIPT_LT~ ו-~INPUT_SCRIPT_RT~ כדי לשאוף.~n~"
}

with open("current_batch.json", "w", encoding="utf-8") as f:
    json.dump(translations, f, ensure_ascii=False, indent=4)
