import json

data = {
    "~z~but it was going nowhere.": "~z~אבל זה לא הוביל לשום מקום.",
    "~z~They do! That's why I'm going to make it street again.": "~z~הם כן! בגלל זה אני הולך להפוך את זה לרחוב שוב.",
    "~z~And when fate finally catches up - man he will be fucked.": "~z~וכשהגורל סוף סוף ישיג אותו - בנאדם הוא הולך להידפק.",
    "~z~and they ain't going to suddenly stop being selfish, and look after you. So": "~z~והם לא הולכים פתאום להפסיק להיות אנוכיים, ולשמור עליך. אז",
    "~z~Simpler times.": "~z~זמנים פשוטים יותר.",
    "~z~You're on the wrong drugs, boy.": "~z~אתה על הסמים הלא נכונים, ילד.",
    "~z~Gotta love them. Anyway, how's school?": "~z~אי אפשר שלא לאהוב אותם. בכל מקרה, איך בבית ספר?",
    "~z~Only Dad faked his death. You could have maybe tracked us down.": "~z~רק אבא זייף את המוות שלו. אולי היית יכול לאתר אותנו.",
    "~z~but we can't help it.": "~z~אבל אנחנו לא יכולים לעזור בזה.",
    "~z~I will find a purpose. I swear.": "~z~אני אמצא מטרה. אני נשבע.",
    "~z~Your dad, eh? What a guy. What a guy.": "~z~אבא שלך, אה? איזה בחור. איזה בחור.",
    "~z~I knew that only sadness would come out of that union, and I shoulda done something.": "~z~ידעתי שרק עצב ייצא מהאיחוד הזה, והייתי צריך לעשות משהו.",
    "~z~I've never really thought of that... I guess my problem is it just": "~z~אף פעם לא ממש חשבתי על זה... אני מניח שהבעיה שלי היא שזה פשוט",
    "~z~Not too much, kid. Just enjoying myself, mostly.": "~z~לא יותר מדי, ילד. רק נהנה מהחיים, בעיקר.",
    "~z~So, how's Tracey? I don't see enough of that girl.": "~z~אז, איך Tracey? אני לא רואה מספיק מהילדה הזאת.",
    "~z~That would probably keep you quiet.": "~z~זה כנראה ישתיק אותך.",
    "~z~I'm pleased we can spend this time together, boy.": "~z~אני שמח שאנחנו יכולים להעביר את הזמן הזה ביחד, ילד.",
    "~z~Then you graduated, nigga.": "~z~ואז סיימת, ניגה.",
    "~z~Well, yeah. There's always been a dress code - flag, the colors, all that shit got to match.": "~z~ובכן, כן. תמיד היה קוד לבוש - דגל, הצבעים, כל החרא הזה חייב להתאים.",
    "~z~What is this, the army? Is there a code of appearance for being in your gang now?": "~z~מה זה, הצבא? יש קוד מראה כדי להיות בכנופיה שלכם עכשיו?",
    "~z~I miss Brad.": "~z~אני מתגעגע לבראד.",
    "~z~Told who?": "~z~אמרת למי?",
    "~z~Shit, I do it with a look, I'll be in the mirror just staring at myself and I see them sharks staring right back at me like... look...": "~z~שיט, אני עושה את זה עם מבט, אני אהיה מול המראה רק מסתכל על עצמי ואני רואה את הכרישים האלה בוהים בי בחזרה כמו... תראה...",
    "~z~Thank you, Lamar - I'm kind of getting fond of you, too.": "~z~תודה, Lamar - גם אני מתחיל לחבב אותך.",
    "~z~Can I gang bang?": "~z~אני יכול להיות חבר כנופיה?",
    "~z~I mean, don't get in the situation where you have to miss him. Look out for him. Stick together.": "~z~אני מתכוון, אל תיכנס למצב שאתה צריך להתגעגע אליו. תשגיח עליו. תישארו ביחד.",
    "~z~The liver. Always the liver.": "~z~הכבד. תמיד הכבד.",
    "~z~atoms splitting, rupture in the space time continuum. Shit would be fucked.": "~z~אטומים מתפצלים, קרע ברצף הזמן והחלל. חרא יהיה דפוק.",
    "~z~very low tolerance for lies and bullshit.": "~z~סובלנות נמוכה מאוד לשקרים ובולשיט.",
    "~z~I don't have time to think about that shit.": "~z~אין לי זמן לחשוב על החרא הזה.",
    "~z~So, what's happening, homie?": "~z~אז, מה קורה, אחי?",
    "~z~Boo!": "~z~בו!",
    "~z~Umm... okay...": "~z~אממ... אוקיי...",
    "~z~Err... err... Oh, my bad, I mean... I mean he meant": "~z~אה... אה... או, טעות שלי, אני מתכוון... אני מתכוון שהוא התכוון",
    "~z~Nothing. What's wrong with you, getting all touchy?": "~z~כלום. מה הבעיה שלך, נהיה כולך רגיש?",
    "~z~and theres a few other sets, but most Families, you know, them niggas is assholes.": "~z~ויש עוד כמה סטים, אבל רוב ה-Families, אתה יודע, הניגרים האלה הם חארות.",
    "~z~That's a lot of animals you got there.": "~z~זה הרבה חיות שיש לך שם.",
    "~z~Franklin... I mean... nobody...": "~z~Franklin... אני מתכוון... אף אחד...",
    "~z~I don't know... I'm not scared of much. That's what I'm supposed to say.": "~z~אני לא יודע... אני לא מפחד מהרבה דברים. זה מה שאני אמור להגיד.",
    "~z~Trevor, you's a good friend, homie. I'm serious.": "~z~Trevor, אתה חבר טוב, אחי. אני רציני.",
    "~z~Terrifying - literally the most frightening shark to ever say boo to me.": "~z~מפחיד - פשוטו כמשמעו הכריש הכי מפחיד שאי פעם אמר לי בו.",
    "~z~Do you love me, as a friend?": "~z~אתה אוהב אותי, בתור חבר?",
    "~z~I ain't soft, bitch. I'll prove I ain't no pussy right motherfucking now. Come on.": "~z~אני לא רך, כלבה. אני אוכיח שאני לא כוסית ממש עכשיו. קדימה.",
    "~z~Fucking right, man. I heard that. But, you know, them Ballas are pretty fucking annoying too.": "~z~פאקינג צודק, בנאדם. שמעתי את זה. אבל, אתה יודע, ה-Ballas האלה גם די פאקינג מעצבנים.",
    "~z~So how you been, dude?": "~z~אז מה שלומך, אחי?",
    "~z~But you don't scare me, motherfucker. You're crazy, but you're good people, though.": "~z~אבל אתה לא מפחיד אותי, בן זונה. אתה משוגע, אבל אתה אנשים טובים, בכל זאת.",
    "~z~What was that now?": "~z~מה זה היה עכשיו?",
    "~z~But, uhh, I heard that Michael dude is living in a big ass house while you down here bumming in a motherfucking trailer.": "~z~אבל, אהה, שמעתי שהבחור הזה Michael חי בבית ענק בזמן שאתה פה למטה מתבטל בקרוואן המזדיין הזה.",
    "~z~Old creepy ass motherfucker.": "~z~בן זונה זקן ומצמרר.",
    "~z~What it takes?": "~z~מה שצריך?",
    "~z~I won't leave you. We won't leave you. Me and Frank is lifers, man. Lifers.": "~z~אני לא אעזוב אותך. אנחנו לא נעזוב אותך. אני ופרנק לכל החיים, אחי. לכל החיים.",
    "~z~Wait, oh, shit. Wait, wait, wait. This a old trick now, you on that bullshit. It's like, if you ain't no pussy,": "~z~רגע, או, שיט. רגע, רגע, רגע. זה טריק ישן עכשיו, אתה על הבולשיט הזה. זה כאילו, אם אתה לא כוסית,",
    "~z~Fuck a team. We more of two dudes against the world type dudes.": "~z~שיזדיין הצוות. אנחנו יותר בקטע של שני בחורים נגד העולם.",
    "~z~only thing, they was trying to murder me, rather than hang with me, but it's cool.": "~z~הדבר היחיד, הם ניסו לרצוח אותי, במקום להסתובב איתי, אבל זה מגניב.",
    "~z~The difference is between green, like grass; and purple, like a big ol' purple shit.": "~z~ההבדל הוא בין ירוק, כמו דשא; וסגול, כמו חתיכת חרא סגול וגדול.",
    "~z~Yeah. Yeah, me too...": "~z~כן. כן, גם אני...",
    "~z~Well what does it take? I mean, I love the music -": "~z~ובכן מה צריך? אני מתכוון, אני אוהב את המוזיקה -",
    "~z~Maybe one day you'll be. But now, it's Franklin.": "~z~אולי יום אחד תהיה. אבל עכשיו, זה Franklin.",
    "~z~Forte, man, I fuck shit up all the time.": "~z~פורטה, אחי, אני דופק דברים כל הזמן.",
    "~z~Come on, keep it one thousand with your boy, man. Keep it real. You can holla at me.": "~z~קדימה, תשמור את זה מאה (הערה: אמיתי) עם הבחור שלך, אחי. תשמור על זה אמיתי. אתה יכול לדבר איתי.",
    "~z~Don't miss Franklin like I miss Brad, alright?": "~z~אל תתגעגע ל-Franklin כמו שאני מתגעגע לבראד, בסדר?",
    "~z~So, let me tell you something, homie.": "~z~אז, תן לי להגיד לך משהו, אחי.",
    "~z~Well, it's the only thing I can think about when I'm within like ten feet of you.": "~z~ובכן, זה הדבר היחיד שאני יכול לחשוב עליו כשאני במרחק של איזה עשרה מטרים ממך.",
    "~z~Nothing to be ashamed of.": "~z~אין ממה להתבייש.",
    "~z~Eh, man, you ever play sports as a kid?": "~z~אה, בנאדם, אי פעם שיחקת ספורט כילד?",
    "~z~What the fuck is wrong with you, fool?": "~z~מה לעזאזל הבעיה שלך, טמבל?",
    "~z~And loyal too. Really though, I'm all about loyalty.": "~z~וגם נאמן. באמת, אני רק בעניין של נאמנות.",
    "~z~If you want to fight...": "~z~אם אתה רוצה ללכת מכות...",
    "~z~That ungrateful little fat shit. He's just like his buddy Michael. I tell you...": "~z~החרא השמן הקטן וכפוי הטובה הזה. הוא בדיוק כמו החבר שלו Michael. אני אומר לך...",
    "~z~But look, I really was gonna ask you though, who you got more love for, me or Franklin, man?": "~z~אבל תראה, באמת התכוונתי לשאול אותך בכל זאת, את מי אתה אוהב יותר, אותי או את Franklin, אחי?",
    "~z~you were crazy in the efforts you would go to protect the truth and help people...": "~z~היית משוגע במאמצים שהיית עושה כדי להגן על האמת ולעזור לאנשים...",
    "~z~Sorry, I like you, and I respect you, and we're friends. But Franklin's in the crew.": "~z~סליחה, אני מחבב אותך, ואני מכבד אותך, ואנחנו חברים. אבל Franklin הוא בצוות.",
    "~z~I got love for all my homies, homie.": "~z~יש לי אהבה לכל האחים שלי, אחי.",
    "~z~They're the angriest, most self-obsessed people on the planet.": "~z~הם האנשים הכי כועסים, הכי אובססיביים לעצמם על כדור הארץ.",
    "~z~Ah, nah nigga, I don't get down like that...": "~z~אה, לא ניגה, אני לא עושה את זה ככה...",
    "~z~let's just say they won't make that mistake again... you ever get that?": "~z~בוא רק נגיד שהם לא יעשו את הטעות הזאת שוב... קרה לך פעם?",
    "~z~and disrespectful, so I followed them home and, anyway,": "~z~וחסרי כבוד, אז עקבתי אחריהם הביתה ובכל מקרה,",
    "~z~Man - sometimes I even frighten myself.": "~z~בנאדם - לפעמים אני אפילו מפחיד את עצמי.",
    "~z~What you scared of?": "~z~ממה אתה מפחד?",
    "~z~I mean buildings coming down, explosions and shit, blood raining from the sky.": "~z~אני מתכוון בניינים קורסים, פיצוצים וחרא כזה, דם יורד מהשמיים.",
    "~z~so maybe his is the example to take. But you know, I'm just talking out loud, man. I'm just thinking the shit through.": "~z~אז אולי הדוגמה שלו היא מה שצריך לקחת. אבל אתה יודע, אני רק מדבר בקול רם, בנאדם. אני פשוט חושב על החרא הזה.",
    "~z~because I'm like on the internet, and I got a smartphone. I'm a reboot that's cold, dog.": "~z~כי אני כאילו באינטרנט, ויש לי סמארטפון. אני ריבוט קר, כלב.",
    "~z~You know - it's been complicated.": "~z~אתה יודע - זה היה מסובך.",
    "~z~So what's up homie, how you been?": "~z~אז מה קורה אחי, מה שלומך?",
    "~z~Eh, come on, crazy dude, let's fuck shit up. Yeah.": "~z~אה, קדימה, בחור משוגע, בוא נדפוק דברים. כן.",
    "~z~So, Lamar, I got a question.": "~z~אז, Lamar, יש לי שאלה.",
    "~z~You miss Brad so much, go fucking hang with Brad, leave my ass alone, thank you.": "~z~אתה כל כך מתגעגע לבראד, לך תסתובב עם בראד, עזוב אותי בשקט, תודה.",
    "~z~Bro, are you for real? 'Cause you seem like bit of a pussy.": "~z~אחי, אתה רציני? כי אתה נראה כמו קצת כוסית.",
    "~z~Then I'm your dog, dog.": "~z~אז אני הכלב שלך, כלב.",
    "~z~I'm gonna teach him the problems with a lack of gratitude - me and a blow torch. Fucking wretch.": "~z~אני אלמד אותו את הבעיות של חוסר הכרת תודה - אני והמבער שלי. פאקינג עלוב.",
    "~z~I'm sorry. I'm afraid... I'm afraid of everything. Of everyone.": "~z~אני מצטער. אני מפחד... אני מפחד מהכל. מכולם.",
    "~z~The difference is everything. The difference is about being real, and about being a self-proclaimed buster.": "~z~ההבדל הוא הכל. ההבדל הוא בלהיות אמיתי, ובלהיות שמוק שמכריז על עצמו ככזה.",
    "~z~You don't seem like you got that killer edge, is all. No offense. Nothing to be ashamed of.": "~z~אתה לא נראה שיש לך את היתרון הקטלני הזה, זה הכל. בלי להעליב. אין במה להתבייש.",
    "~z~Nah, nah, nah, bro. You got it all wrong. You know, I ain't getting at yo' ass right now. I mean, you's a good friend.": "~z~לא, לא, לא, אחי. הבנת הכל לא נכון. אתה יודע, אני לא נכנס בך עכשיו. אני מתכוון, אתה חבר טוב.",
    "~z~I dunno, homie. What's happening?": "~z~אני לא יודע, אחי. מה קורה?",
    "~z~Tell you what?": "~z~להגיד לך מה?",
    "~z~Shit, I won't... I mean, that is my nigga, but shit, when he gone, he gone.": "~z~שיט, אני לא... אני מתכוון, זה הניגה שלי, אבל שיט, כשהוא איננו, הוא איננו.",
    "~z~Eh, you know what, T? You're alright, man... you're alright.": "~z~אה, אתה יודע מה, T? אתה בסדר, בנאדם... אתה בסדר.",
    "~z~Holla at your boy, man. Tell me about it.": "~z~דבר עם הבחור שלך, אחי. ספר לי על זה.",
    "~z~Me too... when I realize what I'm thinking.": "~z~גם אני... כשאני מבין מה אני חושב.",
    "~z~If you wanna to be rich and miserable, fuck loyalty. Fuck it in its ass.": "~z~אם אתה רוצה להיות עשיר ואומלל, שתזדיין הנאמנות. תזיין אותה בתחת.",
    "~z~Me too, man. Me too.": "~z~גם אני, אחי. גם אני.",
    "~z~Homie? We're homies now? Now we're homies?": "~z~אחי? אנחנו אחים עכשיו? עכשיו אנחנו אחים?",
    "~z~Well, I am a little upset. I'll try to get over it.": "~z~ובכן, אני קצת עצבני. אני אנסה להתגבר על זה.",
    "~z~What up?": "~z~מה קורה?",
    "~z~Exactly...": "~z~בדיוק...",
    "~z~I'm like a throwback, but like a throwback that couldn't exist in any other time": "~z~אני כמו חזרה לעבר, אבל חזרה לעבר שלא יכלה להתקיים בשום זמן אחר",
    "~z~I was nearly a rapper, but I don't feel like I belong.": "~z~כמעט הייתי ראפר, אבל אני לא מרגיש שייך.",
    "~z~Confused, if I'm honest.": "~z~מבולבל, אם להיות כנה.",
    "~z~Whoa, now you're pushing it. I suggest shutting up.": "~z~וואו, עכשיו אתה מגזים. אני מציע שתשתוק.",
    "~z~But the right kind of asshole?": "~z~אבל הסוג הנכון של חרא?",
    "~z~Peace, love, and tranquility.": "~z~שלום, אהבה, ושלווה.",
    "~z~and sham spirituality. From the way they go on, you'd think it was some zen paradise out here.": "~z~ורוחניות מזויפת. מהדרך שהם מתנהגים, היית חושב שזה איזה גן עדן זן פה.",
    "~z~Not quite, homie,": "~z~לא ממש, אחי,",
    "~z~What you talking about, homie?": "~z~על מה אתה מדבר, אחי?",
    "~z~A ball sack? Oh hell no. You shitting me? Nigga, this Families for life.": "~z~שק אשכים? או לעזאזל לא. אתה צוחק עליי? ניגה, זה Families לחיים.",
    "~z~I don't fucking believe it - man, you ain't got no soul. That's what you should be afraid of...": "~z~אני פאקינג לא מאמין - בנאדם, אין לך נשמה. זה ממה שאתה צריך לפחד...",
    "~z~Have I got what it takes?": "~z~יש לי את מה שצריך?",
    "~z~When I think... When I think about it. I really am...": "~z~כשאני חושב... כשאני חושב על זה. אני באמת...",
    "~z~You the one using them old French-ass words with accents and shit. Forte. Pfft. Nigga, you the pussy.": "~z~אתה זה שמשתמש במילים הצרפתיות הישנות האלה עם מבטאים וחרא. פורטה. פחח. ניגה, אתה הכוסית.",
    "~z~Like an irresistible object and an immovable force, you know. Boom! Nigga, like,": "~z~כמו אובייקט שאי אפשר לעמוד בפניו וכוח שאי אפשר להזיז, אתה יודע. בום! ניגה, כאילו,",
    "~z~But, uh, you ain't in a gang. I'm just saying though, you look a little bit all over the place with that shit, nigga. And you stink.": "~z~אבל, אה, אתה לא בכנופיה. אני רק אומר למרות זאת, אתה נראה קצת מבולגן עם החרא הזה, ניגה. ואתה מסריח.",
    "~z~So tell me, Trevor...": "~z~אז תגיד לי, Trevor...",
    "~z~Is there a voice telling you to kill me right now? A tiny little voice in your head.": "~z~יש קול שאומר לך להרוג אותי עכשיו? קול קטן בראש שלך.",
    "~z~Sure you are, buddy. Sure.": "~z~בטח שאתה, חבר. בטח.",
    "~z~Thanks, Lamar. You're a good friend too.": "~z~תודה, Lamar. גם אתה חבר טוב.",
    "~z~I knew this homie thing might go wrong with you. Anything coming out that mouth just seems creepy as fuck.": "~z~ידעתי שעניין ה'אחי' הזה יכול להשתבש איתך. כל מה שיוצא מהפה הזה פשוט נשמע מצמרר רצח.",
    "~z~No - this shit ain't no femdamine name, nigga - it's my name.": "~z~לא - החרא הזה הוא לא איזה שם נשי, ניגה - זה השם שלי.",
    "~z~I don't want to fight! You my homie. I'm just saying, though, if we did though...": "~z~אני לא רוצה ללכת מכות! אתה אחי. אני רק אומר, למרות זאת, אם כן היינו...",
    "~z~Yeah, okay, fo' sho'. I got you.": "~z~כן, אוקיי, בטוח. הבנתי אותך.",
    "~z~Fo' shiggadale": "~z~פו שיגאדייל (הערה: סלנג ל'בטח')",
    "~z~I always dreamed about rolling with a gang banger.": "~z~תמיד חלמתי להסתובב עם חבר כנופיה.",
    "~z~It's hard when you're all alone in the world - a guy trying to stay true to his principles...": "~z~זה קשה כשאתה לגמרי לבד בעולם - בחור שמנסה להישאר נאמן לעקרונות שלו...",
    "~z~Some people are just born soft.": "~z~יש אנשים שפשוט נולדים רכים.",
    "~z~Nah, man, nah fuck that. If that's the case then I'd rather be broke and angry, just like you.": "~z~לא, בנאדם, לא לעזאזל עם זה. אם זה המצב אז הייתי מעדיף להיות תפרן וכועס, בדיוק כמוך.",
    "~z~I'm one of those crazy cats that the big dogs want to be and bitches want to be with.": "~z~אני אחד מאותם חתולים משוגעים שהכלבים הגדולים רוצים להיות וכלבות רוצות להיות איתם.",
    "~z~I mean your crew are your brothers, without them, you're nothing.": "~z~אני מתכוון שהצוות שלך הם האחים שלך, בלעדיהם, אתה כלום.",
    "~z~Yeah, whatever, nigga.": "~z~כן, מה שתגיד, ניגה.",
    "~z~I mean I want to relate, I really do. But, uhhh...": "~z~אני מתכוון שאני רוצה להזדהות, אני באמת רוצה. אבל, אההה...",
    "~z~Okay. Touched a nerve. Good to know.": "~z~אוקיי. נגעתי בעצב רגיש. טוב לדעת.",
    "~z~two crazy cats in a crazy world.": "~z~שני חתולים משוגעים בעולם משוגע.",
    "~z~I've tried breakdancing, and I'll be honest - it wasn't pretty.": "~z~ניסיתי ברייקדאנס, ואני אהיה כנה - זה לא היה יפה.",
    "~z~But it sound like you and Brad's love ran real deep?": "~z~אבל זה נשמע כאילו האהבה שלך ושל בראד הייתה ממש עמוקה?",
    "~z~Yeah, and I had dreams about creepy-ass serial killers too,": "~z~כן, וגם היו לי חלומות על רוצחים סדרתיים מצמררים,",
    "~z~Cool, well, I think I've got that. So you down with all \"Families\"?": "~z~מגניב, ובכן, אני חושב שהבנתי את זה. אז אתה בעד כל ה\"משפחות\"?",
    "~z~No - ask you. Anyway, are you a Balla?": "~z~לא - שואל אותך. בכל מקרה, אתה באלאס?",
    "~z~The rich phonies, bro. With their yoga mats,": "~z~המזויפים העשירים, אחי. עם מזרני היוגה שלהם,",
    "~z~re-thought that, and realized they were exceedingly rude": "~z~חשבתי על זה שוב, והבנתי שהם היו גסים בצורה יוצאת דופן",
    "~z~While everyone else sells theirs for a new phone, huh?": "~z~בזמן שכל השאר מוכרים את שלהם בשביל טלפון חדש, אה?",
    "~z~Fo' sho' T, holla.": "~z~בטוח T, נדבר.",
    "~z~Man, what kind of a fucked up queston is that, fool? You good homie but, uhh, Chop... Chop is Chop.": "~z~בנאדם, איזו מן שאלה דפוקה זאת, טמבל? אתה אח טוב אבל, אהה, צ'ופ... צ'ופ זה צ'ופ.",
    "~z~Okay, okay, fo sho. You right. But, when y'all niggas finish with him, I'ma stick to his rich ass as tight as I can.": "~z~אוקיי, אוקיי, בטוח. אתה צודק. אבל, כשאתם הניגרים תסיימו איתו, אני אדבק לתחת העשיר שלו כמה שרק אוכל.",
    "~z~I'm not crazy.": "~z~אני לא משוגע.",
    "~z~Will you? Will you feel me?": "~z~תרצה? תרגיש אותי?",
    "~z~Are you trying to tell me something, homie? Are you coming at me?": "~z~אתה מנסה להגיד לי משהו, אחי? אתה בא אליי?",
    "~z~Eh, and I can tell that about you.": "~z~אה, ואני יכול לראות את זה עליך.",
    "~z~Uh huh, yeah, it's talking. It's telling me to kill you.": "~z~אה הא, כן, הוא מדבר. הוא אומר לי להרוג אותך.",
    "~z~Yeah, slash, sure, slash, first and only lesson - loyalty.": "~z~כן, קו נטוי, בטח, קו נטוי, שיעור ראשון ויחיד - נאמנות.",
    "~z~Yeah, seems that way, don't it?": "~z~כן, נראה ככה, לא?",
    "~z~Michael doesn't impart the same value system as me.": "~z~Michael לא מנחיל את אותה מערכת ערכים כמוני.",
    "~z~Tell away.": "~z~דבר.",
    "~z~Breakdancing?": "~z~ברייקדאנס?",
    "~z~I know - I'm a fucking jungle cat, like a panther. I've got this magnetic thing that attracts people.": "~z~אני יודע - אני פאקינג חתול ג'ונגל, כמו פנתר. יש לי את הדבר המגנטי הזה שמושך אנשים.",
    "~z~Don't get creeped out, homie.": "~z~אל תירתע, אחי.",
    "~z~Trevor, man, what's up with your look?": "~z~Trevor, אחי, מה קורה עם המראה שלך?",
    "~z~That's what I told him.": "~z~זה מה שאמרתי לו.",
    "~z~Man, that's cool, but I've got a gang of homies already.": "~z~בנאדם, זה מגניב, אבל כבר יש לי כנופיה של אחים.",
    "~z~Chill, chill, chill, man... he didn't mean it like that.": "~z~תרגע, תרגע, תרגע, בנאדם... הוא לא התכוון לזה ככה.",
    "~z~Man, you going to ruin the motherfucking word for me. Shit.": "~z~בנאדם, אתה הולך להרוס לי את המילה המזדיינת הזאת. שיט.",
    "~z~Isn't that a girl's name? It sounds very feminine.": "~z~זה לא שם של בת? זה נשמע מאוד נשי.",
    "~z~There's no voice telling me to... oh wait. Yeah.": "~z~אין קול שאומר לי ל... או רגע. כן.",
    "~z~I'm happy for you.": "~z~אני שמח בשבילך.",
    "~z~Me and you tussling would be fucking insane. 'Cause we beasts.": "~z~אני ואתה נאבקים יהיה פאקינג מטורף. כי אנחנו חיות.",
    "~z~Nah, nah - most of them assholes. I'm down with my set though,": "~z~לא, לא - רובם חארות. אבל אני סבבה עם הסט שלי,",
    "~z~Yeah, but you act crazy. So, is you crazy? Like hear voices in your head and shit?": "~z~כן, אבל אתה מתנהג כמו משוגע. אז, אתה משוגע? כאילו שומע קולות בראש שלך וחרא כזה?",
    "~z~So, word is you one crazy motherfucker, T.": "~z~אז, שמועות אומרות שאתה חתיכת משוגע, T.",
    "~z~So, you mean like only eating at Burger Shot and not fucking with that Clunking Bell shit?": "~z~אז, אתה מתכוון כאילו רק לאכול בברגר שוט ולא להתעסק עם החרא של קלאקינג בל?",
    "~z~Friends don't mean 'holding' each other...": "~z~חברים זה לא אומר 'להחזיק' אחד את השני...",
    "~z~Hey, I'm glad we're friends.": "~z~היי, אני שמח שאנחנו חברים.",
    "~z~So let me ask you a question, Lamar.": "~z~אז תן לי לשאול אותך שאלה, Lamar.",
    "~z~Well, these people I met in the bar the other day - nice people, or so I thought, but then I": "~z~ובכן, האנשים האלה שפגשתי בבר לפני כמה ימים - אנשים נחמדים, או ככה חשבתי, אבל אז אני",
    "~z~Oh, hell yeah, yeah dude, I'm with that. Loyalty for sure.": "~z~או, לכל הרוחות כן, כן אחי, אני איתך בזה. נאמנות בטוח.",
    "~z~My buddy, Brad, I miss him.": "~z~החבר שלי, בראד, אני מתגעגע אליו.",
    "~z~I feel you, homie.": "~z~אני מרגיש אותך, אחי.",
    "~z~For shiggerdale... good. Good to know. I was keen to graduate from bro to homie.": "~z~פור שיגרדייל (הערה: סלנג)... טוב. טוב לדעת. הייתי להוט לעלות מ'אחי' ל'הומי'.",
    "~z~Fuck you, man - I thought we was getting close. I thought we had an little understanding, you know -": "~z~לך תזדיין, בנאדם - חשבתי שאנחנו מתקרבים. חשבתי שיש לנו קצת הבנה, אתה יודע -",
    "~z~You stink, man, you smell like ass.": "~z~אתה מסריח, אחי, אתה מריח כמו תחת.",
    "~z~Oh, come on, it's all the same. Breakdancing, circle jerks, drive-by molestings - I'm down for all of it.": "~z~או, קדימה, זה הכל אותו דבר. ברייקדאנס, אוננות במעגל, הטרדות תוך כדי נסיעה - אני זורם על הכל.",
    "~z~He did?": "~z~הוא כן?",
    "~z~Can I be a nice gang banger then? If that's what's important...": "~z~אז אני יכול להיות חבר כנופיה נחמד? אם זה מה שחשוב...",
    "~z~Tell me, man, who you hate the most? Like, out of everybody in LS?": "~z~תגיד לי, אחי, את מי אתה שונא הכי הרבה? כאילו, מכולם בלוס סנטוס?",
    "~z~Ah, now I've got you.": "~z~אה, עכשיו הבנתי אותך.",
    "~z~Leroy? It's Lamar, motherfucker.": "~z~לירוי? זה Lamar, בן זונה.",
    "~z~What you mean, my look?": "~z~למה אתה מתכוון, המראה שלי?",
    "~z~Thank you. I like to think so.": "~z~תודה. אני אוהב לחשוב ככה.",
    "~z~Do you love me more than Chop?": "~z~אתה אוהב אותי יותר מ-Chop?",
    "~z~Oh, shit, man, my bad.": "~z~או, שיט, אחי, טעות שלי.",
    "~z~Then how did he mean it, homie? And think before you speak -": "~z~אז לאיזה מובן הוא התכוון, אחי? ותחשוב לפני שאתה מדבר -",
    "~z~That's why I called you - because I'm a fun guy, and you seem like you need a friend.": "~z~בגלל זה התקשרתי אליך - כי אני בחור כיפי, וזה נראה שאתה צריך חבר.",
    "~z~You too, Leroy.": "~z~גם אתה, לירוי.",
    "~z~Some hockey... I wasn't very good at teams. Or coaches, either.": "~z~קצת הוקי... לא הייתי כל כך טוב בקבוצות. או מאמנים, גם כן.",
    "~z~Keeping it one thousand... It's Franklin, homie.": "~z~שומר את זה מאה (הערה: אמיתי)... זה Franklin, אחי.",
    "~z~I'm saying, though, if I ever had to serve you, shit would go down.": "~z~אני רק אומר, אבל, אם אי פעם הייתי צריך להיכנס בך, דברים היו קורים.",
    "~z~So, umm, since you all on this mentorship": "~z~אז, אממ, בגלל שאתה כולך בקטע של חונכות",
    "~z~Well, Frank ain't that good a student if he leaving me on the road to hang with you motherfuckers.": "~z~ובכן, פרנק הוא לא כזה תלמיד טוב אם הוא משאיר אותי על הכביש כדי להסתובב איתכם בני זונות.",
    "~z~Ain't what I heard.": "~z~זה לא מה ששמעתי.",
    "~z~Yeah, real shit.": "~z~כן, חרא אמיתי.",
    "~z~Shit, it is in the movies I see.": "~z~שיט, זה ככה בסרטים שאני רואה.",
    "~z~Absolute nonsense, amigo.": "~z~שטויות מוחלטות, אמיגו.",
    "~z~I'm really afraid. Everyone... leaves.. me... in the end...": "~z~אני באמת מפחד. כולם... עוזבים.. אותי... בסוף...",
    "~z~I'm old school. A dangerous nigga.": "~z~אני מהדור הישן. ניגה מסוכן.",
    "~z~Will you... will you hold me? I want to be held.": "~z~אתה תהיה... אתה תחזיק אותי? אני רוצה שיחזיקו אותי.",
    "~z~I mean the way you dress. You all bummy and scruffy and shit.": "~z~אני מתכוון לדרך שבה אתה מתלבש. אתה נראה כמו איזה הומלס מוזנח וחרא.",
    "~z~Well, don't say that... homie.": "~z~ובכן, אל תגיד את זה... אחי.",
    "~z~Man, I ain't touchy -  it's just you ain't being nice.": "~z~בנאדם, אני לא רגיש - פשוט אתה לא נחמד.",
    "~z~So, let me ask you something.": "~z~אז, תן לי לשאול אותך משהו.",
    "~z~Well, you with me right now, so, uh, enjoy the moment, motherfucker, and don't talk about people who ain't here.": "~z~ובכן, אתה איתי עכשיו, אז, אה, תהנה מהרגע, בן זונה, ואל תדבר על אנשים שלא פה.",
    "~z~I'm scared of... I'm scared of myself. Is that the right answer?": "~z~אני מפחד מ... אני מפחד מעצמי. זאת התשובה הנכונה?",
    "~z~So, uhh, Trevor, I got a question.": "~z~אז, אהה, Trevor, יש לי שאלה.",
    "~z~Fuck shit up? I don't think that's your forte.": "~z~לדפוק דברים? אני לא חושב שזה התחום החזק שלך.",
    "~z~Eh, yeah, me too.": "~z~אה, כן, גם אני.",
    "~z~Preppy gang bangers. What is the world coming to?": "~z~חברי כנופיה צפוניים. לאן העולם מגיע?",
    "~z~Exactly. Assholes, not turds.": "~z~בדיוק. חארות, לא גללים.",
    "~z~I'm serious. I mean, shit, if we ever came at each other, shit would go big.": "~z~אני רציני. אני מתכוון, שיט, אם אי פעם ניכנס אחד בשני, זה יהיה גדול.",
    "~z~Oh, too long, brother.": "~z~או, יותר מדי זמן, אחי.",
    "~z~Yeah, well, I would hang with Brad, but he's gone away.": "~z~כן, ובכן, הייתי מסתובב עם בראד, אבל הוא נעלם.",
    "~z~It's good seeing you, man.": "~z~טוב לראות אותך, אחי.",
    "~z~And you're soft.": "~z~ואתה רך.",
    "~z~No, homie - say what you want.": "~z~לא, אחי - תגיד מה שאתה רוצה.",
    "~z~I'm kind of out there. I'll admit it, nigga, a badass. But, you dude, you straight up crazy.": "~z~אני קצת מטורף. אני אודה בזה, ניגה, קשוח. אבל, אתה אחי, אתה פשוט משוגע.",
    "~z~Shit, you tell me, homie.": "~z~שיט, אתה תגיד לי, אחי.",
    "~z~pull down your pants down and let me touch you like a real man. Man, fuck that, I'm onto you, nigga.": "~z~תוריד את המכנסיים שלך ותן לי לגעת בך כמו גבר אמיתי. בנאדם, לעזאזל עם זה, עליתי עליך, ניגה.",
    "~z~slash role model, slash inspiration tip with the homie Franklin, I was wondering, you know, why don't you give an upancommer the game?": "~z~קו נטוי מודל לחיקוי, קו נטוי טיפ השראה עם האחי Franklin, תהיתי, אתה יודע, למה שלא תלמד איזה מתחיל את העסק?",
    "~z~It's not like that in the movies.": "~z~זה לא ככה בסרטים.",
    "~z~But I'm kind of new in town, so I need more friends with an in.": "~z~אבל אני די חדש בעיר, אז אני צריך עוד חברים מקושרים.",
    "~z~Truth is, stuff gets exaggerated. I'm really a mellow guy, with a very,": "~z~האמת היא, שדברים יוצאים מפרופורציות. אני ממש בחור רגוע, עם סובלנות,",
    "~z~So... It's cool to hang out, man.": "~z~אז... זה מגניב לבלות, אחי.",
    "~z~as there are now lives on the line.": "~z~כי עכשיו יש חיים על כף המאזניים.",
    "~z~Hey, if you hate Ballas, so do I.": "~z~היי, אם אתה שונא Ballas, אז גם אני.",
    "~z~Damn, Trevor, dude, you been here for a while now, right. In LS?": "~z~לעזאזל, Trevor, אחי, אתה כבר פה הרבה זמן, נכון. בלוס סנטוס?",
    "~z~I love that kid.": "~z~אני אוהב את הילד הזה.",
    "~z~What's the difference?": "~z~מה ההבדל?",
    "~z~Pretty much lived a low life kind of existence...": "~z~די חייתי קיום של חיים נמוכים...",
    "~z~Ahh - yeah.": "~z~אהה - כן.",
    "~z~I thought you'd say that.": "~z~חשבתי שתגיד את זה.",
    "~z~Still - it's a stupid thing to do.": "~z~עדיין - זה דבר טיפשי לעשות.",
    "~z~He is a pretty shit part, and that's only 'cause he's in jail.": "~z~הוא חלק די חרא, וזה רק בגלל שהוא בכלא.",
    "~z~Can you please take this seriously?": "~z~אתה יכול בבקשה לקחת את זה ברצינות?",
    "~z~Before you ask,": "~z~לפני שתשאל,",
    "~z~Get in the car - we're gonna check out the front entrance.": "~z~כנס למכונית - אנחנו הולכים לבדוק את הכניסה הקדמית.",
    "~z~Ain't it obvious? Busting Brad outta the clink.": "~z~זה לא מובן מאליו? מבריחים את בראד מהכלא.",
    "~z~Like clockwork, Mikey. Like clockwork.": "~z~כמו שעון, Mikey. כמו שעון.",
    "~z~Hey man, you might not notice it, but I picked up a few things rolling with you.": "~z~היי בנאדם, אולי לא שמת לב, אבל למדתי כמה דברים מלהסתובב איתך.",
    "~z~So gentlemen,": "~z~אז רבותיי,",
    "~z~Pull back! Come on.": "~z~קח אחורה! קדימה.",
    "~z~I respect you enough to be honest.": "~z~אני מכבד אותך מספיק כדי להיות כן.",
    "~z~I'm feeling pretty good. We got Lester planning it - he'll get us options.": "~z~אני מרגיש די טוב. יש לנו את Lester שמתכנן את זה - הוא ישיג לנו אפשרויות.",
    "~z~I ain't even talked to Mike about it yet, but he's gonna be on board, he's obligated.": "~z~אפילו לא דיברתי עם מייק על זה עדיין, אבל הוא יהיה בפנים, הוא מחויב.",
    "~z~I mean, there's times I think I got to be the senior partner in the group -": "~z~אני מתכוון, יש פעמים שאני חושב שאני צריך להיות השותף הבכיר בקבוצה -",
    "~z~Yeah, fucking eerie, ain't it?": "~z~כן, פאקינג מצמרר, לא?",
    "~z~What happened to our new found mutual respect?": "~z~מה קרה לכבוד ההדדי החדש שלנו?",
    "~z~There's a couple of armored cars on a dry run to the Depository - intel suggests they'll be going down": "~z~יש זוג מכוניות משוריינות בנסיעת מבחן למאגר - המודיעין מצביע על כך שהם ייסעו",
    "~z~I mean there were other guys though too,": "~z~אני מתכוון שהיו עוד בחורים גם למרות זאת,",
    "~z~So, you goin' tell me about this Brad dude, and the deal with the FIB? What happened in North Yankton, back in the day, anyway?": "~z~אז, אתה הולך לספר לי על הבחור הזה בראד, והעסקה עם ה-FIB? מה קרה בנורת' ינקטון, בימים ההם, בכל מקרה?",
    "~z~Still, come on, twenty percent of that's a lot of coin for sitting on your fat ass.": "~z~עדיין, נו באמת, עשרים אחוז מזה זה הרבה כסף בשביל לשבת על התחת השמן שלך.",
    "~z~and then do one last big score,": "~z~ואז נעשה מכה אחת גדולה אחרונה,",
    "~z~If it's ever going to, this is the time.": "~z~אם זה אי פעם יקרה, זה הזמן.",
    "~z~Yeah, you know, getting a feel for it - security, exit routes, general vibe.": "~z~כן, אתה יודע, לקבל תחושה של המקום - אבטחה, נתיבי מילוט, אווירה כללית.",
    "~z~Just a minute.": "~z~רק דקה.",
    "~z~I want your help. All twenty percent of two-hundred million of it, actually, man,": "~z~אני רוצה את העזרה שלך. כל עשרים אחוז ממאתיים מיליון מזה, בעצם, אחי,",
    "~z~I'm worried we're not going to make it.": "~z~אני דואג שלא נצליח.",
    "~z~We've still got information to collect. Get back to the excavation.": "~z~עדיין יש לנו מידע לאסוף. תחזור לחפירות.",
    "~z~Then, I'm going to be honest with you. This armored car ploy... it won't work.": "~z~אז, אני הולך להיות כנה איתך. תרגיל המכוניות המשוריינות הזה... הוא לא יעבוד.",
    "~z~I was gonna head that way anyway.": "~z~הייתי בדרך לשם בכל מקרה.",
    "~z~We robbed and lied and we hurt people.": "~z~שדדנו ושיקרנו ופגענו באנשים.",
    "~z~Now, they're gone. Thank you, Trevor!": "~z~עכשיו, הם נעלמו. תודה, Trevor!",
    "~z~You mentioned a job before - something I could help you with.": "~z~הזכרת עבודה קודם - משהו שאוכל לעזור לך בו.",
    "~z~the fridge is broken.": "~z~המקרר מקולקל.",
    "~z~Trevor and I need to map their route for a possible hijack point, so we're going to his airfield in Blaine County,": "~z~Trevor ואני צריכים למפות את המסלול שלהם לנקודת חטיפה אפשרית, אז אנחנו הולכים לשדה התעופה שלו במחוז בליין,",
    "~z~It's important to know how cops behave in the target area... now, we can carry on.": "~z~חשוב לדעת איך שוטרים מתנהגים באזור היעד... עכשיו, אנחנו יכולים להמשיך.",
    "~z~That's the excavation - I need you to hold the chopper above it while I take a look.": "~z~זה החפירות - אני צריך שתחזיק את המסוק מעל זה בזמן שאני מעיף מבט.",
    "~z~Man you'd think they'd put more than one motherfucker": "~z~בנאדם היית חושב שהם ישימו יותר מפאקינג בן אדם אחד",
    "~z~What are you doing? Keep back.": "~z~מה אתה עושה? תישאר מאחור.",
    "~z~We're running out of time.": "~z~נגמר לנו הזמן.",
    "~z~Will he? Yeah, I hope so, man. I hope he holds it together.": "~z~הוא יהיה? כן, אני מקווה, אחי. אני מקווה שהוא יחזיק מעמד.",
    "~z~Had it for ages.": "~z~יש לי את זה שנים.",
    "~z~'Cause I don't remember any specific instances, but it stands to reason I woulda taken advantage of those": "~z~כי אני לא זוכר מקרים ספציפיים, אבל זה הגיוני שהייתי מנצל את ה",
    "~z~there were three guys.": "~z~היו שם שלושה בחורים.",
    "~z~Looks like a normal consumer bank up here.": "~z~נראה כמו בנק צרכנים רגיל למעלה פה.",
    "~z~Don't ask Trevor!": "~z~אל תשאל את Trevor!",
    "~z~This isn't a game. What are you doing?": "~z~זה לא משחק. מה אתה עושה?",
    "~z~It's a long drive, so... you know.": "~z~זאת נסיעה ארוכה, אז... אתה יודע.",
    "~z~I didn't think it was, but now I do.": "~z~לא חשבתי שזה כן, אבל עכשיו כן.",
    "~z~being hunted by government officials,": "~z~להיות ניצודים על ידי פקידי ממשל,",
    "~z~We're in the chopper, heading to the intercept point.": "~z~אנחנו במסוק, בדרך לנקודת היירוט.",
    "~z~Hey the cops gonna connect us to the Union Depository, Huh?": "~z~היי המשטרה הולכת לקשר אותנו ליוניון דפוזיטורי, הא?",
    "~z~I wanna square things away with Merryweather,": "~z~אני רוצה ליישר את ההדורים עם מריוות'ר,",
    "~z~Brad's not a thing - he's part of the crew.": "~z~בראד הוא לא חפץ - הוא חלק מהצוות.",
    "~z~When there ain't an obvious profit in something, you're a hard guy to motivate.": "~z~כשאין רווח ברור במשהו, קשה להניע אותך.",
    "~z~13:30 - we're an hour down, two to go.": "~z~13:30 - עברה לנו שעה, נשארו עוד שעתיים.",
    "~z~What you thinking?": "~z~מה אתה חושב?",
    "~z~If you looking for a tunnel... if I remember, the construction's happening on the north side of the bank.": "~z~אם אתה מחפש מנהרה... אם אני זוכר נכון, הבנייה מתבצעת בצד הצפוני של הבנק.",
    "~z~We've lost them! Perfect!": "~z~איבדנו אותם! מושלם!",
    "~z~Don't get too close.": "~z~אל תתקרב יותר מדי.",
    "~z~Alright. We'll start thinking about the breakout too. Bradley Snider -": "~z~בסדר. אנחנו נתחיל לחשוב גם על הבריחה. בראדלי סניידר -",
    "~z~There's your \"big-ass hole.\" Hover above it while I record what we need.": "~z~הנה ה\"חור הענק\" שלך. רחף מעליו בזמן שאני מקליט את מה שאנחנו צריכים.",
    "~z~I've taken down an armored car -": "~z~כבר הורדתי מכונית משוריינת -",
    "~z~Trevor, how we doing?": "~z~Trevor, מה המצב?",
    "~z~I was thinking Michael - it might appeal to his ego.": "~z~חשבתי על Michael - זה אולי יקסום לאגו שלו.",
    "~z~on our national fucking reserves.": "~z~על הפאקינג רזרבות הלאומיות שלנו.",
    "~z~You think I'm taking down the Union Depository in anything other": "~z~אתה חושב שאני מוריד את היוניון דפוזיטורי במשהו אחר",
    "~z~It looks good - we're lucky these projects take so long.": "~z~זה נראה טוב - יש לנו מזל שהפרויקטים האלה לוקחים כל כך הרבה זמן.",
    "~z~in a faraway place": "~z~במקום רחוק",
    "~z~waiting on a signal from the UD. Won't go out on any other call.": "~z~מחכים לאות מה-UD. לא ייצאו לשום קריאה אחרת.",
    "~z~Leon...": "~z~ליאון...",
    "~z~If we can stop some empty cars in a quiet place, we've got a good chance of taking control.": "~z~אם נוכל לעצור כמה מכוניות ריקות במקום שקט, יש לנו סיכוי טוב להשתלט עליהן.",
    "~z~I've lost sight of them - think they might be in the tunnel.": "~z~איבדתי אותם מהעיניים - חושב שאולי הם במנהרה.",
    "~z~He's changed, alright? He writes now,": "~z~הוא השתנה, בסדר? הוא כותב עכשיו,",
    "~z~A maximum of two hundred million, if I can get the funds diverted, and you can pull it off.": "~z~מקסימום של מאתיים מיליון, אם אני אצליח להסיט את הכספים, ואתם תצליחו לבצע את זה.",
    "~z~Don't screw this up, Michael!": "~z~אל תדפוק את זה, Michael!",
    "~z~What am I saying? We got the perfect guy for it.": "~z~מה אני אומר? יש לנו את הבחור המושלם בשביל זה.",
    "~z~we'll have red flags all over the place.": "~z~יהיו לנו דגלים אדומים בכל מקום.",
    "~z~Just hold the chopper here - you can do that, right?": "~z~רק תחזיק את המסוק כאן - אתה יכול לעשות את זה, נכון?",
    "~z~When does everything go to plan?": "~z~מתי משהו בכלל הולך לפי התוכנית?",
    "~z~So you must know Leon,": "~z~אז אתה בטח מכיר את ליאון,",
    "~z~over active saliva glands.": "~z~בלוטות רוק פעילות מדי.",
    "~z~I don't know if we're going to make it.": "~z~אני לא יודע אם נצליח לעשות את זה.",
    "~z~We want Innocence Boulevard where it goes across the Elysian.": "~z~אנחנו רוצים את אינוסנס שדרות איפה שזה חוצה את אליז'יאן.",
    "~z~Lots of clear space.": "~z~הרבה שטח פתוח.",
    "~z~Trevor. How're you doing?": "~z~Trevor. מה שלומך?",
    "~z~Yeah huh?": "~z~כן אה?",
    "~z~If we take the job, we won't hit a mid afternoon run. We'll choose some cars leaving in the morning, around oh eight hundred.": "~z~אם ניקח את העבודה, לא נפגע במשמרת של אמצע אחר הצהריים. אנחנו נבחר כמה מכוניות שעוזבות בבוקר, בסביבות אפס שמונה מאות.",
    "~z~Point taken.": "~z~הנקודה הובנה.",
    "~z~We could recover the cars. With the right equipment, we'd haul 'em up the side.": "~z~נוכל לחלץ את המכוניות. עם הציוד המתאים, נגרור אותן למעלה מהצד.",
    "~z~Fuck it, I'ma ask Trevor.": "~z~לעזאזל עם זה, אני אשאל את Trevor.",
    "~z~Trevor,": "~z~Trevor,",
    "~z~You want to take down a car carrying bonds, or gold for that matter -": "~z~אתה רוצה להוריד מכונית שמובילה איגרות חוב, או זהב לצורך העניין -",
    "~z~We need to get back - I don't have all the data I need.": "~z~אנחנו צריכים לחזור - אין לי את כל הנתונים שאני צריך.",
    "~z~It's not impossible.": "~z~זה לא בלתי אפשרי.",
    "~z~There's you, a guy I know I can depend on. And then there's Trevor.": "~z~יש אותך, בחור שאני יודע שאני יכול לסמוך עליו. ואז יש את Trevor.",
    "~z~Won't even have to fire a shot... if everything goes to plan.": "~z~לא נצטרך אפילו לירות ירייה אחת... אם הכל ילך לפי התוכנית.",
    "~z~Roger that - looking for a big-ass hole.": "~z~רות עבור - מחפש חור ענק.",
    "~z~We can modify this chopper to carry the weight. But we'd need another one to match.": "~z~אנחנו יכולים לשנות את המסוק הזה כדי שיישא את המשקל. אבל נצטרך עוד אחד שיתאים.",
    "~z~Hey, I was expecting you thirty seconds ago.": "~z~היי, ציפיתי לך לפני שלושים שניות.",
    "~z~They're too far ahead.": "~z~הם רחוקים מדי מקדימה.",
    "~z~I have changed my ways, alright?": "~z~שיניתי את הדרכים שלי, בסדר?",
    "~z~You are in restricted airspace. Divert your course, or you will be shot down!": "~z~אתה במרחב אווירי מוגבל. שנה את המסלול שלך, או שתופל!",
    "~z~That's no good, it's load bearing.": "~z~זה לא טוב, זה קיר תומך.",
    "~z~They know we're on 'em, man!": "~z~הם יודעים שאנחנו עליהם, אחי!",
    "~z~Fine, shit, I was gonna pay you, man.": "~z~בסדר, שיט, התכוונתי לשלם לך, בנאדם.",
    "~z~Alright, fine, you passed the test.": "~z~בסדר, בסדר, עברת את המבחן.",
    "~z~So far, yeah - the security's internal rather than external,": "~z~בינתיים, כן - האבטחה היא פנימית ולא חיצונית,",
    "~z~I'm thinking I don't like being in close proximity to you for extended periods of time,": "~z~אני חושב שאני לא אוהב להיות בקרבתך לפרקי זמן ממושכים,",
    "~z~Think you can handle it without your cane?": "~z~חושב שאתה יכול להסתדר בלי המקל שלך?",
    "~z~I wanna bring you in on the ground floor this time, and that's not a joke about disabled access.": "~z~אני רוצה להכניס אותך בקומת הקרקע הפעם, וזאת לא בדיחה על נגישות נכים.",
    "~z~Talk to Michael, okay? Goodbye.": "~z~תדבר עם Michael, בסדר? להתראות.",
    "~z~There they are, back out in the open. It'll need to be a quick turnaround, but you can take them in there.": "~z~הנה הם, בחזרה בשטח הפתוח. זה יצטרך להיות סיבוב מהיר, אבל אתה יכול לקחת אותם משם.",
    "~z~The Union Depository.": "~z~היוניון דפוזיטורי.",
    "~z~These cars are due at 1530. When it's not a dry run, we'll probably take an earlier shift - maybe oh eigh hundred.": "~z~המכוניות האלו אמורות להגיע ב-1530. כשזו לא נסיעת מבחן, אנחנו כנראה ניקח משמרת מוקדמת יותר - אולי אפס שמונה מאות.",
    "~z~and coming back in his chopper to intercept. Michael, Franklin -": "~z~וחוזר במסוק שלו כדי ליירט. Michael, Franklin -",
    "~z~Come in, Michael. We have a visual on the convoy.": "~z~Michael, עבור. יש לנו קשר עין על השיירה.",
    "~z~Tell that to the traffic.": "~z~תגיד את זה לפקקים.",
    "~z~And Brad.": "~z~ובראד.",
    "~z~It's too open, there's a number of get outs, and we'd be compromised if they were driven off the road into the river.": "~z~זה פתוח מדי, יש כמה נתיבי מילוט, ואנחנו ניחשף אם הם ייסעו מחוץ לכביש לתוך הנהר.",
    "~z~No, seriously. A big job, payment up front.": "~z~לא, ברצינות. עבודה גדולה, תשלום מראש.",
    "~z~T, L - we're coming up to the front of the bank.": "~z~T, L - אנחנו מתקרבים לחזית של הבנק.",
    "~z~Alright, we're here - only one security guard.": "~z~בסדר, אנחנו כאן - רק שומר אחד.",
    "~z~Yeah, right, whatever.": "~z~כן, נכון, מה שתגיד.",
    "~z~I'm guessing we don't want the cops along on this?": "~z~אני מנחש שאנחנו לא רוצים את המשטרה בעסק הזה?",
    "~z~Yeah I'm done with that crazy shit, alright?": "~z~כן סיימתי עם החרא המשוגע הזה, בסדר?",
    "~z~Argh! This thing is blown!": "~z~ארר! הדבר הזה נהרס!",
    "~z~They call it a wasting disease 'cause you waste people's time? Move it.": "~z~קוראים לזה מחלה מנוונת כי אתה מבזבז לאנשים את הזמן? תזוז.",
    "~z~Keep with 'em, T. Do whatever Lest needs you to do.": "~z~תישאר איתם, T. תעשה כל מה ש-Lest צריך שתעשה.",
    "~z~A little longer.": "~z~עוד קצת.",
    "~z~It'll be my...": "~z~זה יהיה ה...",
    "~z~Talk to Michael, then come back to me.": "~z~דבר עם Michael, ואז תחזור אליי.",
    "~z~looks like they'd be able to lock this whole place down if they needed to -": "~z~נראה שהם יוכלו לנעול את כל המקום הזה אם הם יצטרכו -",
    "~z~Alright, I think I've got enough information to work with.": "~z~בסדר, אני חושב שיש לי מספיק מידע לעבוד איתו.",
    "~z~Anyway, if we want to hit the vault in a way that people will notice the key will be to divert the security team.": "~z~בכל מקרה, אם אנחנו רוצים לפגוע בכספת בדרך שאנשים ישימו לב אליה המפתח יהיה להסיח את דעת צוות האבטחה.",
    "~z~Get where I can see the route.": "~z~תגיע לאיפה שאני יכול לראות את המסלול.",
    "~z~No, it.. ah... won't. We're looking for somewhere with cover for us, and no escape routes for them.": "~z~לא, זה.. אה... לא יעזור. אנחנו מחפשים מקום עם מחסה בשבילנו, ובלי דרכי מילוט בשבילם.",
    "~z~Look dog,": "~z~תראה כלב,",
    "~z~You know what, I met Amanda, and I know who scares me the most.": "~z~אתה יודע מה, פגשתי את אמנדה, ואני יודע מי מפחיד אותי הכי הרבה.",
    "~z~So there's that.": "~z~אז יש את זה.",
    "~z~Murietta Heights - Innocence Boulevard where it goes over the Elysian.": "~z~מוריאטה הייטס - שדרות אינוסנס איפה שזה עובר מעל האליז'יאן.",
    "~z~Come in, you there? Alright, we're on a strict schedule.": "~z~עבור, אתה שם? בסדר, אנחנו בלוח זמנים צפוף.",
    "~z~I'd like to confirm that they've come out of the tunnel.": "~z~הייתי רוצה לאשר שהם יצאו מהמנהרה.",
    "~z~It's complicated, alright?": "~z~זה מסובך, בסדר?",
    "~z~it's a standard bank,  it's getting underground that's hard.": "~z~זה בנק סטנדרטי, לרדת למתחת לאדמה זה הקטע הקשה.",
    "~z~Shit, we didn't make it in time!": "~z~שיט, לא הספקנו בזמן!",
    "~z~We need to maintain visual contact with the cars.": "~z~אנחנו צריכים לשמור על קשר עין עם המכוניות.",
    "~z~Yeah, Trevor'll get it done.": "~z~כן, Trevor יעשה את זה.",
    "~z~happy.": "~z~שמח.",
    "~z~That should hold some weight.": "~z~זה אמור להחזיק קצת משקל.",
    "~z~and Lester.": "~z~ו-Lester.",
    "~z~If the armored cars are a viable option - we'll bring out the gold in them. Simple.": "~z~אם המכוניות המשוריינות הן אפשרות מעשית - נוציא את הזהב בתוכן. פשוט.",
    "~z~we're not getting in and outta there unless they want us to.": "~z~אנחנו לא ניכנס ונצא משם אלא אם כן הם ירצו שאנחנו ניכנס ונצא.",
    "~z~Charming. Again you've got me confused with Brad.": "~z~מקסים. שוב בלבלת אותי עם בראד.",
    "~z~Yeah, I don't know why I didn't think of it before.": "~z~כן, אני לא יודע למה לא חשבתי על זה קודם.",
    "~z~Sounds hopeful to me - you got a backup plan?": "~z~נשמע לי מבטיח - יש לך תוכנית גיבוי?",
    "~z~Eh..We... ah... taking the temperature?": "~z~אה.. אנחנו... אה... בודקים את הדופק?",
    "~z~Right on time.": "~z~בדיוק בזמן.",
    "~z~Onion eighty-six in sight.": "~z~אוניון שמונים ושש בטווח ראייה.",
    "~z~We're mapping the route, and finding an ambush point - stay with them.": "~z~אנחנו ממפים את המסלול, ומוצאים נקודת מארב - תישאר איתם.",
    "~z~A'ight. Holla at me.": "~z~סבבה. דבר איתי.",
    "~z~You're the one who keeps talking about the schedule, Lest. Come on.": "~z~אתה זה שממשיך לדבר על לוח הזמנים, Lest. קדימה.",
    "~z~Attention, aircraft. This airspace is prohibited. Reverse course now.": "~z~שים לב, כלי טיס. המרחב האווירי הזה אסור. שנה מסלול עכשיו.",
    "~z~Is it too much to ask for a little respect? Just a little? 'Cause I respect you, Trevor.": "~z~זה יותר מדי לבקש קצת כבוד? רק קצת? כי אני מכבד אותך, Trevor.",
    "~z~You see the time!? We didn't make it!": "~z~אתה רואה מה השעה!? לא הספקנו!",
    "~z~Take us around the building, and find the construction site.": "~z~קח אותנו מסביב לבניין, ותמצא את אתר הבנייה.",
    "~z~We'll spend the rest of our lives": "~z~אנחנו נבלה את שארית חיינו",
    "~z~light again man.": "~z~קל שוב אחי.",
    "~z~If they see the TP Enterprises chopper acting weird, this thing'll be blown.": "~z~אם הם יראו את המסוק של TP תעשיות מתנהג מוזר, הדבר הזה יתפוצץ (הערה: נחשף).",
    "~z~I think I've got everything I need to make some plans.": "~z~אני חושב שיש לי כל מה שאני צריך כדי לעשות קצת תוכניות.",
    "~z~Yeah, they were carrying bonds, and we had to smash 'em off the road, and blow the doors to get access.": "~z~כן, הם נשאו איגרות חוב, והיינו צריכים להעיף אותם מהכביש, ולפוצץ את הדלתות כדי לקבל גישה.",
    "~z~I'm picking up the cars.": "~z~אני קולט את המכוניות.",
    "~z~We'll be fine.": "~z~יהיה בסדר.",
    "~z~Well, a crew's more than the sum of its parts, and he was a pretty shit part.": "~z~ובכן, צוות הוא יותר מסך כל חלקיו, והוא היה חלק די חרא.",
    "~z~I never did anything like that in the old days. You must have got me confused - maybe with Brad.": "~z~אף פעם לא עשיתי דבר כזה בימים ההם. בטח התבלבלת ביני לבין מישהו - אולי עם בראד.",
    "~z~intel suggests they'll be going down Innocence Boulevard in East LS.": "~z~המודיעין מצביע על כך שהם ייסעו בשדרות אינוסנס במזרח לוס סנטוס.",
    "~z~sure,": "~z~בטח,",
    "~z~We're going down to the back entrance, see where the gold comes out.": "~z~אנחנו יורדים לכניסה האחורית, לראות מאיפה הזהב יוצא.",
    "~z~Looks steady enough on that bedrock.": "~z~נראה יציב מספיק על סלע האם הזה.",
    "~z~Okay, they'll be back out in the open now. It will have to be a quick turn around, but you can hijack the trucks in there.": "~z~אוקיי, הם יהיו בחזרה בשטח פתוח עכשיו. זה יצטרך להיות סיבוב מהיר, אבל אתה יכול לחטוף את המשאיות שם.",
    "~z~The old days were a long, long time ago but certain horrors I wouldn't be able to block out.": "~z~הימים הישנים היו לפני המון זמן אבל זוועות מסוימות לא הייתי יכול לחסום.",
    "~z~So how'd you come by this place anyway?": "~z~אז איך הגעת למקום הזה בכלל?",
    "~z~Around two hundred million in gold bricks, all taken from kindly Uncle Sam.": "~z~בסביבות מאתיים מיליון במטילי זהב, כולם נלקחו מהדוד סם האדיב.",
    "~z~Okay, I'll take Frank back home.": "~z~אוקיי, אני אקח את פרנק חזרה הביתה.",
    "~z~When he's got something, Lester'll be in touch.": "~z~כשיש לו משהו, Lester יהיה בקשר.",
    "~z~It would be good to confirm their exit from the tunnel.": "~z~יהיה טוב לאשר את היציאה שלהם מהמנהרה.",
    "~z~You are flying in restricted airspace. Turn around immediately!": "~z~אתה טס במרחב אווירי מוגבל. הסתובב מיד!",
    "~z~What those two don't know is, there's a special team of cops on standby twenty four seven,": "~z~מה שהשניים האלה לא יודעים זה, שיש צוות מיוחד של שוטרים בכוננות עשרים וארבע שבע,",
    "~z~They're doing construction down there... but it ain't a tunnel excavation. We'll keep looking.": "~z~הם עושים שם עבודות בנייה... אבל זה לא חפירת מנהרה. נמשיך לחפש.",
    "~z~Okay, good work.": "~z~אוקיי, עבודה טובה.",
    "~z~Divert it? You said they hold out for calls from the UD, and that's it.": "~z~להסיט את זה? אמרת שהם מחכים לקריאות מה-UD, וזהו.",
    "~z~I will, but I got to talk you, too. You're planning this.": "~z~אני אעשה את זה, אבל אני חייב לדבר גם איתך. אתה מתכנן את זה.",
    "~z~A central station is monitoring the cars' positions - if the GPS tracker reads it's down there in the channel -": "~z~תחנה מרכזית מנטרת את המיקומים של המכוניות - אם מעקב ה-GPS מראה שזה שם למטה בערוץ -",
    "~z~I was hoping they'd come through here. This tunnel would work for a switch - they go in, you come out.": "~z~קיוויתי שהם יעברו דרך כאן. המנהרה הזאת יכולה לעבוד בשביל החלפה - הם נכנסים, אתה יוצא.",
    "~z~a Mexican gang, some Chinese gangsters, and a private army, okay?": "~z~כנופיה מקסיקנית, קצת גנגסטרים סינים, וצבא פרטי, אוקיי?",
    "~z~Hey, it, ahh, it looks like we're gonna need some IDs to get in the building this way -": "~z~היי, זה, אהה, נראה שנצטרך תעודות מזהות כדי להיכנס לבניין בדרך הזאת -",
    "~z~Fuck. Killed his cousin, he might as well have a good time.": "~z~לעזאזל. הרג את בן דודו, עדיף שהוא לפחות יעשה חיים.",
    "~z~Steady now.": "~z~יציב עכשיו.",
    "~z~What is the big one?": "~z~מהו הגדול?",
    "~z~That's the twenty percent of two hundred million dollar question.": "~z~זאת שאלת העשרים אחוז של מאתיים מיליון דולר.",
    "~z~We're down on Alta street - coming up on the back of the bank.": "~z~אנחנו למטה ברחוב אלטה - מתקרבים לחלק האחורי של הבנק.",
    "~z~he's getting bored.": "~z~הוא משתעמם.",
    "~z~Aint that where the metal's kept?": "~z~זה לא איפה שהמתכת נשמרת?",
    "~z~Bust Brad out of prison,": "~z~להבריח את בראד מהכלא,",
    "~z~Yeah, but you just pissed off the FIB, and the IAA, and your family, man.": "~z~כן, אבל רק עכשיו עיצבנת את ה-FIB, וה-IAA, והמשפחה שלך, בנאדם.",
    "~z~Now, if I remember from planning the Jewel Store Job, they're excavating the new LS metro tunnel around here.": "~z~עכשיו, אם אני זוכר מהתכנון של שוד חנות התכשיטים, הם חופרים את המנהרה החדשה של המטרו בלוס סנטוס באזור הזה.",
    "~z~than a chopper with my name on it, well then, you don't know me, bro.": "~z~ממסוק עם השם שלי עליו, ובכן אז, אתה לא מכיר אותי, אחי.",
    "~z~Yeah, I heard about that. They were carrying bonds, weren't they?": "~z~כן, שמעתי על זה. הם נשאו איגרות חוב, לא?",
    "~z~We're here - there's a guard on the door, I don't know what's behind him -": "~z~אנחנו פה - יש שומר בדלת, אני לא יודע מה יש מאחוריו -",
    "~z~Yeah, it still ain't fully been explained to me though.": "~z~כן, זה עדיין לא הוסבר לי לגמרי למרות זאת.",
    "~z~We need to be closer!": "~z~אנחנו צריכים להיות קרובים יותר!",
    "~z~You've written your company name on the side of the chopper. Cops won't have trouble finding us if this goes wrong.": "~z~כתבת את שם החברה שלך על הצד של המסוק. לשוטרים לא תהיה בעיה למצוא אותנו אם זה ישתבש.",
    "~z~What kind of ambush spot are we looking for?": "~z~איזה סוג של נקודת מארב אנחנו מחפשים?",
    "~z~Here's some construction. Ah, wait. This ain't the metro tunnel. We'll keep looking.": "~z~הנה קצת עבודות בנייה. אה, רגע. זאת לא מנהרת המטרו. נמשיך לחפש.",
    "~z~one thing and one thing only...": "~z~דבר אחד ודבר אחד בלבד...",
    "~z~Getting paid to do nothing, and spying on innocent people.": "~z~לקבל כסף על לעשות כלום, ולרגל אחרי אנשים תמימים.",
    "~z~Okay, I'll get closer for you.": "~z~אוקיי, אני אתקרב בשבילך.",
    "~z~There's the entrance, I'll pull up.": "~z~הנה הכניסה, אני אעצור.",
    "~z~but!": "~z~אבל!",
    "~z~find some gainful employment.": "~z~נמצא איזו עבודה רווחית.",
    "~z~The big one.~c~~n~The big one!": "~z~הגדול.~c~~n~הגדול!",
    "~z~Hmmm. Really? You sure?": "~z~המממ. באמת? אתה בטוח?",
    "~z~Brad was there sometimes as well.": "~z~בראד היה שם לפעמים גם.",
    "~z~Innocence Boulevard in East LS at approximately fifteen thirty.": "~z~שדרות אינוסנס במזרח לוס סנטוס בערך ב-15:30.",
    "~z~and then you know...": "~z~ואז אתה יודע...",
    "~z~A long, long time ago": "~z~מזמן, מזמן",
    "~z~Why don't you talk to Michael about it?": "~z~למה שלא תדבר עם Michael על זה?",
    "~z~Don't mess around - get to it!": "~z~אל תתעסק - תתחיל עם זה!",
    "~z~Hover above, so I can shoot down into it.": "~z~רחף מעל, כדי שאוכל לצלם למטה לתוכו.",
    "~z~Looks good, looks good.": "~z~נראה טוב, נראה טוב.",
    "~z~You think you can manage that?": "~z~אתה חושב שאתה יכול להתמודד עם זה?",
    "~z~Stand by.": "~z~היכון.",
    "~z~I'm gonna run this,": "~z~אני אנהל את זה,",
    "~z~Man security looks light. We send in a couple a sprung niggas - clap clap.": "~z~בנאדם האבטחה נראית קלה. נשלח איזה שני ניגרים קופצניים - מחיאות כפיים.",
    "~z~I can think of a few uses for you, you chubby little ball of fun.": "~z~אני יכול לחשוב על כמה שימושים בשבילך, כדור כיף קטן ושמנמן.",
    "~z~They do, so we'd have to hit it twice - once to distract 'em, and once to get it done.": "~z~הם כן, אז נצטרך לפגוע בו פעמיים - פעם אחת כדי להסיח את דעתם, ופעם אחת כדי לעשות את העבודה.",
    "~z~Yeah, well, I ain't pissed off hillbillies, bikers,": "~z~כן, ובכן, לא עצבנתי רדנקס, אופנוענים,",
    "~z~but always dreaming of": "~z~אבל תמיד חולם על",
    "~z~and get out there and": "~z~ולצאת לשם ו",
    "~z~Do you want to take down the Union depository, or not?": "~z~אתה רוצה להוריד את היוניון דפוזיטורי, או לא?",
    "~z~Be careful not to get too close to the prison - we'll trip an alarm.": "~z~תיזהר לא להתקרב יותר מדי לכלא - אנחנו נפעיל אזעקה.",
    "~z~I have changed my ways alright.": "~z~שיניתי את דרכיי בסדר.",
    "~z~Alright, I'm going to drop Frank at his place.": "~z~בסדר, אני הולך להוריד את פרנק אצלו.",
    "~z~if we live through the attempt,": "~z~אם נישאר בחיים אחרי הניסיון,",
    "~z~We're mapping their route - that means we need to get where we can see them.": "~z~אנחנו ממפים את המסלול שלהם - זה אומר שאנחנו צריכים להגיע לאיפה שנוכל לראות אותם.",
    "~z~I'm assuming that's doable, Lest.": "~z~אני מניח שזה אפשרי, Lest.",
    "~z~is the big one.": "~z~הוא הגדול.",
    "~z~Hold it.": "~z~תחזיק את זה.",
    "~z~We're on a schedule, bro!": "~z~אנחנו בלוח זמנים, אחי!",
    "~z~So what's goin' on here?": "~z~אז מה קורה פה?",
    "~z~Get to work, you idiot!": "~z~תתחיל לעבוד, יא אידיוט!",
    "~z~Hold here.": "~z~תחזיק פה.",
    "~z~I don't know. What?": "~z~אני לא יודע. מה?",
    "~z~tax dollars for doing nothing. Oh yeah, that and spying on innocent people.": "~z~כספי מיסים על כלום. או כן, זה ולרגל אחרי אנשים תמימים.",
    "~z~Pull back.": "~z~קח אחורה.",
    "~z~Strangely, I do. I can see how you're useful. Terrifying, but useful.": "~z~באופן מוזר, אני כן. אני יכול לראות איך אתה מועיל. מפחיד, אבל מועיל."
}

import json
with open("current_batch.json", "r", encoding="utf-8") as f:
    original = json.load(f)

for k in data:
    if k in original:
        original[k] = data[k]

with open("current_batch.json", "w", encoding="utf-8") as f:
    json.dump(original, f, ensure_ascii=False, indent=4)
