import json

data = {
    "~z~Those two clowns...": "~z~שני הליצנים האלה...",
    "~z~That whole thing about me \"cruising\" has been totally blown out of proportion. The photos are misleading.": "~z~כל הקטע הזה שאני \"מפטרל/מחפש\" יצא לגמרי מפרופורציה. התמונות מטעות.",
    "~z~All units be advised, we have a possible joy rider heading west on Hawick in a black Z-Type.": "~z~לידיעת כל היחידות, יש לנו נהג פרוע אפשרי שנוסע מערבה בהאוויק ב-Z-Type שחורה.",
    "~z~Get him!": "~z~תפסו אותו!",
    "~z~You a professional fuckup.": "~z~אתה דפוק מקצועי.",
    "~z~Suspect is... umm... let me get back to you, okay?": "~z~החשוד הוא... אהמ... תן לי לחזור אליך, אוקיי?",
    "~z~Total dick!": "~z~חרא טוטאלי!",
    "~z~The Z-Type? Mr. Weston will be glad you caught us, he wanted to see it before we took off.": "~z~ה-Z-Type? מר ווסטון ישמח שתפסת אותנו, הוא רצה לראות את זה לפני שהמראנו.",
    "~z~I'm an idiot, you know? Shit.": "~z~אני אידיוט, אתה יודע? שיט.",
    "~z~We have a visual on the suspect going west on Eastbourne.": "~z~יש לנו קשר עין עם החשוד נוסע מערבה באיסטבורן.",
    "~z~Time was, every garage was a pickup joint.": "~z~פעם, כל מוסך היה מקום פיקאפ (הכרויות).",
    "~z~Err, shit, like ten?": "~z~אה, שיט, איזה עשר?",
    "~z~Nothing like a middle-aged throat fuck in a dingy back alley to prove romance ain't dead.": "~z~אין כמו זיון גרון של אדם בגיל העמידה בסמטה אחורית אפלולית כדי להוכיח שהרומנטיקה לא מתה.",
    "~z~This isn't the one.": "~z~זה לא האחד.",
    "~z~Hey, keep looking, bro. Where is he?": "~z~היי, תמשיך לחפש, אחי. איפה הוא?",
    "~z~I'm just going to get out of your way.": "~z~אני פשוט אזוז לך מהדרך.",
    "~z~Don't know what he doing here, but he ain't him, homie.": "~z~לא יודע מה הוא עושה פה, אבל זה לא הוא, אחי.",
    "~z~One more word outta you!": "~z~עוד מילה אחת ממך!",
    "~z~Look, please. We've come so far in the last two decades.": "~z~תראה, בבקשה. הגענו כל כך רחוק בשני העשורים האחרונים.",
    "~z~Hey, where this fuckin' asshole at?": "~z~היי, איפה החרא המזדיין הזה נמצא?",
    "~z~Man, I ain't gonna be a part of that.": "~z~בנאדם, אני לא הולך להיות חלק מזה.",
    "~z~No, not like ten, man.": "~z~לא, לא איזה עשר, בנאדם.",
    "~z~If you target them, the scanner accesses the database, and pulls their record.": "~z~אם אתה מתמקד בהם, הסורק ניגש למאגר הנתונים, ושולף את התיק שלהם.",
    "~z~You can use the sticks to move the camera, zoom in and out.": "~z~אתה יכול להשתמש בג'ויסטיקים כדי להזיז את המצלמה, לעשות זום פנימה והחוצה.",
    "~z~They are a full core meltdown,": "~z~הם היתוך ליבה מלא,",
    "~z~Right, right, right.": "~z~נכון, נכון, נכון.",
    "~z~Take me, right?": "~z~תפסו אותי, נכון?",
    "~z~Hey, I'm supposed to meet Devin Weston here...": "~z~היי, אני אמור לפגוש את דווין ווסטון כאן...",
    "~z~I didn't kill your dog. That wasn't me.": "~z~לא הרגתי את הכלב שלך. זה לא הייתי אני.",
    "~z~I mean, that car's a bit flashy for my taste.": "~z~אני מתכוון, המכונית הזאת קצת נוצצת מדי לטעמי.",
    "~z~Del Perro side of the lot, there's a man by a car.": "~z~בצד של דל פרו במגרש, יש איש ליד מכונית.",
    "~z~Hey, you my eye up there, man. Come on.": "~z~היי, אתה העיניים שלי שם למעלה, בנאדם. קדימה.",
    "~z~Now we got that clear, you need to know we're looking for a high value automobile.": "~z~עכשיו כשהבהרנו את זה, אתה צריך לדעת שאנחנו מחפשים רכב בעל ערך גבוה.",
    "~z~Hey, that's the motherfucker. Thank you, Trevor Philips.": "~z~היי, זה הבן זונה. תודה לך, טרבור פיליפס.",
    "~z~Car owner is still out there.": "~z~בעל המכונית עדיין בחוץ שם.",
    "~z~Good boy.": "~z~ילד טוב.",
    "~z~Umm. You can toggle to thermal vision if you think that would help.": "~z~אהמ. אתה יכול לעבור לראייה תרמית אם אתה חושב שזה יעזור.",
    "~z~You make me sick!": "~z~אתה מגעיל אותי!",
    "~z~Man, I ain't hitting on nobody for you, man, least of all her.": "~z~בנאדם, אני לא מתחיל עם אף אחת בשבילך, בנאדם, בטח שלא איתה.",
    "~z~I mean, I've had millions and I've lost them. Not, like, lost them at the track, or spent 'em on mink coats, I mean actually": "~z~אני מתכוון, היו לי מיליונים ואיבדתי אותם. לא, כאילו, איבדתי במסלול המרוצים, או בזבזתי על מעילי מינק, אני מתכוון ממש",
    "~z~Knock his brains out!": "~z~תעיף לו את המוח החוצה!",
    "~z~The car is cutting through a parking lot. Heading toward Eastbourne.": "~z~המכונית חותכת דרך חניון. לכיוון איסטבורן.",
    "~z~We got to keep looking.": "~z~אנחנו חייבים להמשיך לחפש.",
    "~z~What else you got?": "~z~מה עוד יש לך?",
    "~z~No more banging the snitches, buddy. Come on.": "~z~אין יותר לזיין את המלשינות (Snitches), חבר. קדימה.",
    "~z~I was told you were a professional.": "~z~אמרו לי שאתה מקצוען.",
    "~z~Well, let's see what the fuck he doing.": "~z~ובכן, בוא נראה מה לעזאזל הוא עושה.",
    "~z~Gimme just one more minute.": "~z~תן לי רק עוד דקה אחת.",
    "~z~It's okay, boy. You want a sedative?": "~z~זה בסדר, ילד. אתה רוצה הרגעה?",
    "~z~I think you need some help.": "~z~אני חושב שאתה צריך קצת עזרה.",
    "~z~Out the way, you bag of worms.": "~z~זוז מהדרך, שק של תולעים.",
    "~z~I think your guy's back around that way.": "~z~אני חושב שהבחור שלך חזר לכיוון ההוא.",
    "~z~they are the worst kind of disaster that can ever come down.": "~z~הן סוג האסון הגרוע ביותר שיכול אי פעם לרדת.",
    "~z~Haven't found him.": "~z~עדיין לא מצאנו אותו.",
    "~z~Ohhh! Chad, that was close.": "~z~אווו! צ'אד, זה היה קרוב.",
    "~z~Suspect continues west on Del Perro.": "~z~החשוד ממשיך מערבה בדל פרו.",
    "~z~Shit. Okay. I'll find him. I'll find him.": "~z~שיט. אוקיי. אני אמצא אותו. אני אמצא אותו.",
    "~z~Handle with care!": "~z~טפל בזהירות!",
    "~z~It'll pick up pedestrians carrying the 2012 SA state license.": "~z~זה יקלוט הולכי רגל שנושאים רישיון מדינת סן אנדראס משנת 2012.",
    "~z~Okay. Booting up.": "~z~אוקיי. מאתחל.",
    "~z~Man, it usually takes a rocket launcher to lose a chopper, bro. Where the fuck is he?": "~z~בנאדם, בדרך כלל צריך משגר רקטות כדי לאבד מסוק, אחי. איפה לעזאזל הוא?",
    "~z~You wanna bullshit me, you can bullshit the freeway!": "~z~אתה רוצה לזבל לי במוח, אתה יכול לזבל לכביש המהיר!",
    "~z~Oh. Oh, right. Uhh, the helipad is on the roof.": "~z~או. או, נכון. אהה, מנחת המסוקים נמצא על הגג.",
    "~z~You look like my Grandma did in 1920.": "~z~את נראית כמו שסבתא שלי נראתה ב-1920.",
    "~z~Bringing it back around.": "~z~עושה סיבוב חוזר.",
    "~z~Man, I'll just stick to driving, alright?": "~z~בנאדם, אני פשוט אשאר עם הנהיגה, בסדר?",
    "~z~Why'd she get a boob job if she didn't want me looking?": "~z~למה היא עשתה הגדלת חזה אם היא לא רצתה שאסתכל?",
    "~z~physically lost them. I don't know where they are. My outgoings aren't that high.": "~z~פיזית איבדתי אותם. אני לא יודע איפה הם. ההוצאות שלי לא כל כך גבוהות.",
    "~z~Give us the word and we're GTG.": "~z~תן לנו את המילה ואנחנו מוכנים (GTG).",
    "~z~Rip his cock off!": "~z~תקרע לו את הזין!",
    "~z~No stool yet. Dogs with borderline personality disorder are meant to take longer.": "~z~עדיין אין צואה (Stool). כלבים עם הפרעת אישיות גבולית אמורים לקחת יותר זמן.",
    "~z~Come in, Franklin. We are in position over Hawick Avenue. What's the name of the suspect?": "~z~כנס, פרנקלין. אנחנו בעמדה מעל שדרת האוויק. מה השם של החשוד?",
    "~z~Who we got over by the oil derricks? My man, I'll give him a scan.": "~z~את מי יש לנו שם ליד מגדלי הקידוח? האיש שלי, אני אתן לו סריקה.",
    "~z~What's wrong with you?": "~z~מה הבעיה שלך?",
    "~z~Suspect has spun out outside the Rockford Hills Police Department.": "~z~החשוד הסתחרר (Spun out) מחוץ לתחנת המשטרה של רוקפורד הילס.",
    "~z~Pilot boy. Take us down. I need to see inside the building.": "~z~ילד טייס. קח אותנו למטה. אני צריך לראות בתוך הבניין.",
    "~z~Far side of the garage... to my right... guy by the hood of his car.": "~z~בצד הרחוק של המוסך... לימיני... בחור ליד מכסה המנוע של המכונית שלו.",
    "~z~You gone crazy. I knew you wasn't cut out for this game.": "~z~השתגעת. ידעתי שאתה לא מתאים למשחק הזה.",
    "~z~We gotta call the cops.": "~z~אנחנו צריכים להתקשר למשטרה.",
    "~z~Stupid boxes!": "~z~קופסאות מטופשות!",
    "~z~I'm playing tennis tomorrow.": "~z~אני משחק טניס מחר.",
    "~z~I told you, I needed something.": "~z~אמרתי לך, הייתי צריך משהו.",
    "~z~Just take any car and go!": "~z~פשוט קח כל מכונית וסע!",
    "~z~Where we headed?": "~z~לאן אנחנו פונים?",
    "~z~Okay... no... wait... come back...": "~z~אוקיי... לא... חכה... תחזור...",
    "~z~No, no, no, no, no.": "~z~לא, לא, לא, לא, לא.",
    "~z~Car maintains a westward trajectory on Del Perro Boulevard.": "~z~המכונית שומרת על מסלול מערבה בשדרות דל פרו.",
    "~z~I know you might think this car might be worth something, but, it ain't got resale. Zilch.": "~z~אני יודע שאולי תחשוב שהמכונית הזאת שווה משהו, אבל, אין לה ערך מכירה חוזרת (Resale). כלום (Zilch).",
    "~z~Eh, Molly, right? I got that car for y'all.": "~z~אה, מולי, נכון? השגתי לכם את המכונית הזאת.",
    "~z~Man in his car to my right. Looks like he's on the phone.": "~z~איש במכונית שלו לימיני. נראה שהוא בטלפון.",
    "~z~The search continues.": "~z~החיפוש נמשך.",
    "~z~I'm reading you.": "~z~אני שומע אותך (Reading you).",
    "~z~Not my baby! No! No! Not my baby!": "~z~לא התינוקת שלי (מכונית)! לא! לא! לא התינוקת שלי!",
    "~z~Come on, you dick.": "~z~קדימה, יא חרא.",
    "~z~Sure.": "~z~בטח.",
    "~z~Hey, loose ends. You want to be a professional.": "~z~היי, קצוות פתוחים. אתה רוצה להיות מקצוען.",
    "~z~You see him?": "~z~אתה רואה אותו?",
    "~z~Have a great day.": "~z~שיהיה לך יום נהדר.",
    "~z~Nice! Great. You've upset him.": "~z~יפה! נהדר. הרגזת אותו.",
    "~z~His psychotherapist says it goes back to when he was a puppy.": "~z~הפסיכותרפיסט שלו אומר שזה חוזר לתקופה שהוא היה גור.",
    "~z~You the ride along? Get on board.": "~z~אתה בסיור (Ride along)? עלה לסיפון.",
    "~z~Right, right. There he is. Over by the oil derricks. Let's see if we can scan him.": "~z~נכון, נכון. הנה הוא. שם ליד מגדלי הקידוח. בוא נראה אם אפשר לסרוק אותו.",
    "~z~Man, I'm just lookin' for a paycheck for my services.": "~z~בנאדם, אני רק מחפש משכורת על השירותים שלי.",
    "~z~Ping it over to me. I think that'd really help.": "~z~שלח (Ping) לי את זה. אני חושב שזה ממש יעזור.",
    "~z~Hey, this shit don't happen on the cop shows, dog. Find him.": "~z~היי, החרא הזה לא קורה בתוכניות משטרה, אחי. תמצא אותו.",
    "~z~How pathetic is someone who spends ten million dollars on a car?": "~z~כמה פתטי זה מישהו שמוציא עשרה מיליון דולר על מכונית?",
    "~z~We got a guy. Standing over by a row of cars. Middle of the floor.": "~z~יש לנו בחור. עומד שם ליד שורה של מכוניות. באמצע הקומה.",
    "~z~Alright, you got me homie, alright. You know how to work that face recognition shit already?": "~z~בסדר, תפסת אותי אחי, בסדר. אתה יודע איך להפעיל את החרא הזה של זיהוי פנים כבר?",
    "~z~Hey, take a look around. Is there another heat source?": "~z~היי, תסתכל סביב. יש עוד מקור חום?",
    "~z~Piece of shit!": "~z~חתיכת חרא!",
    "~z~Not our suspect.": "~z~לא החשוד שלנו.",
    "~z~Suspect down! Fine work ground unit.": "~z~חשוד מנוטרל! עבודה טובה יחידת קרקע.",
    "~z~I really appreciate the thought.": "~z~אני באמת מעריך את המחשבה.",
    "~z~Suspect in sight. He's right below us.": "~z~חשוד בקשר עין. הוא ממש מתחתינו.",
    "~z~She's showing it off! She wanted me to look!": "~z~היא מציגה את זה לראווה! היא רצתה שאסתכל!",
    "~z~Hey, you reading other heat signatures on this level?": "~z~היי, אתה קולט עוד חתימות חום בקומה הזאת?",
    "~z~My precious rectal glands.": "~z~הבלוטות הרקטליות היקרות שלי.",
    "~z~Fuck this shit, man!": "~z~לעזאזל עם החרא הזה, בנאדם!",
    "~z~After everything I've done for you... you are just like Michael.": "~z~אחרי כל מה שעשיתי בשבילך... אתה בדיוק כמו מייקל.",
    "~z~Hey, hey, hey, hey, hey, hey, hey! Noooooooo!": "~z~היי, היי, היי, היי, היי, היי, היי! לאאאאאאא!",
    "~z~Whoa! Whoa! Whoa!": "~z~וואה! וואה! וואה!",
    "~z~Hey, tell me something, you know how many of these things they made?": "~z~היי, תגיד לי משהו, אתה יודע כמה כאלה הם ייצרו?",
    "~z~Nah, homie. Thought you'd appreciate the authenticity.": "~z~לא, אחי. חשבתי שתעריך את האותנטיות.",
    "~z~Surveillance state is working, but it's working slowly.": "~z~מדינת המעקב עובדת, אבל היא עובדת לאט.",
    "~z~Frank. I saw that.": "~z~פרנק. ראיתי את זה.",
    "~z~We got a front row seat up here. Life's rich tapestry. No wonder you cops think you know it all.": "~z~יש לנו שורה ראשונה כאן למעלה. הפסיפס העשיר של החיים. לא פלא שאתם השוטרים חושבים שאתם יודעים הכל.",
    "~z~Suspect sighted in the vicinity of the Rockford Hills Police Department.": "~z~חשוד נראה בסביבת תחנת המשטרה של רוקפורד הילס.",
    "~z~Can you pretend you're enjoying it? I'm already very insecure. This isn't helping.": "~z~אתה יכול להעמיד פנים שאתה נהנה מזה? אני כבר מאוד חסרת ביטחון. זה לא עוזר.",
    "~z~Shit baby you know I love you, baby! I'm sorry!": "~z~שיט מותק, את יודעת שאני אוהב אותך, מותק! אני מצטער!",
    "~z~Where's the fun in meeting a lay over instant message?": "~z~מה הכיף בלפגוש סטוץ (Lay) בהודעות מיידיות?",
    "~z~Man, fuck that. I got a high ass, homie. One time will pick a brother up for any old shit.": "~z~בנאדם, לעזאזל עם זה. אני מסומם טילים, אחי. המשטרה (One time) תעצור אח על כל חרא קטן.",
    "~z~I'd have to break my twenty and under rule.": "~z~הייתי צריך לשבור את חוק העשרים ומטה שלי.",
    "~z~Punch the creep!": "~z~תרביץ לקריפ!",
    "~z~That's all good and all, but can we keep this channel open for important information?": "~z~זה הכל טוב ויפה, אבל אפשר להשאיר את הערוץ הזה פתוח למידע חשוב?",
    "~z~This better be him.": "~z~כדאי שזה יהיה הוא.",
    "~z~Okay. I see the motherfucker, man. I got this.": "~z~אוקיי. אני רואה את הבן זונה, בנאדם. יש לי את זה.",
    "~z~Your boy Chad very nearly totaled the score.": "~z~הבחור שלך צ'אד כמעט והרס טוטאלית את המכונית (השלל).",
    "~z~Just a scratch, homie. No drama.": "~z~רק שריטה, אחי. בלי דרמה.",
    "~z~You are sharp, man.": "~z~אתה חד, בנאדם.",
    "~z~I'ma show him how to drive that thing.": "~z~אני אראה לו איך לנהוג בדבר הזה.",
    "~z~But he still dead with my DNA on his dick, fool!": "~z~אבל הוא עדיין מת עם ה-DNA שלי על הזין שלו, טיפש!",
    "~z~Here. Here. I'm booting up the software for you.": "~z~הנה. הנה. אני מעלה את התוכנה בשבילך.",
    "~z~Hey, Mr. Pilot, your usefulness is about to run out, my friend.": "~z~היי, מר טייס, השימושיות שלך עומדת להיגמר, חבר שלי.",
    "~z~You're a very sick man.": "~z~אתה אדם חולה מאוד.",
    "~z~They only made ten of these. You think anyone's gonna take it off your hands? It's too hot.": "~z~הם ייצרו רק עשר כאלה. אתה חושב שמישהו יקח את זה ממך? זה חם (גנוב/מסוכן) מדי.",
    "~z~Wee oooh wee oooh wee oooh.": "~z~וו או וו או וו או.",
    "~z~Shit, where's that car?": "~z~שיט, איפה המכונית ההיא?",
    "~z~Lordy lord.": "~z~אלוהים אדירים.",
    "~z~Slow and steady.": "~z~לאט ובטוח.",
    "~z~Whoa, easy there. We haven't been paid for the cars yet.": "~z~וואה, לאט לך שם. עדיין לא שילמו לנו על המכוניות.",
    "~z~I can't see him. Need some help here, flyboy. Where is he?": "~z~אני לא רואה אותו. צריך קצת עזרה פה, טייס (Flyboy). איפה הוא?",
    "~z~Just spoke to Devin's man-woman lawyer person.": "~z~הרגע דיברתי עם עורך הדין איש-אישה של דווין.",
    "~z~But, you know what?": "~z~אבל, אתה יודע מה?",
    "~z~it can be a real bitch.": "~z~זה יכול להיות חרא אמיתי.",
    "~z~It's gonna need some body work.": "~z~זה יצטרך קצת פחחות.",
    "~z~What's your angle, Mike?": "~z~מה הזווית שלך (המטרה שלך), מייק?",
    "~z~Come on! Keep up.": "~z~קדימה! תשמור על הקצב.",
    "~z~That wasn't meant to happen.": "~z~זה לא היה אמור לקרות.",
    "~z~Hey! What are you doing? ~c~~n~Hey! Hey! Hey!": "~z~היי! מה אתה עושה? ~c~~n~היי! היי! היי!",
    "~z~You don't like the job, take a fucking walk.": "~z~אתה לא אוהב את העבודה, קח פאקינג הליכה (תעוף).",
    "~z~Yeah, maybe. Something like that.": "~z~כן, אולי. משהו כזה.",
    "~z~Yeah, I guess we will, homie.": "~z~כן, אני מניח שכן, אחי.",
    "~z~after all the crap we been through, man, you got me right back where I'd be at anyway.": "~z~אחרי כל החרא שעברנו, בנאדם, החזרת אותי בדיוק למקום שהייתי נמצא בו בכל מקרה.",
    "~z~Oh, and Michael.": "~z~או, ומייקל.",
    "~z~Yup, so what's going on?": "~z~יאפ, אז מה קורה?",
    "~z~I'm about to shoot your tires out, asshole!": "~z~אני עומד לירות לך בגלגלים, חרא!",
    "~z~Clinton, you're on the ground.": "~z~קלינטון, אתה על הקרקע.",
    "~z~right before I met you, I was boosting rides and racing 'em. It feel likes it come full circle to me.": "~z~רגע לפני שפגשתי אותך, הייתי גונב רכבים ומתחרה איתם. זה מרגיש לי כאילו סגרתי מעגל.",
    "~z~five,": "~z~חמישה,",
    "~z~When I catch these assholes!": "~z~כשאני אתפוס את החארות האלה!",
    "~z~Talent prevails, that's all I'll say.": "~z~כישרון מנצח, זה כל מה שאגיד.",
    "~z~You idiot!": "~z~אתה אידיוט!",
    "~z~The order was for five cars.": "~z~ההזמנה הייתה לחמש מכוניות.",
    "~z~Pull it over! Now!": "~z~עצור בצד! עכשיו!",
    "~z~Enough is enough - stop your vehicles on the bridge!": "~z~מספיק זה מספיק - עצרו את הרכבים שלכם על הגשר!",
    "~z~Mulligan's a record producer.": "~z~מוליגן הוא מפיק תקליטים.",
    "~z~I'ma be waiting at the finish line.": "~z~אני אחכה בקו הסיום.",
    "~z~Our patience will be rewarded - stay with them.": "~z~הסבלנות שלנו תשתלם - תישארו איתם.",
    "~z~Look out, I'm passing.": "~z~זהירות, אני עובר.",
    "~z~Some prosper, and some struggle.": "~z~יש כאלה שמשגשגים, ויש כאלה שנאבקים.",
    "~z~Gentlemen!": "~z~רבותיי!",
    "~z~Get out of the fucking car!": "~z~צא מהמכונית המזדיינת!",
    "~z~You talk a good game. Okay. Just, ahh, don't scratch the cars.": "~z~אתה מדבר יפה. אוקיי. רק, אהה, אל תשרוט את המכוניות.",
    "~z~You alright?": "~z~אתה בסדר?",
    "~z~Aaah, of course! You must be the creepy one...": "~z~אאאה, כמובן! אתה בטח זה הקריפי...",
    "~z~I guess we'll find out.": "~z~אני מניח שנגלה.",
    "~z~Good to meet you.": "~z~נעים להכיר אותך.",
    "~z~Just keep on 'em, I'm coming.": "~z~רק תישאר עליהם, אני בא.",
    "~z~How's my paintjob look?": "~z~איך עבודת הצבע שלי נראית?",
    "~z~for some wealthy communists in China": "~z~עבור כמה קומוניסטים עשירים בסין",
    "~z~All we've got to go on is that the car's in a lockup in Hawick.": "~z~כל מה שיש לנו להסתמך עליו זה שהמכונית נמצאת במחסן בהאוויק.",
    "~z~Good things come to those who wait.": "~z~דברים טובים באים לאלו שמחכים.",
    "~z~It's lonely at the front of the pack, boys.": "~z~זה בודד בקדמת הלהקה (החבורה), בנים.",
    "~z~We'll worry about that another time. Time to exert some reasonable force in the line of duty.": "~z~נדאג לזה בפעם אחרת. הזמן להפעיל כוח סביר במסגרת התפקיד.",
    "~z~They're too far ahead, we got to catch up to them if we want 'em to stop.": "~z~הם רחוקים מדי מקדימה, אנחנו חייבים להשיג אותם אם אנחנו רוצים שהם יעצרו.",
    "~z~That looked nasty.": "~z~זה היה נראה מגעיל (כואב).",
    "~z~Buh-bye, gentlemen, and stay spiritual.": "~z~להתראות, רבותיי, ותישארו רוחניים.",
    "~z~Well, I'll tell you about that later...": "~z~ובכן, אני אספר לך על זה אחר כך...",
    "~z~Boom!": "~z~בום!",
    "~z~He's the real deal. I've seen his house. He can make things happen.": "~z~הוא הדבר האמיתי. ראיתי את הבית שלו. הוא יכול לגרום לדברים לקרות.",
    "~z~Hold on.": "~z~חכה.",
    "~z~Hey, look, Devin Weston - he ain't like anyone you worked for before.": "~z~היי, תראה, דווין ווסטון - הוא לא כמו אף אחד שעבדת עבורו לפני כן.",
    "~z~Mr. Weston will not discuss matters like this with you on the phone. I'll be your port of call for business concerns.": "~z~מר ווסטון לא ידון בעניינים כאלה איתך בטלפון. אני אהיה כתובתך לענייני עסקים.",
    "~z~Don't worry about me.": "~z~אל תדאגו לי.",
    "~z~Don't get too creepy, alright? She's a professional woman, who's doing a job, and leave it at that.": "~z~אל תהיה יותר מדי קריפי, בסדר? היא אישה מקצועית, שעושה עבודה, ותשאיר את זה ככה.",
    "~z~What did I tell you, bro? These cars. This is an opportunity.": "~z~מה אמרתי לך, אחי? המכוניות האלה. זו הזדמנות.",
    "~z~Let's go, come on. ~c~~n~Fuck's sake.": "~z~בואו נלך, קדימה. ~c~~n~למען השם.",
    "~z~Yeah, likewise, homie.": "~z~כן, כנ\"ל, אחי.",
    "~z~We got to stick with them. They gotta stop sometime.": "~z~אנחנו חייבים להישאר איתם. הם יצטרכו לעצור מתישהו.",
    "~z~because they can afford it,": "~z~כי הם יכולים להרשות לעצמם,",
    "~z~Am I gaining on them, or is that my imagination?": "~z~אני מצמצם פערים, או שזה הדמיון שלי?",
    "~z~Don't worry, I'm taking care of that.": "~z~אל תדאג, אני מטפל בזה.",
    "~z~And if you think it's good to be working with common thieves, well, you're very mistaken. Have you got the cars?": "~z~ואם אתה חושב שזה טוב לעבוד עם גנבים פשוטים, ובכן, אתה טועה מאוד. השגת את המכוניות?",
    "~z~Alright. Good.": "~z~בסדר. טוב.",
    "~z~Stop your cars, you idiots!": "~z~עצרו את המכוניות שלכם, אידיוטים!",
    "~z~I'm coming. Hold on.": "~z~אני בא. חכה.",
    "~z~He'll clock any ground surveillance we run.": "~z~הוא יקלוט כל מעקב קרקעי שנריץ.",
    "~z~Stop your car now, hotshot!": "~z~עצור את המכונית שלך עכשיו, תותח (Hotshot)!",
    "~z~I mean, is it just the smell of green?": "~z~אני מתכוון, האם זה רק בגלל הריח של הדולרים (ירוק)?",
    "~z~See if you can stay with me.": "~z~נראה אם אתה יכול להישאר איתי.",
    "~z~Who the fuck does two point seven?": "~z~מי לעזאזל עושה 2.7?",
    "~z~I'm on 'em.": "~z~אני עליהם.",
    "~z~Oh, man...": "~z~או, בנאדם...",
    "~z~Why? Because they have things nobody else has,": "~z~למה? כי יש להם דברים שלאף אחד אחר אין,",
    "~z~Yeah I hope so, 'cause I'm in charge of this shit, and I will dock your pay.": "~z~כן אני מקווה שכן, כי אני אחראי על החרא הזה, ואני אקזז לכם מהשכר.",
    "~z~not to ask me any Goddamn stupid questions.": "~z~לא לשאול אותי שום שאלות טיפשיות ארורות.",
    "~z~You wanna get shot? Cops can do that ya know!": "~z~אתה רוצה שירו בך? שוטרים יכולים לעשות את זה אתה יודע!",
    "~z~Molly Schultz, Senior Vice President and General Council to Devin Weston's holding company, if that's what you mean.": "~z~מולי שולץ, סגנית נשיא בכירה ויועצת משפטית לחברת האחזקות של דווין ווסטון, אם לזה אתה מתכוון.",
    "~z~Hey you dudes is in the stolen rides, you ain't got an excuse for being all the way back there.": "~z~היי אתם ברכבים הגנובים, אין לכם תירוץ להיות כל כך מאחור.",
    "~z~I got you guys.": "~z~יש לי אתכם, חבר'ה.",
    "~z~I need to tell Devin we got them cars.": "~z~אני צריך להגיד לדווין שהשגנו את המכוניות.",
    "~z~and you're gonna rob two trust fund kids": "~z~ואתה הולך לשדוד שני ילדי קרן נאמנות",
    "~z~and five!": "~z~וחמש!",
    "~z~I'm nearly with these dudes, man. You guys comfortable on your end?": "~z~אני כמעט עם החבר'ה האלה, בנאדם. אתם בסדר בצד שלכם?",
    "~z~Move aside, bikers. We're on police business.": "~z~זוזו הצידה, אופנוענים. אנחנו בתפקיד משטרתי.",
    "~z~If I'm a rat, how come you never went to prison? Anyway, that's them.": "~z~אם אני עכבר (מלשן), איך זה שמעולם לא הלכת לכלא? בכל מקרה, אלה הם.",
    "~z~Mr. Weston and I will meet you there.": "~z~מר ווסטון ואני נפגוש אותך שם.",
    "~z~Mr. Weston's research team suggests": "~z~צוות המחקר של מר ווסטון מציע",
    "~z~You must know who this guy is. Look him up.": "~z~אתה בטח יודע מי הבחור הזה. חפש אותו.",
    "~z~You been going too fast, bud. Cool it down.": "~z~נסעת מהר מדי, חבר. תרגיע.",
    "~z~You're not needed for this job.": "~z~אנחנו לא צריכים אותך לעבודה הזאת.",
    "~z~Hey, man, you know how hard it was to drive slow enough to stay with these fools? Let's have a real race.": "~z~היי, בנאדם, אתה יודע כמה קשה היה לנסוע לאט מספיק כדי להישאר עם הטיפשים האלה? בוא נעשה מירוץ אמיתי.",
    "~z~you pint size prick!": "~z~יא זין קטן!",
    "~z~I'm telling you two point seven millimeters.": "~z~אני אומר לך 2.7 מילימטרים.",
    "~z~Here comes the overtake.": "~z~הנה באה העקיפה.",
    "~z~If I can keep this lead, I'll be able to get some alone time with Devin's lady friend.": "~z~אם אני אצליח לשמור על ההובלה הזאת, אני אוכל לקבל קצת זמן איכות לבד עם החברה של דווין.",
    "~z~What you mean, like how am I going to beat your ass in this race?": "~z~מה זאת אומרת, כאילו איך אני הולך לקרוע לך את התחת במירוץ הזה?",
    "~z~Side of the road - now!": "~z~לצד הכביש - עכשיו!",
    "~z~I'm telling you, two point seven milimeters.": "~z~אני אומר לך, 2.7 מילימטרים.",
    "~z~as if there was any doubt. Get here safe now.": "~z~כאילו שהיה ספק. תגיעו לפה בבטחה עכשיו.",
    "~z~So we just go house to house?": "~z~אז אנחנו פשוט עוברים מבית לבית?",
    "~z~Now, I mean that as a friend.": "~z~עכשיו, אני אומר את זה בתור חבר.",
    "~z~They're driving into Paleto Bay - traffic might slow 'em down.": "~z~הם נוסעים לתוך מפרץ פאלטו - התנועה אולי תאט אותם.",
    "~z~Man, I'm sick of driving so slow, staying with these fools. Can we have a real race?": "~z~בנאדם, נמאס לי לנהוג כל כך לאט, ולהישאר עם הטיפשים האלה. אפשר לעשות מירוץ אמיתי?",
    "~z~That's a nice fucking speech about the value of friendship.": "~z~זה נאום מזדיין יפה על הערך של חברות.",
    "~z~We're coming back for you, bikers!": "~z~אנחנו נחזור אליכם, אופנוענים!",
    "~z~So what's next, man?": "~z~אז מה הלאה, בנאדם?",
    "~z~Here they come.": "~z~הנה הם באים.",
    "~z~You alright, bro?": "~z~אתה בסדר, אחי?",
    "~z~Yeah, well, I don't understand the deal between you two either.": "~z~כן, ובכן, גם אני לא מבין את הקטע ביניכם.",
    "~z~You're late, sugar tits.": "~z~איחרת, שוגר-טיטס.",
    "~z~Ain't these meant to be mint?": "~z~הן לא היו אמורות להיות במצב מושלם (Mint)?",
    "~z~Let's do this, let's get 'em.": "~z~בואו נעשה את זה, בואו נשיג אותם.",
    "~z~I can still take you, you believe that.": "~z~אני עדיין יכול לקחת (לנצח) אותך, תאמין לזה.",
    "~z~I'm serious. Both of you. Back off her.": "~z~אני רציני. שניכם. תעזבו אותה בשקט.",
    "~z~follow him to the lockup,": "~z~לעקוב אחריו למחסן,",
    "~z~Stay on them, T. They'll stop eventually.": "~z~תישאר עליהם, T. הם יעצרו בסוף.",
    "~z~My car is fine.": "~z~המכונית שלי בסדר.",
    "~z~And you, you little shit.": "~z~ואתה, יא חרא קטן.",
    "~z~You drive like an old dude.": "~z~אתה נוהג כמו בחור זקן.",
    "~z~Stay in the car there, homeboy.": "~z~תישאר במכונית שם, אחי.",
    "~z~You got an authority problem, son?  Stop your car!": "~z~יש לך בעיית סמכות, ילד? תעצור את המכונית שלך!",
    "~z~Wow, the whole résumé. Yeah, we got the cars.": "~z~וואו, קורות חיים שלמים. כן, השגנו את המכוניות.",
    "~z~Alright. So, who does what?": "~z~בסדר. אז, מי עושה מה?",
    "~z~I guess. We look pretty ridiculous.": "~z~אני מניח. אנחנו נראים די מגוחכים.",
    "~z~Robbing my so called friends, Slick.": "~z~לשדוד את ה'חברים' שלי כביכול, סליק.",
    "~z~Nah, I'm serious. If you hadn't got me fired from my repo job,": "~z~לא, אני רציני. אם לא היית גורם לי לפיטורים מעבודת העיקולים שלי,",
    "~z~We'll pick you up coming through Grapeseed, get the drivers there, and get 'em going at speed.": "~z~נאסוף אותך כשנעבור דרך גרייפסיד, נתפוס את הנהגים שם, ונגרום להם לנסוע מהר.",
    "~z~So, he, like, to you, what you were to me.": "~z~אז, הוא, כאילו, בשבילך, מה שאתה היית בשבילי.",
    "~z~Well, shit, me and your boss ain't gonna have any personal concerns.": "~z~ובכן, שיט, לי ולבוס שלך לא יהיו שום עניינים אישיים.",
    "~z~Can you be careful!?": "~z~אתה יכול להיזהר!?",
    "~z~Don't think you got me beat.": "~z~אל תחשוב שניצחת אותי.",
    "~z~Asshole.": "~z~חרא.",
    "~z~He's hiding his valuable assets,": "~z~הוא מסתיר את הנכסים היקרים שלו,",
    "~z~Look, complete the work, you'll all be well paid.": "~z~תראו, תשלימו את העבודה, כולכם תקבלו תשלום יפה.",
    "~z~I'm first back. Get your cars here safe, boys.": "~z~אני הראשון שחזר. תביאו את המכוניות שלכם לפה בבטחה, בנים.",
    "~z~You don't wanna make me angry - pull over.": "~z~אתה לא רוצה להכעיס אותי - תעצור בצד.",
    "~z~Trevor Philips - number one -": "~z~טרבור פיליפס - מספר אחד -",
    "~z~Yeah... I-I-I don't understand the deal between you two.": "~z~כן... א-א-אני לא מבין את הקטע ביניכם.",
    "~z~Hey, Frank.": "~z~היי, פרנק.",
    "~z~Get out of the fucking car,": "~z~צא מהמכונית המזדיינת,",
    "~z~The fool wants to race us.": "~z~הטיפש רוצה להתחרות בנו.",
    "~z~The car got away from me!": "~z~המכונית חמקה לי!",
    "~z~Whoa, hey!": "~z~וואה, היי!",
    "~z~Oh-ho-ho!": "~z~או-הו-הו!",
    "~z~That was weird.": "~z~זה היה מוזר.",
    "~z~because frankly I'm rich enough to do whatever the fuck I want,": "~z~כי למען האמת אני מספיק עשיר לעשות מה שבא לי,",
    "~z~Life is just one long mystery.": "~z~החיים הם רק תעלומה אחת ארוכה.",
    "~z~Alright, man, look, I'll see you soon.": "~z~בסדר, בנאדם, תראה, נתראה בקרוב.",
    "~z~He's going through a messy divorce.": "~z~הוא עובר גירושין מכוערים.",
    "~z~We were just getting out of here anyway.": "~z~בכל מקרה היינו בדיוק יוצאים מפה.",
    "~z~Coming up on Paleto Bay - we might gain some ground on them.": "~z~מתקרבים למפרץ פאלטו - אולי נצמצם את הפער מהם.",
    "~z~Find Mulligan in Hawick,": "~z~תמצאו את מוליגן בהאוויק,",
    "~z~Yeah right, fool!": "~z~כן בטח, טיפש!",
    "~z~Watch the car, homie.": "~z~תיזהר על המכונית, אחי.",
    "~z~Watch the paintwork.": "~z~תיזהרו על הצבע.",
    "~z~Man, he runs his mouth, wants me to boost cars, and most likely goin' be payin' me a fraction of what they worth.": "~z~בנאדם, הוא מדבר הרבה, רוצה שאני אגנוב מכוניות, וכנראה הולך לשלם לי שבריר ממה שהן שוות.",
    "~z~They ain't going to stop with us back here. We got to get right up behind them.": "~z~הם לא יעצרו כשאנחנו מאחורה פה. אנחנו חייבים להיצמד אליהם.",
    "~z~Hey, how about we see which one of you two is for real?": "~z~היי, מה דעתכם שנבדוק מי משניכם הוא באמת הדבר האמיתי?",
    "~z~Yeah, fuck you too.": "~z~כן, לך תזדיין גם אתה.",
    "~z~God, this is gonna be fantastic.": "~z~אלוהים, זה הולך להיות פנטסטי.",
    "~z~Officer down - where's my partner?": "~z~שוטר נפגע - איפה השותף שלי?",
    "~z~You got the fuckin' paper?": "~z~הבאת את הכסף המזדיין?",
    "~z~Keep talking. Mmm, I'm enjoying this.": "~z~תמשיך לדבר. מממ, אני נהנה מזה.",
    "~z~If you say so...": "~z~אם אתה אומר...",
    "~z~Frank's at the back. I think they want him to stop and take the booking.": "~z~פרנק מאחור. נראה לי שהם רוצים שהוא יעצור ויקח את הדוח.",
    "~z~If it's about the girl, I saw her first.": "~z~אם זה בקשר לבחורה, אני ראיתי אותה קודם.",
    "~z~This a weird road, homies.": "~z~זה כביש מוזר, אחים שלי.",
    "~z~If I'm finna do this, I'm finna do it right. So, ahh, how your car, Mike?": "~z~אם אני הולך לעשות את זה, אני הולך לעשות את זה כמו שצריך. אז, אה, מה מצב המכונית שלך, מייק?",
    "~z~Ah, I stacked it.": "~z~אה, ריסקתי אותה (Stacked it).",
    "~z~You're gonna dress up as traffic cops": "~z~אתם הולכים להתחפש לשוטרי תנועה",
    "~z~I don't think they can hear the sirens, we've got to get close.": "~z~אני לא חושב שהם שומעים את הסירנות, אנחנו חייבים להתקרב.",
    "~z~It aint' no fun if no one pushing me, come on, dudes.": "~z~זה לא כיף אם אף אחד לא דוחף אותי, קדימה, חבר'ה.",
    "~z~and dress up as a cop!": "~z~ולהתחפש לשוטר!",
    "~z~Not quite.": "~z~לא בדיוק.",
    "~z~Finally, you got your uniform on.": "~z~סוף סוף, שמת את המדים שלך.",
    "~z~Frank's still on them - the dickheads probably want him to stop and take the heat.": "~z~פרנק עדיין עליהם - הטמבלים האלה כנראה רוצים שהוא יעצור ויחטוף את האש.",
    "~z~You doing alright back there, partner?": "~z~אתה מסתדר שם מאחורה, שותף?",
    "~z~If I'm not mistaken, that's only two.": "~z~אם אני לא טועה, זה רק שתיים.",
    "~z~He's such a goon.": "~z~הוא כזה בריון (Goon).",
    "~z~Deal with you later.": "~z~אטפל בך אחר כך.",
    "~z~Slick!": "~z~סליק (חלקלק)!",
    "~z~What happened there?": "~z~מה קרה שם?",
    "~z~I ain't down yet.": "~z~אני עדיין לא למטה (לא הפסדתי).",
    "~z~including the car,": "~z~כולל המכונית,",
    "~z~You ain't going to have that lead for much longer.": "~z~לא יהיה לך את היתרון הזה לעוד הרבה זמן.",
    "~z~Or is there some other thing with this guy and you? It feels funky.": "~z~או שיש עוד משהו עם הבחור הזה ואיתך? זה מרגיש מוזר.",
    "~z~Sweet.": "~z~מתוק (מעולה).",
    "~z~Get the fuck outta here!": "~z~עוף מפה לעזאזל!",
    "~z~I wouldn't write off Uncle T.": "~z~לא הייתי מספיד את דוד T.",
    "~z~Shit, I screwed up!": "~z~שיט, פישלתי!",
    "~z~Bring them to Hayes Auto on Little Big Horn in South Los Santos. Mr. Weston and I will meet you there.": "~z~הביאו אותן להייס אוטו בליטל ביג הורן בדרום לוס סאנטוס. מר ווסטון ואני נפגוש אתכם שם.",
    "~z~Mmmmm... what's going on?": "~z~מממממ... מה קורה?",
    "~z~They don't look like they're stopping, we got to get closer.": "~z~לא נראה שהם עוצרים, אנחנו חייבים להתקרב.",
    "~z~You want me to slow down? I'm kinda running away with it, huh?": "~z~אתה רוצה שאאט? אני קצת בורח עם זה, הא?",
    "~z~So get in your cars and let's see if they move as fast as your mouths.": "~z~אז תיכנסו למכוניות שלכם ובואו נראה אם הן זזות מהר כמו הפה שלכם.",
    "~z~You... finally get to realize your childhood dream": "~z~אתה... סוף סוף זוכה להגשים את חלום הילדות שלך",
    "~z~Be careful of the cars.": "~z~היזהרו על המכוניות.",
    "~z~Mmmmm, I know that voice, you're that Johnson's Johnson.": "~z~מממממ, אני מכיר את הקול הזה, אתה הג'ונסון של ג'ונסון הזה.",
    "~z~Don't hang up! I... I think I love you.": "~z~אל תנתקי! אני... אני חושב שאני אוהב אותך.",
    "~z~Suspect has entered the Braddock Tunnel - Officer T maintains his pursuit.": "~z~החשוד נכנס למנהרת בראדוק - השוטר T ממשיך במרדף שלו.",
    "~z~someone on the ground collects the car.": "~z~מישהו על הקרקע אוסף את המכונית.",
    "~z~I vote we indulge his childish need to play. Besides, it's his head on the block if they get scratched.": "~z~אני בעד שנספק את הצורך הילדותי שלו לשחק. חוץ מזה, הראש שלו על המוקד אם הן נשרטות.",
    "~z~Out the way, bro.": "~z~זוז מהדרך, אחי.",
    "~z~Oh would you look at this goon?": "~z~או, תראה את הבריון הזה?",
    "~z~Gee, I don't know, officer. I uh...": "~z~וואו, אני לא יודע, שוטר. אני אה...",
    "~z~Don't get too comfortable out in front.": "~z~אל תרגיש יותר מדי בנוח שם מקדימה.",
    "~z~Good to see you taking this seriously, Frank. Good management.": "~z~טוב לראות שאתה לוקח את זה ברצינות, פרנק. ניהול טוב.",
    "~z~Oh, you must be Michael's boy.": "~z~או, אתה בטח הילד של מייקל.",
    "~z~Five,": "~z~חמישה,",
    "~z~Oh, that was me!": "~z~או, זה הייתי אני!",
    "~z~Sounds manageable.": "~z~נשמע אפשרי.",
    "~z~Watch the ride, man!": "~z~תיזהר על הרכב, בנאדם!",
    "~z~Let's assume you're talking about the cars. Bring them to Hayes Auto on Little Big Horn in South LS.": "~z~נניח שאתה מדבר על המכוניות. הביאו אותן להייס אוטו בליטל ביג הורן בדרום LS.",
    "~z~Trevor by a nose.": "~z~טרבור ניצח בהפרש של חוטם (Belly).",
    "~z~Go on!": "~z~המשך!",
    "~z~We can get a good price for the vehicles in Asia.": "~z~אנחנו יכולים לקבל מחיר טוב על הרכבים באסיה.",
    "~z~My life's already way the fuck out of control.": "~z~החיים שלי כבר יצאו משליטה לגמרי.",
    "~z~Alright, look...": "~z~בסדר, תראה...",
    "~z~The computer on board can ID pedestrians from a chip in their driver's license.": "~z~המחשב על הסיפון יכול לזהות הולכי רגל משבב ברישיון הנהיגה שלהם.",
    "~z~so that makes it complicated.": "~z~אז זה מסבך את העניינים.",
    "~z~You know how fast you were goin'?": "~z~אתה יודע כמה מהר נסעת?",
    "~z~This one's on the wrong side of the road. I'll stay on him, come if you can handle it.": "~z~האחד הזה בצד הלא נכון של הכביש. אני אשאר עליו, בוא אם אתה יכול להתמודד עם זה.",
    "~z~this exactly the kinda shit I'd be doing. So thanks dog,": "~z~זה בדיוק סוג החרא שהייתי עושה. אז תודה אחי,",
    "~z~Hands on the car.": "~z~ידיים על המכונית.",
    "~z~This ain't over yet.": "~z~זה עדיין לא נגמר.",
    "~z~Good. My ass is dead!": "~z~טוב. התחת שלי מת!",
    "~z~Abso-fucking-lutely!": "~z~בהחלט-פאקינג-כן!",
    "~z~We got to keep these things in good condition.": "~z~אנחנו חייבים לשמור על הדברים האלה במצב טוב.",
    "~z~Gimme...": "~z~תן לי...",
    "~z~It's Molly Schultz - Senior Vice President and General Counsel to Mr. Weston's holding company.": "~z~זו מולי שולץ - סגנית נשיא בכירה ויועצת משפטית לחברת האחזקות של מר ווסטון.",
    "~z~We got 'em.": "~z~השגנו אותם.",
    "~z~No sexual harassment in the workplace, T. Not on my watch.": "~z~בלי הטרדה מינית במקום העבודה, T. לא במשמרת שלי.",
    "~z~We hear you're a competent repo guy, yes?": "~z~שמענו שאתה בחור עיקולים (repo) מוכשר, כן?",
    "~z~Hey! You two get going.": "~z~היי! שניכם צאו לדרך.",
    "~z~Yeah, this is kinda like a little hobby of mine,": "~z~כן, זה די תחביב קטן שלי,",
    "~z~I'll be in touch about your friend, Solomon.": "~z~אני אהיה בקשר לגבי חבר שלך, סולומון.",
    "~z~Eh, the paintwork!": "~z~אה, הצבע!",
    "~z~requisitioning the underappreciated...": "~z~מפקיע את מה שלא מעריכים מספיק...",
    "~z~So Devin's lawyer says we got to take them to Hayes Auto in South LS. I'ma be there well ahead of you.": "~z~אז עורך הדין של דווין אומר שאנחנו צריכים לקחת אותם להייס אוטו בדרום LS. אני אהיה שם הרבה לפניכם.",
    "~z~The lead horse always burns out before the end.": "~z~הסוס המוביל תמיד נשרף לפני הסוף.",
    "~z~Pull over to the side of the road!": "~z~עצור בצד הכביש!",
    "~z~Pull over to the side of the road.": "~z~עצור בצד הכביש.",
    "~z~Ah, the lady from before, Devin's assistant? Good to be working with you.": "~z~אה, הגברת ממקודם, העוזרת של דווין? טוב לעבוד איתך.",
    "~z~Tell Devin I didn't have anything to do with that.": "~z~תגידי לדווין שלא היה לי שום קשר לזה.",
    "~z~Chad Mulligan.": "~z~צ'אד מוליגן.",
    "~z~I'll be there in a second.": "~z~אני אהיה שם תוך שנייה.",
    "~z~You should be in the slow lane, brother.": "~z~אתה צריך להיות בנתיב האיטי, אחי.",
    "~z~Bring the cars to Hayes Auto on Little Big Horn in South Los Santos. Mr. Weston and I will meet you there.": "~z~הביאו את המכוניות להייס אוטו בליטל ביג הורן בדרום לוס סאנטוס. מר ווסטון ואני נפגוש אתכם שם.",
    "~z~I'm a payment on completion of work type of guy.": "~z~אני בחור של תשלום עם סיום העבודה.",
    "~z~the two boys like to ride on the Senora Freeway.": "~z~שני הבנים אוהבים לנסוע על הכביש המהיר סנורה.",
    "~z~Well, you and your boys look like you were drag racing from where we were sitting there.": "~z~ובכן, אתה והחבר'ה שלך נראים כאילו עשיתם מירוץ דראג מאיפה שישבנו שם.",
    "~z~We'll see about that.": "~z~נראה לגבי זה.",
    "~z~They're pulling over.": "~z~הם עוצרים בצד.",
    "~z~Assistant? This is Molly Schultz, Senior Vice President and General Council for Devin Weston Holdings.": "~z~עוזרת? זו מולי שולץ, סגנית נשיא בכירה ויועצת משפטית ל-Devin Weston Holdings.",
    "~z~Let's go, T.": "~z~בוא נלך, T.",
    "~z~Eh, your cars still alright, right?": "~z~אה, המכוניות שלכם עדיין בסדר, נכון?",
    "~z~Well, it's the Z-Type.": "~z~ובכן, זו ה-Z-Type.",
    "~z~Dog, come on, man.": "~z~אחי, נו, בנאדם.",
    "~z~This is your lucky break.": "~z~זה הפריצה שלך למזל (lucky break).",
    "~z~Finally - it looks like they're slowing down.": "~z~סוף סוף - נראה שהם מאטים.",
    "~z~I'm just biding my time.": "~z~אני רק מחכה להזדמנות שלי (Biding my time).",
    "~z~I don't know what's up with this road.": "~z~אני לא יודע מה הקטע עם הכביש הזה.",
    "~z~that I know and dislike intensely.": "~z~שאני מכיר ולא סובל בעוצמה.",
    "~z~Don't scratch 'em!": "~z~אל תשרוט אותן!",
    "~z~try to keep it under the limit.": "~z~תנסה לשמור על זה מתחת למהירות המותרת.",
    "~z~Silly me - you're a rat... not a turd.": "~z~טיפש שכמוני - אתה עכבר (מלשן)... לא גוש חרא.",
    "~z~Did anyone see that?": "~z~מישהו ראה את זה?",
    "~z~Find a safe place to stop, and pull over!": "~z~תמצא מקום בטוח לעצור, ועצור בצד!",
    "~z~Gentleman, move the vehicles.": "~z~רבותיי, תזיזו את הרכבים.",
    "~z~I'm a jet pilot, asshole.": "~z~אני טייס סילון, חרא.",
    "~z~Choose!": "~z~בחר!",
    "~z~Dog, I don't know if this shit is for me, homie.": "~z~אחי, אני לא יודע אם החרא הזה מתאים לי.",
    "~z~Hey, I'm just trying to do what's best for Frank. You know, help him make the best of the chances he's given.": "~z~היי, אני רק מנסה לעשות מה שהכי טוב לפרנק. אתה יודע, לעזור לו להפיק את המרב מההזדמנויות שניתנו לו.",
    "~z~We have access to an LSPD helicopter.": "~z~יש לנו גישה למסוק של ה-LSPD.",
    "~z~Yes it is. Get down, c'mon.": "~z~כן זה כן. רד למטה, קדימה.",
    "~z~I'll be waiting at Hayes Auto in South LS for you idiots to show up.": "~z~אני אחכה בהייס אוטו בדרום LS שאתם האידיוטים תופיעו.",
    "~z~Just give me the fucking money now!": "~z~פשוט תן לי את הכסף המזדיין עכשיו!",
    "~z~That all you got?": "~z~זה כל מה שיש לך?",
    "~z~Or have you simply found your level in life?": "~z~או שפשוט מצאת את הרמה שלך בחיים?",
    "~z~How far they taking us? I could swear we've circled half the state.": "~z~כמה רחוק הם לוקחים אותנו? יכולתי להישבע שעקפנו חצי מדינה.",
    "~z~Well, I ain't waiting around, man. Let's go, but, uhh, don't mess up the cars, you hear me?": "~z~ובכן, אני לא מחכה פה, בנאדם. בואו נלך, אבל, אהה, אל תהרוס את המכוניות, אתה שומע אותי?",
    "~z~Hey Frank.": "~z~היי פרנק.",
    "~z~I was in witsec, that don't make me a cop.": "~z~הייתי בתוכנית להגנת עדים (witsec), זה לא הופך אותי לשוטר.",
    "~z~Now, are you out of your Goddamn mind?": "~z~עכשיו, השתגעת לגמרי לעזאזל?",
    "~z~It ain't over till it's over, you heard?": "~z~זה לא נגמר עד שזה לא נגמר, שמעת?",
    "~z~Hey, you that lady? The intense dude's assistant, right?": "~z~היי, את הגברת הזאת? העוזרת של הבחור האינטנסיבי ההוא, נכון?",
    "~z~Don't sound that different, to be honest.": "~z~לא נשמע כל כך שונה, למען האמת.",
    "~z~possessions of my contemporaries": "~z~הרכוש של בני דורי",
    "~z~Don't wreck the ride, you hear?": "~z~אל תהרוס את הרכב, שומע?",
    "~z~Where you gone, Michael? We got to catch these guys.": "~z~לאן הלכת, מייקל? אנחנו חייבים לתפוס את החבר'ה האלה.",
    "~z~How you doing, T? We got to hang in there.": "~z~איך אתה מסתדר, T? אנחנו חייבים להחזיק מעמד.",
    "~z~why don't you get yourself out of the car?": "~z~למה שלא תוציא את עצמך מהמכונית?",
    "~z~Sorry, bro. I got a race to win.": "~z~מצטער, אחי. יש לי מירוץ לנצח בו.",
    "~z~Look, you finish the job, you get the paper, but...": "~z~תראה, תסיים את העבודה, תקבל את הכסף (Paper), אבל...",
    "~z~Gimme a moment.": "~z~תן לי רגע.",
    "~z~Chest kiss, homie!": "~z~נשיקה בחזה, אחי!",
    "~z~I see your house, I think this dude can take me places.": "~z~אני רואה את הבית שלך, אני חושב שהבחור הזה יכול לקחת אותי למקומות.",
    "~z~Nine years in the force, and I'm only just seeing your true colors.": "~z~תשע שנים בכוח, ורק עכשיו אני רואה את הפרצוף האמיתי שלך.",
    "~z~Officer, is this entirely necessary? ~c~~n~Officer, officer.": "~z~שוטר, האם זה הכרחי לחלוטין? ~c~~n~שוטר, שוטר.",
    "~z~Well looks like you guys are fighting it out for second and third.": "~z~ובכן נראה שאתם נלחמים על המקום השני והשלישי.",
    "~z~who the fuck would have thought it?": "~z~מי לעזאזל היה חושב על זה?",
    "~z~Eh, we comin' up now, man. Be there in a few seconds.": "~z~אה, אנחנו עולים (מתקרבים) עכשיו, בנאדם. נהיה שם בעוד כמה שניות.",
    "~z~Namaste.": "~z~נמסטה.",
    "~z~You've had your fun - now come to a stop on the bridge!": "~z~היה לכם כיף - עכשיו עצרו על הגשר!",
    "~z~Come on man, speed up.": "~z~נו בנאדם, תגביר מהירות.",
    "~z~Sometimes enlightenment,": "~z~לפעמים הארה,",
    "~z~Now, are you gonna do this?": "~z~עכשיו, אתה הולך לעשות את זה?",
    "~z~Whatever.": "~z~מה שתגיד.",
    "~z~The stains on the seats were here when I got in.": "~z~הכתמים על המושבים היו פה כשנכנסתי.",
    "~z~Oh, I'm so scared, I really really am, but you know what?": "~z~או, אני כל כך מפחד, באמת באמת, אבל אתה יודע מה?",
    "~z~Long as we can keep with them, we'll pull this off.": "~z~כל עוד נוכל להישאר איתם, נצליח בזה.",
    "~z~Can you move, I'm in a hurry.": "~z~אתה יכול לזוז, אני ממהר.",
    "~z~Your rich friend ain't going to like it if they're scratched.": "~z~החבר העשיר שלך לא יאהב את זה אם הן יהיו שרוטות.",
    "~z~We'll have driven around the whole of Southern San Andreas before they stop.": "~z~ניסע סביב כל דרום סן אנדראס לפני שהם יעצרו.",
    "~z~What's the hold up, Mike? You going to maintain pursuit?": "~z~מה העיכוב, מייק? אתה הולך להמשיך במרדף?",
    "~z~I wouldn't write me off just yet.": "~z~לא הייתי מספיד אותי עדיין.",
    "~z~Oh, oh-ho-ho!": "~z~או, או-הו-הו!",
    "~z~San Andreas highway patrol - stop your vehicles!": "~z~סיירת הכבישים המהירים של סן אנדראס - עצרו את הרכבים שלכם!",
    "~z~Philips, you're in the chopper.": "~z~פיליפס, אתה במסוק.",
    "~z~What a surprise, I won this thing. You dudes got no excuse for chipped paintwork.": "~z~איזו הפתעה, ניצחתי בזה. חבר'ה, אין לכם תירוץ לצבע שרוט.",
    "~z~Oh come on T, man... please.": "~z~או נו באמת T, בנאדם... בבקשה.",
    "~z~Alright, we gotta make sure.": "~z~בסדר, אנחנו חייבים לוודא.",
    "~z~Lay it on 'em, kid.": "~z~תן להם בראש, ילד.",
    "~z~One kid and two old creeps,": "~z~ילד אחד ושני קריפים זקנים,",
    "~z~Devin's lonely lawyer says go to Hayes Auto in South LS, so that's where I'll be waiting...": "~z~עורך הדין הבודד של דווין אומר ללכת להייס אוטו בדרום LS, אז שם אני אחכה...",
    "~z~They're slowing down - this looks like our shot.": "~z~הם מאטים - זה נראה כמו ההזדמנות שלנו.",
    "~z~The only thing to figure now, is which one of you is getting the silver medal, right?": "~z~הדבר היחיד שצריך להבין עכשיו, זה מי מכם מקבל את מדליית הכסף, נכון?",
    "~z~I'm way out in front, guys.": "~z~אני הרחק מקדימה, חבר'ה.",
    "~z~and you're poor enough": "~z~ואתה עני מספיק",
    "~z~And that's coming from you? Please!": "~z~וזה בא ממך? בבקשה!",
    "~z~who will value them much more.": "~z~שיעריכו אותן הרבה יותר.",
    "~z~I'm a Darwinist, brother, alright?": "~z~אני דרוויניסט, אחי, בסדר?",
    "~z~I'll see you at the finish.": "~z~אראה אתכם בקו הסיום.",
    "~z~Where's my backup? I can't see you, Michael.": "~z~איפה הגיבוי שלי? אני לא רואה אותך, מייקל.",
    "~z~I love you all!": "~z~אני אוהב את כולכם!",
    "~z~Security! Security!": "~z~אבטחה! אבטחה!",
    "~z~Get to the side of the road!": "~z~סעו לצד הכביש!",
    "~z~If you want him in, then you get him to boost the rest of the shit you got.": "~z~אם אתה רוצה אותו בפנים, אז תיתן לו לגנוב את שאר החרא שיש לך.",
    "~z~Hurry up please!": "~z~תזדרז בבקשה!",
    "~z~Aight.": "~z~בסדר (Aight).",
    "~z~Woo, woo, woo, woo.": "~z~וו, וו, וו, וו.",
    "~z~Oh my gosh, get me out of here!": "~z~או אלוהים אדירים, תוציאו אותי מפה!",
    "~z~What's the point in building all these sets, if we got to put Brandon's head on this guy's body in post!": "~z~מה הטעם לבנות את כל הסטים האלה, אם אנחנו צריכים לשים את הראש של ברנדון על הגוף של הבחור הזה בעריכה (post)!",
    "~z~I've been abducted by a crazed fan!": "~z~נחטפתי על ידי מעריץ מטורף!",
    "~z~Fuck, I've picked up a tail.": "~z~פאק, יש לי זנב (מישהו עוקב אחריי).",
    "~z~Come on, buddy!": "~z~קדימה, חבר!",
    "~z~Take me back now!": "~z~תחזיר אותי עכשיו!",
    "~z~It is what it is.": "~z~זה מה שזה.",
    "~z~We plan on refitting the guns to take live ammunition, do the traffic spikes and ejector seat need replacing too?": "~z~אנחנו מתכננים להתאים מחדש את הרובים לתחמושת חיה, האם גם דוקרני התנועה ומושב המפלט צריכים החלפה?"
}

with open("current_batch.json", "r", encoding="utf-8") as f:
    orig = json.load(f)

for k in orig:
    if k in data:
        orig[k] = data[k]
    else:
        orig[k] = ""

with open("current_batch.json", "w", encoding="utf-8") as f:
    json.dump(orig, f, indent=4, ensure_ascii=False)

print("Translation applied!")
