###                                                                \    /  
###                       _  _                 _            _      \\__//  
###      ____ ._/______:_//\//_/____       _  //___  ./_ __//_____:_\\//   
###     :\  //_/    _  . /_/  /    /_/__:_//_/    /\ /\__/_    _  . /\\\   
###      \\///      ____/___./    / /     / /    /  /  \X_/   //___/ /_\_  
###     . \///   _______   _/_   /_/    _/_/     \\/   //        /_\_\  /. 
###       z_/   _/\  _/   // /         //      /  \   ///     __//   :\//  
###     | / _   / /\//   /__//      __//_   _ /\     /X/     /__/   |/\/2  
###   --+-_=\__/ / /    / \_____:__/ //\____// /\   /\/__:_______=_-+--\4  
###     |-\__\- / /________\____.__\/- -\--/_\/_______\--.\________\|___\  
###      = dS!\/- -\_______\ =-RUNE- -== \/ ==-\______\-= ======== --\__\ 
###
###
### Game data is stored at %SystemDrive%\Users\Public\Documents\Steam\CODEX\2483190
###

[Settings]
###
### Game identifier (http://store.steampowered.com/app/2483190)
###
AppId=2483190
###
### Steam Account ID, set it to 0 to get a random Account ID
###
#AccountId=0
### 
### Name of the current player
###
UserName=Nehoray
###
### Language that will be used in the game
###
Language=english
###
### Enable lobby mode
###
LobbyEnabled=1
###
### Lobby port to listen on
###
#LobbyPort=31183
###
### Enable/Disable Steam overlay
###
Overlays=1
###
### Set Steam connection to offline mode
###
Offline=1
###
BuildId=24241019
###
SkipRegistry=1
###
SkipHooks=1
###
SelfProtect=0
###

[HTTP]
d696f975bb3df45472669f8d56aef437=httpcache\1337

[Interfaces]
###
### Steam Client API interface versions
###
SteamAppList=STEAMAPPLIST_INTERFACE_VERSION001
SteamApps=STEAMAPPS_INTERFACE_VERSION008
SteamClient=SteamClient017
SteamController=SteamController008
SteamFriends=SteamFriends017
SteamGameServer=SteamGameServer013
SteamGameServerStats=SteamGameServerStats001
SteamHTMLSurface=STEAMHTMLSURFACE_INTERFACE_VERSION_005
SteamHTTP=STEAMHTTP_INTERFACE_VERSION003
SteamInput=SteamInput002
SteamInventory=STEAMINVENTORY_INTERFACE_V003
SteamMatchGameSearch=SteamMatchGameSearch001
SteamMatchMaking=SteamMatchMaking009
SteamMatchMakingServers=SteamMatchMakingServers002
SteamMusic=STEAMMUSIC_INTERFACE_VERSION001
SteamMusicRemote=STEAMMUSICREMOTE_INTERFACE_VERSION001
SteamNetworking=SteamNetworking006
SteamParentalSettings=STEAMPARENTALSETTINGS_INTERFACE_VERSION001
SteamParties=SteamParties002
SteamRemoteStorage=STEAMREMOTESTORAGE_INTERFACE_VERSION014
SteamScreenshots=STEAMSCREENSHOTS_INTERFACE_VERSION003
SteamUGC=STEAMUGC_INTERFACE_VERSION015
SteamUser=SteamUser021
SteamUserStats=STEAMUSERSTATS_INTERFACE_VERSION012
SteamUtils=SteamUtils010
SteamVideo=STEAMVIDEO_INTERFACE_V002
###

[DLC]
###
### Automatically unlock all DLCs
###
DLCUnlockall=0
###
### Identifiers for DLCs
###
#ID=Name
4439240=Forza Horizon 6 Expansion 1
4439250=Forza Horizon 6 Expansion 2
4439260=Forza Horizon 6 Welcome Pack
4439270=Forza Horizon 6 Premium VIP
4439280=Forza Horizon 6 Time Attack Car Pack
4439290=Forza Horizon 6 Italian Passion Car Pack
4439300=Forza Horizon 6 Ferrari J50
4439750=Forza Horizon 6 Treasure Map
4439790=Forza Horizon 6 Car Pass
4439800=Forza Horizon 6 1990 Nissan #12 Skyline GT-R (BNR32 Gr.A) JTC
4439810=Forza Horizon 6 2024 Koenigsegg Gemera
4439820=Forza Horizon 6 1972 Datsun #269 Attacking the Clock Racing 240Z "All Carbon Hill Climb Beast"
4439830=Forza Horizon 6 2008 Honda Civic Type R (FD2)
4439840=Forza Horizon 6 2023 Audi R8 Coupé V10 GT RWD
4439890=Forza Horizon 6 1974 Mazda #123 Mad Mike 808 Wagon 'FURSTY'
4439900=Forza Horizon 6 2023 Toyota GR Corolla
4440380=Forza Horizon 6 VIP Membership
4444140=Forza Horizon 6 TBDS2
4444150=Forza Horizon 6 1962 Peel P50 Trolli Edition
4520350=Forza Horizon 6 Expansions Bundle
4520360=Forza Horizon 6 Premium Upgrade Bundle
4562050=Forza Horizon 6 Crunchyroll Voucher
4610350=Forza Horizon 6 1998 Nissan Skyline GT-R 40th Anniversary
###

[Crack]
2fd7811c55f88495=3681a9beddbae875
71f12671c4b66a1d=3681a9beddbae875
242d3c9965c56336=3681a9beddbae875
7709783584847053=3681a9beddbae875
