@echo off
REM ============================================================================
REM  Translation Manager — Windows EXE build
REM
REM  1) Reads Supabase URL + anon key from .env.build (gitignored) and
REM     generates translation_manager\auth\_baked.py (also gitignored) so
REM     the launcher boots out-of-the-box for end users without env vars.
REM  2) Builds the React frontend (npm run build) → frontend/dist/
REM  3) Bundles main_eel.py + translation_manager package + frontend/dist into
REM     a single TranslationManager.exe using PyInstaller.
REM
REM  Requirements (one-time):
REM     pip install -r translation_manager\requirements.txt
REM     cd frontend && npm install
REM
REM  Required local files:
REM     .env.build  — must contain SUPABASE_URL=... and SUPABASE_ANON_KEY=...
REM
REM  Output: dist\TranslationManager.exe
REM ============================================================================

setlocal enableextensions enabledelayedexpansion

cd /d "%~dp0"

echo.
echo === [1/4]  Baking Supabase config into translation_manager\auth\_baked.py ===
if not exist ".env.build" (
    echo [build_exe] .env.build is missing.
    echo            Create it with:
    echo                SUPABASE_URL=https://your-project.supabase.co
    echo                SUPABASE_ANON_KEY=sb_pub_xxx_or_legacy_jwt
    echo            Both files are gitignored and never committed.
    exit /b 1
)

REM Parse .env.build (lines like KEY=VALUE; ignore blanks and comments).
set "SUPABASE_URL="
set "SUPABASE_ANON_KEY="
for /f "usebackq tokens=1,* delims==" %%A in (".env.build") do (
    set "_line=%%A"
    if not "!_line:~0,1!"=="#" if not "!_line!"=="" (
        if /i "%%A"=="SUPABASE_URL"      set "SUPABASE_URL=%%B"
        if /i "%%A"=="SUPABASE_ANON_KEY" set "SUPABASE_ANON_KEY=%%B"
    )
)

if "%SUPABASE_URL%"=="" (
    echo [build_exe] .env.build is missing SUPABASE_URL — aborting.
    exit /b 1
)
if "%SUPABASE_ANON_KEY%"=="" (
    echo [build_exe] .env.build is missing SUPABASE_ANON_KEY — aborting.
    exit /b 1
)

REM Generate the _baked.py module Python's config.py imports if present.
REM Triple-quoted on its own lines so the values themselves can never
REM break Python tokenization, no matter what characters they contain.
> "translation_manager\auth\_baked.py" (
    echo # Auto-generated by build_exe.bat — DO NOT EDIT, DO NOT COMMIT.
    echo # Sourced from .env.build at PyInstaller time.
    echo SUPABASE_URL = r"""%SUPABASE_URL%"""
    echo SUPABASE_ANON_KEY = r"""%SUPABASE_ANON_KEY%"""
)
echo Baked _baked.py — URL ends with: %SUPABASE_URL:~-8% ^| KEY length: bytes-as-baked

echo.
echo === [1b/4]  Baking build id into translation_manager\_build_info.py ===
REM A fresh UTC timestamp every build. Baked into the launcher AND written to
REM the launcher_releases row on release — the in-app self-updater treats a
REM mismatch as "update available" even when the version string is unchanged
REM (the project re-releases in place as v1.1.0). PowerShell gives a
REM locale-independent timestamp, unlike %DATE%/%TIME%.
set "BUILD_ID="
for /f %%i in ('powershell -NoProfile -Command "[DateTime]::UtcNow.ToString('yyyyMMddHHmmss')"') do set "BUILD_ID=%%i"
if "%BUILD_ID%"=="" (
    echo [build_exe] could not generate BUILD_ID — aborting.
    exit /b 1
)
> "translation_manager\_build_info.py" (
    echo # Auto-generated by build_exe.bat — DO NOT EDIT, DO NOT COMMIT.
    echo # Build identity for the in-app self-updater's same-version detection.
    echo BUILD_ID = "%BUILD_ID%"
)
echo Baked _build_info.py — BUILD_ID=%BUILD_ID%

echo.
echo === [2/4]  Building React frontend (npm run build) ===
pushd frontend
call npm run build
if errorlevel 1 (
    echo.
    echo [build_exe] frontend build FAILED — aborting.
    popd
    exit /b 1
)
popd

if not exist "frontend\dist\index.html" (
    echo [build_exe] frontend\dist\index.html missing after npm run build — aborting.
    exit /b 1
)

echo.
echo === [3/4]  Cleaning previous PyInstaller output ===
if exist build      rmdir /s /q build
if exist dist       rmdir /s /q dist
REM Spec is hand-maintained (--onedir layout, see TranslationManager.spec).
REM Do NOT delete it here.

echo.
echo === [4/4]  Running PyInstaller (onedir, via spec) ===
REM Driven by TranslationManager.spec so the EXE + COLLECT split stays
REM under source control. Onedir layout writes:
REM   dist\TranslationManager\TranslationManager.exe   (thin bootstrap)
REM   dist\TranslationManager\_internal\...            (binaries + datas)
REM installer.iss bundles the whole directory tree so Inno Setup shows a
REM streaming progress bar instead of stalling on a single huge file.
python -m PyInstaller --noconfirm --clean TranslationManager.spec

if errorlevel 1 (
    echo.
    echo [build_exe] PyInstaller FAILED.
    exit /b 1
)

echo.
echo === BUILD SUCCESS ===
if exist "dist\TranslationManager\TranslationManager.exe" (
    for %%I in ("dist\TranslationManager\TranslationManager.exe") do echo Output: %%~fI   ^(%%~zI bytes^)
) else (
    echo [WARN] dist\TranslationManager\TranslationManager.exe not found — check PyInstaller output above.
    exit /b 1
)

echo.
echo Next step:  compile installer.iss with Inno Setup 6
echo            ^("%%ProgramFiles(x86)%%\Inno Setup 6\ISCC.exe" installer.iss^)
echo.

endlocal
exit /b 0
