[Main]
RealAppId=2483190
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=true

[Misc]
ExtraProtection=true
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[Hashes]
0=a9a3b25170f8b5e02654b5abf85f5505670c7ddb5dff3d1552859c179b9281113e33af1a9f8fdaa32d29ec8a7f27f2854c794f582e442c3ca202db810b164cda
