import json

# These are the items that need actual gender modifications
fixes = {
    "base|onscreens/onscreens_final.json|35088": "החזק <Input actionName=\"VisionHold\" color=\"Tutorial.InputHint\"></> כדי להפעיל את הסורק, ל",
    "base|onscreens/onscreens_final.json|40326": "הי, זה אני שוב! אתה עדיין מעוניין בעבודה? ליאם חזר לעיר והוא מתנהג יותר חשוד מרגיל :( עזרה..",
    "base|onscreens/onscreens_final.json|40401": "מזל טוב, V – הוכחת שאתה אחד משכירי החרב הטובים ביותר שלי. בגלל זה, אתה תקבל גיגים מכמה מהלקוחות הכי מהימנים שלי. מעריך את כל העבודה הקשה שעשית עד כה.",
    "base|onscreens/onscreens_final.json|43469": "לכולנו מגיע קצת תענוג בחיים. מצא את שלך עם ORGIATIC.",
    "base|onscreens/onscreens_final.json|43755": "החזק את <Input context=\"VehicleDrive\" actionName=\"Accelerate\" color=\"Tutorial.InputHint\"></> כדי לצאת מהמוסך.",
    "base|onscreens/onscreens_final.json|49359": "הצטייד בקוויקהאק 'פינג' במלאי שלך והעלה אותו למצלמה.",
    "base|onscreens/onscreens_final.json|49636": "מטרת הקוויקהאק שלך תמיד ממורכזת על המסך. השתמש ב-<Input context=\"UI_QuickHackPanel\" actionName=\"UI_MoveLeft\" color=\"Tutorial.InputHint\"></> וב-<Input context=\"UI_QuickHackPanel\" actionName=\"UI_MoveRight\" color=\"Tutorial.InputHint\"></> כדי לעבור בין מטרות סמוכות.",
    "base|onscreens/onscreens_final.json|49664": "בחר תו מהשורה או העמודה המודגשת ולחץ על <Input context=\"UIMenuShared\" actionName=\"click\" color=\"MainColors.Blue\"></> כדי לשלוח אותו למאגר.",
    "base|onscreens/onscreens_final.json|50049": "אתה צודק, זה תוכנית מציאות. Watson Whore אפילו לא משווה",
    "base|onscreens/onscreens_final.json|50207": "אני מבין. נראה שהוא לא כלב התקיפה הפראי היחיד בסיפור הזה",
    "base|onscreens/onscreens_final.json|51422": "תוכל לעבור בין מידע על מטרות סרוקות לבין פרטי קוויקהאק בעזרת <Input actionName=\"DescriptionChange\" color=\"Tutorial.InputHint\"></>.",
    "base|onscreens/onscreens_final.json|52133": "האויב מזוין בפצצה מפוצצת קלאסית. אל תתפזר מהם – אם אתה מוצא את עצמ",
    "base|onscreens/onscreens_final.json|52507": "רחף מעל קוויקהאק עם הסמן כדי לקרוא פרטים עליו. לחץ על <Input context=\"UIMenu\" actionName=\"click\" color=\"0099ff\"></> כדי להתקין אותו במשבצת פעילה בסייברדק שלך.",
    "base|onscreens/onscreens_final.json|52657": "בדוק פרטים על הפעילויות שנעקבות ויעדים ידועים",
    "base|onscreens/onscreens_final.json|52962": "סייברוור שנקנה וכרגע מצויד עליך. שתלים שאינם מצוידים ניתנים למכירה על ידי לחיצה על <Input context=\"UIMenu\" actionName=\"activate_secondary\" color=\"0099ff\"></> על הפריט.",
    "base|onscreens/onscreens_final.json|54135": "הגודל נכון... אבל למה אתה לא יכול להיפטר מהתחושה שזה עדיין צר מדי",
    "base|onscreens/onscreens_final.json|77908": "הוסף את זה לארון של וי כדי לחגוג את מהפכת נטול ה-DRM",
    "base|onscreens/onscreens_final.json|78553": "כן... החלק הגרוע ביותר הוא שאתה לעולם לא יודע מה מסוכן יותר – להתחבר לקורפוסים או להפוך אותך",
    "base|onscreens/onscreens_final.json|78756": "כברירת מחדל, תוכל לדלג על שורות דיאלוג בודדות על ידי לחיצה על <Input actionName=\"SceneFastForward\" color=\"Tutorial.InputHint\" hold=\"Hide\"></>. תוכל גם לשנות זאת בהגדרות ל\"רציף\", מה שיאפשר לך לדלג על מספר שורות ברצף על ידי לחיצה והחזקה של <Input actionName=\"SceneFastForward\" color=\"Tutorial.InputHint\" hold=\"Show\"></> עד שהכפתור ישוחרר.",
    "base|onscreens/onscreens_final.json|78943": "לכשאתה צריך משהו שיבטא את מצב הנשמה שלך.",
    "base|onscreens/onscreens_final.json|79384": "תירה, תהרוג, תזרוק. לא בדיוק מזכרת - אתה תזרוק את האומברה",
    "base|onscreens/onscreens_final.json|79545": "היי, זאת קלייר, ברמנית ב-Afterlife. הבר מלא שמועות עליך לאחרונה, אז חשבתי... תשמע",
    "base|onscreens/onscreens_final.json|79576": "חרא, V... היית צריך לחסל את מאוסר, לא סתם לעשות לו כאב ראש. סליחה, בלי תשלום על המהלך הזה",
    "base|onscreens/onscreens_final.json|79586": "אמרתי בלי דם לא מזדקק. שכחת? העבודה הסתיימה וסגרה, בטוח. אתה הצלת",
    "base|onscreens/onscreens_final.json|79643": "ויגה נרדם בקופסה, לא נפגעו אזרחים – ידעתי שאתה",
    "base|onscreens/onscreens_final.json|79688": "החבילה התקבלה. תודה, V. המשך לעבוד טוב. הרחובות יזכרו את שמך",
    "base|onscreens/onscreens_final.json|79713": "אתה רק אספת איזה כמות עצומה של אדיים, והחיות האלה רואות אדום. Se",
    "base|onscreens/onscreens_final.json|79729": "אולי אתה לא מודע, אבל הפעלת האזהרה וההעדרות אינן אותו דבר",
    "base|onscreens/onscreens_final.json|79732": "אני רואה שאתה לא שואל שאלות מיותרות, V. אתה פשוט עושה מה שמבקשים ממך. אני מעריצה תכונ",
    "base|onscreens/onscreens_final.json|79738": "היכנס ויוצא כמו אובדן, V. אף אחד במקדש אפילו לא ידע על הופעתך",
    "base|onscreens/onscreens_final.json|79809": "אתה מנסה אולי לא תשנה את העולם, אבל אתה עדיין יכול לשנות את המכונית שלך! אל קפיטן כאן כדי לעזור! הפעל",
    "base|onscreens/onscreens_final.json|79985": "תתעשה עד אז. תודה... שוב. זה באמת אומר לי הרבה",
    "base|onscreens/onscreens_final.json|80117": "ואני רוצה להגיד תודה, V. על שהיית איתי, על כל מה שעשית. ופשוט על שאתה זה ש",
    "base|onscreens/onscreens_final.json|80186": "נראה מה עוד אשמע ממך בעתיד. או עליך",
    "base|onscreens/onscreens_final.json|80201": "אתה מרוצה מפונקציית הירי האוטונומי? אנא קפוץ לאישור",
    "base|onscreens/onscreens_final.json|80217": "למה לא קצת להנאה? תכתוב לה בחזרה, תיתן לה את הכתובת של קובאצ'ק",
    "base|onscreens/onscreens_final.json|80238": "כן, הוא הופך לחזק יותר כל יום. אתה לא מצליח לדמיין כמה אנחנו מודים",
    "base|onscreens/onscreens_final.json|80304": "אני הולך לעשות את זה. מרגיש כמו הצעד הנכון עבורי. משלב את המשפחה",
    "base|onscreens/onscreens_final.json|80368": "זהו תשובה טובה אם ראיתי אחת! אתה זכאי לשקידה מיוחדת בגלל זה :",
    "base|onscreens/onscreens_final.json|80396": "אגב, תחזיק לי אצבעות. חושבת שאולי יש לי את החוזה הראשון שלי. ללקוח יש עד סוף",
    "base|onscreens/onscreens_final.json|80409": "ההה! אולי אני נופל עליך, אבל לא מהמגדל הזה. לא עכשיו",
    "base|onscreens/onscreens_final.json|81560": "אתה עובר את הגבול פעם אחת, רק פעם אחת... והחיים שלך הופכים למשהו גרוע. אני מסתיימת, V. אבל לפחות הלב שלי עדיין נוגד",
    "base|onscreens/onscreens_final.json|84041": "אתה מפעיל כל XBD שמצאת ברחוב? אוי, אני לא",
    "base|onscreens/onscreens_final.json|84919": "סודות מ-Edgerunners מחכים לך ברחובות נייט סיטי, אז צא לשם ומצא אותם",
    "base|onscreens/onscreens_final.json|86092": "אתה יכול לשמור עד 6 תלבושות במדף שלך. אפשר להפעיל אותן ב",
    "base|onscreens/onscreens_final.json|87382": "<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_0} RAM</> כשאתה מבטל יריב",
    "base|onscreens/onscreens_final.json|90913": "אתה גורם <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">-{float_0}% נזק רעל</>, אך",
    "base|onscreens/onscreens_final.json|91934": "כשאתה אוסף פריט מתכלה, הוא יתווסף אוטומטית",
    "base|onscreens/onscreens_final.json|92542": "<Rich color=\"MainColors.TutorialColor\" style=\"Bold\">שריון</> מציין את ההתנגדות שלך לנזק.\\n\\nאתה יכול להגדיל",
    "base|onscreens/onscreens_final.json|92756": "עכשיו אתה יכול לירות בנשקים ולפעיל סייברואר מהנוחות של הרכב שלך! השתמש ב-",
    "base|onscreens/onscreens_final.json|94515": "אין האקינג מהיר מותקן. פתח את התפריט של האקינג מהיר כדי להתקין אותם על הסייברדק",
    "base|onscreens/onscreens_final.json|95155": "נפגש ב-Lizzie's! רק תגיד ל-Matteo כשאתה מגיע והוא ישלח לי הודעה",
    "base|onscreens/onscreens_final.json|95369": "אני לא מכירה את הביטוי הזה, אבל זה נשמע כמו שהחיים היו מתוקים כמוך :",
    "base|onscreens/onscreens_final.json|95384": "אתה מדבר בדיחה! בדוגטאון יפרקו את התרטון שלי עד לברג האחרון",
    "base|onscreens/onscreens_final.json|96442": "היי היי! שמעתי על עבודה בשביל שכיר החרב הכי יפה בעיר, אם מעניין אותך. מכ",
    "base|onscreens/onscreens_final.json|96801": "המשחק האחרון הותיר אותך יותר מדי עייף לנהוג? תן ל-AutoDrive לנהוג במקומך!",
    "base|onscreens/onscreens_final.json|96917": "לא הייתי שואל אם לא הייתי חושבת שאתה הכי מתאים. מה אתה אומר",
    "base|onscreens/onscreens_final.json|17636": "ה-€$ הרגע נכנס. תהנה מזה וסע בזהירות!",
    "base|onscreens/onscreens_final.json|18773": "הייייי איך החיים ב-NC? מצליח לישון קצת? ובכן נחש מי לא? הבחור הזה. וכשאתה לא יכול לישון, אתה עושה עוד €$. הנה העניין – היוליה הקטנה והמתוקה שלי נעלמה מהרדאר (radio silent). לא ביג דיל, חוץ מהעובדה שהיא מחזיקה נתונים שאני צריך לעזאזל. תשיג אותה ותביא לי את זה. מפרט מצורף.",
    "base|onscreens/onscreens_final.json|18901": "הייי V! רוצה לעשות מעשה טוב ולהרוויח קצת €$ על הדרך? כל מה שאתה צריך לעשות זה לחלץ מישהו מאחיזתם של הטייגר קלוז (Tyger Claws) לפני שהם יקצצו אותו לחתיכות קטנטנות. אתה בעניין? פרטים מצורפים. אל תגרום לי להתחנן!",
    "base|subtitles/media/finalboards/fb_hanako_refused.json|1800967908251910144": "שישה חודשים יעברו מהר יותר ממה שאתה מדמיין. חבל לתת לזמן הזה ללכת לאיבוד",
    "base|subtitles/media/finalboards/fb_mitch.json|1801085141229748224": "אוקיי, כולנו תהינו מתי סוף סוף תקפוץ לבקר",
    "base|subtitles/media/finalboards/fb_panam.json|1790825019249840128": "מה אתה חשבת, הוי? או שלא חשבת בכלל? זה כל מה?",
    "base|subtitles/media/finalboards/fb_peralez.json|1801097369924386816": "מה היית אומר על להיות ראש צוות הביטחון שלי, ה?",
    "base|subtitles/media/finalboards/fb_rogue.json|1790870161553936384": "ג'וני, תראה – אני כבר מספיק מנוסה כדי לדעת שכולו אפשרי i",
    "base|subtitles/media/finalboards/fb_saul.json|1790933088948506624": "אום, שמעתי על רעש גדול שיצא מ-night city עם, אום, אתה מעורב",
    "base|subtitles/media/finalboards/fb_victor.json|1790848289349095424": "אז למעשה – מה אם תבוא פשוט כשתחזור לעיר, hm? Thi",
    "base|subtitles/media/fluff/safe_n_sound_02.json|1805356588127207424": "בלי צורך מוחלט, לעולם לא תהלך ברחובות נייט סיטי. Ins",
    "base|subtitles/media/fluff/ybimb_5.json|1752960302357995520": "אם אתה רוצה להיות בטוח, ואני מתכוונת באמת בטוח, השקע ב-Ofuda prote",
    "base|subtitles/media/quests/q001_01_arasaka_chip_debate.json|1795286079641468928": "האדם הזה... הוא לא יעזוב אותך לעולם, חבר נצחי בתוך המודעות שלך. תדמיין רק אם-",
    "base|subtitles/media/quests/sq006_05_debate.json|1800917441295663104": "ובכן, אולי תרצה לספר לנו כמה כסף אתה שומר באיי קיימן",
    "base|subtitles/media/radio/radio_01_conspiracy.json|2150517839495811072": "ובכן, אני חושב שאתה נראה כמו מאמין אמיתי, בן. תודה על הקריאה",
    "base|subtitles/media/radio/radio_growl.json|3662700775186554900": "שיט, אף פעם לא חשבתי שאצטרך להכריז על משהו כזה. תישאר עמנו: תדע עוד יותר כשתדענו יותר",
    "base|subtitles/media/radio/radio_growl.json|3662715170406981664": "ואתה יודע מה? אני מקווה שהבן זונה נפל צועק, באמת",
    "base|subtitles/open_world/community/e3_q110_bum_village_chat.json|1720064913590243328": "תנסה ותראה מה קורה, ביצית. כל השכונה לא שווה כלום חוץ ממלונות ריקים בכל מקרה",
    "base|subtitles/open_world/fixers/mr_hands_default.json|1959157768110665728": "קוראים לי מר הונדס. אם אתה מחפש עבודות בפacificא, קרא לי",
    "base|subtitles/open_world/fixers/wakako_okada_default.json|1904296690718883840": "יש לנו איזה עסק פתוח לסגור. זוכר את סנדרה דורסט",
    "base|subtitles/open_world/scenes/bls_east_017.json|2189664249187098624": "יודע מה? יש לי תחושה שהזוהמה הזאת זה מה שבאמת מדליק אותך",
    "base|subtitles/open_world/scenes/bls_east_020.json|2181051025136009216": "לא, עדיף להישאר רחוק מהרואות. אתה יודע מה הן יכולות לעשות.",
    "base|subtitles/open_world/scenes/bls_south_013.json|2181092625215086592": "אז היא סוף סוף זכרה שאתה קיים, הלאה? הפעם האחרונה שהגונק התנהג כאילו בכלל לא הכיר אותך",
    "base|subtitles/open_world/scenes/cct_cpz_chat_014.json|2171994564773666816": "הקשב, רציתי להיפגש כי יש לי משהו מאוד חשוב לספר לך",
    "base|subtitles/open_world/scenes/cct_cpz_chat_019.json|2189968258685571072": "מה אתה מתכוון, לא מותר כניסה?! תן לי להיכנס עכשיו! אני המפקדת כאן",
    "base|subtitles/open_world/scenes/cct_dtn_chat_003.json|1963337465011617792": "אתה פשוט צריך להעלות את הסיכון. נסה משהו נובה. תודה לי על זה",
    "base|subtitles/open_world/scenes/cct_dtn_chat_006.json|1963524457871687680": "תמשיך להגיד את זה לעצמך. אבל אתה לא תעשה עם זה כלום",
    "base|subtitles/open_world/scenes/cct_dtn_chat_006.json|1963524845559595008": "מה, אתה חושב שאחרי שעובד עם קורפו אתה פתאום בלתי נגע?",
    "base|subtitles/open_world/scenes/cct_dtn_chat_006.json|1963525119078547456": "גם את זה. אבל הסיבה העיקרית היא שלא תכופף את אחותך הקטנה מאחור",
    "base|subtitles/open_world/scenes/cct_dtn_chat_009.json|1964666471740850176": "אתם יודעים... אני באמת לא צריכה לספר לכם את זה... אבל ניצחתי את טום ברדלי על התפקיד",
    "base|subtitles/open_world/scenes/cct_dtn_chat_034.json|2180928470257483776": "אבל, אממ... אתה אמור לצאת אל העם, לתת למצביעים לראות אותך"
}

d = json.load(open('current_batch.json', encoding='utf-8'))
for k, v in d.items():
    if k in fixes:
        v['fixed_male'] = fixes[k]
    else:
        v['fixed_male'] = 'SKIP'

json.dump(d, open('current_batch.json', 'w', encoding='utf-8'), indent=1, ensure_ascii=False)
