# -*- coding: utf-8 -*-
import json

translations = {
    "129022": "מעצב אופנה מדהים",
    "129023": "עלייתו של הקיסר קטמה",
    "129024": "משבצת נהר",
    "129025": "משבצת נהר נווה מדבר",
    "129026": "קידוסי אניטוני:<br/>מפצח קודים יוצא דופן: חלק 2",
    "129027": "קידוסי אניטוני:<br/>מפצח קודים יוצא דופן: חלק 3",
    "129028": "קידוסי אניטוני:<br/>דברי הימים של אנבסה",
    "129029": "ניסיתי להציב את הטקסטים זה לצד זה, ויכולתי להבין כמה מהמילים. במיוחד את \"וואהה דשר\", שהכתב העתיק שלה מוכר לי מכיוון שהוא חרוט בכל מקום באורקל: <custom-entity tag=\"enbesan\"><custom-properties image=\"water\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"land\"/></custom-entity>. אנו מכנים את וואהה דשר \"ארץ המים\", והכתב העתיק שלה מורכב משני סמלים: אחד שנראה כמו מים, ואחד שנראה כמו הרים.",
    "129030": "המשך",
    "129031": "נסה שוב",
    "129032": "קח הפסקה",
    "129033": "הסכם",
    "129034": "מגדלור קידוסי אניטוני",
    "129035": "מגדלור וואהה דשר",
    "129036": "השפה הזו נראית פיגורטיבית — שבה המילים הן מה שהסימנים מייצגים. לדוגמה, <custom-entity tag=\"enbesan\"><custom-properties image=\"goods\"/></custom-entity> נראה כמייצג ארגז. לכן אני די בטוח ש-<custom-entity tag=\"enbesan\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity> פירושו \"סחורות\"!",
    "129037": "דוגמה נוספת: במשפט \"וואהה דשר מצמיחה צמחים לנצח\", ישנה קבוצת הסימנים הזו: <custom-entity tag=\"enbesan\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity>. האם תוכל לנחש לאזו מילה היא מתייחסת?",
    "129038": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"unit\"/></custom-entity> חייב לומר \"לנצח\".",
    "129039": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"unit\"/></custom-entity> חייב לומר \"צמחים\".",
    "129040": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"unit\"/></custom-entity> חייב לומר \"לצמוח\".",
    "129041": "הסימן הזה, <custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity>, נראה כמצביע על צורת רבים. אם כך, זה חייב לומר ש-<custom-entity tag=\"enbesan\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity> אינו 'אדמה' אלא 'צמחים'.",
    "129042": "\"צמחים\", אכן! כפי שאתה רואה, הסימן כשלעצמו אינו מספיק כדי לייצג 'צמחים' לבדו, ולכן הכתב העתיק הוסיף שם שני סמלים: <custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity> כדי לציין את הרבים, ו-<custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity> בסוף כדי לציין שמדובר בשם עצם.",
    "129043": "עוד אחד! בתמליל שהבאת לי, מצאתי את אותו סימן <custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity> המצביע על שם עצם, ישות פיזית. הוא היה חלק מהמילה <custom-entity tag=\"enbesan\"><custom-properties image=\"land\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity> — אך האם תוכל לנחש מה פירושו?",
    "129044": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"land\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"unit\"/></custom-entity> חייב לומר \"אדמה\".",
    "129045": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"land\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"unit\"/></custom-entity> חייב לייצג \"הרים\".",
    "129046": "אתה מתחיל להבין! מילה אחת אחרונה לפני שנקח הפסקה. זיהיתי את המילה \"שבועה\" ב-<custom-entity tag=\"enbesan\"><custom-properties image=\"holy\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"wind\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"head\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity>, שבה <custom-entity tag=\"enbesan\"><custom-properties image=\"holy\"/></custom-entity> נראה כמתייחס לכל דבר קדוש, טהור, או לפחות קשור לאלים, ו-<custom-entity tag=\"enbesan\"><custom-properties image=\"wind\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"head\"/></custom-entity> מתייחס לדיבור, מכיוון שהוא נראה כמו נשימה וראש אדם. לאחר מכן, בתמליל של הספרייה הישנה שהבאת לי, הייתה המילה <custom-entity tag=\"enbesan\"><custom-properties image=\"holy\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity>. יש לך מושג מה זה יכול להביע?",
    "129047": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"holy\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"unit\"/></custom-entity> פירושו... \"סחורות קדושות\"?",
    "129048": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"holy\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"unit\"/></custom-entity> חייב לומר \"מתנות האלים\".",
    "129049": "פיקח מאוד! תרגום ספרותי יותר יהיה קרוב יותר ל-'חפצי פולחן', לדעתי, אך עלינו למצוא תחילה את המשמעות הפרטנית של הסימנים לפני שנשייך משמעויות משולבות או הקשריות. הסימן <custom-entity tag=\"enbesan\"><custom-properties image=\"holy\"/></custom-entity> נראה כמתקן טקסטואלי, המגדיר את המילה הקודמת כקדושה או מקודשת. פריצת דרך קלה! זמן להוסיף עוד תה לקומקום, ואז נוכל להמשיך בתרגום — אמתין לשובך!",
    "129050": "לא, זה לא יכול להיות נכון. 'אלים' ייכתב <custom-entity tag=\"enbesan\"><custom-properties image=\"holy\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"human\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity> - מילולית, זה יהיה 'ישויות אנושיות קדושות'. אך כאן מוזכרות סחורות, כך שבמקום שם העצם, <custom-entity tag=\"enbesan\"><custom-properties image=\"holy\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity> חייב להיות תואר, עבור 'חפצי פולחן'.",
    "129051": "זה יכול היה להביע הרים, אילו היה <custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity> בין שני הסימנים. אך לעת עתה, עלינו להניח ש-<custom-entity tag=\"enbesan\"><custom-properties image=\"land\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity> פירושו \"אדמה\", או \"הר\", אולי.",
    "129052": "אני בטוח כעת ש-<custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity> נמצא תמיד כסיומת לשם עצם, ולא אחרי פעלים. לפיכך, אני מסתפק אם <custom-entity tag=\"enbesan\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity> יכול להיות 'לצמוח'. הייתי מעז לנחש שמדובר ב-'צמחים'.",
    "129053": "מצאתי משהו נוסף. <custom-entity tag=\"enbesan\"><custom-properties image=\"arms\"/></custom-entity> ו-<custom-entity tag=\"enbesan\"><custom-properties image=\"legs\"/></custom-entity> נראים כקשורים לפעולות... פעלים? כמו מילה זו בתמליל הספרייה הישנה: <custom-entity tag=\"enbesan\"><custom-properties image=\"water\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"legs\"/></custom-entity>, שנראית כבעלת משמעות של \"לנווט\", ו-<custom-entity tag=\"enbesan\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"legs\"/></custom-entity> \"להוביל\". זיהיתי גם את המילה הבאה על אבן השבועה: <custom-entity tag=\"enbesan\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"high\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"arms\"/></custom-entity>. מה לדעתך היא אומרת?",
    "129054": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"high\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"arms\"/></custom-entity> פירושו \"להריח\".",
    "129055": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"high\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"arms\"/></custom-entity> פירושו \"לחיות\".",
    "129056": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"high\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"arms\"/></custom-entity> פירושו \"לשתול\".",
    "129057": "הפועל 'להריח' ייכתב ככל הנראה עם הסימן <custom-entity tag=\"enbesan\"><custom-properties image=\"head\"/></custom-entity> בסוף המילה. אך כאן, יש לנו <custom-entity tag=\"enbesan\"><custom-properties image=\"arms\"/></custom-entity>, המייצג פעולה המבוצעת עם ידיים. <custom-entity tag=\"enbesan\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"high\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"arms\"/></custom-entity> הוא כנראה פועל, או 'שתילה' או 'גידול'.",
    "129058": "ערך מטאפורי, אם כן? מעניין! אך הסימן <custom-entity tag=\"enbesan\"><custom-properties image=\"arms\"/></custom-entity> פירושו בבירור \"לעשות\", כך שההצעה שלך אינה יכולה להיות נכונה לחלוטין. הייתי מהמר ש-<custom-entity tag=\"enbesan\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"high\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"arms\"/></custom-entity> פירושו \"לשתול\", או \"לגדל\".",
    "129059": "כמעט נכון! נראה ש-<custom-entity tag=\"enbesan\"><custom-properties image=\"high\"/></custom-entity> מצביע על כיוון כלפי מעלה, ולכן כאן \"לגדל\" נראה כתרגום הולם יותר עבור אבן השבועה שלנו.",
    "129060": "כעת יש לנו את המשפט הזה:<br/><br/><custom-entity tag=\"enbesan\"><custom-properties image=\"with\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"predator\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"land\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"water\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"human\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"arms\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"one\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"land\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"water\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"sun\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"land\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"eternity\"/></custom-entity><br/><br/>הוא מקביל למשפט \"ואנבסה מציעה את סחורות האדמה לקאשטה לנצח\". האם תוכל לזהות את קבוצת הסימנים שפירושה \"מציעה\"?",
    "129061": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"land\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"goods\"/></custom-entity> פירושו \"מציעה\".",
    "129062": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"water\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"human\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"arms\"/></custom-entity> פירושו \"מציעה\".",
    "129063": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"unit\"/></custom-entity> פירושו \"מציעה\".",
    "129064": "<custom-entity tag=\"enbesan\"><custom-properties image=\"land\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"goods\"/></custom-entity> מסתווה ב-<custom-entity tag=\"enbesan\"><custom-properties image=\"goods\"/></custom-entity>, ולכן הפועל שאנו מחפשים צריך להסתיים בסמל הביצועי <custom-entity tag=\"enbesan\"><custom-properties image=\"arms\"/></custom-entity>. מה שאנו יכולים לקבוע בוודאות הוא ש-<custom-entity tag=\"enbesan\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"water\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"human\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"arms\"/></custom-entity> פירושו כמעט בוודאות 'להציע'.",
    "129065": "ניחוש טוב! הפועל <custom-entity tag=\"enbesan\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"water\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"human\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"arms\"/></custom-entity> נכתב בצורה מורכבת יותר. כאן, <custom-entity tag=\"enbesan\"><custom-properties image=\"water\"/></custom-entity> מצביע על כיוון, ואחריו משהו שנראה כמייצג אדם, כך שזו הפעולה של אספקת סחורות למישהו.",
    "129066": "הפעלים האלה עובדים כמו שמות העצם, בסופו של דבר! אך יש אחד שטרם זיהיתי. במשפט השני, <custom-entity tag=\"enbesan\"><custom-properties image=\"time\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"wind\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"head\"/></custom-entity> מקביל למילה \"אמר\". אני רואה את <custom-entity tag=\"enbesan\"><custom-properties image=\"wind\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"head\"/></custom-entity> שנראה כבעל משמעות של \"לדבר\", אך מה לדעתך מייצג הסימן הראשון <custom-entity tag=\"enbesan\"><custom-properties image=\"time\"/></custom-entity>?",
    "129067": "אולי שעון חול?",
    "129068": "שני כוחות מנוגדים?",
    "129069": "מינרל?",
    "129070": "כמובן! שעון החול שבו השתמשו למדידת זמן חייב להצביע על אירועי העבר בכתב העתיק! אני תוהה באיזה סמל הם משתמשים כדי לציין את העתיד, אם כן? בכל אופן, זמן להפסקה נוספת. אני חושב שאנו מתקרבים לפיצוח הכתב העתיק!",
    "129071": "הכתב העתיק נראה כמורכב מסמלים קונקרטיים ופרגמטיים למדי, כמו השמש <custom-entity tag=\"enbesan\"><custom-properties image=\"sun\"/></custom-entity>, זרועות <custom-entity tag=\"enbesan\"><custom-properties image=\"arms\"/></custom-entity>, אנושי <custom-entity tag=\"enbesan\"><custom-properties image=\"human\"/></custom-entity> וכו'. לכן זה חייב להתייחס למעין פריט כלשהו ששימש לפני זמן רב. <custom-entity tag=\"enbesan\"><custom-properties image=\"time\"/></custom-entity> אני חושב שהוא שעון חול, שפירושו ככל הנראה 'זמן' ובאופן עקיף מציין את זמן העבר — כן, זה נשמע נכון! ובכן, נקח הפסקה ונחזור לזה עם ראש צלול יותר — העתקה היא עסק צמא!",
    "129072": "אין אזכורים במיתוסים על פעילות כרייה כלשהי בסיל'אמידוש. התכשיטים שהיו להם היו בהשפעה קאשטנית. אני חושב שהכתב העתיק היה משתמש במילה מורכבת לכל דבר ממקור זר, במקום בסמל ייחודי. לכן זה כאן, <custom-entity tag=\"enbesan\"><custom-properties image=\"time\"/></custom-entity>, חייב להיות שעון חול — שפירושו זמן — וגם ייתכן, בהתחשב במה שיש לנו כאן, ששימש לציון זמן עבר! אה, נפלא! אחרי פריצת דרך שכזו, אני חושב שעלינו לקחת הפסקה קצרה.",
    "129073": "אולי תזכור ש-<custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity> הוא סמן המשמש לסימון מבנה כשם עצם, בעוד שאנו מחפשים כעת פועל. <custom-entity tag=\"enbesan\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity> פירושו 'סחורות', כפי שקבענו. לכן זה כאן, <custom-entity tag=\"enbesan\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"water\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"human\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"arms\"/></custom-entity> חייב אפוא להביע 'מנחות' או 'מציעה'.",
    "129074": "כבר למדנו על הפעלים ושמות העצם שלהם, אך יש עוד דברים שאנו יכולים לדלות מאבן שבועה זו. ישנו סימן נוסף: <custom-entity tag=\"enbesan\"><custom-properties image=\"emotion\"/></custom-entity>, שנראה שאינו תואם שמות עצם ולא פעלים. הוא מופיע בקבוצת הסימנים <custom-entity tag=\"enbesan\"><custom-properties image=\"predator\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"emotion\"/></custom-entity>. שם, הסימן <custom-entity tag=\"enbesan\"><custom-properties image=\"predator\"/></custom-entity> נראה כמתייחס לכפה של חיה מסוכנת, כמו אריה. לכן, אני מאמין ש-<custom-entity tag=\"enbesan\"><custom-properties image=\"predator\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"emotion\"/></custom-entity> פירושו \"מסוכן\", כפי שהוא מופיע במשפט \"קאשטה, מסוכן לכל\".",
    "129075": "ישנו גם אותו סימן במשפט האחרון, אך בקבוצת מילים אחרת: <br/><custom-entity tag=\"enbesan\"><custom-properties image=\"holy\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"wind\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"head\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"time\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"wind\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"head\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"emotion\"/></custom-entity>. <br/><br/>\"שבועה\", שכבר ראינו יחד, מקבילה לארבעת הסימנים הראשונים <custom-entity tag=\"enbesan\"><custom-properties image=\"holy\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"wind\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"head\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity>. אני מאמין ש-<custom-entity tag=\"enbesan\"><custom-properties image=\"emotion\"/></custom-entity> מצביע על תואר השם כמו ב-\"מסוכן\". למה לדעתך מתורגם <custom-entity tag=\"enbesan\"><custom-properties image=\"time\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"wind\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"head\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"emotion\"/></custom-entity>?",
    "129076": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"time\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"wind\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"head\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"emotion\"/></custom-entity> מתורגם ל-\"הוקשב\"",
    "129077": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"time\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"wind\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"head\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"emotion\"/></custom-entity> מתורגם ל-\"מדובר\".",
    "129078": "לא, זה לא יכול להיות זה. ב-<custom-entity tag=\"enbesan\"><custom-properties image=\"time\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"wind\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"head\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"emotion\"/></custom-entity>, אנו רואים את <custom-entity tag=\"enbesan\"><custom-properties image=\"time\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"wind\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"head\"/></custom-entity> שלגביו הסכמנו שיהיה 'אמר', בשל סמן זמן העבר. הוספת <custom-entity tag=\"enbesan\"><custom-properties image=\"emotion\"/></custom-entity> לא אמורה לשנות את משמעותו הבסיסית, אלא את הקטגוריה הדקדוקית של המילה. לכן <custom-entity tag=\"enbesan\"><custom-properties image=\"time\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"wind\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"head\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"emotion\"/></custom-entity> עם סמן עבר זה יהיה 'מדובר'.",
    "129079": "ניתוח יפה! <custom-entity tag=\"enbesan\"><custom-properties image=\"time\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"wind\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"head\"/></custom-entity> היא מילה שכבר פגשנו בעבר, שפירושה \"לומר\". על ידי הוספת <custom-entity tag=\"enbesan\"><custom-properties image=\"emotion\"/></custom-entity> בסוף, היא הופכת ל-\"מדובר\". נתקלתי במילה אחרת בתמליל הספרייה הישנה המשתמשת באותו סמל: <custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"emotion\"/></custom-entity>. אותה הייתי מתרגם כ-\"עשיר\".",
    "129080": "ישנם כמה סימנים שאיני מצליח להבין בדיוק מה הם מייצגים, כמו <custom-entity tag=\"enbesan\"><custom-properties image=\"one\"/></custom-entity> ו-<custom-entity tag=\"enbesan\"><custom-properties image=\"in\"/></custom-entity>. אני מאמין שאם סימן הוא קטן למדי ואיבד את דמיונו למה שייצג בתחילה, הרי שהסימן הזה היה בשימוש תדיר, והכתב שלו פושט במהלך השנים כדי להקל על הלבלרים.",
    "129081": "לדוגמה, אנו מוצאים את <custom-entity tag=\"enbesan\"><custom-properties image=\"one\"/></custom-entity> בקבוצת המילים <custom-entity tag=\"enbesan\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"one\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"land\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity>. קבוצת מילים זו מופיעה במשפט \"ואנבסה מציעה את סחורות האדמה לקאשטה לנצח.\". מה לדעתך פירוש הסימן <custom-entity tag=\"enbesan\"><custom-properties image=\"one\"/></custom-entity>?",
    "129082": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"one\"/></custom-entity> פירושו \"ה-\" (הא הידיעה)?",
    "129083": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"one\"/></custom-entity> פירושו \"של\"!",
    "129084": "אה, אני חושש שלא... הכתב העתיק הוא שפה ללא יידוע ביחיד — הוא אינו משתמש בתוויות יידוע כמו 'ה-' או 'אחד' בצורת היחיד. ברבים, כמובן, זה יהיה <custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity>, אך ביחיד זה מובן מאליו. לא, זה חייב להיות מילה אחרת. אולי שייכות (גניטיב)? כן, 'של' יהיה הגיוני כאן.",
    "129085": "בדיוק! <custom-entity tag=\"enbesan\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"one\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"land\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity> מקביל ל-\"סחורות האדמה\", או ליתר דיוק, \"תוצרת חקלאית\" בלשוננו. <custom-entity tag=\"enbesan\"><custom-properties image=\"one\"/></custom-entity> עובד כמו מילת קישור. ישנן אחרות, כמו <custom-entity tag=\"enbesan\"><custom-properties image=\"in\"/></custom-entity> שפירושה \"בתוך\", ו-<custom-entity tag=\"enbesan\"><custom-properties image=\"by\"/></custom-entity> שפירושה \"על ידי\".",
    "129086": "כעת, נראה כי אנשים, דמויות ושמות פרטיים אינם מוגדרים על ידי <custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity>, אלא על ידי <custom-entity tag=\"enbesan\"><custom-properties image=\"human\"/></custom-entity>. כמו כן, שמות נכתבים בצורה מפושטת, אך שומרים על משמעות. לדוגמה, תהרקה, מלך קאשטה באותה תקופה, נכתב <custom-entity tag=\"enbesan\"><custom-properties image=\"cut\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"through\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"human\"/></custom-entity>. באופן משעשע, שמו נראה כמייצג סכין החותכת דרך משהו - אולי הוא היה חרחרן מלחמה נורא? או מתנקש? בכל אופן, ישנה דמות נוספת ששמה נזכר כאן: שבה, שנכתב <custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"one\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"human\"/></custom-entity>. כפי שניתן לראות, <custom-entity tag=\"enbesan\"><custom-properties image=\"one\"/></custom-entity> מופיע כאן שוב, אחרי <custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity>. למה לדעתך שמה מתורגם?",
    "129087": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"one\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"human\"/></custom-entity> יכול להתרגם ל-\"רבת-צמחים\"... ?",
    "129088": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"one\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"human\"/></custom-entity> יכול להתרגם ל-\"עשירת-צמחים\"?",
    "129089": "אני לא חושב כך. שם שפירושו 'רבת-צמחים' לא היה נכתב כך, אלא <custom-entity tag=\"enbesan\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"human\"/></custom-entity>. כאן, מכיוון ש-<custom-entity tag=\"enbesan\"><custom-properties image=\"one\"/></custom-entity> בא אחרי <custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity>, זה אומר שאת <custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity> יש לתרגם כ-'עשיר'. לפיכך, <custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"one\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"human\"/></custom-entity> יהפוך ל-'עשירת-צמחים'.",
    "129090": "בדיוק! כאן, מכיוון ש-<custom-entity tag=\"enbesan\"><custom-properties image=\"one\"/></custom-entity> בא אחרי <custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity>, זה אומר שאת <custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity> יש לתרגם כ-'עשיר'. זה שגוי מבחינה דקדוקית — \"עשיר\" צריך להיכתב <custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"emotion\"/></custom-entity>, אך שמות הם בבירור שגויים מבחינה דקדוקית בכל מקרה!",
    "129091": "עשינו זאת! באמת הערכתי את שיתוף הפעולה שלנו כאן. כתבתי את כל הכללים בספר קטן. הוא עבורך, אם תסכים להביא אותו לחוקר! היהירות שלו אמורה להיעלם למשך זמן מה!",
    "129092": "נקודת ציון",
    "129093": "נקודת ציון",
    "129098": "הקיסר קטמה מעיר על המחלה המתפשטת ברחובותיך.",
    "129099": "הקיסר קטמה מתייחס למהומות המתרחשות בעירך.",
    "129100": "הקיסר קטמה מעיר על התופת המשתוללת ברחובותיך.",
    "129101": "הקיסר קטמה מעיר על תהלוכת המים היפה הזורמת באנבסה.",
    "129102": "הקיסר קטמה מאוכזב שבאת להגדיל את שעות העבודה של אנשיך.",
    "129103": "החוקר מזכיר לך לאסוף את תוצאות המחקר שלהם.",
    "129104": "החוקר מדווח שפיתוח הפריט הושלם.",
    "129105": "החוקר מדווח שאישור הרחבת הקמפוס מוכן לאיסוף.",
    "129106": "החוקר מדווח שהם השיגו תגלית חשובה.",
    "129108": "הקיסר קטמה מברך את החוקרים שלך על התגלית החשובה.",
    "129110": "הארמון הקיסרי",
    "129111": "כנסיית לה קורונה",
    "129112": "האנדרטה לשבעה",
    "129113": "חומות חצר הארמון",
    "129114": "קשת סורייה",
    "129115": "מקדש עילם",
    "129116": "קיר עתיק",
    "129117": "קיר עתיק",
    "129118": "קונסוליית הכתר באנבסה",
    "129119": "מנזר טבורימה",
    "129120": "מקדש טבורימה",
    "129121": "האקדמיה הצבאית הקיסרית",
    "129122": "מכון המחקר של הארמון",
    "129123": "הגנים הקיסריים",
    "129124": "חווה חדשה",
    "129125": "גנים בוטניים",
    "129126": "אדמירליות המסחר",
    "129127": "הגנות צבאיות",
    "129129": "דברי הימים של אנבסה של בניאם",
    "129130": "אסוף את דברי הימים של אנבסה ב-[AssetData([Conditions QuestCondition Context]) Text]",
    "129131": "מסור את המילון אל [AssetData([Conditions QuestCondition ExecutionObject]) Text]",
    "129132": "בניאם מעוניין ללעוג לחוקר על ידי הצגת הוכחה לעבודתך פורצת הדרך.",
    "129133": "בניאם מוכן להפקיד את המילון בידיך.",
    "129134": "החוקר שואל על התקדמותך בפיענוח הכתב העתיק.",
    "129135": "החוקר בוחן את כתב היד, וממאן להאמין לדיוקו.",
    "129136": "הישג בעל ממדים היסטוריים! מעולם לא נעשה מאמץ כזה בעבר, ובוודאי שלא בהצלחה כה מדהימה! פיענוח שפה עתיקה אינו משימה טריוויאלית, וישנם אך מעטים בהיסטוריה שהיו בעלי מיומנות מספקת כדי להצליח בהבהרת הכתב האנבסאי העתיק, המורכב להפליא! כל שנותר הוא למסור את תוצאות עמלך לחוקר בקידוסי אניטוני, תוך הבטחת עותק של רשימותיך לאוצר הידע האישי שלך.",
    "129139": "קידוסי אניטוני:<br/>והמדבר ייקח את הכל",
    "129140": "קידוסי אניטוני:<br/>ברית מופרת",
    "129141": "החוקר מציע את עזרתו בתרגום קיר הספרייה הישנה.",
    "129151": "<b>בלשנות</b><br/>פענח את הכתובת שנלקחה מהקיר העתיק!",
    "129152": "ובכן, בוא נעיף מבט בחריטת הקיר... היא מייצגת שתי דמויות — אחת מחזיקה בתכשיטים של וואהה דשר, והשנייה נראית כמו כוהן מקידוסי אניטוני, עם קעקוע הפנים שלהם. קערה של צמחים מוצגת ביניהם, ומסמלת חילופין.",
    "129155": "המשך",
    "129156": "אני יכול לקרוא את הטקסט שמעל החריטה, הודות למילון של בניאם:<br/>\"שנה 8 לשבה, היא-הפורחת-פרחים. המלכה אמרה:\"<br/>אם כן, זה מתוארך לשנותיה הראשונות של אנבסה! עדות מתחילת תור הזהב! הטקסט ממשיך...",
    "129157": "להלן הנאום שנשאה המלכה:<br/>\"מי ייתן ומסחר ראשון זה יחתום את תחילתה של ידידות נצח<br/>בין שתי ה-<custom-entity tag=\"enbesan\"><custom-properties image=\"land\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"one\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"human\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"human\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"human\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity> שגברים אלו מייצגים.\"<br/>אה, איני בטוח לגבי המילה כאן... 'מדינות' או 'עמים' נראה הכי ברור מאליו, אך זה לא מתאים לסצנה המיוצגת על הקיר.",
    "129158": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"land\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"one\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"human\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"human\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"human\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"unit\"/></custom-entity> מתייחס ל-\"איים\".",
    "129159": "חשבתי שהכתב העתיק יבחין בין שתי המילים בצורה ברורה יותר. אך בוא נמשיך:<br/>\"... בין שני האיים המפוארים שגברים אלו מייצגים.<br/>שכן האחד זקוק לצמחי האלמוות עבור ה-<custom-entity tag=\"enbesan\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"water\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"human\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"arms\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"one\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"life\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity> שלהם\"<br/>אני חושב שהסמל הזה בסוף נראה כמו ענף, המוחזק בידי כוהנים בתור הזהב. סמל לדת? לפחות אני חושב שאני מזהה \"מנחה\", או \"מתנה\", בתחילת המילה.",
    "129160": "אם <custom-entity tag=\"enbesananswer\"><custom-properties image=\"life\"/></custom-entity> מתייחס לצמחים מיוחדים, הרי ש-<custom-entity tag=\"enbesananswer\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"water\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"human\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"arms\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"unit\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"one\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"life\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"unit\"/></custom-entity> חייב להביע 'טקסים'.",
    "129161": "'מנחה של צמחים מיוחדים' אתה אומר? אילו היו קדושים, האם <custom-entity tag=\"enbesan\"><custom-properties image=\"holy\"/></custom-entity> לא היה נכלל גם כן? хממ. בוא נבטח באינסטינקט שלך, אם כן. הטקסט קרוב להשלמה:<br/>\"שכן האחד זקוק לצמחי האלמוות עבור טקסיו<br/>בעוד שהשני, <custom-entity tag=\"enbesan\"><custom-properties image=\"holy\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"water\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"human\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"arms\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"human\"/></custom-entity>, זקוק לשדות כדי לעבדם.\"<br/>המילה האחרונה הזו היא ברבים, כלומר קבוצה של אנשים, אך מה המשמעות המדויקת... כאן, מה דעתך על כך? יש לי תחושה שעלולות להיות השלכות קשות למה שנחשוף כאן.",
    "129162": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"holy\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"water\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"human\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"arms\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"human\"/></custom-entity> חייב להביע \"כוהנים\".",
    "129163": "\"מי ייתן ומסחר ראשון זה יחתום את תחילתה של ידידות נצח<br/>בין שני האיים המפוארים שגברים אלו מייצגים.<br/>שכן האחד זקוק לצמחי האלמוות עבור טקסיו<br/>בעוד שהשני, הכוהנים, זקוקים לשדות כדי לעבדם.\"<br/>משמעות הדבר היא שכוהני קידוסי אניטוני גידלו את החסד האלמותי עבור כוהני וואהה דשר! אני מקווה שתשקול את כובד המשקל של טענה זו. האם אתה באמת חושב שזה נכון?",
    "129164": "תרגום זה נכון.",
    "129165": "אם כן, ארשום זאת רשמית, ואקווה לטוב.",
    "129166": "התמודד עם ההשלכות",
    "129167": "הייתי מנסה שוב — משהו נראה לי שגוי.",
    "129168": "בחירה נבונה. אני מאמין שעשינו מספר טעויות. מצא אותי מתי שתהיה מוכן.",
    "129169": "הסכם להתחיל מחדש את התרגום",
    "129170": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"holy\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"water\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"human\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"arms\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"human\"/></custom-entity> חייב להביע \"חקלאים\".",
    "129171": "\"מי ייתן ומסחר ראשון זה יחתום את תחילתה של ידידות נצח<br/>בין שני האיים המפוארים שגברים אלו מייצגים.<br/>שכן האחד זקוק לצמחי האלמוות עבור טקסיו<br/>בעוד שהשני, החקלאים, זקוקים לשדות כדי לעבדם.\"<br/>משמעות הדבר היא שחקלאי וואהה דשר גידלו את החסד האלמותי כדי שכוהני קידוסי יוכלו לבצע את טקסיהם. תזה מעניינת עבור הכוהנת הגדולה, אך משהו מרגיש לא תקין. האם אתה עדיין חושב שזה נכון?",
    "129172": "אם כן, ארשום זאת רשמית. זה אמור להשביע את רצונה של הכוהנת הגדולה.",
    "129173": "בחירה נבונה. אני מאמין גם כן שעשינו כמה טעויות. מצא אותי מתי שתהיה מוכן.",
    "129174": "אם <custom-entity tag=\"enbesananswer\"><custom-properties image=\"life\"/></custom-entity> פירושו 'חיים', הרי ש-<custom-entity tag=\"enbesananswer\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"water\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"human\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"arms\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"unit\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"one\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"life\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"unit\"/></custom-entity> חייב להביע 'בריאות'.",
    "129175": "'מנחת חיים', אתה אומר? תיאור פיוטי של בריאות אכן! ובכן — בוא נבטח באינסטינקט שלך. איננו רחוקים מהשלמת הטקסט כעת:<br/>'שכן האחד זקוק לצמחי האלמוות לבריאותו<br/>בעוד שהשני, <custom-entity tag=\"enbesan\"><custom-properties image=\"holy\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"water\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"human\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"arms\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"human\"/></custom-entity>, זקוק לשדות כדי לעבדם.'<br/>המילה האחרונה הזו היא ברבים, עבור קבוצה של אנשים, אך מה המשמעות המדויקת...? אולי יש לך מושג? יש לי תחושה שעלולות להיות השלכות קשות למה שנחשוף כאן.",
    "129176": "\"מי ייתן ומסחר ראשון זה יחתום את תחילתה של ידידות נצח<br/>בין שני האיים המפוארים שגברים אלו מייצגים.<br/>שכן האחד זקוק לצמחי האלמוות לבריאותו<br/>בעוד שהשני, הכוהנים, זקוקים לשדות כדי לעבדם.\"<br/>משמעות הדבר היא שכוהני קידוסי אניטוני גידלו את החסד האלמותי כדי לרפא את אנשי וואהה דשר! אני מקווה שתשקול את כובד המשקל של טענה זו. האם אתה באמת חושב שזה נכון?",
    "129178": "בחירה נבונה. אני מאמין שעשינו טעות במקום כלשהו. מצא אותי מתי שתהיה מוכן.",
    "129179": "\"מי ייתן ומסחר ראשון זה יחתום את תחילתה של ידידות נצח<br/>בין שני האיים המפוארים שגברים אלו מייצגים.<br/>שכן האחד זקוק לצמחי האלמוות לבריאותו<br/>בעוד שהשני, החקלאים, זקוקים לשדות כדי לעבדם.\"<br/>משמעות הדבר היא שחקלאי וואהה דשר גידלו את החסד האלמותי עבור כוהני קידוסי אניטוני לצורך תרופה. תזה מעניינת עבור הכוהנת הגדולה, אך משהו מרגיש לא תקין. האם אתה עדיין חושב שזה נכון?",
    "129180": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"land\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"one\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"human\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"human\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"human\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"many\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"unit\"/></custom-entity> מתייחס ל-\"מדינות\".",
    "129181": "זה נשמע נכון... אך אז הדמות עם התכשיטים היא מקאשטה? בוא נמשיך:<br/>\"... בין שני האיים המפוארים שגברים אלו מייצגים.<br/>שכן האחד זקוק לצמחי האלמוות עבור ה-<custom-entity tag=\"enbesan\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"water\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"human\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"arms\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"one\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"life\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity> שלהם\"<br/>אני חושב שהסמל הזה בסוף נראה כמו ענף, המוחזק בידי כוהנים בתור הזהב. סמל לדת? לפחות אני חושב שאני מזהה \"מנחה\", או \"מתנה\", בתחילת המילה.",
    "129182": "\"מי ייתן ומסחר ראשון זה יחתום את תחילתה של ידידות נצח<br/>בין שתי המדינות המפוארות שגברים אלו מייצגים.<br/>שכן האחד זקוק לצמחי האלמוות עבור טקסיו<br/>בעוד שהשני, הכוהנים, זקוקים לשדות כדי לעבדם.\"<br/>משמעות הדבר היא שכוהני קידוסי אניטוני גידלו את החסד האלמותי עבור כוהני קאשטה! אני מקווה שתשקול את כובד המשקל של טענה זו. האם אתה באמת חושב שזה נכון?",
    "129183": "\"מי ייתן ומסחר ראשון זה יחתום את תחילתה של ידידות נצח<br/>בין שתי המדינות המפוארות שגברים אלו מייצגים.<br/>שכן האחד זקוק לצמחי האלמוות עבור טקסיו<br/>בעוד שהשני, החקלאים, זקוקים לשדות כדי לעבדם.\"<br/>משמעות הדבר היא שחקלאי וואהה דשר גידלו את החסד האלמותי עבור כוהני קאשטה? איני חושב שתרגום זה נכון, אך לכוהנת הגדולה לא יהיה אכפת. האם אתה עדיין חושב שזה נכון?",
    "129184": "\"מי ייתן ומסחר ראשון זה יחתום את תחילתה של ידידות נצח<br/>בין שתי המדינות המפוארות שגברים אלו מייצגים.<br/>שכן האחד זקוק לצמחי האלמוות לבריאותו<br/>בעוד שהשני, הכוהנים, זקוקים לשדות כדי לעבדם.\"<br/>משמעות הדבר היא שכוהני קידוסי אניטוני גידלו את החסד האלמותי כדי לרפא את אנשי קאשטה...",
    "129185": "זה מזכיר לי אירוע שהתרחש בתור הזהב, המוזכר בספר בספרייה. נאמר שם שמלך קאשטה היה חולה, וכוהני קידוסי אניטוני נשלחו לרפא אותו, בהצלחה. אך שנים לאחר מכן, הקאשטנים החליטו לבזוז את אסם התבואה של אנבסה כדי לנכס לעצמם את תרופת הפלא, וזה סימן את האובדן הסופי של החסד האלמותי עבור ארצנו.",
    "129186": "אם כן, קיר הספרייה הישנה יהיה עדות לסיפור זה! מרתק! ועם זאת, המשמעות של כך היא גם שכוהני קידוסי אניטוני עיבדו את החסד האלמותי בעצמם, לפי התרגום שלך... הצהרה שבוודאי לא תשביע את רצונה של הכוהנת הגדולה. האם אתה בטוח שזה נכון?",
    "129187": "תרגום זה נכון, ויש לומר את האמת.",
    "129188": "אם כן, ארשום זאת רשמית. אחרי הכל, אל לנו לעצב מחדש את העבר כדי לרצות את בני זמננו.",
    "129190": "התמודד עם השלכות האמת",
    "129191": "תרגום זה מסוכן מדי, עלינו לשנות אותו.",
    "129192": "אני די עצוב להסתיר את האמת, אך יייתכן ששינויה יהיה לטובת עתידה של אנבסה. צור איתי קשר ברגע שתהיה מוכן לזייף תרגום אחר.",
    "129193": "הסכם לזייף את התרגום",
    "129194": "\"מי ייתן ומסחר ראשון זה יחתום את תחילתה של ידידות נצח<br/>בין שתי המדינות המפוארות שגברים אלו מייצגים.<br/>שכן האחד זקוק לצמחי האלמוות לבריאותו<br/>בעוד שהשני, החקלאים, זקוקים לשדות כדי לעבדם.\"<br/>משמעות הדבר היא שחקלאי וואהה דשר גידלו את החסד האלמותי לבריאותם של כוהני קאשטה? ובכן, זה סותר את הסצנה שעל הקיר. איני חושב שתרגום זה נכון, אך לכוהנת הגדולה לא יהיה אכפת. האם אתה עדיין חושב שזה נכון?",
    "129195": "אך שמעו כוהני קידוסי אניטוני על הצלחתך בפענוח סודות הכתב האנבסאי העתיק, והם כבר דחקו בך להתמודד עם הכתובת שבספרייה הישנה. חמוש בידע החדש שלך, ובעזרת החוקר, עליך להתמודד כעת עם האתגר המרתיע ביותר שלך עד כה, שכן כל מה שהכתובת תחשוף ודאי יניב תובנות בעלות ממדים היסטוריים באמת, אשר ככל הנראה ישנו את פני אנבסה, ואולי אף יכריעו את גורל אחדותה.",
    "129196": "החוקר חושש מההשלכות שעלולות להיות לתרגום שלך על אנבסה.",
    "129197": "הכוהנת הגדולה מוקיעה בזעם את התרגום שלך כהטעיה.",
    "129198": "החוקר מפרסם את התרגום שלך, מבלי להיות משוכנע.",
    "129199": "הכוהנת הגדולה מאשרת את התרגום שלך.",
    "129200": "החוקר מזמין אותך להגיש לו תרגומים נוספים.",
    "129201": "כעת באפשרותך לתרגם כל קטע של כתב עתיק",
    "129202": "מכונית משטרה QO",
    "129209": "קידוסי אניטוני:<br/>מאמץ מבוכי",
    "129210": "האם יש משהו למטה?",
    "129216": "קידוסי אניטוני:<br/>והמדבר ייקח את הכל",
    "129222": "מפה של שדה קרב ימי עתיק",
    "129223": "מפת אוצר",
    "129224": "מפה שסופקה על ידי מלחים קיסריים",
    "129227": "הכוהנת הגדולה מבקשת ממך ליידע את קטמה שיש לקבל את דת קידוסי, או להניח לה.",
    "129228": "החוקר מציע שתמסור את התרגום שעשית לקטמה.",
    "129230": "השג את תרגום הקיר ב-[AssetData([Conditions QuestCondition Context]) Text]",
    "129231": "קח את התרגום שעשית לקטמה",
    "129233": "אז הכוהנת הגדולה מסרבת לקבל את האמת, גם כאשר הכתבים העתיקים מעידים נגד שקריה? יש לי אמון בתרגום שלך, ובאמת שהוא נושא. העובדה שקידוסי אניטוני הייתה פעם מקום של עבודת אדמה וכפיים תעניק לי את הלגיטימיות הדרושה לי כדי להחיל עליהם את חוקי אנבסה שלי. ואם הם מעוניינים למחות... העולם ידע שהם שיקרו במשך מאות שנים לאין ספור, כשהם מרוויחים מעמלם של אחרים בעצלותם המאוסה.",
    "129234": "ללא ספק הם חשו שהיותם השומרים הבלעדיים של הידע העניקה להם כוח",
    "129235": "אולי הם פשוט חששו שהספרייה תאבד לניוון אילו היו נאלצים לעבוד עבודת כפיים",
    "129236": "מפה חתומה על ידי בית המשפט",
    "129237": "מפה שסופקה על ידי מלחים קיסריים",
    "129238": "מפת מצוק",
    "129239": "מפה של מחנה רועים אבוד",
    "129240": "מפה של מוצב עתיק",
    "129241": "נציג הקיסר בעל סמכויות מלאות",
    "129242": "תרגום חפוז",
    "129243": "מפה של אחוזה שקועה",
    "129244": "תרגום מוצלח",
    "129245": "קטמה מציין כי הוא מתכוון להשמיד את האבן.",
    "129246": "SonarTreasurePoolAfrica",
    "129247": "שכנע את קטמה לזנוח את תוכניות ההשמדה שלו",
    "129248": "מפה מטביעת ספינה לאחרונה",
    "129249": "מפה שנלקחה מדוח ביטוח",
    "129250": "קטמה מחליט להגלות את קידוסי, ולמנוע מכל כוהניה כניסה לאנבסה.",
    "129251": "מפת הקפטן שספינתו נטרפה",
    "129252": "הכוהנת הגדולה מלינה על בחירתו של קטמה, אך עומדת על דעתה.",
    "129253": "קטמה החליט לקבל את קידוסי אניטוני אל אנבסה, מבלי להכריח אותם לעבוד.",
    "129254": "הכוהנת הגדולה מסכימה באי רצון לאפשר לקידוסי להצטרף לאימפריה.",
    "129255": "קטמה מציין כי הוא מתכוון להשמיד את האבן.",
    "129256": "קטמה מבקש ממך להוביל את השליח לקידוסי אניטוני.",
    "129257": "הכוהנת הגדולה שואלת אם התקבלה תשובה כלשהי מקטמה.",
    "129258": "הכוהנת הגדולה מקוננת על ההשלכות הרסניות של נוכחותך ביניהם.",
    "129259": "הכוהנת הגדולה זועמת על בגידתך.",
    "129261": "אין ספק בכך: תמליל קיר הספרייה הישנה שביצעת חושף כי כוהני קידוסי אניטוני היו במקור עם חקלאי, שתפקידו לעבד את האדמה. הדבר נוגד כל עיקרון באמונתה העתיקה של קידוסי, שבמרכזה עומד הסירוב לעבודת כפיים פשוטה. גילוי כזה היה כמובן בלתי קביל עבור הכוהנת הגדולה, והיא הורתה לך לחזור בך ממסקנות אלו ולשכנע את קטמה בצדקת אמונתה ועיקרי דתה של קידוסי.",
    "129262": "התרגום שלך לכתובת שעל קירות הספרייה הישנה אישש סוף סוף את טענותיהם בנות מאות השנים: אמונתם אכן עתיקה כמו אנבסה עצמה, ומקדשת את הסירוב לעבודת כפיים בלב לבה, כשהיא מייחסת לכת הכוהנים אך ורק התבוננות ועיסוקים מחקריים. מסקנה משביעת רצון עבור הכוהנת הגדולה, אך אמונה שאינה תואמת לחלוטין את חזונו של הקיסר קטמה לאנבסה מאוחדת ומחודשת — כזו שהוא ללא ספק יסרב לקבל.",
    "129266": "למרות מיטב מאמציך, לא הצלחת לשכנע את הקיסר בלגיטימיות של טענות הכוהנת הגדולה. הוא גמר בליבו להגלות את כוהני קידוסי אניטוני מממלכתו והורה על השמדת אבן השבועה, כדי שאיש לא ידע על אמיתות טענותיהם, וכדי שכל הקולות המתנגדים באנבסה החדשה והמאוחדת ישתקו. הוא הטיל עליך להוביל את סוכנו לקידוסי, שם יקריא את הודעתו של קטמה לכוהנים, לפני שיבטיח את השמדת אחד החפצים העתיקים ביותר בעולם.",
    "129267": "הכוהנים האלה הוליכו אותך שולל, ובכישרון רב. הם יודעים שאתה תמצא עדות לטענותיהם בחורבות אדמתם, ראיות שלא יכולתי להכחיש. אך איני יכול להרשות באימפריה שלי עם שאינו מוכן להשתתף בעמלם של כולם, המעוניין רק לחיות כעלוקה על חשבון עבודתם של אחרים. יש להשמיד את הממצאים הללו, ולמחוק כל זכר להיסטוריה זו, לטובת אנבסה כולה.",
    "129268": "אבל אלו שרידים יקרי ערך, אוצרות של עבר אבוד!",
    "129269": "שתוק",
    "129270": "המשך",
    "129271": "ראה באיזו מיומנות הם טיפחו אותך! אם העבר אבוד, אז הנח לו! ההיסטוריה והמורשת היומרניות שלהם הן שרידים של עבר — של אנבסה שלא הייתה קיימת מזה מאות שנים! הייתי רוצה לראות את אנבסה צומחת חופשייה ממסורות כה צרות אופקים ואכזריות. אם כתישת היסטוריה כזו לאפר היא המחיר שיש לשלם עבור גדולתם של אנשיי, זהו מחיר שאשלם בשמחה!",
    "129272": "אינני מבקש ממך לעשות זאת - ואני גם לא סומך עליך לחלוטין שתעשה זאת אילו ביקשתי. אחד הסוכנים שלי יטפל בהכל, אתה רק צריך לקחת אותו אל האי הארור ההוא. נתת לאיום הזה להתפתח באין מפריע, וכעת אתה <i>אכן</i> תראה אותו מוכנע.",
    "129273": "העריץ סורייה החריב את קידוסי לפני זמן רב. האם זה השם שאתה רוצה שיהיה קשור למורשתך?",
    "129274": "העריץ סורייה היה מטורף שהעלה את המדינה כולה באש! הוא חיפש את מה שנמנע ממנו בצדק על ידי שמיים והקריב הכל, אפילו את עמו, לשאיפתו המטורפת! אינני דומה לו <i>בכלל</i>! הייתי רוצה לראות את ארצי משגשגת, את עמי פורח ועומד חזק ומאוחד מול כל אויב.",
    "129275": "לא אשמע עוד דבר בעניין. שכולם יוגלו ויוקצו מאנבסה. שכל מסחר איתם ייאסר, ושייבלו ויידעכו. הם יכולים לאכול את המגילות היקרות שלהם אם הם חייבים! הכל חייב למות, וזמנם הגיע.",
    "129276": "גירוש הוא עונש קשה מספיק — אין צורך להשמיד את האבן!",
    "129277": "ולסתכן בגילוי שישלח את עמי למלחמת אזרחים? סכסוך דמים של אח נגד אח בשם אמונה שמתה מזמן? רעיונות הם דבר מסוכן — במיוחד כפירה. לא אסתכן בהידרדרות לכאוס ולמהומות בשם קדושה עקרונית וערטילאית של ההיסטוריה. אחדותה של אנבסה דקה כשערת אריה, ולא אתן לה להישבר!",
    "129278": "מספיק. החלטתי התקבלה. פנה למשימתך, והובל את השליח שלי לקידוסי אניטוני. שהפרק הזה בנתיב המיוסר של אנבסה ייעלם אל תהום השיכחה והשתיקה. אנבסה תתאחד תחת האמונה והדת האחת והאמיתית של האל, למען עתיד מזהיר יותר.",
    "129279": "הסכם להשמיד את האבן",
    "129285": "קידוסי אניטוני:<br/>המדון מאחור, האחדות מלפנים",
    "129286": "קידוסי אניטוני:<br/>דעיכתה של קידוסי אניטוני",
    "129287": "קידוסי אניטוני:<br/>הכנעתה של קידוסי אניטוני",
    "129288": "מפה ספוגת גשם של יישוב רועים.",
    "129289": "מפה של אחוזה עתיקה, שחוקה ממי מלח ומלח ים.",
    "129290": "מפה של יישוב שאבד מזמן באוקיינוס.",
    "129291": "השג את השליח המיוחד ב-[AssetData([Conditions QuestCondition Context]) Text]",
    "129292": "הובל את שליחו של קטמה אל [AssetData([Conditions QuestCondition ExecutionObject]) Text]",
    "129295": "אוסטרקסטרופה",
    "129296": "השברים החבוטים של אחת מספינות הפשיטה של אנגרב.",
    "129298": "הוא מכוסה בקצף מביקורו האחרון אצל הספר.",
    "129299": "טקסטים עתיקים הזכירו קרב ללא מנצח שהתרחש בדיוק במקום כזה.",
    "129300": "יש האומרים שהיו אלו שוניות נסתרות. אחרים מדברים על לווייתני ענק. האמת שוכנת עם המתים.",
    "129301": "החוקר להוט להתחיל לתרגם.",
    "129302": "קידוסי אניטוני:<br/>כתבי האורקל",
    "129304": "ביטוח עבור ספינת משא מתיישנת הנושאת חפצים שונים עבור נתנאל סימנון אחד.",
    "129305": "כפוף של בליקוורת' ציין שמקום זה שימש להטבעת מטען לצורך הונאת ביטוח.",
    "129306": "אדמירל ו. סילבה אחד הזמין את אותו סוג של ציוד כבד פעמיים תוך פרק זמן קצר, במקביל להיעלמותה המוזרה של אחת מספינותיהם באזורים אלו.",
    "129307": "קפטן שספינתו נטרפה מתלונן על סדרה של ארגזים גדולים, השמורים על ידי גברים הנושאים את סמלו של מר נ. סימנון, אשר הועמסו על ספינתו. הוא מאשים את משקלם הלא ידוע של הארגזים באסונו.",
    "129310": "קידוסי אניטוני:<br/>עקבות של פירורי דגן",
    "129322": "קידוסי אניטוני:<br/>עקבות האורקל",
    "129324": "שרטוטים של חפץ עתיק אגדי",
    "129326": "מפה של שדה קרב ימי עתיק",
    "129327": "מפת מצוק",
    "129328": "המשימה הארוכה שלך לאחד את קידוסי אניטוני עם אנבסה של הקיסר קטמה מתקרבת לסיומה — אך עדיין נותרו סימני שאלה שיש לחשוף. החשוב שבהם הוא שאלת אמונתה המקורית והאמיתית של אנבסה. ודאי שמציאת תשובה לתהייה עתיקת יומין זו תסייע בגישור על הפערים בין עמיה המפולגים הרבים של אנבסה! אולי ישנן כתובות נוספות, הניתנות כעת לפענוח, שניתן למצוא על מונומנטים עתיקים ברחבי הארץ? החוקר ללא ספק יתענג על האתגר, ומי יודע אילו אופקים חדשים עשויים להיחשף?",
    "129329": "<i>אופציונלי:</i> קח תמליל נוסף לחוקר",
    "129333": "SonarTreasurePoolAfrica",
    "129334": "SonarTreasurePoolAfrica",
    "129335": "Shipwreck_Modern_Map_Scrap_Africa",
    "129336": "Shipwreck_Modern_Map_Scrap_Africa",
    "129337": "Shipwreck_Modern_Map_Scrap_Africa",
    "129338": "Shipwreck_Modern_Map_Scrap_Africa",
    "129357": "האורקל בוואהה דשר חרוט בשורות רבות של אנבסאית עתיקה - אתגר עצום אפילו עבור המוח הפיקח ביותר! למרבה המזל, החוקר להוט לסייע לך בפיענוחן.",
    "129358": "החוקר אינו שבע רצון מהתרגום.",
    "129359": "החוקר תוהה מה היה פירושו של אסם תבואה עבור קידוסי אניטוני.",
    "129360": "החוקר מציע לנטוש את חקר סודותיה של קידוסי.",
    "129361": "החוקר מסכים עם התרגום שלך.",
    "129362": "פענח את כתבי האורקל",
    "129363": "אתה אומר שהכתובת הזו nanny באורקל בוואהה דשר, מעל תיאור של דמויות כוהנים המעבדים את האדמה. מעניין מאוד... בוא נראה מה עוד זה יניב.",
    "129364": "המשך",
    "129365": "<custom-entity tag=\"enbesan\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"building\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"one\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"holy\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"land\"/></custom-entity><br/><br/>אני מזהה את שני הסמלים האחרונים הללו... ההר הקדוש! זהו קידוסי אניטוני, אני בטוח בכך! והאם זה לא היה גם בכתובת שעל הקיר בספרייה?",
    "129366": "<custom-entity tag=\"enbesan\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"building\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"one\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"holy\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"land\"/></custom-entity><br/><br/>אולם, לגבי החלק הראשון הזה, איני בטוח. אני יכול לראות ש-<custom-entity tag=\"enbesan\"><custom-properties image=\"building\"/></custom-entity> נראה בדיוק כמו דלתות האבן המסורתיות של מבנים מתור הזהב אבל... хממ. ניחושים כלשהם?",
    "129367": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"building\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"one\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"holy\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"land\"/></custom-entity> פירושו \"נמל קידוסי אניטוני\", לדעתי.",
    "129368": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"building\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"one\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"holy\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"land\"/></custom-entity> פירושו \"אסם התבואה של קידוסי אניטוני\", הייתי אומר.",
    "129369": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"goods\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"building\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"one\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"holy\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"land\"/></custom-entity> חייב להביע \"מקדש קידוסי אניטוני\".",
    "129370": "זה... נראה לא סביר. זו בהחלט התייחסות למבנה בקידוסי, אך נמל? הייתי מצפה שזה יסומן בסמל <custom-entity tag=\"enbesan\"><custom-properties image=\"water\"/></custom-entity>. לא, זה חייב להיות מבנה אחר.",
    "129371": "נסה תרגום נוסף",
    "129372": "אסם תבואה! כן, זה אכן הגיוני. אך ההשלכות — המשמעויות עבור קידוסי ואמונתה... אנו זקוקים להוכחה מוצקה יותר לכך. ראיות ארכאולוגיות! אם היה אסם תבואה בסדר גודל כזה בקידוסי, חייב להישאר זכר כלשהו ממנו איפשהו.",
    "129373": "חפש את אסם התבואה",
    "129374": "מקדש? לא, אני מסתפק בכך. מקדש נכתב בדרך כלל כ-<custom-entity tag=\"enbesan\"><custom-properties image=\"holy\"/></custom-entity>. מבנה ללא ספק, אך לא מקדש, לדעתי.",
    "129375": "החוקר מציע לחפש שרידים של אסם התבואה.",
    "129376": "החוקר נרגש לחשוף שאולי מצאת את אסם התבואה.",
    "129377": "בין הכתובות שעל האורקל בוואהה דשר היו אזכורים ל-'אסם תבואה בקידוסי אניטוני'. החוקר מתעקש בהתרגשות שאם מבנה כזה אכן היה קיים, ודאי שנותרו ממנו שרידים, החבויים באי. הוא מבקש ממך לחקור, וממליץ לך להתמקד בשטחים הפתוחים והבלתי מיושבים של האי. האם אסם תבואה זה יכול להיות עתיק אף יותר מהספרייה הישנה?",
    "129378": "בחר את המיקום שבו לדעתך שכן אסם התבואה בקידוסי אניטוני",
    "129379": "קידוסי אניטוני:<br/>סוד אגור, שמושתק באבק",
    "129380": "קידוסי אניטוני:<br/>כתובת חמקמקה",
    "129381": "Angereb_MarketStalls01",
    "129382": "משבצת נהר",
    "129383": "Angereb_MarketStalls01",
    "129384": "משבצת נהר",
    "129385": "קידוסי אניטוני:<br/>כשהאבק שוקע",
    "129386": "הכתובות שעל האורקל בוואהה דשר הובילו אותך לאתר ארכאולוגי שהיה חבוי עד כה בקידוסי אניטוני — שרידיו של אסם תבואה גדול! כל מה ששוכן בפנים יניב תובנות משמעותיות לגבי ההיסטוריה של האי!",
    "129387": "החוקר נרגש מהאפשרות לחפצים עתיקים חדשים.",
    "129388": "נתח את החפצים שבאסם התבואה",
    "129389": "במהלך חפירה זהירה של אסם התבואה בקידוסי אניטוני, נתקלת בכד עתיק שלם ברובו. עליו חרוטה כתובת, קריאה מספיק כדי שתוכל לנסות להעתיקה בעזרת החוקר.",
    "129390": "החוקר מבקש את עזרתך בתרגום הסמלים.",
    "129391": "פענח את הכתובת שעל הכד",
    "129392": "קרמיקה — כד בעל עיצוב מורכב. סימני אש על המעטפת החיצונית שלו, אך נראה שיש משהו בפנים — זרעים! שרופים, כמצופה. אך ישנה כתובת כאן... היא בקושי נראית, אך היא עדיין אמורה להיות ניתנת לפענוח, אני חושב...",
    "129393": "<custom-entity tag=\"enbesan\"><custom-properties image=\"eternity\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"life\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"hibiscus\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity><br/><br/>כעת את הסמל הזה אני מכיר! <custom-entity tag=\"enbesan\"><custom-properties image=\"hibiscus\"/></custom-entity> זהו אותו סמל שהכוהנים מקעקעים על פניהם: סמל פרח ההיביסקוס!",
    "129394": "<custom-entity tag=\"enbesan\"><custom-properties image=\"eternity\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"life\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"hibiscus\"/></custom-entity><custom-entity tag=\"enbesan\"><custom-properties image=\"unit\"/></custom-entity><br/><br/>כעת את הסמל הראשון הזה... אנו יודעים ש-<custom-entity tag=\"enbesan\"><custom-properties image=\"time\"/></custom-entity> פירושו \"זמן\", או \"עבר\". נתקלנו ב-<custom-entity tag=\"enbesan\"><custom-properties image=\"life\"/></custom-entity> בעבר, בכתובת שעל הקיר. אם זכרוני אינו מטעה אותי, פירושו היה... חיים? או שמא אמונה?",
    "129395": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"eternity\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"life\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"unit\"/></custom-entity> חייב אפוא לומר \"צמחי העתיד\".",
    "129396": "צמחי העתיד? זה לא נשמע כמו שום דבר ששמעתי עליו אי פעם בידע או באמונה... לא, איני חושב שזה יכול להיות נכון. אך אם היינו יכולים לזהות את <custom-entity tag=\"enbesan\"><custom-properties image=\"life\"/></custom-entity>... הענף הזה כאן אינו שונה מהענף שהכוהנים הוצגו מחזיקים בתחריטים ישנים...",
    "129397": "<custom-entity tag=\"enbesananswer\"><custom-properties image=\"eternity\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"life\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"plant\"/></custom-entity><custom-entity tag=\"enbesananswer\"><custom-properties image=\"unit\"/></custom-entity> חייב לומר \"צמחי חיי נצח\".",
    "129398": "כמובן! שעון החול הניצב כאן <custom-entity tag=\"enbesan\"><custom-properties image=\"time\"/></custom-entity> חייב להיות זרימת הזמן, אך שעון חול על צידו אומר שהזרימה פסקה, שהזמן נעצר — סמל הנצח <custom-entity tag=\"enbesan\"><custom-properties image=\"eternity\"/></custom-entity>, יחד עם סמל החיים <custom-entity tag=\"enbesan\"><custom-properties image=\"life\"/></custom-entity>...",
    "129399": "הקשב בקשב רב",
    "129400": "החסד האלמותי! זהו כד שבו אוחסנו זרעי החסד האלמותי — ואם להאמין לכתובות, הרי שהפרחים האגדיים הללו אינם אלא פרחי היביסקוס! לחשוב שהכוהנים המשיכו לטפח ולהוקיר את הפרחים, למרות ששכחו את מטרתם... זה מרתק! עליך לשאול את הכוהנת הגדולה אם היא יודעת על כך!",
    "129401": "שאל את הכוהנת הגדולה",
    "129402": "QI_Treasure_Dummy",
    "129403": "QI_Treasure_Dummy",
    "129404": "QI_Treasure_Dummy",
    "129405": "קידוסי אניטוני:<br/>הקינה על קידוסי אניטוני",
    "129406": "QI_Treasure_Dummy",
    "129407": "QI_Treasure_Dummy",
    "129408": "QI_Treasure_Dummy",
    "129409": "תגלית מרעישה! לאחר שתורגמה, הכתובת חשפה כי בתור הזהב של אנבסה, כוהני קידוסי אניטוני היו גננים ומגדלי זרעים, שתפקידם לגדל את החסדים האלמותיים הקדושים — מרחק עצום אכן מהתבוננותם נטולת העמל כיום! אינך יכול שלא להבחין כי פרח קדוש זה, החסד האלמותי, נותר סמל האי והפולחן שלו עד היום. ללא ספק הכוהנת הגדולה אינה יכולה להיות בורה לגבי ההיסטוריה שלו והשלכותיה? החוקר דוחק בך להתעמת איתה בעניין.",
    "129410": "QI_Treasure_Dummy",
    "129411": "QI_Treasure_Dummy",
    "129412": "QI_Treasure_Dummy",
    "129413": "QI_Treasure_Dummy",
    "129414": "החוקר מציע שתתעמת עם הכוהנת הגדולה",
    "129415": "הכוהנת הגדולה מודה שהיה לה ידע מוקדם על החורבות.",
    "129416": "בחר את הכוהנת הגדולה",
    "129417": "קידוסי אניטוני:<br/>אירוניה מתוקה",
    "129418": "מכתב הכוהנת הגדולה",
    "129419": "כשהיא ניצבת מול ראיות מוצקות ומותקפת בשאלות נוקבות, לא נותרה לכוהנת הגדולה ברירה אלא להודות בידע המלא שלה על ההיסטוריה של קידוסי אניטוני, ועל מאות השנים של המרמה שבתוכה. כשהיא מחזירה לעצמה מעט משלוותה, היא מזמינה אותך לעקוב אחריה, בעוד היא מספרת לך על ההיסטוריה האמיתית של האי — ועל משמעות המונומנטים שחשפת.",
    "129420": "הכוהנת הגדולה החליטה לספר לך את סיפורה האמיתי של קידוסי אניטוני.",
    "129421": "הכוהנת הגדולה מודה שידעה שעיקרי אמונתה של קידוסי היו בדותות.",
    "129422": "בדוק את פרחי ההיביסקוס",
    "129423": "בחן את הפסל בקידוסי אניטוני",
    "129424": "בחן את אסם התבואה",
    "129425": "בחן את קיר הספרייה הישנה",
    "129426": "בחן את הכדים השרופים",
    "129427": "בחן את הספרייה הישנה",
    "129428": "בחן את הספרייה החדשה",
    "129429": "השג את המכתב מהכוהנת הגדולה",
    "129430": "מסור את המכתב לקטמה אל [AssetData([Conditions QuestCondition ExecutionObject]) Text]",
    "129431": "הכוהנת הגדולה החליטה להצטרף לאימפריה של קטמה, תחת הדת הישנה.",
    "129432": "הכוהנת הגדולה דורשת שתיקח את מכתבה לקטמה.",
    "129433": "קטמה חושד במכתבה של הכוהנת הגדולה, ומטיל ספק בתום ליבה.",
    "129434": "קטמה מודיע שקידוסי אניטוני מעוניינת להצטרף לאימפריה עם הדת העתיקה.",
    "129435": "קטמה נרגש לקבל את הצעתה של קידוסי.",
    "129436": "כעת, לאחר שההיסטוריה האמיתית של קידוסי אניטוני נחשפה באמצעות מחקרך המקיף — והודאתה של הכוהנת הגדולה — היא נראית עייפה ממאות השנים של המרמה. אף על פי שהיא עדיין עומדת על הלגיטימיות של תפקידה והסיבות שהציגה בפניך, היא הגיעה לאמונה שהשעה בשלה לחזרה לאמונתה המקורית של אנבסה — כזו שהקיסר ודאי יוכל להסכים לה. היא מבקשת ממך לקחת את קבלתה והכנעתה הצנועות אליו, ולשכנע אותו בכל מה שיש לו להרוויח מפשרה זו.",
    "129437": "הכוהנת הגדולה מודעת היטב לכך שהיא חבה את מרבית קבלתה והישרדותה של קידוסי אניטוני למאמציך. אף על פי שחשפת תרמית בת אלפי שנים, הדבר הסיר מכתפיה מורשת מעיקה, ואפשר לכוהנים להתאחד מחדש עם אמונתם המקורית, ועם אדמה שממנה היו מנותקים זמן רב. לקידוסי אולי יש מעט מאוד עושר ארצי, אך הכוהנת הגדולה מעוניינת לתגמל את מאמציך וכנותך על ידי הפקדת אחד החפצים היקרים ביותר של המסדר שלה בידיך.",
    "129438": "הכוהנת הגדולה מעוניינת להציע לך משהו.",
    "129439": "הכוהנת הגדולה מעוניינת להציע לך כד יקר ערך, ירושה משפחתית מסיל'אמידוש.",
    "129440": "הכוהנת הגדולה מודיעה שספרים עתיקים זמינים כעת.",
    "129441": "בקר בקידוסי אניטוני",
    "129442": "כד מסיל'אמידוש",
    "129443": "קידוסי אניטוני:<br/>מתנה עתיקה",
    "129444": "פרסינה, הכוהנת הגדולה",
    "129445": "היביסט קוש, כך כינינו את אלו. החסד האלמותי. היינו גננים אז, טיפלנו בגני סיל'אמידוש, וסיפקנו תוצרת לאדמות המלכה. זה היה כבוד גדול עבורנו לטפל בפרחים אלו, ותוך זמן קצר, המנהג קבע שרק כוהנים יטפלו בהם — מתנות האלים.",
    "129447": "כאשר הגענו לאנבסה, המלך הקאשטני העניק לנו את המחוז הגדול של וואהה דשר לעיבוד, שהאי הזה היה רק חלק קטן ממנו. חלק מהכוהנים אימצו את התרבות הקאשטנית, והקימו פסלים גבוהים כמו זה, בעוד אחרים פרשו להרים והקימו מקדש. המקדש הזה.",
    "129449": "בהרים שאפנו לגדל את ההיביסט קוש שוב. זרענו וחפרנו תעלות, ומילאנו את אסם התבואה שלנו עד גדותיו בדגן ובפרחים. למדנו את סודות הפרחים. החכמנו בדרכי המרפא והריפוי, ורבים הגיעו אלינו בחיפוש אחר תרופות לתחלואיהם.",
    "129451": "שמנו הלך לפנינו עד כדי כך שיום אחד, שליח מקאשטה הגיע אלינו. המלך שכב גוסס, והציע לתגמל אותנו אם יינצל מציפורני קוטל החיים. האירוע הזה מתואר על הקיר שחשפת. עמדנו לצד מיטתו במשך שבעה ימים ולילות, רקחנו וטיפלנו בו — והוא ניצל. מתוך הודיה, המלך נשבע ידידות לקידוסי ולאנבסה.",
    "129453": "אך רומינו. המלך חמד את הידע שלנו, ושלח רוצחים בלילה שקטלו רבים, שרפו את המקדש שלנו, לקחו את הפרחים והותירו את האדמה שוממת. היינו הרוסים. טיפוח הצמחים היה סיבת קיומנו, אך מלך אנבסה סירב להסתכן בהכעסת עוצמתה של קאשטה. סירבנו, ונבלנו.",
    "129455": "העברנו את יגוננו לדיו ולקלף. כתבנו רבות — את כל הידע וההיסטוריה שלנו, השמורים בתוך ספרייה גדולה בהרים. הספרייה הישנה שחפרת <i>אתה</i>. אך זה לא החזיק מעמד. המלך המטורף סורייה בזז את אדמותינו, בחיפוש אחר אלמוות שלא היה לנו עוד — ושוב, חלק גדול אבד באש.",
    "129457": "בעוד המלך המטורף משתולל באנבסה, קוטל או עוקר את אנשיה, פנינו פעם נוספת לכתיבה, וטווינו היסטוריה חדשה לארצנו. כשהחשיכה ירדה על זיכרון אנבסה, טווינו סיפור מפותל שהשיב את מקומנו ללב האומה שלנו, כשומרים של כוונת האלים.",
    "129459": "כאשר הספרייה נשרפה, לפני אלפי שנים, זה לא היה הדבר היחיד שאיבדנו. הברברים הקאשטנים לקחו גם את פרחי האלמוות, שניצלו מחורבן סיל'אמידוש.",
    "129460": "פגוש אותי בבריכת הטקסים. זה המקום שבו הכל מתחיל.",
    "129461": "pool_",
    "129462": "קיצורי דרך חדשים זמינים",
    "129463": "ישנם קיצורי דרך חדשים זמינים, אך המקשים אינם מוקצים. לפתוח את תפריט האפשרויות כעת?",
    "129464": "מפה של מחנה רועים אבוד",
    "129465": "מפה של אחוזה שקועה",
    "129466": "מפה של מוצב עתיק",
    "129467": "מפה חתומה על ידי בית המשפט",
    "129468": "מפה שנלקחה מדוח ביטוח",
    "129469": "מפה מטביעת ספינה לאחרונה",
    "129470": "מפת הקפטן שספינתו נטרפה",
    "129472": "קידוסי אניטוני:<br/>הקינה על קידוסי אניטוני",
    "129474": "קידוסי אניטוני:<br/>הקינה על קידוסי אניטוני",
    "129475": "עקוב אחר הכוהנת הגדולה והקשב לסיפוריה",
    "129477": "כוח אדם הדרוש למחקר",
    "129478": "שאל את הכוהנת הגדולה על החלק הבא בסיפור",
    "129479": "קידוסי אניטוני:<br/>הקינה על קידוסי אניטוני",
    "129481": "קידוסי אניטוני:<br/>הקינה על קידוסי אניטוני",
    "129483": "עץ קשה ואיכותי עבור נגר...",
    "129484": "קורטוב של תבלין מעורר חושים קהים.",
    "129485": "תמיסה אנטי-בקטריאלית ואנטיספטית טבעית יוצאת דופן.",
    "129486": "עור קשוח ובשר מתוק כגרגרים. כמו כן, מאזינים נהדרים.",
    "129487": "מעולם לא הזיק לאיש להיראות מטופח...",
    "129488": "בד בעל חוזק מתיחה טוב...",
    "129489": "טוב בשביל להכניס אותך למצב הרוח...",
    "129490": "חשוב להתייעצויות אלוהיות...",
    "129491": "בעלי חיים נמשכים לפנסים, או נרתעים מהם...",
    "129492": "מעולם לא הזיק לאיש להיראות מטופח...",
    "129493": "ההגאי וחדר המנועים יכולים כעת לשמור על קשר...",
    "129494": "קידוסי אניטוני:<br/>הקינה על קידוסי אניטוני",
    "129496": "קידוסי אניטוני:<br/>הקינה על קידוסי אניטוני",
    "129498": "קידוסי אניטוני:<br/>הקינה על קידוסי אניטוני",
    "129512": "אזור: אנבסה",
    "129513": "מפת אוצר",
    "129532": "אימפריה בהתהוות",
    "129533": "עזור לקיסר קטמה להביא יציבות לאנבסה מבירתה החדשה טבורימה. הדף איומים מבפנים ומבחוץ כדי להביא שלום ושגשוג לאזור. גלה את ההיסטוריה העשירה של אנבסה, והפק תועלת מידע זה עם בונוסים חדשים.",
    "129534": "רתום את כוחם של המים",
    "129535": "הקם מערכת תעלות חדשה לגמרי להשקיית השדות! ספק את צורכי הרועים וזקני השבט של אנבסה, הגע לשיאים כלכליים חדשים, וראה את המדבר פורח!",
    "129536": "בנה את מכון המחקר החדש בעולם הישן, וגלה טכנולוגיות חדשות שאינן שונות ממעשי קסם. הפוך אדמה לפורייה, ייצר סחורות ממשאבים חלופיים, ומצא את המומחה המדויק או המכונות שאתה צריך!",
    "129537": "הקם אנדרטה לידע",
    "129538": "הבא חוקרים לעולם הישן מכל רחבי העולם! ספק את צורכיהם הקוסמופוליטיים כדי שיחד עם המהנדסים שלך, הם יזינו את הקידמה המדעית!",
    "129539": "מעמד חדש של הוגים",
    "129541": "דווח לפועל",
    "129546": "איסד העתיקה",
    "129547": "מחנה העולם הישן ההרוס",
    "129548": "נווה המדבר של וואהה דשר",
    "129549": "הריסות",
    "129550": "הריסות",
    "129551": "הריסות",
    "129552": "שדייט העתיקה",
    "129553": "הפועלים של קטמה",
    "129554": "בחר כדי לשתול עצים",
    "129555": "בחר כדי לשתול עצים",
    "129556": "בחר כדי לשתול עצים",
    "129557": "הבל, המפקח",
    "129558": "מחסן חדש",
    "129559": "ביתה של קיריה",
    "129560": "קיריה",
    "129561": "עץ תפוז",
    "129562": "החווה של קיריה"
}

with open("trans_part_1.json", "w", encoding="utf-8") as f:
    json.dump(translations, f, ensure_ascii=False, indent=4)
print("Saved 400 translations to trans_part_1.json")
