import json
import os

batch = json.load(open("to_translate_batch.json", encoding="utf-8"))

skips_to_add = []

mapping = {
    "You’re serious about this? I saw the lads come back from the quartermaster office - injured! You realize, the money you’re takin’ from them is food off their family’s table!": "אתה רציני לגבי זה? ראיתי את הבחורים חוזרים ממשרד האפסנאות — פצועים! אתה מבין שהכסף שאתה לוקח מהם הוא אוכל מהשולחן של המשפחות שלהם!",
    "It makes a grand difference to us boss! Very good of you it is, we’ll raise a glass to you at the pub tonight!": "זה עושה הבדל עצום עבורנו בוס! יפה מאוד מצדך, נרים כוסית לכבודך בפאב הלילה!",
    "A mistake! You’ll never hear the end of it – they’ll cook up more trouble and come running back to you expecting a handout.": "טעות! אתה לא תשמע את הסוף של זה — הם יבשלו עוד צרות ויבואו בריצה בחזרה אליך בציפייה לנדבות.",
    "Skyline Tower: Strike-Breaking": "מגדל קו הרקיע: שבירת שביתה",
    "All Skyline Tower Phases": "כל שלבי מגדל קו הרקיע",
    "Donny wants you to negotiate the workers coming back to work.": "דוני רוצה שתנהל משא ומתן עם הפועלים כדי שיחזרו לעבודה.",
    "Surely you can finagle something— my lawyer would kill for your negotiation skills! Get these workers back— kicking and screaming for all I care.": "בטוח תוכל להנדס משהו — עורך הדין שלי היה מוכן להרוג בשביל כישורי המשא ומתן שלך! תחזיר את הפועלים האלה — בצעקות ובכוח מצידי.",
    "A strike has begun at the Skyline Tower": "שביתה החלה במגדל קו הרקיע",
    "Negotiate with the striking workers": "נהל משא ומתן עם הפועלים השובתים",
    "With the strikes causing delays to the Skyline Tower's construction, Bader suggests you negotiate with the workers to get them back on track. A nice, generous gesture might increase their happiness, even if it’s just a temporary boost to the spirit.": "מאחר שהשביתות גורמות לעיכובים בבניית מגדל קו הרקיע, ביידר מציע שתנהל משא ומתן עם הפועלים כדי להחזיר אותם למסלול. מחווה נחמדה ונדיבה עשויה להגביר את האושר שלהם, אפילו אם זה רק חיזוק זמני למורל.",
    "Skyline Tower: Girder Grumbles": "מגדל קו הרקיע: רטינות הפיגומים",
    "The goddamn construction site's shut down— the workers are striking! It’s disrespect— against us! Take care of it, will you?": "אתר הבנייה הארור מושבת — הפועלים שובתים! זה חוסר כבוד — כלפינו! טפל בזה, טוב?",
    "Donny demands you find a way to make the workers comply.": "דוני דורש שתמצא דרך לגרום לפועלים לציית.",
    "Reach a <b>happiness of 15</b> for your workers in [Area Area([Conditions QuestArea]) CityName]<br />Current happiness: [Area Area([Conditions QuestArea]) Happiness AverageHappinessByPopulation(15000001) >> happiness]": "הגע אל <b>אושר ברמה של 15</b> עבור הפועלים שלך ב-[Area Area([Conditions QuestArea]) CityName]<br />אושר נוכחי: [Area Area([Conditions QuestArea]) Happiness AverageHappinessByPopulation(15000001) >> happiness]",
    "The workers in your city are very unhappy with the way they’ve been treated, and have organised a strike at the Skyline Tower construction site. The only way to compel them to resume their work is to increase the general happiness of your city.": "הפועלים בעיר שלך אינם מרוצים כלל מהיחס שקיבלו, והם ארגנו שביתה באתר הבנייה של מגדל קו הרקיע. הדרך היחידה לאלץ אותם לחדש את עבודתם היא להעלות את רמת האושר הכללית בעיר שלך.",
    "<i>Hint: You can manipulate happiness through 5 different factors, or by negotiating with the workers directly.</i>": "<i>רמז: תוכל להשפיע על האושר באמצעות 5 גורמים שונים, או על ידי ניהול משא ומתן ישיר עם הפועלים.</i>",
    "There are five factors influencing a population's happiness: goods satisfaction, pollution, peace, working conditions and the news. Alter those to achieve the desired increase in happiness.": "ישנם חמישה גורמים המשפיעים על אושר האוכלוסייה: שביעות רצון מסחורות, זיהום, שלום, תנאי עבודה וחדשות. שנו אותם כדי להשיג את העלייה המבוקשת באושר.",
    "Temporary modifiers that decrease your workers' happiness due to your earlier decisions may be active right now. Waiting for them to time out may also help you reach the desired happiness level.": "ייתכן שמשפיעים זמניים שמפחיתים את אושר הפועלים שלך בעקבות החלטות קודמות שלך פעילים כעת. המתנה לפקיעת תוקפם עשויה גם היא לעזור להגיע לרמת האושר הרצויה.",
    "You can enter negotiations with the workers through the \"Negotiations\" quest. Based on your choices, your workers may receive a temporary happiness buff.": "תוכל להיכנס למשא ומתן עם הפועלים באמצעות משימת \"משא ומתן\". בהתבסס על הבחירות שלך, הפועלים שלך עשויים לקבל תוספת אושר זמנית.",
    "Look, <b>you've left us little choice</b> here, boss. The guys and me, we’re pissed. You’ve been ignoring or plight; our low wages; our lack of relaxation time! It’s disrespect, it is!<br /><br />If you want us to finish Skyline, you're gonna have to <b>meet our demands!</b> Simple as that.": "תשמע, <b>לא השארת לנו ברירה</b> כאן, בוס. החבר'ה ואני עצבניים. התעלמת מהמצוקה שלנו; השכר הנמוך שלנו; חוסר הזמן למנוחה! זה חוסר כבוד, זה מה שזה!<br /><br />אם אתה רוצה שנסיים את קו הרקיע, תצטרך <b>להיענות לדרישות שלנו!</b> פשוט מאוד.",
    "Offer them <b>free tickets</b> to the zoo ([AssetData(137507) Text]).<br />[AssetData(137509) Text]": "הצע להם <b>כרטיסים חינם</b> לגן החיות ([AssetData(137507) Text]).<br />[AssetData(137509) Text]",
    "Finance a staff <b>barbecue</b> for workers (Pay <img height='24' width='24' src=\"[AssetData(1010214) Icon]\"/>[AssetData(137062) Text] [AssetData(1010214) Text], <img height='24' width='24' src=\"[AssetData(1010238) Icon]\"/>[AssetData(137062) Text] [AssetData(1010238) Text]. Current amount: <img height='24' width='24' src=\"[AssetData(1010214) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010214) >> storagegood], <img height='24' width='24' src=\"[AssetData(1010238) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010238) >> storagegood]). [AssetData(137512) Text]": "ממן <b>ברביקיו</b> לעובדים (שלם <img height='24' width='24' src=\"[AssetData(1010214) Icon]\"/>[AssetData(137062) Text] [AssetData(1010214) Text], <img height='24' width='24' src=\"[AssetData(1010238) Icon]\"/>[AssetData(137062) Text] [AssetData(1010238) Text]. כמות נוכחית: <img height='24' width='24' src=\"[AssetData(1010214) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010214) >> storagegood], <img height='24' width='24' src=\"[AssetData(1010238) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010238) >> storagegood]). [AssetData(137512) Text]",
    "Give all workers a <b>major bonus</b> ([AssetData(137513) Text] [AssetData(137503) Text]).<br />[AssetData(137514) Text]": "תן לכל הפועלים <b>בונוס משמעותי</b> ([AssetData(137513) Text] [AssetData(137503) Text]).<br />[AssetData(137514) Text]",
    "Chaps at the bees club have lost the damn bet. You can quite clearly see from up here no curvature of the earth whatsoever...": "החבר'ה במועדון הדבורים הפסידו בהימור הארור. אפשר לראות מכאן למעלה בבירור שאין שום קימור של כדור הארץ...",
    "Zoo Attractiveness": "אטרקטיביות גן החיות",
    "Beer and Sausages": "בירה ונקניקיות",
    "Free Zoo Tickets": "כרטיסים חינם לגן החיות",
    "Barbecue Event": "אירוע ברביקיו",
    "Huge Bonuses": "בונוסים ענקיים",
    "Happiness Buff": "תוספת אושר",
    "Your workers are temporarily happier": "הפועלים שלך זמנית מאושרים יותר",
    "Your workers are temporarily much happier": "הפועלים שלך זמנית מאושרים הרבה יותר",
    "The workers are thankful for the free zoo tickets.": "הפועלים אסירי תודה על הכרטיסים החינמיים לגן החיות.",
    "Donny thinks zoo tickets should work.": "דוני חושב שכרטיסים לגן החיות צריכים לעבוד.",
    "The workers are looking forward to the free barbecue.": "הפועלים מצפים לברביקיו החינמי.",
    "Donny thinks a barbecue should appease the workers.": "דוני חושב שברביקיו אמור לרצות את הפועלים.",
    "The workers are grateful for the generous bonus.": "הפועלים אסירי תודה על הבונוס הנדיב.",
    "Donny isn't sure the workers are worth it.": "דוני לא בטוח שהפועלים שווים את זה.",
    "The workers decide to stop striking — for now.": "הפועלים מחליטים להפסיק את השביתה — לעת עתה.",
    "Donny is relieved you managed to end the strike.": "דוני מוקל מכך שהצלחת לסיים את השביתה.",
    "A visit to the Zoo? That’ll be a change o’ pace and little Emmi’s gonna be chuffed to go!": "ביקור בגן החיות? זה יהיה שינוי מרענן ואמי הקטנה תהיה מאושרת ללכת!",
    "A free ticket to the zoo! Wow! That's basically their natural habitat!": "כרטיס חינם לגן החיות! וואו! זה בעצם בית הגידול הטבעי שלהם!",
    "Can’t go wrong with a hearty feast. It’ll be nice to have a carefree night, help the lad’s take their minds of things.": "אי אפשר לטעות עם סעודה דשנה. יהיה נחמד ליהנות מלילה חסר דאגות, לעזור לבחורים להסיח את דעתם מהדברים.",
    "Yes, a barbecue bash! Stuff their bellies with beer and sausage, til they're too sluggish to care anymore.": "כן, מסיבת ברביקיו! לפטם את הבטן שלהם בבירה ונקניקיות, עד שהם יהיו עצלנים מדי מכדי שיהיה להם אכפת.",
    "That’s quite something boss! It’ll last us a stretch to be sure. Might even get us something nice like one of them fancy toasters, or a new toy for Emmi.": "זה משהו מיוחד בוס! זה יחזיק לנו מעמד לזמן מה, זה בטוח. אולי אפילו נקנה משהו נחמד כמו אחד ממצנמי הפאר האלה, או צעצוע חדש לאמי.",
    "Oh, great! Steep investment with no return— workers don’t spend their money in the shopping arcades— you know those people don't even eat toast?": "אוי, נהדר! השקעה כבדה ללא תמורה — פועלים לא מבזבזים את כספם בפסז'י הקניות — אתה יודע שהאנשים האלה אפילו לא אוכלים צנימים?",
    "Right, we’ve decided to get back to it. It’s our work after all and we take pride in it, just remember we ain’t interchangeable and if we don’t feel valued, we can go back to striking.": "טוב, החלטנו לחזור לעבודה. זו העבודה שלנו אחרי הכל ואנו גאים בה, רק תזכור שאנחנו לא ניתנים להחלפה ואם לא נרגיש מוערכים, נוכל לחזור לשבות.",
    "Oh, finally! Let’s just hope you’ve not been spoiling these guys. They’ll need to put their backs into it, if we're going to plan to make any good on the time they’ve wasted!": "אוי, סוף סוף! בוא רק נקווה שלא פינקת את הבחורים האלה. הם יצטרכו להשקיע מאמץ רציני, אם אנחנו מתכננים לפצות על הזמן שהם בזבזו!",
    "A strike has ended at the Skyline Tower": "שביתה הסתיימה במגדל קו הרקיע",
    "Skyline Tower: Risk Assessment": "מגדל קו הרקיע: הערכת סיכונים",
    "I implore you to act! With each day the risks become greater. It’s paramount that we check the state of the lower floors and the columns...": "אני מפצירה בך לפעול! עם כל יום שעובר הסיכונים גדלים. זה קריטי שנבדוק את מצב הקומות התחתונות והעמודים...",
    "No surveys! I hate surveys! This isn’t the first - or last - tower built in my name. Just make sure those workers aren’t slacking and get me a coffee. Gaelic.": "בלי סקרים! אני שונא סקרים! זה לא המגדל הראשון — או האחרון — שנבנה על שמי. רק ודא שהפועלים האלה לא מתרשלים ותביא לי קפה. גאלי.",
    "What a relief! I'll get to it right away. You won’t regret taking the time to do this, thank you!": "איזו הקלה! אגש לזה מיד. לא תתחרט על כך שהקדשת לזה זמן, תודה!",
    "Mr. Bader truly has found his mirror.": "מר ביידר באמת מצא את המראה שלו.",
    "Theodora insists the Skyline Tower's stability be checked.": "תיאודורה מתעקשת לבדוק את יציבות מגדל קו הרקיע.",
    "Donny dismisses Theodora's concerns.": "דוני מבטל את החששות של תיאודורה.",
    "Talk with Miss Jenny in private": "דבר עם מיס ג'ני ביחידות",
    "Miss Jenny (a.k.a. Theodora) insists that checking the integrity of the Skyline Tower is a vital step in the construction process, yet one which Donald Bader seems determined to ignore, whatever the risks. Now that she has your ear, though, you should be perfectly capable of making an informed choice for the project by yourself.": "מיס ג'ני (הידועה גם כתיאודורה) מתעקשת שבדיקת היציבות של מגדל קו הרקיע היא שלב חיוני בתהליך הבנייה, אך כזה שדונלד ביידר נחוש להתעלם ממנו, יהיו הסיכונים אשר יהיו. כעת, כשהיא זוכה לקשב שלך, אתה אמור להיות מסוגל לחלוטין לקבל החלטה מושכלת עבור הפרויקט בעצמך.",
    "Skyline Tower: The Cracks Appear": "מגדל קו הרקיע: הסדקים מופיעים",
    "Theodora is relieved you agreed to survey the tower.": "תיאודורה מוקלת מכך שהסכמת לבדוק את המגדל.",
    "Theodora is disappointed you decided against surveying the tower.": "תיאודורה מאוכזבת מכך שהחלטת שלא לבדוק את המגדל.",
    "The Skyline Tower’s making history — the heights Mr. Bader envisions have never been reached before! But such a <i>construction is unprecedented</i>. I fear the <b>structure isn’t strong enough</b> to support its own weight, or withstand the adverse wind conditions up there. The architect had all the solutions for these issues, but Mr. Bader knew they would cost, so he's taken several shortcuts instead.<br /><br />I strongly advise <b>conducting a survey</b> to verify the building's structural integrity. That way, if my fears are well-founded, we can act.": "מגדל קו הרקיע עושה היסטוריה — הגבהים שמר ביידר מדמיין מעולם לא הושגו לפני כן! אך <i>בנייה שכזו היא חסרת תקדים</i>. אני חוששת שה<b>מבנה אינו חזק מספיק</b> כדי לשאת את משקלו שלו, או לעמוד בתנאי הרוח הקשים שם למעלה. לאדריכל היו את כל הפתרונות לבעיות הללו, אך מר ביידר ידע שהם יעלו כסף, ולכן הוא בחר בכמה קיצורי דרך במקום.<br /><br />אני ממליצה בחום <b>לערוך בדיקה</b> כדי לוודא את היציבות המבנית של הבניין. בדרך זו, אם החששות שלי מבוססים, נוכל לפעול.",
    "Agree to organise a structural <b>survey</b> ([AssetData(137515) Text] [AssetData(137503) Text]).<br /> [AssetData(137516) Text]": "הסכם לארגן <b>בדיקה</b> מבנית ([AssetData(137515) Text] [AssetData(137503) Text]).<br /> [AssetData(137516) Text]",
    "<b>Ignore</b> Miss Jenny": "<b>להתעלם</b> ממיס ג'ני",
    "Skyline Tower: Sound and Fury": "מגדל קו הרקיע: קולות וזעם",
    "It is as I feared: Cracks are forming on the lower levels. If they expand, the integrity of the tower might be at stake. We must act fast!": "זה בדיוק כפי שחששתי: סדקים מתחילים להיווצר בקומות התחתונות. אם הם יתרחבו, יציבות המגדל עלולה להיות בסכנה. עלינו לפעול מהר!",
    "Very good! I will coordinate the installation with the workers. It will take some time, but it will be worth it.": "יפה מאוד! אתאם את ההתקנה עם הפועלים. זה ייקח קצת זמן, אבל זה יהיה שווה את זה.",
    "This is gross negligence! There’s evidence that the tower's unstable and yet you refuse to act!": "זו רשלנות פושעת! יש ראיות לכך שהמגדל אינו יציב ועדיין אתה מסרב לפעול!",
    "Theodora has found a serious problem, and advises you to act.": "תיאודורה מצאה בעיה חמורה, וממליצה לך לפעול.",
    "Theodora will gladly help stabilise the Tower.": "תיאודורה תשמח לעזור לייצב את המגדל.",
    "Theodora accuses you of gross negligence.": "תיאודורה מאשימה אותך ברשלנות פושעת.",
    "Talk with Theodora": "דבר עם תיאודורה",
    "Theodora’s concerns were well-founded! The structural integrity of the Skyline Tower has been compromised by its height and weight, and cracks are forming on the lower levels! If only the chief investor hadn't been so stingy in sourcing quality materials! Theodora, however, believes that if you act fast, the Tower can still be saved. She sees a couple of possible solutions.": "החששות של תיאודורה היו מבוססים! היציבות המבנית של מגדל קו הרקיע נפגעה עקב גובהו ומשקלו, וסדקים מתחילים להיווצר בקומות התחתונות! אילו רק המשקיע הראשי לא היה כל כך קמצן ברכישת חומרים איכותיים! תיאודורה, לעומת זאת, מאמינה שאם תפעל מהר, עדיין ניתן להציל את המגדל. היא רואה כמה פתרונות אפשריים.",
    "Here's a summary: the lower levels are showing wear, and <b>some cracks have formed near the entrance</b>. We’ve also had a partial cave-in on the fourth floor. The weight and winds have combined to weaken the foundation, and with every floor we add, we compound the problem.<br /><br />We must strengthen the base by <b>adding shoring devices</b> — a wooden support system to provide additional load-bearing support. But I’ll need quite a lot of wood to make it work, and Mr. Bader certainly isn’t prepared to pay...": "הנה סיכום קצר: הקומות התחתונות מראות סימני שחיקה, ו<b>כמה סדקים נוצרו ליד הכניסה</b>. כמו כן, הייתה לנו קריסה חלקית בקומה הרביעית. המשקל והרוחות חברו יחד כדי להחליש את היסודות, ועם כל קומה שאנו מוסיפים, אנו מחמירים את הבעיה.<br /><br />עלינו לחזק את הבסיס על ידי <b>הוספת התקני תמיכה</b> — מערכת תמיכה מעץ כדי לספק כושר נשיאת עומס נוסף. אך אצטרך די הרבה עץ כדי לגרום לזה לעבוד, ומר ביידר בהחלט לא מוכן לשלם...",
    "Agree to provide the <b>timber</b> (Pay <img height='24' width='24' src=\"[AssetData(1010196) Icon]\"/>[AssetData(137065) Text] [AssetData(1010196) Text]. Current amount: <img height='24' width='24' src=\"[AssetData(1010196) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010196) >> storagegood]).<br />[AssetData(137517) Text]": "הסכם לספק את <b>העצים</b> (שלם <img height='24' width='24' src=\"[AssetData(1010196) Icon]\"/>[AssetData(137065) Text] [AssetData(1010196) Text]. כמות נוכחית: <img height='24' width='24' src=\"[AssetData(1010196) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010196) >> storagegood]).<br />[AssetData(137517) Text]",
    "Refuse to compromise on Donny's vision.": "סרב להתפשר על החזון של דוני.",
    "An emergency! The workers heard cracking noises from the structure. Some columns can’t bear the weight— they're bending! We must strengthen them, or they might not hold!": "מצב חירום! הפועלים שמעו קולות של סדקים מהמבנה. חלק מהעמודים אינם יכולים לשאת את המשקל — הם מתכופפים! עלינו לחזק אותם, אחרת הם עלולים לא להחזיק מעמד!",
    "Bending columns? They’re made of steel for chrissakes! I'm the ace when it comes to construction and I say that’s goddam ridiculous.": "עמודים מתכופפים? הם עשויים מפלדה למען השם! אני מומחה בכל הנוגע לבנייה ואני אומר שזה מגוחך לעזאזל.",
    "Theodora alerts you to another urgent problem with the tower.": "תיאודורה מתריעה בפניך על בעיה דחופה נוספת במגדל.",
    "Donny dismisses the evidence.": "דוני מבטל את הראיות.",
    "Find a solution": "מצא פתרון",
    "Theodora was right! Having heard strange groaning noises, the workers discovered more signs that the tower’s structural integrity was failing, as it transpires some of the columns are starting to bend! Theodora implores you to act fast, as the tower's core structure must be strengthened.": "תיאודורה צדקה! לאחר ששמעו רעשי גניחה מוזרים, הפועלים גילו סימנים נוספים לכך שהיציבות המבנית של המגדל קורסת, שכן מתברר שחלק מהעמודים מתחילים להתכופף! תיאודורה מפצירה בך לפעול מהר, מאחר שיש לחזק את ליבת המבנה של המגדל.",
    "I wish we'd <i>acted sooner</i>... For the columns to bend, the weight must be immense — they may even start to give way! Surely you can see how dire this situation is?<br /><br /><b>We must strengthen them</b>! We could fortify them by cementing the base, effectively <b>doubling their size</b>, or by adding structural support through <b>shoring devices</b>.<br /><br />I think neither option will be the end of our woes, but they might at least buy us some time!": "הלוואי ש<i>היינו פועלים מוקדם יותר</i>... כדי שהעמודים יתכופפו, המשקל חייב להיות עצום — הם עלולים אפילו להתחיל לקרוס! אתה בטח מבין כמה המצב הזה חמור?<br /><br /><b>עלינו לחזק אותם</b>! נוכל לבצר אותם על ידי דיס יסודות (ביטון הבסיס), ובכך <b>להכפיל את גודלם</b> באופן אפקטיבי, או על ידי הוספת תמיכה מבנית באמצעות <b>התקני תמיכה</b>.<br /><br />אני חושבת שאף אחת מהאפשרויות לא תהיה סוף הצרות שלנו, אך הן עשויות לפחות לקנות לנו קצת זמן!",
    "<b>Double the size</b> of the columns (Pay <img height='24' width='24' src=\"[AssetData(1010231) Icon]\"/>[AssetData(137066) Text] [AssetData(1010231) Text]. Current amount: <img height='24' width='24' src=\"[AssetData(1010231) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010231) >> storagegood]).<br />[AssetData(137522) Text]": "<b>הכפל את גודל</b> העמודים (שלם <img height='24' width='24' src=\"[AssetData(1010231) Icon]\"/>[AssetData(137066) Text] [AssetData(1010231) Text]. כמות נוכחית: <img height='24' width='24' src=\"[AssetData(1010231) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010231) >> storagegood]).<br />[AssetData(137522) Text]",
    "Agree to finance the <b>shoring devices</b> ([AssetData(137524) Text] [AssetData(137503) Text]).<br />[AssetData(137523) Text]": "הסכם לממן את <b>התקני התמיכה</b> ([AssetData(137524) Text] [AssetData(137503) Text]).<br />[AssetData(137523) Text]",
    "<b>Refuse</b>": "<b>לסרב</b>",
    "Better later than never! I'll provide the workers with materials, and we’ll encase the main columns. This should buy us some time.": "עדיף מאוחר מאשר לעולם לא! אספק לפועלים חומרים, ונעטוף את העמודים הראשיים. זה אמור לקנות לנו קצת זמן.",
    "Better later than never! I’ve ordered the shoring devices. They’ll arrive soon. Installation will take some time, but it might save the tower!": "עדיף מאוחר מאשר לעולם לא! הזמנתי את התקני התמיכה. הם יגיעו בקרוב. ההתקנה תיקח קצת זמן, אבל זה עשוי להציל את המגדל!",
    "I am rendered speechless.": "נותרתי ללא מילים.",
    "Oh, don’t go catching Miss Jenny’s paranoia! I pegged you as immune to this nonsense. But, I know you’ll bounce back, just make sure my tower's finished.": "אוי, אל תידבק בפרנויה של מיס ג'ני! חשבתי שאתה חסין לשטויות האלה. אבל אני יודע שתתאושש, רק ודא שהמגדל שלי יושלם.",
    "My guru, steadfast as always. When one is in pursuit of a great goal there’s no time to let fools distract you!": "הגורו שלי, איתן כתמיד. כשנמצאים במרדף אחר מטרה גדולה, אין זמן לתת לטיפשים להסיח את דעתך!",
    "Theodora is glad you decided to act.": "תיאודורה שמחה שהחלטת לפעול.",
    "Donny believes the cement is a waste of money.": "דוני מאמין שהמלט הוא בזבוז כסף.",
    "Donny believes the shoring is a waste of money.": "דוני מאמין שהתמיכה היא בזבוז כסף.",
    "Theodora is shocked by your ignorance.": "תיאודורה הזדעזעה מהבורות שלך.",
    "Donny agrees that speed trumps spend.": "דוני מסכים שהמהירות גוברת על ההוצאות.",
    "What the hell was that noise? It didn't come from the tower?! I refuse to lose face in front of this city!": "מה לעזאזל היה הרעש הזה? הוא לא הגיע מהמגדל?! אני מסרב להביך את עצמי בפני העיר הזו!",
    "Something must be done - Miss Jenny! It’s her goddamn job to have ideas! Where the hell is she?": "צריך לעשות משהו — מיס ג'ני! זה התפקיד הארור שלה להביא רעיונות! איפה היא לעזאזל?",
    "Donny is alarmed to hear the noises coming from the tower.": "דוני נבהל לשמוע את הרעשים המגיעים מהמגדל.",
    "Donny is worried and wishes Theodora could help.": "דוני מודאג ומקווה שתיאודורה תוכל לעזור.",
    "Skyline Tower: Teetering At The Precipice": "מגדל קו הרקיע: מתנדנד על פי תהום",
    "Your recent choices have culminated in a worst-case scenario: The tower is now highly unstable, and Miss Jenny is nowhere to be found. In his time of crisis, Donald turns desperately to you, demanding a solution.": "הבחירות האחרונות שלך הובילו לתרחיש הגרוע ביותר: המגדל כעת אינו יציב לחלוטין, ומיס ג'ני נעלמה. בשעת משבר זו, דונלד פונה אליך בייאוש ודורש פתרון.",
    "Miss Jenny kept nagging that we ought to do something about, what was it again? Ah, yes, <i>thicker pillars</i>? Sounds about right... Oh, and there was something about <i>off-shoring</i>, and <i>devices?</i><br /><br />Maybe we should try one of those — or <b>what would you suggest</b>, oh guru?": "מיס ג'ני המשיכה לנדנד שאנחנו צריכים לעשות משהו בקשר ל... מה זה היה שוב? אה, כן, <i>עמודים עבים יותר</i>? נשמע נכון... אוה, והיה משהו לגבי <i>תומכים</i>, ו<i>התקנים?</i><br /><br />אולי כדאי שננסה אחד מאלה — או <b>מה אתה היית מציע</b>, הו גורו?",
    "Let's <b>triple the size</b> of the support columns (Pay <img height='24' width='24' src=\"[AssetData(1010231) Icon]\"/>[AssetData(137091) Text] [AssetData(1010231) Text]. Current amount: <img height='24' width='24' src=\"[AssetData(1010231) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010231) >> storagegood]).<br />[AssetData(137527) Text]": "בוא <b>נשלש את גודל</b> עמודי התמיכה (שלם <img height='24' width='24' src=\"[AssetData(1010231) Icon]\"/>[AssetData(137091) Text] [AssetData(1010231) Text]. כמות נוכחית: <img height='24' width='24' src=\"[AssetData(1010231) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010231) >> storagegood]).<br />[AssetData(137527) Text]",
    "I think you mean <b>shoring devices?</b>. We'll install them on two thirds of the tower ([AssetData(137529) Text] [AssetData(137503) Text]). [AssetData(137527) Text]": "אני חושב שאתה מתכוון ל<b>התקני תמיכה?</b>. נתקין אותם בשני שלישים מהמגדל ([AssetData(137529) Text] [AssetData(137503) Text]). [AssetData(137527) Text]",
    "I... really feel it's better we just leave it rather than guess.": "אני... באמת מרגיש שעדיף פשוט להשאיר את זה ככה במקום לנחש.",
    "Donny wonders if cement might help.": "דוני תוהה אם מלט עשוי לעזור.",
    "Donny wonders if shoring might help.": "דוני תוהה אם תמיכה עשויה לעזור.",
    "Donny admits his own ignorance of the subject.": "דוני מודה בבורותו שלו בנושא.",
    "Yes. Strengthen the pillars... maybe that could stop this wretched creaking? For once I’d be glad to have Miss Jenny here yapping away about some crazy solution!": "כן. לחזק את העמודים... אולי זה יכול להפסיק את החריקות המקוללות האלה? לשם שינוי הייתי שמח לראות את מיס ג'ני כאן מקשקשת על איזה פתרון מטורף!",
    "Shoring. Sounds good. Think I’ve heard Miss Jenny use that term. For once I’d be glad to have Miss Jenny here yapping away about some crazy solution!": "תמיכה. נשמע טוב. נראה לי ששמעתי את מיס ג'ני משתמשת במונח הזה. לשם שינוי הייתי שמח לראות את מיס ג'ני כאן מקשקשת על איזה פתרון מטורף!",
    "Guru, if you’re out of ideas...so am I. For once I’d be glad to have Miss Jenny here yapping away about some crazy solution!": "גורו, אם לך נגמרו הרעיונות... אז גם לי. לשם שינוי הייתי שמח לראות את מיס ג'ני כאן מקשקשת על איזה פתרון מטורף!",
    "Skyline Tower: Dora's Way": "מגדל קו הרקיע: דרכה של דורה",
    "The measures we’ve taken have saved us some time, but the tower’s still <b>in great peril</b>. If we don’t take decisive action now, it might be too late...<br /><br />As I’ve said, I’m working hard on a solution, but I <i>need more time</i> to finalise my calculations. There’s no room for error. If you could <b>get me the parts I need</b>, we might just make it in time.": "הצעדים שנקטנו קנו לנו קצת זמן, אך המגדל עדיין <b>בסכנה גדולה</b>. אם לא נפעל באופן נחרץ כעת, זה עלול להיות מאוחר מדי...<br /><br />כפי שאמרתי, אני עובדת קשה על פתרון, אך אני <i>זקוקה לזמן נוסף</i> כדי להשלים את החישובים שלי. אין מקום לטעויות. אם תוכל <b>להביא לי את החלקים שאני צריכה</b>, אולי נספיק לעשות זאת בזמן.",
    "Agree to <b>provide</b> her with the materials required (Pay <img height='24' width='24' src=\"[AssetData(1010228) Icon]\"/>[AssetData(137111) Text] [AssetData(1010228) Text]. Current amount: <img height='24' width='24' src=\"[AssetData(1010228) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010228) >> storagegood])": "הסכם <b>לספק</b> לה את החומרים הדרושים (שלם <img height='24' width='24' src=\"[AssetData(1010228) Icon]\"/>[AssetData(137111) Text] [AssetData(1010228) Text]. כמות נוכחית: <img height='24' width='24' src=\"[AssetData(1010228) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010228) >> storagegood])",
    "<b>Sorry</b>, but you’ll have to sort this without me.": "<b>מצטער</b>, אבל תצטרכי להסתדר בלעדיי.",
    "Theodora reveals she is working on a possible solution.": "תיאודורה מגלה שהיא עובדת על פתרון אפשרי.",
    "Theodora needs more time to formulate a solution.": "תיאודורה זקוקה לזמן נוסף כדי לגבש פתרון.",
    "Theodora will find a solution without you.": "תיאודורה תמצא פתרון בלעדיך.",
    "You’ve been looking for me? I’ve been very busy! I... Look, I might be onto a possible fix. But there’s not much time and...I’ll need your help to make it work.": "חיפשת אותי? הייתי עסוקה מאוד! אני... תראה, אולי עליתי על פתרון אפשרי. אבל אין הרבה זמן ו... אצטרך את העזרה שלך כדי לגרום לזה לעבוד.",
    "Thank the stars! – okay, we must hurry. I'll finalize everything at the office and then hopefully set it all in motion before it’s too late...": "תודה לאל! — אוקיי, אנחנו חייבים למהר. אשלים את הכל במשרד ואז בתקווה אפעיל את הכל לפני שיהיה מאוחר מדי...",
    "I see. You may be able to live with yourself ignoring this, but I can’t. So, leave me to my work!": "אני מבינה. אולי אתה יכול לחיות עם עצמך כשאתה מתעלם מזה, אבל אני לא יכולה. אז תן לי להמשיך בעבודה שלי!",
    "...and the toasters even, to a degree, are very well made.": "...ואפילו המצנמים, במידה מסוימת, מיוצרים בצורה טובה מאוד.",
    "Skyline Tower: Shattered Porcelain": "מגדל קו הרקיע: חרס שבור",
    "Listen to Theodora": "הקשב לתיאודורה",
    "The security measures you implemented were vital in preventing complete disaster, but the tower is not yet saved. Theodora has contacted you. She’s working on a plan to strengthen the structure — but to implement it, she requires your help.": "אמצעי הבטיחות שיישמת היו חיוניים למניעת אסון מוחלט, אך המגדל עדיין אינו בטוח. תיאודורה יצרה איתך קשר. היא עובדת על תוכנית לחיזוק המבנה — אך כדי ליישם אותה, היא זקוקה לעזרתך.",
    "Help me! Get over here quick! – God, I’ve never heard a screeching so terrible. Make it stop for chrissakes!": "עזור לי! בוא לכאן מהר! — אלוהים, מעולם לא שמעתי חריקה נוראית כל כך. תגרום לזה להפסיק למען השם!",
    "The whole thing’s breaking! Goddamned - How!? For all our sakes, what will we do?": "הכל נשבר! לעזאזל — איך!? למען כולנו, מה נעשה?",
    "What will you do!? You’re in charge, find a solution! —You always do! This can’t be it... this tower can’t fall!": "מה תעשה!? אתה האחראי, תמצא פתרון! — אתה תמיד מוצא! זה לא יכול להסתיים ככה... המגדל הזה לא יכול ליפול!",
    "Donny is panicking at the Skyline Tower.": "דוני נכנס לפאניקה במגדל קו הרקיע.",
    "Donny thinks the tower is going to collapse.": "דוני חושב שהמגדל עומד לקרוס.",
    "Donny hopes you might have a solution.": "דוני מקווה שאולי יש לך פתרון.",
    "The Skyline Tower is on the brink of collapse!": "מגדל קו הרקיע על סף קריסה!",
    "How did this all go so wrong? So terribly, terribly wrong! <i>Can't you do something!</i> Throw the bank at it, I don’t care, just make it <b>stop</b>! Somehow... this can't be how it ends! It can't. Say you have an idea! <b>Say something, guru!!</b>": "איך הכל השתבש כל כך? כל כך, כל כך נורא! <i>אתה לא יכול לעשות משהו!</i> תשפוך על זה כסף, לא אכפת לי, רק תגרום לזה <b>להפסיק</b>! איכשהו... זה לא יכול להיות הסוף! זה לא יכול. תגיד שיש לך רעיון! <b>תגיד משהו, גורו!!</b>",
    "There's a way. <b>Miss Jenny’s working on a something</b>. Let’s talk to her.": "יש דרך. <b>מיס ג'ני עובדת על משהו</b>. בוא נדבר איתה.",
    "I'm afraid there are no options left. All we can do is watch it <b>fall</b>.": "אני חושש שלא נותרו עוד אפשרויות. כל מה שאנחנו יכולים לעשות זה לצפות בו <b>קורס</b>.",
    "Theodora’s predictions have come to fruition once more — the Skyline Tower has reached a height too great for its structure! Donald faltered at the groans of his wavering monument and, in the absence of Miss Jenny, has turned to you for an inexpert solution!": "התחזיות של תיאודורה התגשמו פעם נוספת — מגדל קו הרקיע הגיע לגובה רב מדי עבור המבנה שלו! דונלד נרתע למשמע גניחות המונומנט המיטלטל שלו, ובהיעדרה של מיס ג'ני, פנה אליך לקבלת פתרון לא מקצועי!",
    "Assess the situation": "הערך את המצב",
    "You didn't support Miss Jenny in her research.": "לא תמכת במיס ג'ני במחקר שלה.",
    "God, that sound is driving me crazy!": "אלוהים, הרעש הזה משגע אותי!",
    "Dear god the tower’s swaying! There’s no time! Get word to the lads we must evacuate everyone – Now!": "אלוהים אדירים, המגדל מתנדנד! אין זמן! תמסור לבחורים שחייבים לפנות את כולם — עכשיו!",
    "Sweet Jesus it will fall. Like a house of damned cards... What have we done? We need Miss Jenny...": "ישו הקדוש, הוא יפול. כמו בית קלפים ארור... מה עשינו? אנחנו צריכים את מיס ג'ני...",
    "But... where the hell has she been this whole time? Not in the lab...? Oh wait, she's not in the tower, is she!?": "אבל... איפה היא הייתה לעזאזל כל הזמן הזה? לא במעבדה...? אוי רגע, היא לא במגדל, נכון!?",
    "Donny is deeply worried about the tower.": "דוני מודאג מאוד לגבי המגדל.",
    "The workers are rushing to evacuate the tower.": "הפועלים ממהרים לפנות את המגדל.",
    "Donny is desperate.": "דוני מיואש.",
    "Donny wonders if Theodora might be in the tower.": "דוני תוהה אם תיאודורה נמצאת במגדל.",
    "Skyline Tower: Where is Miss Jenny?": "מגדל קו הרקיע: איפה מיס ג'ני?",
    "Select the Skyline Tower to look for Miss Jenny": "בחר את מגדל קו הרקיע כדי לחפש את מיס ג'ני",
    "With the tower threatening to fall at any moment, Donny J. Bader is frantically searching for his Miss Jenny. He is concerned that his lead engineer and all-round crutch might still be in the tower. Convinced that she is his last hope, he charges you with making sure that, at the very least, she is not in immediate danger.": "כשסכנת קריסה מרחפת מעל המגדל בכל רגע, דוני ג'. ביידר מחפש בטירוף את מיס ג'ני שלו. הוא מודאג מכך שמהנדסת הפיתוח הראשית שלו והמשענת שלו עדיין נמצאת במגדל. משוכנע שהיא תקוותו האחרונה, הוא מטיל עליך לוודא שלפחות היא לא נמצאת בסכנה מיידית.",
    "Miss Jenny": "מיס ג'ני",
    "Group of Workers": "קבוצת פועלים",
    "Highly Suspicious Crates": "ארגזים חשודים מאוד",
    "Miss Jenny, what the hell is this? Is this your idea of a joke...": "מיס ג'ני, מה לעזאזל זה? האם זה רעיון שלך לבדיחה...",
    "Donny is confused by Theodora's behaviour.": "דוני מבולבל מהתנהגותה של תיאודורה.",
    "Survey": "בדיקה",
    "Skyline Tower: Revelations": "מגדל קו הרקיע: גילויים",
    "Select Miss Jenny to reveal who she is": "בחר את מיס ג'ני כדי לחשוף מי היא",
    "You found Theodora, surrounded by workers, near the crumbling tower. She seems uncharacteristically out-of-patience with Donald, and curses his blind ignorance — an ignorance that even prevented him from seeing who she truly was all this time. You should give her the chance to reveal her true identity.": "מצאת את תיאודורה, מוקפת בפועלים, ליד המגדל המתפורר. נראה שבאופן לא אופייני פקעה סבלנותה כלפי דונלד, והיא מקללת את בורותו העיוורת — בורות שאפילו מנעה ממנו לראות מי היא באמת כל הזמן הזה. עליך לתת לה את ההזדמנות לחשוף את זהותה האמיתית.",
    "Skyline Tower: Deus Ex Machina": "מגדל קו הרקיע: דאוס אקס מכינה",
    "It’s never been Miss Jenny, it's Theodora, 'Donny'! And honestly, I should have quit after the first note I sent. but somehow, I thought ‘he can’t be that dense!’ Well, here we are. This crumbling mess, it’s on you!": "זו מעולם לא הייתה מיס ג'ני, זו תיאודורה, 'דוני'! ובכנות, הייתי צריכה להתפטר אחרי הפתק הראשון ששלחתי. אבל איכשהו חשבתי 'הוא לא יכול להיות כל כך סתום!' ובכן, הנה אנחנו כאן. הבלגן המתפורר הזה הוא באשמתך!",
    "You had ample opportunity to change: The tarot card, the posters, the letters... you laughed it all off. I thought you’d be deterred by setbacks; all I ever wanted was for you to be more responsible – but whatever disguise I took on, I was always beneath you.": "היו לך שפע הזדמנויות להשתנות: קלף הטארוט, הכרזות, המכתבים... צחקת על הכל. חשבתי שתירתע מכישלונות; כל מה שאי פעם רציתי זה שתהיה אחראי יותר — אך בכל תחפושת שעטיתי, תמיד נשארתי נחותה בעיניך.",
    "I’m done playing charades. I’m not Miss Jenny, not your secretary, not your engineer – very different jobs by the way! Let me show you who I am.": "סיימתי לשחק במשחקי תפקידים. אני לא מיס ג'ני, לא המזכירה שלך, לא המהנדסת שלך — תפקידים שונים מאוד אגב! תן לי להראות לך מי אני.",
    "You can’t be... are you truly the one who’s been interfering all along? But why!? Why?!": "זה לא יכול להיות... האם את באמת זו שהפרעת לנו כל הזמן הזה? אבל למה!? למה?!",
    "I’ve been the one trying to stop you all along. I’m one of them lot. I applied for this job hoping to improve working conditions, safety, but no-one listened! You really are two of a kind.": "אני הייתי זו שניסיתי לעצור אותך כל הזמן הזה. אני אחת מהחבורה ההיא. הגשתי מועמדות לעבודה הזו בתקווה לשפר את תנאי העבודה והבטיחות, אך אף אחד לא הקשיב! אתם באמת מאותו הסוג.",
    "I’ve been the one trying to stop you all along. I’m one of them lot. I applied for this job hoping to improve working conditions, safety, and found someone in your partner, Donny, who actually cares!": "אני הייתי זו שניסיתי לעצור אותך כל הזמן הזה. אני אחת מהחבורה ההיא. הגשתי מועמדות לעבודה הזו בתקווה לשפר את תנאי העבודה והבטיחות, ומצאתי בשותף שלך, דוני, מישהו שבאמת אכפת לו!",
    "Miss... Theodora. I can’t fix this. You’re... right, you’ve been right. This tower is a crumbling mess. Get us out of it, please. Help me?": "מיס... תיאודורה. אני לא יכול לתקן את זה. את... צודקת, צדקת כל הזמן. המגדל הזה הוא בלגן מתפורר. תחלצי אותנו מזה, בבקשה. תעזרי לי?",
    "Here’s my plan: I’ve returned those stolen materials. We'll repurpose them to join the existing pillars to provide loadbearing support - what Donny should have been willing to do all along— and we'll need more!": "הנה התוכנית שלי: החזרתי את החומרים הגנובים האלה. אנו נשתמש בהם מחדש כדי לחבר את העמודים הקיימים ולספק תמיכה לנשיאת עומס — מה שדוני היה צריך להיות מוכן לעשות מלכתחילה — ונצטרך עוד!",
    "Theodora blames Mr. Bader for all the tower's problems.": "תיאודורה מאשימה את מר ביידר בכל בעיות המגדל.",
    "Theodora is very disappointed in Mr. Bader's leadership.": "תיאודורה מאוכזבת מאוד מהנהגתו של מר ביידר.",
    "Theodora says she is not who Mr. Bader thinks she is.": "תיאודורה אומרת שהיא אינה מי שמר ביידר חושב שהיא.",
    "Donny is baffled.": "דוני מבולבל.",
    "Theodora is disappointed that you, too, proved irresponsible.": "תיאודורה מאוכזבת מכך שגם אתה התגלית כלא אחראי.",
    "Theodora appreciates your efforts, in spite of Mr. Bader.": "תיאודורה מעריכה את מאמציך, למרות מר ביידר.",
    "Donny begs Theodora for help.": "דוני מתחנן בפני תיאודורה לעזרה.",
    "Theodora asks you to deliver materials to the construction site.": "תיאודורה מבקשת ממך למסור חומרים לאתר הבנייה.",
    "Theodora": "תיאודורה",
    "Lying on top of the crates is a bundle of clothes. Among them you find a fake moustache, a brown wig, and a long blue dress... Accessories used by Theodora to disguise her identity whenever she needed to.": "על גבי הארגזים מונחת חבילת בגדים. ביניהם ניתן למצוא שפם מזויף, פאה חומה ושמלה כחולה ארוכה... אביזרים ששימשו את תיאודורה כדי להסוות את זהותה בכל פעם שהיה לה צורך בכך.",
    "Do you have the lacquer?": "יש לך את הלקה?",
    "The workers and I will take care of it. We'll let you know once it’s done.": "הפועלים ואני נטפל בזה. נודיע לך ברגע שזה יסתיים.",
    "Theodora asks if you have the required materials.": "תיאודורה שואלת אם יש לך את החומרים הדרושים.",
    "Theodora will inform you when the repairs are done.": "תיאודורה תודיע לך כאשר התיקונים יושלמו.",
    "Deliver to Theodora:": "מסור לתיאודורה:",
    "Theodora, having revealed herself as a humble worker-cum-engineer (defying the social ladder) — and also the vigilante who's been trying to stop Donald's irresponsible construction practices during the Skyline Tower project — has come through for you once more. She's been preparing a last-minute solution to stabilise the wobbling tower once and for all. To implement it, she's going to require additional materials from you.": "תיאודורה, לאחר שחשפה עצמה כפועלת ומהנדסת צנועה (הקוראת תיגר על המעמדות החברתיים) — וגם הנוקמת שניסתה לעצור את שיטות הבנייה הלא אחראיות של דונלד במהלך פרויקט מגדל קו הרקיע — באה לעזרתך פעם נוספת. היא הכינה פתרון של הרגע האחרון כדי לייצב את המגדל המתנדנד אחת ולתמיד. כדי ליישם אותו, היא תזדקק לחומרים נוספים ממך.",
    "Goddamn...that was close.": "לעזאזל... זה היה קרוב.",
    "Donald is deeply shaken by the close call.": "דונלד מזועזע עמוקות מהאירוע הכמעט הרסני.",
    "Skyline Tower: Post Mortem": "מגדל קו הרקיע: ניתוח שלאחר המוות",
    "Good god, it's done! The danger’s passed and the behemoth lives another day.": "אלוהים אדירים, זה נגמר! הסכנה חלפה והענק ימשיך להתקיים.",
    "So it does. Thanks to you...Theodora. Well, I’d say it was high time we wrapped this up... I can’t wait for this tower to be finished with me.": "אכן כך. בזכותך... תיאודורה. ובכן, הייתי אומר שהגיע הזמן לסיים את זה... אני לא יכול לחכות שהמגדל הזה כבר יסתיים איתי.",
    "Me too. Once it's done, we'll need to have a talk, all together.": "גם אני. ברגע שזה יושלם, נצטרך לנהל שיחה, כולנו יחד.",
    "Theodora says the tower has now been made safe.": "תיאודורה אומרת שהמגדל כעת בטוח.",
    "Donny is keen to finish quickly.": "דוני להוט לסיים במהירות.",
    "Theodora wants a talk once the tower is finished.": "תיאודורה רוצה לקיים שיחה ברגע שהמגדל יושלם.",
    "Weak": "חלש",
    "Moderate": "בינוני",
    "Decent": "סביר",
    "Strong": "חזק",
    "Intense": "עז",
    "But that's nothing compared to what Theodora and the workers accomplished. So, well done. I might disappear for a drink.": "אבל זה שום דבר בהשוואה למה שתיאודורה והפועלים השיגו. אז, כל הכבוד. אולי אלך לשתות משהו.",
    "I don't feel the need to apologise, but I will say this, that the Skyline Tower at least has a vision behind it— it'll change the skyline forever.": "אני לא מרגיש צורך להתנצל, אך אומר זאת, שלפחות למגדל קו הרקיע יש חזון מאחוריו — הוא ישנה את קו הרקיע לנצח.",
    "Let's gather together. The project didn't go without a few major hickups, and I'd like to address a couple of things before I leave you to your tower, Donny.": "בואו נתאסף. הפרויקט לא עבר בלי כמה מהמורות רציניות, והייתי רוצה להתייחס לכמה דברים לפני שאשאיר אותך עם המגדל שלך, דוני.",
    "Offers various consumer goods for a high life society.": "מציע מגוון מוצרי צריכה לחברת החיים הטובים.",
    "Reach for the skies.": "להגיע אל השמים.",
    "Theodora... You were obviously much wiser than I thought... I beg you: please fix the tower— do it for the workers! I can't live with the shadow of such a catastrophe.": "תיאודורה... ברור שהיית הרבה יותר חכמה משחשבתי... אני מתחנן בפנייך: אנא תקני את המגדל — עשי זאת למען הפועלים! אני לא יכול לחיות בצל של אסון כזה.",
    "Donny admits it is thanks to Theodora that disaster was averted.": "דוני מדווח שבזכות תיאודורה נמנע האסון.",
    "Theodora understands the vision, if not the process.": "תיאודורה מבינה את החזון, אם לא את התהליך.",
    "Theodora gathers everyone for a post-mortem.": "תיאודורה מאספת את כולם לניתוח שלאחר המוות.",
    "Discuss matters with Theodora and Donald": "דון בנושאים עם תיאודורה ודונלד",
    "The Skyline Tower is a momentous achievement that will forever define the skyline of your city — yet its construction was subject to many issues and incidents. Theodora insists that you take stock of the many mistakes made along the way, so that any future construction projects won't suffer the same.": "מגדל קו הרקיע הוא הישג כביר שיגדיר לנצח את קו הרקיע של העיר שלך — אך בנייתו הייתה נתונה לבעיות ותקריות רבות. תיאודורה מתעקשת שתפיק לקחים מהטעויות הרבות שנעשו לאורך הדרך, כדי שפרויקטי בנייה עתידיים לא יסבלו מאותו הדבר.",
    "I’ve taken the time to gauge the situation. I’ve talked to workers and passing citizens, and <b>there’s a lot of contention surrounding the Skyline Tower</b>. Due to its immense height, the workers have felt that, throughout the construction, their safety has been at risk. A lot of citizens, too, are unhappy with the shadow the tower casts across the city.<br /><br />In their interest, we want you to undersign a bill to guarantee a <b>limit of one Skyline Tower per city</b>. This is a non-negotiable demand.": "הקדשתי זמן כדי להעריך את המצב. שוחחתי עם פועלים ואזרחים עוברי אורח, ו<b>ישנה מחלוקת רבה סביב מגדל קו הרקיע</b>. בשל גובהו העצום, הפועלים הרגישו שלאורך כל הבנייה, בטיחותם הייתה בסכנה. כמו כן, אזרחים רבים אינם מרוצים מהצל שהמגדל מטיל על העיר.<br /><br />למענם, אנו רוצים שתחתום על הצעת חוק שתבטיח <b>מגבלה של מגדל קו הרקיע אחד לכל עיר</b>. זוהי דרישה שאינה ניתנת למשא ומתן.",
    "Continue": "המשך",
    "One per city? Ha, and here I thought I was making a <i>unique tower</i>! No, of course! It’ll be a hit in every city, and so long as my name's on all of them, I’m in. <b>Where do I sign?</b>": "אחד לכל עיר? הא, ואני חשבתי שאני בונה <i>מגדל ייחודי</i>! לא, ברור! זה יהיה להיט בכל עיר, וכל עוד השם שלי מופיע על כולם, אני בפנים. <b>איפה אני חותם?</b>",
    "<b>Agree to the limit</b> of one Skyline Tower per city": "<b>הסכם למגבלה</b> של מגדל קו הרקיע אחד לכל עיר",
    "<b>Good</b>. But there’s <i>more</i>. Skyscrapers are a true wonder, of that there is no doubt. They are a symbol of modernity and advancement, but they're also an ode to money and power. They reach far above any other residence, public place, or church... and our fear is that by elevating one part of the population — those with means — the already existing divide within our society will only deepen.<br /><br />The Skyline Tower <i>should stand for something</i>. By virtue of its uniqueness, it has the eyes of the world on it, and we have the chance to make use of that attention. We demand the <b>Tower be dedicated to a single cause.</b>": "<b>טוב</b>. אך יש <i>עוד</i>. גורדי שחקים הם פלא אמיתי, בכך אין ספק. הם סמל למודרניות וקידמה, אך הם גם שיר הלל לכסף ולכוח. הם נישאים הרבה מעל לכל מגורים אחרים, מקום ציבורי או כנסייה... והחשש שלנו הוא שעל ידי הרמת חלק אחד של האוכלוסייה — אלה שיש להם את האמצעים — השסע הקיים ממילא בחברה שלנו רק יתרחב.<br /><br />מגדל קו הרקיע <i>צריך לייצג משהו</i>. בזכות הייחודיות שלו, עיני העולם נשואות אליו, ויש לנו הזדמנות לנצל את תשומת הלב הזו. אנו דורשים ש<b>המגדל יוקדש למטרה אחת ויחידה.</b>",
    "Dedicate the monument to <b>environmental awareness</b> (Skyline Tower: +500 Attractiveness)": "הקדש את המונומנט ל<b>מודעות סביבתית</b> (מגדל קו הרקיע: +500 אטרקטיביות)",
    "Dedicate the monument to an <b>anti-consumerism campaign</b> (Skyline Tower: -10% consumption of Carriages, Jewellery and Pocket Watches)": "הקדש את המונומנט ל<b>קמפיין נגד צרכנות</b> (מגדל קו הרקיע: -10% צריכה של כרכרות, תכשיטים ושעוני כיס)",
    "Dedicate the monument to a <b>fair and optimistic future</b> (Skyline Tower: +500 attractiveness, -10% consumption of Carriages, Jewellery and Pocket Watches)": "הקדש את המונומנט ל<b>עתיד הוגן ואופטימי</b> (מגדל קו הרקיע: +500 אטרקטיביות, -10% צריכה של כרכרות, תכשיטים ושעוני כיס)",
    "Panorama Effect": "אפקט הפנורמה",
    "My Skyline Tower, a messenger for a <i>good cause</i>? Well surely such a — what’s the word — <i>philanthropic</i> move would get people’s attention? You know, that could actually be a good advertisement for Galleria Bader... Er, well, anyway...<br /><br />How about something to do with... <i>poverty? Sickness?</i> Erm, maybe it'd be better if <b>you</b> chose the charity?": "מגדל קו הרקיע שלי, שליח ל<i>מטרה טובה</i>? ובכן, ללא ספק צעד — מה המילה — <i>פילנתרופי</i> שכזה ימשוך את תשומת לבם של אנשים? אתה יודע, זה יכול למעשה להיות פרסום טוב לגלריית ביידר... אממ, טוב, בכל מקרה...<br /><br />מה דעתך על משהו שקשור ל... <i>עוני? מחלות?</i> אממ, אולי יהיה טוב יותר אם <b>אתה</b> תבחר את עמותת הצדקה?",
    "Dedication to Environmental Causes": "הקדשה למטרות סביבתיות",
    "Dedication to Anti-Consumerist Causes": "הקדשה למטרות נגד צרכנות",
    "Dedication to Theodora's Egalitarian Future": "הקדשה לעתיד השוויוני של תיאודורה",
    "New buff active on the Skyline Tower": "השפעה חיובית חדשה פעילה במגדל קו הרקיע",
    "I'm done with this Donny. I'll get back to my own projects now...": "סיימתי עם זה, דוני. אני חוזרת לפרויקטים שלי עכשיו...",
    "I'm not fired? I'm not fired!? How about this Donny Bader— you work for me from now on. I run the company, and you get me the cash. I get an office at the top of the tower. You can start by getting me a coffee. Gaelic.": "אני לא מפוטרת? אני לא מפוטרת!? מה דעתך על זה, דוני ביידר — אתה עובד בשבילי מעכשיו. אני מנהלת את החברה, ואתה מביא לי את הכסף. אני מקבלת משרד בראש המגדל. אתה יכול להתחיל בלהביא לי קפה. גאלי.",
    "Miss Jen- Theodora! You're not fired, you know! I could keep you as my advisor. Increased salary, vacation. It'd be my honour.": "מיס ג'נ- תיאודורה! את לא מפוטרת, את יודעת! אני יכול להשאיר אותך כיועצת שלי. שכר מוגדל, חופשה. זה יהיה כבוד עבורי.",
    "Theodora says she has decided to quit her job.": "תיאודורה אומרת שהיא החליטה להתפטר מעבודתה.",
    "Donny is desperate for Theodora to stay.": "דוני נואש לכך שתיאודורה תישאר.",
    "Theodora agrees to stay, on the condition that she's put in charge.": "תיאודורה מסכימה להישאר, בתנאי שהיא תמונה לאחראית.",
    "It won't take long.": "זה לא ייקח הרבה זמן.",
    "It will only take a few hours!": "זה ייקח רק כמה שעות!",
    "The work is done, the construction can resume now.": "העבודה הושלמה, ניתן לחדש את הבנייה כעת.",
    "What’s this? Did we discuss halting construction? Well, better pick it up fast!": "מה זה? האם דנו בעצירת הבנייה? ובכן, מוטב שתזדרז!",
    "The islands lost!? And with it all our progress! – I better go find another guru.": "האיים אבדו!? ויחד איתם כל ההתקדמות שלנו! — מוטב שאלך למצוא גורו אחר.",
    "Where's it gone!? Did it cross your mind to give me some kind of warning? – Oh I hate starting from scratch...": "לאן הוא נעלם!? עלה בדעתך לתת לי אזהרה כלשהי? — אוי, אני שונא להתחיל מאפס...",
    "It is probably for the best.": "זה כנראה לטובה.",
    "No Panorama": "אין פנורמה",
    "Gold Performance Medal": "מדליית ביצוע מזהב",
    "Right on time – Just as ordered! Despite all the hassle you finished the Skyline Tower in good time! Here a have a treat, with regards from all of us at the Galeria Baderette.": "בדיוק בזמן — בדיוק כפי שהוזמן! למרות כל הטרחה, סיימת את מגדל קו הרקיע בזמן טוב! הנה משהו נחמד, דרישת שלום מכולנו בגלריית ביידרט.",
    "Donny gives you a gift by way of thanks for delivering the tower in good time.": "דוני מעניק לך מתנה כהוקרה על מסירת המגדל בזמן טוב.",
    "Reward Patent": "פטנט פרס",
    "Silver Performance Medal": "מדליית ביצוע מכסף",
    "Bronze Performance Medal": "מדליית ביצוע מברונזה",
    "Unstoppable – my guru! Despite all that hassle you finished the Skyline Tower in no time, I’m stunned. Here a special present for the best, with regards from us all, at the Galeria Baderette.": "בלתי ניתן לעצירה — הגורו שלי! למרות כל הטרחה, סיימת את מגדל קו הרקיע תוך זמן קצר, אני המום. הנה מתנה מיוחדת לטוב ביותר, עם ברכות מכולנו בגלריית ביידרט.",
    "Fashionably late? Given the issues we faced I guess it’s fine. I already had this wrapped anyway so here take it, from all of us at the Galeria Baderette.": "באיחור אופנתי? בהתחשב בבעיות שנתקלנו בהן, אני מניח שזה בסדר. בכל מקרה כבר עטפתי את זה אז הנה קח, מכולנו בגלריית ביידרט.",
    "A special certificate issued by the Galeria Baderette rewarding outstanding commitment to finishing a task faster than demanded. It may inspire your workers to strive for similar recognition.": "תעודה מיוחדת המוענקת מטעם גלריית ביידרט על מחויבות יוצאת דופן להשלמת משימה מהר יותר מהנדרש. היא עשויה לעורר השראה בפועלים שלך לשאוף להכרה דומה.",
    "An honorary certificate issued by the Galeria Baderette rewarding endeavour in finishing a task on time. It may inspire your workers to strive for similar recognition.": "תעודת הוקרה המוענקת מטעם גלריית ביידרט על מאמץ בהשלמת משימה בזמן. היא עשויה לעורר השראה בפועלים שלך לשאוף להכרה דומה.",
    "A certificate issued by the Galeria Baderette rewarding the avoidance of complete failure. It might inspire your workers to strive for similar recognition.": "תעודה המוענקת מטעם גלריית ביידרט כפרס על הימנעות מכישלון מוחלט. היא עשויה לעורר השראה בפועלים שלך לשאוף להכרה דומה.",
    "Theodora says that construction has been temporarily paused.": "תיאודורה אומרת שהבנייה הופסקה זמנית.",
    "Donny demands that construction resumes.": "דוני דורש לחדש את הבנייה.",
    "Theodora says construction has resumed.": "תיאודורה אומרת שהבנייה חודשה.",
    "Immortalize our victory! Let all know who built the highest tower of the era! – All that trouble must be worth something!": "הנצח את הניצחון שלנו! תן לכולם לדעת מי בנה את המגדל הגבוה ביותר של העידן! — כל הצרות האלה חייבות להיות שוות משהו!",
    "The world won’t forget what we all achieved! They’ll remember us as pioneers!": "העולם לא ישכח את מה שהשגנו! הם יזכרו אותנו כחלוצים!",
    "Skyline Tower:<br />Pioneers Of A New Dawn": "מגדל קו הרקיע:<br />חלוצי שחר חדש",
    "Donald insists you photograph the Skyline Tower to mark the occasion.": "דונלד מתעקש שתצלם את מגדל קו הרקיע כדי לציין את האירוע.",
    "Donald is pleased with the photograph.": "דונלד מרוצה מהתמונה.",
    "A SKYLINE FOREVER CHANGED": "קו רקיע שהשתנה לנצח",
    "Donald Bader, face of Galeria Baderette, brings a momentous monument to [Area Area([RefGuid]) CityName]! Rumours of a construction plagued with strife dissipate entirely. Bader was very quick to praise his partner, and in particular one Theodora Thistlethorpe for her sterling...(cont. p6.)": "דונלד ביידר, הפנים של גלריית ביידרט, מביא מונומנט כביר אל [Area Area([RefGuid]) CityName]! השמועות על בנייה רוויית מאבקים מתפוגגות לחלוטין. ביידר מיהר לשבח את שותפו, ובמיוחד את אחת, תיאודורה ת'יסלת'ורפ, על עבודתה המצוינת... (המשך בעמ' 6)",
    "Finally, the work’s done! We can move forward with the construction.": "סוף סוף העבודה הושלמה! אנו יכולים להתקדם בבנייה.",
    "Donny reports that the repairs are complete.": "דוני מדווח שהתיקונים הושלמו.",
    "Dust Cloud 1": "ענן אבק 1",
    "Workers on Strike": "פועלים שובתים",
    "Workers Partying": "פועלים חוגגים",
    "As for the fifth...well, he makes it. Barely. The cops, for once, have an open ear and get our witch weighed fast. If there's any kind of lesson, it's he oughtta think to cook his own dinners from now on...": "באשר לחמישי... ובכן, הוא שורד את זה. בקושי. לשם שינוי, השוטרים קשובים ושופטים את המכשפה שלנו במהירות. אם יש לקח כלשהו, הוא שהוא צריך לחשוב על לבשל את ארוחות הערב שלו בעצמו מעכשיו...",
    "A week later Agatha gets the response she wasn't looking for, and the girl was there to see it. Remembers the thud at the door, hiding under the table. When the poor girl left my office that day, I could see blood, dried at the soles of her shoes.": "שבוע לאחר מכן אגתה מקבלת את התשובה שהיא לא חיפשה, והילדה הייתה שם כדי לראות זאת. היא זוכרת את החבטה בדלת, מסתתרת מתחת לשולחן. כשהילדה המסכנה עזבה את המשרד שלי באותו יום, יכולתי לראות דם, יבש על סוליות נעליה.",
    "She had that far-away-look... and all I could do was go and make a promise I knew I couldn't keep, that I'd make sure she was safe. The same damn lie I told Agatha.": "היה לה את המבט המרוחק הזה... וכל מה שיכולתי לעשות זה ללכת ולהבטיח הבטחה שידעתי שלא אוכל לקיים, שאדאג שהיא תהיה בטוחה. אותו שקר ארור שסיפרתי לאגתה.",
    "She just smiled. Like it's done now, and her words won’t raise the dead, so she’ll take it them to the grave. And anyway she says, who am I to deserve such a secret? So, I talk to my client, the owner of the dancing establishment, and she cares. I arrange for the two of them to talk. For once I wait outside.": "היא פשוט חייכה. כאילו זה נגמר כעת, ומילותיה לא יקימו את המתים לתחייה, אז היא תיקח אותן איתה לקבר. ובכל מקרה היא אומרת, מי אני שאזכה לסוד כזה? אז אני מדבר עם הלקוחה שלי, הבעלים של מועדון הריקודים, ואכפת לה. אני מארגן לשתיים לדבר. לשם שינוי, אני ממתין בחוץ.",
    "This case is out of my hands. I made sure to hand my client a list of trustworthy lawyers, for whenever she might need to inquire. Now she got a taste for spilling her secrets, she tried it on me, but I stopped her at 'my father was poisoned'. It’s not my story to tell, and as things stand, I don’t need more ghosts haunting my mind.": "התיק הזה כבר אינו בידיי. הקפדתי למסור ללקוחה שלי רשימה של עורכי דין מהימנים, לכל מקרה שבו תצטרך להתייעץ. כעת כשהיא קיבלה חשק לחשוף את סודותיה, היא ניסתה זאת עליי, אך עצרתי אותה ב'אבי הורעל'. זה לא הסיפור שלי לספר, וכפי שהדברים עומדים, אני לא צריך רוחות רפאים נוספות שירדפו את מוחי.",
    "I didn't bother. In my experience real crims rarely pen riddles and this one happened to be in green ink.": "לא טרחתי. מניסיוני פושעים אמיתיים ממעטים לכתוב חידות, וזו במקרה נכתבה בדיו ירוקה.",
    "Uh-huh. Turns out he's grown bored of the 'Phantom Detective' and is working on a new story. One he wanted put to the test.": "אה-הא. מתברר שנמאס לו מ'הבלש הרפאים' והוא עובד על סיפור חדש. סיפור שהוא רצה להעמיד למבחן.",
    "Young man is nabbed red-handed. Didn't exactly trust the curator's charity after the first time, and besides, wanted to cream a bit off the top.": "הבחור הצעיר נתפס על חם. הוא לא ממש בטח בצדקה של האוצר אחרי הפעם הראשונה, ומלבד זאת, רצה לגזור קופון שמן.",
    "With a little luck. Meanwhile the coroner is exhuming the wife's body for the trial, for some reason she was buried with an oriental Noh mask on. Ugly scenes.": "עם קצת מזל. בינתיים חוקר מקרי המוות מוציא את גופת האישה מקברה לצורך המשפט, מסיבה כלשהי היא נקברה כשעליה מסכת נו מזרחית. מחזות מכוערים.",
    "Artisanal Workshop Wares": "מוצרי סדנת מלאכה",
    "Assembly Line Parts": "חלקי קו הרכבה",
    "Customise Skyscraper": "התאם אישית גורד שחקים",
    "Select a skyscraper level to change its appearance": "בחר רמה של גורד שחקים כדי לשנות את המראה שלו",
    "Foundation": "יסודות",
    "Current Produce!": "תוצרת נוכחית!",
    "This fine-flavoured brandy requires only a select strain of grapes. The acidic, thin wine they make is virtually undrinkable — but give it two loving years to age, and the result is romance in a glass. Warm, flavourful, digestive!": "ברנדי בעל טעם משובח זה דורש זן נבחר בלבד של ענבים. היין החומצי והדליל שהם מייצרים כמעט אינו ראוי לשתייה — אך תנו לו שנתיים אוהבות להתיישן, והתוצאה היא רומנטיקה בכוס. חם, עשיר בטעם, ומסייע לעיכול!",
    "Donald is eager to see the world from above.": "דונלד להוט לראות את העולם מלמעלה.",
    "Build [ToolOneHelper UnlockRequirements([RefGuid]) AT(0) Text] <br />[ToolOneHelper UnlockRequirements([RefGuid]) AT(0) CurrentAmount >> storagegood]/[ToolOneHelper UnlockRequirements([RefGuid]) AT(0) TargetAmount >> storagegood]": "בנה [ToolOneHelper UnlockRequirements([RefGuid]) AT(0) Text] <br />[ToolOneHelper UnlockRequirements([RefGuid]) AT(0) CurrentAmount >> storagegood]/[ToolOneHelper UnlockRequirements([RefGuid]) AT(0) TargetAmount >> storagegood]",
    "Build [ToolOneHelper UnlockRequirements([RefGuid]) AT(0) Text] <br />[ToolOneHelper UnlockRequirements([RefGuid]) AT(0) CurrentAmount >> storagegood]/[ToolOneHelper UnlockRequirements([RefGuid]) AT(0) TargetAmount >> storagegood] <br />OR <br />Build [ToolOneHelper UnlockRequirements([RefGuid]) AT(1) Text] <br />[ToolOneHelper UnlockRequirements([RefGuid]) AT(1) CurrentAmount >> storagegood]/[ToolOneHelper UnlockRequirements([RefGuid]) AT(1) TargetAmount >> storagegood]": "בנה [ToolOneHelper UnlockRequirements([RefGuid]) AT(0) Text] <br />[ToolOneHelper UnlockRequirements([RefGuid]) AT(0) CurrentAmount >> storagegood]/[ToolOneHelper UnlockRequirements([RefGuid]) AT(0) TargetAmount >> storagegood] <br />או <br />בנה [ToolOneHelper UnlockRequirements([RefGuid]) AT(1) Text] <br />[ToolOneHelper UnlockRequirements([RefGuid]) AT(1) CurrentAmount >> storagegood]/[ToolOneHelper UnlockRequirements([RefGuid]) AT(1) TargetAmount >> storagegood]",
    "Upgrade Skyscraper": "שדרג גורד שחקים",
    "Provide height variation in your city’s skyline to achieve the highest panorama effect.": "ספק גיוון בגבהים בקו הרקיע של העיר שלך כדי להשיג את אפקט הפנורמה הגבוה ביותר.",
    "-5 <img height='24' width='24' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text] for 30 minutes": "-5 <img height='24' width='24' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text] למשל 30 דקות",
    "-10 <img height='24' width='24' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text] for 45 minutes": "-10 <img height='24' width='24' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text] למשך 45 דקות",
    "-15 <img height='24' width='24' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text] for 45 minutes": "-15 <img height='24' width='24' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text] למשך 45 דקות",
    "Current <img height='24' width='24' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text]: [Area Area([Conditions QuestArea]) Happiness AverageHappinessByPopulation(15000001) >> happiness]": "נוכחי <img height='24' width='24' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text]: [Area Area([Conditions QuestArea]) Happiness AverageHappinessByPopulation(15000001) >> happiness]",
    "Requires <img height='24' width='24' src=\"[ItemAssetData(190712) Icon]\"/>[ItemAssetData(190712) Text] on the island": "דורש <img height='24' width='24' src=\"[ItemAssetData(190712) Icon]\"/>[ItemAssetData(190712) Text] על האי",
    "Pay <img height='24' width='24' src=\"[AssetData(1010255) Icon]\"/>[AssetData(137505) Text] [AssetData(1010255) Text].": "שלם <img height='24' width='24' src=\"[AssetData(1010255) Icon]\"/>[AssetData(137505) Text] [AssetData(1010255) Text].",
    "Current amount: <img height='24' width='24' src=\"[AssetData(1010255) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010255) >> storagegood]": "כמות נוכחית: <img height='24' width='24' src=\"[AssetData(1010255) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010255) >> storagegood]",
    "Requires <img height='24' width='24' src=\"[ItemAssetData(190722) Icon]\"/>[ItemAssetData(190722) Text] on the island": "דורש <img height='24' width='24' src=\"[ItemAssetData(190722) Icon]\"/>[ItemAssetData(190722) Text] על האי",
    "Pay <img height='24' width='24' src=\"[AssetData(1010017) Icon]\"/>[AssetData(137060) Text]  [AssetData(1010017) Text].": "שלם <img height='24' width='24' src=\"[AssetData(1010017) Icon]\"/>[AssetData(137060) Text]  [AssetData(1010017) Text].",
    "Current balance: <img height='24' width='24' src=\"[AssetData(1010017) Icon]\"/>[Economy MetaStorage StorageAmount(1010017) >> storagegood]": "יתרה נוכחית: <img height='24' width='24' src=\"[AssetData(1010017) Icon]\"/>[Economy MetaStorage StorageAmount(1010017) >> storagegood]",
    "Pay <img height='24' width='24' src=\"[AssetData(1010218) Icon]\"/>[AssetData(137061) Text] [AssetData(1010218) Text].": "שלם <img height='24' width='24' src=\"[AssetData(1010218) Icon]\"/>[AssetData(137061) Text] [AssetData(1010218) Text].",
    "Current amount: <img height='24' width='24' src=\"[AssetData(1010218) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010218) >> storagegood]": "כמות נוכחית: <img height='24' width='24' src=\"[AssetData(1010218) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010218) >> storagegood]",
    "Requires <img height='24' width='24' src=\"[AssetData(1010470) Icon]\"/>[AssetData(1010470) Text] with <img height='24' width='24' src=\"[AssetData(500176) Icon]\"/>[AssetData(137508) Text] on the island.": "דורש <img height='24' width='24' src=\"[AssetData(1010470) Icon]\"/>[AssetData(1010470) Text] עם <img height='24' width='24' src=\"[AssetData(500176) Icon]\"/>[AssetData(137508) Text] על האי.",
    "+5 <img height='24' width='24' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text] for 10 minutes": "+5 <img height='24' width='24' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text] למשך 10 דקות",
    "Pay <img height='24' width='24' src=\"[AssetData(1010214) Icon]\"/>[AssetData(137062) Text] [AssetData(1010214) Text], <img height='24' width='24' src=\"[AssetData(1010238) Icon]\"/>[AssetData(137062) Text] [AssetData(1010238) Text].": "שלם <img height='24' width='24' src=\"[AssetData(1010214) Icon]\"/>[AssetData(137062) Text] [AssetData(1010214) Text], <img height='24' width='24' src=\"[AssetData(1010238) Icon]\"/>[AssetData(137062) Text] [AssetData(1010238) Text].",
    "Current amount: <img height='24' width='24' src=\"[AssetData(1010214) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010214) >> storagegood], <img height='24' width='24' src=\"[AssetData(1010238) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010238) >> storagegood].": "כמות נוכחית: <img height='24' width='24' src=\"[AssetData(1010214) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010214) >> storagegood], <img height='24' width='24' src=\"[AssetData(1010238) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010238) >> storagegood].",
    "+10 <img height='24' width='24' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text] for 15 minutes": "+10 <img height='24' width='24' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text] למשך 15 דקות",
    "Pay <img height='24' width='24' src=\"[AssetData(1010017) Icon]\"/>[AssetData(137063) Text]  [AssetData(1010017) Text].": "שלם <img height='24' width='24' src=\"[AssetData(1010017) Icon]\"/>[AssetData(137063) Text]  [AssetData(1010017) Text].",
    "+20 <img height='24' width='24' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text] for 20 minutes": "+20 <img height='24' width='24' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text] למשך 20 דקות",
    "Pay <img height='24' width='24' src=\"[AssetData(1010017) Icon]\"/>[AssetData(137064) Text]  [AssetData(1010017) Text].": "שלם <img height='24' width='24' src=\"[AssetData(1010017) Icon]\"/>[AssetData(137064) Text]  [AssetData(1010017) Text].",
    "Construction paused for 2 minutes": "הבנייה הופסקה למשך 2 דקות",
    "Construction paused for 5 minutes": "הבנייה הופסקה למשך 5 דקות",
    "Pay <img height='24' width='24' src=\"[AssetData(1010196) Icon]\"/>[AssetData(137065) Text] [AssetData(1010196) Text].": "שלם <img height='24' width='24' src=\"[AssetData(1010196) Icon]\"/>[AssetData(137065) Text] [AssetData(1010196) Text].",
    "Current amount: <img height='24' width='24' src=\"[AssetData(1010196) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010196) >> storagegood]": "כמות נוכחית: <img height='24' width='24' src=\"[AssetData(1010196) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010196) >> storagegood]",
    "Pay <img height='24' width='24' src=\"[AssetData(1010231) Icon]\"/>[AssetData(137066) Text] [AssetData(1010231) Text].": "שלם <img height='24' width='24' src=\"[AssetData(1010231) Icon]\"/>[AssetData(137066) Text] [AssetData(1010231) Text].",
    "Current amount: <img height='24' width='24' src=\"[AssetData(1010231) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010231) >> storagegood]": "כמות נוכחית: <img height='24' width='24' src=\"[AssetData(1010231) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010231) >> storagegood]",
    "Construction paused for 10 minutes": "הבנייה הופסקה למשך 10 דקות",
    "Pay <img height='24' width='24' src=\"[AssetData(1010017) Icon]\"/>[AssetData(137067) Text]  [AssetData(1010017) Text].": "שלם <img height='24' width='24' src=\"[AssetData(1010017) Icon]\"/>[AssetData(137067) Text]  [AssetData(1010017) Text].",
    "Pay <img height='24' width='24' src=\"[AssetData(1010231) Icon]\"/>[AssetData(137091) Text] [AssetData(1010231) Text].": "שלם <img height='24' width='24' src=\"[AssetData(1010231) Icon]\"/>[AssetData(137091) Text] [AssetData(1010231) Text].",
    "Current amount: <img height='24' width='24' src=\"[AssetData(1010231) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010231) >> storagegood]": "כמות נוכחית: <img height='24' width='24' src=\"[AssetData(1010231) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010231) >> storagegood]",
    "Construction paused for 20 minutes": "הבנייה הופסקה למשך 20 דקות",
    "Pay <img height='24' width='24' src=\"[AssetData(1010017) Icon]\"/>[AssetData(137092) Text]  [AssetData(1010017) Text].": "שלם <img height='24' width='24' src=\"[AssetData(1010017) Icon]\"/>[AssetData(137092) Text]  [AssetData(1010017) Text].",
    "Pay <img height='24' width='24' src=\"[AssetData(1010228) Icon]\"/>[AssetData(137111) Text] [AssetData(1010228) Text].": "שלם <img height='24' width='24' src=\"[AssetData(1010228) Icon]\"/>[AssetData(137111) Text] [AssetData(1010228) Text].",
    "Current amount: <img height='24' width='24' src=\"[AssetData(1010228) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010228) >> storagegood]": "כמות נוכחית: <img height='24' width='24' src=\"[AssetData(1010228) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010228) >> storagegood]",
    "RED CARPET TREATMENT!": "טיפול שטיח אדום!",
    "Galeria Baderette is the talk of the town, as the arcade floods with the frocks and frills of women shopping entirely for themselves for the first time! The reason? Lipstick! Say what you will about how it looks — some are calling it the key to a new era of self-determination...(Janice Spark reports p4.)": "גלריית ביידרט היא שיחת היום, כאשר הפסז' מוצף בשמלות ובקישוטים של נשים העורכות קניות לחלוטין עבור עצמן בפעם הראשונה! הסיבה? שפתון! תגידו מה שתגידו על איך שזה נראה — יש המכנים זאת המפתח לעידן חדש של הגדרה עצמית... (ג'ניס ספארק מדווחת, עמ' 4)",
    "Donny and his wife are jubilant about the lipstick patent.": "דוני ואשתו צוהלים על פטנט השפתון.",
    "Lose Monument": "להפסיד את המונומנט",
    "Lose Island": "להפסיד את האי",
    "Donny is aghast that you stopped building the tower.": "דוני מזועזע מכך שהפסקת לבנות את המגדל.",
    "Donny is astounded that you lost the Skyline Tower island.": "דוני נדהם מכך שהפסדת את האי של מגדל קו הרקיע.",
    "Theodora never trusted Mr. Bader anyway.": "תיאודורה מעולם לא בטחה במר ביידר ממילא.",
    "Production will take time, so let's diversify our portfolio— The Arcade could cater for the furnishing of empty office towers.": "הייצור ייקח זמן, אז בואו נגוון את תיק העבודות שלנו — הפסז' יוכל לספק את הריהוט של מגדלי משרדים ריקים.",
    "A hit! Of course my Galeria Baderette is the best. Let’s keep it that way, the lamps are old news, we need a new best seller! We could even ask the customers...": "להיט! ברור שגלריית ביידרט שלי היא הטובה ביותר. בואו נשמור על זה ככה, המנורות הן היסטוריה, אנו זקוקים לרב-מכר חדש! נוכל אפילו לשאול את הלקוחות...",
    "This weird loser's really obsessed with me! I mean I’m impressive, takes a lot of work to look like this. Are you into grooming? Cosmetics and such?": "הלוזר המוזר הזה ממש אובססיבי לגביי! כלומר, אני מרשים, זה דורש המון עבודה כדי להיראות ככה. האם אתה בעניין של טיפוח? קוסמטיקה וכאלה?",
    "Well, if people aren’t all smiles! A perfect advert! But something’s off– I know the mouth-breathers are buying but the numbers don't add!": "ובכן, האנשים כולם מחייכים! פרסומת מושלמת! אבל משהו לא מסתדר — אני יודע שהפשוטים קונים אבל המספרים לא מתחברים!",
    "A Drug Store hit! With so many arcades we need to fill em’! Build bigger towers. Attract some whales.": "להיט בבית המרקחת! עם כל כך הרבה פסז'ים אנחנו צריכים למלא אותם! בנה מגדלים גדולים יותר. משוך כמה לקוחות כבדים (whales).",
    "My guru, city's really grown! Lots of rich people, lots of very wealthy people. But I was here first, I'm the original, the biggest whale. I think they need a reminder...": "הגורו שלי, העיר באמת גדלה! המון אנשים עשירים, המון אנשים אמידים מאוד. אבל אני הייתי כאן קודם, אני המקורי, הלקוח הכי כבד כאן. אני חושב שהם צריכים תזכורת...",
    "It'll be a heck of a view! Don't make me wait. Really, I hate waiting. The faster you build the bigger the pay-off for you.": "זה יהיה נוף מדהים! אל תגרום לי לחכות. באמת, אני שונא לחכות. ככל שתבנה מהר יותר, כך התגמול שלך יהיה גדול יותר.",
    "Jenny": "ג'ני",
    "<font size=\"18\"><b>Construction Interrupted</b></font><br /><i>(due to survey underway)</i><br /><br />Time estimate: 2 minutes": "<font size=\"18\"><b>הבנייה הופסקה</b></font><br /><i>(עקב בדיקה בעיצומה)</i><br /><br />הערכת זמן: 2 דקות",
    "<font size=\"18\"><b>Construction Interrupted</b></font><br /><i>(due to security installation)</i><br /><br />Time estimate: 5 minutes": "<font size=\"18\"><b>הבנייה הופסקה</b></font><br /><i>(עקב התקנת אמצעי אבטחה)</i><br /><br />הערכת זמן: 5 דקות",
    "<font size=\"18\"><b>Construction Interrupted</b></font><br /><i>(due to reinforcement of columns)</i><br /><br />Time estimate: 10 minutes": "<font size=\"18\"><b>הבנייה הופסקה</b></font><br /><i>(עקב חיזוק העמודים)</i><br /><br />הערכת זמן: 10 דקות",
    "<font size=\"18\"><b>Construction Interrupted</b></font><br /><i>(due to reinforcement of columns)</i><br /><br />Time estimate: 20 minutes": "<font size=\"18\"><b>הבנייה הופסקה</b></font><br /><i>(עקב חיזוק העמודים)</i><br /><br />הערכת זמן: 20 דקות",
    "<font size=\"18\"><b>Construction Interrupted</b></font><br /><i>(due to imminent collapse)</i><br /><br />Everyone runs away!": "<font size=\"18\"><b>הבנייה הופסקה</b></font><br /><i>(עקב קריסה מיידית)</i><br /><br />כולם בורחים!",
    "<font size=\"18\"><b>Construction Interrupted</b></font><br /><i>(due to workers strike)</i><br /><br />Duration: undetermined": "<font size=\"18\"><b>הבנייה הופסקה</b></font><br /><i>(עקב שביתת פועלים)</i><br /><br />משך זמן: לא נקבע",
    "<font size=\"18\"><b>Construction Interrupted</b></font><br /><i>(due to worker barbecue)</i><br /><br />Duration: undetermined": "<font size=\"18\"><b>הבנייה הופסקה</b></font><br /><i>(עקב ברביקיו של הפועלים)</i><br /><br />משך זמן: לא נקבע",
    "The dedication of the Skyline Tower towards environmental awareness has encouraged its inhabitants to add greenery to their balconies.": "הקדשת מגדל קו הרקיע לטובת מודעות סביבתית עודדה את תושביו להוסיף צמחייה למרפסות שלהם.",
    "The dedication of the Skyline Tower towards an anti-consumerism campaign has encouraged its inhabitants to rethink and reduce their luxury impulse purchases.": "הקדשת מגדל קו הרקיע לטובת קמפיין נגד צרכנות עודדה את תושביו לחשוב מחדש ולצמצם את רכישות המותרות האימפולסיביות שלהם.",
    "The dedication of the Skyline Tower towards a fair and optimistic future has encouraged its inhabitants to add greenery to their balconies, and to rethink and reduce their luxury impulse purchases.": "הקדשת מגדל קו הרקיע לטובת עתיד הוגן ואופטימי עודדה את תושביו להוסיף צמחייה למרפסותיהם, ולחשוב מחדש ולצמצם את רכישות המותרות האימפולסיביות שלהם.",
    "White Cherry Pew": "ספסל דובדבן לבן",
    "White Cherry": "דובדבן לבן",
    "A crown of beautiful white cherry blossoms!": "עטרה של פריחת דובדבן לבן יפהפייה!",
    "Knowing that no other volunteers could be found across the entire city has only served to scare those up on the scaffolds even more...": "הידיעה שלא ניתן למצוא מתנדבים נוספים בכל רחבי העיר רק הפחידה עוד יותר את אלו שנמצאים למעלה על הפיגומים...",
    "Your decision to ignore the workers' fears of climbing the scaffolding has caused them to grow weary of you.": "החלטתך להתעלם מפחדי הפועלים לטפס על הפיגומים גרמה להם להתרחק ממך.",
    "Breaking your promise to build a hospital next to the tower’s construction site has led to brewing resentment among your workers.": "הפרת הבטחתך לבנות בית חולים ליד אתר הבנייה של המגדל הובילה לתרעומת גוברת בקרב הפועלים שלך.",
    "Your refusal to provide security measures at the construction site after the accident has distressed many of your workers.": "סירובך לספק אמצעי בטיחות באתר הבנייה לאחר התאונה גרם למצוקה בקרב רבים מהפועלים שלך.",
    "Your choice to punish a random group of workers for the stolen construction goods has been received with a mixture of anger and fear.": "החלטתך להעניש קבוצה אקראית של פועלים על גניבת חומרי הבנייה התקבלה בתערובת של כעס ופחד.",
    "The workers are appreciative of the zoo tickets you gifted them.": "הפועלים מעריכים את הכרטיסים לגן החיות שהענקת להם במתנה.",
    "The barbecue you organized at the construction site has been well-received by the workers, who took it as a nice thank you.": "הברביקיו שארגנת באתר הבנייה התקבל בברכה על ידי הפועלים, שראו בכך הבעת תודה נחמדה.",
    "Your workers didn't expect such a generous bonus for their hard work, and they're very grateful to you. It's something they'll remember for a while.": "הפועלים שלך לא ציפו לבונוס נדיב כל כך על עבודתם הקשה, והם אסירי תודה לך מאוד. זה משהו שהם יזכרו לזמן מה.",
    "The newspaper boy will get you on the right track. Read the hints carefully and select the corresponding items to move forward. If you get stuck, look out for blue highlighting.": "נער העיתונים יכוון אותך למסלול הנכון. קרא את הרמזים בעיון ובחר את הפריטים המתאימים כדי להתקדם. אם נתקעת, חפש הדגשה כחולה.",
    "Maintaining a building of this type requires specialised staff and equipment — whether it becomes expensive or profitable relies on careful supervision.": "תחזוקת בניין מסוג זה דורשת צוות וציוד מיוחדים — השאלה אם הוא יהפוך ליקר או רווחי תלויה בפיקוח קפדני.",
    "Toys": "צעצועים",
    "Billiard Tables": "שולחנות ביליארד",
    "Violins": "כינורות",
    "Cognac": "קוניאק",
    "Typewriters": "מכונות כתיבה",
    "Biscuits": "ביסקוויטים",
    "Elevators": "מעליות",
    "Lacquer": "לקה",
    "Chewing Gum": "מסטיק",
    "Ethanol": "אתנול",
    "Celluloid": "צלולואיד",
    "Lemonade": "לימונדה",
    "Shampoo": "שמפו",
    "Souvenir": "מזכרת",
    "Jenny Destination": "יעד ג'ני",
    "Build: [AssetData([RefGuid]) Text]": "בנה: [AssetData([RefGuid]) Text]",
    "Get Rich Quick Vol VII: Automation Nation": "להתעשר במהירות כרך ז': אומת האוטומציה",
    "When you select a skyscraper, smaller skyscrapers are <b>colored in green</b>. <br />Taller or equal height skyscrapers are <b>colored in brown</b>. <br /><br />Click on the \"?\" in the skyscraper menu to get more information on the Panorama Effect.": "כאשר בוחרים גורד שחקים, גורדי שחקים נמוכים יותר <b>צבועים בירוק</b>. <br />גורדי שחקים גבוהים יותר או שווי גובה <b>צבועים בחום</b>. <br /><br />לחץ על ה-\"?\" בתפריט גורדי השחקים כדי לקבל מידע נוסף על אפקט הפנורמה.",
    "TutorialHint HighLife": "TutorialHint HighLife",
    "In the seventh volume of his acclaimed business series, Dr. Val Goldfall argues that all humans can essentially be fed code.": "בכרך השביעי של סדרת העסקים המהוללת שלו, ד\"ר ואל גולדפול טוען שניתן בעצם להזין את כל בני האדם בקוד.",
}

# Add skips to skip.json
skip_file = "skip.json"
skips = []
if os.path.exists(skip_file):
    try:
        skips = json.load(open(skip_file, encoding="utf-8"))
    except Exception:
        skips = []

skips_set = set(skips)
for s in skips_to_add:
    skips_set.add(s)
new_skips = sorted(list(skips_set), key=lambda x: int(x))
json.dump(new_skips, open(skip_file, "w", encoding="utf-8"), ensure_ascii=False, indent=0)
print(f"Updated skip.json: {len(new_skips)} total skips")

# Clean up other trans_part_*.json files
for i in range(2, 6):
    p = f"trans_part_{i}.json"
    if os.path.exists(p):
        os.remove(p)
        print(f"Deleted old {p}")
for i in range(1, 6):
    p = f"skip_part_{i}.json"
    if os.path.exists(p):
        os.remove(p)
        print(f"Deleted old {p}")

# Translate the batch
translated = {}
missing = []
for guid, val in batch.items():
    if guid in skips_to_add:
        continue
    if val in mapping:
        translated[guid] = mapping[val]
    else:
        # Check if it was stripped by auto_skip or is in skips
        if guid in skips_set:
            continue
        missing.append((guid, val))

if missing:
    print(f"Error: {len(missing)} missing translations in batch!")
    for g, v in missing[:10]:
        print(f"  {g}: {v!r}")
else:
    # Save to trans_part_1.json
    json.dump(translated, open("trans_part_1.json", "w", encoding="utf-8"), ensure_ascii=False, indent=4)
    print(f"Successfully saved {len(translated)} translations to trans_part_1.json")