import json
import os

batch = json.load(open("to_translate_batch.json", encoding="utf-8"))

skips_to_add = []

mapping = {
    "Furniture Store Wares": "סחורות חנות הרהיטים",
    "A store for high-end movables — perfect for furnishing new skyscraper apartments! An elegant office, a cosy bedroom, and a vanity screen to divide the two!": "חנות לרהיטים יוקרתיים — מושלמת לריהוט דירות גורדי השחקים החדשות! משרד אלגנטי, חדר שינה נעים ופרגוד שיפריד בין השניים!",
    "Shopping Catalogue": "קטלוג קניות",
    "Total number of design patents acquired": "סך כל פטנטי העיצוב שהושגו",
    "Drug Store Products": "מוצרי בית המרקחת",
    "A store for tinctures, pastes, and chemical concoctions. Customers are greeted by a fragrant mix of cinnamon, citrus, and hibiscus as they seek to cure the incurable, and expunge the unexpungeable.": "חנות למרקחות, משחות ותכשירים כימיים. הלקוחות מתקבלים בתערובת ריחנית של קינמון, פירות הדר והיביסקוס, בעודם מבקשים לרפא את חשוכי המרפא ולמחות את מה שלא ניתן למחות.",
    "Chemical Plant: Chewing Gum": "מפעל כימי: מסטיק",
    "Chewing Gum": "מסטיק",
    "Department Store: Crockery": "חנות כלבו: כלי אוכל",
    "Department Store: Vacuum Cleaners": "חנות כלבו: שואבי אבק",
    "Department Store: Refrigerators": "חנות כלבו: מקררים",
    "Department Store: Briefcases": "חנות כלבו: תיקי מסמכים",
    "Drug Store: Detergent": "בית מרקחת: חומר ניקוי",
    "Drug Store: Lipstick": "בית מרקחת: שפתון",
    "Drug Store: Face Cream": "בית מרקחת: קרם פנים",
    "Drug Store: Pomade": "בית מרקחת: משחת שיער",
    "Estimated Crockery Sales": "מכירות כלי אוכל מוערכות",
    "Estimated Vacuum Cleaner Sales": "מכירות שואבי אבק מוערכות",
    "Estimated Refrigerator Sales": "מכירות מקררים מוערכות",
    "Estimated Detergent Sales": "מכירות חומרי ניקוי מוערכות",
    "Estimated Lipstick Sales": "מכירות שפתונים מוערכות",
    "Estimated Face Cream Sales": "מכירות קרם פנים מוערכות",
    "Crockery": "כלי אוכל",
    "Vacuum Cleaner": "שואב אבק",
    "Refrigerator": "מקרר",
    "Briefcase": "תיק מסמכים",
    "Detergent": "חומר ניקוי",
    "Lipstick": "שפתון",
    "Face Cream": "קרם פנים",
    "Pomade": "משחת שיער",
    "This fully automated breakfast machine is, apparently, calibrated perfectly for the toast that’s ‘just right’ — simply pop in a slice, wait, and soon you’ll smell the delightful scent of perfectly toasted bread! If you like your bread rare or well-done, look elsewhere.": "מכונת ארוחת הבוקר האוטומטית לחלוטין הזו מכוילת, ככל הנראה, בצורה מושלמת לקבלת הטוסט 'המדויק' — פשוט הכנס פרוסה, המתן, ובקרוב תריח את הניחוח הנפלא של לחם קלוי בצורה מושלמת! אם אתה אוהב את הלחם שלך כמעט לא עשוי או שרוף, חפש במקום אחר.",
    "Feel good about having guests again! Set the table for any occasion — a cosy breakfast, a quick lunch, a fancy dinner party — then leave the dirty dishes for the next day! Or the one after that... Or just throw them out and buy some more!": "תרגיש טוב לארח אורחים שוב! ערוך את השולחן לכל אירוע — ארוחת בוקר נעימה, ארוחת צהריים מהירה, מסיבת ארוחת ערב מהודרת — ואז השאר את הכלים המלוכלכים ליום המחרת! או ליום שאחריו... או פשוט זרוק אותם וקנה חדשים!",
    "No more sweeping things under the rug! This machine removes dirt in no time. Five minutes until the guests arrive? No problem! It'll huff and puff and leave the apartment clean as a new dime. It can even tackle the bigger stains! Sick of the cat, the kids, the wife or husband? You know what to do!": "לא עוד לטאטא דברים מתחת לשטיח! המכונה הזו מסירה לכלוך תוך זמן קצר. חמש דקות עד שהאורחים מגיעים? אין בעיה! היא תתנשף ותתנשף ותשאיר את הדירה נקייה ומבריקה. היא אפילו יכולה להתמודד עם הכתמים הגדולים יותר! נמאס לך מהחתול, הילדים, האישה או הבעל? אתה יודע מה לעשות!",
    "Tired of going up and down the stairs to the ice cellar at garden parties? Dashing to the iceman for your icebox, or worse still, waiting for that big snow? Imagine ice every day, all year 'round! Spoiled food? Yesterday’s worry! A perfectly iced glass of summer strawberry and cucumber? Coming right up!": "נמאס לך לרדת ולעלות במדרגות למרתף הקרח במסיבות גן? לרוץ למוכר הקרח בשביל ארגז הקרח שלך, או גרוע מכך, לחכות לשלג הגדול ההוא? דמיין קרח כל יום, כל השנה! אוכל מקולקל? הדאגה של אתמול! כוס צוננת להפליא של תות ומלפפון של קיץ? כבר מגיעה!",
    "A superior leather attaché for people with all-too-important business to attend to. Perfect for legal documents, top secret papers, diamonds, and cash bribes — all the essentials in one place! But for goodness' sake, don't leave it lying around.": "תיק מנהלים מעור משובח לאנשים שיש להם עסקים חשובים מכדי לעסוק בהם. מושלם עבור מסמכים משפטיים, ניירות סודיים ביותר, יהלומים ושוחד במזומן — כל הדברים החיוניים במקום אחד! אבל למען השם, אל תשאיר אותו זרוק סתם כך.",
    "For optimal use, apply this carbon-based black paste to your teeth twice or thrice a day and scrub vigorously with a brush! You can even brush your tongue if you wish, though we'll leave that decision entirely up to you...": "לשימוש אופטימלי, מרח את המשחה השחורה הזו המבוססת על פחם על שיניך פעמיים או שלוש ביום ושפשף במרץ עם מברשת! תוכל אפילו לצחצח את הלשון אם תרצה, למרות שנשאיר את ההחלטה הזו לחלוטין לשיקול דעתך...",
    "A synthetic surfactant, this all-rounder is the cleansing agent to remove blemishes big or small. Whether you mop, scrub, or wash, it’ll smell citrusy fresh — and take your skin off if you're not careful!": "חומר פעיל שטח סינתטי זה הוא חומר הניקוי הרב-תכליתי להסרת כתמים גדולים כקטנים. בין אם תשטוף, תשפשף או תכבס, הריח יהיה רענן ולימוני — והוא עלול לקלף לך את העור אם לא תיזהר!",
    "A portable splash of fiery red for the perfect cupid's bow. Once the preserve only of actresses and undesirables, lipstick now heralds a new era of emancipation for women — suffragettes walking arm-in-arm — who have the freedom of the arcades!": "נגיעה ניידת של אדום לוהט למראה שפתיים מושלם. פעם נחלתן של שחקניות ונשים לא רצויות בלבד, השפתון מבשר כעת על עידן חדש של שחרור לנשים — סופרג'יסטיות הצועדות שלובי זרוע — שיש להן את החופש לטייל במרכזי הקניות!",
    "A moisturising lotion that conjures images of groves of citrus and pleasant afternoons, it's soft and gentle on the skin, and promises the secrets of eternal youth — <i>long-term effects unknown, please read the small print, terms and conditions apply, may contain traces of nuts.</i>": "קרם לחות המעורר תמונות של מטעי פירות הדר ואחר צהריים נעימים, הוא רך ועדין על העור, ומבטיח את סודות נעורי הנצח — <i>השפעות ארוכות טווח אינן ידועות, אנא קרא את האותיות הקטנות, תנאים והגבלות חלים, עשוי להכיל עקבות של אגוזים.</i>",
    "The discerning gentleman has a duty — nay! — an obligation to the upkeep of his hair, real or otherwise, and the concealment of the first sign of the dreaded grey... Apply liberally to shape, hue and style your moustaches too! For removal, a companion detergent is available at all respectable retailers...": "לג'נטלמן המתוחכם יש חובה — לא! — התחייבות לטיפוח שיערו, האמיתי או המלאכותי, ולהסתרת הסימן הראשון של השיבה המפחידה... מרח בנדיבות כדי לעצב, לצבוע ולסגנן גם את השפם שלך! להסרה, חומר ניקוי תואם זמין אצל כל הקמעונאים המכובדים...",
    "Chemical Plant (New World)": "מפעל כימי (העולם החדש)",
    "Celluloid": "צלולואיד",
    "Chewing Gum": "מסטיק",
    "Chemical Plant: Celluloid": "מפעל כימי: צלולואיד",
    "Chemical Factory Patent List": "רשימת פטנטים של מפעל כימי",
    "Thankfully, the use of celluloid has now replaced that of elephant ivory in the manufacture of billiard balls — a shapeshifting, chemical wonder! Simply liquefy, pour into any mold, wait, and ta-da — dolls? A mantelpiece clock? The only limit is your imagination!": "למרבה המזל, השימוש בצלולואיד החליף כעת את השנהב של פילים בייצור כדורי ביליארד — פלא כימי משנה צורה! פשוט הנזל, שפוך לכל תבנית, המתן, וטא-דא — בובות? שעון לאח? הגבול היחיד הוא הדמיון שלך!",
    "This sticky, sugary, elastic snack is infused with the sweet and spicy flavors of cinnamon — for a little while, anyway. The medical advisory board of High Clarence Hall advise that it should be spat out once the enjoyment has passed, to avoid the agglomeration of indissolubles in the lower abdomen.": "חטיף גמיש, מתוק ודביק זה ספוג בטעמים המתוקים והחריפים של קינמון — לזמן קצר, בכל אופן. הוועדה הרפואית המייעצת של היי קלרנס הול ממליצה לירוק אותו ברגע שההנאה חולפת, כדי למנוע הצטברות של חומרים בלתי מסיסים בבטן התחתונה.",
    "Biscuits": "ביסקוויטים",
    "Typewriter": "מכונת כתיבה",
    "Toys": "צעצועים",
    "Billiard Tables": "שולחנות ביליארד",
    "Violins": "כינורות",
    "Cognac": "קוניאק",
    "You have my attention until the elevator reaches my floor. That's five minutes, so shoot!": "יש לך את תשומת הלב שלי עד שהמעלית תגיע לקומה שלי. זה חמש דקות, אז שוט!",
    "I avoid the lower floors, I abhor the feeling of going down.": "אני נמנע מהקומות הנמוכות, אני מתעב את תחושת הירידה.",
    "\"I care for a lofty lifestyle\" - is that actually something people say?": "\"אני מעדיף סגנון חיים גבוה\" - זה באמת משהו שאנשים אומרים?",
    "All inclusive: Living spaces, offices, shops, entertainment. Soon the city will be brimming with smaller cities.": "הכל כלול: שטחי מגורים, משרדים, חנויות, בידור. בקרוב העיר תהיה גדושה בערים קטנות יותר.",
    "As a fellow Investor once said 'plant trees that other men will sit under,' and look at the shadow this tower provides!": "כמו שמשקיע עמית אמר פעם, 'שתול עצים שאנשים אחרים יישבו תחתיהם', ותראה איזה צל המגדל הזה מספק!",
    "They do know we have stairs? The party is tonight and I needed those drinks yesterday. Have them carry the crates up.": "הם יודעים שיש לנו מדרגות? המסיבה הלילה והייתי צריך את המשקאות האלה אתמול. תגיד להם להעלות את הארגזים למעלה.",
    "David, this isn't about us merely competing, we have to dominate!": "דייוויד, זה לא רק עניין של תחרות בינינו, אנחנו חייבים לשלוט!",
    "I have to say the novel view of the city even elevates the chore of bookkeeping, for a while anyhow.": "אני חייב לומר שהנוף החדש של העיר אפילו משדרג את המטלה של הנהלת החשבונות, לזמן מה בכל אופן.",
    "Charles is appraising the property as we speak, a new get-away. I grow tired of the countryside.": "צ'ארלס מעריך את הנכס ברגע זה, מקום מפלט חדש. נמאס לי מהאזור הכפרי.",
    "Wallace was droning on about some supposedly useful invention, what a bore.": "וואלאס ליהג על איזו המצאה שימושית לכאורה, איזה שיעמום.",
    "Well yes, I have heard murmurs about rent pricing— but give the buggers an inch and they'll take a mile.": "נו טוב, שמעתי שמועות על מחירי השכירות — אבל תן לממזרים אצבע והם ירצו את כל היד.",
    "I instructed Hall: we settle out of court. Hook or crook, Janice, hook or crook.": "הנחיתי את הול: אנחנו סוגרים את זה מחוץ לכותלי בית המשפט. בטוב או ברע, ג'ניס, בטוב או ברע.",
    "The skyline is reminiscent of the stock market, you never know which district is about to rise an which about to fall.": "קו הרקיע מזכיר את שוק המניות, אתה אף פעם לא יודע איזה רובע עומד לעלות ואיזה עומד לרדת.",
    "I assure you the real estate market will switch from square to cubic meters. There's simply room for growth.": "אני מבטיח לך ששוק הנדל\"ן יעבור ממטרים רבועים למעוקבים. יש פשוט מקום לצמיחה.",
    "After a fashion the skyline mirrors society. The lows and highs.": "במובן מסוים קו הרקיע משקף את החברה. המורדות והעליות.",
    "Dizzying is it not?": "מסחרר, הלא כן?",
    "Up here my good soul, the stars are just around the corner.": "כאן למעלה, נשמה טובה שלי, הכוכבים נמצאים ממש מעבר לפינה.",
    "To further science is to stand astride the shoulders of giants, or... simply take the elevator to the top.": "לקדם את המדע פירושו לעמוד על כתפי ענקים, או... פשוט לקחת את המעלית לקצה.",
    "Do you think the upstairs neighbours might be more accommodating? You see, I need to test this at altitude...": "האם אתה חושב שהשכנים מלמעלה יהיו יותר נוחים? אתה מבין, אני צריך לבדוק את זה בגובה...",
    "Precisely— the great feat of engineering is translating the measurable into the immeasurable.": "בדיוק — ההישג ההנדסי הגדול הוא תרגום המדיד לבלתי מדיד.",
    "The risk is due to the vertical build you see, fire moves upwards.": "הסיכון נובע מהבנייה האנכית, אתה מבין, אש נעה כלפי מעלה.",
    "I have said it before and I will say it again, zoning restrictions are the death of creative construction!": "אמרתי זאת בעבר ואומר זאת שוב, מגבלות תכנון ובנייה הן המוות של הבנייה היצירתית!",
    "Would you mind skipping my window? It helps me to gaze out across the city when I'm stuck on a problem.": "אכפת לך לדלג על החלון שלי? זה עוזר לי להביט אל העיר כשאני תקוע בבעיה.",
    "Are you aware the soap you are using to clean the windows, is a feat of science too?": "האם אתה מודע לכך שהסבון שבו אתה משתמש לניקוי החלונות הוא גם הישג מדעי?",
    "I despise animal cruelty, but that pigeon coop must go, I have not slept a wink!": "אני מתעב התאכזרות לבעלי חיים, אבל שובך היונים הזה חייב לעוף, לא עצמתי עין!",
    "Sure, the elevator is a grand feat of engineering— rising easily to the top, even— but much ingenuity is less overt— take the flush toilet!": "בטח, המעלית היא הישג הנדסי גדול — אפילו עולה בקלות לקצה — אבל הרבה תושייה היא פחות גלויה — קח למשל את האסלה עם הניאגרה!",
    "Shameless! Read the second paragraph, identical in every regard— even the semiconductor junctions! Martha, they've stolen my design!": "חסר בושה! קראי את הפסקה השנייה, זהה לחלוטין מכל בחינה — אפילו חיבורי חצי המוליך! מרתה, הם גנבו את העיצוב שלי!",
    "For heaven's sake close the blinds Harold! The light will damage the samples!": "למען השם סגור את התריסים, הארולד! האור יפגע בדגימות!",
    "Get me the binoculars— it's those neighbours acting up again.": "הבא לי את המשקפת — אלה השכנים שמתפרעים שוב.",
    "Honey, who would we call? Of course I know how to fix a stuck window, I'm an engineer for chrissakes.": "מותק, למי נתקשר? ברור שאני יודע איך לתקן חלון תקוע, אני מהנדס למען השם.",
    "Artisan's Workshop": "סדנת אומנים",
    "Surely we should take the stairs! It will feel like ascending a mountain!": "בוודאי שעלינו לעלות במדרגות! זה ירגיש כמו טיפוס על הר!",
    "Look! From up here the other skyscrapers look itsy-bitsy!": "תראה! מכאן למעלה גורדי השחקים האחרים נראים פיציים!",
    "Louise, tell me true is it my imagination or does it resemble a giant needle?": "לואיז, תגידי לי את האמת, זה הדמיון שלי או שזה דומה למחט ענקית?",
    "There she is, the Skyline Tower! A beacon for all the world to behold!": "הנה הוא, מגדל קו הרקיע! מגדלור שכל העולם יכול לחזות בו!",
    "She is a marvel!": "הוא פלא!",
    "I feel as though each day there's a new piece in the papers on some elevator mishap. There's just so much to go awry on the way up or down...": "אני מרגיש כאילו כל יום יש כתבה חדשה בעיתונים על איזו תקלה במעלית. יש פשוט כל כך הרבה דברים שיכולים להשתבש בדרך למעלה או למטה...",
    "You know Marcy, one spark might turn that spire into a towering inferno...": "את יודעת מרסי, ניצוץ אחד עלול להפוך את הצריח הזה למלכודת אש נישאת...",
    "Humans made this! ...I mean just look at how measly we are in comparison!": "בני אדם בנו את זה! ...זאת אומרת, פשוט תראה כמה אנחנו עלובים בהשוואה לזה!",
    "Look up there, the flag! Are we supposed to put our hand to our heart?": "תסתכל שם למעלה, הדגל! אנחנו אמורים להניח יד על הלב?",
    "There's a foreboding feeling in the air, hell I even saw lightning strike the needle once!": "יש תחושה מבשרת רעות באוויר, לעזאזל, אפילו ראיתי פעם ברק פוגע במחט!",
    "Oh it's a mighty tower, don't get me wrong, it's overpowering. But, from out on the farm it's a spike on the horizon next to mountains.": "הו, זה מגדל אדיר, אל תבין אותי לא נכון, הוא משתלט. אבל מהחווה זה נראה כמו סיכה באופק ליד ההרים.",
    "Darling look! All the way up they are, cleaning the windows! Hanging on by a thread!": "יקירתי תראי! הם נמצאים שם למעלה, מנקים את החלונות! תלויים על בלימה!",
    "Assembly Line: Biscuits": "פס ייצור: ביסקוויטים",
    "Helen was adamant that I didn't need to get her a present. A little too adamant so...": "הלן הייתה נחרצת בכך שלא הייתי צריך להביא לה מתנה. קצת נחרצת מדי, אז...",
    "Scuse me, would you kindly point me towards the lavatory?": "סלח לי, האם תוכל בטובך להפנות אותי לשירותים?",
    "A toaster? Would you say it comparers to roasting bread over fire?": "מצנם? היית אומר שזה משתווה לקליית לחם על האש?",
    "The wife told me to 'simply grab some spoons' on the way home, but there so many variations!": "אשתי אמרה לי 'פשוט לקנות כמה כפיות' בדרך הביתה, אבל יש כל כך הרבה סוגים!",
    "five, twenty, thirty, thirty two and... wait how much did you say it was again?": "חמש, עשרים, שלושים, שלושים ושתיים ו... רגע, כמה אמרת שזה שוב?",
    "I recommend two sets. At least! For everyday use and for special occasions. But you'll also want a backup, for when the good china breaks.": "אני ממליץ על שתי מערכות כלים. לפחות! לשימוש יומיומי ולאירועים מיוחדים. אבל תרצה גם גיבוי, למקרה שכלי הפורצלן הטובים יישברו.",
    "Yes, the pantry has changed considerably since I've started taking care of the shopping. The supply is dictated by my demand.": "כן, המזווה השתנה במידה ניכרת מאז שהתחלתי לדאוג לקניות. ההיצע מוכתב על ידי הביקוש שלי.",
    "That's wrong Alice. This once for white, this once for red, this once for sparkling wine and well this is an eggcup... who's been stocking these?": "זה לא נכון אליס. זה מיועד ליין לבן, זה ליין אדום, זה ליין מבעבע וזה... גביע ביצה... מי מילא את המלאי של אלה?",
    "Was I here this morning? Yes well, there were a few more things I needed to get, so I thought why not pop back in and browse for a bit.": "הייתי כאן הבוקר? כן, ובכן, היו עוד כמה דברים שהייתי צריך לקנות, אז חשבתי למה לא לקפוץ שוב ולדפדף קצת.",
    "Oliver used to do all the shopping, but since it has become fashionable for us to shop, I've gladly taken over.": "אוליבר נהג לעשות את כל הקניות, אבל מאז שזה נהיה אופנתי שנעשה קניות, שמחתי לקחת את העניינים לידיים.",
    "Go on, I must inspect this sofa. I'll sit down for a spell, determine if it's snug enough...": "המשך, אני חייב לבחון את הספה הזו. אשב עליה קצת כדי לקבוע אם היא נוחה מספיק...",
    "The finishing looks rather dull does it not? Everything in the catalogue looks so... glossy!": "הגימור נראה די עמום, לא כן? כל דבר בקטלוג נראה כל כך... מבריק!",
    "What? You expect me to carry the cabinet!?": "מה? אתה מצפה ממני לסחוב את הארון!?",
    "He heard it from a friend, who’s brother's wife's sister knows a bloke from newspaper row. It's factual— refrigerator paint's full of lead poison.": "הוא שמע את זה מחבר, שאחותה של אשת אחיו מכירה בחור מרחוב העיתונות. זו עובדה — צבע המקרר מלא ברעל עופרת.",
    "She went and invited the lot, they're to arrive at seven and we're still four walnut chairs short!": "היא הלכה והזמינה את כולם, הם אמורים להגיע בשבע ועדיין חסרים לנו ארבעה כיסאות אגוז!",
    "Put that desk lamp down. You already 'work' too many nights as it is.": "הורד את מנורת השולחן הזו. אתה כבר עובד יותר מדי לילות כפי שזה.",
    "Oh no, look part of the upholstery is torn, you think they'll give me a discount?": "אוי לא, תראה, חלק מהריפוד קרוע, אתה חושב שהם יתנו לי הנחה?",
    "There’s Alice, Abby, Agatha, and Angela - she's new - and, well used to be Anne, rest her soul, so you see I’ll need a bigger bed.": "יש את אליס, אבי, אגתה ואנג'לה - היא חדשה - וטוב, פעם זו הייתה אן, מנוחתה עדן, אז אתה מבין שאצטרך מיטה גדולה יותר.",
    "Yes, well, I know we're lost, we passed that revolting lilac cabinet fifteen minutes ago!": "כן, ובכן, אני יודע שהלכנו לאיבוד, עברנו ליד הארון הלילך הדוחה ההוא לפני רבע שעה!",
    "I do appreciate a change of scenery when shopping, but the way the stores are made to look, it does feels like I've just entered another apartment.": "אני אכן מעריך שינוי באווירה בזמן קניות, אבל האופן שבו החנויות מעוצבות גורם לזה להרגיש כאילו זה עתה נכנסתי לדירה אחרת.",
    "Artisan's Workshop: Violins": "סדנת אומנים: כינורות",
    "Trust me, a pinch of nutmeg, works like a charm...": "סמוך עליי, קורטוב של אגוז מוסקט עושה פלאים...",
    "I took three just to be sure. Now I am feeling rather drowsy...": "לקחתי שלושה רק כדי להיות בטוחה. עכשיו אני מרגישה די מנומנמת...",
    "In my professional opinion the whole side effect business has been steamed up.": "לדעתי המקצועית כל עניין תופעות הלוואי נופח מעבר לכל פרופורציה.",
    "...and then he got up and walked again. I'll ya' that medicine is our saviour, reborn.": "...ואז הוא קם והלך שוב. אני אומר לך, התרופה הזו היא המושיע שלנו, שנולד מחדש.",
    "All these fancy products when a good scrub with soap and hot water will do...am I right dear? ...Dear?": "כל המוצרים המפוארים האלה כששפשוף טוב עם סבון ומים חמים יעשה את העבודה... אני צודק יקירתי? ...יקירתי?",
    "Artisan's Workshop: Billiard Tables": "סדנת אומנים: שולחנות ביליארד",
    "Ruth you must get this lipstick, the shade of red is so daring! I love it.": "רות, את חייבת לקנות את השפתון הזה, גוון האדום שלו כל כך נועז! אני מתה על זה.",
    "So this why Mary's been looking less pale of late! It's the rouge. And here I was speculating that her health had improved.": "אז זו הסיבה שמרי נראית פחות חיוורת לאחרונה! זה הסומק. ואני כבר שיערתי שבריאותה השתפרה.",
    "Eric's depleted another tin! His Handlebar moustache has drooped into a horseshoe.": "אריק חיסל עוד פחית! שפם הכידון שלו צנח לצורת פרסה.",
    "Judy vows the tincture did wonders for her complexion, and the itching's only minor.": "ג'ודי נשבעת שהמרקחת עשתה פלאים לעור הפנים שלה, והגירוד הוא רק קל.",
    "Ingrid dear, I recommend this. With all your woes, it's never too soon to ward off wrinkles.": "אינגריד יקירתי, אני ממליצה על זה. עם כל הצרות שלך, אף פעם לא מוקדם מדי להתגונן מפני קמטים.",
    "Artisan's Workshop Patent List": "רשימת פטנטים של סדנת אומנים",
    "Artisan's Workshop: Cognac": "סדנת אומנים: קוניאק",
    "I expected Rory to be part o' this one...": "ציפיתי שרורי יהיה חלק מזה...",
    "You haven't heard...?": "לא שמעת...?",
    "You know whut'? Them lofty heights they dream of, they'd be nothin' without us to raise em' up.": "אתה יודע מה? הגבהים הנישאים האלה שהם חולמים עליהם, לא היו שווים כלום בלעדינו שירימו אותם.",
    "Just castles in the sky ain't it?": "פשוט מגדלים פורחים באוויר, לא?",
    "You ever consider the odds?": "חשבת פעם על הסיכויים?",
    "Nah, if I wanted better ones I'd enlist.": "לא, אם הייתי רוצה סיכויים טובים יותר הייתי מתגייס.",
    "So, what do you family say about this job?": "אז מה המשפחה שלך אומרת על העבודה הזו?",
    "Blimey, if me Ma' knew I was walking iron she'd climb up here and pull me down by me ears. Poor fool mom thinks I work in the offices.": "בחייך, אם אמא שלי הייתה יודעת שאני הולך על קורות ברזל היא הייתה מטפסת לכאן ומושכת אותי למטה באוזניים. אמא התמימה חושבת שאני עובד במשרדים.",
    "Every time we start with a fresh patch o' dirt, it's impossible to imagine the monster it'll make.": "בכל פעם שאנחנו מתחילים עם פיסת אדמה ריקה, בלתי אפשרי לדמיין איזה מפלצת תצמח שם.",
    "It's gonna change the look of the city forever.": "זה הולך לשנות את מראה העיר לנצח.",
    "Rained last night, better take care not to slip...": "ירד גשם אתמול בלילה, כדאי להיזהר שלא להחליק...",
    "Good weather won't make the fall any shorter.": "מזג אוויר טוב לא יהפוך את הנפילה לקצרה יותר.",
    "Had some rude fella trying to tell me it's the perfect job for fearless workers like us.": "היה איזה בחור חסר נימוס שניסה להגיד לי שזו העבודה המושלמת לעובדים ללא חת כמונו.",
    "Send em' up the scaffold. They'll soon learn those who ain’t afraid don’t make it.": "שלח אותם למעלה על הפיגום. הם ילמדו מהר מאוד שמי שלא מפחד לא שורד.",
    "It’s a matter of perspective ain't it? Down there they look like ants to us, up here we’re ants to them.": "זה עניין של נקודת מבט, לא? שם למטה הם נראים לנו כמו נמלים, וכאן למעלה אנחנו נמלים בשבילם.",
    "By the way they be looking down on us workers you’d think they're the ones whiling away in the skies.": "לפי הדרך שבה הם מסתכלים עלינו העובדים מלמעלה, אפשר לחשוב שהם אלה שמבלים את זמנם בשחקים.",
    "You know what bothers me? We do an excellent job no one mentions it, something goes bad...": "אתה יודע מה מפריע לי? אנחנו עושים עבודה מצוינת ואף אחד לא מזכיר את זה, אבל כשמשהו משתבש...",
    "...they start pointing fingers!": "...הם מתחילים להאשים!",
    "Poor old us huh! Haha... Toss me em' rivets!": "מסכנים שכמונו, הא! חחח... זרוק לי את המסמרות האלה!",
    "Sure thing, still heatin' em up.": "אין בעיה, עדיין מחמם אותן.",
    "Did you make it to Mike's funeral?": "הגעת להלוויה של מייק?",
    "...didn't get the day off.": "...לא קיבלתי יום חופש.",
    "Yeah well... Hey! Look at that scraper down there! I worked that job a few months ago, ha, thought it was the highest ever...": "כן, ובכן... היי! תראה את גורד השחקים ההוא שם למטה! עבדתי בעבודה הזו לפני כמה חודשים, חה, חשבתי שזה הכי גבוה שיש...",
    "Looks like you broke your own record!": "נראה ששברת את השיא של עצמך!",
    "Yeah, almost done. What do you reckon they'll do for the opening?": "כן, כמעט סיימנו. מה אתה חושב שהם יעשו לפתיחה?",
    "Give us the day off. We ain't fancy enough to cut no ribbons, but can't say I'm complaining. Hey, I like my kids!": "יתנו לנו יום חופש. אנחנו לא מספיק מכובדים כדי לגזור סרטים, אבל אני לא יכול להתלונן. היי, אני אוהב את הילדים שלי!",
    "Used to be I could count the family I had working in the sky on one hand. The old man, my uncle, grandfather Joe...": "פעם יכולתי לספור על יד אחת את בני המשפחה שעבדו בשחקים. הזקן, דוד שלי, סבא ג'ו...",
    "I know exactly what you mean. Was my brother who started it for us, but now there's a familiar face walking iron in every corner of the city.": "אני מבין בדיוק למה אתה מבקש. אח שלי התחיל עם זה בשבילנו, אבל עכשיו יש פנים מוכרות שהולכות על ברזל בכל פינה בעיר.",
    "In the end we can only build the best from the materials we're given...": "בסופו של דבר אנחנו יכולים לבנות את הטוב ביותר רק מהחומרים שנותנים לנו...",
    "Yeah, sometimes it sure does feel like they expect us to spin gold out o' straw...": "כן, לפעמים זה באמת מרגיש כאילו הם מצפים מאיתנו להפוך קש לזהב...",
    "A case this clear cut makes you wonder... do the rest just avert their gaze? Scared to be branded snitches, or worse...": "מקרה כל כך ברור גורם לך לתהות... האם השאר פשוט מסיטים את מבטם? מפחדים להיות מתוייגים כמלשינים, או גרוע מכך...",
    "And like the cops I damn near dismissed her. No-one likes folk who stick their noses into other folks' business— I should know— and the picture she painted of the couple next door was made in pretty broad strokes... Her curiosity was piqued when the wife asks the Landlady if she can make a little casket-sized space in the basement.": "וכמו השוטרים, כמעט נפנפתי אותה. אף אחד לא אוהב אנשים שדוחפים את האף לעניינים של אחרים — אני אמור לדעת — והתמונה שהיא ציירה לגבי הזוג מהדלת ליד הייתה די כללית... הסקרנות שלה התעוררה כשהאישה שאלה את בעלת הבית אם היא יכולה לפנות מקום קטן בגודל של ארון קבורה במרתף.",
    "No, not yet. He's still out and about, but his wife's there knitting her mourning cap, lamenting his short life. Nosy neighbour's convinced herself the wife’s a soothsayer of doom— a Cassandra. I tell her if 'you want an exorcism, you're tooting the wrong ringer'!": "לא, עדיין לא. הוא עדיין בחוץ, אבל אשתו שם סורגת את כובע האבל שלה, ומקוננת על חייו הקצרים. השכנה החטטנית שוכנעה שהאישה היא מנבאת חורבן — קסנדרה. אמרתי לה שאם 'את רוצה גירוש שדים, פנית לכתובת הלא נכונה'!",
    "A quick look might not have taken me long, but I fell down the rabbit hole. Took a few twisted arms, but I began to notice our neighbours couldn't help but mention the wife's 'dinners'.": "מבט מהיר אולי לא היה לוקח לי הרבה זמן, אבל נשאבתי למחילה. נדרש קצת לחץ, אבל התחלתי להבחין שהשכנים שלנו לא יכולים שלא להזכיר את 'ארוחות הערב' של האישה.",
    "Ha! Well, I dug around. Not a month ago a hefty life insurance was made for the soon-to-be-late husband— then I discovered our would-be-widow was widowed before. Several times.": "חה! ובכן, חפרתי קצת. לפני פחות מחודש נחתם ביטוח חיים שמן עבור הבעל שעומד ללכת לעולמו בקרוב — ואז גיליתי שהאלמנה-לעתיד שלנו כבר התאלמנה בעבר. מספר פעמים.",
    "Yeah, that’s when the other kind of digging had to start. With the help of a friend I unearth the plain facts from six feet under: there's no arsenic in the ground, but plenty in the remains of our four unlucky suitors.": "כן, ואז היה צריך להתחיל סוג אחר של חפירה. בעזרת חבר שלפתי את העובדות הפשוטות מעומק האדמה: אין ארסן באדמה, אבל יש שפע ממנו בשרידיהם של ארבעת המחזרים בישי המזל שלנו.",
    "Wasn't it you who called your client a ‘nosy neighbour’?": "זה לא היית אתה שקראת ללקוחה שלך 'שכנה חטטנית'?",
    "Someone died?": "מישהו מת?",
    "Let me guess, all that witchiness had you spellbound too?": "תן לי לנחש, כל הכישוף הזה כישף גם אותך?",
    "Witches make lousy cooks?": "מכשפות הן בשלניות גרועות?",
    "Doesn't take witchcraft to predict where this is going.": "לא צריך כישוף כדי לחזות לאן זה הולך.",
    "Allegedly. You know me— I'm an amicable sort.  I try to stay clear of trouble, but it has a tendency to seek me out.": "לכאורה. אתה מכיר אותי — אני טיפוס ידידותי. אני מנסה להתרחק מצרות, אבל יש להן נטייה לחפש אותי.",
    "I was headed to a juice joint, when I see a car tailing a young nurse— bad part of town. The car speeds up and I'm thinking I don't need this one on my mind and push her aside. But, the car turns, drops a briefcase and rushes off. I go to inspect...": "הייתי בדרכי לבר משקאות, כשראיתי מכונית עוקבת אחרי אחות צעירה — אזור מפוקפק של העיר. המכונית מאיצה ואני חושב לעצמי שאני לא צריך את הצרות האלה על הראש ודוחף אותה הצידה. אבל המכונית פונה, שמטה תיק מסמכים וממהרת להסתלק. הלכתי לבדוק...",
    "That's when Detective Hayes emerges from an alley.  Says I've been caught red handed and takes me for a drive uptown. Heard of Donoghue? Big shot surgeon. He's been getting calls...": "באותו רגע הבלש הייז מגיח מסמטה. אומר שנתפסתי על חם ולוקח אותי לנסיעה למרכז העיר. שמעת על דונוהו? מנתח בכיר. הוא קיבל שיחות...",
    "They'll throw 'acid in his kisser' if he don't serve up ten grand by the end of the week. Now the doc's a handsome fellow, but any self-respecting blackmailer should have threatened to burn his hands...": "הם יזרקו לו 'חומצה לפרצוף' אם הוא לא יביא עשרת אלפים דולר עד סוף השבוע. כעת הדוקטור הוא בחור נאה, אבל כל סוחט שמכבד את עצמו היה צריך לאיים לשרוף לו את הידיים...",
    "Scapegoat. I'd wandered into the handover, the real culprit— a no-show. The cops are puzzled, but it's an open case. Hayes should consult the gossip column once in a while, then he'd know the doc's business gone bad. Botched an operation on a starlet.": "שעיר לעזאזל. נקלעתי לנקודת המפגש של העברת הכסף, הפושע האמיתי לא הופיע. השוטרים מבולבלים, אבל התיק פתוח. הייז צריך לעיין במדור הרכילות מדי פעם, אז הוא היה יודע שהעסקים של הדוקטור התדרדרו. הוא פישל בניתוח של כוכבנית.",
    "So, I rip off the Band-Aid for 'em. It's a ruse, Donoghue wants to leverage his alleged victimhood for a spot of good press. My diagnosis is met with denial.": "אז אני פשוט מגלה להם את האמת הכואבת. זו מזימה, דונוהו רוצה למנף את הקורבנות לכאורה שלו כדי לזכות בקצת סיקור חיובי. האבחנה שלי נתקלת בהכחשה.",
    "Word is you've tried your hand at extortion?": "השמועה אומרת שניסית את כוחך בסחיטה באיומים?",
    "Is that so?": "האומנם?",
    "From your humble perspective as a...?": "מנקודת המבט הצנועה שלך בתור...?",
    "And Hayes just let you walk? The end?": "והייז פשוט נתן לך ללכת? זה הסוף?",
    "Like I said, I am an amicable sort— and there's a press conference tomorrow. Donoghue will get to show off his acting chops and I intend to be there. See the show, ask some compelling questions. Of course.": "כמו שאמרתי, אני טיפוס ידידותי — ויש מחר מסיבת עיתונאים. דונוהו יזכה להשוויץ בכישורי המשחק שלו ואני מתכוון להיות שם. לראות את ההצגה, לשאול כמה שאלות נוקבות. כמובן.",
    "You go to church?": "אתה הולך לכנסייה?",
    "Growing up, but I dropped the habit... ...Hall told me he pled insanity. Stood, his back like a lightning rod, the accused, as if preaching to his congregation. You know that right after he killed her he went and delivered a sermon?": "כשהייתי קטן, אבל הפסקתי... הול סיפר לי שהוא טען לאי-שפיות. הנאשם עמד שם, גבו כמו כליא ברק, כאילו הוא נושא דרשה בפני קהל מאמיניו. אתה יודע שמיד אחרי שהוא רצח אותה הוא הלך ונשא דרשה?",
    "God' spaketh to him and said: 'make a sacrifice.' ...You know I thought about skipping the roof today, the new speakeasy downtown looked so inviting. Simmering with the booze tinged troubles of its flock, the promise to drown among them nearly turned me around.": "אלוהים דיבר אליו ואמר: 'הקרב קורבן'... אתה יודע שחשבתי לדלג על הגג היום, הבר המחתרתי החדש במרכז העיר נראה כל כך מזמין. הוא תסס מצרותיהם הספוגות באלכוהול של מאמיניו, וההבטחה להטביע בהם את יגוני כמעט גרמה לי לחזור על עקביי.",
    "...I think we may have crossed paths, back when I was still raking muck. I was downtown for some silly news story when I passed this baby church...": "...אני חושב שאולי דרכינו הצטלבו, בתקופה שעוד עסקתי באיסוף רכילות. הייתי במרכז העיר בשביל איזה סיפור חדשותי טיפשי כשעברתי ליד הכנסייה הקטנה הזו...",
    "A young priest was out front, I think I asked him for a divine light, and we talked. He seemed too polite. A young girl had just gone missing in the area. I was too busy with my notepad to add two and two together.": "כומר צעיר עמד בחוץ, אני חושב שביקשתי ממנו אש, ודיברנו. הוא נראה מנומס מדי. ילדה צעירה בדיוק נעלמה באזור. הייתי עסוק מדי עם פנקס הרשימות שלי מכדי לקשר בין הדברים.",
    "I think a lot of people could have. There were questions when he was ordained, complaints in every parish. But everyone just passed him along, like he was someone else's problem. So did I, in a way. Anyway, they found the poor thing buried at the back of the church.": "אני חושב שהרבה אנשים יכלו. היו שאלות כשהוא הוסמך לכמורה, תלונות בכל קהילה. אבל כולם פשוט העבירו אותו הלאה, כאילו הוא הבעיה של מישהו אחר. כך עשיתי גם אני, במובן מסוים. בכל אופן, הם מצאו את המסכנה קבורה בחלק האחורי של הכנסייה.",
    "Once in a blue moon. You?": "פעם ביובל. אתה?",
    "This is the one who mangled his victim and tossed her in a river?": "זה הבחור שהשחית את גופת הקורבן שלו והשליך אותה לנהר?",
    "Yet here you are.": "ובכל זאת אתה כאן.",
    "Think you could have done something?": "חושב שיכולת לעשות משהו?",
    "For a moment I thought Agatha would know peace. I should know these kinds of secrets always end in the grave.": "לרגע חשבתי שאגתה תמצא מנוחה. הייתי צריך לדעת שסודות מהסוג הזה תמיד מסתיימים בקבר.",
    "We were rivals, in a sense, although she was always better. Had a skilful way of dissecting my work at a glance. While she published truth, I dug up dirt, my lines riddled with lies before the ink could set.": "היינו יריבים במובן מסוים, למרות שהיא תמיד הייתה טובה יותר. הייתה לה דרך מיומנת לנתח את העבודה שלי במבט חטוף. בזמן שהיא פרסמה אמת, אני חפרתי רפש, והשורות שלי היו רצופות שקרים עוד לפני שהדיו הספיקה להתייבש.",
    "When I quit the paper, she ordered us drinks. When I told her I planned to strike out as a private eye, she ordered more. I'd hoped she'd believe I was finally stumbling upon something true. Now here I am, failing to close her case...": "כשהתפטרתי מהעיתון, היא הזמינה לנו משקאות. כשאמרתי לה שאני מתכנן להתחיל לעבוד כבלש פרטי, היא הזמינה עוד. קיוויתי שהיא תאמין שאני סוף סוף נתקל במשהו אמיתי. ועכשיו הנה אני כאן, נכשל בסגירת התיק שלה...",
    "Hearsay from ex-columnists in dingy offices downtown is nothing in court. The only one who had any power to turn the tide is gone...": "שמועות מפי בעלי טורים לשעבר במשרדים מוזנחים במרכז העיר אינן שוות דבר בבית המשפט. היחידה שהיה לה כוח להטות את הכף איננה...",
    "Yeah, they were pretty pictures. They called her beautiful. I was dead on the case, no solid lead to speak of, and she walks in, guilty-eyed, a story to tell. I could see in the set of her jaw, the words of hope waiting to be spoken, but someone had scared her.": "כן, אלה היו תמונות יפות. הם קראו לה יפהפייה. הייתי תקוע בתיק ללא קצה חוט של ממש, והיא נכנסת, עם מבט אשם בעיניים וסיפור לספר. יכולתי לראות לפי תנועת הלסת שלה את מילות התקווה שמחכות להיאמר, אבל מישהו הפחיד אותה.",
    "She was already working for Agatha weeks before the big story broke.  How I wish Agatha had snuffed the piece in it's crib, but, as you know, it was published. And like all of her work it hit true— mobsters dragged under the spotlight.": "היא כבר עבדה עבור אגתה שבועות לפני שהסיפור הגדול התפרסם. כמה הלוואי שאגתה הייתה גונזת את הכתבה עוד בחיתוליה, אבל, כפי שאתה יודע, היא פורסמה. וכמו כל העבודות שלה, היא פגעה בול — המאפיונרים נגררו אל אור הזרקורים.",
    "But you know who did it...": "אבל אתה יודע מי עשה את זה...",
    "The secretary? I saw her pretty little face in the papers.": "המזכירה? ראיתי את פניה הקטנות והיפות בעיתונים.",
    "She must have be traumatized...": "היא בטח הייתה בטראומה...",
    "She’s dressed in yellow, stands out in the dismal place like a flower growing up through concrete. There’s a resolve on her face, she harbours no illusions, innocent or not, her judgment is made. So, I forego preamble, and ask did she stab the counsellor.": "היא לבושה בצהוב, בולטת במקום העגום הזה כמו פרח הצומח מתוך הבטון. יש נחישות על פניה, היא אינה משלה את עצמה, אשמה או לא, גזר דינה נקבע. אז אני מוותר על ההקדמות, ושואל אם היא דקרה את היועץ.",
    "The popular story is she did it for the money. They were seen in the club, him flirting, her dancing. Some say they left together, others say he followed, she led. The next time they saw him he was dead, bleeding out in a side-street.": "הגרסה הנפוצה היא שהיא עשתה את זה בשביל הכסף. ראו אותם במועדון, הוא מפלרטט, היא רוקדת. יש האומרים שהם עזבו יחד, אחרים אומרים שהוא עקב אחריה, והיא הובילה. בפעם הבאה שראו אותו הוא היה מת, שותת דם בסמטה צדדית.",
    "Rowse grew sloppy. He likely poisoned his wife over months, maybe years, but his rival wants him to pay up, fast. First he sends a box of chocolates to the house. But the sister-in-law receives them and gets peckish. That night she falls ill.": "רוז נהיה רשלן. סביר להניח שהוא הרעיל את אשתו במשך חודשים, אולי שנים, אבל היריב שלו רוצה שהוא ישלם, ומהר. ראשית הוא שולח קופסת שוקולדים לבית. אבל הגיסה מקבלת אותם ומקבלת תיאבון. באותו לילה היא נופלת למשכב.",
    "They both survive?": "שניהם שורדים?",
    "Plan B is the invitation to yellow tea and cake I mentioned. Rival barely accepts. Then it was \"'scuse fingers\" as Rowse hands him a slice of death. The attending physician is the same one that attended Rowse's late wife and he gives me a call.": "תוכנית ב' היא ההזמנה לתה צהוב ועוגה שהזכרתי. היריב כמעט ולא מסכים. ואז זה היה \"סליחה על האצבעות\" כשרוז מגיש לו פרוסה של מוות. הרופא המטפל הוא אותו אחד שטיפל באשתו המנוחה של רוז והוא מרים אליי טלפון.",
    "When I delivered the news that her husband was faithful, do you know what he did? Spat at my feet, accused me of being a con.": "כשמסרתי את הבשורה שבעלה נאמן, אתה יודע מה הוא עשה? ירק לרגליי, והאשים אותי שאני נוכל.",
    "The more truth I uncover the lighter my pockets seem to get.": "ככל שאני חושף יותר אמת, כך הכיסים שלי נהיים קלים יותר.",
    "You sell a version of the truth.": "אתה מוכר גרסה של האמת.",
    "You contradicted a reality she was convinced of.": "סתרת מציאות שהיא הייתה משוכנעת בה.",
    "I make a living.": "אני מתפרנס.",
    "What other kind is there?": "איזה סוג אחר יש?",
    "The empirical, the one many don't wish to hear. She gave me a conclusion and I was to evidence it. A strange woman accosted her at the mall. Tried to steal her ruby earrings, calling her the thief, and when she told her husband, he tried to downplay it all.": "האמפירי, זה שרבים אינם רוצים לשמוע. היא נתנה לי מסקנה והייתי צריך להוכיח אותה. אישה זרה פנתה אליה במרכז הקניות. ניסתה לגנוב את עגילי הרובין שלה, קראה לה גנבת, וכשהיא סיפרה לבעלה, הוא ניסה להמעיט בערך העניין.",
    "Likely she knew on some level, but chose to believe otherwise.": "סביר להניח שהיא ידעה ברמה מסוימת, אך בחרה להאמין אחרת.",
    "A week later the earrings are gone from her dresser. Her conclusion: Her husband took the earrings for his jilted lover. As for mine: I won't deny one can make a living off the dead...but the mortician’s wage hardly explains his wealth.": "שבוע לאחר מכן העגילים נעלמו משידת המגירות שלה. המסקנה שלה: בעלה לקח את העגילים עבור המאהבת הדחויה שלו. באשר לשלי: לא אכחיש שאפשר להתפרנס מהמתים... אבל השכר של הקברן בקושי מסביר את עושרו.",
    "Another private eye?": "עוד בלש פרטי?",
    "Ignorance was prudent to her lifestyle. Anyway, I stakeout the coroner's office, trying not to doze off until I realize I'm not the only sorry ass wasting away in the sun— and if anything the wife has a knack for describing people, because who I'm seeing is the alleged assailant from the mall— a young woman.": "הבורות הייתה נבונה עבור אורח חייה. בכל אופן, תצפתתי על משרד חוקר מקרי המוות, מנסה לא להירדם עד שהבנתי שאני לא המסכן היחיד שמבזבז את הזמן בשמש — ולחלופין, לאשתו יש כישרון לתיאור אנשים, כי מי שאני רואה זו התוקפת לכאורה ממרכז הקניות — אישה צעירה.",
    "She doesn't spot me. I wait 'til she leaves to do some digging, and there's plenty to be suspicious of. Seems most of the dead died without family.": "היא לא מבחינה בי. חיכיתי שהיא תעזוב כדי לחפור קצת, ויש הרבה סיבות לחשוד. נראה שרוב המתים מתו ללא משפחה.",
    "He liquidates their assets.": "הוא מנזיל את הנכסים שלהם.",
    "And keeps their belongings.": "ושומר את החפצים שלהם.",
    "Like a pair of ruby earrings.": "כמו זוג עגילי רובין.",
    "What he doesn't know is the dame he stripped them from had a quick-witted niece, who I'm thinking of introducing to his lovely lady wife.": "מה שהוא לא יודע זה שלגברת שהוא הפשיט ממנה את העגילים הייתה אחיינית שנונה, שאני חושב להציג בפני אשתו המקסימה.",
    "Artisan's Workshop: Toys": "סדנת אומנים: צעצועים",
    "Toys": "צעצועים",
    "Donny is getting impatient for elevators.": "לדוני נגמרת הסבלנות למעליות.",
    "Our elevator plants are cutting-edge. Time to get production off the ground!": "מפעלי המעליות שלנו הם חזית הטכנולוגיה. הגיע הזמן להתניע את הייצור!",
    "Donald J. Bader": "דונלד ג'יי. ביידר",
    "An investor vaunts the commercial promise of the latest tech.": "משקיע מהלל את ההבטחה המסחרית של הטכנולוגיה העדכנית ביותר.",
    "First Elevators, now Metal Frames! Skyscrapers are key to this city’s otherwise worthless future— sky’s the limit I'd say— a business venture ripe for the both of us!": "תחילה מעליות, עכשיו שלדות מתכת! גורדי שחקים הם המפתח לעתידה חסר הערך אחרת של עיר זו — השמים הם הגבול, הייתי אומר — מיזם עסקי בשל עבור שנינו!",
    "Sorry, you've probably heard of me— Donald Bader, call me Donny. They say don't brag, but who has time to be coy? I'm the best Investor this city has, apart from you of course— my guru!": "סליחה, כנראה שמעת עליי — דונלד ביידר, קרא לי דוני. אומרים לא להתרברב, אבל למי יש זמן להצטנע? אני המשקיע הכי טוב שיש לעיר הזו, חוץ ממך כמובן — הגורו שלי!",
    "Mr. Bader is eager to introduce himself.": "מר ביידר להוט להציג את עצמו.",
    "Donny wants to build towers with you.": "דוני רוצה לבנות איתך מגדלים.",
    "We have the elevators, so let's elevate our ambitions— sky's empty, so we fill it. We'll be kings in no time, looking over our beautiful kingdoms.": "יש לנו את המעליות, אז בוא נרים את השאיפות שלנו — השמים ריקים, אז נמלא אותם. נהיה מלכים תוך זמן קצר, ונשקיף על הממלכות היפות שלנו.",
    "Donny is just getting started.": "דוני רק מתחיל.",
    "So proud we laid the first stone. Keep it up— plenty of real estate up there! My rivals are trying to keep pace, which is so funny to me, because they are all failures.": "כל כך גאה שהנחנו את האבן הראשונה. תמשיך כך — יש הרבה נדל\"ן שם למעלה! היריבים שלי מנסים לעמוד בקצב, וזה כל כך מצחיק אותי, כי כולם כישלונות.",
    "Donny values typewriters more than employees.": "דוני מעריך מכונות כתיבה יותר מאשר עובדים.",
    "Nifty gizmos these typewriters— save time and money, both of which I need. You know, my lawyer's handwriting was unreadable, but now I can get typist monkeys punching all that profit in.": "מכשירים שימושיים מכונות הכתיבה האלה — חוסכים זמן וכסף, ושניהם דרושים לי. אתה יודע, כתב היד של עורך הדין שלי היה בלתי קריא, אבל עכשיו אני יכול להביא קופים קלדנים שיקלידו את כל הרווחים האלה פנימה.",
    "Behold, The Galeria Baderette! Now, sacred halls have to have product worthy of worship. Get the suckers leaving with their arms full.": "ראה, גלריית ביידרט! כעת, היכלות קדושים חייבים להכיל מוצרים הראויים לסגידה. דאג שהפראיירים ייצאו בידיים מלאות.",
    "Donny salivates over the prospect of fully-stocked shopping arcades.": "דוני מרייר על הסיכוי לפסז'י קניות מלאים בסחורה.",
    "A Toaster! The perfect trap. Pipe toasty smells out and put the suckers in mind of breakfasts surrounded by family, childhood camping trips...all weak spots we'll target.": "מצנם! המלכודת המושלמת. הזרם ריחות של לחם קלוי החוצה והזכר לפראיירים ארוחות בוקר מוקפות במשפחה, טיולי קמפינג מהילדות... כל נקודות התורפה בהן נמקד את המטרה.",
    "Donny dreams of eager shoppers buying toasters.": "דוני חולם על קונים נלהבים שקונים מצנמים.",
    "Toasters are selling fast! Imagine the profits if we had more types of products in our stores!": "המצנמים נמכרים מהר! תאר לעצמך את הרווחים אילו היו לנו סוגים נוספים של מוצרים בחנויות שלנו!",
    "Donny sees the potential in other shopping arcade goods.": "דוני רואה את הפוטנציאל בסחורות אחרות של פסז' הקניות.",
    "Donny shares an odd warning letter he received.": "דוני משתף במכתב אזהרה מוזר שקיבל.",
    "Found this note on my way back from brunch— really bizarre. An artistic sort of a threat— get this all the time. Here, go ahead, if you want a laugh!": "מצאתי את הפתק הזה בדרכי חזרה מארוחת הבוקר המאוחרת — ממש מוזר. איום מסוג אמנותי — מקבל כאלה כל הזמן. הנה, קח, אם בא לך לצחוק!",
    "<font size=\"21\"><b>Take Heed!</b><br /><br /><i>“Pride goeth before destruction, and a haughty spirit before a fall.”</i>Proverbs 16:18-19<br /><br /><b>Dear Mr. Bader, I apologise for the dramatic imagery and citation, but I really feel compelled to caution you on your present disregard for the health and safety of employees at your construction sites. In addition, I have reason to believe you are bending important building regulations in order to rush your constructions to completion. Please be more responsible! Yours, a concerned citizen.</b></font>": "<font size=\"21\"><b>שים לב!</b><br /><br /><i>“לפני שבר גאון, ולפני כשלון גובה רוח.”</i>משלי טז:יח-יט<br /><br /><b>מר ביידר היקר, אני מתנצל על הדימוי הדרמטי והציטוט, אך אני באמת מרגיש מחויב להזהיר אותך לגבי הזלזול הנוכחי שלך בבריאותם ובבטיחותם של העובדים באתרי הבנייה שלך. בנוסף, יש לי סיבה להאמין שאתה מכופף תקנות בנייה חשובות על מנת לזרז את השלמת הבניות שלך. אנא היה אחראי יותר! שלך, אזרח מודאג.</b></font>",
    "Donny doesn't seem too concerned.": "דוני לא נראה מוטרד מדי.",
    "Someone likes a crystal ball— If I wanted foreboding notes, I'd go see my cardiologist— Only no hopers hate change. Can we expect you up on the skydeck for lunch?": "מישהו אוהב כדורי בדולח — אם הייתי רוצה פתקים מבשרי רעות, הייתי הולך לראות את הקרדיולוג שלי — רק חסרי תקווה שונאים שינוי. נוכל לצפות לראות אותך לארוחת צהריים בסיפון השמיים?",
    "Skyline Tower: Glazing": "מגדל קו הרקיע: זיגוג",
    "Market Research: The Lab": "מחקר שוק: המעבדה",
    "Donny is eager to expand your shopping catalogue.": "דוני להוט להרחיב את קטלוג הקניות שלך.",
    "Time to brew up tomorrow's trends! I’ll uncork the bubbles! This catalogue will be bursting in no time, and with a fat profit! I take it you're not turning down the co-opportunity of a lifetime?": "הגיע הזמן לרקוח את הטרנדים של מחר! אני אחלוץ את הפקקים! הקטלוג הזה עומד להתפוצץ תוך זמן קצר, ועם רווח שמן! אני מניח שאינך מסרב לשותפות החד-פעמית של החיים?",
    "Knew you’d be onboard, oh wise one! To kick off we have to invest in R & D – a bore-chore – but we delegate. Once we've built them their lab we can get on to the real stuff.": "ידעתי שתהיה בעניין, הו חכם באדם! כדי להתחיל עלינו להשקיע במו\"פ — מטלה משעממת — אבל אנחנו מאצילים סמכויות. ברגע שנבנה להם את המעבדה שלהם נוכל לעבור לדבר האמיתי.",
    "Scared? Happens to some...I'd better find another industrialist to idolise.": "מפחד? זה קורה לחלק... מוטב שאמצא תעשיין אחר להעריץ.",
    "Donny wants a market research lab built.": "דוני רוצה שתיבנה מעבדת מחקר שוק.",
    "Donny is surprised his idol turned him down.": "דוני מופתע מכך שהאליל שלו סירב לו.",
    "Obsessed with the Shopping Arcade’s promise of profit, Donald Bader tasks you with commandeering office space amid the existing Engineer apartments for a so-called ‘market research lab‘. He wants to develop new patents there — or as he calls them, the needs of tomorrow!": "כשהוא אובססיבי להבטחת הרווח של פסז' הקניות, דונלד ביידר מטיל עליך להשתלט על שטח משרדי בין דירות המהנדסים הקיימות עבור מה שקרוי 'מעבדת מחקר שוק'. הוא רוצה לפתח שם פטנטים חדשים — או כפי שהוא מכנה אותם, צורכי המחר!",
    "Reach the following amount of new skyscrapers in [Area Area([Conditions QuestArea]) CityName]:<br/>[Conditions QuestCondition CurrentAmount]/[Conditions QuestCondition Amount] [AssetData([Conditions QuestCondition Context]) Text]": "הגע לכמות הבאה של גורדי שחקים חדשים ב-[Area Area([Conditions QuestArea]) CityName]:<br/>[Conditions QuestCondition CurrentAmount]/[Conditions QuestCondition Amount] [AssetData([Conditions QuestCondition Context]) Text]",
    "Place a <b>Gazebo Plaza</b> next to the Engineer Skyscraper in [Area Area([Conditions QuestArea]) CityName]": "מקם <b>כיכר גזיבו</b> ליד גורד השחקים של המהנדסים ב-[Area Area([Conditions QuestArea]) CityName]",
    "You can upgrade an Engineer residence into a skyscraper from its menu once you've fulfilled all the Engineer's needs.": "תוכל לשדרג בית מגורים של מהנדסים לגורד שחקים מתוך התפריט שלו ברגע שתספק את כל צורכי המהנדס.",
    "The Gazebo Plaza is an ornament belonging to the Luxury Park category. Open the Classic Tab of the Beautification Menu to find it. Donald Bader’s tastes are highly specific and he will accept no other ornament.": "כיכר הגזיבו היא קישוט השייך לקטגוריית פארק היוקרה. פתח את הלשונית הקלאסית בתפריט הקישוטים כדי למצוא אותו. הטעמים של דונלד ביידר הם מאוד ספציפיים והוא לא יקבל שום קישוט אחר.",
    "Donny expects offices to look fancier.": "דוני מצפה שהמשרדים ייראו מפוארים יותר.",
    "Boring! We’re shaping the future of consume, here! The outside’s drab— has to show off what happens inside. People like gardens, right? Slap a gazebo next to it!": "משעמם! אנחנו מעצבים פה את עתיד הצריכה! מבחוץ זה אפרורי — זה חייב להציג לראווה את מה שקורה בפנים. אנשים אוהבים גנים, נכון? שים גזיבו ליד זה!",
    "Not too shabby! Should be a breeze now for Miss Jenny, my house help here, to get to work. We do the big picture, she'll do the nitty-gritty.": "לא רע בכלל! זה אמור להיות משחק ילדים כעת עבור מיס ג'ני, עוזרת הבית שלי כאן, להגיע לעבודה. אנחנו דואגים לתמונה הגדולה, והיא תדאג לפרטים הקטנים.",
    "Donny off-handedly introduces his lead engineer.": "דוני מציג כבדרך אגב את המהנדסת הראשית שלו.",
    "Lose Island": "איבוד האי",
    "All Department Stores": "כל חנויות הכלבו",
    "All Furniture Stores": "כל חנויות הרהיטים",
    "All Drug Stores": "כל בתי המרקחת",
    "Fridge Trigger": "טריגר מקרר",
    "Have a member's club next to a pub. The proximity of the classes may lead to new innovations for the dining room!": "הצב מועדון חברים ליד פאב. הקרבה של המעמדות עשויה להוביל לחידושים חדשים עבור חדר האוכל!",
    "Have at least 5 Investor skyscrapers of level 3 height. Expanding the amount of habitable square meters may create new and more efficient ways to keep them clean.": "החזק לפחות 5 גורדי שחקים של משקיעים בגובה דרגה 3. הרחבת השטח הראוי למגורים עשויה ליצור דרכים חדשות ויעילות יותר לשמור עליהם נקיים.",
    "Invent and equip \"The Magnificone\" Ice Cream Maker in a town hall in the Old World. The concept of chilling food could be a study for your Engineers.": "המצא והצטייד במכונת הגלידה \"דה מגניפיקון\" בבית עירייה בעולם הישן. הרעיון של קירור מזון יכול להוות מחקר עבור המהנדסים שלך.",
    "Place a Department Store next to your Scholar residences. The particularly inspired customers could lead to new fashionable trends and patents...": "מקם חנות כלבו ליד בתי המגורים של המלומדים שלך. הלקוחות מלאי ההשראה במיוחד עשויים להוביל למגמות אופנתיות ופטנטים חדשים...",
    "Complete the Eastern Jungle exhibition in one of your Old World zoos. Visitors inspired by its exoticism may want to bring an oriental touch to their homes.": "השלם את תערוכת הג'ונגל המזרחי באחד מגני החיות שלך בעולם הישן. מבקרים שקיבלו השראה מהאקזוטיות שלה עשויים לרצות להביא מגע מזרחי לבתיהם.",
    "Have a Shopping Arcade providing Banker's Lamps with 100% productivity. Having so many lamps, you'll need at least as many desks...": "החזק בפסז' קניות המספק מנורות בנקאים עם 100% פרודוקטיביות. כשיש כל כך הרבה מנורות, תצטרך לפחות אותו מספר של שולחנות כתיבה...",
    "Give access to more bear fur and feathers to any of your Old-World islands. Such materials could provide inspiration for your tailors...": "ספק גישה ליותר פרוות דובים ונוצות לכל אחד מהאיים שלך בעולם הישן. חומרים כאלה יכולים לספק השראה לחייטים שלך...",
    "Build 2 additional radio towers. The development of a radio network may lead to new habits, and new needs.": "בנה 2 מגדלי רדיו נוספים. פיתוח רשת רדיו עשוי להוביל להרגלים חדשים ולצרכים חדשים.",
    "Have 40 investor skyscrapers of the highest level. If the view of the city is tainted, the investors may come up with some solutions...": "החזק ב-40 גורדי שחקים של משקיעים מהדרגה הגבוהה ביותר. אם נוף העיר נפגע, המשקיעים עשויים להעלות כמה פתרונות...",
    "Have a Variety Theatre next to an Investor skyscraper of the highest Level. Wealthy ladies may develop new habits when going out for the night.": "הצב תיאטרון וראייטי ליד גורד שחקים של משקיעים מהדרגה הגבוהה ביותר. גבירות עשירות עשויות לפתח הרגלים חדשים ביציאה לבילוי לילי.",
    "Complete the Icebound exhibition in one of your Old World museums. Cold environments in your most frequented places could lead to new needs for skin care.": "השלם את תערוכת הקרח באחד המוזיאונים שלך בעולם הישן. סביבות קרות במקומות המתויירים ביותר שלך עשויות להוביל לצרכים חדשים לטיפוח העור.",
    "Have a hibiscus farm next to a beekeeper. The two experts may mix their products, creating unique results.": "הצב חוות היביסקוס ליד מגדל דבורים. שני המומחים עשויים לערבב את המוצרים שלהם, וליצור תוצאות ייחודיות.",
    "Once you've provided your citizens with toasters and accepted the hunt for new patents from Donald, you should attempt to fulfill his demands.": "לאחר שסיפקת לאזרחיך מצנמים והסכמת למצוד אחר פטנטים חדשים מדונלד, עליך לנסות לענות על דרישותיו.",
    "Make sure you provide your citizens with Banker's Lamps and have an Engineer skyscraper nearby; then Donald should provide you with some new tasks.": "ודא שאתה מספק לאזרחיך מנורות בנקאים ושיש גורד שחקים של מהנדסים בקרבת מקום; אז דונלד אמור לספק לך כמה משימות חדשות.",
    "Ensure that your citizens have access to Toothpaste, and that you have an Engineer skyscraper nearby. Then Donald will certainly have some new tasks for you.": "ודא שלאזרחיך יש גישה למשחת שיניים, ושיש לך גורד שחקים של מהנדסים בקרבת מקום. אז לדונלד בהחלט יהיו כמה משימות חדשות עבורך.",
    "Patent Unlock": "פתיחת פטנט",
    "New department store patent unlocked!": "פטנט חנות כלבו חדש נפתח!",
    "New furniture store patent unlocked!": "פטנט חנות רהיטים חדש נפתח!",
    "New drug store patent unlocked!": "פטנט בית מרקחת חדש נפתח!",
    "The investor says crockery can now be sold in shopping arcades.": "המשקיע אומר שכעת ניתן למכור כלי אוכל בפסז'י קניות.",
    "The Investor says vacuum cleaners can now be sold in shopping arcades.": "המשקיע אומר שכעת ניתן למכור שואבי אבק בפסז'י קניות.",
    "The Investor says refrigerators can now be sold in Shopping Arcades.": "המשקיע אומר שכעת ניתן למכור מקררים בפסז'י קניות.",
    "The investor says briefcases can now be sold in shopping arcades.": "המשקיע אומר שכעת ניתן למכור תיקי מסמכים בפסז'י קניות.",
    "The investor says vanity screens can now be sold in shopping arcades.": "המשקיע אומר שכעת ניתן למכור פרגודים בפסז'י קניות.",
    "The investor says the writing desk can now be sold in shopping arcades.": "המשקיע אומר שכעת ניתן למכור שולחנות כתיבה בפסז'י קניות.",
    "The investor says the four-poster bed can now be sold in shopping arcades.": "המשקיע אומר שכעת ניתן למכור מיטות אפריון בפסז'י קניות.",
    "The investor says lounge seating can now be sold in shopping arcades.": "המשקיע אומר שכעת ניתן למכור פינות ישיבה בפסז'י קניות.",
    "The investor says detergent can now be sold in shopping arcades.": "המשקיע אומר שכעת ניתן למכור חומרי ניקוי בפסז'י קניות.",
    "The investor says lipstick can now be sold in shopping arcades.": "המשקיע אומר שכעת ניתן למכור שפתונים בפסז'י קניות.",
    "The investor says face cream can now be sold in shopping arcades.": "המשקיע אומר שכעת ניתן למכור קרם פנים בפסז'י קניות.",
    "The investor says pomade can now be sold in shopping arcades.": "המשקיע אומר שכעת ניתן למכור משחת שיער בפסז'י קניות.",
    "Who am I to deny the working class? They’ve seen us eating off china at the club, and now they want the same. Let them! — all they have to do is pay for it!": "מי אני שאמנע זאת ממעמד הפועלים? הם ראו אותנו אוכלים מכלי פורצלן במועדון, ועכשיו הם רוצים את אותו הדבר. שיהיה להם! — כל מה שהם צריכים לעשות זה לשלם על זה!",
    "Splendid! Cleaning all these floors is hard work, I should know, I pay the bill. With this machine I can slash the staff!": "נהדר! ניקוי כל הקומות האלה זו עבודה קשה, אני יודע, אני משלם את החשבון. עם המכונה הזו אני יכול לקצץ בצוות העובדים!",
    "Engineers, a restless bunch! Even on an ice cream break, they think up the next thing - And I do prefer my scotch on the rocks and my meat unspoiled.": "מהנדסים, חבורה חסרת מנוח! אפילו בהפסקת גלידה הם חושבים על הדבר הבא - ואני אכן מעדיף את הוויסקי שלי עם קרח ואת הבשר שלי לא מקולקל.",
    "Yes, Jr. has a classmate from Enbesa, young chap, jaunts about with a sleek leather bag. Passing the shopping arcades, he’s practically a walking advertisment!": "כן, לג'וניור יש בן כיתה מאנבסה, בחור צעיר, שמסתובב עם תיק עור אלגנטי. כשהוא עובר ליד פסז'י הקניות, הוא פשוט פרסומת מהלכת!",
    "I’ve heard the oriental exhibition at the zoo is a hit. haven't been myself but, a vanity screen with a thematic print might be the perfect souvenir.": "שמעתי שתערוכת המזרח בגן החיות היא להיט. לא הייתי שם בעצמי אבל, פרגוד עם הדפס תמטי עשוי להיות המזכרת המושלמת.",
    "Clearly a quality lamp needs a quality writing desk to stand on, however else will our customers work through the night to afford both. Rather illuminating wouldn’t you agree?": "ברור שמנורה איכותית צריכה שולחן כתיבה איכותי לעמוד עליו, אחרת איך עוד הלקוחות שלנו יעבדו לאורך כל הלילה כדי להרשות לעצמם את שניהם. מאיר עיניים למדי, לא תסכים?",
    "Yes, maybe with quality bedding – something warm and soft from up North, like eiderdowns – people would require fewer hours of rest and could go shopping!": "כן, אולי עם מצעים איכותיים — משהו חם ורך מהצפון, כמו פוך נוצות — אנשים יצטרכו פחות שעות מנוחה ויוכלו לצאת לקניות!",
    "People enjoy listening to the wireless together? Well surely, we can provide comfort with the appropriate seating. They’ll have to work to afford the leisure time of course...": "אנשים נהנים להאזין לרדיו יחד? ובכן בוודאי, נוכל לספק להם נוחות עם מקומות הישיבה המתאימים. הם יצטרכו לעבוד כדי להרשות לעצמם את שעות הפנאי כמובן...",
    "In meetings with Avery I like to gaze out of the window – contingencies are a bore – but there was this nasty spot on the glass obscuring my view. I can’t have that!": "בפגישות עם אייברי אני אוהב להביט מהחלון — מקרי חירום הם מטרד — אבל היה הכתם המגעיל הזה על הזכוכית שהסתיר לי את הנוף. אני לא יכול להרשות את זה!",
    "The wife’s taken a liking to the cabaret – beats me – but feels that among the glitz she can’t shine. I tell her, 'darling wear something bold, something the others can’t afford.'": "אשתי התחילה לחבב את הקברט — אין לי מושג למה — אבל מרגישה שבין כל הזוהר היא לא יכולה לבלוט. אמרתי לה, 'יקירתי, תלבשי משהו נועז, משהו שאחרים אינם יכולים להרשות לעצמם'.",
    "The museum’s new exhibit is rather ill received by my peers – the icy rooms you see, make their skin turn red! Face cream, with some whitener, should appease their antiquated standards!": "התערוכה החדשה של המוזיאון מתקבלת בצורה די גרועה על ידי חבריי — החדרים הקפואים, אתה מבין, גורמים לעור שלהם להאדים! קרם פנים, עם קצת חומר הלבנה, אמור להשקיט את הסטנדרטים המיושנים שלהם!",
    "The wind up here makes having a tipple a chore. We need something to set the hair. Jr. spoke of a wax-based hibiscus hair mask from Enbesa, let’s brand it for the regional market.": "הרוח כאן למעלה הופכת כל כוסית למטרד. אנחנו צריכים משהו שיקבע את השיער. ג'וניור דיבר על מסכת שיער מבוססת שעווה והיביסקוס מאנבסה, בוא נמתג אותה עבור השוק המקומי.",
    "Toaster Supply": "אספקת מצנמים",
    "Some patent unlock conditions have changed": "כמה מתנאי פתיחת הפטנטים השתנו",
    "Donny asks you to relocate the market research lab.": "דוני מבקש ממך להעתיק את מיקום מעבדת מחקר השוק.",
    "The whole darn island? Tough business! Well, this patent is dead. We'll have to relocate, if we want Miss Jenny to get working for us.": "כל האי הארור הזה? עסק קשה! ובכן, הפטנט הזה מת. נצטרך להעתיק את המיקום, אם אנחנו רוצים שמיס ג'ני תתחיל לעבוד בשבילנו.",
    "Donny says a new engineer skyscraper is needed to continue the research.": "דוני אומר שנדרש גורד שחקים חדש של מהנדסים כדי להמשיך במחקר.",
    "Keep in mind, without a marketing office our partnership will come to an end!": "קח בחשבון שללא משרד שיווק, השותפות שלנו תגיע לסיומה!",
    "Oh, so you’ve decided to outsource to another island? A shame.": "הו, אז החלטת להעביר את העבודה למיקור חוץ באי אחר? חבל.",
    "No lab, no research. But don't wait, find some new real estate and build Miss Jenny a place to busy herself.": "אין מעבדה, אין מחקר. אבל אל תמתין, מצא נדל\"ן חדש ובנה למיס ג'ני מקום להעסיק את עצמה בו.",
    "All Engineer Skyscrapers": "כל גורדי השחקים של המהנדסים",
    "Lose Lab": "איבוד המעבדה",
    "Donny says check your shopping catalogue.": "דוני אומר לבדוק את קטלוג הקניות שלך.",
    "You know, your catalogue is pretty skinny... It's ok, Donny has some ideas to fatten it up— I already put notes in the margins.": "אתה יודע, הקטלוג שלך די דליל... זה בסדר, לדוני יש כמה רעיונות להשמין אותו — כבר רשמתי הערות בשוליים.",
    "Miss Jenny": "מיס ג'ני",
    "Theodora Thistlethorpe (a.k.a Miss Jenny)": "תיאודורה ת'יסלת'ורפ (הידועה כמיס ג'ני)",
    "William Brokeman": "ויליאם ברוקמן",
    "Yes, it is in the Beaux-Arts style, but at the upper levels the decor is less pronounced. A perfect marriage of aesthetics and pragmatism.": "כן, זה בסגנון הבוז-אר, אבל ברמות הגבוהות יותר העיטור פחות בולט. שילוב מושלם של אסתטיקה ופרגמטיות.",
    "Everyone's praising it, calling it a grand success, but I had a friend working top side and he got stories to tell that make you shudder...": "כולם משבחים את זה, קוראים לזה הצלחה גדולה, אבל היה לי חבר שעבד למעלה ויש לו סיפורים לספר שיגרמו לך להצטמרר...",
    "...and I said, no way in hell could they build such a behemoth so fast, and now they're done even sooner! I sure hope it holds up.": "...ואמרתי שאין שום סיכוי בעולם שהם יוכלו לבנות מפלצת כזו כל כך מהר, ועכשיו הם סיימו אפילו מוקדם יותר! אני מאוד מקווה שזה יחזיק מעמד.",
    "I for one have a bad feeling about the Skyline Tower. They neglected to skip the 13th floor.": "לי באופן אישי יש תחושה רעה לגבי מגדל קו הרקיע. הם שכחו לדלג על הקומה ה-13.",
    "Whatever the architect designs next, it will always have to live up to that there Skyline Tower.": "מה שהאדריכל יעצב בהמשך, זה תמיד יצטרך לעמוד בסטנדרט של מגדל קו הרקיע ההוא.",
    "Donny dreams of eager shoppers buying toasters.": "דוני חולם על קונים נלהבים שקונים מצנמים.",
    "Toasters are selling fast! Imagine the profits if we had more types of products in our stores!": "המצנמים נמכרים מהר! תאר לעצמך את הרווחים אילו היו לנו סוגים נוספים של מוצרים בחנויות שלנו!",
    "Donny sees the potential in other shopping arcade goods.": "דוני רואה את הפוטנציאל בסחורות אחרות של פסז' הקניות.",
    "Donny shares an odd warning letter he received.": "דוני משתף במכתב אזהרה מוזר שקיבל.",
    "Found this note on my way back from brunch— really bizarre. An artistic sort of a threat— get this all the time. Here, go ahead, if you want a laugh!": "מצאתי את הפתק הזה בדרכי חזרה מארוחת הבוקר המאוחרת — ממש מוזר. איום מסוג אמנותי — מקבל כאלה כל הזמן. הנה, קח, אם בא לך לצחוק!",
    "<font size=\"21\"><b>Take Heed!</b><br /><br /><i>“Pride goeth before destruction, and a haughty spirit before a fall.”</i>Proverbs 16:18-19<br /><br /><b>Dear Mr. Bader, I apologise for the dramatic imagery and citation, but I really feel compelled to caution you on your present disregard for the health and safety of employees at your construction sites. In addition, I have reason to believe you are bending important building regulations in order to rush your constructions to completion. Please be more responsible! Yours, a concerned citizen.</b></font>": "<font size=\"21\"><b>שים לב!</b><br /><br /><i>“לפני שבר גאון, ולפני כשלון גובה רוח.”</i>משלי טז:יח-יט<br /><br /><b>מר ביידר היקר, אני מתנצל על הדימוי הדרמטי והציטוט, אך אני באמת מרגיש מחויב להזהיר אותך לגבי הזלזול הנוכחי שלך בבריאותם ובבטיחותם של העובדים באתרי הבנייה שלך. בנוסף, יש לי סיבה להאמין שאתה מכופף תקנות בנייה חשובות על מנת לזרז את השלמת הבניות שלך. אנא היה אחראי יותר! שלך, אזרח מודאג.</b></font>",
    "Donny doesn't seem too concerned.": "דוני לא נראה מוטרד מדי.",
    "Someone likes a crystal ball— If I wanted foreboding notes, I'd go see my cardiologist— Only no hopers hate change. Can we expect you up on the skydeck for lunch?": "מישהו אוהב כדורי בדולח — אם הייתי רוצה פתקים מבשרי רעות, הייתי הולך לראות את הקרדיולוג שלי — רק חסרי תקווה שונאים שינוי. נוכל לצפות לראות אותך לארוחת צהריים בסיפון השמיים?",
    "Skyline Tower: Glazing": "מגדל קו הרקיע: זיגוג",
    "Market Research: The Lab": "מחקר שוק: המעבדה",
    "Donny is eager to expand your shopping catalogue.": "דוני להוט להרחיב את קטלוג הקניות שלך.",
    "Time to brew up tomorrow's trends! I’ll uncork the bubbles! This catalogue will be bursting in no time, and with a fat profit! I take it you're not turning down the co-opportunity of a lifetime?": "הגיע הזמן לרקוח את הטרנדים של מחר! אני אחלוץ את הפקקים! הקטלוג הזה עומד להתפוצץ תוך זמן קצר, ועם רווח שמן! אני מניח שאינך מסרב לשותפות החד-פעמית של החיים?",
    "Knew you’d be onboard, oh wise one! To kick off we have to invest in R & D – a bore-chore – but we delegate. Once we've built them their lab we can get on to the real stuff.": "ידעתי שתהיה בעניין, הו חכם באדם! כדי להתחיל עלינו להשקיע במו\"פ — מטלה משעממת — אבל אנחנו מאצילים סמכויות. ברגע שנבנה להם את המעבדה שלהם נוכל לעבור לדבר האמיתי.",
    "Scared? Happens to some...I'd better find another industrialist to idolise.": "מפחד? זה קורה לחלק... מוטב שאמצא תעשיין אחר להעריץ.",
    "Donny wants a market research lab built.": "דוני רוצה שתיבנה מעבדת מחקר שוק.",
    "Donny is surprised his idol turned him down.": "דוני מופתע מכך שהאליל שלו סירב לו.",
    "Obsessed with the Shopping Arcade’s promise of profit, Donald Bader tasks you with commandeering office space amid the existing Engineer apartments for a so-called ‘market research lab‘. He wants to develop new patents there — or as he calls them, the needs of tomorrow!": "כשהוא אובססיבי להבטחת הרווח של פסז' הקניות, דונלד ביידר מטיל עליך להשתלט על שטח משרדי בין דירות המהנדסים הקיימות עבור מה שקרוי 'מעבדת מחקר שוק'. הוא רוצה לפתח שם פטנטים חדשים — או כפי שהוא מכנה אותם, צורכי המחר!",
    "Reach the following amount of new skyscrapers in [Area Area([Conditions QuestArea]) CityName]:<br/>[Conditions QuestCondition CurrentAmount]/[Conditions QuestCondition Amount] [AssetData([Conditions QuestCondition Context]) Text]": "הגע לכמות הבאה של גורדי שחקים חדשים ב-[Area Area([Conditions QuestArea]) CityName]:<br/>[Conditions QuestCondition CurrentAmount]/[Conditions QuestCondition Amount] [AssetData([Conditions QuestCondition Context]) Text]",
    "Place a <b>Gazebo Plaza</b> next to the Engineer Skyscraper in [Area Area([Conditions QuestArea]) CityName]": "מקם <b>כיכר גזיבו</b> ליד גורד השחקים של המהנדסים ב-[Area Area([Conditions QuestArea]) CityName]",
    "You can upgrade an Engineer residence into a skyscraper from its menu once you've fulfilled all the Engineer's needs.": "תוכל לשדרג בית מגורים של מהנדסים לגורד שחקים מתוך התפריט שלו ברגע שתספק את כל צורכי המהנדס.",
    "The Gazebo Plaza is an ornament belonging to the Luxury Park category. Open the Classic Tab of the Beautification Menu to find it. Donald Bader’s tastes are highly specific and he will accept no other ornament.": "כיכר הגזיבו היא קישוט השייך לקטגוריית פארק היוקרה. פתח את הלשונית הקלאסית בתפריט הקישוטים כדי למצוא אותו. הטעמים של דונלד ביידר הם מאוד ספציפיים והוא לא יקבל שום קישוט אחר.",
    "Donny expects offices to look fancier.": "דוני מצפה שהמשרדים ייראו מפוארים יותר.",
    "Boring! We’re shaping the future of consume, here! The outside’s drab— has to show off what happens inside. People like gardens, right? Slap a gazebo next to it!": "משעמם! אנחנו מעצבים פה את עתיד הצריכה! מבחוץ זה אפרורי — זה חייב להציג לראווה את מה שקורה בפנים. אנשים אוהבים גנים, נכון? שים גזיבו ליד זה!",
    "Not too shabby! Should be a breeze now for Miss Jenny, my house help here, to get to work. We do the big picture, she'll do the nitty-gritty.": "לא רע בכלל! זה אמור להיות משחק ילדים כעת עבור מיס ג'ני, עוזרת הבית שלי כאן, להגיע לעבודה. אנחנו דואגים לתמונה הגדולה, והיא תדאג לפרטים הקטנים.",
    "Donny off-handedly introduces his lead engineer.": "דוני מציג כבדרך אגב את המהנדסת הראשית שלו.",
    "Lose Island": "איבוד האי",
    "All Department Stores": "כל חנויות הכלבו",
    "All Furniture Stores": "כל חנויות הרהיטים",
    "All Drug Stores": "כל בתי המרקחת",
    "Fridge Trigger": "טריגר מקרר",
    "Have a member's club next to a pub. The proximity of the classes may lead to new innovations for the dining room!": "הצב מועדון חברים ליד פאב. הקרבה של המעמדות עשויה להוביל לחידושים חדשים עבור חדר האוכל!",
    "Have at least 5 Investor skyscrapers of level 3 height. Expanding the amount of habitable square meters may create new and more efficient ways to keep them clean.": "החזק לפחות 5 גורדי שחקים של משקיעים בגובה דרגה 3. הרחבת השטח הראוי למגורים עשויה ליצור דרכים חדשות ויעילות יותר לשמור עליהם נקיים.",
    "Invent and equip \"The Magnificone\" Ice Cream Maker in a town hall in the Old World. The concept of chilling food could be a study for your Engineers.": "המצא והצטייד במכונת הגלידה \"דה מגניפיקון\" בבית עירייה בעולם הישן. הרעיון של קירור מזון יכול להוות מחקר עבור המהנדסים שלך.",
    "Place a Department Store next to your Scholar residences. The particularly inspired customers could lead to new fashionable trends and patents...": "מקם חנות כלבו ליד בתי המגורים של המלומדים שלך. הלקוחות מלאי ההשראה במיוחד עשויים להוביל למגמות אופנתיות ופטנטים חדשים...",
    "Complete the Eastern Jungle exhibition in one of your Old World zoos. Visitors inspired by its exoticism may want to bring an oriental touch to their homes.": "השלם את תערוכת הג'ונגל המזרחי באחד מגני החיות שלך בעולם הישן. מבקרים שקיבלו השראה מהאקזוטיות שלה עשויים לרצות להביא מגע מזרחי לבתיהם.",
    "Have a Shopping Arcade providing Banker's Lamps with 100% productivity. Having so many lamps, you'll need at least as many desks...": "החזק בפסז' קניות המספק מנורות בנקאים עם 100% פרודוקטיביות. כשיש כל כך הרבה מנורות, תצטרך לפחות אותו מספר של שולחנות כתיבה...",
    "Give access to more bear fur and feathers to any of your Old-World islands. Such materials could provide inspiration for your tailors...": "ספק גישה ליותר פרוות דובים ונוצות לכל אחד מהאיים שלך בעולם הישן. חומרים כאלה יכולים לספק השראה לחייטים שלך...",
    "Build 2 additional radio towers. The development of a radio network may lead to new habits, and new needs.": "בנה 2 מגדלי רדיו נוספים. פיתוח רשת רדיו עשוי להוביל להרגלים חדשים ולצרכים חדשים.",
    "Have 40 investor skyscrapers of the highest level. If the view of the city is tainted, the investors may come up with some solutions...": "החזק ב-40 גורדי שחקים של משקיעים מהדרגה הגבוהה ביותר. אם נוף העיר נפגע, המשקיעים עשויים להעלות כמה פתרונות...",
    "Have a Variety Theatre next to an Investor skyscraper of the highest Level. Wealthy ladies may develop new habits when going out for the night.": "הצב תיאטרון וראייטי ליד גורד שחקים של משקיעים מהדרגה הגבוהה ביותר. גבירות עשירות עשויות לפתח הרגלים חדשים ביציאה לבילוי לילי.",
    "Complete the Icebound exhibition in one of your Old World museums. Cold environments in your most frequented places could lead to new needs for skin care.": "השלם את תערוכת הקרח באחד המוזיאונים שלך בעולם הישן. סביבות קרות במקומות המתויירים ביותר שלך עשויות להוביל לצרכים חדשים לטיפוח העור.",
    "Have a hibiscus farm next to a beekeeper. The two experts may mix their products, creating unique results.": "הצב חוות היביסקוס ליד מגדל דבורים. שני המומחים עשויים לערבב את המוצרים שלהם, וליצור תוצאות ייחודיות.",
    "Once you've provided your citizens with toasters and accepted the hunt for new patents from Donald, you should attempt to fulfill his demands.": "לאחר שסיפקת לאזרחיך מצנמים והסכמת למצוד אחר פטנטים חדשים מדונלד, עליך לנסות לענות על דרישותיו.",
    "Make sure you provide your citizens with Banker's Lamps and have an Engineer skyscraper nearby; then Donald should provide you with some new tasks.": "ודא שאתה מספק לאזרחיך מנורות בנקאים ושיש גורד שחקים של מהנדסים בקרבת מקום; אז דונלד אמור לספק לך כמה משימות חדשות.",
    "Ensure that your citizens have access to Toothpaste, and that you have an Engineer skyscraper nearby. Then Donald will certainly have some new tasks for you.": "ודא שלאזרחיך יש גישה למשחת שיניים, ושיש לך גורד שחקים של מהנדסים בקרבת מקום. אז לדונלד בהחלט יהיו כמה משימות חדשות עבורך.",
    "Patent Unlock": "פתיחת פטנט",
    "New department store patent unlocked!": "פטנט חנות כלבו חדש נפתח!",
    "New furniture store patent unlocked!": "פטנט חנות רהיטים חדש נפתח!",
    "New drug store patent unlocked!": "פטנט בית מרקחת חדש נפתח!",
    "The investor says crockery can now be sold in shopping arcades.": "המשקיע אומר שכעת ניתן למכור כלי אוכל בפסז'י קניות.",
    "The Investor says vacuum cleaners can now be sold in shopping arcades.": "המשקיע אומר שכעת ניתן למכור שואבי אבק בפסז'י קניות.",
    "The Investor says refrigerators can now be sold in Shopping Arcades.": "המשקיע אומר שכעת ניתן למכור מקררים בפסז'י קניות.",
    "The investor says briefcases can now be sold in shopping arcades.": "המשקיע אומר שכעת ניתן למכור תיקי מסמכים בפסז'י קניות.",
    "The investor says vanity screens can now be sold in shopping arcades.": "המשקיע אומר שכעת ניתן למכור פרגודים בפסז'י קניות.",
    "The investor says the writing desk can now be sold in shopping arcades.": "המשקיע אומר שכעת ניתן למכור שולחנות כתיבה בפסז'י קניות.",
    "The investor says the four-poster bed can now be sold in shopping arcades.": "המשקיע אומר שכעת ניתן למכור מיטות אפריון בפסז'י קניות.",
    "The investor says lounge seating can now be sold in shopping arcades.": "המשקיע אומר שכעת ניתן למכור פינות ישיבה בפסז'י קניות.",
    "The investor says detergent can now be sold in shopping arcades.": "המשקיע אומר שכעת ניתן למכור חומרי ניקוי בפסז'י קניות.",
    "The investor says lipstick can now be sold in shopping arcades.": "המשקיע אומר שכעת ניתן למכור שפתונים בפסז'י קניות.",
    "The investor says face cream can now be sold in shopping arcades.": "המשקיע אומר שכעת ניתן למכור קרם פנים בפסז'י קניות.",
    "The investor says pomade can now be sold in shopping arcades.": "המשקיע אומר שכעת ניתן למכור משחת שיער בפסז'י קניות.",
    "Who am I to deny the working class? They’ve seen us eating off china at the club, and now they want the same. Let them! — all they have to do is pay for it!": "מי אני שאמנע זאת ממעמד הפועלים? הם ראו אותנו אוכלים מכלי פורצלן במועדון, ועכשיו הם רוצים את אותו הדבר. שיהיה להם! — כל מה שהם צריכים לעשות זה לשלם על זה!",
    "Splendid! Cleaning all these floors is hard work, I should know, I pay the bill. With this machine I can slash the staff!": "נהדר! ניקוי כל הקומות האלה זו עבודה קשה, אני יודע, אני משלם את החשבון. עם המכונה הזו אני יכול לקצץ בצוות העובדים!",
    "Engineers, a restless bunch! Even on an ice cream break, they think up the next thing - And I do prefer my scotch on the rocks and my meat unspoiled.": "מהנדסים, חבורה חסרת מנוח! אפילו בהפסקת גלידה הם חושבים על הדבר הבא - ואני אכן מעדיף את הוויסקי שלי עם קרח ואת הבשר שלי לא מקולקל.",
    "Yes, Jr. has a classmate from Enbesa, young chap, jaunts about with a sleek leather bag. Passing the shopping arcades, he’s practically a walking advertisement!": "כן, לג'וניור יש בן כיתה מאנבסה, בחור צעיר, שמסתובב עם תיק עור אלגנטי. כשהוא עובר ליד פסז'י הקניות, הוא פשוט פרסומת מהלכת!",
    "I’ve heard the oriental exhibition at the zoo is a hit. haven't been myself but, a vanity screen with a thematic print might be the perfect souvenir.": "שמעתי שתערוכת המזרח בגן החיות היא להיט. לא הייתי שם בעצמי אבל, פרגוד עם הדפס תמטי עשוי להיות המזכרת המושלמת.",
    "Clearly a quality lamp needs a quality writing desk to stand on, however else will our customers work through the night to afford both. Rather illuminating wouldn’t you agree?": "ברור שמנורה איכותית צריכה שולחן כתיבה איכותי לעמוד עליו, אחרת איך עוד הלקוחות שלנו יעבדו לאורך כל הלילה כדי להרשות לעצמם את שניהם. מאיר עיניים למדי, לא תסכים?",
    "Yes, maybe with quality bedding – something warm and soft from up North, like eiderdowns – people would require fewer hours of rest and could go shopping!": "כן, אולי עם מצעים איכותיים — משהו חם ורך מהצפון, כמו פוך נוצות — אנשים יצטרכו פחות שעות מנוחה ויוכלו לצאת לקניות!",
    "People enjoy listening to the wireless together? Well surely, we can provide comfort with the appropriate seating. They’ll have to work to afford the leisure time of course...": "אנשים נהנים להאזין לרדיו יחד? ובכן בוודאי, נוכל לספק להם נוחות עם מקומות הישיבה המתאימים. הם יצטרכו לעבוד כדי להרשות לעצמם את שעות הפנאי כמובן...",
    "In meetings with Avery I like to gaze out of the window – contingencies are a bore – but there was this nasty spot on the glass obscuring my view. I can’t have that!": "בפגישות עם אייברי אני אוהב להביט מהחלון — מקרי חירום הם מטרד — אבל היה הכתם המגעיל הזה על הזכוכית שהסתיר לי את הנוף. אני לא יכול להרשות את זה!",
    "The wife’s taken a liking to the cabaret – beats me – but feels that among the glitz she can’t shine. I tell her, 'darling wear something bold, something the others can’t afford.'": "אשתי התחילה לחבב את הקברט — אין לי מושג למה — אבל מרגישה שבין כל הזוהר היא לא יכולה לבלוט. אמרתי לה, 'יקירתי, תלבשי משהו נועז, משהו שאחרים אינם יכולים להרשות לעצמם'.",
    "The museum’s new exhibit is rather ill received by my peers – the icy rooms you see, make their skin turn red! Face cream, with some whitener, should appease their antiquated standards!": "התערוכה החדשה של המוזיאון מתקבלת בצורה די גרועה על ידי חבריי — החדרים הקפואים, אתה מבין, גורמים לעור שלהם להאדים! קרם פנים, עם קצת חומר הלבנה, אמור להשקיט את הסטנדרטים המיושנים שלהם!",
    "The wind up here makes having a tipple a chore. We need something to set the hair. Jr. spoke of a wax-based hibiscus hair mask from Enbesa, let’s brand it for the regional market.": "הרוח כאן למעלה הופכת כל כוסית למטרד. אנחנו צריכים משהו שיקבע את השיער. ג'וניור דיבר על מסכת שיער מבוססת שעווה והיביסקוס מאנבסה, בוא נמתג אותה עבור השוק המקומי.",
    "Toaster Supply": "אספקת מצנמים",
    "Some patent unlock conditions have changed": "כמה מתנאי פתיחת הפטנטים השתנו",
    "Donny asks you to relocate the market research lab.": "דוני מבקש ממך להעתיק את מיקום מעבדת מחקר השוק.",
    "The whole darn island? Tough business! Well, this patent is dead. We'll have to relocate, if we want Miss Jenny to get working for us.": "כל האי הארור הזה? עסק קשה! ובכן, הפטנט הזה מת. נצטרך להעתיק את המיקום, אם אנחנו רוצים שמיס ג'ני תתחיל לעבוד בשבילנו.",
    "Donny says a new engineer skyscraper is needed to continue the research.": "דוני אומר שנדרש גורד שחקים חדש של מהנדסים כדי להמשיך במחקר.",
    "Keep in mind, without a marketing office our partnership will come to an end!": "קח בחשבון שללא משרד שיווק, השותפות שלנו תגיע לסיומה!",
    "Oh so you’ve decided to outsource to another island? A shame.": "הו, אז החלטת להעביר את העבודה למיקור חוץ באי אחר? חבל.",
    "No lab, no research. But don't wait, find some new real estate and build Miss Jenny a place to busy herself.": "אין מעבדה, אין מחקר. אבל אל תמתין, מצא נדל\"ן חדש ובנה למיס ג'ני מקום להעסיק את עצמה בו.",
    "All Engineer Skyscrapers": "כל גורדי השחקים של המהנדסים",
    "Lose Lab": "איבוד המעבדה",
    "Donny says check your shopping catalogue.": "דוני אומר לבדוק את קטלוג הקניות שלך.",
    "You know, your catalogue is pretty skinny... It's ok, Donny has some ideas to fatten it up— I already put notes in the margins.": "אתה יודע, הקטלוג שלך די דליל... זה בסדר, לדוני יש כמה רעיונות להשמין אותו — כבר רשמתי הערות בשוליים.",
    "Miss Jenny": "מיס ג'ני",
    "Theodora Thistlethorpe (a.k.a Miss Jenny)": "תיאודורה ת'יסלת'ורפ (הידועה כמיס ג'ני)",
    "William Brokeman": "ויליאם ברוקמן",
    "Yes, it is in the Beaux-Arts style, but at the upper levels the decor is less pronounced. A perfect marriage of aesthetics and pragmatism.": "כן, זה בסגנון הבוז-אר, אבל ברמות הגבוהות יותר העיטור פחות בולט. שילוב מושלם של אסתטיקה ופרגמטיות.",
    "Everyone's praising it, calling it a grand success, but I had a friend working top side and he got stories to tell that make you shudder...": "כולם משבחים את זה, קוראים לזה הצלחה גדולה, אבל היה לי חבר שעבד למעלה ויש לו סיפורים לספר שיגרמו לך להצטמרר...",
    "...and I said, no way in hell could they build such a behemoth so fast, and now they're done even sooner! I sure hope it holds up.": "...ואמרתי שאין שום סיכוי בעולם שהם יוכלו לבנות מפלצת כזו כל כך מהר, ועכשיו הם סיימו אפילו מוקדם יותר! אני מאוד מקווה שזה יחזיק מעמד.",
    "I for one have a bad feeling about the Skyline Tower. They neglected to skip the 13th floor.": "לי באופן אישי יש תחושה רעה לגבי מגדל קו הרקיע. הם שכחו לדלג על הקומה ה-13.",
    "Whatever the architect designs next, it will always have to live up to that there Skyline Tower.": "מה שהאדריכל יעצב בהמשך, זה תמיד יצטרך לעמוד בסטנדרט של מגדל קו הרקיע ההוא.",
    "She agrees she did it. But points out for me that his wallet remained untouched. They don't want to know her real motive— bad press. But make him out to be a martyr? What a legacy. Hours before the funeral his second has already picked up the mantle.": "היא מסכימה שהיא עשתה זאת. אך מצביעה בפניי על כך שארנקו נותר ללא פגע. הם אינם רוצים לדעת את המניע האמיתי שלה — סיקור עיתונאי שלילי. אבל להציג אותו כקדוש מעונה? איזו מורשת. שעות ספורות לפני ההלוויה, סגנו כבר לקח על עצמו את התפקיד.",
    "She ever tell you her motive?": "היא אי פעם סיפרה לך על המניע שלה?",
    "Little you can do for her, I imagine.": "אין הרבה שתוכל לעשות עבורה, אני מניח.",
    "The landlady is simply shocked no-one’s out looking for the young man. At first, I think her concerns lie with the state of her property. But turns out she relishes the young writer's work.": "בעלת הבית פשוט המומה מכך שאף אחד לא מחפש את הבחור הצעיר. בתחילה, אני חושב שדאגותיה נוגעות למצב הנכס שלה. אך מתברר שהיא מתענגת על יצירתו של הסופר הצעיר.",
    "Yes, more than a little derivative, if you ask me. Although by the looks of it, he wasn't a great fan of his latest efforts either. The chimney was packed with the remnants of charred notebooks and flame-eaten papers. The room's a mess, there’s burns on the carpet— it look like he packed up and left in a hurry— and there's a pot of dragon-green ink spilled on the table.": "כן, זה די נדוש וחסר מקוריות, אם תשאל אותי. אם כי למראית עין, הוא עצמו לא היה מעריץ גדול של מאמציו האחרונים. הארובה הייתה גדושה בשאריות של מחברות חרוכות וניירות אכולי אש. החדר מבולגן, יש כוויות על השטיח — זה נראה כאילו הוא ארז ועזב בחיפזון — וישנו מיכל של דיו ירוק-דרקון שנשפך על השולחן.",
    "Maybe he wrote something? But there doesn't seem to be a note. Then I find something strange: money stuffing up a tea box— why leave it? I start snooping. His contact at the magazine tells me the ‘Phantom Detective’ was doing swell but its writer was slow to deliver...": "אולי הוא כתב משהו? אבל נראה שאין שום פתק. ואז אני מוצא משהו מוזר: כסף שדחוס בתוך קופסת תה — למה להשאיר אותו? אני מתחיל לרחרח. איש הקשר שלו במגזין מספר לי ש\"הבלש הרפאים\" הצליח מאוד אבל הסופר שלו התעכב בהגשת החומרים...",
    "Oh, and this was the pulp writer? Wrote about the 'Phantom Detective'?": "הו, וזה היה סופר הספרות הזולה? זה שכתב על \"הבלש הרפאים\"?",
    "So, the squibbler skipped town because his creative trail had gone cold?": "אז השרבטן ברח מהעיר כי מעיין היצירה שלו יבש?",
    "You solve it?": "פתרת את זה?",
    "Yeah maybe. I try and get mine on track by spending the evening at his favourite haunt in the hope of gossip. The place is like death, lacks the seedy flair or a downtown juice joint, or the glitz of a snazzy uptown gin mill.": "כן, אולי. אני מנסה לעלות על המסלול על ידי בילוי הערב במקום המפגש המועדף עליו בתקווה לשמוע רכילות. המקום מרגיש כמו מוות, חסר לו את החן המפוקפק של בית מרזח במרכז העיר, או את הזוהר של מסבאת ג'ין יוקרתית.",
    "Dragon-green ink?": "דיו ירוק-דרקון?",
    "A few excitable friends of his invite me for a drink. One is fascinated to know my procedure, adamant he knows how ones like this always get solved. Another suggests an artistic quarrel drove him out of town. A third reckons he got in with the wrong crowd. After the fourth drink they mention his financial troubles. After the fifth it's the mob, the scorned lover, wild dogs and I'm tired of contradictions.": "כמה מחבריו הנוחים להתרגש מזמינים אותי למשקה. אחד מהם מרותק לרצות לדעת את שיטת העבודה שלי, נחוש בדעתו שהוא יודע כיצד מקרים כאלה תמיד נפתרים. אחר מציע שריב אמנותי גרם לו לעזוב את העיר. שלישי סבור שהוא הסתבך עם החבורה הלא נכונה. אחרי המשקה הרביעי הם מזכירים את הצרות הפיננסיות שלו. אחרי החמישי זה כבר המאפיה, המאהב הדחוי, כלבי פרא ואני כבר עייף מסתירות.",
    "So I make some guesses of my own, like which of their jolly crowd might work as a likely suspect. That's when they fess up. They got a strange letter— night their friend disappeared— a riddle they've been failing to solve, and it hurts their pride.": "אז אני מעלה כמה השערות משלי, כמו מי מתוך החבורה העליזה שלהם יכול לשמש כחשוד סביר. באותו רגע הם מודים. הם קיבלו מכתב מוזר — בלילה שבו חברם נעלם — חידה שהם לא הצליחו לפתור, וזה פוגע בגאוותם.",
    "Ever see it up close?": "ראית את זה אי פעם מקרוב?",
    "When I arrived at the scene all that was left was the empty frame. It lay on the floor all gaudy, a hushed silence suffocating the room.": "כשהגעתי למקום כל מה שנותר היה המסגרת הריקה. היא הייתה מונחת על הרצפה בצורה מצועצעת, ושתיקה חרישית חנקה את החדר.",
    "It was. Three days after, the curator walks in my office and confesses. I give him directions to the closest church, but he persists. He says a week before the crime he's confronted by a young man, tries to extort him, fails badly. They get talking.": "כך היה. שלושה ימים לאחר מכן, האוצר נכנס למשרדי ומתוודה. אני מכוון אותו לככנסייה הקרובה ביותר, אך הוא מתעקש. הוא מספר שבוע לפני הפשע פנה אליו בחור צעיר, ניסה לסחוט אותו ונכשל כישלון חרוץ. הם התחילו לשוחח.",
    "Once. Nice Painting. What drew me in was the marvel of the crowd.": "פעם אחת. ציור יפה. מה שמשך אותי היה הפלא של הקהל.",
    "Didn't the press speculate it was an inside job?": "האם העיתונות לא שיערה שזה היה שיתוף פעולה מבפנים?",
    "Help the kid steal the painting.": "לעזור לילד לגנוב את הציור.",
    "The kid's desperate, begs the curator for his life. He's gotten in with the mob and the Don wants him to steal a masterpiece as a present for his wife. The curator gets an idea.": "הילד מיואש, מתחנן בפני האוצר על חייו. הוא הסתבך עם המאפיה והדון רוצה שהוא יגנוב יצירת מופת כמתנה לאשתו. לאוצר עולה רעיון.",
    "And the kid-thief, does he know?": "והילד-גנב, האם הוא יודע?",
    "Almost. He can't imagine the Don will think to have the painting inspected, so the night of the theft he makes sure there's a fake on the wall.": "כמעט. הוא אינו מעלה על דעתו שהדון יחשוב לבדוק את הציור, ולכן בליל הגניבה הוא דואג שיהיה זיוף על הקיר.",
    "So the kid wants the Curator to deal directly with the mob?": "אז הילד רוצה שהאוצר יתעסק ישירות עם המאפיה?",
    "No, he thinks he's gotten the real 'woman on rocking chair', 'til the day he gets a letter. The Don's wife's real discerning and had someone take a look. Now they want the real one plus reparations.": "לא, הוא חושב שהוא השיג את \"האישה על כיסא הנדנדה\" האמיתית, עד ליום שבו הוא מקבל מכתב. אשתו של הדון באמת בעלת הבחנה דקה והיא דאגה שמישהו יבדוק את זה. עכשיו הם רוצים את הציור האמיתי ובתוספת פיצויים.",
    "You're there when the trade happens?": "אתה שם כשהעסקה מתבצעת?",
    "So it seems. But the whole thing feels off— after all the mob rarely correspond by mail. Anyway, we pen a response, naming a place and a time for a trade. The Curator'll bring the genuine piece, and two more.": "כך נראה. אבל כל העניין מרגיש חשוד — אחרי הכל, המאפיה כמעט ולא מתכתבת בדואר. בכל אופן, אנחנו מנסחים תשובה, וקובעים מקום וזמן לעסקה. האוצר יביא את היצירה המקורית, ועוד שתיים נוספות.",
    "What a shame. I was hoping the Don would be caught.": "כמה חבל. קיוויתי שהדון ייתפס.",
    "He's aghast— steal two more with the cops crawling the place!? Well for once I'm not working solo, I call up Hayes, who loves that I might need his help, but agrees. We get two pieces 'on loan' so to speak.": "הוא מזועזע — לגנוב עוד שתיים כשהשוטרים שורצים במקום?! ובכן, לשם שינוי אני לא עובד לבד, אני מרים טלפון להייז, ששמח על כך שאני עשוי להזדקק לעזרתו, אך מסכים. אנחנו משיגים שתי יצירות \"בהשאלה\", כביכול.",
    "Then you might have spotted the pair up in the balconies.": "אז אולי הבחנת בזוג למעלה ביציעים.",
    "Yes, Mr. Hall neglected to mention this in his defence, although that wasn't the most pertinent information about the princess he omitted.": "כן, מר הול שכח להזכיר זאת בהגנתו, אם כי זה לא היה המידע הרלוונטי ביותר לגבי הנסיכה שהוא השמיט.",
    "I went to see an operetta that night, ‘The Merry Widow.’": "הלכתי לראות אופרטה באותו לילה, \"האלמנה העליזה\".",
    "Really, they were out that night?": "באמת, הם יצאו באותו לילה?",
    "You were at the hearing? I heard people arrived before daybreak for a chance at a glimpse of her.": "היית בשימוע? שמעתי שאנשים הגיעו עוד לפני עלות השחר כדי לזכות בהזדמנות להציץ בה.",
    "Five days in total and I was there for the lot— still nebulous to me what truly transpired.": "חמישה ימים בסך הכל והייתי שם בכולם — עדיין מעורפל עבורי מה באמת התרחש שם.",
    "You really think she killed the sultan?": "אתה באמת חושב שהיא הרגה את הסולטאן?",
    "Shot him three times. They were alone, and the door to the hotel room was locked. Hell, they had to knock it through to reach 'em.": "ירתה בו שלוש פעמים. הם היו לבד, ודלת החדר במלון הייתה נעולה. לכל הרוחות, הם נאלצו לפרוץ אותה כדי להגיע אליהם.",
    "The press called her husband a monster.": "העיתונות כינתה את בעלה מפלצת.",
    "It was easy for Mr. Hall to cast him the villain and her the damsel in distress. See, there's more to the princess then meets the public eye. She made her initial foray into the limelight as a dancer, then upped her paygrade to an escort and ultimately, as you know, rose to become foreign royalty.": "זה היה קל עבור מר הול להציג אותו כנבל ואותה כעלמה במצוקה. ראה, יש בנסיכה יותר ממה שנראה לעין הציבורית. היא עשתה את צעדיה הראשונים באור הזרקורים כרקדנית, לאחר מכן שידרגה את מעמדה כמלווה ולבסוף, כפי שאתה יודע, עלתה למעמד של בת מלוכה זרה.",
    "None of her past was mentioned in the press!": "שום דבר מעברה לא הוזכר בעיתונות!",
    "Vested interests ensured that it wasn't. Before she met the Sultan she had a short but heated affair with a duke. I was hired to make sure the lovers letters are kept out of the limelight.": "אינטרסים אישיים הבטיחו שזה לא יקרה. לפני שפגשה את הסולטאן היה לה רומן קצר אך סוער עם דוכס. נשכרתי כדי לוודא שמכתבי האוהבים יישארו מחוץ לאור הזרקורים.",
    "You were tasked to find them?": "הוטל עליך למצוא אותם?",
    "She holds the Duke's responses as leverage to get someone like Hall on her side. I was to make sure there no other clues could be uncovered.": "היא מחזיקה בתשובותיו של הדוכס כמנוף לחץ כדי להשיג מישהו כמו הול לצדה. הייתי צריך לוודא שלא יתגלו רמזים נוספים.",
    "You were to obscure the truth?": "היית אמור להסתיר את האמת?",
    "It pays the rent. I convinced myself it had nothing to do with the murder. Well, shows what I know. Hall send me a card, a job well done.": "זה משלם את שכר הדירה. שכנעתי את עצמי שאין לזה שום קשר לרצח. ובכן, זה מראה מה אני יודע. הול שלח לי כרטיס, עבודה טובה.",
    "In his defence the solicitor said Rowse made a habit of carrying phials of arsenic in his pockets, to kill off the dandelions outside his house. This was in the dead of winter.": "בהגנתו אמר עורך הדין שרוז נהג לשאת בקבוקוני ארסן בכיסיו, כדי להשמיד את שיני הארי מחוץ לביתו. זה היה בעיצומו של החורף.",
    "They make the argument that the central plaintiff is his rival. But then again, said rival was poisoned over some chit-chat and a cup of yellow tea.  And Rowse owed him money, money his business was no longer bringing in.": "הם טוענים שהתובע המרכזי הוא היריב שלו. אך מצד שני, היריב המדובר הורעל במהלך שיחת חולין וכוס תה צהוב. ורוז היה חייב לו כסף, כסף שהעסק שלו כבר לא הניב.",
    "Not for the first time. There was an inquiry made six months ago— about his wife. She'd been gravely ill but recovered at a countryside hospital. When she returned home she was dead inside a month. I looked into it at the time, but the physician was convinced she'd relapsed— In some sense he was right— shouldda insisted on a thorugh examination of the body.": "לא בפעם הראשונה. היתה חקירה שנערכה לפני שישה חודשים — לגבי אשתו. היא הייתה חולה אנושות אך החלימה בבית חולים כפרי. כשחזרה לביתה היא מתה בתוך פחות מחודש. בדקתי את זה בזמנו, אך הרופא היה משוכנע שהיא חלתה שוב — במובן מסוים הוא צדק — הייתי צריך להתעקש על בדיקה יסודית של הגופה.",
    "Some say he may have been framed?": "יש האומרים שאולי הפילו עליו תיק?",
    "So he puts his arsenic to use...deadheading...": "אז הוא משתמש בארסן שלו... לקטימת פרחים נבולים...",
    "So what was different this time?": "אז מה היה שונה הפעם?"
}

# Add skips to skip.json
skip_file = "skip.json"
skips = []
if os.path.exists(skip_file):
    try:
        skips = json.load(open(skip_file, encoding="utf-8"))
    except Exception:
        skips = []

skips_set = set(skips)
for s in skips_to_add:
    skips_set.add(s)
new_skips = sorted(list(skips_set), key=lambda x: int(x))
json.dump(new_skips, open(skip_file, "w", encoding="utf-8"), ensure_ascii=False, indent=0)
print(f"Updated skip.json: {len(new_skips)} total skips")

# Clean up other trans_part_*.json files
for i in range(2, 6):
    p = f"trans_part_{i}.json"
    if os.path.exists(p):
        os.remove(p)
        print(f"Deleted old {p}")
for i in range(1, 6):
    p = f"skip_part_{i}.json"
    if os.path.exists(p):
        os.remove(p)
        print(f"Deleted old {p}")

# Translate the batch
translated = {}
missing = []
for guid, val in batch.items():
    if guid in skips_to_add:
        continue
    if val in mapping:
        translated[guid] = mapping[val]
    else:
        # Check if it was stripped by auto_skip or is in skips
        if guid in skips_set:
            continue
        missing.append((guid, val))

if missing:
    print(f"Error: {len(missing)} missing translations in batch!")
    for g, v in missing[:10]:
        print(f"  {g}: {v!r}")
else:
    # Save to trans_part_1.json
    json.dump(translated, open("trans_part_1.json", "w", encoding="utf-8"), ensure_ascii=False, indent=4)
    print(f"Successfully saved {len(translated)} translations to trans_part_1.json")
