import json
import os

handoff = r"c:\Users\Nehoray_Cohen\Projects\Game translator\games\anno1800\agent_handoff"

trans = {
    "803660": "<b>You take them completely by surprise.</b> In moments, the men are down and out for the count. The woman is eloquent and alert, and <b>she asks to join your expedition.</b> Once she is safely out of the village, she explains with sadness that the angry young men of a rival family have seized control of the region, and that it would be dangerous for her to remain.",
    "803661": "<b>The odds aren't good</b> - two against three - and your scouts are knocked violently to the floor. The prisoner is forced to drink, and the vial's contents appear to make her compliant. The three young men push her out of the cabin. <b>When your scouts have themselves recovered, they wonder what they should do.</b>",
    "803662": "Call for reinforcements",
    "803663": "<b>Keen reinforcements arrive at the double, only to discover that the gang of abductors has grown.</b> They must be fifty-strong, a miscellany of raiders who've been terrorising the region. They are, however, wary of your capabilities, and agree to relinquish the captive woman in return for your immediate departure. Her relatives soon carry her to safety - <b>but with two casualties of your own, you'd best move on quickly too.</b>",
    "803664": "<b>Your reinforcements charge idiotically</b> into an important local ritual, causing needless bloodshed. When the woman captive is seen being pushed into a grave of bodies, your men have no sense that this is just the theatre of the occult, and — to the bewilderment of the locals — they open fire. <b>The realisation of what they have done will traumatise your men for the rest of their lives.</b>",
    "803665": "Let her go, it's not worth the trouble",
    "803666": "<b>A dark silence falls over the village,</b> but for what sounds like the grim clink of shovels on soil. Your men better run for it before they quiver to jelly.",
    "803667": "Better to stay out of it after all",
    "803668": "Your men try to remain objective, but <b>the scene makes for uncomfortable viewing.</b> The drugged cup, made with the white devil's trumpet flower that grows all around, puts the woman into a somnambulant state, ensuring her compliance. She is taken outside and herded together with the other women, who appear to exist here in patriarchal servitude. <b>You leave feeling depressed</b> that negative stereotypes of other cultures appear to have been reinforced.",
    "803669": "<b>It's likely to be an international scandal.</b> Your numbskull spies are caught snooping about, which as it turns out, is an act in breach of a treaty between these people and Her Majesty's government. The leader of the protectorate vows to tear up the treaty and ban all westerners from these territories in future. <b>Your officers all let out little screams inside.</b>",
    "803670": "Ask the locals what's going on",
    "803671": "<b>Your envoys are sensitive to the particulars of the region,</b> and the locals feel relaxed enough to talk. It seems it was the scream of a young boy: he had been misbehaving, and was given medicine so that ancestors in the spirit world might admonish him, but the medicine seems to have had a bad effect. He is trapped in his nightmares, sweating and screaming all the while. <b>The locals are worried, and look to you for help.</b>",
    "803672": "Make a medical diagnosis",
    "803673": "<b>The doctor knows botanicals.</b> In the dregs of the medicine cup, the doctor finds Brugmansia, also called Devil's Trumpet — a hallucinogenic plant known for its power to terrify. Though often used in ritual here, the dosage seems high for a child. The other villagers don't seem surprised, because his parents are the local idiots. The villagers are glad the doctor is able to help pump the poison from the boy's stomach, and after a few days he is back to his usual impish self. <b>Your expedition are proud to have been of help.</b>",
    "803674": "<b>The doctor puts his hands down the boy's throat.</b> It isn't clear what he is trying to achieve by this, but it causes the boy to thrash violently from side to side. \"Damnation!\" cries the doctor, yanking out his arm, for the boy has bitten it. Then blood begins to pour from the boy's mouth, and a wriggling pink triangle flops to the floor. He has bitten out his own tongue, and <b>you are shooed angrily from the village.</b>",
    "803675": "Consult your knowledge of world faith",
    "803676": "\"Must be Brugmansia — also known as the Devil's trumpet.\" <b>Your clergyman is acutely aware of the local religion,</b> and knows the flower is used to induce spiritual delirium. \"Once the demon trumpet has been exorcised from his belly, I shall lead both the boy and his parents to a higher place,\" he says with a self-satisfied air, \"and this sort of thing need never happen here again.\" Rightly or wrongly, <b>your expedition will leave feeling it has done fine missionary work.</b>",
    "803677": "Instead of helping the poor boy, <b>your clergyman gets carried away</b> with his proselytising. Being ignorant of the boy's exact affliction, he falls fearfully back to the age-old redoubt of the cleric: that all around them are wicked heathens. It takes several strong soldiers to drag him away, and <b>your expedition leaves feeling it may have tarnished Her Majesty's reputation.</b>",
    "803678": "Ignore the screaming and carry on",
    "803679": "<b>It sure sounded like torture,</b> and the sanctimonious among you waste no time in reminding everyone of that probability. While good fences make good neighbours, it doesn't hurt to be nosey and neighbourly from time to time.",
    "803680": "<b>Your representatives don't approach it in the right way:</b> \"We heard screaming, and we demand to know the cause!\" These people see no reason why they should have to explain themselves to you, and produce a document with a royal seal granting immunity from such unwanted attention. <b>Your leadership feel embarrassed and undermined.</b>",
    "803681": "Trespassers",
    "803682": "<b>An ambush of missiles!</b> This unmapped region of the great forest is home to an indigenous people, whose policy is to pre-empt the hostility of trespassers into their territory. Suddenly a man grips his shoulder, where a feathered dart now hangs. It could have come from anywhere. Do you <b>hide</b>, <b>fight</b>, or if all else fails, <b>flee?</b>",
    "803683": "Find cover!",
    "803684": "<b>The rain of darts comes to an end</b> when your group quickly and cleverly diffuses, each finding their own space. Out of respect, perhaps, your ambushers decide to retreat — or do they simply believe the damage has already been done? Those who were hit begin to wheeze heavily, collapsing to the floor, for <b>the darts are tipped with poison!</b>",
    "803685": "Identify the poison",
    "803686": "<b>The doctor is praised for their quickness of thought.</b> \"Wolf's bane, of the slopes above,\" words pour out, \"classically lethal, but by Jove, I have an idea!\" An extraordinary antidote is proposed — a posset of deadly nightshade — and its effect is remarkable. \"Don't ask me how, but it's worked!\" the doctor says cheerfully, as the victims of the poison darts begin to return to normal. Your expedition marks the territory on the map for the sake of anthropology, before taking the long road around it.",
    "803687": "<b>Anxious to avoid misdiagnosis, the doctor is slow to react.</b> Before long, the one who took a dart to the neck suffers opisthotonos — his back arching in spasm, before giving out to exhaustion. The death sparks the good doctor into life. \"Ah, so it's strychnine!\" he says gesturing to the trees, \"Sourced from breadfruit.\" Chloroform relaxes his patients for a cleansing irrigation, and somehow, they manage to recover. Time to leave this place.",
    "803689": "Knowledge of local practices may yield answers",
    "803690": "<b>It's what the locals know as 'ourare'.</b> Accounts from the region frequently reference it as a lethal coating for arrowheads, or in this case, blowpipe darts. A treatment is also mentioned — a form of mouth-to-mouth in which the resuscitator acts as an iron lung for the patient. And it works! There is no childish awkwardness, with an excess of volunteers offering to save their fellows. The victims of the poison are saved, and all emerge from those (often dark) hours with a new feeling of togetherness.",
    "803691": "<b>\"You always hear stories about poison dart frogs out here,\"</b> says one of the officers. He doesn't seem to know much more than that, except that in a 'Boy's Own' adventure story, chloroform was used to treat frog poisoning. No-one seems to know where the medicine box is, but by the time it is found, someone has already succumbed to convulsions. It is only a slight relief then, that the chloroform does indeed relax the other victims sufficiently to keep their hearts beating. Time to leave this place.",
    "803692": "<b>Your barbarous dimwits are ignorant of local customs.</b> \"Do they tip arrows with cyanide, perhaps?\" Your officer snaps, wiping sweat from his reddened face, \"How the devil would I know what these primitives use?!\" Those who took darts wear expressions confused and melancholy as they melt into darkness, wondering, perhaps, what the point of their sacrifice was. Your expedition bury the dead as fast as they can, lest the hostile peoples of this particular territory return.",
    "803693": "<b>Unfortunately, the darts continue to find their mark,</b> for the hostile tribe know the forest too well. It is fortunate that your ambushers, perhaps seeing the sort of weapons you're carrying, decide to retreat. Or do they simply believe the damage has already been done? The men who were hit begin wheezing heavily, and collapse to the floor, for <b>the darts were tipped with poison!</b>",
    "803694": "Root out and tackle the ambushers",
    "803695": "<b>It takes all of their calm</b> for your men to fan into the forest. There's a thud as one of the dart-blowers is struck down with the butt of a rifle. Whistles all around signal a retreat, leaving your men to examine one of the six-foot blowpipes: perhaps they left knowing the damage had already been done? Sure enough, those hit begin wheezing heavily, collapsing to the floor. <b>The darts are tipped with poison!</b>",
    "803696": "<b>Your men make themselves easy targets,</b> desperately trying to pursue and isolate their adversaries, to no avail. As more of the feathery darts hit home, so too does a realisation of their function. Whistles all around signal a surprise retreat, as those who have been hit begin to wheeze heavily, collapsing to the floor. <b>The darts are tipped with poison!</b>",
    "803697": "Identify the poison",
    "803698": "Knowledge of local practices may yield answers",
    "803708": "Make a desperate run for it!",
    "803709": "<b>The people of the forest will do all they can to protect it.</b> As your expedition flees, the poison darts that have stuck in their backs begin to take effect. There is nothing to do but leave the unlucky ones contorting in agony.",
    "803711": "<b>\"There's no other way, we must wade the swamp.\"</b> It doesn't look too deep at first, but soon the party are up to their waists in muddy water and too far in to turn back. A sinister log, seemingly adrift, mutates into the jaws of a dragon. <b>\"A gator!\"</b>",
    "803712": "Take the shot",
    "803713": "<b>Bullseye!</b> Your skilled huntsman pulls out his rifle and it only takes him one deep breath to put a bullet exactly two inches behind the creature's razor-sharp eye, hitting its marble-sized brain. The monster goes limp immediately and the crew members roar as they lift the legendary trophy above their heads, marking the day your daring huntsman became the dragonslayer.",
    "803714": "<b>The creature's scales are bulletproof!</b> Your hunters fail to find a weak spot and every shot seemingly ricochets off the monster's skin. The creature growls, but the hail of pellets fails to stop its swift jaws from clamping down on your petrified navigator's arm.",
    "803715": "Force the monster's jaw open",
    "803716": "<b>A feat everyone will remember!</b> It takes ten men to restrain the alligator and pull its maw open only a tiny slit, but it is enough for your navigator to pull her chewed-out arm out. As she stumbles away gripping her limp arm, a sailor sinks a knife in the beast's neck and it slowly stops twisting and wriggling. Everyone is bruised and scratched, and the navigator might never fully recover from her wounds, but she will never forget they way her comrades risked their lives to save hers.",
    "803717": "<b>They underestimated the monster!</b> Two men confront it head on, as the rest of the party watch meekly from afar. The beast snaps the navigator's arm as if it were a twig and launches itself onto the men, fast as lightning. It takes one of them by the armpit and, with a fearsome roll, rips his body apart. Both creature and man disappear in the murky water, leaving nothing but a trail of gore behind.",
    "803718": "Run for your life",
    "803719": "<b>The crew waddles away as fast as they can, </b>leaving their navigator trapped in the jaws of the monster. Luckily, the creature is sated with one big bite out of her forearm, and she is free to catch up to her cowardly comrades and escape the situation with nothing but a gruesome scar and an irreconcilable mistrust in her fellow crewmen.",
    "803720": "<b>A tragedy!</b> Each armed crew member draws their pistol and unleashes a hail of pellets upon the beast. Not only is the reckless manoeuvre utterly ineffective against the monster's bulletproof scales; your petrified navigator is caught between the beast and the open fire. With nowhere to run, she falls an easy prey to the gator. It shakes her tiny body around in its jaws like a puppet and pulls her down to the cloudy water, never to be seen again.",
    "803721": "Tackle the beast",
    "803722": "<b>A legend has been born!</b> While some members of the crew distract the beast, one bold sailor jumps on the gator’s back and clutches its neck. It takes ten more men to pin the monster's maw shut, but once it's immobilised, the sailor pulls out a knife and sinks it into the monster’s skull. At first the creature twitches, but then it goes limp. The crew members roar as they lift the legendary trophy above their heads, marking the day their daring crewmate became the dragonslayer.",
    "803723": "<b>A miraculous escape!</b> While some members of the crew distract the beast, one bold sailor draws a knife, jumps on the gator’s back and clutches its neck. But he's no match for the monster's atrocious strength, and it easily squirms out of his embrace, shutting its maw around his arm. With a harrowing howl, the man manages to sink his knife into the alligator's skull, killing it instantly. The stump on his arm shall forever remind him of his heroic feat.",
    "803724": "<b>They underestimated the monster.</b> Two men confront it head on, as the rest of the party watch meekly from afar. The beast launches itself onto the men, fast as lightning. It takes one of them by the armpit and, with a fearsome roll, rips his body apart. Both creature and man disappear in the murky water, leaving nothing but a trail of gore behind.",
    "803725": "The Beast of the Swamp",
    "803727": "For Whom The Bell Atolls",
    "803728": "<b>Your ship is pinned on the razor-sharp coral</b> that fringes an underwater volcano. Since she has rolled onto her side, freeing your ship will require surgical precision if you're to prevent gallons of water from flooding in. If you do not wish to <b>send a team of divers to cut the ship free,</b> you may instead be able to <b>make or use something clever</b> to break free.",
    "803729": "Use your diving bell",
    "803730": "<b>The bell rings true.</b> Despite plonking into the water at an angle to which it is unaccustomed — the ship being at such a slant — the diving bell descends easily to the scene of your troubles. Through the little glass window, a forest of living pastel appears, of which some of the more beautiful examples are embedded in the hull. Once your divers have detached the lifelinks constraining your vessel, your crew are free to resume what is becoming a fascinating journey.",
    "803731": "Send free divers down to remove the coral",
    "803732": "<b>Your divers take to the sea like fish to water,</b> having had some dive training with the navy. Still, the others worry when five or six pass, and they still have yet to surface. Suddenly the boat begins to wobble — they've been cut free! Soon after, your heroes emerge from the water giddy and glistening, brandishing the magnificent coral in their hands.",
    "803733": "<b>They can barely hold their breath for long enough</b> to reach the coral floor, and as such, they're forced to cut the ship free in relays. Error creeps in to their work along with feelings of lightheadedness, and <b>one of the divers slices his foot open on a shank of coral.</b> Everyone is too absorbed in their task to notice, but once the ship is free and back at sea, the pustulent swelling of the man's foot becomes increasingly difficult to ignore...",
    "803734": "Tend to the diver's foot",
    "803735": "<b>Although your medic does take immediate action,</b> vigorously scrubbing the wound and flushing with fresh water and vinegar, the coral cut takes a surprisingly long time to properly heal. \"Will I die? Is this the end?\" the injured officer complains, as if an invalid to be waited on hand and foot. Thankfully, eventually the swelling reduces, and everyone can get on with their lives.",
    "803736": "<b>Someone puts bandages around the wounds in a haphazard fashion,</b> as if they were mere scratches. \"Change the bandages every few days\" is the advice, but the abscess that has formed beneath soon bursts, and the vile infection spreads. <b>The man dies in his sleep.</b> For the others, their negligence will forever remain a source of great shame — for no man is an island, and the death of one man diminishes the whole.",
    "803737": "Tell him to grin and bear it.",
    "803738": "<b>The diver develops a fever.</b> The abscess does not disappear, and a nasty infection spreads up the arm causing it to become swollen. He will be of no use on the ship for the remainder of the expedition, instead serving only as an unpleasant reminder of the officers' inhuman disregard for the welfare of their crew.",
    "803739": "Find a cunning way to free the ship",
    "803740": "<b>Your ship looks a sensation now she has coral poking from her keel.</b> Like doctors treating a foreign object, your fine craftsmen utilise a panoply of tools to reach under the hull and fragment the coral. They are then nimbly able to dress the wound in the hull before very much water gets in. The few naughty pieces of coral that remain wedged in the keel look rather fetching!",
    "803741": "<b>They use a lot of spare materials, but it works.</b> Fighting against the slant of the ship, they are able to fragment the coral with a long pole they have constructed out of wood and rope. It is extremely heavy, however, and as the ship judders free, your men cannot stop it from sliding into the sea. It feels like a waste, and there's only just enough wood left to repair the breach in the hull.",
    "803742": "<b>There is a lot of head-scratching below deck,</b> as your confused carpenters try to fight the flood. They have neither the tools nor creativity to do much more than smash the coral that has ripped through the ship. When the vessel judders free, it has almost no buoyancy, and the crew count themselves lucky when the lumbering ship is swept ashore on the tide. <b>It seems you have shipwrecked on a coral atoll.</b>",
    "803744": "Permit A38",
    "803745": "Not a step forward!\" says the harbour master of the big merchant harbor the crew stopped at. \"You need to register your galley before doing anything here! Go to the harbour office, the red building, on the first floor corridor B last door on the right.\" A group of sailors volunteer to go but when they arrive there is no door on the right, only on the left.",
    "803746": "Open the left door and ask for direction",
    "803747": "The diplomat is the nicest consumer the administration officer has seen in a while. The old man holds up the group, rambling about his life for long minutes, visibly happy to have somebody to listen. Eventually, he stamps the official paper and wishes the bush a nice day. The crew leaves happy, they can be among the happy few who have a great experience with administration.<br/><br/>Diplomat beat them at their own game, understanding the administration system.",
    "803748": "The diplomat is already bothered by what seems to be a boring administrative procedure. He opens the door without knocking and startled a man who was swinging on his chair, clearly not working. \"Who gave you permission to come to my office?! I am not a guide, take care of your own problems! And close the door, impertinent!\" ",
    "803749": "Threaten him to get the information",
    "803750": "Visibly intimidated, gives direction. They walk long corridors and start to believe the man fooled them when they arrived in front of the door marked Gallery Matriculation. Enter, they get the permit.",
    "803751": "\"Such bad manners! Go to window 1 second floor fourth corridor\"</br>One of the sailor notices a smirk on his face but is too happy to finally have a direction to question it.</br>At window 1, two ladies talking and refusing to answer the sailors request, they claim they are not abilited but the official stamp is on their desk.",
    "803752": "Win them over so they deliver the authorization / Be nice, not usual costumer",
    "803753": "The sailor listens carefully to their conversation and notices the exact right moment to get into it. \"You are so right! It is shocking that she  had to let her maid go because she has no more money? I am utterly chocked!\" <br/>\"Exactly!\" answers the lady, \"but she claims she fired her because she prefers to do the housework herself but I know that...\" <br/>The conversation goes on for a few minutes then one of the ladies command the sailor on his niceness and politeness. She agrees the sign the authorization.",
    "803754": "Sailor push himself into the conversation. Feels really rude. The two ladies refuse to help them out and order them to leave their office immediately. The sailors lost hours for nothing, the ship is forced to leave the harbour.",
    "803755": "Slam a fist on the desk",
    "803756": "\"Gentlemen please call down, some of us are trying to work! You want to immatriculate a galley, here is your paper. Now be kind to leave!\"",
    "803757": "The demonstration of strength is not for the least intimidating for the ladies. \"Jesus, how rude people are these days! No way I am helping you!\" \"Give us the Permit!\" screams a sailor. \"No we are here to immatriculate a galley!\" screams the other.<br/>\"Out, all of you!\" the lady screams. The sailors lost hours for nothing, the ship is forced to leave the harbour.<br/><br/>Shut the metal window",
    "803758": "Take the stamp on their desk discreetly",
    "803759": "Pretend to check on papers on the desk and succesfully manage to grab the stamp while the ladies have a lively discussion. Stamp the official paper and put the stamp back in place unnoticed.",
    "803760": "Fail, see them try to steal the stamp. The sailors are carried outside. They lost hours for nothing.",
    "803761": "Leave the office and look for a map",
    "803762": "The crew is extremely careful in order to spot anything which might look like direction. They end up finding a confusing map in a remote corridor but they manage to make sense of it. Spot the Galley Matriculation office on it. Go there, get the permit.",
    "803763": "Climb all the floors, look everywhere. \"These stairs are pretty steep!\" complains a sailor. Unfortunately no map is on sight. The sailors are very tired and a bit discouraged.",
    "803764": "Ask for help to the first passerby",
    "803765": "Despite his exasperation, the diplomat remains nice. The person gladly gives direction but once at the office one of the clerk say the person they are looking for is gone for lunch.",
    "803766": "Persuade the lady present to take care of the request",
    "803767": "\"Aren't you a dove\" giggles the old lady as she take the stamp on her colleague desk. She provides them with the galley registration paper.",
    "803768": "The diplomat is rude, the old lady refuses to help them. They wait for the person in charge for two hours and when he arrives, the old lady whispers a few words to him while looking at the sailors. The administrative officers lets everybody else go first and when it's finally the crew turn the officers shot \"End of office hours, please leave the building!\" The crew has last hours for nothing, go back to the ship which is forced to leave the harbour.",
    "803769": "Wait for the officer to come back",
    "803770": "After two hours waiting the officer comes back and sign. The crew lost a lot of time but they had the permit they were looking for.",
    "803771": "Give up",
    "803772": "Lost time, the rest of the crew is angry at them, think they are stupid to not be able to perform a task as easy as this one. The ship has to leave.",
    "803773": "Look for a map",
    "803774": "The crew easily spots a piece of paper on the wall which looks nothing like a map to the untrained eyes. Though confusing, they manage to make sense of it and find the galley registration office., ground floor, first corridor on the right.<br/>\"We need to register a galley\". \"You didn't need to come here\" says the office lady, \"a stamp from the harbor master would have been enough. Luckily I have one here, here you go\". The crew feels lucky to be done with an administrative procedure so fast.<br/><br/>Beat them at their own game",
    "803775": "Climb all the floors, look everywhere but see nothing. \"These stairs are pretty steep!\" complains a sailor. The sailors are very tired and a bit discouraged.",
    "803776": "Too bad for the planned nice time on land, administration is one of the circle of hell",
    "803777": "Have to leave the harbor immediately without being able to relax and enjoy life on land before having to come back to the sea.",
    "803778": "\"Fly you fools! I have been trapped in this house for hours today and it is already the third time I come back for the same document! I don't know what to do!\" He storms out of the corridor screaming. Without direction, the sailors keep roaming for hours for nothing until they give up and go back to the ship which is forced to leave the harbour.",
    "803780": "The snake bite",
    "803781": "Today after the usual lunch, one crew member died. he was the only one who had eaten the porridge, it had certainly been poisoned! If we have a traitor on board, we better find him now! The obvious suspects are the cook and his assistant.",
    "803782": "Look for unusual elements in the kitchen",
    "803783": "After inspecting the kitchen carefully, the detective finds no evidence of guilt. \"Maybe we should analyze the whole chain, not simply the last link\". He opens the storage and among the amount of perfectly good supply, he notices that the porridge's cereals have a strange smell. Inspecting closer, opening a seed, he notices tiny worms going out of it. \"The food was not poisoned, the supplies went bad. The only blame we could give her is for negligence but certainly not murder.\" The crew is relieved to learn nobody acted malevolently. The cook and his assistant spend hours sorting the wheat from the chaff but it's a small concession for everybody safety.",
    "803784": "The detective finds nothing of substance but an element makes him suspicious. A half empty bottle labeled banana liquor smells nothing like it. ",
    "803785": "Analyze what remains of the bottle's content",
    "803786": "It smells more like bitter almond and further analyze show that it is cyanide! There is no more doubt, it is poisoning. The doctor has an idea. He asks both the cook and his assistant to meet with him, reassuring tone. \"You must be really shaken after this poor sailor death. But you shouldn't\"t beat yourself up, I am sure now certain the porridge didn't kill him. here, have a drink, relax a bit. It's a cocktail I learnt about a few weeks ago, rum and cherry liquor, a delight!\" He pours the rum and the content of the bottle into glasses and offer them to the two men. He observes their reaction. As the cook reaches for the glass without hesitation, the assistant winces. \"I ... I am not thirsty thank you.\" The doctor stops the cook from drinking and says, \"A shame, considering you will only get water and old bread from now on.\"",
    "803787": "The doctor has absolutely no idea what the bottle contains. It is not banana for sure, but it doesn't mean it is poison. It's part of the cook's supplies but it doesn't prove he is involved.",
    "803788": "Hold his head over the stove so he confesses what he knows",
    "803789": "He is held tightly, making it clear he cannot escape. As soon as his head comes close to the stove, the cook confesses immediately. Denounce his assistant who wanted to get revenge on the victim for mistreating him for months.",
    "803790": "Does not hold him correctly, a fight ensue above the heated stove. In the melee the cook finishes head first on the fire, burns half of his face, his skins melts. He dies and the truth with him.",
    "803791": "Give up",
    "803792": "\"We have neither proof of culpability or innocence.\" says the captain, \"It might well be that the victim was sick or had strong intolerance to what was in the porridge. I will therefore demand you to come back to your position and not speak of this again\". The suspicion remains high but nobody else dies.",
    "803793": "Grill the cook and his assistant to learn the truth",
    "803794": "By interrogating them separately, the cook assistant makes a mistake in his version of events, was trying to frame the cook for the murder in order to take his spot. He is tied up and put in the ship jail and awaits his trial.<br/>The crew is relieved but still resent the death of their comrade.",
    "803795": "All the facts are straight, or rather the diplomat fails to see the holes in the stories. Tension rises within the crew, the suspicion keeps the men on the edge and fights start to occur. The trail becomes thin and the crew patience shrinks.",
    "803796": "Favor denunciation",
    "803797": "\"If anybody knows anything, if you are protecting somebody who doesn't deserve to be protected, it is now time to come forward. There is no shame in reporting criminal. On the contrary, you are doing society a favor. If you come forward now, we will be merciful and forgive you for not speaking up earlier. But should we discover later than you knew all along, then you will share the murderer's fate.\" The diplomat speech has a strong effect. Sailors start to murmur between themselves when unexpectedly one of them comes forward \"I know who did it. I am sorry Jimmy but you can't get away with it\" he says as he turns toward the cook assistant. 'Jimmy wanted to punish Robert and Charles for mistreating him but he didn't realize the poison would be so strong it would kill them\". A murder is a murder, even if unvoluntary. Young Jimmy is seized and hanged. The crew is relieved the perpetrator has been found but sad to see a young man die for a stupid mistake. ",
    "803798": "\"Look at you, a pack of rats standing for each others. But I am certain you do not want to all be punished for the actions of only one of you. I am going to count until 10. If at 10 I don't have the name of a culprit, then I will withdraw the food for all of you!\" The diplomat was barely at 2 when the sailors start to accuse each others dispraisingly. They get to fist, a few sailors are wounded. No culprit is found and the rest of the trip is spent in suspicion.",
    "803799": "Give up",
    "803800": "\"We have neither proof of culpability or innocence.\" says the captain, \"It might well be that the victim was sick or had strong intolerance to what was in the porridge. I will therefore demand you to come back to your position and not speak of this again\". The suspicion remains high but nobody else dies.",
    "803801": "Find nothing. An accident? A murder? The crew spends the rest of the trip in suspicion and the truth is not uncovered.",
    "803802": "Analyze the body",
    "803803": "Examining his throat and stomach, it is clear that the sailor had an allergic reaction to the type of cereals used in the porridge. It is a regrettable accident but everybody is relieved to learn no murderer is on board.",
    "803804": "Considering the quickness of the death and the effects on the body, especially the stomach, ingested poison is a viable explanation but there is no certainty.",
    "803805": "Look through the cook and his assistant belongings",
    "803806": "Find a letter proving the assistant guilt, wanted to frame the cook for the murder to take his spot. He is locked on the ship and kept there until the end of the expedition so he can face a fair trial once back home. The men are relieved the threat is gone.",
    "803807": "The hunter finds no proof, the case is dropped. The captain, disappointed, announces \"We have neither proof of culpability or innocence. It might well be that the victim was sick or add strong intolerance to what was in the porridge. I will therefore demand you to come back to your position and not speak of this again\". The suspicion remains high but nobody else dies.",
    "803808": "Find nothing. An accident? A murder? The crew spends the rest of the trip in suspicion and the truth is not uncovered.",
    "803894": "An Arctic Welcome",
    "803895": "<b>The first severe blizzard.</b> You've only just caught sight of the Baffling Island littoral, when the headwind suddenly whips up and a dark fringe of cloud appears in the heavens. All take cover below deck, as rock-hard pellets of ice begin striking the ship with such force as to cause lasting damage. <b>There must be something that can be done to protect the ship,</b> but it'd take a hero to go back out into that.",
    "803896": "Send your best to take down the sails",
    "803897": "<b>Several worthy heroes step forward.</b> \"We'll do whatever it takes for this crew and this ship,\" says the burliest of them, before striding out into the storm. Undeterred by the howl and buffeting of the wind, they manage to put the sails 'in their gear' — loosing the sheetlines, and pulling the buntlines through, until the ship is safely running under jib alone. When the storm passes, the crew are delighted that <b>thanks to these mighty efforts, the ship has come through unscathed.</b>",
    "803898": "<b>Not easy handling sails at minus thirty,</b> and while those brave enough to take on the ice storm are strong enough, their labour is clumsy. As the snowblasted sails are loosened, your men allow them to catch a crosswind and suddenly they are off! Flapping wildly against a creaking mainmast, <b>the sails are threatening to rip half the ship away.</b>",
    "803899": "Cut the ropes holding the sails",
    "803900": "<b>Twang! The sails flap away into dark drifts of snow.</b> Your able-footed sailor reaches every rope without slipping, the snowflakes crowding his eyes unable to prevent the skillful execution of his art. When the sun rises the next day, the Arctic sky is still once more. <b>\"The mast is intact, and we've spare rope and sail,\" says the carpenter, \"we'll be all right.\"</b>",
    "803901": "<b>Your men cannot keep their footing</b> for the ice on deck, and the hard rocking of the ship gives them further excuse to lower their swords. They can only watch as, under the pull of the sails, the mainmast cracks open like grissini, the upper section cartwheeling out to sea, a tangle of rigging behind it. The crew are all accounted for, but<b> the damage to the ship</b> is probably irreparable.",
    "803902": "Let the blizzard do its worst",
    "803903": "<b>The mainmast takes much of the brunt,</b> whipped and contorted in every direction by the impassioned sails. When the storm and seizures finally end, <b>the carpenter tallies the cost of your inaction.</b> \"There's fissures in the mast. It may hold with enough resin... but then again, maybe not...\"",
    "803905": "<b>A bunch of wet lettuces.</b> They claim that the rigging is too slippery to grip. If these are your best sailors, Lord help the others, but those sails must come down — the ship is being blown towards some jagged silhouette! You can <b>grab something to aid their climb</b> or <b>get them up there quick.</b>",
    "803906": "Risk finding a climbing aid",
    "803907": "<b>At least no-one dies.</b> The crew raid stores for ropes and chains so as to climb the rigging safely, before stowing the sails away. The ship slows, but does not completely halt, colliding with that silhouette — a small and craggy island — and damaging the hull. <b>The crew have some lengthy repairs ahead of them.</b>",
    "803908": "<b>A disaster of their own fashioning.</b> Instead of finding a proper solution, the crew hurriedly don standard-issue gloves. The leather is so smooth in the palm, it is worse than climbing with no gloves at all. The ship lurches inexorably into that silhouette— a hideously craggy isle — and the impact flings the gripless riggers into the water. Visibility is so poor, and the water so cold, that <b>there's no hope of saving those who fell overboard.</b>",
    "803909": "Order the cowards up that mast, quick!",
    "803910": "<b>Filled with doubt, they do as instructed.</b> The conditions are dreadful, and they can barely see to work in the sideways slather, what with the waves buffeting the ship. A man falls from the upper rigging, and is found to be only loosely intact. \"What are you trying to prove?!\" bellows the navigator above the whine of the wind. Finally, the sails are put up and the boat can ride out the remainder of the storm without blowing off course. <b>Your crew are incensed at the coldness of their superiors.</b>",
    "803912": "Stay inside and pray",
    "803913": "<b>Faith and prudence.</b> Your sailors huddle below, rocked hard, but out of harm's way. They resist the temptation to attend to the creaking ship and its rudder, and instead trust their course to the divine. Soon the grog is flowing, with sailors playing cribbage, and all forget where they are. \"Hold! I hear no storm!\" a sailor says suddenly. The hatch is opened to reveal stillness and stars, and <b>a harlequin snake of an aurora, smiling down benevolent.</b>",
    "803914": "<b>Your sailors will not wait for God.</b> The storm shrieks its name, as sailors muttered frenzied supplications to the nameless. \"To hell and damn you all, I want to die living!\" the others bellow at them, and so unchained, they rush out into the white. Harsh commands can be heard above, before those voices fall silent. Somehow the ship rides out the storm, but <b>the bodies of your saviours are never found.</b>",
    "803915": "Save the propellers from the ice",
    "803917": "<b>You have a hardy legion indeed.</b> They rush to the tarpaulins, and with commendable teamwork and physical strength in the challenging conditions, are able to pull them over the ship's most sensitive instruments and machinery. Heading below deck to relax, <b>the heroes wait out the storm in luxury</b> with buttered currant buns and hot tea.",
    "803918": "<b>Their defence of the ship is a little half-hearted.</b> Initially the men show willing, but the blizzard quickly wears them down, and they retreat inside claiming that their work is done. After the worst of it has passed, the officers survey the ship. Beneath a poorly affixed and feeble tarpaulin, the engine is found flooded with slush that must now be cleared. <b>One has to wonder if they are cut out for these kinds of challenges.</b>",
    "803919": "<b>Tragic youthful over-exuberance.</b> Your sailors drain a bottle of strong rum before going back out, perhaps believing machismo will keep them warm. They batten the hatches in the white flurry, stumbling, belching and laughing. The hilarity continues when one of the lads slips and loses his feet — that is, until the steel rim of the funnel meets his head with a clomp. <b>He dies instantly.</b>",
    "803920": "Protect the steamship in any way you can",
    "803921": "<b>You have a hardy legion indeed.</b> They rush to the tarpaulins, and with commendable teamwork and physical strength in the challenging conditions, are able to pull them over the ship's most sensitive instruments and machinery. Heading below deck to relax, <b>the heroes wait out the storm in luxury</b> with buttered currant buns and hot tea.",
    "803922": "<b>Their defence of the steamship is a little half-hearted.</b> Initially the men show willing, but the blizzard quickly wears them down, and they retreat inside claiming that their work is done. After the worst of it has passed, the officers survey the ship. Beneath a poorly affixed and feeble tarpaulin, the engine is found to have suffered damage, albeit fixable. <b>One has to wonder if they are cut out for these kinds of challenges.</b>",
    "803923": "<b>Tragic youthful over-exuberance.</b> Your sailors drain a bottle of strong rum before going back out, perhaps believing machismo will keep them warm. They batten the hatches in the white flurry, stumbling, belching and laughing. The hilarity continues when one of the lads slips and loses his footing — that is, until the steel rim of the funnel meets his head with a clomp. <b>He dies instantly.</b>",
    "803924": "<b>\"Sir!\" cries the lookout, \"Dark shapes on the ridge!\"</b> A group climb the icy escarpment. At the top they find a companionable trio of driftwood boards plugged into three man-sized heaps of snow. Sunlight hits the scritchings in the wood: \"Sacred to the memory of Joseph Braine, who departed this life New Year's Day 1846 on board of H.M. Styx.\" The others named are \"John Gore\" and \"Francis Seeley.\" <b>Your men tremble at the idea of disturbing the graves.</b>",
    "803925": "Dig up the graves, no matter the crew's fears",
    "803926": "<b>The crew agree to draw lots.</b> A scrawny man gets the shovel, and clears the snow to reveal Braine's face, who might look asleep but for his skin of leather. In his pocket, there is a letter to his wife. <i><br/><font  overrideTextColor=\"true\" color='#695c4c'>\"Dearest Elaine,<br/> I've few breaths left. I die never having found the Passage — but then, no glory awaits any servant of Sir John. He was certain the ice would not thicken around us in the spring. The fate of the expedition now rests on circumnavigation of Terrier Island by short, perilous west shore, or by long, open east channel. I fear I know what Sir John will prefer. <br/>Farewell, my Elaine.\"</font></i>",
    "803927": "Search around the graves instead",
    "803928": "A mere hundred metres from the graves, <b>the men discover the remains of a camp</b> at which the lost expedition wintered. They built a cairn — a small stack of stones — under which a tin cylinder containing a tightly-rolled letter is found. \"They left a note of their progress,\" says the Captain. Lady Faithful recognises her husband's writing immediately.<br/><font  overrideTextColor=\"true\" color='#695c4c'><i>\"May 28th, 1847 { H.M. ships 'Styx' and 'Hades' wintered in the ice lat. 70˚ 05' N; long. 98˚ 23' W. Previously wintered in 1846-7 at Baffling Island, lat. 74˚ 43' 28\" N; long. 91˚ 39' 15\" W, after having sailed Wailing Channel to lat. 77˚, and returned by the west side of Cornell Island. Total loss by deaths to date: 3 men due to sickness — Braine, Gore and Seeley, God rest their souls. Leaving tomorrow for Terrier Island. Aim to reach Passage by end of June; we must be close now. John Faithful, Commander, HMS Styx.\"</i></font>",
    "803929": "Circle the island along the west coast",
    "803930": "Circle the island along the east coast",
    "803931": "It is late summer when the expedition reaches the Tchilling Sound, and yet <b>the conditions in these icy seas are already challenging.</b> The wind only has to pick up, and the men are tugging up their collars and tramping below deck. It seems hopeless to think Sir John Faithful's men could have lasted three winters here. Beyond Tchilling Sound, the seaway divides.<b> To the west</b> lies a chain of small islands separated by partially melted ice. <b>To the south</b>: a long, dark headland crowned with snow that hazes out of sight.",
    "803932": "Go West",
    "803933": "Go South",
    "803934": "As you near the coast, a large human construction delineates itself, <b>\"Most probably an abandoned trading post of the Huddlesome Bay company.\"</b> It leans hard into the wind, its once red boards now scoured pale. If Sir John and his crew came this way, they would likely have stopped here. \"How are we going to get there, sir?\" says the ship's boy. He has noticed that <b>an ice sheet lies between your ship and the trading post.</b>",
    "803935": "Take the safest route by avoiding the cracks",
    "803936": "<b>Your crew's instincts are solid.</b> Keeping just the right distance apart, they move at a purposeful speed, avoiding the cracks and dark splodges indicative of thinner ice. They reach the abandoned building without incident.",
    "803937": "<b>Their knowledge is shaky.</b> One of your groups avoids the gaping holes, but fails to notice the darker patches of thin ice. Cracking can be heard, but none of the group dare move. They hit the water with a woosh as the brûlée snaps. It is freezing, and they'll struggle to climb out on their own. <b>If not rescued quickly, they'll die of hypothermia.</b>",
    "803938": "Haul the sailors out with a rope",
    "803939": "<b>The rope team keep balance.</b> Lying down, and spreading out to distribute their weight, they throw ropes to those in the water, who thrash to bind themselves under their armpits. On a count of three, they are hoisted clear of the water. <b>Wet and chattering with cold,</b> your expedition takes refuge in the old trading post.",
    "803940": "Forget strength, <b>what they needed was teamwork.</b> The rope team disregard their own safety and pull as they would on dry land. The ice was never going to hold, and it soon collapses beneath them. Some manage to crawl free of the water and save themselves, but <b>others slip away</b> to fertilise the ocean bed. The survivors trudge for the thin comforts of the disused trading post.",
    "803941": "Offer some words of encouragement",
    "803942": "<b>They make it. They're okay!</b> The survivors are cheered across the line in a spirit akin to the finish of a cross-country race at school back home. Nobody left behind then, and nobody left behind now. <b>Wet and chattering with cold,</b> your expedition takes refuge in the abandoned building, offering up prayers of gratitude.",
    "803943": "To those in the water <b>the encouragement sounds noticeably strained.</b> Convulsing as they slip down between part-frozen cuboids, their resolve fades with the voices, the light above ever more distant. <b>Knowing they could have done more,</b> the survivors trudge on for the thin comforts of the disused trading post.",
    "803944": "Measure the thickness of the ice",
    "803945": "<b>The ship's carpenters improvise with a rotary drill.</b> It takes a fair bit of effort to get it turning, suggesting the ice is pretty solid. The first measurement is 11 inches — no hazard even for a sizeable group to pass over. Every few steps a new reading is taken, but it proves a mere formality, since the readings change very little. <b>They make the abandoned building without incident.</b>",
    "803946": "<b>It was never going to work,</b> using a heavy, blunt instrument to make the hole. Lucky as it happens that the carpenter is alone when his sledgehammer comes down, as it sunders the ice all about him and casts him into the freezing water. Turns out the ice is fairly thick, but that won't save the poor fellow now. The others trudge on for the thin comforts of the disused trading post in disbelief.",
    "803947": "Risk walking over it",
    "803949": "Resume the expedition under clearer skies...",
    "803950": "At the abandoned trading post...",
    "803951": "<b>\"At least it's a shelter,\"</b> the Captain remarks. The men shut the doors on the wind, to find the building interior licked with frost. Rusted hooks hang from the beams, relics of the short-lived fur trade. \"Comforts are few and far between out here. I doubt Sir John would have passed it by.\" <b>There must be some evidence of the lost expedition here.</b>",
    "803952": "Search for signs of recent use",
    "803953": "<b>No sign at all.</b> Undisturbed in ten years or more, these cabins are just as they were when the traders left. There should be prints in the dust, objects out of place, but there aren't. Everyone concedes <b>it is very unlikely Sir John's expedition came this way.</b>",
    "803954": "Find information about the local area",
    "803955": "<b>Something to go on at least.</b> Whoever the fur traders were, they left in a rush. Papers and maps are strewn about, some trodden and sodden into mush, a precious few dry and intact. Dockets are found relating to consignments received from a nearby Inuit settlement named Ivujivik, which also happens to be marked on a fragment of map. \"The Inuit are sure to have noticed anyone passing through,\" says the Captain, \"we should visit them.\"",
    "803956": "Go back and head west to Baffling Island",
    "803957": "Continue south toward the Inuit settlement of Ivujivik",
    "803958": "A Blizzard At Baffling Island",
    "803959": "Over The Ice To Huddlesome Bay",
    "803960": "The crew return to the ship. Once at Tchilling Sound, they head west.",
    "803961": "The crew mark the position of the Inuit settlement of Ivujivik on the map, and set sail.",
    "803962": "The route to the Inuit settlement of Ivujivik is <b>a two day trek by foot across exposed ice flats.</b> A small expedition party set off, leaving the rest at sea to await their return.<br/>Although the going is tough, it is not that which preoccupies the crew. <b>As night falls, they are sure something has been following them.</b>",
    "803963": "Stop for the night and keep watch",
    "803964": "<b>Your sharp-eared watchman keeps vigil.</b> In the small dark of the Arctic summer, he catches the scratch of a bear's unretractable claws on ice. It is trying to approach discretely, but the watchman is ready. At the sound of his gun the rest wake with a jolt, only to find a big dead bear at his feet. <b>They celebrate their trophy, and are soon back en route to Ivujivik.</b>",
    "803965": "<b>A mother polar bear!</b> Your watchman isn't used to such long days, struggling to keep his eyes open beside the hypnotic fire. A loud growl. Mother bear digs her claws deep into his spine and drags him away. <b>Moments later, she is back for more!</b>",
    "803966": "Organise and defend yourselves",
    "803967": "<b>Years of ambush drills pay off.</b> Quickly forming a circle, your men level their guns into the half-light. Sensing the danger they pose, mama bear grows more cautiously, and after a single circuit of your camp, disappears out of sight. <br/>Full of adrenaline, <b>your scout party reach the Inuit camp.</b>",
    "803968": "<b>Hands trembling with fear,</b> the men grab for their rifles, but mama bear smells their nerves and is upon them. Finally, someone gets a shot away, and though it misses, it scares her momentarily. Her white coat is lank with the blood of several men. Those still standing flee. The Inuit are startled when your party <b>arrive at Ivujivik the next afternoon looking especially bedraggled.</b>",
    "803969": "Use cunning to trick the bear",
    "803970": "<b>Your men know they have to stand tall</b> to face down a polar bear, and waving their coats above their heads like flags, they succeed in driving the bear away. Full of adrenaline, <b>your scout party reach the Inuit camp.</b>",
    "803971": "<b>Mama bear looks angry.</b> Your men had assumed that staring might make her back down, but she has taken it as a display of aggression. Her white coat is soon lank with the blood of several men. Those still standing flee. The Inuit are startled when your party <b>arrive at Ivujivik the next afternoon looking especially bedraggled.</b>",
    "803972": "Continue to walk despite being cold and exhausted",
    "803973": "<b>The men are strong and dedicated.</b> They tramp through the half hour of pitch-black darkness normally reserved for sleep, keeping good pace. Whatever was following them has soon given up. Gazing upwards, the party find themselves to be lucky observers of the aurora borealis. <br/><b>They reach the Inuit settlement the following lunchtime with a sense of wonder.</b>",
    "803974": "<b>One of the men struggles to keep up</b> with his unsympathetic comrades. He is the runt, the weakest of the pack, and the polar bear knows it. The rest of the group hear a piercing scream, followed by the sound of crunching and tearing. Moments later <b>mama bear is bounding across the snow towards them, hungry for more!</b>",
    "803975": "Nanuk's Way",
    "803976": "At the Inuit settlement...",
    "803977": "Ivujivik is a semi-permanent settlement. <b>The Inuit appear worried, but nevertheless offer your men every hospitality,</b> inviting them into a large iglu where they are served a hearty Suaasat— a meat stew— under the silent gaze of what feels like the whole village. A girl, Tapeesa, is able to translate, and the others warm up when they hear the story of your journey over the ice flats. Soon the subject turns to Sir John's lost expedition. <b>Tapeesa shows you items</b> that look like they belonged to the missing men.",
    "803978": "Offer to trade for the relics",
    "803979": "They were strange men. Who doesn't want to eat when they've been out in the cold...?",
    "803980": "<b>Silver cutlery embossed with the names Hades and Styx. These are from Sir John's expedition ships!</b> There are also cufflinks belonging to Sir John engraved with assorted marsupials, and a knife handle with the emblem of the Arctic council. Tapeesa says that about a year ago, some men came wanting to know about channels through the ice, and traded their things for information. <b>She points to the west coast of Terrier Island on your map.</b>",
    "803981": "Ask how they got hold of them",
    "803982": "<b>Tapeesa patiently explains</b> that they traded with men like yours about a year ago. The men wanted to know about channels through the ice, and traded their things for information. <b>She points to the west coast of Terrier Island on your map.</b>",
    "803983": "Accept Trade",
    "803984": "Decline, and ask how they got them.",
    "803985": "Nanuk's Way",
    "803986": "The route to the Inuit settlement is <b>a two day trek by foot across exposed ice flats.</b> A small expedition party set off, leaving the rest at sea to await their return.<br/>Although the going is tough, it is not that which preoccupies the crew. <b>As night falls, they are sure something has been following them.</b>",
    "803987": "Stop for the night and keep watch",
    "803988": "<b>Your sharp-eared watchman keeps vigil.</b> In the small dark of the Arctic summer, he catches the scratch of a bear's unretractable claws on ice. It is trying to approach discretely, but the watchman is ready. At the sound of his gun, the rest wake with a jolt, only to find a big dead bear at his feet. <b>They celebrate their trophy, and are soon back en route.</b>",
    "803989": "<b>A mother polar bear!</b> Your watchman isn't used to such long days, and is struggling to keep his eyes open beside the hypnotic fire. A loud growl, and mother bear's claws dig deep into his spine, as she drags him away. <b>Moments later, she's back for more!</b>",
    "803990": "Organise and defend yourselves",
    "803991": "<b>Years of ambush drills pay off.</b> Quickly forming a circle, your men level their guns into the half-light. Sensing the danger they pose, mama bear grows more cautious, and after a single circuit of your camp, disappears out of sight. <br/>Full of adrenaline, <b>your scout party reach the Inuit camp.</b>",
    "803992": "<b>Hands trembling with fear,</b> the men grab for their rifles, but mama bear smells their nerves and is upon them. Finally, someone gets a shot away, and though it misses, it scares her momentarily. Her white coat is lank with the blood of several men. Those still standing flee. The Inuit are startled when your party <b>arrive the next afternoon looking especially bedraggled.</b>",
    "803993": "Use cunning to trick the bear",
    "803994": "<b>Your men know they have to stand tall</b> to face down a polar bear, and waving their coats above their heads like flags, they succeed in driving the bear away. Full of adrenaline, <b>your scout party reaches the Inuit camp.</b>",
    "803995": "<b>Mama bear looks angry.</b> Your men had assumed that staring might make her back down, but she's taken it as a display of aggression. Her white coat is soon lank with the blood of several men. Those still standing flee. The Inuit are startled when your party <b>arrives the next afternoon looking especially bedraggled.</b>",
    "803996": "Continue to walk despite being cold and exhausted",
    "803997": "<b>The men are strong and dedicated.</b> They tramp through the half hour of pitch-black darkness normally reserved for sleep, keeping good pace. Whatever was following them has soon given up. Gazing upwards, the party find themselves to be lucky observers of the aurora borealis.<br/><b>They reach the Inuit settlement the following lunchtime with a sense of wonder. </b>",
    "803998": "<b>One of the men struggles to keep up</b> with his unsympathetic comrades. He is the runt, the weakest of the pack, and the polar bear knows it. The rest of the group hear a piercing scream, followed by the sound of crunching and tearing. Moments later <b>mama bear is bounding across the snow towards them, hungry for more!</b>",
    "803999": "Stranded Off Terrier Island",
    "804000": "<b>Your ship is stranded on an iceberg!</b> It is night along the east coast of Terrier Island. The meek light of your vessel seems to dissolve into the moonless blackness. Even at easy sail and under constant vigil, your ship runs the risk here, for slumbering ice giants leer from the darkness in all directions. \"Dead ahead!\" comes the cry, but it's too late! A low growl shakes the boat, as a wave dumps it atop a iceberg — in the shape of an upturned molar — beaching it there. The ship is undamaged, if only it could be returned to the water...",
    "804001": "Break free with dynamite",
    "804002": "<b>Nothing in nature can prevail against human endeavour,</b> it would seem. The crew watch with trepidation as the fuses burn down to the stick, before an ear-splitting series of detonations rings across the vastness, sundering the icy claws that had held your ship hostage. A small blizzard of debris blankets the deck, to the delight of all aboard, for they are free once more!",
    "804003": "Bombard the icy prison",
    "804004": "<b>Ice crumbles around such firepower.</b> Any cannon that can be swiveled at the target is put to use, chipping away at the icy dungeon in which the ship has become wedged, until the vessel breaks free. Like a cheerful sea lion, the fair vessel slips down an escarpment and plops back into the water. The crew cheer and continue on their way.",
    "804005": "<b>The iceberg fights back.</b> Though the way is almost clear, the relentless cannonfire seems to have woken the ogre below, and to the horror of the crew the vast iceberg rolls slightly to one side. Great shards of ice detach and bounce over the deck, injuring your men. <b>Quick action is needed.</b>",
    "804006": "Get out and push the ship free",
    "804007": "<b>Your men live for such challenges,</b> and scarcely need telling what to do. Leaping down from the boat, they get behind her, knotting guy ropes as fast as they can. The iceberg still rumbles ominously, but it is your quick-thinking crew who prevail. Once clear of the ice field, the crew will be able to treat their wounds.",
    "804008": "<b>It's an uphill struggle.</b> The pitching of the unstable iceberg does not help one jot, as the men tumble and slide as they struggle to find their grip. Such is the effort required to pull the ship successfully down from the iceberg into the sea, no-one notices that one of the teams is missing. It appears they have fallen through a thin part of the ice to their deaths.",
    "804009": "Let the rolling iceberg toss you into the sea.",
    "804010": "<b>Your ship performs a rather messy dismount.</b> After its initial roll, the iceberg halts long enough to suggest it wants to stay in its new position — but then everything happens all at once. The iceberg spins violently, and the ship with it! The ship strikes the water at such an angle that serious damage is done to much of the lee-side. Fortunately, the crew emerge unharmed.",
    "804011": "Build something to help you escape",
    "804012": "<b>The crew assembles a dozen hardy levers to free the ship.</b>  Flexible hickory planking is cut and reshaped into wedges, before being inserted into the ice at intervals of five paces, until they surround the stern. On a count of three the men lift — and to their surprise, so does the hull! Once it starts moving, there's no stopping it, and it clatters through all icy obstructions to the sea. Your sailors embrace — they have been very resourceful.",
    "804013": "<b>The wrong wood is selected for the task.</b> It is a decorative mahogany veneer, stripped from the Captain's cabin. \"Whatever it takes,\" the Captain says with laudable magnanimity, but the whole business is futile. Despite the wedges being placed in great number at the stern of the ship, no amount of pressure from the crew can encourage the ship to move, since the levers lack the requisite spring. They'll need to find another way off this iceberg.",
    "804014": "Search for Sir John along the east coast",
    "804015": "<b>Free of the iceberg,</b> the crew manage to circumvent Terrier Island via its easterly shore. However, they have found no trace of the lost expedition. You'll have to try the west coast, next.<br/>Sir John must have taken the risky option.",
    "804016": "The Narrows",
    "804017": "The west coast of Terrier Island is snaggled up with monstrous horns of ice. <b>Navigation is going to be tricky.</b> Will the narrows lead back once more to open water, or will your ship end up stuck? You can <b>navigate carefully</b>, <b>get a better view</b> of the channels from a nearby rock, or <b>send scouts ahead in rowboats</b> to see.",
    "804018": "Find a path through the narrows",
    "804019": "To their relief, <b>your crew reach the open sea on the other side.</b> As there is a lack of consensus on magnetic north at this time, your navigators decide to ignore the compasses and trust their instincts, saving them a collision on more than one occasion.<br/><br/>The crew enters King William Sound, a majestic carpet of water leading up to its seat, King William Island. <b>Sensing something, Lady Faithful suddenly emerges from below deck,</b> and voices the determined hopes of her heart...",
    "804020": "<b>The compass readings are confusing.</b> After several wrong turns, the crew realise magnetic north is not where they — or where anyone else imagined. Your ship finds itself alongside the run-off of a sizeable glacier, which, as it's spring, is melting. There are cracks, then an almighty rumble as <b>the entire wall of ice threatens to separate and topple into the water!</b>",
    "804021": "Full sail ahead!",
    "804022": "<b>Your crew escape!</b> In mere moments, the masts are dropped almost horizontal to catch every last ounce of wind, giving you just, <i>just</i> enough extra speed to avoid the mountain of ice that comes crashing down into the channel. Waves from this rare natural event form a new avenue, leading <b>out into the open sea</b>.<br/><br/>The crew enters King William Sound, a majestic carpet of water leading up to its seat, King William Island. <b>Sensing something, Lady Faithful suddenly emerges from below deck,</b> and voices the determined hopes of her heart...",
    "804023": "<b>Your crew escape!</b> The engine room takes the initiative ahead of the orders from the bridge and stoke the fires. The ship picks up just, <i>just</i> enough extra speed to avoid the mountain of ice crashing down into the channel. Waves from this rare natural event form a new avenue leading <b>out to the open sea</b>.<br/><br/>The crew enters King William Sound, a majestic carpet of water leading up to its seat, King William Island. <b>Sensing something, Lady Faithful suddenly emerges from below deck,</b> and voices the determined hopes of her heart...",
    "804024": "<b>Your navigators panic.</b> Though the sails catch the breeze, the men fail to adjust course out from under the falling wall. Blocks of ice the size of cows tumble onto the deck and explode to powder. <b>A death and several injuries result.</b> The rest are lucky that large waves from the icefall form a new avenue leading <b>out to the open sea</b>.<br/><br/>The crew enters King William Sound, a majestic carpet of water leading up to its seat, King William Island. <b>Sensing something, Lady Faithful suddenly emerges from below deck,</b> and voices the determined hopes of her heart...",
    "804025": "<b>They are too close to the falling ice wall.</b> Your engines are fired up but the resulting turn is not a sharp one. Blocks of ice the size of cows tumble onto the deck and explode to powder. <b>A death and several injuries result.</b> You are lucky that giant waves from the icefall form an avenue of escape <b>out to the open sea.</b><br/><br/>The crew enters King William Sound, a majestic carpet of water leading up to its seat, King William Island. <b>Sensing something, Lady Faithful suddenly emerges from below deck,</b> and voices the determined hopes of her heart...",
    "804026": "Full steam ahead!",
    "804027": "Brace for impact!",
    "804028": "<b>\"Ha! Let it rain!\"</b> the captain bellows, as blocks of ice the size of cows tumble onto the deck and explode to powder. <b>Your powerful vessel surges through to safety!</b> Waves from the icefall form a new avenue leading <b>out to the open sea.</b><br/><br/>The crew enters King William Sound, a majestic carpet of water leading up to its seat, King William Island. <b>Sensing something, Lady Faithful suddenly emerges from below deck,</b> and voices the determined hopes of her heart...",
    "804029": "<b>Your ship is no icebreaker.</b> There are cries as blocks of ice the size of cows tumble onto the deck and explode to powder. <b>A death and several injuries result.</b> You are lucky that giant waves from the icefall form an avenue of escape <b>out to the open sea.</b><br/><br/>The crew enters King William Sound, a majestic carpet of water leading up to its seat, King William Island. <b>Sensing something, Lady Faithful suddenly emerges from below deck,</b> and voices the determined hopes of her heart...",
    "804030": "Send men up the slope for a better view",
    "804031": "<b>The men are used to hard climbs like these</b> and are up in no time to survey the labyrinth ahead. They report back with an easy route forward that leads to open sea once more.<br/><br/>The crew enters King William Sound, a majestic carpet of water leading up to its seat, King William Island. <b>Sensing something, Lady Faithful suddenly emerges from below deck,</b> and voices the determined hopes of her heart...",
    "804032": "<b>Your men say the climb is too steep,</b> or at least, no-one is daredevil enough to attempt it with the limited equipment they have. <b>Everyone is exasperated. You must find another solution.</b>",
    "804033": "Send scouts ahead in rowboats to check",
    "804034": "<b>Follow the seals, that's the answer!</b> Seals and more besides. From their rowboats your scouts are even able to follow a baleen whale as she surfaces for air. She leads them to open water, and your expedition ship follows. <br/><br/>The crew enters King William Sound, a majestic carpet of water leading up to its seat, King William Island. <b>Sensing something, Lady Faithful suddenly emerges from below deck,</b> and voices the determined hopes of her heart...",
    "804035": "<b>No-one returns with a definitive clue.</b> \"Ivory gulls were circling above what looks like a large glacier,\" says one, \"it may lead us to open water...\" It's the best you've got, but soon your ship finds itself alongside the run-off of a sizeable glacier, which it being spring, is melting. There are cracks, then there is an almighty rumble as <b>the entire wall of ice threatens to separate and topple into the water!</b>",
    "804038": "The ship is now headed for the west coast of Terrier Island. The crew hope to find Sir John and his men soon, and pray no more obstacles will be thrown in their way.",
    "804039": "The ship is now headed for the east coast of Terrier Island. The crew hope to find Sir John and his men soon, and pray no more obstacles will be thrown in their way.",
    "804042": "Over the Ice",
    "804043": "As you near the coast, a large human construction delineates itself, <b>\"Most probably an abandoned trading post.\"</b> It leans hard into the wind, its once-red boards scoured pale. \"How are we getting there, sir?\" says the ship's boy. He has noticed that <b>an ice sheet lies between your ship and the trading post.</b>",
    "804044": "Take the safest route by avoiding the cracks",
    "804045": "<b>Your crew's instincts are solid.</b> Keeping just the right distance apart, they move at a purposeful speed, avoiding the cracks and dark splodges indicative of thinner ice. They reach the abandoned building without incident.",
    "804046": "<b>Their knowledge is shaky.</b> One of your groups avoids the gaping holes, but fails to notice the darker patches of thin ice. Cracking can be heard, but none of the group dare move. They hit the water with a woosh as the brûlée snaps. It is freezing, and they are struggling to climb out on their own. <b>If not rescued quickly, they'll die of hypothermia.</b>",
    "804047": "Haul the sailors out with a rope",
    "804048": "<b>The rope team keep balance.</b> Lying down, and spreading out to distribute their weight, they throw ropes to those in the water, who thrash to bind themselves under their armpits. On a count of three, they are hoisted clear of the water. <b>Wet and chattering with cold,</b> your expedition takes refuge in the old trading post.",
    "804049": "Forget strength, <b>what they needed was teamwork.</b> The rope team disregard their own safety and pull as they would on dry land. The ice was never going to hold, and it soon collapses beneath them. Some manage to crawl free of the water and save themselves, but <b>others slip away</b> to fertilise the ocean bed. The survivors trudge on for the thin comforts of the disused trading post.",
    "804050": "Offer some words of encouragement",
    "804051": "<b>They make it. They're okay!</b> The survivors are cheered across the line in a spirit akin to the finish of a cross-country race at school back home. Nobody left behind then, and nobody left behind now. <b>Wet and chattering with cold,</b> your expedition takes refuge in the abandoned building, offering up prayers of gratitude.",
    "804052": "To those in the water <b>the encouragement sounds noticeably strained.</b> Convulsing as they slip down between part-frozen cuboids, their resolve fades with their voices, the light above ever more distant. <b>Knowing they could have done more,</b> the survivors trudge on for the thin comforts of the disused trading post.",
    "804053": "Measure the thickness of the ice",
    "804054": "<b>The ship's carpenters improvise with a rotary drill.</b> It takes a fair bit of effort to get it turning, suggesting the ice is pretty solid. The first measurement is 11 inches — no hazard even for a sizeable group to pass over. Every few steps a new reading is taken, but it proves a mere formality, since the readings change very little. <b>They make the abandoned building without incident.</b>",
    "804055": "<b>It was never going to work,</b> using a heavy, blunt instrument to make the hole. Lucky as it happens that the carpenter is alone when his sledgehammer comes down, sundering the ice all about him and casting him into the freezing water. Turns out the ice is fairly thick, but that won't save the poor fellow now. The others trudge on for the thin comforts of the disused trading post in disbelief.",
    "804056": "Risk walking over it",
    "804060": "The Narrows",
    "804061": "The west coast of the island is snaggled up with monstrous horns of ice. <b>Navigation is going to be tricky.</b> Will the narrows lead back to open water once more, or will your ship end up stuck? You can <b>navigate carefully</b>, <b>get a better view</b> of the channels from a nearby rock, or <b>send scouts ahead in rowboats</b> to explore.",
    "804062": "Find a path through the narrows",
    "804063": "To their relief, <b>your crew find open sea on the other side.</b> As there is a lack of consensus on magnetic north at this time, your navigators decide to ignore the compasses and simply trust their instincts, saving them a collision on more than one occasion. The crew arrive at their destination safely.",
    "804064": "<b>The compass readings are confusing.</b> After several wrong turns, the crew realise magnetic north is not where they — or anyone else — imagined. Your ship finds itself alongside the run-off of a sizeable glacier, which with it being spring, is melting. There are cracks, then there is an almighty rumble as <b>the entire wall of ice threatens to separate and topple into the water!</b>",
    "804065": "Full sail ahead!",
    "804066": "Full steam ahead!",
    "804067": "<b>Your crew escape!</b> In mere moments, the masts are dropped almost horizontal to catch every last ounce of wind, giving you just, <i>just</i> enough extra speed to avoid the mountain of ice that comes crashing down into the channel. Waves from this rare natural event form a new avenue leading <b>out into the open sea</b>. The crew arrive at their destination.",
    "804068": "<b>Your crew escape!</b> The engine room takes the initiative ahead of orders from the bridge, and stokes the fires. To everyone's relief, the ship picks up just, <i>just</i> enough extra speed to avoid the mountain of ice that comes crashing down into the channel. Waves from this rare natural event form a new avenue leading <b>out into the open sea</b>. The crew arrive at their destination.",
    "804069": "<b>Your navigators panic.</b> Though the sails catch the breeze, the men fail to adjust their course away from the falling wall. Blocks of ice the size of cows tumble onto the deck and explode into powder. <b>A death, and several injuries result.</b> The rest are lucky that large waves from the icefall form a new avenue leading <b>out into the open sea</b>. The crew arrive at their destination.",
    "804070": "<b>They are too close to the falling ice wall!</b> Your engines are fired up, but the resulting turn is not a sharp one. Blocks of ice the size of cows tumble onto the deck and explode into powder. <b>A death, and several injuries result.</b> You're lucky that the giant waves from the icefall form an alternative avenue of escape <b>out into the open sea.</b> The crew arrive at their destination.",
    "804071": "Brace for impact!",
    "804072": "<b>\"Ha! Let it rain!\"</b> the Captain bellows, as blocks of ice the size of cows tumble onto the deck and explode into powder. <b>Your powerful vessel surges through to safety!</b> Handily, waves from the icefall carve a new avenue, leading <b>out into the open sea.</b> The crew arrive at their destination.",
    "804073": "<b>Your ship is no icebreaker.</b> There are cries as blocks of ice the size of cows tumble onto the deck and explode into powder. <b>A death, and several injuries result.</b> You're lucky that giant waves from the icefall carve an alternative avenue of escape <b>out into the open sea.</b> The crew arrive at their destination.",
    "804074": "Send men up the slope for a better view",
    "804075": "<b>The men are used to hard climbs like these</b>, and scale the rock in no time to survey the labyrinth ahead. They report back with an easy route forward that leads to the open sea once more. With a new path at hand, the crew soon arrive at their destination.",
    "804076": "<b>Your men say the climb is too steep,</b> or at least, no-one is daredevil enough to attempt it with the limited equipment they have. <b>Everyone is exasperated. You must find another solution.</b>",
    "804077": "Send scouts ahead in rowboats to check",
    "804078": "<b>Follow the seals, that's the answer!</b> Seals and more besides! From their rowboats, your scouts are even able to follow a baleen whale as she surfaces for air. She leads them into open water, and your expedition ship soon follows. Before long, the crew arrive at their destination.",
    "804079": "<b>No-one returns with a definitive clue.</b> \"Ivory gulls were circling above what looks like a large glacier,\" says one, \"It could lead us to open water...\" It's the best option you've got. Unfortunately, your ship soon finds itself alongside the run-off of a sizeable glacier, which with it being spring, is melting. There are cracks, then there is an almighty rumble as <b>the entire wall of ice threatens to separate and topple into the water!</b>",
    "804080": "<b>It is clumsy.</b> Out of breath and struggling weakly against a strong current, your divers bludgeon blindly at the coral, sending clouds of particles up through the water. Little do they realise how fragile the hull has become. With one misplaced blow, it implodes, and the water comes gushing in. The crew must count themselves lucky that the tide proceeds to sweep the unhappy vessel to the shore. <b>It seems you have shipwrecked on a coral atoll.</b>",
    "804081": "Send in your specialist diver",
    "804082": "<b>Your diver takes to the sea like a fish to water,</b> having ample experience. Still, the others worry when after five or six minutes, he still has yet to surface. Suddenly, the boat begins to wobble — it has been cut free! Soon after, your hero emerges from the water giddy and glistening — and brandishing some magnificent coral in their hands.",
    "804083": "<b>The accident with the coral reef as left the expedition shipwrecked on an atoll.</b> For a time your crew feel like children again — dancing along the sand and bathing in the sun, as they await a verdict on the damaged hull. When it comes, the news is not good: an extensive repair is needed, and with supplies so short, there is considerable disagreement. Why <b>concentrate on repairs</b>, given how long that may take, when <b>you could scout for food and water.</b>",
    "804084": "The Coral Island",
    "804091": "Map Event A",
    "804092": "Choose direction to search",
    "804094": "go north",
    "804096": "Choose direction to search 2",
    "804098": "go north 2",
    "804099": "go south 2",
    "804100": "Choose direction to search 2",
    "804101": "go north 3",
    "804102": "go south 3",
    "804103": "go south",
    "804104": "Choose direction to search 2",
    "804105": "go north 4",
    "804106": "go south 4",
    "804107": "Choose direction to search 2",
    "804108": "go north 5",
    "804109": "go south 5",
    "804110": "Map Event B",
    "804111": "Choose location to search",
    "804112": "beach",
    "804113": "Choose direction to search 2",
    "804115": "go left",
    "804116": "go right",
    "804117": "river",
    "804118": "Choose direction to search 2",
    "804119": "forest",
    "804120": "village",
    "804121": "Search on other side of island",
    "804122": "Found it!",
    "804138": "Huddlesome Bay Trading Post",
    "804139": "Ivujivik",
    "804141": "<b>The first severe blizzard.</b> You've only just caught sight of the Baffling Island littoral when the headwind suddenly whips up, and a dark fringe of cloud appears in the heavens. All take cover below deck, as rock-hard pellets of ice begin to pelt the ship with such force as to cause lasting damage. <b>\"We've lost control of her,\" screams the navigator,</b> but it'd take a hero to go back out into that.",
    "804142": "Terrier Island (East)",
    "804143": "<b>The thrill-seeking diver relishes the task.</b> Covering themselves in bear fat and brandishing a sharp pick, they enter the water without a splash, resurfacing no more than five minutes later to the embrace of a pre-warmed towel. \"All clear!\" your diver says. <b>Cheers go up below at the sound of the engines at full power once more.</b>",
    "804144": "Send an expert diver to unclog the propellers of ice",
    "804145": "Send an expert diver to unclog the propellers of ice",
    "804146": "<b>The thrill-seeking diver relishes the task.</b> Covering themselves in bear fat and brandishing a sharp pick, they enter the water without a splash, resurfacing no more than five minutes later to the embrace of a pre-warmed towel. \"All clear!\" your diver says. <b>Cheers go up below at the sound of the engines at full power once more.</b>",
    "804147": "Baffling Island",
    "804148": "Huddlesome Bay",
    "804149": "Baffling Island",
    "804150": "Terrier Island (West)",
    "804151": "Ivujivik",
    "1010540": "Small Trading Post",
    "4100010": "The Anarchist",
    "10000003": "Press [GamepadActionManager GamepadActionTooltip(CameraNavigateToKontorOrNextOfSelection)] to jump back to your trading post<br />(Deselect any building or ship first)",
    "10000020": "Press [GamepadActionManager GamepadActionTooltip(SuperButtonPress)] to switch ship stance",
    "10000021": "Press [GamepadActionManager GamepadActionTooltip(SuperButtonPress)] to switch fleet stance",
    "10000024": "New Savegame",
    "10000038": "Taking the Wheel",
    "10000039": "Move With the Times",
    "10000046": "Faster than Flight",
    "10000047": "Third Time's the Charm",
    "10000049": "Copy Tool",
    "10000050": "Quick Navigation Map",
    "10000051": "Quick Navigation Map - Teleport",
    "10000052": "Contextual Commands",
    "10000053": "Contextual Commands Reminder",
    "10000055": "The <b>copy tool</b> can be a powerful helper! You can use it to <b>copy entire districts</b>, e.g. a Marketplace and the residences and streets surrounding it.",
    "10000056": "Open the Region Map. Here, you will find a detailed overview of the whole region.",
    "10000057": "From here, you can instantly teleport to any location on the map.",
    "10000058": "The<b>Tools menu</b> includes helpful contextual commands. They will appear at the top, <b>adapting to any building you select</b>. Try it out on a Farm, a Residence or a Ship!",
    "10000059": "Remember that the <b>Tools menu</b> contains <b>useful contextual commands that will appear at the top</b>! If you open the Tools Menu while hovering over a Warehouse, you can directly upgrade it.",
    "10000060": "Now that you have discovered a new region, you will need to switch between regions every once in a while. Open the Region Map to switch.",
    "10000061": "Switch between regions by using the tabs at the top...",
    "10000063": "Aarhant encourages you to familiarize yourself with the controls.",
    "10000064": "Aarhant is happy you now know the basics of how to get around.",
    "10000065": "Hannah wants you to try to increase the game's speed.",
    "10000066": "Hannah teaches you a few tricks that help you navigate more quickly.",
    "10000067": "Hannah wants you to remember what she taught you about quick navigation.",
    "10000068": "Press [GamepadActionManager GamepadActionTooltip(TargetManagerPrimaryActionPress)] while hovering over your ship to select it, then press [GamepadActionManager GamepadActionTooltip(TargetManagerSecondaryActionPress)] to send it to the targeted location.",
    "10000069": "Use [GamepadActionManager GamepadButtonTooltip(Dpad_all)] to target the dynamite on your ship. Then press [GamepadActionManager GamepadActionTooltip(ShipOMActivateItem)] to detonate it.",
    "10000070": "With your ship selected, press [GamepadActionManager GamepadActionTooltip(TargetManagerSecondaryActionPress)] while hovering over the fish to pick them up.",
    "10000071": "Once your <b>farmers' needs are completely satisfied</b> you will be able to <b>promote them to workers</b>. Choose the <b>Upgrade tool</b> and apply it to <b>a residence that is ready</b>.",
    "10000085": "Destroy the enemy's ships with military ships. You can find them by accessing the Quest Tracker and pressing [GamepadActionManager GamepadActionTooltip(JumpToQuestLocation)].",
    "10000086": "Bring a ship to the requested location. You can find it by accessing the Quest Tracker and pressing [GamepadActionManager GamepadActionTooltip(JumpToQuestLocation)].",
}

skips_to_add = [
    "803688",
    "803948",
    "804057",
]

# Load to_translate_batch.json to verify we covered all keys
with open(os.path.join(handoff, "to_translate_batch.json"), "r", encoding="utf-8") as f:
    batch = json.load(f)

# Sanity Check
all_covered_keys = set(trans.keys()).union(set(skips_to_add))
batch_keys = set(batch.keys())

missing_in_our_code = batch_keys - all_covered_keys
extra_in_our_code = all_covered_keys - batch_keys

print(f"Batch size: {len(batch)}")
print(f"Translated in our code: {len(trans)}")
print(f"Skipped in our code: {len(skips_to_add)}")
print(f"Total covered: {len(all_covered_keys)}")

if missing_in_our_code:
    print(f"CRITICAL ERROR: Keys missing in our code: {missing_in_our_code}")
if extra_in_our_code:
    print(f"CRITICAL ERROR: Extra keys in our code: {extra_in_our_code}")

if not missing_in_our_code and not extra_in_our_code:
    print("Verification passed! Writing outputs...")
    
    # Save trans_part_1.json
    out_path = os.path.join(handoff, "trans_part_1.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(trans, f, ensure_ascii=False, indent=0)
    
    # Update skip.json
    skip_path = os.path.join(handoff, "skip.json")
    if os.path.exists(skip_path):
        with open(skip_path, "r", encoding="utf-8") as f:
            skips = json.load(f)
    else:
        skips = []
        
    skips.extend(skips_to_add)
    # Sort and remove duplicates
    skips = sorted(list(set(skips)), key=lambda x: int(x))
    
    with open(skip_path, "w", encoding="utf-8") as f:
        json.dump(skips, f, ensure_ascii=False, indent=0)
        
    print("Files updated successfully!")
else:
    print("Verification failed! Not writing files.")
