import json
import os

batch = json.load(open("to_translate_batch.json", encoding="utf-8"))

skips_to_add = []

mapping = {
    "Donny commands his lawyer to sue Theodora.": "דוני מורה לעורך הדין שלו לתבוע את תיאודורה.",
    "Of course, it’s just... well, before boarding the cruise, I misplaced my briefcase. And the papers you requested...they're in there...": "כמובן, זה פשוט... ובכן, לפני העלייה לשיט, איבדתי את תיק המסמכים שלי. והמסמכים שביקשת... הם שם בפנים...",
    "Mr. Brokeman claims he misplaced the all-important suitcase.": "מר ברוקמן טוען שהוא איבד את המזוודה החשובה מכל.",
    "Misplaced? Astounding, I should commission a study on the adverse effects of holidays on worker morale. My partner will find your briefcase no doubt. In the meantime, start writing the complaint!": "איבדת? מדהים, אני צריך להזמין מחקר על ההשפעות השליליות של חופשות על מורל העובדים. השותף שלי ימצא את תיק המסמכים שלך ללא ספק. בינתיים, התחל לכתוב את הקובלנה!",
    "Donny wants you to find Mr. Brokeman’s suitcase.": "דוני רוצה שתמצא את המזוודה של מר ברוקמן.",
    "Catastrophe. Mr. Brokeman was right to be worried, Bader had him watched. They finally got to him and now he’s gone and revealed our plans...": "קטסטרופה. מר ברוקמן צדק כשהוא דאג, ביידר עקב אחריו. הם סוף סוף הגיעו אליו ועכשיו הוא הלך וחשף את התוכניות שלנו...",
    "Theodora says Mr. Bader has sadly uncovered your plans.": "תיאודורה אומרת שמר ביידר חשף לצערנו את התוכניות שלכם.",
    "Ah, I see you too uncovered what Miss Jenny and my lawyer were working on in secret—  new patents without my consent! But the money’s spent... so, development may as well conclude now!": "אה, אני רואה שגם אתה גילית על מה מיס ג'ני ועורך הדין שלי עבדו בסתר — פטנטים חדשים ללא הסכמתי! אבל הכסף כבר הושקע... אז מן הראוי שהפיתוח יסתיים כעת!",
    "I doubt it will make a splash, but I might get some compensation in marginal profits. The rest I’ll collect by means of a lawsuit against Miss Jenny via Mr. Brokeman.": "אני בספק אם זה יעשה רעש גדול, אבל אולי אקבל פיצוי כלשהו ברווחים שוליים. את השאר אגבה באמצעות תביעה משפטית נגד מיס ג'ני דרך מר ברוקמן.",
    "Donny plans to complete Theodora's patent anyway.": "דוני מתכנן להשלים את הפטנט של תיאודורה בכל מקרה.",
    "Donny intends to file a lawsuit aginst Theodora.": "דוני מתכוון להגיש תביעה משפטית נגד תיאודורה.",
    "Brokeman's Documents": "המסמכים של ברוקמן",
    "Find Mr. Brokeman's documents in [Area Area([Conditions QuestArea]) CityName]": "מצא את המסמכים של מר ברוקמן ב-[Area Area([Conditions QuestArea]) CityName]",
    "<i>Hint: he left his suitcase at the harbour before boarding a cruise ship</i>": "<i>רמז: הוא השאיר את המזוודה שלו בנמל לפני העלייה לספינת תענוגות</i>",
    "Mr. Brokeman, Donald's lawyer, left his suitcase behind before boarding a cruise ship. You'll likely find it at the harbour.": "מר ברוקמן, עורך הדין של דונלד, השאיר את המזוודה שלו מאחור לפני שעלה לספינת תענוגות. סביר להניח שתמצא אותה בנמל.",
    "Seeing as his money has already been spent on the research, Mr. Bader has decided that he might as well try and finalise the product. He intends to recoup any monetary loss by having Mr. Brokeman issue a brutal lawsuit against his employee, Miss Jenny. To file the suit, you first have to prove your loyalty to Bader by locating Mr. Brokeman’s briefcase, which contains the necessary documents.": "מאחר שכספו כבר הושקע במחקר, מר ביידר החליט שעדיף לנסות ולהשלים את המוצר. הוא מתכוון להחזיר את ההפסד הכספי על ידי כך שמר ברוקמן יגיש תביעה משפטית אכזרית נגד העובדת שלו, מיס ג'ני. כדי להגיש את התביעה, תחילה עליך להוכיח את נאמנותך לביידר על ידי איתור תיק המסמכים של מר ברוקמן, המכיל את המסמכים הדרושים.",
    "Splendid! Mr. Brokeman can finally earn his wages. Miss Jenny will be notified of the hearing arrangements.": "נפלא! מר ברוקמן יכול סוף סוף להרוויח את לחמו. למיס ג'ני תימסר הודעה על סידורי השימוע.",
    "Donny thanks you for prepping his lawsuit.": "דוני מודה לך על הכנת התביעה המשפטית שלו.",
    "We settled out of court. Miss Jenny could not afford a lawsuit. She’s agreed to forego her vacation and work overtime on our patents! This should make up for the time we lost to her bid at independence.": "הגענו להסדר מחוץ לכותלי בית המשפט. מיס ג'ני לא יכלה להרשות לעצמה תביעה משפטית. היא הסכימה לוותר על החופשה שלה ולעבוד שעות נוספות על הפטנטים שלנו! זה אמור לפצות על הזמן שאיבדנו בגלל הניסיון שלה לעצמאות.",
    "Donny says Theodora has to work overtime to pay him back.": "דוני אומר שתיאודורה חייבת לעבוד שעות נוספות כדי להחזיר לו את החוב.",
    "Donny believes the shopping arcade plan is back on track.": "דוני מאמין שתוכנית פסז' הקניות חזרה למסלול.",
    "Yes, this is how a business should be run— I lead, everyone else follows! I'm the one with the nose for profit!": "כן, כך צריך לנהל עסק — אני מוביל, כל השאר בעקבותיי! אני זה שיש לו חוש לרווחים!",
    "Reward Patent": "פטנט פרס",
    "Lose Island": "להפסיד את האי",
    "Lose Lab": "להפסיד את המעבדה",
    "Internal Use": "שימוש פנימי",
    "Skyline Tower:<br />Foundations": "מגדל קו הרקיע:<br />יסודות",
    "Skyline Tower:<br />First Storeys": "מגדל קו הרקיע:<br />קומות ראשונות",
    "Globe Statue": "פסל הגלובוס",
    "A global statue for a worldly city.": "פסל גלובוס לעיר קוסמופוליטית.",
    "If anything, my expectations have sky-rocketed!": "אם כבר, הציפיות שלי הרקיעו שחקים!",
    "Left high and dry! Outrageous!": "נשארתי תלוי באוויר! שערורייה!",
    "This house of cards is about to topple!": "בית הקלפים הזה עומד לקרוס!",
    "Skyscrapers, a colossal failure!": "גורדי שחקים, כישלון קולוסאלי!",
    "Are everyone's heads up in the sodding clouds?!": "האם הראשים של כולם נמצאים בעננים הארורים?!",
    "The hubris of constructing such towers!": "היהירות שבבניית מגדלים שכאלה!",
    "So high, and yet so low-down and dirty.": "כל כך גבוה, ועדיין כל כך נמוך ומלוכלך.",
    "We're facing a brick wall at the moment.": "אנחנו עומדים מול קיר אטום כרגע.",
    "This whole skyscraper idea seems on the verge of collapse.": "כל רעיון גורדי השחקים הזה נראה על סף קריסה.",
    "A high rise, only with low standards.": "בנייה לגובה, רק עם סטנדרטים נמוכים.",
    "I should be up in the clouds right now...": "הייתי צריך להיות בעננים עכשיו...",
    "High rises seem to be a work in progress.": "נראה שבניית גורדי שחקים היא עבודה בתהליך.",
    "There is some headroom yet to match my expectations.": "יש עוד מרווח מסוים כדי לענות על הציפיות שלי.",
    "The view from up here is bearable.": "הנוף מכאן למעלה נסבל.",
    "I thought it might be a bit less boring up here.": "חשבתי שיהיה קצת פחות משעמם כאן למעלה.",
    "The tower is still standing at least.": "המגדל עדיין עומד לפחות.",
    "Worth the steep investment.": "שווה את ההשקעה הגבוהה.",
    "High risk, high dividend.": "סיכון גבוה, דיבידנד גבוה.",
    "Buy low and sell high.": "לקנות בזול ולמכור ביוקר.",
    "On the up and up again!": "בעלייה מתמדת שוב!",
    "I must concede, it is a step upwards.": "אני חייב להודות, זה צעד כלפי מעלה.",
    "Why think of heaven, when I've offices like these?": "למה לחשוב על גן עדן, כשיש לי משרדים כאלה?",
    "Ah! This really is the high life.": "אה! אלו באמת החיים הטובים.",
    "Like a king in one's castle.": "כמו מלך בטירתו שלו.",
    "To the elevator!?": "אל המעלית!?",
    "Get out while you still can!": "צא החוצה כל עוד אתה יכול!",
    "I wish the wretched windows opened on this floor...": "הלוואי שהחלונות הארורים היו נפתחים בקומה הזו...",
    "Rarified air...I thought...above the smog...I thought...": "אוויר דליל... חשבתי... מעל הערפיח... חשבתי...",
    "Consider my investment withheld!": "ראה את ההשקעה שלי כמעוכבת!",
    "In case you were wondering, this comes right from the very top!": "אם תהיתם, זה מגיע ישר מלמעלה!",
    "Stellar timing! I was just about to give into the temptation of an afternoon sip on the roof, but now that you're here, let's call it a meeting shall we?": "תזמון מעולה! בדיוק עמדתי להיכנע לפיתוי של לגימה של אחר הצהריים על הגג, אבל עכשיו כשאתה כאן, בוא נקרא לזה פגישה, טוב?",
    "Assiduous as always? I too am rather swamped with work. You know how it is, money won't move itself around.": "חרוץ כמו תמיד? גם אני די מוצף בעבודה. אתה יודע איך זה, הכסף לא יעביר את עצמו.",
    "You must come across your fair share of tiresome people? Freeman is heralding a bear market again, but you and I know, a 10% decline is no true bear. The bull will come charging back!": "אתה בטח נתקל בלא מעט אנשים מעייפים? פרימן שוב מכריז על שוק דובי, אבל אתה ואני יודעים שירידה של 10% היא לא דוב אמיתי. השוק השורי עוד יחזור להסתער!",
    "Know why my investments are so profitable? I follow two simple rules. One: when investing I don't lose. And two: I never disobey the first rule.": "יודע למה ההשקעות שלי כל כך רווחיות? אני פועל לפי שני כללים פשוטים. אחד: כשאני משקיע אני לא מפסיד. ושניים: אני אף פעם לא מפר את הכלל הראשון.",
    "A unique tower demands unique expectations.": "מגדל ייחודי דורש ציפיות ייחודיות.",
    "The Skyline Tower is the height of shame!": "מגדל קו הרקיע הוא שיא הבושה!",
    "A towering disaster!": "אסון אדיר!",
    "...and I forfeit funds for this calamity! Conned!": "...ואני מוותר על כספים בשביל האסון הזה! רימו אותי!",
    "This? The apex of engineering? Balder-dilly-dash-balls!": "זה? פסגת ההנדסה? קישקוש בלבוש!",
    "This is a faulty tower!": "זהו מגדל פגום!",
    "I've been having to take the stairs.": "נאלצתי לעלות במדרגות.",
    "The scale of the build-up is proportional to the let down.": "קנה המידה של הציפייה יחסית לגודל האכזבה.",
    "This all feels like a sizeable mistake.": "כל זה מרגיש כמו טעות גדולה למדי.",
    "Here I am, stuck up a mountain with a Yeti.": "הנה אני, תקוע על הר עם יטי.",
    "Skyline Tower? Skydive!": "מגדל קו הרקיע? צניחה חופשית!",
    "Capacious, but empty.": "מרווח, אך ריק.",
    "It is higher than others, but is it better?": "הוא גבוה יותר מאחרים, אבל האם הוא טוב יותר?",
    "So many windows, and little to see.": "כל כך הרבה חלונות, וכל כך מעט מה לראות.",
    "For a supposedly unique building it is rather unremarkable.": "עבור מבנה שאמור להיות ייחודי, הוא די רגיל.",
    "If I find it only satisfactory, imagine the poor chuffs on the ground floor.": "אם אני מוצא אותו רק משביע רצון, תאר לעצמך את המסכנים שבקומת הקרקע.",
    "Society's grafters are up in the rafters.": "אנשי העמל של החברה נמצאים גבוה למעלה.",
    "Just like old Skyline, I've always been a head above the rest.": "בדיוק כמו קו הרקיע הישן, תמיד הייתי בראש אחד מעל השאר.",
    "The Skyline Tower is getting top billing.": "מגדל קו הרקיע זוכה לפרסום ראשי.",
    "Blue-chip, blue sky, if you're one of the Skyline brigade.": "מניות בטוחות, שמיים כחולים, אם אתה חלק מחבורת קו הרקיע.",
    "Boredom is rare, now we have a little Skyline luxury.": "שיעמום הוא נדיר כעת, כשיש לנו קצת מיוקרת קו הרקיע.",
    "There's no-one that isn't looking up to me now. Except birds, perhaps.": "אין אף אחד שלא נושא אליי עיניים כעת. מלבד הציפורים, אולי.",
    "Daddy's little place up on Mount Olymp.": "המקום הקטן של אבא למעלה על הר אולימפוס.",
    "I've risen to the top...the absolute top. All that's left is to stay there now...": "עליתי לפסגה... הפסגה המוחלטת. כל מה שנותר כעת הוא להישאר שם...",
    "A towering inferno!": "מלכודת אש נישאת!",
    "We have flown too close to the sun!": "עפנו קרוב מדי לשמש!",
    "It's those unwashed window monkeys, spreading disease through the glass.": "אלו מנקי החלונות הלא שטופים האלה, שמפיצים מחלות דרך הזכוכית.",
    "Close the boardroom doors! Stop the commotion and the gawking! I am owed my rest!": "סגרו את דלתות חדר הישיבות! הפסיקו את המהומה ואת המבטים הבוהים! מגיעה לי מנוחה!",
    "The board will suffer your baroque misconduct no longer!": "הדירקטוריון לא יסבול עוד את התנהגותך הפסולה והמוזרה!",
    "This tower is the capstone of your failings, I refuse to parley! Speak only to my lawyer!": "מגדל זה הוא גולת הכותרת של כישלונותיך, אני מסרב לדון בדבר! דבר רק עם עורך הדין שלי!",
    "The View? Sterling! I spy my house in the countryside, the little veranda, the dogs, gazebo three.": "הנוף? נהדר! אני מבחין בביתי שבכפר, במרפסת הקטנה, בכלבים, בסוכה השלישית.",
    "Here's a spot of advice. Anticipating people's needs is impractical - unpredictable as stocks - convince them they are in need what you have on offer. Let the money come to you.": "הנה עצה קטנה. צפיית הצרכים של אנשים אינה מעשית — בלתי צפויה כמו מניות — שכנע אותם שהם זקוקים למה שיש לך להציע. תן לכסף לבוא אליך.",
    "I heard of a chap, raving about a mile-high skyscraper he plans to construct, but something tells me the record of the Skyline Tower will be safe for quite some time yet!": "שמעתי על בחור אחד שמדבר בהתלהבות על גורד שחקים בגובה מייל שהוא מתכנן לבנות, אבל משהו אומר לי שהשיא של מגדל קו הרקיע יישאר בטוח לעוד די הרבה זמן!",
    "Care to join me for cognac out on the skydeck? Although, mind you, that pesky elevator might be out of order again, so you may have to slum it up the stairs...": "רוצה להצטרף אליי לקוניאק במרפסת התצפית? למרות שקח בחשבון שהמעלית המציקה הזו עלולה להיות מקולקלת שוב, אז אולי תצטרך לכתת רגליים במדרגות...",
    "My hypothesis predicts that the 'high life' will suit me— I've always been squirreled away in attics.": "ההשערה שלי צופה ש'החיים הטובים' יתאימו לי — תמיד הייתי סגור בעליות גג.",
    "A source of extreme vertigo!": "מקור לוורטיגו חמור!",
    "Don't for a moment imagine ivory towers...": "אל תדמיין לרגע מגדלי שן...",
    "The foundations of something are there...": "היסודות למשהו נמצאים שם...",
    "To this tower is come an influx of great minds.": "למגדל זה מגיעה זרימה של מוחות גדולים.",
    "An ivory tower without the ivory, it's fairly near perfect.": "מגדל שן ללא השן, זה כמעט מושלם.",
    "Quickly, form an orderly queue by the fire escapes!": "במהירות, צרו תור מסודר ליד מדרגות החירום!",
    "This tower is very densely populated, the spread must be contained!": "מגדל זה מאוכלס בצפיפות רבה, יש לבלום את ההתפשטות!",
    "Since we were crammed into towers, our discontent has spiked!": "מאז שנדחסנו לתוך מגדלים, חוסר שביעות הרצון שלנו הרקיע שחקים!",
    "There you go, coffee with milk— I use powdered. Sugar is over there - oh! careful! it's the one on the left. To the right is Lead acetate. Sweet, but toxic.": "בבקשה, קפה עם חלב — אני משתמש באבקת חלב. הסוכר נמצא שם — או! זהירות! זה שמשמאל. מימין זה עופרת אצטט. מתוק, אך רעיל.",
    "Teetering on the brink!": "מתנדנד על פי תהום!",
    "Integrity is failing! I predict complete collapse!": "היציבות המבנית קורסת! אני חוזה התמוטטות מוחלטת!",
    "All that optimism comes crashing down!": "כל האופטימיות הזו קורסת ברעש גדול!",
    "Someone has pulled the cut-off switch on us up here.": "מישהו משך את מתג הניתוק שלנו כאן למעלה.",
    "Height provides no innate additive value to my research.": "הגובה אינו מספק ערך מוסף מולד למחקר שלי.",
    "This tower is quantifiably deficient.": "מגדל זה לוקה בחסר באופן מדיד.",
    "My concerns require concrete solutions.": "החששות שלי דורשים פתרונות קונקרטיים.",
    "This building is an echo chamber.": "הבניין הזה הוא תיבת תהודה.",
    "Our peer review shows this construction to have room for further refinement.": "ביקורת העמיתים שלנו מראה שבבנייה הזו יש מקום לשיפור נוסף.",
    "I have identified a number of small tower issues I would like to raise.": "זיהיתי מספר בעיות קטנות במגדל שאשמח להעלות.",
    "I have revised and annotated a version of the skyscraper blueprints.": "עדכנתי והוספתי הערות לגרסה של שרטוטי גורד השחקים.",
    "I don't consider myself especially needy, not compared to the investors in any case...": "אני לא מחשיב את עצמי כנזקק במיוחד, בכל אופן לא בהשוואה למשקיעים...",
    "No glass ceiling to obstruct me from fulfilling my potential.": "אין תקרת זכוכית שתמנע ממני לממש את הפוטנציאל שלי.",
    "I have been having elevated thoughts.": "היו לי מחשבות נעלות.",
    "I am experiencing a heightened sense of productivity.": "אני חווה תחושה מוגברת של פריון.",
    "Breathtaking— yet the altitude hasn't dented my brain power one bit.": "עוצר נשימה — ועדיין הגובה לא פגע בכוח המוח שלי אפילו במעט.",
    "Another summit of ingenuity for our species!": "פסגת תושייה נוספת עבור המין שלנו!",
    "The story of the engineering behind tall structures is fascinating, I quite recommend it.": "סיפור ההנדסה שמאחורי מבנים גבוהים הוא מרתק, אני די ממליץ עליו.",
    "No, never ever the elevator! Always the stairs!": "לא, בחיים לא במעלית! תמיד במדרגות!",
    "Open-plan offices increase the efficiency of viruses too...": "משרדים בחלל פתוח מגבירים גם את היעילות של וירוסים...",
    "The pressure will only build unless you make concessions to our demands!": "הלחץ רק יגבר אלא אם כן תעשה ויתורים לדרישותינו!",
    "Yes, I am often transported to unexpected floors too...I am presently working on a equation that will calculate the elevator's sequence of priority, and roundtrip time, based on traffic.": "כן, גם אותי מסיעים לעיתים קרובות לקומות לא צפויות... אני עובד כרגע על משוואה שתחשב את סדר העדיפויות של המעלית, ואת זמן הנסיעה הלוך ושוב, בהתבסס על עומס התנועה.",
    "Are you aware that a typical skyscraper fire escape suffers many shortcomings? I have prepared a 'fire shute' concept I mean to share with architects and those ethical persons of business.": "האם אתה מועד לכך שמדרגות חירום טיפוסיות בגורד שחקים סובלות מחסרונות רבים? הכנתי קונספט של 'מגלשת אש' שבכוונתי לשתף עם אדריכלים ואנשי עסקים מוסריים.",
    "Have you considered any alternative names for the skyscraper? The term could be easily confused, since the appellation formerly indicated especially tall horses, ship's masts and ladies' bonnets.": "האם שקלת שמות חלופיים לגורד השחקים? המונח עלול לגרום לבלבול בקלות, מכיוון שהכינוי ציין בעבר סוסים גבוהים במיוחד, תרני ספינות וכובעי נשים.",
    "Shopping Arcade": "פסז' קניות",
    "How can the people enjoy the delights of arcadia without a road?": "כיצד יכולים האנשים ליהנות מתענוגות ארקדיה ללא כביש?",
    "I thought it might be nice to lay a small road to the shopping arcade?": "חשבתי שיהיה נחמד לסלול כביש קטן לפסז' הקניות?",
    "Of course shopping off the beaten track is wonderful...": "כמובן שקניות מחוץ למסלול הרגיל הן דבר נפלא...",
    "Please, peruse! It's like a museum to craft, but you can take things home!": "בבקשה, עיינו! זה כמו מוזיאון למלאכת יד, אבל אפשר לקחת את הדברים הביתה!",
    "The arts and crafts movement can be the consolidation of practical and decorative, behold!": "תנועת האמנויות והאומנויות יכולה להיות איחוד של השימושי והקישוטי, ראו בעצמכם!",
    "I must ask you not to touch if you do not intend to purchase.": "אני חייב לבקש ממך לא לגעת אם אין בכוונתך לרכוש.",
    "Certain components of our vacuums are handmade you know...": "חלקים מסוימים משואבי האבק שלנו מיוצרים בעבודת יד, אתה יודע...",
    "Keep the body afloat so the mind may create.": "שמור על הגוף פעיל כדי שהמוח יוכל ליצור.",
    "Welcome to the Drug-Store. We are happy to hear your complaints.": "ברוכים הבאים לבית המרקחת. נשמח לשמוע את תלונותיכם.",
    "A tincture for all nature's little blemishes!": "טינקטורה לכל הפגמים הקטנים של הטבע!",
    "Come, cover your eyes with cucumber and your face with cream.": "בואו, כסו את עיניכם במלפפון ואת פניכם בקרם.",
    "Pull up a chair, make yourself at home.": "משוך כיסא, תרגיש בבית.",
    "Soft surroundings and myriad movables!": "סביבה רכה ואינספור חפצים ניידים!",
    "Yes! Please do take a seat!": "כן! בבקשה שב!",
    "Admittedly, some of our furnishings may divide people...": "יש להודות שחלק מהרהיטים שלנו עשויים לחלק את דעותיהם של אנשים...",
    "I sincerely apologize, for we are currently closed.": "אני מתנצל מעומק הלב, שכן אנו סגורים כעת.",
    "The arcade will throw open its doors to patrons again tout suite.": "הפסז' יפתח את דלתותיו שוב ללקוחות במהירות.",
    "Oh! We're closed for refurbishment presently.": "אנו סגורים לרגל שיפוצים כעת.",
    "Candle-light flickers in carpenter's grottoes once more! The arcade is open again!": "אור הנרות מהבהב שוב במערות הנגרים! הפסז' פתוח שוב!",
    "Ah yes, there's the wonderful chime of the cash register.": "אח כן, הנה הצלצול הנפלא של קופת הרושמת.",
    "Then, my life among the aisles and shelves must resume!": "אם כן, חיי בין המעברים והמדפים חייבים להתחדש!",
    "Close the arcade?": "לסגור את הפסז'?",
    "Yes, you're right, enough of social interaction!": "כן, אתה צודק, מספיק עם אינטראקציה חברתית!",
    "They seem to be closing down the arcades everywhere.": "נראה שסוגרים את הפסז'ים בכל מקום.",
    "The wooden shelving is alight!": "מדפי העץ עולים באש!",
    "Fire is sweeping the arcade!": "אש מתפשטת בפסז'!",
    "A malady creeps through the arcade! Bar the doors! Stop the spread!": "מחלה מתגנבת דרך הפסז'! חסמו את הדלתות! עצרו את ההתפשטות!",
    "It can only be the consumption!": "זו יכולה להיות רק השחפת!",
    "Down with consumerism! Restore what is beautiful!": "הלאה הצרכנות! השיבו את מה שיפה!",
    "We are the shop front! We are the shop front!": "אנחנו חלון הראווה! אנחנו חלון הראווה!",
    "Capable hands are low in stock.": "ידיים מוכשרות חסרות במלאי.",
    "Just some willing to arrange the bouquets here and there.": "רק כמה אנשים שמוכנים לסדר את הזרים פה ושם.",
    "Mam', I regret to inform you, this product appears to be out of stock.": "גברתי, אני מצטער להודיע לך, נראה שהמוצר הזה אזל מהמלאי.",
    "Between empty shelves I see customers wandering, searching, yearning!": "בין מדפים ריקים אני רואה לקוחות מסתובבים, מחפשים, משתוקקים!",
    "Oh, can it be as tedious as a warehouse?": "אוי, האם זה יכול להיות משעמם כמו מחסן?",
    "We await a delivery from a non-existent warehouse.": "אנחנו מחכים למשלוח ממחסן לא קיים.",
    "Women shopping in the arcades is the first bud of liberation. To purchase a good is to take ownership, after all.": "נשים שעורכות קניות בפסז'ים הן הניצן הראשון של השחרור. אחרי הכל, לרכוש סחורה פירושו לקחת בעלות.",
    "Not at all— I relish inquiring what our customers truly seek. Toasters, yes, but what lies beyond that base craving for a crisp slice of bread?": "כלל לא — אני נהנה לברר מה הלקוחות שלנו באמת מחפשים. מצנמים, כן, אבל מה מסתתר מעבר לתשוקה הבסיסית הזו לפרוסת לחם פריכה?",
    "I ponder, do Arcades influence our perception of the self? Are we less what we do and more what we own? Do we consume these goods or do they consume us? Um...would you like a bag?": "אני תוהה, האם פסז'ים משפיעים על תפיסת העצמי שלנו? האם אנחנו פחות מה שאנחנו עושים ויותר מה שבבעלותנו? האם אנחנו צורכים את הסחורות האלה או שהן צורכות אותנו? אממ... תרצה שקית?",
    "Browsing is the finest part! The way our wares present themselves is everything— we take great care— and besides once you've paid, all virtue in them dies.": "השיטוט הוא החלק הטוב ביותר! הדרך שבה המוצרים שלנו מציגים את עצמם היא הכל — אנחנו מקפידים מאוד — ומלבד זאת, ברגע ששילמת, כל הסגולה שבהם נעלמת.",
    "Would you like a sample treatment? Although, I must preface the long-term side-effects are not within our purview.": "האם תרצה טיפול להתנסות? אם כי, עליי להקדים ולומר שהתופעות הלוואי לטווח הארוך אינן בתחום אחריותנו.",
    "Have you seen the traveling elixir show? A lovely lie turns snake oil into a miracle cure. The crowd was wooed, but I was struck – Am I the same? Dressing tinctures in empty promises.": "ראית את מופע השיקויים הנודד? שקר יפה הופך שמן נחשים לתרופת פלא. הקהל נכבש בקסמיו, אך אני נותרתי המום — האם אני אותו הדבר? מלביש טינקטורות בהבטחות ריקות.",
    "One ensures a pale complexion, the other adds a vibrant flush of colour. A dichotomy, but a healthy mind can withstand dissonance.": "האחד מבטיח גוון עור חיוור, השני מוסיף סומק חי של צבע. דיכוטומיה, אך מוח בריא יכול לעמוד בדיסוננס.",
    "Consider bartering. Our Products, unused, are inert but when applied produce a chemical reaction – by virtue of the user they come alive, thus the price should vary.": "שקול סחר חליפין. המוצרים שלנו, כשאינם בשימוש, הם אדישים אך כאשר מורחים אותם הם מייצרים תגובה כימית — בזכות המשתמש הם קמים לתחייה, ולכן המחיר צריך להשתנות.",
    "It is a wonder. In a single building we have created a multitude of faux habitats. A Livingroom here, an office yonder, and a bedroom over there. None of them lived in, but all of them, so convincing!": "זה פלא. בבניין אחד יצרנו שפע של סביבות מחיה מדומות. סלון פה, משרד שם, וחדר שינה שם. באף אחד מהם לא מתגוררים, אבל כולם כל כך משכנעים!",
    "Homemaking is a primal act – vulnerable beings seeking shelter from a hostile world – but what of aesthetics? Is the abode our refuge for the corporeal and beauty our refuge for the soul?": "הקמת בית היא אקט ראשוני — יצורים פגיעים המחפשים מחסה מפני עולם עוין — אך מה לגבי אסתטיקה? האם המעון הוא המקלט שלנו לגוף והיופי הוא המקלט שלנו לנפש?",
    "I’ve taken to decorating the store – look, there’s flowers in the lounge! A beautiful vase is it not?... in my home all fragile things end in shards. There lurks a black furred monster when I am gone.": "התחלתי לקשט את החנות — תראה, יש פרחים בטרקלין! כד יפהפה, הלא כן?... בביתי כל הדברים השבירים מסיימים כרסיסים. שם אורבת מפלצת בעלת פרווה שחורה כשאני לא נמצא.",
    "I can assure you the comfort and luxury of our furnishings is sublime. I'm forever having to dislodge customers falling asleep upon our lounge collection.": "אני יכול להבטיח לך שהנוחות והיוקרה של הרהיטים שלנו הם נשגבים. אני כל הזמן נאלץ להעיר לקוחות שנרדמים על קולקציית הסלונים שלנו.",
    "These wares are made equal in darkness.": "הסחורות הללו הופכות שוות בחשכה.",
    "Without electricity the arcade is as like a wolf without lungs.": "ללא חשמל, הפסז' הוא כמו זאב ללא ריאות.",
    "While my mind feeds on ideas, these shelves do not.": "בזמן שהמוח שלי ניזון מרעיונות, המדפים הללו אינם עושים זאת.",
    "An empty arcade fulfills no purpose.": "פסז' ריק אינו משרת שום מטרה.",
    "Customers are seeking goods, but we have naught to offer.": "לקוחות מחפשים סחורות, אך אין לנו דבר להציע.",
    "A dandy choice!": "בחירה מצוינת!",
    "This is sure to please many customers.": "זה בטוח ישמח לקוחות רבים.",
    "A fine piece of craftsmanship.": "יצירת אומנות משובחת.",
    "Deliver to Miss Jenny:<br/>[Conditions QuestCondition Amount(ObjectiveIndex)]t [AssetData([Conditions QuestCondition DeliveryObject(ObjectiveIndex)]) Text]": "מסור למיס ג'ני:<br/>[Conditions QuestCondition Amount(ObjectiveIndex)] טונות של [AssetData([Conditions QuestCondition DeliveryObject(ObjectiveIndex)]) Text]",
    "Parts Catalogue": "קטלוג חלקים",
    "Craft Catalogue": "קטלוג מלאכה",
    "Oh good, are those my oils?": "אוי יופי, אלו השמנים שלי?",
    "Theodora asks if you have her materials.": "תיאודורה שואלת אם יש לך את החומרים שלה.",
    "Deliver to Miss Jenny:": "מסור למיס ג'ני:",
    "1/ There is this issue for triggering the quests that I told you about yesterday</br>2/ Another issue: factory productivity objective does not resolve. Quest 136102</br>3/ Another issue: This quest 136230 starts 3 triggers, to emulate a scene and characters moving and talking.</br>The second character never spawns (Trigger 136257), and at the time where he should spawn, I got that strange assert canceling the fake quest (it shouldn't end there)</br></br></br> </br></br> </br>4/ Photo quest 136264 for obscure reasons refuses to show me the picture I took, quest is blocked due to that (must be an issue in my parameters?? )</br>5/ Sadly making an object walk to another one in an ActionMoveObject works, but NOT when the target is a pool of assets. Hence I can't make the engineer walk towards the harbor... Could we have this?</br>6/ I had an issue yesterday, in questline 1, that the decision quest started in Cape Trelawney while quests 1 and 3 started in Old World. I think that we had a similar issue in tourist that we fixed. I'll investigate once I'll have time, but in case you know something...<br /><br />Add spawning to quest_marker_0 in the hunt for the saboter (harbor + mall), trigger to verify that a mall exists (furniture), else fall back or spawn at the end of previous quest, fix lab issue": "1/ ישנה בעיה זו בהפעלת המשימות שסיפרתי לך עליה אתמול</br>2/ בעיה נוספת: יעד פריון המפעל אינו נפתר. משימה 136102</br>3/ בעיה נוספת: משימה 136230 זו מפעילה 3 טריגרים, כדי לדמות סצנה ודמויות שזזות ומדברות.</br>הדמות השנייה אינה מופיעה מעולם (טריגר 136257), ובזמן שבו היא אמורה להופיע, קיבלתי את ה-assert המוזר ההוא שמבטל את משימת הדמה (זה לא אמור להסתיים שם)</br></br></br> </br></br> </br>4/ משימת צילום 136264 מסיבות לא ברורות מסרבת להראות לי את התמונה שצילמתי, המשימה חסומה בגלל זה (בטח יש בעיה בפרמטרים שלי?? )</br>5/ לצערי לגרום לאובייקט ללכת לאובייקט אחר ב-ActionMoveObject עובד, אך לא כאשר היעד הוא מאגר של נכסים. לכן אני לא יכול לגרום למהנדס ללכת לכיוון הנמל... האם נוכל לקבל את זה?</br>6/ הייתה לי בעיה אתמול, בשרשרת משימות 1, שמשימת ההחלטה התחילה בקייפ טרלוני בעוד שמשימות 1 ו-3 התחילו בעולם הישן. אני חושב שהייתה לנו בעיה דומה בתיירים שתיקנו. אחקור ברגע שיהיה לי זמן, אבל במקרה שאתה יודע משהו...<br /><br />הוסף הופעה ל-quest_marker_0 במצוד אחר המחבל (נמל + קניון), טריגר לאימות שקיים קניון (רהיטים), אחרת חזור לאחור או הופע בסוף המשימה הקודמת, תקן את בעיית המעבדה",
    "Hey guru, look at the skyline we shaped— what’s missing? A massive tower to shame the rest! The suckers will call it hubris, and we’ll be spitting on their heads from the top.": "היי גורו, תסתכל על קו הרקיע שעיצבנו — מה חסר? מגדל ענק שיבייש את כל השאר! הפראיירים יקראו לזה יהירות, ואנחנו נירק להם על הראש מלמעלה.",
    "Donny asks you to lay the foundations for the Skyline Tower.": "דוני מבקש ממך להניח את היסודות למגדל קו הרקיע.",
    "Place the Skyline Tower foundations:<br />Phase 1/4": "הנח את יסודות מגדל קו הרקיע:<br />שלב 1/4",
    "Build the Skyline Tower in [Area Area([Conditions QuestArea]) CityName]:<br />Phase 2/4": "בנה את מגדל קו הרקיע ב-[Area Area([Conditions QuestArea]) CityName]:<br />שלב 2/4",
    "Continue building the Skyline Tower in [Area Area([Conditions QuestArea]) CityName]:<br />Phase 3/4": "המשך בבניית מגדל קו הרקיע ב-[Area Area([Conditions QuestArea]) CityName]:<br />שלב 3/4",
    "Finish building the Skyline Tower in [Area Area([Conditions QuestArea]) CityName]:<br />Phase 4/4": "סים את בניית מגדל קו הרקיע ב-[Area Area([Conditions QuestArea]) CityName]:<br />שלב 4/4",
    "Residents blocking progress": "תושבים חוסמים את ההתקדמות",
    "Stupendous! Oh, the envy they'll feel – let’s get it done, faster the better!": "עצום! אוי, הקנאה שהם ירגישו — בואו נעשה את זה, וכמה שיותר מהר יותר טוב!",
    "My Tower! Unfinished and already dominating the skyline! Once built they’ll be looking up at it and chanting our names!": "המגדל שלי! לא גמור וכבר שולט בקו הרקיע! ברגע שייבנה הם יישאו אליו עיניים וישירו את שמותינו!",
    "At last, my tower stands! The true gold standard! Let the fools try and surpass it, it’ll be real fun watching them fail. Oh what a legacy!": "סוף סוף, המגדל שלי עומד! תקן הזהב האמיתי! שיתנו לטיפשים לנסות ולעבור אותו, יהיה ממש כיף לראות אותם נכשלים. אוי, איזו מורשת!",
    "Donny is excited to see the Skyline Tower progressing.": "דוני נרגש לראות את מגדל קו הרקיע מתקדם.",
    "Donny drools over your progress on the Skyline Tower.": "דוני מרייר על ההתקדמות שלך במגדל קו הרקיע.",
    "Donny is in awe of the completed Skyline Tower.": "דוני נפעם ממגדל קו הרקיע המושלם.",
    "The success of the Galeria Baderette Shopping Arcade has set a precedent for the future of consumerism — a founding myth for a new era, its daring promise of endless growth exemplified by rising sales and towering skyscrapers. To ensure his place in history, Donald Bader dreams of a unique monument: the gigantic Skyline Tower. And he has entrusted you with making it a reality.": "הצלחת פסז' הקניות גלריית ביידרט היוותה תקדים לעתיד הצרכנות — מיתוס מכונן לעידן חדש, הבטחתו הנועזת לצמיחה אינסופית המגולמת בעליית המכירות ובגורדי שחקים נישאים. כדי להבטיח את מקומו בהיסטוריה, דונלד ביידר חולם על מונומנט ייחודי: מגדל קו הרקיע הענק. והוא הפקיד בידיך את המשימה להפוך אותו למציאות.",
    "Choose one of your islands and place the Skyline Tower's foundation on it, then proceed with the construction phases that follow.": "בחר באחד האיים שלך והנח עליו את יסודות מגדל קו הרקיע, ולאחר מכן המשך בשלבי הבנייה הבאים.",
    "Another weird note. This one landed on my desk —someone’s gonna answer for that — care to see what trash they came up with this time?": "עוד פתק מוזר. הפתק הזה נחת על שולחני — מישהו הולך לתת על זה את הדין — רוצה לראות איזה זבל הם המציאו הפעם?",
    "Well, this is getting to be darn annoying. Keep an eye on my tower, will you?": "ובכן, זה מתחיל להיות מעצבן לעזאזל. שים עין על המגדל שלי, טוב?",
    "Donny shares another portentous note with you.": "דוני משתף איתך עוד פתק מבשר רעות.",
    "Donny is growing worried about the warnings he's been receiving.": "דוני מתחיל לדאוג מהאזהרות שהוא מקבל.",
    "<font size=\"21\"><b>Beware!</b></font><br /><br /><br /><i>\"Your Majesty looked, and there before you stood a large statue...<br />The head of the statue was made of pure gold, its chest and arms of silver, its belly and thighs of bronze, and its feet of baked clay.\"</i> Daniel 2:31-33<br /><br /><br /><b> Come, Mr. Bader, note the popular feeling against your abominable construction practices, and make a change!</b>": "<font size=\"21\"><b>היזהר!</b></font><br /><br /><br /><i>\"אתה המלך ראית והנה פסל גדול עומד לפניך...<br />ראשו של הפסל היה עשוי זהב טהור, חזהו וזרועותיו כסף, בטנו וירכיו ברונזה, ורגליו מחרס אפוי.\"</i> דניאל ב:31-33<br /><br /><br /><b> בחייך, מר ביידר, שים לב לרגשות הציבור נגד שיטות הבנייה המתועבות שלך, ועשה שינוי!</b>",
    "Too late for record time, but at least we’ll still smash the height record.": "מאוחר מדי לזמן שיא, אבל לפחות עדיין נשבור את שיא הגובה.",
    "An Hour already!? Just wrap it up, will you? I hate waiting!": "שעה כבר!? פשוט תסיים עם זה, טוב? אני שונא לחכות!",
    "This should have been a sprint not a damn crawl. Maybe I bet on the wrong horse.": "זה היה צריך להיות ריצה מהירה ולא זחילה ארורה. אולי הימרתי על הסוס הלא נכון.",
    "Donny says you missed his optimistic construction deadline.": "דוני אומר שפספסת את מועד הבנייה האופטימי שלו.",
    "Donny is disappointed at how much time the construction is taking.": "דוני מאוכזב מכמה זמן שהבנייה אורכת.",
    "Donny is disappointed you missed all his construction deadlines.": "דוני מאוכזב מכך שפספסת את כל מועדי הבנייה שלו.",
    "No-one wants to climb the tower": "אף אחד לא רוצה לטפס על המגדל",
    "Fear of falling": "פחד מנפילה",
    "Skyline Tower: Vertigo": "מגדל קו הרקיע: ורטיגו",
    "Some of the workers are scared of heights. What in God's name did they expect? This stunt is wasting us money, any ideas?": "חלק מהפועלים פוחדים מגבהים. למה בשם אלוהים הם ציפו? התעלול הזה מבזבז לנו כסף, יש רעיונות?",
    "Donny asks you to reassure the anxious workers, somehow.": "דוני מבקש ממך להרגיע את הפועלים החרדים, איכשהו.",
    "What damn risk assessment? No Miss Jenny. Why go out of your mind looking for problems when there are none!?": "איזו הערכת סיכונים ארורה? לא, מיס ג'ני. למה לצאת מהדעת ולחפש בעיות כשאין כאלה!?",
    "With the expected height of the Skyline Tower, we must assume that any hazards will be of proportional magnitude. A risk assessment is vital in helping us react should anything happen.": "עם הגובה הצפוי של מגדל קו הרקיע, עלינו להניח שכל סכנה תהיה בממדים יחסיים. הערכת סיכונים היא חיונית כדי לעזור לנו להגיב אם משהו יקרה.",
    "Theodora advises you that a proper risk assessment is needed.": "תיאודורה ממליצה לך שדרושה הערכת סיכונים נאותה.",
    "Donny turns a blind eye to the potential risks.": "דוני מעלים עין מהסיכונים הפוטנציאליים.",
    "Marie-Louise Carême, Chef de Cuisine": "מארי-לואיז קארם, שפית ראשית",
    "Sous-Chef": "סו-שף",
    "Entremetier": "אנטרמטייה",
    "As ruler of the kitchen kingdom, she knows there’s much more to fine cooking than good taste alone.": "כמלכת ממלכת המטבח, היא יודעת שבישול משובח דורש הרבה יותר מאשר טעם טוב לבדו.",
    "Every chef needs a capable second.": "כל שף זקוק לסגן מוכשר.",
    "“Sir, an extra side of fries with the fish?”": "“אדוני, תוספת של צ'יפס עם הדג?”",
    "With the construction of the Skyline Tower underway, some of the workers have expressed a fear of heights. Mr. Bader wishes to avoid construction delays, and has asked you to knock some sense into them.": "כאשר בניית מגדל קו הרקיע בעיצומה, חלק מהפועלים הביעו פחד מגבהים. מר ביידר מעוניין להימנע מעיכובי בנייה, וביקש ממך להכניס בהם קצת שכל.",
    "Reassure the workers": "להרגיע את הפועלים",
    "On Island": "על האי",
    "He sees and hears all, knowing and keeping the many secrets of his guests.": "הוא רואה ושומע הכל, יודע ושומר את הסודות הרבים של אורחיו.",
    "Mr. Bertram, Hotel Manager": "מר ברטרם, מנהל המלון",
    "Look, it’s not like we ain’t used to the heights — we are, <i>more</i> than most — but that means we know how dangerous it can get. One mis-step can change everything... This tower, it’s higher than we’ve ever built. <br /><br />And that brand logo... it's unlucky — it's spreading fear! We don’t need a reminder of it plastered on the walls... All it takes is one fall...": "תשמע, זה לא שאנחנו לא רגילים לגבהים — אנחנו כן, <i>יותר</i> מרוב האנשים — אבל זה אומר שאנחנו יודעים כמה זה יכול להיות מסוכן. צעד אחד שגוי יכול לשנות הכל... המגדל הזה גבוה יותר מכל מה שבנינו אי פעם. <br /><br />והלוגו של המותג הזה... הוא מביא מזל רע — הוא מפיץ פחד! אנחנו לא צריכים שכל הקירות יהיו מכוסים בתזכורת שלו... כל מה שצריך זה נפילה אחת...",
    "Send a <b>bishop</b> to reassure them ([AssetData(137498) Text])": "שלח <b>בישוף</b> כדי להרגיע אותם ([AssetData(137498) Text])",
    "Promise to find daredevil <b>volunteers</b> in the city.": "הבטח למצוא <b>מתנדבים</b> נועזים בעיר.",
    "Provide <b>harnesses</b> for all (Pay <img height=\'24\' width=\'24\' src=\"[AssetData(1010255) Icon]\"/>[AssetData(137505) Text] [AssetData(1010255) Text]. Current amount: <img height=\'24\' width=\'24\' src=\"[AssetData(1010255) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010255) >> storagegood])": "ספק <b>רתמות</b> לכולם (שלם <img height=\'24\' width=\'24\' src=\"[AssetData(1010255) Icon]\"/>[AssetData(137505) Text] [AssetData(1010255) Text]. כמות נוכחית: <img height=\'24\' width=\'24\' src=\"[AssetData(1010255) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010255) >> storagegood])",
    "<b>Ignore</b> their concerns (-5 <img height=\'24\' width=\'24\' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text] for 30 minutes. Current <img height=\'24\' width=\'24\' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text]: [Area Area([Conditions QuestArea]) Happiness AverageHappinessByPopulation(15000001) >> happiness])": "<b>התעלם</b> מהחששות שלהם (-5 <img height=\'24\' width=\'24\' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text] למשך 30 דקות. נוכחי <img height=\'24\' width=\'24\' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text]: [Area Area([Conditions QuestArea]) Happiness AverageHappinessByPopulation(15000001) >> happiness])",
    "Answer Locked": "התשובה נעולה",
    "Unlock Precondition": "תנאי מקדים לפתיחה",
    "Unlocked": "פתוח",
    "Requires The Passage DLC": "דורש את ה-DLC The Passage",
    "Requires Land of Lions DLC": "דורש את ה-DLC Land of Lions",
    "Madame Blanc, Maître d'hôtel": "מאדאם בלאן, מנהלת המלון (Maître d'hôtel)",
    "She assures all that no guest will ever witness when things go wrong.": "היא מבטיחה לכולם שאף אורח לא יהיה עד לכך שהדברים משתבשים.",
    "Concierge": "קונסיירז'",
    "The first face every guest will see.": "הפנים הראשונות שכל אורח יראה.",
    "Tutorial — Higher and Higher, Baby": "הדרכה — גבוה יותר ויותר, בייבי",
    "Upgrade to Level 2 Skyscraper:": "שדרג לגורד שחקים ברמה 2:",
    "Engineer Skyscraper 0/1": "גורד שחקים של מהנדסים 0/1",
    "Investor Skyscraper 0/1": "גורד שחקים של משקיעים 0/1",
    "The investor suggests building even taller skyscrapers.": "המשקיע מציע לבנות גורדי שחקים גבוהים עוד יותר.",
    "So, what next?— Surely you weren’t about to stop here? These skyscrapers can go even higher, and if they can, they should!": "אז מה הלאה? — בטח לא התכוונת לעצור כאן? גורדי השחקים האלה יכולים להגיע אפילו גבוה יותר, ואם הם יכולים, הם צריכים!",
    "Up to you how and where these towers grow, just make 'em grow real high. I can smell your ambition!": "זה תלוי בך איך ואיפה המגדלים האלה יצמחו, רק תגרום להם לגדול ממש גבוה. אני יכול להריח את השאיפה שלך!",
    "The investor admires your swift progress.": "המשקיע מעריך את ההתקדמות המהירה שלך.",
    "Hand-Pollination Method": "שיטת האבקה ידנית",
    "You've built first level skyscrapers, but why stop there? Donald wants you to go even higher!": "בנית גורדי שחקים ברמה הראשונה, אבל למה לעצור שם? דונלד רוצה שתעלה אפילו גבוה יותר!",
    "As soon as a skyscraper, whether Engineer or Investor, is fully populated, you can upgrade it to the next level.": "ברגע שגורד שחקים, בין אם של מהנדסים או של משקיעים, מאוכלס במלואו, תוכל לשדרג אותו לרמה הבאה.",
    "Engineer skyscrapers can go up to level 3, while investor skyscrapers can go up to level 5.": "גורדי שחקים של מהנדסים יכולים להגיע עד לרמה 3, בעוד שגורדי שחקים של משקיעים יכולים להגיע עד לרמה 5.",
    "Emulating Mother Nature’s delicate touch will yield a plentiful harvest.": "חיקוי המגע העדין של אמא טבע יניב יבול שופע.",
    "Happiness Debuff": "השפעה שלילית על האושר",
    "Your workers are temporarily unhappier": "הפועלים שלך זמנית פחות מאושרים",
    "Your workers are temporarily far less happy": "הפועלים שלך זמנית הרבה פחות מאושרים",
    "You’re the reckless one but, we’ll be the ones dealing with the consequences...": "אתה הפזיז כאן, אבל אנחנו נהיה אלה שנתמודד עם ההשלכות...",
    "The workers are upset that you ignored their concerns.": "הפועלים כועסים על כך שהתעלמת מהחששות שלהם.",
    "Skyline Tower: Daredevils": "מגדל קו הרקיע: פזיזים",
    "Fearless Volunteer": "מתנדב ללא חת",
    "Boss, if we’re to start work on the upper levels on the morrow, we’ll need them new set o’ hands mighty soon!": "בוס, אם אנחנו אמורים להתחיל לעבוד על הקומות העליונות מחר, נצטרך את זוגות הידיים החדשות האלה בקרוב מאוד!",
    "Those new lads seem capable! Up here confidence is key, the price of an indecisive step is steep... and they’ve just arrived in time!": "הבחורים החדשים האלה נראים מוכשרים! כאן למעלה ביטחון עצמי הוא המפתח, המחיר של צעד מהסס הוא כבד... והם בדיוק הגיעו בזמן!",
    "The Lads and I were counting on not going upwards today. Wish we’d had some time to prepare... that kind of uncertainty can be fatal.": "הבחורים ואני בנינו על לא לעלות למעלה היום. הלוואי שהיה לנו קצת זמן להתכונן... אי-ודאות כזו עלולה להיות קטלנית.",
    "The workers say they need more volunteers.": "הפועלים אומרים שהם זקוקים למתנדבים נוספים.",
    "The workers are thankful to have some backup.": "הפועלים אסירי תודה על הגיבוי.",
    "The workers are afraid to work at such heights.": "הפועלים פוחדים לעבוד בגבהים כאלה.",
    "Tutorial — Even Higher": "הדרכה — גבוה עוד יותר",
    "Interspecies Grafting": "הרכבה בין-מינית",
    "From a single stem grows a multitude of produce.": "מגבעול יחיד צומח שפע של תוצרת.",
    "Optimized Pruning": "גיזום מיטבי",
    "Following reports that some workers at the Skyline Tower had expressed a fear of heights, you promised to find brave volunteers in the city to help them safely though their shifts on the higher levels. To fulfil this promise, you need to find replacements before the workers' shifts start. Failing to do so could end in considerable disappointment.": "בעקבות דיווחים לפיהם חלק מהפועלים במגדל קו הרקיע הביעו פחד מגבהים, הבטחת למצוא מתנדבים אמיצים בעיר שיעזרו להם לעבור בבטחה את המשמרות שלהם בקומות העליונות. כדי לקיים הבטחה זו, עליך למצוא מחליפים לפני תחילת המשמרות של הפועלים. אי עשיית כן עלולה להסתיים באכזבה ניכרת.",
    "Cutting off unproductive branches.": "חיתוך ענפים לא יצרניים.",
    "Look for brave volunteers walking the streets of your city.": "חפש מתנדבים אמיצים ברחובות העיר שלך.",
    "Find the following people in [Area Area([Conditions QuestArea]) CityName]:<br />[AssetData([Conditions QuestCondition Context]) Text] [Conditions QuestCondition CurrentAmount]/[Conditions QuestCondition Amount]": "מצא את האנשים הבאים ב-[Area Area([Conditions QuestArea]) CityName]:<br />[AssetData([Conditions QuestCondition Context]) Text] [Conditions QuestCondition CurrentAmount]/[Conditions QuestCondition Amount]",
    "Re-Rendering": "עיבוד מחדש",
    "Skyline Tower: Accident At Work": "מגדל קו הרקיע: תאונת עבודה",
    "A Priest? Good God, with that superstitious lot, all they need is a wing and a prayer.": "הקשב למשאלות ליבם של אנשי אמונה אלה, כומר הוא כל מה שהם זקוקים לו.",
    "A Priest? Good God, with that superstitious lot, all they need is a wing and a prayer.": "כומר? אלוהים אדירים, עם החבורה האמונה התפלה הזו, כל מה שהם צריכים זה קצת אמונה ותקווה.",
    "Wait, there are workers milling around who aren’t on my scaffolds? Can’t have them miss the view of a lifetime now, can we?": "רגע, יש פועלים שמסתובבים שם והם לא על הפיגומים שלי? לא נוכל לתת להם לפספס את נוף חייהם עכשיו, נכון?",
    "Safety harnesses and equipment? Well, if you feel like burning money you can go right ahead.": "רתמות בטיחות וציוד? ובכן, אם מתחשק לך לשרוף כסף, אתה מוזמן להמשיך.",
    "It's important to be able to ignore people. If you give their kind a finger, they'll grab the whole darn hand!": "חשוב להיות מסוגל להתעלם מאנשים. אם תיתן לטיפוסים כמוהם אצבע, הם יקחו את כל היד הארורה!",
    "Retaining, refining, and reusing byproducts.": "שימור, זיקוק ושימוש חוזר במוצרי לוואי.",
    "A priest? Well, maybe some of the lads can find solace...": "כומר? ובכן, אולי חלק מהבחורים ימצאו נחמה...",
    "Ah, that’s great boss! The lads and I appreciate you takin’ action.": "אה, זה נהדר בוס! הבחורים ואני מעריכים את זה שאתה פועל.",
    "The workers say a priest might provide some consolation.": "הפועלים אומרים שכומר עשוי לספק נחמה כלשהי.",
    "Donny believes a priest will solve everything.": "דוני מאמין שכומר יפתור הכל.",
    "Donny says ignoring the workers is what he always does.": "דוני אומר שלהתעלם מהפועלים זה מה שהוא תמיד עושה.",
    "Donny doesn't care who builds the tower, as long as it gets built.": "לדוני לא אכפת מי בונה את המגדל, כל עוד הוא ייבנה.",
    "The workers are grateful you invested in their health and safety.": "הפועלים אסירי תודה על כך שהשקעת בבריאות ובבטיחות שלהם.",
    "Donny doesn’t care if you want to pay for health and safety.": "לדוני לא אכפת אם אתה רוצה לשלם על בריאות ובטיחות.",
    "Spot of bad news. A worker lost his balance, had a tumble – terrible accident. The others could be trouble now... they’ll be wanting to talk to us.": "חדשות רעות קטנות. פועל אחד איבד את שיווי המשקל שלו, נפל — תאונה נוראית. האחרים עלולים לעשות צרות עכשיו... הם ירצו לדבר איתנו.",
    "Donny would rather you talked to the workers.": "דוני מעדיף שאתה תדבר עם הפועלים.",
    "Talk to the workers": "דבר עם הפועלים",
    "The lack of basic security measures at the construction site led to a tragic accident: a worker fell and suffered serious injuries. His fellow workers are demanding to speak to the person in charge, and Donald seems to think you might be the best one to handle the conversation.": "היעדר אמצעי בטיחות בסיסיים באתר הבנייה הוביל לתאונה טרגית: פועל נפל ונפצע קשה. חבריו לעבודה דורשים לדבר עם האחראי, ונראה שדונלד חושב שאתה האיש המתאים ביותר לנהל את השיחה.",
    "See, it wasn’t just superstition! We know the dangers up here better than any, and we warned you! <b>Thomas was a good worker</b>. Always careful — <i>always</i>! Now his legs are busted. He can’t put food on the table — and there's nothin’ more we can do. God knows the other boys are thinking, what if it's them next? What if it’s <i>worse</i>...": "רואה, זו לא הייתה סתם אמונה תפלה! אנחנו מכירים את הסכנות כאן למעלה טוב יותר מכל אחד, והזהרנו אותך! <b>תומאס היה פועל טוב</b>. תמיד זהיר — <i>תמיד</i>! עכשיו הרגליים שלו מרוסקות. הוא לא יכול להביא אוכל הביתה — ואין שום דבר נוסף שאנחנו יכולים לעשות. אלוהים יודע ששאר הבחורים חושבים, מה אם הם הבאים בתור? מה אם זה יהיה <i>גרוע יותר</i>...",
    "Promise to build them a <b>hospital</b> near the site": "הבטח לבנות להם <b>בית חולים</b> ליד האתר",
    "Send a <b>physician</b> for Thomas ([AssetData(137501) Text])": "שלח <b>רופא</b> עבור תומאס ([AssetData(137501) Text])",
    "Pay a <b>risk premium</b> to all ([AssetData(137502) Text] [AssetData(137503) Text])": "שלם <b>תוספת סיכון</b> לכולם ([AssetData(137502) Text] [AssetData(137503) Text])",
    "<b>Ignore</b> their concerns (-10 <img height=\'24\' width=\'24\' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text] for 45 minutes. Current <img height=\'24\' width=\'24\' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text]: [Area Area([Conditions QuestArea]) Happiness AverageHappinessByPopulation(15000001) >> happiness])": "<b>התעלם</b> מהחששות שלהם (-10 <img height=\'24\' width=\'24\' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text] למשך 45 דקות. נוכחי <img height=\'24\' width=\'24\' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text]: [Area Area([Conditions QuestArea]) Happiness AverageHappinessByPopulation(15000001) >> happiness])",
    "Lack of health infrastructure": "מחסור בתשתית בריאות",
    "Tragic accidents at the construction site": "תאונות טרגיות באתר הבנייה",
    "Skyline Tower: Hospitalised": "מגדל קו הרקיע: מאושפז",
    "There’s anger brewing on site...shouldn’t expect anything else by the way you’ve been treating us!": "כעס מתעורר באתר... לא היינו צריכים לצפות לשום דבר אחר לפי הדרך שבה התייחסת אלינו!",
    "A whole hospital? The closer the better! Quick action can be a lifesaver. Thomas will be relived.": "בית חולים שלם? כמה שיותר קרוב יותר טוב! פעולה מהירה יכולה להציל חיים. תומאס יוקל.",
    "Nice to know there’s help close by – makes me worry a tad less about the lads, but let’s hope we don’t need it!": "נחמד לדעת שיש עזרה קרובה — זה גורם לי לדאוג קצת פחות לבחורים, אבל בוא נקווה שלא נצטרך אותה!",
    "You really hold so little regard for our lives? We got no safety on site, no hospital close by... it be madness on our part not to be scared!": "באמת אכפת לך כל כך מעט מהחיים שלנו? אין לנו בטיחות באתר, אין בית חולים קרוב... זה יהיה שיגעון מצדנו לא לפחד!",
    "One doctor? Will he be around for a bit? You never know what’ll happen tomorrow...": "רופא אחד? הוא יהיה בסביבה לזמן מה? לעולם אי אפשר לדעת מה יקרה מחר...",
    "That's good! The risk won’t be gone, but if something does happen... well, it’s quite a bit! It could pay for little Emmi’s education...": "זה טוב! הסיכון לא ייעלם, אבל אם משהו יקרה... ובכן, זה די הרבה! זה יכול לשלם על החינוך של אמי הקטנה...",
    "The workers are angry.": "הפועלים כועסים.",
    "A doctor? What’s his name? Either way, always better to get a man on the job you can trust to patch things up.": "רופא? מה שמו? כך או כך, תמיד עדיף להביא איש מקצוע שאפשר לסמוך עליו שיטפל בדברים.",
    "A hospital? Isn't that an overreaction? Besides think of how goddarn awful it’ll look next to my tower— sickness, death— boy, what a downer!": "בית חולים? זו לא תגובת יתר? חוץ מזה, תחשוב כמה נורא זה ייראה ליד המגדל שלי — מחלות, מוות — ילד, איזה דיכאון!",
    "A risk premium? Well, then I darn well deserve one too. Clearly, I’m at the risk of your questionable choices.": "תוספת סיכון? ובכן, אז גם לי מגיע אחת כזו ובצדק. ברור שאני נתון לסיכון של הבחירות המפוקפקות שלך.",
    "Ignore! Put your fingers in your ears! Always works for me! If push comes to shove, we can always hire more.": "להתעלם! שים אצבעות באוזניים! תמיד עובד בשבילי! אם המצב יחמיר, תמיד נוכל לשכור עוד.",
    "Ugly. You can still remove it. I know a good demolitions crew. Miss Jenny will give you the contacts.": "מכוער. אתה עדיין יכול להסיר את זה. אני מכיר צוות הריסה טוב. מיס ג'ני תיתן לך את אנשי הקשר.",
    "No dismal Hospital! Always keep the other side guessing! Join me for a drink on the skydeck – the Champagne is perfectly chilled.": "בלי בית חולים עגום! תמיד תשאיר את הצד השני מנחש! הצטרף אליי למשקה במרפסת התצפית — השמפניה מצוננת בצורה מושלמת.",
    "Donny prefers to ignore the concerns of the workers.": "דוני מעדיף להתעלם מהחששות של הפועלים.",
    "The workers agree having a hospital nearby would help.": "הפועלים מסכימים שבית חולים בקרבת מקום יעזור.",
    "Donny doesn't see why you wouldn't demolish the hospital now.": "דוני לא מבין למה שלא תהרוס את בית החולים עכשיו.",
    "The workers are pleased you built a hospital nearby.": "הפועלים מרוצים מכך שבנית בית חולים בקרבת מקום.",
    "The workers are upset you broke your promise to build a hospital.": "הפועלים כועסים על כך שהפרת את הבטחתך לבנות בית חולים.",
    "Donny whines that a hospital will devalue the tower.": "דוני מתלונן שבית חולים יפחית מערך המגדל.",
    "Donny is glad you abandoned the squalid idea of a hospital.": "דוני שמח שזנחת את הרעיון העלוב של בית חולים.",
    "The workers are happy you sent for a doctor.": "הפועלים שמחים ששלחת להביא רופא.",
    "Donny supports sending a doctor to the site.": "דוני תומך בשליחת רופא לאתר.",
    "The workers are relieved their risk will be covered financially.": "הפועלים מוקלים מכך שהסיכון שלהם יכוסה כלכלית.",
    "Donny thinks he should be getting a risk premium too.": "דוני חושב שגם לו מגיעה תוספת סיכון.",
    "All Skyline Tower Phases": "כל שלבי מגדל קו הרקיע",
    "Build a new hospital next to the Skyline Tower in [Area Area([Conditions QuestArea]) CityName]": "בנה בית חולים חדש ליד מגדל קו הרקיע ב-[Area Area([Conditions QuestArea]) CityName]",
    "Build the hospital within six tiles of the Skyline Tower.": "בנה את בית החולים בטווח של שישה אריחים ממגדל קו הרקיע.",
    "Following the recent accident at the Skyline Tower, your workers have been asking serious questions about your health and safety measures. To ensure the emergency services can react fast in times of need, you've promised to build a hospital close to the construction site. Your workers welcome the idea — if indeed you follow through on your promise.": "בעקבות התאונה האחרונה במגדל קו הרקיע, הפועלים שלך העלו שאלות רציניות לגבי אמצעי הבריאות והבטיחות שלך. כדי להבטיח ששירותי החירום יוכלו להגיב במהירות בעת הצורך, הבטחת לבנות בית חולים קרוב לאתר הבנייה. הפועלים שלך מברכים על הרעיון — אם אכן תקיים את הבטחתך.",
    "Ensure that the new hospital is next to the Skyline Tower in [Area Area([Conditions QuestArea]) CityName]": "ודא שבית החולים החדש נמצא ליד מגדל קו הרקיע ב-[Area Area([Conditions QuestArea]) CityName]",
    "Get Rich Quick Vol III: Pretty Polyculture": "להתעשר במהירות כרך ג': פוליקולטורה נאה",
    "The best-selling series from veteran businessman Dr. Val Goldfall continues with this look at profiting from diversified garden eco-systems.": "הסדרה הנמכרת ביותר של איש העסקים הוותיק ד\"ר ואל גולדפול ממשיכה במבט זה על הפקת רווחים ממערכות אקולוגיות מגוונות של גנים.",
    "Get Rich Quick Vol I: Pestilential Profit": "להתעשר במהירות כרך א': רווח נגוע במזיקים",
    "Dr. Val Goldfall charts his success, showing how a simple pest control scheme saved the harvest for millions of happy customers.": "ד\"ר ואל גולדפול משרטט את הצלחתו, ומראה כיצד תוכנית פשוטה להדברת מזיקים הצילה את היבול עבור מיליוני לקוחות מרוצים.",
    "Get Rich Quick Vol II: What Shape is a Banana Anyway?": "להתעשר במהירות כרך ב': באיזו צורה יש לבננה בכלל?",
    "Dr. Val Goldfall shares all the tricks of the trade when it comes to bypassing the rules and regs of selling damaged or mis-shapen fruit and veg.": "ד\"ר ואל גולדפול משתף את כל סודות המקצוע בכל הנוגע לעקיפת החוקים והתקנות של מכירת פירות וירקות פגומים או מעוותים.",
    "Double Redundancy": "יתירות כפולה",
    "Higher costs mean higher safety. If a machine fails, there’s always a backup.": "עלויות גבוהות יותר פירושן בטיחות רבה יותר. אם מכונה נכשלת, תמיד יש גיבוי.",
    "Get Rich Quick Vol IV: The Wasteland": "להתעשר במהירות כרך ד': ארץ הישימון",
    "<i>\"Goldfall\'s agronomic poetry never ceases to amaze — it seems now muck is gold!\"</i> — Yate Swindell, Farmboy Weekly.": "<i>\"השירה האגרונומית של גולדפול אף פעם לא מפסיקה להדהים — נראה שעכשיו הזבל הוא זהב!\"</i> — ייט סווינדל, פארמבוי וויקלי.",
    "Get Rich Quick Vol IX: Paid To Perform": "להתעשר במהירות כרך ט': תשלום לפי ביצועים",
    "In his final book, published posthumously, Dr. Goldfall imagines a world in which people are paid not by the hour, but by results.": "בספרו האחרון, שיצא לאור לאחר מותו, ד\"ר גולדפול מדמיין עולם שבו אנשים מקבלים תשלום לא לפי שעה, אלא לפי תוצאות.",
    "Get Rich Quick Vol VIII: Backlogs On The Fire": "להתעשר במהירות כרך ח': פיגורים על האש",
    "Years of experience drip from Dr. Val Goldfall's latest volume, in which he pins down the perfect production schedule.": "שנים של ניסיון נוטפות מכרכו האחרון של ד\"ר ואל גולדפול, שבו הוא מגדיר את לוח הזמנים המושלם לייצור.",
    "Get Rich Quick Vol V: The Geppetto Gambit": "להתעשר במהירות כרך ה': גמביט ג'פטו",
    "Fresh from a prolific career in high-yield farming ventures, Dr. Val Goldfall casts a sharp eye over the enduring power of fine craftsmanship.": "טרי מקריירה פורייה במיזמי חקלאות עתירי יבול, ד\"ר ואל גולדפול מפנה מבט בוחן אל כוחה המתמיד של אומנות משובחת.",
    "<i>\"Business at night runs as smooth as passing ships,\"</i>— Val Goldfall, a man with the midas touch.": "<i>\"עסקים בלילה מתנהלים בצורה חלקה כמו ספינות חולפות,\"</i> — ואל גולדפול, איש עם מגע מידאס.",
    "Get Rich Quick Vol VI: Night Moves": "להתעשר במהירות כרך ו': מהלכי לילה",
    "Belinda San Pedro, Head of Arcade Acquisitions": "בלינדה סן פדרו, ראש תחום רכישות לפסז'ים",
    "Window-Dresser": "מעצב חלונות ראווה",
    "Store Greeter": "מארח חנות",
    "Skyline Tower: Theft On Site": "מגדל קו הרקיע: גניבה באתר",
    "Belinda loves to people-watch — from the moment they step into the arcade to the moment they step out, she observes and takes note.": "בלינדה אוהבת להתבונן באנשים — מהרגע שהם נכנסים לפסז' ועד הרגע שהם יוצאים, היא צופה ורושמת הערות.",
    "His trick is to turn window-shoppers into proper shoppers.": "הטריק שלו הוא להפוך עוברי אורח המביטים בחלונות הראווה לקונים אמיתיים.",
    "Greeting customers makes them feel seen ...especially if they leave without making a purchase.": "ברכת שלום ללקוחות גורמת להם להרגיש שרואים אותם... במיוחד אם הם עוזבים מבלי לבצע רכישה.",
    "Donny is angry about the stolen materials and the warning note.": "דוני כעס על החומרים הגנובים ועל פתק האזהרה.",
    "Stolen steel beams— from the site! How!? Of course, no one saw a thing! And look, there's even one of those damn notes!": "קורות פלדה גנובות — מהאתר! איך!? כמובן, אף אחד לא ראה דבר! ותסתכל, יש אפילו אחד מהפתקים הארורים האלה!",
    "Donny seems keen to blame the workers.": "דוני נראה להוט להאשים את הפועלים.",
    "This pathetic joke’s been dragged out long enough, time we gave it a swift punchline, make an example of these workers— they've just got to be in on it!": "הבדיחה הפתטית הזו נגררה מספיק זמן, הגיע הזמן שניתן לה פאנץ'-ליין מהיר, נהפוך את הפועלים האלה לדוגמה — הם פשוט חייבים להיות שותפים לזה!",
    "Interrogate the workers": "לחקור את הפועלים",
    "The vigilante that's been interfering with Donald Bader's plans has stolen some materials from the construction site, leaving yet another ominous note behind. Mr. Bader believes it can only be a worker causing the mischief, and intends to make an example of them by teaching them a lesson. You still have time to find a more delicate solution.": "הנוקם שהפריע לתוכניותיו של דונלד ביידר גנב כמה חומרים מאתר הבנייה, והשאיר מאחוריו עוד פתק מבשר רעות. מר ביידר מאמין שרק פועל יכול לגרום לצרות הללו, ומתכוון להפוך אותם לדוגמה על ידי לימוד לקח. עדיין יש לך זמן למצוא פתרון עדין יותר.",
    "<font size=\"21\"><b>Dear Donny Bader</b><br/><br/><br/><i>\"And they said, let us build us a city and a tower... lest we be scattered abroad upon the face of the whole earth.\"</i> Genesis 11:1-9<br /><br /><br /><b> Why won't you listen you whiskery old reptile?! It's high time you heard the voices of your workers and compensated them for all the failings in your duties towards them. It's sickening!</b></font>": "<font size=\"21\"><b>דונלד ביידר היקר</b><br/><br/><br/><i>\"ויאמרו הבה נבנה לנו עיר ומגדל... פן נפוץ על פני כל הארץ.\"</i> בראשית יא:1-9<br /><br /><br /><b> למה לא תקשיב, זוחל זקן ומשופם שכמוך?! הגיע הזמן שתשמע את קולותיהם של פועליך ותפצה אותם על כל המחדלים בחובותיך כלפיהם. זה מעורר בחילה!</b></font>",
    "I had <i>nothin’ to do with it</i>, boss! We came back to find the site like that! The beams were gone, and just the little warning note left behind...<br /><br />Look... there's so many frustrated workers working on the Skyline, who knows who’s behind it?! <b>Be reasonable</b>, boss — cut this from our wage, and it’s our families that'll suffer...": "לא היה לי <i>שום קשר לזה</i>, בוס! חזרנו ומצאנו את האתר ככה! הקורות נעלמו, ורק פתק האזהרה הקטן נשאר מאחור...<br /><br />תראה... יש כל כך הרבה פועלים מתוסכלים שעובדים על קו הרקיע, מי יודע מי עומד מאחורי זה?! <b>תהיה הגיוני</b>, בוס — תקזז את זה מהשכר שלנו, והמשפחות שלנו הן אלה שיסבלו...",
    "<b>Replace</b> the missing materials (Pay <img height=\'24\' width=\'24\' src=\"[AssetData(1010218) Icon]\"/>[AssetData(137061) Text] [AssetData(1010218) Text]. Current amount: <img height=\'24\' width=\'24\' src=\"[AssetData(1010218) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010218) >> storagegood])": "<b>החלף</b> את החומרים החסרים (שלם <img height=\'24\' width=\'24\' src=\"[AssetData(1010218) Icon]\"/>[AssetData(137061) Text] [AssetData(1010218) Text]. כמות נוכחית: <img height=\'24\' width=\'24\' src=\"[AssetData(1010218) Icon]\"/>[Area Area([Conditions QuestArea]) Economy StorageAmount(1010218) >> storagegood])",
    "Agree to <b>punish</b> a group of workers at random (-15 <img height=\'24\' width=\'24\' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text] for 45 minutes. Current <img height=\'24\' width=\'24\' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text]: [Area Area([Conditions QuestArea]) Happiness AverageHappinessByPopulation(15000001) >> happiness])": "הסכם <b>להעניש</b> קבוצת פועלים באקראי (-15 <img height=\'24\' width=\'24\' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text] למשך 45 דקות. נוכחי <img height=\'24\' width=\'24\' src=\"[AssetData(15000001) Icon]\"/>[AssetData(13737) Text]: [Area Area([Conditions QuestArea]) Happiness AverageHappinessByPopulation(15000001) >> happiness])",
    "Random Punishment": "עונש אקראי",
    "The workers condemn your treatment of them.": "הפועלים מגנים את היחס שלך אליהם.",
    "Donny believes in punishment.": "דוני מאמין בענישה.",
    "The workers are glad you chose not to hold them responsible for the theft.": "הפועלים שמחים שבחרת שלא להטיל עליהם את האחריות לגניבה.",
    "Donny grumbles about encouraging disobedience.": "דוני רוטן על עידוד חוסר ציות.",
    "Good, time to stop playing nice! The only way their kind learns is a crack of the whip.": "יופי, הגיע הזמן להפסיק להיות נחמדים! הדרך היחידה שטיפוסים כמוהם לומדים היא בהצלפת שוט.",
}

# Add skips to skip.json
skip_file = "skip.json"
skips = []
if os.path.exists(skip_file):
    try:
        skips = json.load(open(skip_file, encoding="utf-8"))
    except Exception:
        skips = []

skips_set = set(skips)
for s in skips_to_add:
    skips_set.add(s)
new_skips = sorted(list(skips_set), key=lambda x: int(x))
json.dump(new_skips, open(skip_file, "w", encoding="utf-8"), ensure_ascii=False, indent=0)
print(f"Updated skip.json: {len(new_skips)} total skips")

# Clean up other trans_part_*.json files
for i in range(2, 6):
    p = f"trans_part_{i}.json"
    if os.path.exists(p):
        os.remove(p)
        print(f"Deleted old {p}")
for i in range(1, 6):
    p = f"skip_part_{i}.json"
    if os.path.exists(p):
        os.remove(p)
        print(f"Deleted old {p}")

# Translate the batch
translated = {}
missing = []
for guid, val in batch.items():
    if guid in skips_to_add:
        continue
    if val in mapping:
        translated[guid] = mapping[val]
    else:
        # Check if it was stripped by auto_skip or is in skips
        if guid in skips_set:
            continue
        missing.append((guid, val))

if missing:
    print(f"Error: {len(missing)} missing translations in batch!")
    for g, v in missing[:10]:
        print(f"  {g}: {v!r}")
else:
    # Save to trans_part_1.json
    json.dump(translated, open("trans_part_1.json", "w", encoding="utf-8"), ensure_ascii=False, indent=4)
    print(f"Successfully saved {len(translated)} translations to trans_part_1.json")
