import json
import os

batch = json.load(open("to_translate_batch.json", encoding="utf-8"))

skips_to_add = []

mapping = {
    "Ed was positively howling with laugher! I only ever asked if he reckoned I could save up a Skyline Tower apartment...": "אד פשוט התגלגל מצחוק! בסך הכל שאלתי אם הוא חושב שאוכל לחסוך מספיק בשביל דירה במגדל קו הרקיע...",
    "Imagine it, waking up to a view from up here. What a high life that would be.": "תאר לעצמך, להתעורר לנוף מכאן למעלה. אילו חיים טובים אלה היו.",
    "Oh no I feel weak in the knees just looking up - Is the tower swaying in the wind?!": "אוי לא, הברכיים שלי רועדות רק מלהביט למעלה — האם המגדל מתנדנד ברוח?!",
    "If I send the patent office the plans for my baseball-catching-device, who's to say they won't steal it?": "אם אשלח למשרד הפטנטים את התוכניות למכשיר שלי לתפיסת כדורי בייסבול, מי יערב לי שהם לא יגנבו אותו?",
    "No, there's a stain on it see here? I was about to polish it with my jacket, how would I even fit this plate in my pocket!?": "לא, יש על זה כתם, רואה כאן? עמדתי להבריק את זה עם הז'קט שלי, איך בכלל אצליח להכניס את הצלחת הזו לכיס שלי?!",
    "Well yes, the refrigerator cost us an arm and a leg, but then, one really does like ice in ones scotch.": "ובכן כן, המקרר עלה לנו הון תועפות, אבל מצד שני, אדם באמת אוהב קרח בוויסקי שלו.",
    "I think I will take to the customer lounge, I must consider this purchase over a sweet cup of tea.": "אני חוכך בדעתי ללכת לטרקלין הלקוחות, אני חייב לשקול את הרכישה הזו על כוס תה מתוק.",
    "Do I need a new bag? Well, I don't know about that. But I certainly don't have one made of leather. Yet.": "האם אני צריך תיק חדש? ובכן, אני לא בטוח לגבי זה. אבל בהחלט אין לי כזה מעור. עדיין.",
    "Oh! This mirror is rather beautiful— or is it just the face in it...": "הו! המראה הזו די יפה — או שמא אלו רק הפנים המשתקפות בה...",
    "What do you mean it's part of the store? I thought all the furniture was for sale.": "מה זאת אומרת שזה חלק מהחנות? חשבתי שכל הרהיטים עומדים למכירה.",
    "Honey, I know the armchair is an heirloom, but look at how tasteful this one is!": "יקירתי, אני יודע שהכורסה היא ירושה משפחתית, אבל תראי כמה זו מעוצבת בטוב טעם!",
    "I would love to test that armchair but I think he’s fallen asleep...": "הייתי שמח לנסות את הכורסה הזו אבל אני חושב שהוא נרדם...",
    "Well, I told Arthur those mustard drapes were awful. No wonder she left...": "ובכן, אמרתי לארתור שוילונות החרדל האלה היו איומים. לא פלא שהיא עזבה...",
    "You know it does make me think of the tincture that agitated travelling salesman offered us... I think I'll stick with cod liver oil.": "אתה יודע, זה באמת גורם לי לחשוב על המרקחת שהסוכן הנודד הנרגש ההוא הציע לנו... נראה לי שאדבוק בשמן כבד דגים.",
    "I see them judging me, it's the third bottle I've had to buy that man this week.": "אני רואה אותם שופטים אותי, זה הבקבוק השלישי שנאלצתי לקנות לאיש הזה השבוע.",
    "Certainly, it's basic hygiene, I brush my teeth twice a week.": "בוודאי, זו היגיינה בסיסית, אני מצחצח שיניים פעמיים בשבוע.",
    "Well it's rather crafty, I heard she used the arsenic in rat poison and honestly...": "ובכן, זה די ערמומי, שמעתי שהיא השתמשה בארסן שברעל עכברים ובכנות...",
    "Do you by chance know how well detergent takes care of blood stains?": "האם אתה יודע במקרה עד כמה חומר ניקוי יעיל בטיפול בכתמי דם?",
    "Theodora introduces herself.": "תיאודורה מציגה את עצמה.",
    "Yes, the details are within my purview. One footnote, my name is Theodora – although Mr. Bader seems to prefer Miss Jenny— an honor to make your acquaintance.": "כן, הפרטים הם בתחום סמכותי. הערת שוליים אחת, שמי הוא תיאודורה — אם כי נראה שמר ביידר מעדיף את השם מיס ג'ני — לכבוד הוא לי להכירך.",
    "Market Research: The Patent": "מחקר שוק: הפטנט",
    "Donny wants you to choose your first patent.": "דוני רוצה שתבחר את הפטנט הראשון שלך.",
    "Choose a patent to research": "בחר פטנט למחקר",
    "With the office completed, and Miss Jenny (who told you she is in fact called Theodora) hired, Donald is extremely pleased with himself, and rewards you by letting you choose the very first patent.": "עם השלמת המשרד, והעסקתה של מיס ג'ני (שסיפרה לך ששמה הוא למעשה תיאודורה), דונלד מרוצה מאוד מעצמו, ומעניק לך פרס על ידי כך שהוא מאפשר לך לבחור את הפטנט הראשון בהחלט.",
    "Miss Jenny, be a dear, I have a cup here with no coffee in it— Now, to business: Our first patent! You've earned the executive decision, partner, what'll it be?": "מיס ג'ני, תהיי נחמדה, יש לי כאן כוס בלי קפה — ועכשיו, לעסקים: הפטנט הראשון שלנו! הרווחת את ההחלטה הניהולית, שותף, מה זה יהיה?",
    "My guru, here’s a pitch: customers are demanding, but gullible — that’s great for us! They’ll have you think they want convenience, luxury, quality... but what they really want is to be <i>led to what they want</i>. We had them on toast with the toaster! I say exploit the moment. Use it. The suckers are salivating for a <b>new gadget</b>, so let’s provide one!<br /><br />Cunning, right?": "הגורו שלי, הנה הרעיון: הלקוחות תובעניים, אבל פתאים — זה מצוין עבורנו! הם יגרמו לך לחשוב שהם רוצים נוחות, יוקרה, איכות... אבל מה שהם באמת רוצים זה ש<i>יובילו אותם למה שהם רוצים</i>. תפסנו אותם חזק עם המצנם! אני אומר שננצל את הרגע. נשתמש בזה. הפראיירים מריירים על <b>גאדג'ט חדש</b>, אז בוא נספק להם אחד!<br /><br />ערמומי, נכון?",
    "Electrifying. The Galeria Baderette sings <b>modernity</b>. Add another machine!": "מחשמל. גלריית ביידרט שרה <b>מודרניות</b>. הוסף מכונה נוספת!",
    "I think the Galeria should be a place of glamour! We need something <b>luxurious</b>!": "אני חוכך בדעתי שהגלריה צריכה להיות מקום של זוהר! אנחנו צריכים משהו <b>יוקרתי</b>!",
    "Ah, great minds, my guru! So, <i>another culinary gadget!</i> They've had a toasty slice, let's provide them a whole darn meal! Everyone’s got to eat!<br /><br /> Let's get their stomachs grumbling, then offer them a gadget to sate their hunger! But, what could that be...?": "הו, מוחות גדולים חושבים דומה, הגורו שלי! אם כן, <i>עוד גאדג'ט קולינרי!</i> הם כבר קיבלו פרוסה קלויה, בוא נספק להם ארוחה שלמה לעזאזל! כולם חייבים לאכול!<br /><br /> בוא נגרום לבטן שלהם לקרקר, ואז נציע להם גאדג'ט שישביע את רעבונם! אבל, מה זה יכול להיות...?",
    "A new gadget? A convenient <b>cooling device</b> for those without room for an ice cellar!": "גאדג'ט חדש? <b>מכשיר קירור</b> נוח למי שאין לו מקום למרתף קרח!",
    "Switch it up. We've built towers, now people need a <b>convenient way to clean</b> them...": "בוא נשנה כיוון. בנינו מגדלים, עכשיו אנשים צריכים <b>דרך נוחה לנקות</b> אותם...",
    "Commercial Needs": "צרכים מסחריים",
    "Crockery Supply": "אספקת כלי אוכל",
    "Vacuum Cleaner Supply": "אספקת שואבי אבק",
    "Refrigerator Supply": "אספקת מקררים",
    "Briefcase Supply": "אספקת תיקי מסמכים",
    "Banker's Lamp Supply": "אספקת מנורות בנקאים",
    "Vanity Screen Supply": "אספקת פרגודים",
    "Writing Desk Supply": "אספקת שולחנות כתיבה",
    "Four-Poster Bed Supply": "אספקת מיטות אפריון",
    "Lounge Seating Supply": "אספקת פינות ישיבה",
    "Toothpaste Supply": "אספקת משחת שיניים",
    "Detergent Supply": "אספקת חומרי ניקוי",
    "Lipstick Supply": "אספקת שפתונים",
    "Face Cream Supply": "אספקת קרם פנים",
    "Pomade Supply": "אספקת משחת שיער",
    "Replace the icebox with a <b>Refrigerator</b>! Of course, my guru! I see the potential! A gadget that opens its doors to a whole new set of culinary products – the bigger we make it, the better!": "החלף את תיבת הקרח ב<b>מקרר</b>! ברור, הגורו שלי! אני רואה את הפוטנציאל! גאדג'ט שפותח את דלתותיו למערכת שלמה של מוצרים קולינריים חדשים — ככל שנעשה אותו גדול יותר, כך ייטב!",
    "Agree to develop the <b>refrigerator</b> patent": "הסכם לפתח את פטנט ה<b>מקרר</b>",
    "Of course, my guru! We’ve built the real-estate — now we get to sell the suckers <b>Vacuum Cleaners</b> to deal with the additional hassle! Ha, wait for the thank you cards their wives will send me!": "בוודאי, הגורו שלי! בנינו את הנדל\"ן — עכשיו אנחנו זוכים למכור לפראיירים <b>שואבי אבק</b> כדי להתמודד עם הטרחה הנוספת! חה, חכה למכתבי התודה שנשותיהם ישלחו לי!",
    "Agree to develop the <b>vacuum cleaner</b> patent": "הסכם לפתח את פטנט <b>שואב האבק</b>",
    "Luxury! Yes, my guru — we model the opulent lifestyle, and they’ll labour under the illusion that they can have it all — if only they work hard enough. Hilarious! <br /><br />What did you have in mind? The toaster numbers surely speak for themselves — <b>something culinary</b>?": "יוקרה! כן, הגורו שלי — אנחנו נציג לראווה סגנון חיים מפואר, והם יעבדו תחת האשליה שהם יכולים להשיג את הכל — אם רק יעבדו קשה מספיק. מצחיק מאוד! <br /><br />מה היה לך בראש? נתוני המצנמים בהחלט מדברים בעד עצמם — <b>משהו קולינרי</b>?",
    "Or something <b>complementary</b>? People need something to eat off after all!": "או משהו <b>משלים</b>? אנשים צריכים משהו לאכול ממנו אחרי הכל!",
    "Oh, <b>Crockery</b>! Yes, why reinvent the wheel when we can just slap a new coat of paint on it and sell it! Let’s make it a staple piece — the good china for <i>special occasions</i>.<br /><br />They’ll need to be of the finest material, of course — the more they break, the more we’ll sell!": "הו, <b>כלי אוכל</b>! כן, למה להמציא מחדש את הגלגל כשאנחנו יכולים פשוט לשים עליו שכבת צבע חדשה ולמכור אותו! בוא נעשה מזה פריט יסוד — כלי הפורצלן הטובים ל<i>אירועים מיוחדים</i>.<br /><br />הם יצטרכו להיות מהחומר המשובח ביותר, כמובן — ככל שהם יישברו יותר, כך נמכור יותר!",
    "If we want to sell luxury, we need business accessories. A <b>high-end bag</b>?": "אם אנחנו רוצים למכור יוקרה, אנחנו צריכים אביזרים עסקיים. <b>תיק יוקרתי</b>?",
    "Agree to develop the <b>crockery</b> patent": "הסכם לפתח את פטנט <b>כלי האוכל</b>",
    "Maybe a <b>Briefcase</b>? I could certainly use one for all these darn documents I have to lug around... Why not be a little <i>self-indulgent</i> for a change!<br /><br />I do love a product that sells itself — every bag hanging off an arm is a walking advertisement!": "אולי <b>תיק מסמכים</b>? אני בהחלט יכול להשתמש באחד עבור כל המסמכים הארורים האלה שאני נאלץ לסחוב... למה לא להיות קצת <i>מפנק עצמית</i> לשם שינוי!<br /><br />אני באמת אוהב מוצר שמוכר את עצמו — כל תיק שתלוי על זרוע הוא פרסומת מהלכת!",
    "Agree to develop the <b>briefcase</b> patent": "הסכם לפתח את פטנט <b>תיק המסמכים</b>",
    "Tutorial — Going Up!": "הדרכה — עולים למעלה!",
    "GOING UP!": "עולים למעלה!",
    "Soaring skyscrapers and cloud-shrouded towers! Elevators and iron frames set to revolutionise the skyline of tomorrow! Onwards and upwards go the citizens of our great cities, fuelled by the burgeoning retail market — shopping arcades and shoppers with money to burn!": "גורדי שחקים נישאים ומגדלים עטויי עננים! מעליות ומסגרות ברזל שעומדות לחולל מהפכה בקו הרקיע של המחר! קדימה ולמעלה צועדים אזרחי הערים הגדולות שלנו, מונעים על ידי שוק הקמעונאות המשגשג — פסז'י קניות וקונים עם כסף לבזבוז!",
    "The wife will be thrilled! Though the noise is intrusive— how will I enjoy the sunday paper? During testing, Miss Jenny will want to get vacuuming and find a way to keep it quiet.": "אשתי תהיה נרגשת! למרות שהרעש מפריע — איך אוכל ליהנות מעיתון יום ראשון? במהלך הבדיקות, מיס ג'ני תרצה להתחיל לשאוב ולמצוא דרך לשמור על השקט.",
    "By-! A device that keeps food fresher, longer. Miss Jenny is good with groceries, great even, with time she might think up the ideal base temperature.": "הו! מכשיר ששומר על המזון טרי יותר, לאורך זמן. מיס ג'ני טובה עם מצרכים, נהדרת אפילו, עם הזמן היא עשויה לחשוב על טמפרטורת הבסיס האידיאלית.",
    "A staple we can get in cheap and ship out at a price. Miss Jenny! Let's get us some blue inks and add the company logo— that’s how they’ll know it’s genuine Bader!": "מוצר בסיסי שאנחנו יכולים להשיג בזול ולשלוח במחיר טוב. מיס ג'ני! בואי נשיג לנו קצת דיו כחול ונוסיף את לוגו החברה — ככה הם ידעו שזה ביידר אמיתי!",
    "Yeah! Miss Jenny will get sewing right away. Has to be a statement piece, out of materials that speak to luxury. We’ll set price accordingly.": "כן! מיס ג'ני תתחיל לתפור מיד. זה חייב להיות פריט בעל נוכחות, מחומרים שמשדרים יוקרה. נקבע את המחיר בהתאם.",
    "Tutorial — Reach for the Skies": "הדרכה — להגיע לשחקים",
    "Tutorial — The Arcade": "הדרכה — הפסז'",
    "Very well, Mr. Bader, I’ll see to it...": "טוב מאוד, מר ביידר, אני אדאג לזה...",
    "Stupendous! Well partner, I’ll be in contact once the lab have finalised the patent.": "נפלא! ובכן שותף, אהיה בקשר ברגע שהמעבדה תשלים את הפטנט.",
    "Donny loves your choice.": "דוני אוהב את הבחירה שלך.",
    "Theodora will finalise the patent.": "תיאודורה תשלים את הפטנט.",
    "Donny will call on you when the patent is finished.": "דוני יפנה אליך כשהפטנט יהיה מוכן.",
    "Select Department Store design patent:<br />Toasters": "בחר פטנט עיצוב לחנות כלבו:<br />מצנמים",
    "Select Assembly Line Patent:<br />Elevators": "בחר פטנט לפס ייצור:<br />מעליות",
    "An investor offers his guidance regarding elevators and skyscrapers.": "משקיע מציע את הדרכתו בנוגע למעליות וגורדי שחקים.",
    "The investor suggests you build a shopping arcade.": "המשקיע מציע שתבנה פסז' קניות.",
    "TutorialHint HighLife": "רמז הדרכה HighLife",
    "For skyscrapers, you need elevators. And elevators are produced in the <b>assembly line</b>, a new <b>multifactory</b>.": "עבור גורדי שחקים, אתה צריך מעליות. ומעליות מיוצרות ב<b>פס הייצור</b>, <b>מפעל מרובה-תעשיות</b> חדש.",
    "In a <b>Multifactory</b>, you can choose the industrial patent it'll produce.": "ב<b>מפעל מרובה-תעשיות</b>, אתה יכול לבחור את הפטנט התעשייתי שהוא ייצר.",
    "The investor suggests building a skyscraper when enough elevators are in stock.": "המשקיע מציע לבנות גורד שחקים כאשר יש מספיק מעליות במלאי.",
    "Uniform in shape, size and taste, these afternoon delights tumble off the assembly line in their dozens — and if they survive the landing, soon disappear off in their boxes. Keep out of reach of children, or else you might end up with just a handful of crumbs!": "אחידים בצורתם, בגודלם ובטעמם, מעדני אחר הצהריים האלה נושרים מפס הייצור בעשרותיהם — ואם הם שורדים את הנחיתה, הם נעלמים במהירות בתוך הקופסאות שלהם. שמור הרחק מהישג ידם של ילדים, אחרת אתה עלול לסיים עם קומץ פירורים בלבד!",
    "Ah, toys! Look at her, for instance — chubby face, rosy cheeks, angelic locks! Simply the perfect gift for itsy-bitsy grandchildren. They will be delighted! Most of them, anyway... Some might be terrified.": "אה, צעצועים! תסתכל עליה, למשל — פנים שמנמנות, לחיים ורדרדות, תלתלים מלאכיים! פשוט המתנה המושלמת לנכדים קטנטנים. הם יהיו מרוצים! רובם, בכל אופן... חלקם עלולים להיות מבועתים.",
    "Upgrade to Skyscraper:": "שדרג לגורד שחקים:",
    "Engineer Residence 0/1": "בית מגורים של מהנדסים 0/1",
    "Corky Jr. getting the better of you again? Don't worry, it's not the cognac! What you need is practice, old sport! So chalk up your cue and get set with this heavy-set game table with a fetching green baize. Ivory-free balls means more tusk on the walls!": "ג'וניור קורקי שוב גובר עליך? אל תדאג, זה לא הקוניאק! מה שאתה צריך זה תרגול, חברי היקר! אז שפשף את הגיר על המקל שלך והתכונן עם שולחן המשחק הכבד הזה בעל הלבד הירוק המושך. כדורים ללא שנהב פירושם יותר חטים על הקירות!",
    "A beautiful, shapely wooden instrument to play when you're feeling blue — play it well, and it may produce breathtaking melodies; play it badly, and well... may you benefit from your neighbour's energetic percussion through the paper-thin wall!": "כלי עץ יפהפה ומעוצב לנגינה כשאתה מרגיש עצוב — נגן עליו היטב, והוא עשוי להפיק מנגינות עוצרות נשימה; נגן עליו גרוע, וטוב... מי ייתן ותיהנה מתיפוף המרץ של השכן שלך דרך הקיר הדק כנייר!",
    "Shopping Arcades are a new building type: they act <b>like public services, but consume input goods</b>! The input goods required depend on the chosen design patent. Start with a <b>department store</b>.": "פסז'י קניות הם סוג מבנה חדש: הם פועלים <b>כמו שירותים ציבוריים, אך צורכים סחורות קלט</b>! סחורות הקלט הנדרשות תלויות בפטנט העיצוב הנבחר. התחל עם <b>חנות כלבו</b>.",
    "When selecting a Shopping Arcade like the Department Store and <b>choosing a new design patent</b>, you require different input goods. So, make sure you have a <b>warehouse</b> within range!": "בעת בחירת פסז' קניות כמו חנות כלבו ו<b>בחירת פטנט עיצוב חדש</b>, אתה זקוק לסחורות קלט שונות. לכן, ודא שיש לך <b>מחסן</b> בטווח הקרוב!",
    "In principle, all shopping arcades act <b>like public services, but they consume input goods</b>. As long as the selected design patent can be produced, it will fulfill the <b>skyscraper residents' need for this type of shopping arcade</b>, no matter which product you've selected.": "כעיקרון, כל פסז'י הקניות פועלים <b>כמו שירותים ציבוריים, אך הם צורכים סחורות קלט</b>. כל עוד ניתן לייצר את פטנט העיצוב הנבחר, הוא יספק את <b>צורך תושבי גורדי השחקים בסוג זה של פסז' קניות</b>, ללא קשר למוצר שבחרת.",
    "Depending on a design patent's ingredients, a Shopping Arcade will require <b>different input goods</b>.<br />Make sure you have a <b>warehouse</b> nearby, that stocks those goods.": "בהתאם למרכיבי פטנט העיצוב, פסז' קניות ידרוש <b>סחורות קלט שונות</b>.<br />ודא שיש לך <b>מחסן</b> בקרבת מקום המחזיק בסחורות אלו.",
    "Aside from fulfilling the need for a Department Store, it also has a <b>beneficial effect on any residents that live nearby</b>.": "מלבד מילוי הצורך בחנות כלבו, יש לו גם <b>השפעה מועילה על כל תושב המתגורר בקרבת מקום</b>.",
    "These tips apply to Shopping Arcades:<br />1. The <b>green street overlay</b> indicates where input goods can be fetched from.<br />2. The <b>green street overlay</b> also indicates which Skyscrapers will have the need for a Shopping Arcade fulfilled.<br />3. The <b>circle</b> indicates which residences benefit from the current patent.": "טיפים אלה חלים על פסז'י קניות:<br />1. <b>שכבת הרחוב הירוקה</b> מציינת מניין ניתן להביא סחורות קלט.<br />2. <b>שכבת הרחוב הירוקה</b> מציינת גם לאילו גורדי שחקים יתמלא הצורך בפסז' קניות.<br />3. <b>העיגול</b> מציין אילו בתי מגורים מפיקים תועלת מהפטנט הנוכחי.",
    "Mr. Bader, there's a problem. While I was out this morning someone broke into the office. The piston pumps have disappeared.": "מר ביידר, יש בעיה. בזמן שהייתי בחוץ הבוקר מישהו פרץ למשרד. משאבות הבוכנה נעלמו.",
    "Mr. Bader, there's a problem. While I was out this morning someone broke into the office. The oil for the cooling system was stolen.": "מר ביידר, יש בעיה. בזמן שהייתי בחוץ הבוקר מישהו פרץ למשרד. השמן למערכת הקירור נגנב.",
    "Mr. Bader, there's a problem. While I was out this morning someone broke into the office. The paints for the brand logo have been stolen.": "מר ביידר, יש בעיה. בזמן שהייתי בחוץ הבוקר מישהו פרץ למשרד. הצבעים של לוגו המותג נגנבו.",
    "Mr. Bader, there's a problem. While I was out this morning someone broke into the office. The bags of cotton have been stolen.": "מר ביידר, יש בעיה. בזמן שהייתי בחוץ הבוקר מישהו פרץ למשרד. שקי הכותנה נגנבו.",
    "You were out, Miss Jenny? I thought your work was your life— well, but can you still continue our research?": "היית בחוץ, מיס ג'ני? חשבתי שהעבודה שלך היא חייך — ובכן, אך האם את עדיין יכולה להמשיך במחקר שלנו?",
    "I am afraid not. Without these materials I cannot move forward with the prototype.": "אני חוששת שלא. ללא החומרים הללו איני יכולה להתקדם עם אב הטיפוס.",
    "The ceaseless assembly line churns out goods with no end. Workers with vacant expressions are caught up in repetitive motion, perfecting their cycle by doing it over and over again.": "פס הייצור הבלתי פוסק פולט סחורות ללא קץ. פועלים עם הבעות פנים ריקות שקועים בתנועה חזרתית, משכללים את המחזור שלהם על ידי ביצועו שוב ושוב.",
    "Are you certain we should use these goods...?": "האם אתה בטוח שעלינו להשתמש בסחורות אלו...?",
    "Theodora asks if these are the replacement materials.": "תיאודורה שואלת אם אלו חומרי החילוף.",
    "Ah, how I relish working with a professional! If only that was the norm, wouldn’t you agree Miss Jenny?": "אה, כמה אני מתענג על עבודה עם מקצוען! אילו רק זה היה הנורמה, לא תסכימי מיס ג'ני?",
    "Donny praises your speed, while deriding Theodora.": "דוני משבח את המהירות שלך, תוך שהוא לועג לתיאודורה.",
    "In <b>Multifactories</b> like the assembly line, you can <b>change the product</b> being produced on the fly. <br />But Elevators are exactly what we need right now, so let's just <b>leave it as is</b>.": "ב<b>מפעלים מרובי-תעשיות</b> כמו פס הייצור, אתה יכול <b>לשנות את המוצר</b> המיוצר תוך כדי תנועה. <br />אבל מעליות הן בדיוק מה שאנחנו צריכים כרגע, אז בוא פשוט <b>נשאיר את זה כפי שהוא</b>.",
    "Here you see <b>all assembly line patents</b>. Right now, only one is available, but you can unlock new ones later.<br />Click on the first patent to <b>jump directly to it</b>.": "כאן אתה רואה את <b>כל פטנטי פסי הייצור</b>. כרגע רק אחד זמין, אך תוכל לפתוח פטנטים חדשים בהמשך.<br />לחץ על הפטנט הראשון כדי <b>לקפוץ ישירות אליו</b>.",
    "Indeed Mr. Bader. I too wish that were the case.": "אכן מר ביידר. גם אני מייחלת לכך שזה היה המצב.",
    "Theodora seems committed to the patent, despite everything.": "תיאודורה נראית מחויבת לפטנט, למרות הכל.",
    "Here, you can see which <b>input goods</b> are necessary to produce this industrial patent. Choose the <b>Elevators</b> now.": "כאן תוכל לראות אילו <b>סחורות קלט</b> נחוצות כדי לייצר פטנט תעשייתי זה. בחר ב<b>מעליות</b> כעת.",
    "Market Research: Cold Calling": "מחקר שוק: שיחות קרות",
    "Market Research: Crock of Gold": "מחקר שוק: סיר של זהב",
    "Market Research: Manbags": "מחקר שוק: תיקי גברים",
    "Reward Patent": "פטנט פרס",
    "Good news, ingenuity has prevailed. The prototype successfully passed testing, is fully functional and is ready to enter into production...": "חדשות טובות, התושייה ניצחה. אב הטיפוס עבר בהצלחה את הבדיקות, הוא תפעולי לחלוטין ומוכן להיכנס לייצור...",
    "Theodora says the patent is now ready for the shops.": "תיאודורה אומרת שהפטנט מוכן כעת לחנויות.",
    "Effective and fairly silent, a winning combination. I may yet keep miss Jenny on!": "יעיל ודי שקט, שילוב מנצח. אולי עוד אשאיר את מיס ג'ני אצלנו!",
    "Donald looks forward to seeing the new product sell.": "דונלד מצפה לראות את המוצר החדש נמכר.",
    "Cold and calculating miss Jenny, as usual. I think we can shut the door on this one, guru.": "מיס ג'ני קרה ומחושבת, כרגיל. אני חושב שאנחנו יכולים לסגור את הסיפור בזה, גורו.",
    "The difference a brand makes, an immediate mark-up. I must admit Miss Jenny you have a keen eye for domestic detail!": "ההבדל שמותג עושה, עליית מחיר מיידית. אני חייב להודות מיס ג'ני שיש לך עין חדה לפרטים ביתיים!",
    "Striking look! I might just grab one for myself, special one-time edition, don't mind if I do. Make it so Miss Jenny.": "מראה בולט! אולי פשוט אחטוף אחד לעצמי, מהדורה מיוחדת חד-פעמית, לא אכפת לי אם כן. דאגי לכך מיס ג'ני.",
    "The Survey: Subjective Feedback": "הסקר: משוב סובייקטיבי",
    "Donny hopes you can drop by the market research lab.": "דוני מקווה שתוכל לקפוץ למעבדת מחקר השוק.",
    "I’ve coaxed a few citizens into a so-called marketing ‘survey.’ Your input is appreciated, can you stop by the office?": "שידלתי כמה אזרחים להשתתף במה שנקרא 'סקר' שיווקי. הערכתך מוערכת, האם תוכל לעבור במשרד?",
    "Mr. Bader has convinced a group of bemused citizens to take part in what he calls a 'marketing survey'. He hopes these survey subjects can unearth the next lucrative patent for him. He’s invited you to his office to hear their survey responses and determine the best course for business.": "מר ביידר שכנע קבוצה של אזרחים משועשעים להשתתף במה שהוא מכנה 'סקר שיווקי'. הוא מקווה שהמשתתפים בסקר יוכלו לחשוף עבורו את הפטנט הרווחי הבא. הוא הזמין אותך למשרדו כדי לשמוע את תשובותיהם לסקר ולקבוע את נתיב הפעולה הטוב ביותר לעסק.",
    "Select the survey subjects to hear their views.": "בחר את המשתתפים בסקר כדי לשמוע את דעותיהם.",
    "<b>Select the following survey subjects</b> to hear their views:": "<b>בחר את המשתתפים הבאים בסקר</b> כדי לשמוע את דעותיהם:",
    "Survey": "סקר",
    "Romantic Survey Subject": "משתתף סקר רומנטי",
    "<i>“What kind of products would you like to see in our stores?”</i> That’s broad... Well, I moved into a skyscraper apartment. The view is nice and all, but the interiors all look the same...": "<i>\"אילו סוגי מוצרים היית רוצה לראות בחנויות שלנו?\"</i> זה די כללי... ובכן, עברתי לדירת גורד שחקים. הנוף נחמד והכל, אבל העיצוב הפנימי של כולם נראה בדיוק אותו הדבר...",
    "<i>“How could your current situation be improved?”</i> Right now? A drink! Sorry. err... Look, I work in an office, and we’re shoulder-to-shoulder in there. There’s just no privacy...": "<i>\"כיצד ניתן לשפר את מצבך הנוכחי?\"</i> כרגע? משקה! סליחה. אממ... תראה, אני עובד במשרד, ואנחנו דחוסים שם כתף אל כתף. פשוט אין שום פרטיות...",
    "<i>“How do you perceive our brand?”</i>How can I put this... It’s very fancy and grand, but... it’s also expensive and intimidating? I feel a little out of place in that swish Arcade...": "<i>\"איך אתה תופס את המותג שלנו?\"</i> איך לנסח זאת... הוא מאוד מפואר ומהודר, אבל... הוא גם יקר ומאיים? אני מרגיש קצת מחוץ למקום בפסז' המהודר הזה...",
    "Reclusive Survey Subject": "משתתף סקר מתבודד",
    "Cheapskate Survey Subject": "משתתף סקר קמצן",
    "The Survey: Analysis": "הסקר: ניתוח",
    "Donny needs help analyzing the survey results.": "דוני זקוק לעזרה בניתוח תוצאות הסקר.",
    "A whole bunch of demanding so-and-sos in that survey. How you put up with them on the daily is beyond me. Let's skim the results, pick our best-seller!": "חבורה שלמה של תובעניים כאלה ואחרים בסקר הזה. איך אתה מתמודד איתם על בסיס יומי זה מעבר להבנתי. בוא נעבור על התוצאות, ונבחר את רב-המכר שלנו!",
    "The marketing survey did not go as Donald intended. But, knowing little of scientific rigour, he is unbothered and wants to you to analyze the results regardless. As long as there’s a product at the end he can sell, he’ll call it a success.": "הסקר השיווקי לא התנהל כפי שדונלד תכנן. אך מכיוון שהוא מבין מעט מאוד בקפדנות מדעית, זה לא מטריד אותו והוא רוצה שתנתח את התוצאות בכל מקרה. כל עוד יש מוצר בסוף שהוא יכול למכור, הוא יכתיר זאת כהצלחה.",
    "Analyse the survey results": "נתח את תוצאות הסקר",
    "I know a thing or two about construction investments and let me tell you elevators and skyscrapers are on the rise! I can offer insider info, if you like.": "אני מבין דבר או שניים בהשקעות בנייה ותן לי להגיד לך שמעליות וגורדי שחקים נמצאים בעלייה! אני יכול להציע מידע פנימי, אם תרצה.",
    "Done. Time to get the Elevators up and running. People want better views— why not turn a typical residence into your very first skyscraper?": "בוצע. הגיע הזמן להפעיל את המעליות. אנשים רוצים נופים טובים יותר — למה לא להפוך בית מגורים רגיל לגורד השחקים הראשון שלך?",
    "Ah yes, Shopping Arcades! Heralding a new era of consumerism. Time to welcome eager patrons into the halls of luxurious promise!": "אה כן, פסז'י קניות! מבשרים על עידן חדש של צרכנות. הגיע הזמן לקבל בברכה לקוחות נלהבים להיכלי ההבטחה היוקרתית!",
    "The market research survey results are in! Where did Miss Jenny put my darn notes... Oh well, don’t need em'! We had some really dull responses. I cherry-picked the data: <br /><br />maybe 80% want <i>fancy furniture</i>, 75% like <i>luxury</i> stuff, and 20-odd percent just want a <i>drink</i>.<br /><br />So, <i>my guru</i>, <b>what do you think will make us money</b>?": "תוצאות סקר מחקר השוק הגיעו! איפה מיס ג'ני שמה את הרשימות הארורות שלי... נו טוב, לא צריך אותן! היו לנו כמה תשובות משעממות באמת. בחרתי בקפידה את הנתונים: <br /><br />אולי 80% רוצים <i>רהיטים מפוארים</i>, 75% אוהבים דברים <i>יוקרתיים</i>, וכעשרים אחוזים פשוט רוצים <i>משקה</i>.<br /><br />אז, <i>הגורו שלי</i>, <b>מה לדעתך יביא לנו כסף</b>?",
    "Furniture <i>, <i>quality</i>, and a <i>drink</i>?... Um, a <b>mini bar</b>?": "<i>רהיטים</i>, <i>איכות</i> ו<i>משקה</i>?... אממ, <b>מיני בר</b>?",
    "Actually, I'd like to <b>hear what Theodora has to say</b> about the results.": "למעשה, הייתי רוצה <b>לשמוע מה יש לתיאודורה לומר</b> על התוצאות.",
    "Ha-ha, I like it! Not everyone has a <i>Miss Jenny</i> around to get em’ a Gin and Tonic, huh? This is a very good ratio, by the way. Miss Jenny, do you think people want a mini-bar? Speak up, what’s your take? No wrong answers.": "חה-חה, אני אוהב את זה! לא לכולם יש <i>מיס ג'ני</i> בסביבה שתביא להם ג'ין וטוניק, הא? זה יחס טוב מאוד, דרך אגב. מיס ג'ני, את חושבת שאנשים רוצים מיני-בר? דברי, מה עמדתך? אין תשובות שגויות.",
    "Listen to <b>Miss Jenny</b>": "הקשב ל<b>מיס ג'ני</b>",
    "What do I think? Well, I must say the 'method' of analysis <b>skewed the results</b>, so I'm intrigued by the percentages you uncovered, Mr. Bader! <i>Well done</i>. <br /><br />If we consider our survey responses, I’d say they want a product to help them <i>personalize</i> their skyscraper apartments, and provide a little <i>privacy</i>, while others perceive the Galleria as rather uninclusive and would prefer a <i>range of affordable products</i>.": "מה אני חושבת? ובכן, אני חייבת לומר ששיטת הניתוח <b>הטתה את התוצאות</b>, אז אני מסוקרנת מהאחוזים שחשפת, מר ביידר! <i>כל הכבוד</i>. <br /><br />אם נתחשב בתשובות לסקר, הייתי אומרת שהם רוצים מוצר שיעזור להם <i>להתאים אישית</i> את דירות גורדי השחקים שלהם, ויעניק מעט <i>פרטיות</i>, בעוד שאחרים תופסים את הגלריה כלא מכילה במיוחד ומעדיפים <i>מגוון של מוצרים ברי-השגה</i>.",
    "Maybe a <b>Vanity Screen</b>. It’s decorative, grants privacy and, well, affordability is relative.": "אולי <b>פרגוד</b>. הוא קישוטי, מעניק פרטיות ו... טוב, היות הדבר בר-השגה הוא עניין יחסי.",
    "It’s hard to define a single product. Maybe our focus should be <b>personalization and affordability</b>.": "קשה להגדיר מוצר יחיד. אולי המיקוד שלנו צריך להיות <b>התאמה אישית ומחיר בר-השגה</b>.",
    "Yes, we have a very diverse customer base. I could <b>write a patent proposal</b> and...": "כן, יש לנו בסיס לקוחות מגוון מאוד. אני יכולה <b>לכתוב הצעת פטנט</b> ו...",
    "Continue": "המשך",
    "A <b>Vanity Screen</b>? That seems rather specific. Maybe for some that could be a fit, but...": "<b>פרגוד</b>? זה נראה די ספציפי. אולי עבור חלק זה יכול להתאים, אבל...",
    "Miss Jenny, there’s no pleasing everyone! We’re here to make a product that sells, and I’ve run out of talk time!<br /><br />My Guru, you’ve taught me to follow my instincts, so let's just go in hard on the <b>Vanity Screens</b>! Decorative, perfect to hide behind, and really, we don’t want every kind in our Arcades now, do we? So make it pricey!": "מיס ג'ני, אי אפשר לרצות את כולם! אנחנו כאן כדי לייצר מוצר שנמכר, ונגמר לי זמן הדיבור!<br /><br />הגורו שלי, לימדת אותי ללכת בעקבות האינסטינקטים שלי, אז בוא פשוט נלך חזק על <b>הפרגודים</b>! קישוטי, מושלם להתחבא מאחוריו, ובאמת, אנחנו לא רוצים כל סוג בפסז'ים שלנו עכשיו, נכון? אז עשה את זה יקר!",
    "Unlock the <b>vanity screen</b> patent": "פתח את פטנט <b>הפרגוד</b>",
    "Well done us! Now all we need is a <i>flashy poster</i> and they’ll be craving a vanity screen in no time! My guru — we need a slogan! We could play on a sense of luxury or fun — make it <b>rhyme</b>!<br /><br />'Galeria Baderette... ‘": "כל הכבוד לנו! עכשיו כל מה שאנחנו צריכים זה <i>כרזה נוצצת</i> והם ישתוקקו לפרגוד תוך זמן קצר! הגורו שלי — אנחנו צריכים סלוגן! אנחנו יכולים לשחק על תחושה של יוקרה או כיף — שזה <b>יחרוז</b>!<br /><br />'גלריית ביידרט... '",
    "”...the height of etiquette”": "\"היא שיא הנימוס והחן\"",
    "”...life is a cabaret”": "\"החיים הם קברט\"",
    "Ah, how <i>creative</i>! They’ll love it. Now all that’s missing is a <b>picture of the vanity screen</b>...<br /><br />Miss Jenny would you... no <i>not</i> that one! The other one! Yes. Good...": "אה, כמה <i>יצירתי</i>! הם יאהבו את זה. עכשיו כל מה שחסר זה <b>תמונה של הפרגוד</b>...<br /><br />מיס ג'ני, האם תוכלי... לא <i>לא</i> זה! השני! כן. טוב...",
    "See the <b>poster</b>": "ראה את ה<b>כרזה</b>",
    "<b>The height of etiquette!</b>": "<b>שיא הנימוס והחן!</b>",
    "<b>Life is a cabaret!</b>": "<b>החיים הם קברט!</b>",
    "Two birds one cartridge: A brand-new patent and a dazzling poster advertisement! While Miss Jenny runs the posters round town, us big dogs can crank up production to meet a deluge of demand!": "שתי ציפורים בכדור אחד: פטנט חדש לגמרי ופרסומת כרזה מסנוורת! בזמן שמיס ג'ני מפיצה את הכרזות ברחבי העיר, אנחנו הבוסים הגדולים יכולים להגביר את הייצור כדי לענות על מבול הביקושים!",
    "Donny wants to start producing Vanity Screens.": "דוני רוצה להתחיל לייצר פרגודים.",
    "The Survey: Vanity Fair": "הסקר: יריד ההבלים",
    "Equip the Vanity Screen patent in your Furniture Store in [Area Area([Conditions QuestArea]) CityName]": "הצטייד בפטנט הפרגוד בחנות הרהיטים שלך ב-[Area Area([Conditions QuestArea]) CityName]",
    "Reach the following productivity in your [AssetData([Conditions QuestCondition Context]) Text] of [Area Area([Conditions QuestArea]) CityName]:<br />[Conditions QuestCondition CurrentAmount]% / [Conditions QuestCondition Amount]%": "הגע לפריון הבא ב-[AssetData([Conditions QuestCondition Context]) Text] שלך ב-[Area Area([Conditions QuestArea]) CityName]:<br />[Conditions QuestCondition CurrentAmount]% / [Conditions QuestCondition Amount]%",
    "With the vanity screen chosen and the poster distributed, Donald demands that you start production!": "עם בחירת הפרגוד והפצת הכרזה, דונלד דורש שתתחיל בייצור!",
    "Vanity screens ready— great! We’ll know how divisive our marketing campaign was once the numbers are in. I'll be sure to pass them along, but so you know, I already put the Champagne on ice.": "הפרגודים מוכנים — נהדר! נדע עד כמה מסע הפרסום שלנו היה שנוי במחלוקת ברגע שהנתונים יגיעו. אני בהחלט אעביר אותם אליך, אבל שתדע, כבר שמתי את השמפניה על קרח.",
    "Donny is feeling positive about the potential of this patent.": "דוני מרגיש חיובי לגבי הפוטנציאל של פטנט זה.",
    "The Survey: No Bad Press": "הסקר: אין פרסום גרוע",
    "Miss Jenny'll make sure the vandal gets it in the neck! Hey, Miss Jenny! Miss... I forgot, she’s off work. Well it's civil disobedience in your city— don't let our little venture take the hit...": "מיס ג'ני תוודא שהוונדל יחטוף בראש! היי, מיס ג'ני! מיס... שכחתי, היא לא בעבודה. ובכן, זה מרי אזרחי בעיר שלך — אל תיתן למיזם הקטן שלנו להיפגע...",
    "Donny wants you to unmask the vandal in Theodora's absence.": "דוני רוצה שתחשוף את הוונדל בהיעדרה של תיאודורה.",
    "A vandal is tagging the vanity screen posters around the city, with a red and white logo of a falling man! Mr. Bader will not have his property defaced, and has tasked you with apprehending the criminal.": "וונדל מרסס את כרזות הפרגודים ברחבי העיר בלוגו אדום ולבן של איש נופל! מר ביידר לא ירשה שישחיתו את רכושו, והטיל עליך לתפוס את הפושע.",
    "Donny presses you to hurry up.": "דוני לוחץ עליך להזדרז.",
    "Time's a wasting! Every poster that's been got at is a dent in our profits!": "הזמן מתבזבז! כל כרזה שהושחתה היא פגיעה ברווחים שלנו!",
    "<b>Hunt the vandal!</b>": "<b>צוד את הוונדל!</b>",
    "<b>Hunt the vandal!</b><br />Ask the newspaper boy if he’s seen anything": "<b>צוד את הוונדל!</b><br />שאל את נער העיתונים אם הוא ראה משהו",
    "<b>Hunt the vandal!</b><br />Clues may be found at the harbour": "<b>צוד את הוונדל!</b><br />רמזים עשויים להימצא בנמל",
    "<b>Hunt the vandal!</b><br />Someone nearby could identify these clothes.": "<b>צוד את הוונדל!</b><br />מישהו בקרבת מקום עשוי לזהות את הבגדים האלה.",
    "<b>Hunt the vandal!</b><br />Seems the vandal fed some birds by the harbour...": "<b>צוד את הוונדל!</b><br />נראה שהוונדל האכיל כמה ציפורים ליד הנמל...",
    "<b>Hunt the vandal!</b><br />The note on the ground hints at your furniture store": "<b>צוד את הוונדל!</b><br />הפתק שעל הרצפה רומז על חנות הרהיטים שלך",
    "A fellow with red and white paint, you say? Yeah, I saw one. Heading down to the docks. He had a proper moustache, too.": "בחור עם צבע אדום ולבן, אתה אומר? כן, ראיתי אחד. פנה לכיוון הרציפים. היה לו גם שפם רציני.",
    "Lying on top of the crates is a bundle of clothes. Among them you find a sizeable fake moustache, a brown wig, and a long blue dress...": "מונחת על גבי הארגזים חבילת בגדים. ביניהם אתה מוצא שפם מלאכותי גדול, פאה חומה ושמלה כחולה ארוכה...",
    "Someone with a moustache? You'll need to be more specific... See, I saw a red-haired woman a little earlier wearing a beautiful blue dress — <i>I wish I had one like it</i>! Now that I can recall! She was feeding the birds.": "מישהו עם שפם? תצטרך להיות ספציפי יותר... ראה, ראיתי אישה ג'ינג'ית קצת קודם לכן לובשת שמלה כחולה יפה — <i>הלוואי שהייתה לי אחת כזו</i>! עכשיו כשאני נזכר! היא האכילה את הציפורים.",
    "The flock of birds is pecking away happily. As you shoo them away, you discover a note placed beneath their feed. It reads: <i>“Mr. Bader, looking for me is like trying to find a needle in a haystack. Give up and go back to sleep in your furniture store.”</i>": "להקת הציפורים מנקרת להנאתה. כשאתה מבריח אותן, אתה מגלה פתק שהונח מתחת למזון שלהן. כתוב בו: <i>\"מר ביידר, לחפש אותי זה כמו לנסות למצוא מחט בערימת שחת. ותר על זה וחזור לישון בחנות הרהיטים שלך.\"</i>",
    "There is a pile of red and white paint buckets. One of them has a note stuck to it. It reads: <i>“Take the paints. This is all futile — your conceited product will see the light of day anyway. Enjoy your shallow victory while it lasts. Regards, an angry worker.”</i>": "ישנה ערימה של דליי צבע אדומים ולבנים. על אחד מהם מודבק פתק. כתוב בו: <i>\"קח את הצבעים. כל זה חסר תועלת — המוצר היהיר שלך יראה אור יום בכל מקרה. תהנה מהניצחון הרדוד שלך כל עוד הוא נמשך. בברכה, פועל כועס.\"</i>",
    "Newsboy": "נער עיתונים",
    "Heap of Disguises": "ערימת תחפושות",
    "Envious Visitor": "מבקר קנאי",
    "Pack of Ravenous Pigeons": "להקת יונים רעבות",
    "Pile of Paint Buckets": "ערימת דליי צבע",
    "Sabotage": "חבלה",
    "Look at: [AssetData([RefGuid]) Text]": "הביט ב: [AssetData([RefGuid]) Text]",
    "Talk to: [AssetData([RefGuid]) Text]": "דבר עם: [AssetData([RefGuid]) Text]",
    "The Department Store requires the input goods for its design patent to be within range. Make sure you have a warehouse nearby. The green street overlay shows you where input goods can be acquired.": "חנות הכלבו דורשת שסחורות הקלט עבור פטנט העיצוב שלה יהיו בטווח. ודא שיש לך מחסן בקרבת מקום. שכבת הרחוב הירוקה מראה לך היכן ניתן להשיג סחורות קלט.",
    "Any Engineer or Investor residence can be upgraded into a skyscraper. They only need to be fully populated.": "ניתן לשדרג כל בית מגורים של מהנדסים או משקיעים לגורד שחקים. הם רק צריכים להיות מאוכלסים במלואם.",
    "The green street overlay also shows you which skyscrapers will have their shopping arcade need fulfilled.": "שכבת הרחוב הירוקה מראה לך גם לאילו גורדי שחקים יתמלא הצורך בפסז' קניות.",
    'Skyscraper residents like to have an <b>unobstructed, panoramic view</b> when looking out their windows.<br />Having <b>smaller</b> skyscrapers around them supports the <b>"Panorama Effect"</b>; skyscrapers that are <b>taller or of equal height</b> reduces the effect.<br /><br />The stronger the "Panorama Effect", the <b>higher the population</b> within the skyscraper will be!': 'תושבי גורדי שחקים אוהבים ליהנות מ<b>נוף פנורמי ללא הפרעה</b> כשהם מביטים מחלונותיהם.<br />הימצאותם של גורדי שחקים <b>קטנים יותר</b> סביבם תומכת ב<b>"אפקט הפנורמה"</b>; גורדי שחקים שהם <b>גבוהים יותר או בגובה שווה</b> מפחיתים את האפקט.<br /><br />ככל ש"אפקט הפנורמה" חזק יותר, כך <b>האוכלוסייה תהיה גבוהה יותר</b> בתוך גורד השחקים!',
    "Tutorial — The Panorama Effect": "הדרכה — אפקט הפנורמה",
    "Create on any Skyscraper: <br />2 x Intense Panorama Effects": "צור על כל גורד שחקים: <br />2 x אפקטי פנורמה עזים",
    "All Investor Skyscrapers": "כל גורדי השחקים של המשקיעים",
    "The investor explains the Panorama Effect.": "המשקיע מסביר את אפקט הפנורמה.",
    "The investor is impressed at your skyscraper's intense Panorama Effect.": "המשקיע מתרשם מאפקט הפנורמה העז של גורד השחקים שלך.",
    "Surely a higher skyscraper surrounded by lower ones would provide the best panoramas of the city?": "בוודאי גורד שחקים גבוה יותר המוקף בנמוכים יותר יספק את הפנורמות הטובות ביותר של העיר?",
    "A truly intense panorama of the city! Reserve an apartment for me at the top, I'd love to be the envy of others!": "פנורמה מדהימה באמת של העיר! שיין לי דירה למעלה, אשמח להיות מושא לקנאתם של אחרים!",
    "Skyscraper residents like to have an unobstructed, panoramic view when looking through their windows.": "תושבי גורדי שחקים אוהבים ליהנות מנוף פנורמי ללא הפרעה כשהם מביטים מחלונותיהם.",
    "Having smaller skyscrapers nearby supports the \"Panorama Effect\". Skyscrapers that are taller, or of equal height reduces the effect.": "הימצאותם של גורדי שחקים קטנים יותר בקרבת מקום תומכת ב\"אפקט הפנורמה\". גורדי שחקים שהם גבוהים יותר, או בגובה שווה, מפחיתים את האפקט.",
    "To achieve an intense Panorama Effect, build five level 1 skyscrapers around one level 2 skyscraper.": "כדי להשיג אפקט פנורמה עז, בנה חמישה גורדי שחקים ברמה 1 סביב גורד שחקים אחד ברמה 2.",
    "Investor Residence 0/1": "בית מגורים של משקיעים 0/1",
    "Donny says the vandal no longer needs to be caught.": "דוני אומר שכבר אין צורך לתפוס את הוונדל.",
    "Ha! You can drop that case! The scandal the vandals hoped for was the proverbial bad publicity we needed to top out our sales!": "חה! אתה יכול לעזוב את התיק הזה! הסקנדל שהוונדלים קיוו לו היה הפרסום השלילי המפורסם שהיינו צריכים כדי להזניק את המכירות שלנו!",
    'The "vanity screen with the red and white logo," is the talk of the town! Well, I’ve decided to follow their model. I\'ve made that graffito our new brand logo!': '"הפרגוד עם הלוגו האדום והלבן" הוא שיחת היום! ובכן, החלטתי לעקוב אחר המודל שלהם. הפכתי את הגרפיטי הזה ללוגו המותג החדש שלנו!',
    "Angry worker you caught, was it? Predictable. But I have half a mind to thank him for his work pro bono! Worked wonders for our sales, you know!": "זה היה פועל כועס שתפסת, הא? צפוי. אבל בא לי פשוט להודות לו על עבודתו בהתנדבות! זה עשה פלאים למכירות שלנו, אתה יודע!",
    "Failed to catch 'em? No harm done— this is your initiation in the big dog ad campaign club. Go ahead, my treat— take the poster as a trophy.": "נכשלת בתפיסתם? לא נורא — זו טבילת האש שלך במועדון של מנהלי מסעי הפרסום הגדולים. קדימה, עליי — קח את הכרזה כפרס.",
    "You really came though for us with these posters. I knew you would. Here's an original for you to keep— your design after all!": "באמת שיחקת אותה בשבילנו עם הכרזות האלה. ידעתי שתעשה זאת. הנה כרזה מקורית שתוכל לשמור — העיצוב שלך אחרי הכל!",
    "Donny says the vandal you caught created a positive buzz.": "דוני אומר שהוונדל שתפסת יצר באז חיובי.",
    "Donny will reuse the vandal's graffiti for his brand logo.": "דוני יעשה שימוש חוזר בגרפיטי של הוונדל עבור לוגו המותג שלו.",
    "Donny gifts you the defaced posters Theodora doubtless collected.": "דוני מעניק לך את הכרזות המושחתות שתיאודורה ללא ספק אספה.",
    "Donny gifts you back one of your own posters.": "דוני מעניק לך בחזרה את אחת הכרזות שלך.",
    "Vandalised Vanity Screen Advertisement": "מודעת פרגוד מושחתת",
    "Original Vanity Screen Advertisement": "מודעת פרגוד מקורית",
    "It's your vanity screen poster! But most of your design's been obscured by the vandal’s artistic additions — a red and white logo of a falling man. Some say it's a bad omen...": "זו כרזת הפרגוד שלך! אבל רוב העיצוב שלך טושטש על ידי התוספות האמנותיות של הוונדל — לוגו אדום ולבן של איש נופל. יש האומרים שזה סימן רע...",
    "It's your vanity screen poster in all its glory — and what a slogan! This is one of the few that was not defaced. A rare original!": "זו כרזת הפרגוד שלך במלוא תפארתה — ואיזה סלוגן! זו אחת הבודדות שלא הושחתו. מקור נדיר!",
    "DLC: Going Up!": "DLC: עולים למעלה!",
    "Build three engineer and three investor skyscrapers (The High Life).": "בנה שלושה גורדי שחקים של מהנדסים ושלושה של משקיעים (High Life).",
    "Industrial Espionage: The Tail": "ריגול תעשייתי: המעקב",
    "Miss Jenny": "מיס ג'ני",
    "Accounting found discrepancies. I don't like to point the finger, but sounds like Miss Jenny's spritzing our budget on personal endeavours. I think you're more discreet than me, think you can check?": "מחלקת הנהלת חשבונות מצאה אי-תאימויות. אני לא אוהב להאשים סתם, אבל נשמע שמיס ג'ני מבזבזת את התקציב שלנו על מאמצים אישיים. אני חומר דיסקרטי יותר ממני, אתה חושב שתוכל לבדוק?",
    "These are changing times, partner. Industrial secrets are worth their weight, and I’m not about to chip away at my worth.": "אלו זמנים משתנים, שותף. סודות תעשייתיים שווים את משקלם, ואני לא מתכוון לפגוע בערך שלי.",
    "Donny is suspicious of Theodora, and asks you to follow her.": "דוני חושד בתיאודורה, ומבקש ממך לעקוב אחריה.",
    "Donny says this could harm his reputation.": "דוני אומר שזה עלול לפגוע במוניטין שלו.",
    "Mr. Bader has been made aware of inconsistencies in the office’s budget reports. He suspects that Miss Jenny (a.k.a. Theodora) might be using the money for her own purposes. Not only would she be disobeying his instructions, but he’s also worried that she might be leaking industrial secrets, endangering the worth of his brand. He's asked you to spy on her.": "מר ביידר קיבל מידע על חוסר עקביות בדוחות התקציב של המשרד. הוא חושד שמיס ג'ני (הידועה גם כתיאודורה) עשויה להשתמש בכסף למטרותיה שלה. לא זו בלבד שהיא תפר את הוראותיו, אלא שהוא גם חושש שהיא מדליפה סודות תעשייתיים, מה שמסכן את שווי המותג שלו. הוא ביקש ממך לרגל אחריה.",
    "Miss Jenny should be in her office, somewhere near an Engineer skyscraper.": "מיס ג'ני צריכה להיות במשרד שלה, אי שם ליד גורד שחקים של מהנדסים.",
    "<b>Tailing the Engineer</b><br />Find Miss Jenny in [Area Area([Conditions QuestArea]) CityName]": "<b>לעקוב אחר המהנדסת</b><br />מצא את מיס ג'ני ב-[Area Area([Conditions QuestArea]) CityName]",
    "<i>Hint: she should be in her office, next to an Engineer skyscraper</i>": "<i>רמז: היא צריכה להיות במשרד שלה, ליד גורד שחקים של מהנדסים</i>",
    "Industrial Spying: Tailing": "ריגול תעשייתי: המעקב",
    "Mystery Broker": "מתווך מסתורי",
    "I must hurry! Oh, I do hope the harbour was a good spot to pick...": "אני חייבת למהר! הו, אני באמת מקווה שהנמל היה מקום טוב לבחור בו...",
    "<b>Tailing the Engineer</b><br />Follow and listen to Miss Jenny": "<b>לעקוב אחר המהנדסת</b><br />עקוב אחר מיס ג'ני והקשב לה",
    "Just wait and listen to Miss Jenny until she meets with a mystery character.": "פשוט המתן והקשב למיס ג'ני עד שהיא תיפגש עם דמות מסתורית.",
    "Skyscraper Ornaments": "קישוטי גורדי שחקים",
    "Small Spotlight": "זרקור קטן",
    "Large Spotlight": "זרקור גדול",
    "Skyscraper Model": "דגם גורד שחקים",
    "Hot-Air Balloon": "כדור פורח",
    "City Fountain": "מזרקת עיר",
    "Tower Billboard": "שלט חוצות של המגדל",
    "It really would have been preferable to acquire the oils on my own terms, but he seems <i>trustworthy</i>.": "באמת היה עדיף להשיג את השמנים בתנאים שלי, אבל הוא נראה <i>אמין</i>.",
    "Keep <b>listening</b>": "המשך <b>להקשיב</b>",
    "I’d hoped the prospect of a whole new customer demographic would sway him, but this could be so much more...! Men shouldn’t hold a monopoly on the modern. Modern conveniences can be tools <b>for social emancipation</b>. Products like mine can normalise women running their own budgets, having agency in the world of commerce.<br /><br />The projected sales figures might yet convince him, but I desperately need to finish the prototype first. Will you <b>help me</b>?": "קיוויתי שהאפשרות לפלח לקוחות חדש לחלוטין תניא אותו, אבל זה יכול להיות כל כך הרבה יותר...! לגברים לא צריך להיות מונופול על המודרני. נוחות מודרנית יכולה לשמש ככלי <b>לשחרור חברתי</b>. מוצרים כמו שלי יכולים לנרמל נשים שמנהלות תקציבים משלהן, ושיש להן סוכנות בעולם המסחר.<br /><br />נתוני המכירות החזויים עשויים עוד לשכנע אותו, אבל אני חייבת קודם כל לסיים את אב הטיפוס. האם <b>תעזור לי</b>?",
    "You're damn right Theodora, something needs to change. <b>I'm in.</b>": "את לגמרי צודקת תיאודורה, משהו צריך להשתנות. <b>אני בפנים.</b>",
    "Miss Jenny! Using Mr. Bader’s funds for personal gain?! <b>I have to report this!</b>": "מיס ג'ני! להשתמש בכספים של מר ביידר לטובתך האישית?! <b>אני חייב לדווח על כך!</b>",
    "Industrial Espionage: Double Agent": "ריגול תעשייתי: סוכן כפול",
    "Industrial Espionage: Loyalties": "ריגול תעשייתי: נאמנויות",
    "Such a relief! I had a feeling you might be of open mind. Mr. Bader, of course, thinks you two are like peas in a pod, but then he only ever sees half the picture.": "זו הקלה עצומה! הייתה לי תחושה שאתה עשוי להיות בעל ראש פתוח. מר ביידר, כמובן, חושב ששניכם מתאימים כמו כפפה ליד, אבל הוא תמיד רואה רק חצי מהתמונה.",
    "I'm no longer surprised Mr. Bader thinks of you as one of his betters. You're all the same as far as I'm concerned— do what you must.": "אני כבר לא מופתעת מכך שמר ביידר חושב עליך כאחד מאנשיו המועדפים. כולכם אותו הדבר מבחינתי — עשה מה שאתה חייב.",
    "Theodora is relieved you chose to support her.": "תיאודורה מוקסמת מכך שבחרת לתמוך בה.",
    "Theodora is used to people going against her wishes.": "תיאודורה רגילה לכך שאנשים הולכים נגד רצונה.",
    "Who’d have thought funny little Miss Jenny could be so daring? Wait, is that Brokeman!? That's my lawyer! Well, you give 'em an inch and they take a mile— seems the guy used his vacation to grow a spine...": "מי היה מאמין שמיס ג'ני הקטנה והמצחיקה יכולה להיות כל כך נועזת? רגע, זה ברוקמן?! זה עורך הדין שלי! ובכן, נותנים להם אצבע והם רוצים את כל היד — נראה שהבחור ניצל את החופשה שלו כדי לגדל עמוד שדרה...",
    "Donny is surprised to discover his lawyer is involved.": "דוני מופתע לגלות שעורך הדין שלו מעורב.",
    "Pretty sure my lawyer grows weary of his vacation— can hardly be relaxing with treason on his mind. Cut it short would you?": "די בטוח שעורך הדין שלי עייף מהחופשה שלו — קשה להירגע כשבגידה עומדת על הפרק. קצר אותה, טוב?",
    "Achieve the toasters, crockery and vacuum cleaners bonus effect for at least 150 residences at the same time (The High Life).": "השג את אפקט הבונוס של המצנמים, כלי האוכל ושואבי האבק עבור לפחות 150 בתי מגורים בו-זמנית (High Life).",
    "Build the Skyline Tower (The High Life).": "בנה את מגדל קו הרקיע (High Life).",
    "Organize a Plan B with Miss Jenny during the Skyline Tower quest (The High Life).": "ארגן תוכנית ב' עם מיס ג'ני במהלך משימת מגדל קו הרקיע (High Life).",
    "Have 10 Intense Panorama Effects in your investor skyscrapers at the same time (The High Life).": "החזק ב-10 אפקטי פנורמה עזים בגורדי השחקים של המשקיעים שלך בו-זמנית (High Life).",
    "Have 3,400 investors living in the Skyline Tower (The High Life).": "החזק ב-3,400 משקיעים המתגוררים במגדל קו הרקיע (High Life).",
    "DLC: It's Black Friday!": "DLC: יום שישי השחור!",
    "DLC: Reach for the Stars – Almost!": "DLC: להגיע לכוכבים — כמעט!",
    "DLC: Better Safe Than Sorry": "DLC: ללכת על בטוח",
    "DLC: 360° Panorama!": "DLC: פנורמה 360°!",
    "DLC: Tower Of Power": "DLC: מגדל העוצמה",
    "I recall him mentioning a fancy cruise ship. Looks like his next item on the docket is a surprise pick-up.": "אני זוכר שהוא הזכיר ספינת תענוגות מפוארת. נראה שהסעיף הבא שלו על סדר היום הוא איסוף בהפתעה.",
    "Theodora asks you to deliver materials for her research.": "תיאודורה מבקשת ממך לספק חומרים למחקר שלה.",
    "Donny asks you to put a summons on his lawyer.": "דוני מבקש ממך למסור זימון לעורך הדין שלו.",
    "Donny recalls his lawyer planned to go on a cruise.": "דוני זוכר שעורך הדין שלו תכנן לצאת לשיט.",
    "Mr. Brokeman had agreed to supply specific oils I required for a new patent I'm developing. As you know, he did not deliver, and without them I am stumped...can you help?": "מר ברוקמן הסכים לספק שמנים ספציפיים שהייתי צריכה עבור פטנט חדש שאני מפתחת. כפי שאתה יודע, הוא לא סיפק אותם, ובלעדיהם אני תקועה... תוכל לעזור?",
    "Time is of the essence, now. Mr. Bader's already suspicious, and if there's any hope of making this product on my own terms... it must be underway before he is alerted.": "הזמן דוחק כעת. מר ביידר כבר חושד, ואם יש תקווה כלשהי לייצר את המוצר הזה בתנאים שלי... זה חייב לצאת לדרך לפני שהוא יוזהר.",
    "Theodora urges you to deliver the goods quickly, before Mr. Bader finds out.": "תיאודורה מפצירה בך לספק את הסחורה במהירות, לפני שמר ביידר יגלה זאת.",
    "All Skyscrapers": "כל גורדי השחקים",
    "Miss Jenny – or rather, Theodora - has persuaded you that her female-oriented product could help modernise society, and provide a much-needed first step towards female emancipation. She’s asked that you provide her with the oils she needs to complete her patent — but you'll have to hurry and deliver them before Mr. Bader catches you in the act!": "מיס ג'ני — או ליתר דיוק תיאודורה — שכנעה אותך שהמוצר המיועד לנשים שלה יכול לעזור למודרניזציה של החברה, ולספק צעד ראשון ונחוץ לקראת שחרור נשי. היא ביקשה שתספק לה את השמנים שהיא צריכה כדי להשלים את הפטנט שלה — אבל תצטרך למהר ולספק אותם לפני שמר ביידר יתפוס אותך בשעת מעשה!",
    "Phew, just in time! I will use it right away— it was only meant to be the last little tweak to finish the prototype...": "פיו, ממש בזמן! אשתמש בזה מיד — זה היה אמור להיות רק הכוונון הקטן האחרון כדי לסיים את אב הטיפוס...",
    "Theodora begs your patience as she finalises the patent.": "תיאודורה מבקשת את סבלנותך בזמן שהיא משלימה את הפטנט.",
    "My newest patent! You’ve earned a look – The Lipstick! Now, to persuade Mr. Bader... Once stocked at the Drug Store, it can fulfill its intended purpose!": "הפטנט החדש שלי! הרווחת הצצה — השפתון! כעת, נותר לשכנע את מר ביידר... ברגע שימולא במלאי בבית המרקחת, הוא יוכל למלא את ייעודו המתוכנן!",
    "Theodora is proud to unveil her lipstick patent.": "תיאודורה גאה לחשוף את פטנט השפתון שלה.",
    "Bit of a surprise you kept your involvement a secret, guru. You think her kind can be big players in the world of commerce? I suppose I'm going to have to hold up my hands and trust your superior instincts.": "די מפתיע ששמרת על מעורבותך בסוד, גורו. אתה חושב שסוג האנשים שלה יכולים להיות שחקנים גדולים בעולם המסחר? אני מניח שאאלץ להרים ידיים ולסמוך על האינסטינקטים המעולים שלך.",
    "Donny is surprised you supported Theodora in secret.": "דוני מופתע מכך שתמכת בתיאודורה בסתר.",
    "Donny is enthused by how cheap the lipstick was to develop.": "דוני נלהב מכך שפיתוח השפתון היה כה זול.",
    "Bit of luck this lipstick stuff is a goer, and a bargain! The lab has found ways to produce it more cheaply than expected.": "איזה מזל שעניין השפתון הזה עובד, וזו מציאה! המעבדה מצאה דרכים לייצר אותו בזול יותר מהצפוי.",
    "Donald is outraged that his employees would have the gall to make deals behind his back — with his own money at that! But he's got a plan, the first step of which is to cut Mr. Brokeman's holiday short, and bring him into the office for a chat. He's delegated that task to you.": "דונלד זועם על כך שלעובדיו יש את החוצפה לבצע עסקאות מאחורי גבו — ועוד בכסף שלו! אבל יש לו תוכנית, שהשלב הראשון שלה הוא לקצר את חופשתו של מר ברוקמן, ולהביא אותו למשרד לשיחה. הוא הטיל את המשימה הזו עליך.",
    "Sepia Dream Cruises & Co.": "Sepia Dream Cruises & Co.",
    "Dolphins": "דולפינים",
    "Jellyfish": "מדוזות",
    "Pick up Mr. Brokeman at his cruise ship": "אסוף את מר ברוקמן מספינת התענוגות שלו",
    "Bring Mr. Brokeman back to [Area Area([Conditions QuestArea]) CityName] harbour": "החזר את מר ברוקמן לנמל [Area Area([Conditions QuestArea]) CityName]",
    "William Brokeman, a lawyer": "ויליאם ברוקמן, עורך דין",
    "William Brokeman, the Lawyer": "ויליאם ברוקמן, עורך הדין",
    "The broker who supported Miss Jenny in her research. He looks longingly at his cruise ship as it glides away, before turning to face his fate...": "המתווך שתמך במיס ג'ני במחקר שלה. הוא מביט בגעגוע בספינת התענוגות שלו כשהיא מפליגה לדרכה, לפני שהוא פונה לעבר גורלו...",
    "Brokeman Drowning": "טביעת ברוקמן",
    "A local investor has big dreams of building the city skywards. The invention of elevators has filled him with excitement, and he’s eager to join you in paving the way towards skyscraper construction.": "למשקיע מקומי יש חלומות גדולים לבנות את העיר כלפי מעלה. המצאת המעליות מילאה אותו בהתרגשות, והוא להוט להצטרף אליך בסלילת הדרך לבניית גורדי שחקים.",
    "With enough elevators in stock, nothing is standing in the way of building your first skyscraper.": "עם מספיק מעליות במלאי, דבר לא עומד בדרך לבניית גורד השחקים הראשון שלך.",
    "The keen local investor sees shopping arcades as the next big investment opportunity. A department store would be the perfect start. Others will surely follow.": "המשקיע המקומי הנלהב רואה בפסז'י קניות את הזדמנות ההשקעה הגדולה הבאה. חנות כלבו תהיה ההתחלה המושלמת. אחרים בוודאי יבואו בעקבותיה.",
    "Who wouldn’t be disappointed when looking out their 14th floor windows just to face a brick wall? Having a panoramic view of the city makes for a much better view, and would certainly attract more people!": "מי לא יתאכזב כשיביט מחלונות הקומה ה-14 שלו רק כדי לעמוד מול קיר לבנים? נוף פנורמי של העיר מספק מראה טוב בהרבה, ובוודאי ימשוך יותר אנשים!",
    "I knew Bader'd be furious but... <i>sweet mercy.</i> I yield! I promise, I’ll spill everything!<br /><br />Just get me out of the water!": "ידעתי שביידר ירתח אבל... <i>רחמים מתוקים.</i> אני נכנע! אני מבטיח, אספר הכל!<br /><br />רק תוציאו אותי מהמים!",
    "Drowning was his idea of a joke? My poor heart... You know, I can’t say I’m surprised. He always has had his own ways of dealing with insubordination... At least I'm still alive. That's <i>something.</i>": "טביעה הייתה הרעיון שלו לבדיחה? ליבי המסכן... אתה יודע, אני לא יכול לומר שאני מופתע. תמיד היו לו דרכים משלו להתמודד עם סרבנות... לפחות אני עדיין בחיים. זה <i>משהו.</i>",
    "Mr. Brokeman is dismayed his holiday has been interrupted.": "מר ברוקמן מתוסכל מכך שחופשתו הופרעה.",
    "Mr. Brokeman asks if he really must come with you.": "מר ברוקמן שואל אם הוא באמת חייב לבוא איתך.",
    "You’re looking for a Mr. Brokeman?... Well that's me. Mr. Bader needs to see me? I-is it really so urgent, I’m on holiday…": "אתה מחפש את מר ברוקמן?... ובכן זה אני. מר ביידר צריך לראות אותי? ה-האם זה באמת כל כך דחוף, אני בחופשה...",
    "I normally give Mr. Bader space when he's having one of his little tantrums. It’s the reason I’m still his lawyer and I’d like to keep it that way. Are you sure I need to see him now?": "אני בדרך כלל נותן למר ביידר מרחב כשהוא חוטף את אחד מהתקפי הזעם הקטנים שלו. זו הסיבה שאני עדיין עורך הדין שלו ואני רוצה לשמור על זה כך. אתה בטוח שאני צריך לראות אותו עכשיו?",
    "I’m unsurprised my vacation's being cut short... Mr. Bader is choleric at the best of times though usually not without cause...": "אני לא מופתע מכך שהחופשה שלי מתקצרת... מר ביידר הוא חם מזג ברוב הזמן אם כי בדרך כלל לא ללא סיבה...",
    "Dora’s idealism is rare. Maybe I was hoping that, by helping her, I could reclaim some of my own drive. I'm tired. Really tired.": "האידיאליזם של דורה הוא נדיר. אולי קיוויתי שעל ידי עזרה לה, אוכל להחזיר לעצמי חלק מהמוטיבציה שלי. אני עייף. באמת עייף.",
    "I knew Mr. Bader would never appreciate the virtues of this product. Immediate gains are his sole measure of success, blind to other kinds of worth, not like Dora...": "ידעתי שמר ביידר לעולם לא יעריך את מעלותיו של המוצר הזה. רווחים מיידיים הם מדד ההצלחה היחיד שלו, עיוור לסוגים אחרים של ערך, לא כמו דורה...",
    "Mr. Brokeman knows why he has been summoned.": "מר ברוקמן יודע מדוע הוא זימן.",
    "Mr. Brokeman reveals his reasons for helping Theodora.": "מר ברוקמן חושף את סיבותיו לעזור לתיאודורה.",
    "Mr. Brokeman says Bader would never have supported Theodora.": "מר ברוקמן אומר שביידר לעולם לא היה תומך בתיאודורה.",
    "Well, the only way out of this is through...": "ובכן, הדרך היחידה לצאת מזה היא לעבור דרך זה...",
    "Mr. Brokeman feels he has no choice but to meet Bader.": "מר ברוקמן מרגיש שאין לו ברירה אלא לפגוש את ביידר.",
    "Listen to: [AssetData([RefGuid]) Text]": "הקשב ל: [AssetData([RefGuid]) Text]",
    "Spy on: [AssetData([RefGuid]) Text]": "רגל אחר: [AssetData([RefGuid]) Text]",
    "Industrial Espionage: Lawsuit": "ריגול תעשייתי: תביעה משפטית",
    "Ah, Mr. Brokeman, how was the vacation? Miss work? You must have— got yourself into a bit of a muddle with my assistant, didn't you?": "אה, מר ברוקמן, איך הייתה החופשה? התגעגעת לעבודה? בטוח שכן — נכנסת לקצת בלבול עם העוזרת שלי, לא?",
    "Donny humiliates his lawyer.": "דוני משפיל את עורך הדין שלו.",
    "Well Brokeman, now you have unique insight into this conspiracy against my company, you can file the case against her. So, get your papers together and show me whose side you're on.": "ובכן ברוקמן, כעת כשיש לך תובנה ייחודית לקנוניה הזו נגד החברה שלי, אתה יכול להגיש את התביעה נגדה. אז, אסוף את המסמכים שלך והראה לי באיזה צד אתה.",
    "Theodora says the materials for the patent have been stolen!": "תיאודורה אומרת שהחומרים עבור הפטנט נגנבו!",
    "Donny asks if his production schedule will be disrupted.": "דוני שואל אם לוח הזמנים של הייצור שלו ישתבש.",
    "Theodora cannot work without those materials.": "תיאודורה אינה יכולה לעבוד ללא החומרים הללו.",
    "In these hallowed halls, high quality pieces are made using traditional processes. Still, with the aid of modern tools, their creation is hastened, so that more can enjoy the fruits of the artisan’s labor.": "בהיכלות מקודשים אלה, יצירות באיכות גבוהה מיוצרות בתהליכים מסורתיים. עם זאת, בעזרת כלים מודרניים, יצירתן מואצת, כך שיותר אנשים יוכלו ליהנות מפירות עמלו של האומן.",
    "Market Research: Demand Vacuum": "מחקר שוק: ואקום ביקוש",
    "Perhaps you can replace the missing goods, guru, you know, keep up your side of the bargain? Not sure I trust Miss Jenny to do it on current form...": "אולי תוכל להחליף את הסחורות החסרות, גורו, אתה יודע, לעמוד בצד שלך בעסקה? לא בטוח שאני סומך על מיס ג'ני שתעשה זאת במצבה הנוכחי...",
    "Darn it, this is stalling us. Wasted time, wasted money, Miss Jenny— my partner and I will have to look at your salary, won't we?": "לעזאזל, זה מעכב אותנו. בזבוז של זמן, בזבוז של כסף, מיס ג'ני — השותף שלי ואני נצטרך לבחון את המשכורת שלך, לא כך?",
    "Currently, this department store is not selling anything. <b>Open the shopping catalogue to choose a design patent.</b>": "כעת, חנות כלבו זו אינה מוכרת דבר. <b>פתח את קטלוג הקניות כדי לבחור פטנט עיצוב.</b>",
    "Here you can see <b>every Department Store design patent</b>. Right now, only one is available, but you can unlock new ones later.<br />Click on the first one to <b>jump directly to it</b>.": "כאן תוכל לראות את <b>כל פטנטי העיצוב של חנות הכלבו</b>. כרגע רק אחד זמין, אך תוכל לפתוח חדשים בהמשך.<br />לחץ על הראשון כדי <b>לקפוץ ישירות אליו</b>.",
    "Donny will recoup his losses from Theodora’s salary.": "דוני יקזז את הפסדיו ממשכורתה של תיאודורה.",
    "Donny would prefer if you replaced the goods.": "דוני יעדיף שאתה תחליף את הסחורות.",
    "Due to the theft of the required goods for the patents, your research has come to a halt. It seems things will remain that way until you deliver the new goods to Miss Jenny (Theodora).": "בשל גניבת הסחורות הנדרשות עבור הפטנטים, המחקר שלך נעצר. נראה שהדברים יישארו כך עד שתספק את הסחורות החדשות למיס ג'ני (תיאודורה).",
    "Donny suspects his rivals were involved.": "דוני חושד שהמתחרים שלו היו מעורבים.",
    "Likely an eager rival trying to tweak his odds. I'm used to slander, it is part and parcel of the business, but that a peer would stoop to thievery. Embarrassing.": "קרוב לוודאי שזה מתחרה נלהב שמנסה לשפר את סיכוייו. אני רגיל להשמצות, זה חלק בלתי נפרד מהעסק, אבל שקולגה ידרדר לגנבה. מביך.",
    "Lose Island": "להפסיד את האי",
    "Lose Lab": "להפסיד את המעבדה",
    "<i>Furniture</i>, <i>quality</i>, and a <i>drink</i>?... Um, a <b>mini bar</b>?": "<i>רהיטים</i>, <i>איכות</i> ו<i>משקה</i>?... אממ, <b>מיני בר</b>?",
    "<i>”...the height of etiquette”</i>": "<i>”...היא שיא הנימוס והחן”</i>",
    "<i>”...life is a cabaret”</i>": "<i>”...החיים הם קברט”</i>",
    '<font size="32"><b>The height of etiquette!</b></font>': '<font size="32"><b>שיא הנימוס והחן!</b></font>',
    '<font size="32"><b>Life is a cabaret!</b></font>': '<font size="32"><b>החיים הם קברט!</b></font>',
    "You can change a shopping arcade's active patent by selecting the corresponding option in the building menu.": "תוכל לשנות את הפטנט הפעיל של פסז' הקניות על ידי בחירת האפשרות המתאימה בתפריט הבנייה.",
    "The vanity screen patent must be equipped in a furniture store on the right island.": "יש להצטייד בפטנט הפרגוד בחנות רהיטים באי הנכון.",
    "Ensure you have enough of the required goods in stock to reach the desired level of productivity.": "ודא שיש לך מספיק מהסחורות הנדרשות במלאי כדי להגיע לרמת הפריון הרצויה.",
    "Donny congratulates himself for Theodora’s hard work.": "דוני מברך את עצמו על עבודתה הקשה של תיאודורה.",
    "The posters are up— can't be missed! I gave Miss Jenny some time off, she didn't look her usual self...": "הכרזות תלויות — אי אפשר לפספס! נתתי למיס ג'ני קצת חופש, היא לא נראתה כמו עצמה בדרך כלל...",
    "What a debacle! Our promising posters have been defaced by some deviant boheme. Look here, it's all over the papers!": "איזו מפלה! הכרזות המבטיחות שלנו הושחתו על ידי בוהמייני סורר כלשהו. תראה כאן, זה בכל העיתונים!",
    "Donny is angry his posters were vandalised.": "דוני כעס על כך שהכרזות שלו הושחתו.",
    "LUXURY BRAND GETS BRANDED!": "מותג יוקרה מוכתם!",
    "Trouble in paradise for Galeria Baderette Shopping Arcade in [Area Area([RefGuid]) CityName]. Eye-catching poster campaign announcing brand-new vanity screen vandalised from top-to-bottom! Questions remain whether sales will now go up or down as a result of the extra publicity...": "צרות בגן עדן עבור פסז' הקניות גלריית ביידרט ב-[Area Area([RefGuid]) CityName]. מסע פרסום של כרזות מושכות עין המכריז על פרגוד חדש לגמרי הושחת מלמעלה עד למטה! השאלות נותרו האם המכירות יעלו או ירדו כעת כתוצאה מהפרסום הנוסף...",
    "For someone so focused on modernisation, Mr. Bader is peculiarly blind to the future. <i>‘Women don’t shop!’</i>. Well, I wonder why?!": "עבור מישהו שכל כך ממוקד במודרניזציה, מר ביידר עיוור באופן מוזר לעתיד. <i>‘נשים לא עושות קניות!’</i>. ובכן, מעניין למה?!",
    "So much on my mind, and it’s all spilling out... <i>Come on, Theodora, take a breath and hurry along!</i> It'll all be over soon...": "כל כך הרבה דברים על הראש שלי, והכל נשפך החוצה... <i>קדימה, תיאודורה, קחי נשימה ותזדרזי!</i> הכל ייגמר בקרוב...",
    "Sometimes you may just find yourself in it.": "לפעמים אתה עשוי פשוט למצוא את עצמך בתוך זה.",
    "Help part of your city to shine.": "עזור לחלק מהעיר שלך לזרוח.",
    "The small version of the towering marvel. Still tall enough to provide enough shade to rest.": "הגרסה הקטנה של הפלא הנישא. עדיין גבוהה מספיק כדי לספק מספיק צל למנוחה.",
    "Up, up, and away!": "למעלה, למעלה, והלאה!",
    "A soothing breeze surrounds the fountain, where people sigh as they pass by.": "בריזה מרגיעה מקיפה את המזרקה, שבה אנשים נאנחים כשהם חולפים על פניה.",
    "To commemorate, or perhaps advertise, the Skyline Tower.": "להנצחת, או אולי לפרסום, מגדל קו הרקיע.",
    "Children gleefully zig-zag between fountains, trying to avoid the water, or hoping to get caught!": "ילדים מזגזגים בעליזות בין המזרקות, מנסים להימנע מהמים, או מקווים להירטב!",
    "All Moderate Kontors": "כל משרדי המסחר הממוזגים",
    "Oh, Mr. Brokeman! There you are! Very punctual...": "או, מר ברוקמן! הנה אתה! דייקן מאוד...",
    "Dora... Please, <i>forgive</i> me. I... I don’t have the oils you asked for.": "דורה... בבקשה, <i>סלחי</i> לי. אני... אין לי את השמנים שביקשת.",
    "...Mr. Bader's doing, I presume?": "...מעשה ידיו של מר ביידר, אני מניח?",
    "Yes, I... he’s having me watched. I can feel it. I want to help, but I can’t lose my livelihood over this... You understand?": "כן, אני... הוא עוקב אחריי. אני יכול להרגיש את זה. אני רוצה לעזור, אבל אני לא יכול לאבד את הפרנסה שלי בגלל זה... את מבינה?",
    "<i>Psst, 'Dora!</i>": "<i>פססט, 'דורה!</i>",
    "Industrial Espionage: Incriminating Evidence": "ריגול תעשייתי: ראיות מפלילות",
    "You followed Miss Jenny to a private meeting with a mystery man by the name of \"Mr. Brokeman.\" There you uncovered that he had promised to supply her with goods for a secret patent project she appears to have undertaken without permission. Taking a picture of the meeting would be the perfect proof of her deception for Mr. Bader.": "עקבת אחרי מיס ג'ני לפגישה פרטית עם איש מסתורי בשם \"מר ברוקמן\". שם גילית שהוא הבטיח לספק לה סחורות עבור פרויקט פטנט סודי שנראה שהיא יזמה ללא אישור. צילום של הפגישה יהיה ההוכחה המושלמת להונאה שלה עבור מר ביידר.",
    "<b>Tailing the Engineer</b><br />Photograph Miss Jenny's private meeting": "<b>לעקוב אחר המהנדסת</b><br />צלם את הפגישה הפרטית של מיס ג'ני",
    "WAIT, WHAT WAS THAT!? A CAMERA FLASH!? OH NO... Theodora, you were followed!": "רגע, מה זה היה!? מבזק מצלמה!? אוי לא... תיאודורה, עקבו אחרייך!",
    "Industrial Espionage: Theodora's Plea": "ריגול תעשייתי: תחינתה של תיאודורה",
    "Listen to Miss Jenny": "הקשב למיס ג'ני",
    "Theodora implores you to hear her out.": "תיאודורה מפצירה בך להקשיב לה.",
    "Oh, he sent you... Please, at least allow me to clarify the situation before you report back to Mr. Bader.": "אוי, הוא שלח אותך... בבקשה, לפחות תן לי להבהיר את המצב לפני שתדווח חזרה למר ביידר.",
    "Having caught Miss Jenny (real name Theodora) red-handed at her private meeting with a broker, she implores you to hear her out before reporting anything back to Mr. Bader. You may as well listen, as either way you have photographic evidence of her secret agenda, and if you still aren't persuaded, you can always grass her up afterwards.": "לאחר שתפסת את מיס ג'ני (שמה האמיתי הוא תיאודורה) על חם בפגישתה הפרטית עם המתווך, היא מפצירה בך להקשיב לה לפני שתדווח על משהו חזרה למר ביידר. מוטב שתקשיב לה, שכן כך או כך יש לך ראיות מצולמות למזימה הסודית שלה, ואם עדיין לא השתכנעת, תמיד תוכל להלשין עליה לאחר מכן.",
    "Secrecy was my last resort! <b>I pitched my patent to Mr. Bader</b>, used reasoned arguments — said this would attract women; customers! — in their droves to the shopping arcades... But <b>he flat-out refused.</b> He said it was an empty market!”<br /><br />Well he’s wrong. It’s only an empty market because <i>women have yet to be allowed in</i>! This product would be a gateway for us!": "סודיות הייתה המוצא האחרון שלי! <b>הצגתי את הפטנט שלי בפני מר ביידר</b>, השתמשתי בטיעונים הגיוניים — אמרתי שזה ימשוך נשים; לקוחות! — בהמוניהן לפסז'י הקניות... אבל <b>הוא סירב על הסף.</b> הוא אמר שזה שוק ריק!”<br /><br />ובכן הוא טועה. זה שוק ריק רק בגלל ש<i>עדיין לא הותר לנשים להיכנס</i>! המוצר הזה יהיה שער הכניסה עבורנו!",
}

# Add skips to skip.json
skip_file = "skip.json"
skips = []
if os.path.exists(skip_file):
    try:
        skips = json.load(open(skip_file, encoding="utf-8"))
    except Exception:
        skips = []

skips_set = set(skips)
for s in skips_to_add:
    skips_set.add(s)
new_skips = sorted(list(skips_set), key=lambda x: int(x))
json.dump(new_skips, open(skip_file, "w", encoding="utf-8"), ensure_ascii=False, indent=0)
print(f"Updated skip.json: {len(new_skips)} total skips")

# Clean up other trans_part_*.json files
for i in range(2, 6):
    p = f"trans_part_{i}.json"
    if os.path.exists(p):
        os.remove(p)
        print(f"Deleted old {p}")
for i in range(1, 6):
    p = f"skip_part_{i}.json"
    if os.path.exists(p):
        os.remove(p)
        print(f"Deleted old {p}")

# Translate the batch
translated = {}
missing = []
for guid, val in batch.items():
    if guid in skips_to_add:
        continue
    if val in mapping:
        translated[guid] = mapping[val]
    else:
        # Check if it was stripped by auto_skip or is in skips
        if guid in skips_set:
            continue
        missing.append((guid, val))

if missing:
    print(f"Error: {len(missing)} missing translations in batch!")
    for g, v in missing[:10]:
        print(f"  {g}: {v!r}")
else:
    # Save to trans_part_1.json
    json.dump(translated, open("trans_part_1.json", "w", encoding="utf-8"), ensure_ascii=False, indent=4)
    print(f"Successfully saved {len(translated)} translations to trans_part_1.json")
