import json
import os

handoff = r"C:\Users\Nehoray_Cohen\Projects\Game translator\games\anno1800\agent_handoff"

part1 = {
    "20292": "סטרקסונד",
    "20293": "קיינוואקה",
    "20294": "סנדיסי",
    "20295": "פורטה די סקווינזו",
    "20296": "סקורסטרו",
    "20297": "ואדוקאסה",
    "20298": "אונטרנטו",
    "20299": "פרושוטו",
    "20300": "קיארודרו",
    "20301": "גורג'ינו",
    "20302": "גרימן",
    "20303": "וולסוון",
    "20304": "סטנהאוזן",
    "20305": "קולצבון",
    "20306": "וסונגן",
    "20307": "פאלבייט",
    "20308": "טאסינארו",
    "20309": "סאלוסינוס",
    "20310": "דון גאלוש",
    "20311": "לס ברננדראס",
    "20312": "הוילייו",
    "20313": "לאסטניאס",
    "20314": "אלפגר",
    "20315": "וסטאנייאן",
    "20316": "דאנדאנמור",
    "20317": "קרוגפורד",
    "20318": "מקלוב",
    "20319": "טאריק",
    "20320": "באלטיוויי",
    "20323": "בתי מגורים שבהם הצורך ב-[ItemAssetData([RefGuid]) AllSubstituteNeedsFormatted] מסופק, מקבלים [ItemAssetData([RefGuid]) AllProvidedNeedsFormatted].",
    "20324": "נועל את מניות האי שלך, ומונע מצד אחר לרכוש אותן.",
    "20325": "מוסיף את היכולת לבנות את [ItemAssetData([RefGuid]) AddAssemblyOptionsFormatted].",
    "20326": "בתי מגורים אינם מאבדים עוד שביעות רצון כתוצאה מאובדן מורל במהלך מלחמות איים.",
    "20327": "בכל פעם שמתבצע מסחר פסיבי בתחנת המסחר, קיים סיכוי לקבלת 5 טון של [ItemAssetData([RefGuid]) GoodGenerationPoolFormatted].",
    "20330": "סוקורוס",
    "20331": "פורנו דה פונדו",
    "20332": "פאטוקייטו",
    "20333": "בואנוס ויינטוס",
    "20334": "שולוטה",
    "20335": "סן דוראניו",
    "20336": "ריו דה חואניטה",
    "20337": "טארטאחנה",
    "20338": "פוארטו סלמוארה",
    "20339": "סנטה טונטונה",
    "20340": "בוקארומאנגוס",
    "20341": "סאו מרטליניו",
    "20342": "טולדנוס",
    "20343": "פוארטאולור",
    "20344": "קראקה",
    "20345": "מאסאיין",
    "20346": "דוס חמלאס",
    "20347": "קאלה-אונדידה",
    "20348": "בואנה-קוסטה",
    "20349": "מרייניה",
    "20350": "לה פסקואה",
    "20351": "בוגוטאמפה",
    "20352": "בלה קונקורדיה",
    "20353": "אלטו בארסילוס",
    "20354": "ארסיפה קרבון",
    "20355": "גואראקיו",
    "20356": "בלנקארנאס",
    "20357": "לה אלקסאבטה",
    "20358": "סלמנקסה",
    "20359": "אובינו",
    "20360": "טאמפיקטה",
    "20361": "אוריזאלבה",
    "20362": "פרנה דה לראנז'ה",
    "20363": "סלסה ורדה",
    "20364": "אזורס",
    "20365": "סן סילבסטרה",
    "20366": "בלאנובה",
    "20367": "מהאדוניה",
    "20368": "אלבסטוז",
    "20369": "גאנסו קום פרנאס",
    "20370": "לוקסה",
    "20371": "טאחארחה",
    "20372": "קאפראיה",
    "20373": "וייאובחונה",
    "20374": "מסקונדו",
    "20375": "לה קבאניה",
    "20376": "פאראבימבו",
    "20377": "מאסאפה",
    "20378": "בוניטה לוסיה",
    "20379": "באהיה אסול",
    "20380": "בובימה",
    "20381": "מקאפאוס",
    "20382": "קוריפינאס",
    "20383": "לה פאלמרה",
    "20384": "מדרירה",
    "20385": "גואנטה-אואסטה",
    "20386": "פיפאבאมבה",
    "20387": "טוקופאן",
    "20388": "קורקונה",
    "20389": "קוסטה דלגאדה",
    "20390": "דו באהיה",
    "20391": "פינצ'אקאנטיס",
    "20392": "רודונדוניה",
    "20393": "ארייה פרטה",
    "20394": "ואקאצ'ינצ'יס",
    "20395": "קאלאוס"
}

part2 = {
    "20396": "מריו",
    "20397": "גוואיאטי",
    "20398": "סנטופה",
    "20399": "חאראקאגווה",
    "20400": "אוחארורו",
    "20401": "לה אייאצ'י",
    "20402": "טנגה דה לה האיה",
    "20403": "ריוראלטו",
    "20404": "פולולו",
    "20405": "סנטולומה",
    "20406": "פאלמה סואטו",
    "20407": "אונאטו",
    "20408": "אל אספינו",
    "20409": "לה אורצ'לה",
    "20410": "ארק דה יאגואל",
    "20411": "גראסיה",
    "20412": "טאקאראי",
    "20413": "איגולואגו",
    "20414": "טופיריטו",
    "20415": "לה גוארידה",
    "20416": "קאקומרה",
    "20417": "אספינוסו",
    "20418": "טיגואראן",
    "20419": "ואייאלגרה",
    "20420": "פצ'יקס",
    "20421": "אל בופרו",
    "20422": "טפה גרנדה",
    "20423": "קאלנסיה",
    "20425": "פוסודורו",
    "20426": "פאלאמינגו",
    "20427": "מרידיטה",
    "20428": "מוראקולאו",
    "20429": "פלאקאצ'יקה",
    "20430": "חואנטו",
    "20431": "לארובה",
    "20432": "קאצ'יניקס",
    "20433": "לה בורינאקה",
    "20434": "סורביאלס",
    "20435": "פורטה סואטה",
    "20436": "יויאנו",
    "20437": "צ'נטיאגו",
    "20438": "בוקטון",
    "20439": "וייחו גורינו",
    "20440": "צ'יקיריטון",
    "20441": "קרוז אמיטה",
    "20442": "אינאזוקו",
    "20443": "ראפאגאסס",
    "20444": "בוקוטו",
    "20445": "אגואקטה",
    "20446": "ייחה",
    "20447": "שולוקורטו",
    "20448": "טאקאראהואפאס",
    "20449": "סנטנחו",
    "20450": "קורנטה פרטו",
    "20451": "א ורמליה",
    "20452": "גראסאו",
    "20453": "דו טרסיניה",
    "20454": "קוצ'וצ'ו",
    "20455": "אל סאראו",
    "20456": "אל באסטיון",
    "20457": "מרסליטאס",
    "20458": "אישור שינוי אפשרות",
    "20459": "האם ברצונך לאשר שינוי זה? <b>זמן נותר: XX שניות</b>",
    "20461": "אזהרה",
    "20463": "לחץ כדי לפתוח את המכתב לאיזבל.",
    "20464": "משיכת פסטיבל",
    "20465": "חסינות מפני תקריות",
    "20466": "מייצר מדי פעם [ItemAssetData([AreaManager AreaFestival BuffGuids AT(0) Text]) AdditionalOutputProductsFormatted()] נוספים.",
    "20467": "מייצר מדי פעם [ItemAssetData([AreaManager AreaFestival BuffGuids AT(1) Text]) AdditionalOutputProductsFormatted()] נוספים.",
    "20468": "מייצר מדי פעם [ItemAssetData([AreaManager AreaFestival BuffGuids AT(2) Text]) AdditionalOutputProductsFormatted()] נוספים.",
    "20469": "מייצר מדי פעם [ItemAssetData([AreaManager AreaFestival BuffGuids AT(3) Text]) AdditionalOutputProductsFormatted()] נוספים.",
    "20470": "במקום [ItemAssetData([AreaManager AreaFestival BuffGuids AT(0) Text]) ReplaceInputOldInputsFormatted], המבנה משתמש ב-[ItemAssetData([AreaManager AreaFestival BuffGuids AT(0) Text]) ReplaceInputNewInputsFormatted].",
    "20471": "במקום [ItemAssetData([AreaManager AreaFestival BuffGuids AT(1) Text]) ReplaceInputOldInputsFormatted], המבנה משתמש ב-[ItemAssetData([AreaManager AreaFestival BuffGuids AT(1) Text]) ReplaceInputNewInputsFormatted].",
    "20472": "במקום [ItemAssetData([AreaManager AreaFestival BuffGuids AT(2) Text]) ReplaceInputOldInputsFormatted], המבנה משתמש ב-[ItemAssetData([AreaManager AreaFestival BuffGuids AT(2) Text]) ReplaceInputNewInputsFormatted].",
    "20473": "במקום [ItemAssetData([AreaManager AreaFestival BuffGuids AT(3) Text]) ReplaceInputOldInputsFormatted], המבנה משתמש ב-[ItemAssetData([AreaManager AreaFestival BuffGuids AT(3) Text]) ReplaceInputNewInputsFormatted].",
    "20474": "צריכה של [AssetData([ItemAssetData([AreaManager AreaFestival BuffGuids AT(0) Text]) GoodConsumptionProvidedNeed(index)]) Text]",
    "20475": "צריכה של [AssetData([ItemAssetData([AreaManager AreaFestival BuffGuids AT(1) Text]) GoodConsumptionProvidedNeed(index)]) Text]",
    "20476": "צריכה של [AssetData([ItemAssetData([AreaManager AreaFestival BuffGuids AT(2) Text]) GoodConsumptionProvidedNeed(index)]) Text]",
    "20477": "צריכה של [AssetData([ItemAssetData([AreaManager AreaFestival BuffGuids AT(3) Text]) GoodConsumptionProvidedNeed(index)]) Text]",
    "20482": "הכנסה מ-[AssetData([ItemAssetData([AreaManager AreaFestival BuffGuids AT(0) Text]) InputBenefitModifierProduct(index)]) Text]",
    "20486": "הכנסה מ-[AssetData([ItemAssetData([AreaManager AreaFestival BuffGuids AT(1) Text]) InputBenefitModifierProduct(index)]) Text]",
    "20487": "הכנסה מ-[AssetData([ItemAssetData([AreaManager AreaFestival BuffGuids AT(2) Text]) InputBenefitModifierProduct(index)]) Text]",
    "20488": "הכנסה מ-[AssetData([ItemAssetData([AreaManager AreaFestival BuffGuids AT(3) Text]) InputBenefitModifierProduct(index)]) Text]",
    "20493": "הרעלה בלתי מוסברת",
    "20494": "אספת המועצה המלכותית באולם היי קלארנס הסתיימה באופן טרגי לאחר שהתפרצה הרעלה המונית ממקור שטרם זוהה. חקירות מתנהלות כעת, אף שעל פי הממצאים הפורנזיים המיידיים לא התגלו עקבות שעשויים להוביל לזיהוי הגורם.",
    "20495": "מירבל",
    "20496": "מריגולד",
    "20497": "אפלה",
    "20498": "תסאוס",
    "20499": "אריאדנה",
    "20500": "גורגונה",
    "20501": "שמשון",
    "20502": "דסדמונה",
    "20503": "מינרווה",
    "20504": "דולסיבלה",
    "20505": "פנטון",
    "20506": "רוח רפאים",
    "20507": "נץ כהה",
    "20508": "דיונון ערפדי",
    "20509": "סרטן מרופט"
}

part3 = {
    "20510": "HMS תולעת צינור",
    "20511": "פנגטות'",
    "20512": "ביטיס גבנוני",
    "20513": "גריפון",
    "20514": "ירבוע",
    "20515": "נלי",
    "20516": "ננטקט",
    "20517": "פרעה",
    "20518": "פוקהונטס",
    "20519": "רחל",
    "20520": "יאנגון",
    "20521": "הוולרוס",
    "20522": "כוכב בודד",
    "20523": "דבר פראי",
    "20524": "המלך קול",
    "20525": "מלכת הקוקוס",
    "20526": "הבננה הראשית",
    "20527": "תקווה כסופה",
    "20528": "מטר פתאומי",
    "20529": "רינגהורני",
    "20530": "כבש המושק",
    "20531": "חולדת ביצות",
    "20532": "דורותי",
    "20533": "טוטו",
    "20534": "שמי ברקת",
    "20535": "לוע הארי",
    "20536": "נורית",
    "20537": "אמא אווזה",
    "20538": "קונדור",
    "20539": "קיפר חם",
    "20540": "פדלדאק",
    "20541": "אונדינה",
    "20542": "נארי-א-ג'ובל",
    "20543": "תפוז פקאו",
    "20544": "זללן",
    "20545": "חיבה",
    "20546": "גווינביר",
    "20547": "ציפור בוץ",
    "20548": "תחיית המתים",
    "20549": "קל דעת",
    "20550": "מתינות",
    "20551": "הרמוניה מתוקה",
    "20552": "זיקוק לוהט",
    "20553": "סיר פלפל",
    "20554": "גובלין אפור",
    "20555": "פרנקלין",
    "20556": "צ'נאי",
    "20557": "הויקאנג",
    "20558": "רחם על הפיראטים",
    "20559": "אנז'י",
    "20560": "אקסום",
    "20561": "לליבלה",
    "20562": "קרתגו",
    "20563": "שפריץ",
    "20564": "אשחר",
    "20565": "פיתול אלמוג",
    "20566": "לורד אלג'רנון",
    "20567": "פיצוויליאם דארסי",
    "20568": "אנג'ל קלייר",
    "20569": "צל כוכב",
    "20570": "דודו מעופף",
    "20571": "קוף מכונף",
    "20572": "טתיס",
    "20573": "היפופוטם",
    "20574": "אלקטרה",
    "20575": "חלילון",
    "20576": "גאות אדומה",
    "20577": "HMS סולו",
    "20578": "זקן קשה",
    "20579": "קצף אוקיינוס",
    "20580": "פסגה נישאת",
    "20581": "סאלאסיה",
    "20582": "צב נשכן",
    "20583": "ברית",
    "20584": "הספרוס",
    "20585": "מפצח צדפות",
    "20586": "סרדין ישן",
    "20587": "קצה קרח",
    "20588": "אנדרטת אנו 1602",
    "20589": "זמין כקישוט נוסף.",
    "20591": "רכבת קיסרית",
    "20592": "ספינת פיקוד קיסרית",
    "20593": "החבילה הקיסרית",
    "20595": "יעילות עיתון",
    "20596": "איכות משוב",
    "20597": "<font color='0xff817f87'>תכונה: <i>[ToolOneHelper ItemExpeditionAttributes([RefGuid], true) AT(index) Text]</i></font>",
    "20599": "חגיגות שלוות",
    "20600": "משך פסטיבל",
    "20601": ", או ",
    "20602": "משפיע על האי כולו",
    "20603": "ביקורים מוגברים",
    "20604": "זר עשוי לבקש ממך לשאת נטל כבד. סרב.",
    "20605": "לעולם אל תכרע ברך מאחורי חמור.",
    "20606": "שתף את כל סודותיך עם החבר הכי טוב שלך. (נ.ב. ראשי התיבות שלו הם W.W.)",
    "20607": "כבד תמיד את המבוגרים ממך, במיוחד את אימך.",
    "20608": "שקול מחדש את מכתב האהבה הזה... היא לא תתעניין...",
    "20609": "אתה תזכה בכסף בקרוב מאוד, אך היזהר! אתה גם תפסיד חלק...",
    "20610": "לפעמים עדיף לעשות את ההפך ממה שתכננת.",
    "20611": "מוות! בנקודת זמן כלשהי בעתיד הקרוב, או הרחוק...",
    "20612": "כשאתה לא מבין משהו, תמיד תעמיד פנים שאתה מבין..."
}

part4 = {
    "20613": "\"חפש הדרכה מגבר או מאישה בימים הקרובים...\"",
    "20614": "\"אם נקרית בדרכך ההזדמנות לספוג קרינה שמימית, קבל אותה בזרועות פתוחות!\"",
    "20615": "\"למה שלא תסייע לחבר קרוב? במיוחד לכזה שנראה שרוי במצוקה רוחנית עמוקה...\"",
    "20616": "\"הפסק להתעלם מהתחזיות שלי, אחרת תפספס!\"",
    "20617": "מקסיים חי בשביל השמחה שבגרימת חיוך על פניהם של אנשים מכל הסוגים — בדרן אמיתי.",
    "20618": "שב בנוח, להירגע וליהנות בזמן שארק מעצב את בית חלומותיך.",
    "20619": "הספינה שלך מתקנת את עצמה ללא הרף, אפילו במהלך קרב.",
    "20620": "משפיע על [ItemAssetData([RefGuid]) ItemOrBuffEffectTargetsFormatted] כאשר מופעל",
    "20621": "נזק",
    "20622": "[AssetData([NotificationContext CharacterGUID]) Text] מציע לך משימת משלוח.",
    "20623": "[AssetData([NotificationContext CharacterGUID]) Text] מציע לך משימת איסוף.",
    "20624": "[AssetData([NotificationContext CharacterGUID]) Text] מציע לך משימת ליווי.",
    "20625": "[AssetData([NotificationContext CharacterGUID]) Text] מציע לך משימת השמדה.",
    "20626": "[AssetData([NotificationContext CharacterGUID]) Text] מציע לך משימת צילום.",
    "20627": "[AssetData([NotificationContext CharacterGUID]) Text] מציע לך משימת צילום.",
    "20628": "סר לואיס חקר ושיפר כל שיטת זיקוק המוכרת לאנושות.",
    "21342": "שונר נמרץ",
    "21343": "חוקר נלהב של מציאויות אלטרנטיביות, דרו משתלב בהרמוניה עם כל תרבות שהוא נתקל בה.",
    "21344": "דניס מפיץ את אהבתו לאוכל לכל מי שקורא את ביקורותיו הנלהבות.",
    "21345": "הצתה",
    "21346": "הקליע מצית את המטרה בעת הפגיעה.",
    "21347": "השמדה עצמית",
    "21348": "הספינה שלך תתפוצץ בעוד 10 שניות, ותגרום נזק אזורי לאויבים בהתאם לנקודות החיים של הספינה שלך.",
    "21349": "אף פעם אי אפשר לדעת היכן יסתיים המסע כשג'וזף אוחז בהגה.",
    "21351": "דריי עושה מעל ומעבר כדי למצוא — או ליצור — סיטואציה מגוחכת. למען המדע!",
    "21352": "כעת חברה בפמלייתה של צ'ינג, ליידי לו החליטה לנצל את יכולות הימאות שלו לשימוש בונה יותר.",
    "21353": "משמיד את הספינה שלך",
    "21354": "קולו של פראס מכניס אנשים לטראנס מנחם, ומאפשר להם לנהל חיים מאושרים, ממוקדים ופרודוקטיביים יותר.",
    "21355": "אוסף יורגנסן",
    "21356": "בנטה יורגנסן, הפילנתרופית ללא חת, פתחה שוב את שערי המוזיאון שלה עם תערוכה חדשה. הפעם, החפצים המרהיבים ילוו בצילומים מקצועיים. חובת ביקור לכל חובב תרבות.",
    "21368": "בנה: <br/>מתחם גן חיות ריק <br/>הצב במתחם גן החיות: <br/>בעל חיים כלשהו",
    "21369": "בנה: <br/>תצוגת מוזיאון ריקה <br/>הצב בתצוגת המוזיאון: <br/>חפץ כלשהו",
    "21370": "אש מהירה",
    "21371": "[AssetData([ItemAssetData([ToolOneHelper ItemActiveBuff([RefGuid])]) AddedFertility]) Text] מסופק",
    "21372": "הספינה יורה קליעי שרשרת מיוחדים, שמאיטים את האויב באופן משמעותי.",
    "21373": "מציף את האויב בהתקפות, ומאט את מהירות התנועה והתקיפה שלו.",
    "21375": "יריות שרשרת",
    "21376": "החזק מעמד: <br/>מאזן של [Conditions QuestCondition CurrentAmount]/[Conditions QuestCondition Amount] למשך [Conditions QuestCondition TimeLimit >> time]",
    "21377": "מחפש משחקים לשני שחקנים[Online AnimatedEllipsis]",
    "21378": "מחפש משחקים לשלושה שחקנים[Online AnimatedEllipsis]",
    "21379": "מחפש משחקים לארבעה שחקנים[Online AnimatedEllipsis]",
    "21380": "מחפש משחקים לשלושה או ארבעה שחקנים[Online AnimatedEllipsis]",
    "21381": "מחפש משחקים לשני, שלושה או ארבעה שחקנים[Online AnimatedEllipsis]",
    "21382": "מחפש באזור ובשפה שלך[Online AnimatedEllipsis]",
    "21383": "מחפש ברחבי העולם בשפה שלך[Online AnimatedEllipsis]",
    "21384": "מחפש ברחבי העולם בכל שפה[Online AnimatedEllipsis]",
    "21385": "שידוך המשחקים יימשך במסך הראשי אלא אם כן תתחיל משחק חדש.",
    "21386": "צרכים מסופקים",
    "21387": "צרכים מופחתים",
    "21388": "זמן שחלף",
    "21389": "מיסים מלכותיים",
    "21390": "לתושבים מסופקים [ItemAssetData([RefGuid]) GoodConsumptionAllProvidedNeedsFormatted].",
    "21391": "תושבים צורכים [ItemAssetData([RefGuid]) GoodConsumptionAmountInPercent(0) >> sellShipPrice]% פחות [ItemAssetData([RefGuid]) GoodConsumptionAllProvidedNeedsFormatted].",
    "21392": "מגדיל את הסיכוי שמומחים יבקרו באי שלך.",
    "21393": "מתחבר לשרת שידוך משחקים[Online AnimatedEllipsis]",
    "21394": "נמצא משחק!",
    "21395": "מעשים מגדירים אדם. הוא זנח את הדגל השחור כדי למכור ידע על ספינות פיראטים למרבה במחיר.",
    "21396": "הפיראטיות בחרה בפטרה, לכן היא לא תההסס לחשוף את סודותיה - כמו כיצד הם מפעילים פריגטות מוראות כאלה.",
    "21397": "ספינות המערכה הפיראטיות שלו היו סוד שמור היטב, עד ששיה יאנג נשבע אמונים לקיסר.",
    "21398": "מאוכזבת מחיי הפיראטים, מריה נמלטה להרים. אם ישכנעו אותה לחזור לחוף, היא בהחלט מכירה היטב את ספינות המוניטור שלה...",
    "21399": "נידון לנידוי מהפירפורינים מכיוון שהדיף ריח של גבינה, סטילטון יודע בדיוק כיצד מיוצרות ספינות המוניטור המרושעות שלהם.",
    "21400": "ערקה כדי להציל את עורה שלה, התוכניות של סוספישיה לסיירת קרב פירפורינית הן מפתות ומקפיאות דם כאחד.",
    "21401": "סיניסטרה הודתה בתוכניות של ספינת המלחמה הפירפורינית תחת עינויים, ויש להחזיק אותה תחת שמירה למען בטיחות כולם.",
    "21402": "גסקוט קיבל את ספינתו הראשונה בגיל חמש. לכן זה היה בלתי נמנע שהוא ימשיך לעבוד עבור המלכה.",
    "21403": "חוש הקהילתיות יוצא הדופן של אנה מאפשר לה לבנות כלי שיט יוזמתיים וחגיגיים כאחד!",
    "21404": "הפיראטים חזרו ומעוניינים לבסס את עצמם מחדש במחבוא הישן שלהם. השמד את הספינות שלהם לפני שהם יעשו זאת!",
    "21405": "עקוב אחרי: <br/>[AssetData([Conditions QuestCondition TargetShip]) Text]",
    "21406": "לתושבים מסופקים [ItemAssetData([ToolOneHelper ItemActiveBuff([RefGuid])]) GoodConsumptionAllProvidedNeedsFormatted].",
    "21407": "תושבים צורכים [ItemAssetData([ToolOneHelper ItemActiveBuff([RefGuid])]) GoodConsumptionAmountInPercent(0) >> sellShipPrice]% פחות [ItemAssetData([ToolOneHelper ItemActiveBuff([RefGuid])]) GoodConsumptionAllProvidedNeedsFormatted].",
    "21408": "מניות אי",
    "21409": "צלם תערוכת מוזיאון המכילה חפץ מתקופת הברונזה או מאוסף הסאגות הצפוניות",
    "21410": "השג השפעה רבה יותר על ידי הגדלת האוכלוסייה העולמית שלך ומשיכת תושבים משקיעים.",
    "21411": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] אוהב את הכרזת המלחמה שלך נגד [Participants ParticipantName([NotificationContext Value(TargetParticipant) Int])].",
    "21412": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] לא אוהב את הכרזת המלחמה שלך נגד [Participants ParticipantName([NotificationContext Value(TargetParticipant) Int])].",
    "21413": "צלם את מעונה של הוד מלכותה באולם היי קלארנס",
    "21414": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] אוהב את הפסקת האש שלך עם [Participants ParticipantName([NotificationContext Value(InitiatorParticipant) Int])].",
    "21415": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] לא אוהב את הפסקת האש שלך עם [Participants ParticipantName([NotificationContext Value(InitiatorParticipant) Int])].",
    "21416": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] אוהב את הסכמתך לחוזה שלום עם [Participants ParticipantName([NotificationContext Value(InitiatorParticipant) Int])].",
    "21417": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] לא אוהב את הסכמתך לחוזה שלום עם [Participants ParticipantName([NotificationContext Value(InitiatorParticipant) Int])].",
    "21418": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] אוהב את הסכמתך לזכויות מסחר עם [Participants ParticipantName([NotificationContext Value(InitiatorParticipant) Int])].",
    "21419": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] לא אוהב את הסכמתך לזכויות מסחר עם [Participants ParticipantName([NotificationContext Value(InitiatorParticipant) Int])].",
    "21420": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] אוהב את הברית שלך עם [Participants ParticipantName([NotificationContext Value(InitiatorParticipant) Int])].",
    "21421": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] לא אוהב את הברית שלך עם [Participants ParticipantName([NotificationContext Value(InitiatorParticipant) Int])].",
    "21422": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] אוהב את הסכם אי-התקיפה שלך עם [Participants ParticipantName([NotificationContext Value(InitiatorParticipant) Int])].",
    "21423": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] לא אוהב את הסכם אי-התקיפה שלך עם [Participants ParticipantName([NotificationContext Value(InitiatorParticipant) Int])].",
    "21424": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] אוהב את הכרזת המלחמה שלך נגד [Participants ParticipantName([NotificationContext Value(TargetParticipant) Int])].",
    "21425": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] לא אוהב את הכרזת המלחמה שלך נגד [Participants ParticipantName([NotificationContext Value(TargetParticipant) Int])].",
    "21426": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] אוהב את הסכמתך להפסקת אש עם [Participants ParticipantName([NotificationContext Value(InitiatorParticipant) Int])].",
    "21427": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] לא אוהב את הסכמתך להפסקת אש עם [Participants ParticipantName([NotificationContext Value(InitiatorParticipant) Int])].",
    "21428": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] אוהב את הסכמתך לחוזה שלום עם [Participants ParticipantName([NotificationContext Value(InitiatorParticipant) Int])].",
    "21429": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] לא אוהב את הסכמתך לחוזה שלום עם [Participants ParticipantName([NotificationContext Value(InitiatorParticipant) Int])].",
    "21430": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] אוהב את זה שאתה סוחר עם [Participants ParticipantName([NotificationContext Value(InitiatorParticipant) Int])].",
    "21431": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] לא אוהב את זה שאתה סוחר עם [Participants ParticipantName([NotificationContext Value(InitiatorParticipant) Int])].",
    "21432": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] אוהב את הברית שלך עם [Participants ParticipantName([NotificationContext Value(InitiatorParticipant) Int])].",
    "21433": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] לא אוהב את הברית שלך עם [Participants ParticipantName([NotificationContext Value(InitiatorParticipant) Int])].",
    "21434": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] אוהב את הסכם אי-התקיפה שלך עם [Participants ParticipantName([NotificationContext Value(InitiatorParticipant) Int])].",
    "21435": "[Participants ParticipantName([NotificationContext Value(SpeakingParticipant) Int])] לא אוהב את הסכם אי-התקיפה שלך עם [Participants ParticipantName([NotificationContext Value(InitiatorParticipant) Int])].",
    "21439": "העסק שלך מתחיל עם כמות בסיסית של השפעה.",
    "21440": "הובל אותנו<br/>אל גורלות לא ידועים",
    "21441": "מדריכים שובבים"
}

# Write each out
with open(os.path.join(handoff, "trans_part_1.json"), "w", encoding="utf-8") as f:
    json.dump(part1, f, ensure_ascii=False, indent=4)
print("Saved part 1")

with open(os.path.join(handoff, "trans_part_2.json"), "w", encoding="utf-8") as f:
    json.dump(part2, f, ensure_ascii=False, indent=4)
print("Saved part 2")

with open(os.path.join(handoff, "trans_part_3.json"), "w", encoding="utf-8") as f:
    json.dump(part3, f, ensure_ascii=False, indent=4)
print("Saved part 3")

with open(os.path.join(handoff, "trans_part_4.json"), "w", encoding="utf-8") as f:
    json.dump(part4, f, ensure_ascii=False, indent=4)
print("Saved part 4")
