import json
import os

batch = json.load(open("to_translate_batch.json", encoding="utf-8"))

skips_to_add = [
    "134314",
    "134387",
    "134388",
    "134491"
]

mapping = {
    "The pastry chef - Honoré - is something of a culinary saint!": "שף המגדנות - אונורה - הוא מעין קדוש קולינרי!",
    "Studies have shown the flavour is exalted by the high altitude and thin air!": "מחקרים הראו כי הטעם מתעלה בגבהים ובאוויר הדליל!",
    "Index": "מפתח",
    "INDEX": "מפתח",
    "Bonus Effect": "אפקט בונוס",
    "High dining in the most literal sense!": "סעודה יוקרתית במובן המילולי ביותר!",
    "I hope one day they'll do my truffled trout... simply terrific… usually!": "אני מקווה שביום מן הימים הם יכינו את פורל הכמהין שלי... פשוט נהדר... בדרך כלל!",
    "I've heard the cellar alone is worth millions!": "שמעתי שרק המרתף עצמו שווה מיליונים!",
    "Couldn't keep away from the soufflé, could you?": "לא יכולת להתרחק מהסופלה, נכון?",
    "Just in time for the hors d'œuvre! Pull up a chair!": "בדיוק בזמן למתאבנים! משוך כיסא!",
    "Recipe Book": "ספר מתכונים",
    "Select a recipe by clicking the button": "בחר מתכון על ידי לחיצה על הכפתור",
    "Jump to current recipe": "קפוץ למתכון הנוכחי",
    "Total Recipes Obtained": "סך כל המתכונים שהושגו",
    "Ingredients": "מרכיבים",
    "Change Recipe": "שנה מתכון",
    "Restaurant": "מסעדה",
    "The heart — or stomach — of any decent city, restaurants provide much-needed culinary entertainment to passing tourists. Their expert chefs provide flexible menus using nothing but the best ingredients.": "הלב — או הקיבה — של כל עיר ראויה לשמה, מסעדות מספקות בידור קולינרי נחוץ מאוד לתיירים חולפים. השפים המומחים שלהן מציעים תפריטים גמישים המשתמשים במרכיבים הטובים ביותר ותו לא.",
    "Café": "בית קפה",
    "Cafés are hubs of social and artistic graces, so it's only natural tourists should flock there too, for a whiff of the 'soul' of the city, a dash of darkish brew, and a nibble of pastried bliss.": "בתי קפה הם מרכזים של חן חברתי ואמנותי, לכן זה אך טבעי שתיירים ינהרו גם לשם, כדי לחוש מעט מ'נשמתה' של העיר, ללגום מעט משקה כהה, ולטעום מטעמי מאפה שמימיים.",
    "Bar": "בר",
    "The latest, modern take on the great spirit-imbibing tradition, bars provide tourists with the much-needed option of getting 'right sloshed' while maintaining an illusion of elegance and grace.": "הגרסה המודרנית והעדכנית ביותר למסורת שתיית המשקאות החריפים, ברים מספקים לתיירים את האפשרות הנחוצה מאוד להשתכר כהוגן, תוך שמירה על אשליה של אלגנטיות ועידון.",
    "Restaurant \"La Reine\"": "מסעת \"לה ריין\"",
    "Culinary excellence set atop engineering excellence: the pinnacle of the Empire's legacy. Table reservations run months long, and dishes comprise some of the most exotic ingredients known to humankind.": "מצוינות קולינרית הניצבת על גבי מצוינות הנדסית: פסגת המורשת של האימפריה. הזמנות שולחן נמשכות חודשים מראש, והמנות כוללות כמה מהמרכיבים האקזוטיים ביותר הידועים לאנושות.",
    "Formula Codex": "קודקס נוסחאות",
    "Select a Formula by clicking on the button": "בחר נוסחה על ידי לחיצה על הכפתור",
    "Total Formulas Obtained": "סך כל הנוסחאות שהושגו",
    "Select Formula": "בחר נוסחה",
    "Chemical Plant Formula Book": "ספר הנוסחאות של המפעל הכימי",
    "The Swiss Army knife of production, with their versatile equipment, these factories can make a wide range of products. In a market full of ever-changing demands, monoculture is a thing of the past.": "האולר השוויצרי של הייצור, עם הציוד הרב-תכליתי שלהם, מפעלים אלה יכולים לייצר מגוון רחב של מוצרים. בשוק מלא בדרישות המשתנות ללא הרף, חד-תרבותיות היא נחלת העבר.",
    "Chemical Plant Formulas": "נוסחאות מפעל כימי",
    "A versatile marvel of modern industry, the Chemical Plant produces a wide range of chemical products using scientific processes. The chemists can change the output of the plant at a moment's notice, to better keep pace with market trends.": "פלא רב-תכליתי של התעשייה המודרנית, המפעל הכימי מייצר מגוון רחב של מוצרים כימיים בתהליכים מדעיים. הכימאים יכולים לשנות את תוצר המפעל בהתרעה קצרצרה, כדי לעמוד בקצב של מגמות השוק.",
    "Orchard Catalogue": "קטלוג מטעים",
    "Select a Product by clicking on the button": "בחר מוצר על ידי לחיצה על הכפתור",
    "Total Tree Products Obtained": "סך כל מוצרי העצים שהושגו",
    "Select Product": "בחר מוצר",
    "Determined to preserve and grow some of the genes indigenous to the Old World, authorities have apportioned land to selectively seed and prune the trees most needed and loved, and ultimately, those whose souls must be harvested for the human experiment!": "נחושים לשמר ולפתח חלק מהגנים המקומיים של העולם הישן, הרשויות הקצו קרקעות לזריעה וגיזום סלקטיביים של העצים הנחוצים והאהובים ביותר, ובסופו של דבר, אלו שנשמותיהם חייבות להיקצר למען הניסוי האנושי!",
    "Determined to preserve and grow some of the genes indigenous to the New World, authorities have apportioned land to selectively seed and prune the trees most needed and loved, and ultimately, those whose souls must be harvested for the human experiment!": "נחושים לשמר ולפתח חלק מהגנים המקומיים של העולם החדש, הרשויות הקצו קרקעות לזריעה וגיזום סלקטיביים של העצים הנחוצים והאהובים ביותר, ובסופו של דבר, אלו שנשמותיהם חייבות להיקצר למען הניסוי האנושי!",
    "Dish of the Day": "מנת היום",
    "The city is simply breath-takingly beautiful!": "העיר פשוט יפהפייה עוצרת נשימה!",
    "Nothing quite as lovely as a peaceful city!": "אין דבר יפה כמו עיר שלווה!",
    "So nice not to hear the drums of war, isn't it?": "כל כך נעים לא לשמוע את תופי המלחמה, נכון?",
    "Every bit the peaceful paradise I'd dreamt of!": "גן עדן שליו לחלוטין, בדיוק כפי שחלמתי!",
    "Truly a pacifist's paradise!": "באמת גן עדן לפציפיסטים!",
    "You certainly know how to make a lady feel welcome!": "אתה בהחלט יודע כיצד לגרום לגברת להרגיש רצויה!",
    "The amenities are simply astounding!": "המתקנים פשוט מדהימים!",
    "The mind dizzies with all the comforts and possibilities!": "הדעת סחרחרה מכל הנוחות והאפשרויות!",
    "I've been to many places, but here I feel so... at home.": "הייתי במקומות רבים, אך כאן אני מרגישה... כל כך בבית.",
    "Treading the fine line between sweetness and astringency, this condensed essence of zingy fruit is a warm evening's favourite drink.": "משקה ערב חמים ואהוב זה, המאזן בעדינות בין מתיקות לעפיצות, הוא תמצית מרוכזת של פירות רעננים.",
    "Softly oiled and primed for hair-care, this soap derivative works wonders on all kinds of capillary assets.": "נגזרת סבון זו, המשומנת ברכות ומוכנה לטיפוח השיער, מחוללת פלאים על כל סוגי השיער.",
    "What is a holiday without a cheap and tacky Souvenir to take home with you?": "מהי חופשה ללא מזכרת זולה והמונית לקחת איתך הביתה?",
    "Thick and colourful Jam, blended from a variety of fruit, including cherry, for optimal breakfast conditioning.": "ריבה סמיכה וצבעונית, שנרקחה ממגוון פירות, כולל דובדבנים, לשדרוג ארוחת הבוקר.",
    "The glossy innards of a neatly sliced coconut, cleaned out and ready for further refinement.": "החלק הפנימי המבריק של קוקוס פרוס בצורה מסודרת, מנוקה ומוכן לעיבוד נוסף.",
    "A rich blend of various bittersweet fruit, primed for further processing.": "תערובת עשירה של פירות מתוקים-מרים שונים, המוכנה לעיבוד נוסף.",
    "Dried and snipped in tight ochre rolls, this bark is a surprisingly potent spice and complements any dish perfectly.": "קליפת עץ זו, המיובשת וגזורה בגלילי אוכרה הדוקים, היא תבלין חזק להפליא ומשלימה כל מנה בצורה מושלמת.",
    "… I'm telling you, the butter… the butler... the butler did it!": "... אני אומר לך, החמאה... המשרת... המשרת עשה זאת!",
    "Another one, please - and I want you to shake it this time, rather than stir it!": "עוד אחד, בבקשה - והפעם אני רוצה שתנער אותו, במקום לערבב!",
    "… called me an uncultured trout! For dipping croissant in coffee!": "... קרא לי שמך לא תרבותי! בגלל שטבלתי קרואסון בקפה!",
    "Look, there's a heart in the coffee foam! Do you think she did it just for me?": "תראה, יש לב בקצף של הקפה! אתה חושב שהיא עשתה זאת רק בשבילי?",
    "Oof, I couldn't possibly! Could I? Oh, very well, one more slice!": "אוף, אני לא מסוגל! או שכן? אוי, טוב ויפה, עוד פרוסה אחת!",
    "Oh! And er...a carafe of the expensive sauvignon, there's a fellow!": "הו! ואה... קראף של הסוביניון היקר, הייה גבר!",
    "… create a distraction and I'll nab one of the spoons for a souvenir!": "... צור הסחת דעת ואני אחטוף את אחת הכפיות למזכרת!",
    "…the first wave is truffles, yes, but then…  is it garangal or ginger?": "... הגל הראשון הוא כמהין, כן, אבל אז... האם זה גלנגאל או זנגביל?",
    "There's a line, yes, but I know someone who knows someone...": "יש תור, כן, אבל אני מכיר מישהו שמכיר מישהו...",
    "One of the beams is actually gold and only painted iron!": "אחת הקורות היא בעצם מזהב ורק צבועה כברזל!",
    "If you crane your necks down that street there you'll notice…": "אם תמתחו את צווארכם במורד הרחוב ההוא שם, תבחינו...",
    "Rather knocks you sideways with the peatiness, this one— pass me the spittoon if you would.": "זה די מכה בך מהצד עם טעם הכבול שלו — העבר לי את המרקקה אם לא אכפת לך.",
    "… no, they're of a mind to outlaw all the speakeasies back home. 'Dry state' they call it…": "... לא, הם מתכוונים להוציא מחוץ לחוק את כל מסבאות המחתרת בבית. 'מדינה יבשה' הם קוראים לזה...",
    "I do believe I may be ever-so-slightly tipsy!": "אני אכן מאמינה שאני עשויה להיות מעט טיפונת שיכורה!",
    "Well I'm partial to both tweed and silk, if you understand my meaning.": "ובכן, יש לי חיבה הן לטוויד והן למשי, אם אתה מבין את כוונתי.",
    "… took my placard and wanted to lock me up! Fortunately sister dearest was there to smooth things out.": "... לקחו את השלט שלי ורצו לנעול אותי! למרבה המזל, אחותי היקרה הייתה שם כדי להחליק את העניינים.",
    "One more for the road? —at least we'll be walking home in straight lines!": "עוד כוסית אחת לדרך? — לפחות נלך הביתה בקו ישר!",
    "… not leaving until the closing bell tolls!": "... לא עוזב עד שיישמע פעמון הסגירה!",
    "It goes like this: a Coronian lord walks into a bar…ouch.": "זה הולך ככה: לורד מקורונה נכנס לבר... איי.",
    "Put it on my tab, will you? We'll be coming here a lot.": "רשום זאת על החשבון שלי, טוב? אנחנו נבוא לכאן הרבה.",
    "I'd no idea there were so many strains of bean!": "לא היה לי מושג שיש כל כך הרבה זנים של פולים!",
    "No no no - milk before the tea!": "לא לא לא - חלב לפני התה!",
    "… oh yes, and a whopping great whirlywhip of cream on top, if you have it!": "... הו כן, ותלולית ענקית של קצפת מעל, אם יש לכם!",
    "Dip your hat, quick! There he is again at that table soixante six.": "הטה את כובעך, מהר! הנה הוא שוב בשולחן שישים ושש.",
    "(coughing) Oh Jemima! That was the salt you buffoon!": "(משתעל) אוי ג'מיימה! זה היה המלח, טיפש שכמוך!",
    "It would be like strata— one palmier, then filling, then another palmier!": "זה יהיה כמו שכבות — פאלמייה אחד, אחר כך מילוי, ואז עוד פאלמייה!",
    "We'll take it strong, I think! All ready for a day on the tour buses!": "ניקח אותו חזק, אני חושב! מוכנים ליום באוטובוסי הסיור!",
    "The combination looks… intriguing. Might I have a bite?": "השילוב נראה... מסקרן. האם אוכל לקבל ביס?",
    "That sauce is lip-smackingly… [blissful sigh]": "הרוטב הזה פשוט מעורר תיאבון... [blissful sigh]",
    "Ah, but you cannot leave yet! You've not tried our famous pudding!": "אה, אבל אינך יכול לעזוב עדיין! לא טעמת את הפודינג המפורסם שלנו!",
    "I wonder… might I change my order? That dish over there looks far tastier.": "אני תוהה... האם אוכל לשנות את ההזמנה שלי? המנה ההיא שם נראית הרבה יותר טעימה.",
    "No table? But… we're practically regulars! It's us, you know us!": "אין שולחן פנוי? אבל... אנחנו כמעט לקוחות קבועים! זה אנחנו, אתם מכירים אותנו!",
    "Ugh, the nerve! They could at least make an effort to learn the language.": "אוף, איזו חוצפה! הם יכלו לפחות לעשות מאמץ ללמוד את השפה.",
    "\"You are a tourist, he is a holidaymaker, but I am a traveller!\"": "\"אתה תייר, הוא נופש, אבל אני מטייל!\"",
    "...A nice gesture that bread comes gratis.": "...מחווה יפה שהלחם מגיע בחינם.",
    "We breathe out, trees breathe in, they breathe out, we breathe in...": "אנחנו נושפים, העצים שואפים, הם נושפים, אנחנו שואפים...",
    "I love the feel of the crisp bark wrapped inside my arms.": "אני אוהב את התחושה של קליפת העץ הפריכה כשהיא עטופה בזרועותיי.",
    "Funny...we chop down trees so we can build a place to plant them again.": "מצחיק... אנחנו כורתים עצים כדי שנוכל לבנות מקום לשתול אותם מחדש.",
    "This way, we can give a tiny bit back to the rainforest.": "בדרך זו, אנו יכולים להחזיר מעט ליערות הגשם.",
    "I can't cut it down... I can't— it's too beautiful and it's ages old.": "אני לא יכול לכרות אותו... אני פשוט לא יכול — הוא יפה מדי והוא עתיק יומין.",
    "Strange sort of smell in there, isn't there?": "יש שם ריח מוזר למדי, לא כן?",
    ".. I'm telling you there are corporate interests you don't know about at play...": "... אני אומר לך שיש פה אינטרסים של תאגידים שאינך מודע אליהם...",
    "... Well sometimes, yes, but I prefer organic and natural myself.": "... ובכן, לפעמים כן, אבל אני עצמי מעדיף אורגני וטבעי.",
    "Tube 54 is empty! You didn't mix it into the solvent, did you?!": "מבחנה 54 ריקה! לא ערבבת אותה בתוך הממס, נכון?!",
    "... nip in and see if that's their latest line, there's a girl!": "... כנסי פנימה ותראי אם זו הקולקציה האחרונה שלהם, ילדה טובה!",
    "Oh, I doubt my sister could see herself eating here. She's always so dreadfully humble.": "הו, אני בספק אם אחותי הייתה מסוגלת לראות את עצמה אוכלת כאן. היא תמיד כל כך צנועה באופן נוראי.",
    "… white for fish, red for venison, sauternes for dessert - unless you…": "... יין לבן לדגים, אדום לבשר צבי, סוטרן לקינוח - אלא אם כן אתה...",
    "... don't worry about the bill, I've opened a credit line in Father's name…": "... אל תדאג לגבי החשבון, פתחתי קו אשראי על שם אבי...",
    "… think the chef would object to an offer of employment to replace Teddy out at The Grange?…": "... האם לדעתך השף יתנגד להצעת עבודה כדי להחליף את טדי שם באחוזה?...",
    "… no, it's bad form! Better leave the bottle unfinished and order a new one for each dish.": "... לא, זה נימוס גרוע! עדיף להשאיר את הבקבוק לא גמור ולהזמין אחד חדש לכל מנה.",
    "I don't suppose we could take this food away with us!": "אני מניח שאיננו יכולים לקחת את האוכל הזה איתנו!",
    "… thought I might try it myself once! But I'm more of a critic than a craftswoman, really.": "... חשבתי שאולי אנסה זאת בעצמי פעם אחת! אבל אני יותר מבקרת מאשר בעלת מלאכה, באמת.",
    "… think of it: without this tower, this restaurant, hundreds would be without employment!": "... חשבו על כך: ללא המגדל הזה, המסעדה הזו, מאות אנשים היו נותרים ללא תעסוקה!",
    "How long before they build one back home for sheer spite?": "כמה זמן יעבור עד שהם יבנו אחד כזה בבית רק מתוך צרות עין?",
    "What of the birds? They'll fly straight into it!": "ומה עם הציפורים? הן יעופו ישר לתוכו!",
    "Two hours queue! Be a dear and fetch me a drink, will you?": "תור של שעתיים! תהיה חמוד ותביא לי משקה, טוב?",
    "… and they could fly around it with a great banner, and…": "... והם יוכלו לעוף סביבו עם כרזה ענקית, ו...",
    "I heard they employed special workers, from the New World - unafraid of heights, you see!": "שמעתי שהם העסיקו פועלים מיוחדים מהעולם החדש - שלא מפחדים מגבהים, אתה מבין!",
    "How far do you think they had to dig to make it sturdy?": "כמה עמוק לדעתך הם היו צריכים לחפור כדי להפוך אותו ליציב?",
    "Imagine your hat blowing off up there!": "תאר לעצמך שהכובע שלך יעוף שם למעלה!",
    "How… many… more… steps?": "כמה... עוד... מדרגות... נותרו?",
    "Ladies and Gentlemen, welcome to the Phantom Tour!": "גבירותיי ורבותיי, ברוכים הבאים לסיור הרפאים!",
    "See the city's strangest corners and hear its dark legends!": "ראו את הפינות המוזרות ביותר בעיר ושימעו את אגדותיה האפלות!",
    "First stop, the infamous plaza where…": "התחנה הראשונה, הכיכר הידועה לשמצה שבה...",
    "Built at the turn of the century, it was rumoured…": "נבנה במפנה המאה, נפוצו שמועות כי...",
    "This one is much older, dating back to annotiquity…": "זה ישן בהרבה, ומתוארך לעת העתיקה של אנו...",
    "And if you turn left you'll notice a dark smudge of the smoke is still there.": "ואם תפנו שמאלה תבחינו שכתם עשן כהה עדיין נותר שם.",
    "… where Humphrey Smidge, Lord Hunt, infamously buried…": "... שבו האמפרי סמידג', לורד האנט, קבר באופן ידוע לשמצה...",
    "… a frantic collector of all things Imperium, including a peculiar theatrical mask…": "... אספן מטורף של כל דבר הקשור לאימפריה, כולל מסכת תיאטרון מוזרה...",
    "It was torn down and rebuilt, but the stones still remember the weeping…": "הוא נהרס ונבנה מחדש, אך האבנים עדיין זוכרות את הבכי...",
    "Assigned": "הוקצה",
    "Food & Drink Venue": "מתחם מזון ומשקאות",
    "Public Production": "ייצור ציבורי",
    "Regal Gala Parade": "תהלוכת גאלה מלכותית",
    "Show Required Goods": "הצג סחורות נדרשות",
    "I would like to know if the food I am enjoying at the restaurant is fresh produce.": "הייתי רוצה לדעת אם האוכל שאני נהנה ממנו במסעדה הוא מתוצרת טרייה.",
    "Come to think of it, the cruise ship should still be around. You have to try those pastries! They churn up so many memories.": "אם חושבים על זה, ספינת התענוגות עדיין אמורה להיות בסביבה. אתה חייב לטעום את המאפים האלה! הם מעוררים כל כך הרבה זיכרונות.",
    "The tourist is curious as to the provenance of the restaurant ingredients.": "התייר סקרן לגבי מקורם של מרכיבי המסעדה.",
    "The Tourist asks if you'd take her on a cruise.": "התיירת מבקשת שתיקח אותה לשייט.",
    "A Trifling Matter:<br />The Eighth Wonder": "עניין של מה בכך:<br />הפלא השמיני",
    "My most loyal subject, I have an idea! Something that can stand for, perhaps come to define our present era,— a marvel to draw crowds from all the world! An Iron Tower impossibly tall. Think you can do it?": "נתיני הנאמן ביותר, יש לי רעיון! משהו שיוכל לייצג, ואולי אף להגדיר את העידן הנוכחי שלנו — פלא שימשוך קהל מכל רחבי העולם! מגדל ברזל גבוה באופן בלתי נתפס. חושב שתוכל לעשות זאת?",
    "The tourist asks that you improve your Public Mooring.": "התייר מבקש שתשפר את רציף העגינה הציבורי שלך.",
    "Upgrade:<br />Public Mooring to [AssetData([Conditions QuestCondition Context]) Text]": "שדרוג:<br />רציף עגינה ציבורי ל-[AssetData([Conditions QuestCondition Context]) Text]",
    "The Tourist asks you to build a Tourist Mooring, so that she and her friends can take a (possibly) well-earned vacation on your island. The Public Mooring isn't nearly welcoming enough for those wanting to make a longer stopover — it does not scream luxury holiday!": "התייר מבקש ממך לבנות רציף עגינה לתיירים, כדי שהיא וחבריה יוכלו לצאת לחופשה שמגיעה להם (אולי) בזכות על האי שלך. רציף העגינה הציבורי אינו מזמין מספיק עבור אלה המעוניינים לעשות עצירה ארוכה יותר — הוא פשוט לא משדר חופשת יוקרה!",
    "Select any of your Public Moorings, and upgrade it.": "בחר אחד מרציפי העגינה הציבוריים שלך ושדרג אותו.",
    "You can find <b>Hotels</b>, and all other <b>Tourism-related buildings</b>, in this spot.": "תוכל למצוא <b>מלונות</b> וכל שאר <b>המבנים הקשורים לתיירות</b> במיקום זה.",
    "Such a quaint place you have! It could be such a success with people like me... But you'd need to expand your public mooring - it's a tad drab for Tourists.": "איזה מקום ציורי יש לך! הוא יכול להיות הצלחה כה גדולה בקרב אנשים כמוני... אבל תצטרך להרחיב את רציף העגינה הציבורי שלך - הוא מעט קודר עבור תיירים.",
    "Build Bus Stops to connect the Hotel to the Tourist Mooring": "בנה תחנות אוטובוס כדי לחבר בין המלון לרציף העגינה לתיירים",
    "Oh, so you won't dedicate an Iron Tower to me? Well you aren't the first to snub one... imagine what it's like trying to get a bill through parliament...": "או, אז לא תקדיש לי מגדל ברזל? ובכן, אינך הראשון שמסרב לאחד... תאר לעצמך מה זה לנסות להעביר הצעת חוק בפרלמנט...",
    "Place <b>Bus Stops</b> so that the Hotel and Tourist Mooring are within their <b>area of effect</b>.": "מקם <b>תחנות אוטובוס</b> כך שהמלון ורציף העגינה לתיירים יהיו בתוך <b>אזור ההשפעה</b> שלהן.",
    "Select a Bus Stop to see its <b>area of effect</b>, and its <b>network reach</b>.": "בחר תחנת אוטובוס כדי לראות את <b>אזור ההשפעה</b> שלה ואת <b>טווח הרשת</b> שלה.",
    "1. The <b>circle</b> around the Bus Stop tells you which buildings are within its <b>area of effect</b>.<br />2. The <b>green overlay on the streets</b> helps you gauge where to build connecting Bus Stops.": "1. ה<b>עיגול</b> סביב תחנת האוטובוס מראה לך אילו מבנים נמצאים בתוך <b>אזור ההשפעה</b> שלה.<br />2. ה<b>צבע הירוק על הרחובות</b> מסייע לך להעריך היכן לבנות תחנות אוטובוס מקשרות.",
    "The <b>green overlay on the streets</b> helps you gauge where to build connecting Bus Stops.": "ה<b>צבע הירוק על הרחובות</b> מסייע לך להעריך היכן לבנות תחנות אוטובוס מקשרות.",
    "Any two bus stops are only considered connected when their green street overlays overlap.": "כל שתי תחנות אוטובוס נחשבות למחוברות רק כאשר הצבע הירוק ברחובות שלהן חופף.",
    "Build Bus Stops to connect the Hotel to the Variety Theatre": "בנה תחנות אוטובוס כדי לחבר בין המלון לתיאטרון הווראייטי",
    "Remember that you might need <b>multiple Bus Stops</b> to connect a Variety Theatre to all Hotels. Make sure that the <b>green street overlays</b> of all Bus Stops <b>overlap</b>.": "זכור שייתכן שתזדקק ל<b>תחנות אוטובוס מרובות</b> כדי לחבר תיאטרון וראייטי לכל המלונות. ודא ש<b>הצבע הירוק ברחובות</b> של כל תחנות האוטובוס <b>חופף</b>.",
    "Know one thing: even if a Hotel is connected to a <b>hotspot Need</b> by bus, the need might not be fulfilled 100% if the <b>distance</b> between them is <b>too great</b>.": "דע דבר אחד: אפילו אם המלון מחובר ל<b>צורך של מוקד עניין</b> באוטובוס, הצורך עלול שלא להתמלא ב-100% אם ה<b>מרחק</b> ביניהם <b>גדול מדי</b>.",
    "The Queen asks for your help with her latest monumental project: building the Iron Tower!": "המלכה מבקשת את עזרתך בפרויקט המונומנטלי האחרון שלה: בניית מגדל הברזל!",
    "The Queen grudgingly accepts your refusal.": "המלכה מקבלת את סירובך באי-רצון.",
    "Remember that you might need <b>multiple Bus Stops</b> to connect a Restaurant to all Hotels. Make sure that the <b>green street overlays of the Bus Stops overlap</b>.": "זכור שייתכן שתזדקק ל<b>תחנות אוטובוס מרובות</b> כדי לחבר מסעדה לכל המלונות. ודא ש<b>הצבע הירוק ברחובות של תחנות האוטובוס חופף</b>.",
    "Connect the Restaurant to Bus Stops & fulfill the Restaurant need": "חבר את המסעדה לתחנות אוטובוס ומלא את צורך המסעדה",
    "Choose a Dish of the Day for the Restaurant": "בחר את מנת היום עבור המסעדה",
    "Restaurants are a new building type. They act <b>like public services, but consume input goods</b>! The input goods depend on the chosen recipe.": "מסעדות הן סוג מבנה חדש. הן פועלות <b>כמו שירותים ציבוריים, אך צורכות סחורות תשומה</b>! סחורות התשומה תלויות במתכון הנבחר.",
    "When selecting a Restaurant, the <b>green street overlay</b> shows you where it can <b>fetch recipe input goods</b> from.<br />Make sure you have a <b>warehouse</b> within range of it!": "בעת בחירת מסעדה, <b>הצבע הירוק ברחובות</b> מראה לך מאיפה היא יכולה <b>להביא סחורות תשומה למתכונים</b>.<br />ודא שיש לך <b>מחסן</b> בטווח שלה!",
    "Currently, this Restaurant has no active recipe. <b>Open the recipe book to choose one.</b>": "כרגע, למסעדה זו אין מתכון פעיל. <b>פתח את ספר המתכונים כדי לבחור אחד.</b>",
    "In principle, Restaurants act <b>like public services, but consume input goods</b>. As long as a Restaurant can produce the selected recipe, it will fulfill the Tourists need for a Restaurant, no matter which recipe you select.": "באופן עקרוני, מסעדות פועלות <b>כמו שירותים ציבוריים, אך צורכות סחורות תשומה</b>. כל עוד מסעדה יכולה להכין את המתכון הנבחר, היא תמלא את צורך התיירים במסעדה, לא משנה באיזה מתכון תבחר.",
    "Depending on a recipe's ingredients, a Restaurant will need <b>different input goods</b>.<br />So make sure you have a <b>warehouse</b> with a stock of those goods nearby.": "בהתאם למרכיבי המתכון, מסעדה תזדקק ל<b>סחורות תשומה שונות</b>.<br />לכן ודא שיש לך <b>מחסן</b> עם מלאי של סחורות אלה בקרבת מקום.",
    "Apart from the effect on us Tourists, a recipe also has a <b>beneficial effect on your local residents near the Restaurant</b>. Local residents <b>do not</b> require a bus connection, however.": "מלבד ההשפעה עלינו התיירים, למתכון יש גם <b>השפעה מועילה על התושבים המקומיים שלך בקרבת המסעדה</b>. עם זאת, תושבים מקומיים <b>אינם</b> זקוקים לחיבור אוטובוס.",
    "So, remember what counts for Restaurants:<br />1. The <b>bus network</b> decides which Hotels can reach a Restaurant.<br />2. The <b>green street overlay </b>shows you where input goods can be fetched from.<br />3. The <b>circle</b> shows which local residences will benefit from the chosen recipe.": "לכן, זכור מה קובע לגבי מסעדות:<br />1. <b>רשת האוטובוסים</b> קובעת אילו מלונות יכולים להגיע למסעדה.<br />2. <b>הצבע הירוק ברחובות</b> מראה לך מאיפה ניתן להביא סחורות תשומה.<br />3. <b>העיגול</b> מראה אילו בתי מגורים מקומיים יפיקו תועלת מהמתכון הנבחר.",
    "Production buildings require a <b>workforce</b>, right? Well, Restaurants require us <b>Tourists as customers</b> in the same way.<br />If a Restaurant has too few customers, the <b>need will not be fully supplied</b>, and the benefit to regular residents will be <b>reduced</b>.": "מבני ייצור דורשים <b>כוח עבודה</b>, נכון? ובכן, מסעדות דורשות אותנו <b>התיירים כלקוחות</b> באותו אופן.<br />אם למסעדה יש מעט מדי לקוחות, <b>הצורך לא יסופק במלואו</b>, והתועלת לתושבים הרגילים <b>תפחת</b>.",
    "We Tourists are very picky! If we are <b>unhappy</b>, filling our basic needs will <b>not attract as many Tourists</b> as it could.<br />In other words, only when you make us fully <b>happy</b>, will you start to have <b>full Hotels</b>!": "אנחנו התיירים מאוד בררנים! אם אנחנו <b>אומללים</b>, מילוי הצרכים הבסיסיים שלנו <b>לא ימשוך תיירים רבים</b> כפי שהוא יכול היה.<br />במילים אחרות, רק כאשר תהפוך אותנו ל<b>מאושרים</b> לחלוטין, תתחיל לקבל <b>מלונות מלאים</b>!",
    "Check the <b>happiness needs</b> tab to find out more about why some Tourists may be reluctant to visit!": "בדוק את לשונית <b>צורכי האושר</b> כדי לגלות עוד על הסיבה לכך שחלק מהתיירים עשויים להסס לבקר!",
    "Right now, we are unhappy because this island is <b>not attractive enough</b>.<br /><b>Build attractive buildings</b> like Zoos and Museums, and with more exhibits! Only then will more of us move in.": "כרגע, אנחנו לא מרוצים מכיוון שהאי הזה <b>אינו אטרקטיבי מספיק</b>.<br /><b>בנה מבנים אטרקטיביים</b> כמו גני חיות ומוזיאונים, ועם עוד מוצגים! רק אז עוד מאיתנו יעברו לגור כאן.",
    "Right now, we are unhappy because this <b>island is under attack</b>.<br /><b>Defeat</b> the attacker or <b>end the war</b> altogether! Only then will more of us move in.": "כרגע, אנחנו לא מרוצים מכיוון שה<b>אי נמצא תחת מתקפה</b>.<br /><b>הבס</b> את התוקף או <b>סיים את המלחמה</b> לחלוטין! רק אז עוד מאיתנו יעברו לגור כאן.",
    "Right now, we are unhappy because of a <b>lack of Tourist Hotspots</b>.<br /><b>Build better hotspots</b> and make sure that they are <b>not too far away by bus</b> to improve this! Only then will more of us move in.": "כרגע, אנחנו לא מרוצים בשל <b>מחסור במוקדי עניין לתיירים</b>.<br /><b>בנה מוקדי עניין טובים יותר</b> וודא שהם <b>אינם רחוקים מדי באוטובוס</b> כדי לשפר זאת! רק אז עוד מאיתנו יעברו לגור כאן.",
    "Right now, we are unhappy because of a <b>lack of luxury needs</b>.<br /><b>Increase production</b> on the ones listed here! Only then will more of us move in.": "כרגע, אנחנו לא מרוצים בשל <b>מחסור בצורכי מותרות</b>.<br /><b>הגבר את הייצור</b> של אלה המפורטים כאן! רק אז עוד מאיתנו יעברו לגור כאן.",
    "Right now, we are unhappy because of <b>negative news</b> coverage.<br />Improve the problems in the city reported in the last newspaper! ...or think about <b>\"editing\" the newspaper next time</b>. Only then will more of us move in.": "כרגע, אנחנו לא מרוצים בשל סיקור <b>חדשות שליליות</b>.<br />תקן את הבעיות בעיר שדווחו בעיתון האחרון! ...או שקול <b>\"לערוך\" את העיתון בפעם הבאה</b>. רק אז עוד מאיתנו יעברו לגור כאן.",
    "You've unlocked a <b>second recipe</b>! Open the <b>Recipe Book</b> to look at it.": "פתחת <b>מתכון שני</b>! פתח את <b>ספר המתכונים</b> כדי להביט בו.",
    "You can <b>jump directly</b> to the new recipe by clicking it.": "תוכל <b>לקפוץ ישירות</b> למתכון החדש על ידי לחיצה עליו.",
    "Tourists like me enjoy all recipes equally. But every recipe requires <b>different input goods</b>, and has <b>different effects</b> on your residents.": "תיירים כמוני נהנים מכל המתכונים באותה מידה. אך כל מתכון דורש <b>סחורות תשומה שונות</b>, ויש לו <b>השפעות שונות</b> על התושבים שלך.",
    "You unlocked the <b>Orchard</b>!<br />In an Orchard, you can <b>choose which trees you want to grow</b>. It's just like them fancy-schmancy new Restaurants that are popping up all over.<br />Rumour has it, <b>Jornaleros</b> intend to use Orchards in the <b>New World</b>!": "פתחת את ה<b>מטע</b>!<br />במטע, תוכל <b>לבחור אילו עצים ברצונך לגדל</b>. זה בדיוק כמו המסעדות החדשות והמפוארות האלה שצוצות בכל מקום.<br />השמועה אומרת ש<b>חורנלרוס</b> מתכוונים להשתמש במטעים ב<b>עולם החדש</b>!",
    "Oh, I see. Very well.": "או, אני מבין. טוב ויפה.",
    "Oh well, sorry for thinking people came on holidays to have fun...": "אוי ובכן, סליחה שחשבתי שאנשים באים לחופשות כדי ליהנות...",
    "You unlocked the <b>chemical plant</b>!<br />The Chemical Plant can produce a variety of products to a set formula, like shampoo! You can <b>change the formula you want to produce</b> on the fly, just like you'd change the recipe in a restaurant.": "פתחת את ה<b>מפעל הכימי</b>!<br />המפעל הכימי יכול לייצר מגוון מוצרים לפי נוסחה מוגדרת, כמו שמפו! תוכל <b>לשנות את הנוסחה שברצונך לייצר</b> תוך כדי תנועה, בדיוק כפי שהיית משנה את המתכון במסעדה.",
    "The tourist is mildly disappointed by your refusal.": "התייר מאוכזב קלות מסירובך.",
    "The Tourist is disappointed by your unhelpfulness.": "התייר מאוכזב מחוסר העזרה שלך.",
    "Here you can see <b>all the available Restaurant recipes</b>. There's only one available right now, but you can unlock new ones later.<br />Click on the first recipe to <b>jump directly to it</b>.": "כאן תוכל לראות את <b>כל מתכוני המסעדה הזמינים</b>. יש רק אחד זמין כרגע, אך תוכל לפתוח חדשים מאוחר יותר.<br />לחץ על המתכון הראשון כדי <b>לקפוץ ישירות אליו</b>.",
    "The Tourist asks you to build a Hotel, and to connect it to the harbour by bus for her convenience. In her own words: \"Travel is terribly tiresome you know, and one must have an omnibus at one's beck and call to deliver all the luggage to the Hotel, and take one around all of the nice and interesting places, while avoiding all the squalid and sordid ones the likes of which one always seems to encounter on foot.\"": "התיירת מבקשת ממך לבנות מלון, ולחבר אותו לנמל באוטובוס לנוחיותה. כדבריה: \"הנסיעה מעייפת נורא, כידוע לך, וחובה שתעמוד לרשותך כרכרת נוסעים מוכנה ומזומנה כדי להוביל את כל המטען למלון, ולקחת אותך לכל המקומות היפים והמעניינים, תוך הימנעות מכל המקומות המלוכלכים והעלובים שכמוהם תמיד נדמה שפוגשים ברגל.\"",
    "I had such hopes, such aspirations...": "היו לי תקוות כאלה, שאיפות כאלה...",
    "Place a Bus Stop near your Tourist Mooring, and a Bus Stop near your Hotel, with additional stops in-between if needed. Each Bus Stop only serves buildings within a certain radius.": "מקם תחנת אוטובוס ליד רציף העגינה לתיירים, ותחנת אוטובוס ליד המלון שלך, עם תחנות נוספות באמצע במידת הצורך. כל תחנת אוטובוס משרתת רק מבנים בטווח מסוים.",
    "Your refusal disappoints the tourist.": "סירובך מאכזב את התייר.",
    "Select a Bus Stop to see a green street overlay. This helps you gauge where to build connecting Bus Stops.": "בחר תחנת אוטובוס כדי לראות צבע ירוק ברחובות. זה מסייע לך להעריך היכן לבנות תחנות אוטובוס מקשרות.",
    "The Tourist wishes there was a Variety Theatre she could reach by bus.": "התייר מייחל לכך שיהיה תיאטרון וראייטי שיוכל להגיע אליו באוטובוס.",
    "The Tourist asks you to build a Variety Theatre, and connect it to her Hotel by bus. Taking in a show, you see, is one of the first expectations of the overnight traveller wishing to absorb the cultural highlights and footlights of any given surround.": "התייר מבקש ממך לבנות תיאטרון וראייטי, ולחבר אותו למלון שלה באוטובוס. צפייה בהצגה, כידוע לך, היא אחת הציפיות הראשונות של הנוסע הלן בלילה המבקש לטעום מפלאי התרבות ואורות הבמה של הסביבה שבה הוא שוהה.",
    "Place a Bus Stop near your Hotel, and a Bus Stop near your Variety Theatre, with additional stops in-between if needed. Each Bus Stop only serves buildings within a certain radius.": "מקם תחנת אוטובוס ליד המלון שלך, ותחנת אוטובוס ליד תיאטרון הווראייטי, עם תחנות נוספות באמצע במידת הצורך. כל תחנת אוטובוס משרתת רק מבנים בטווח מסוים.",
    "The Tourist wishes there was a Restaurant she could reach by bus.": "התייר מייחל לכך שתהיה מסעדה שיוכל להגיע אליה באוטובוס.",
    "The Tourist asks you to build a Restaurant, and connect it to her Hotel by bus. A Tourist expects to wine and dine every evening, somewhere different than the place they're supposed to sleep. Hotel food, you must understand, is barely edible after the hour of nine in the morning when the breakfast service ends. After that, it's nothing but deathly-dry hunks of meat, overboiled vegetables, and dense, over-reduced sauces.": "התייר מבקש ממך לבנות מסעדה, ולחבר אותה למלון שלה באוטובוס. תייר מצפה לסעוד ולשתות יין מדי ערב, במקום שונה מהמקום שבו הוא אמור לישון. אוכל של מלון, עליך להבין, כמעט ואינו אכיל לאחר השעה תשע בבוקר, כאשר שירות ארוחת הבוקר מסתיים. לאחר מכן, אין זה אלא נתחי בשר יבשים כחול, ירקות מבושלים מדי, ורטבים סמיכים ומצומצמים יתר על המידה.",
    "Place a Bus Stop near your Hotel, and a Bus Stop near your Restaurant, with additional stops in-between if needed. Each Bus Stop only serves buildings within a certain radius.": "מקם תחנת אוטובוס ליד המלון שלך, ותחנת אוטובוס ליד המסעדה שלך, עם תחנות נוספות באמצע במידת הצורך. כל תחנת אוטובוס משרתת רק מבנים בטווח מסוים.",
    "The Restaurant requires the input goods for its recipes to be available within range. Make sure you have a warehouse nearby.": "המסעדה דורשת שסחורות התשומה עבור המתכונים שלה יהיו זמינות בטווח שלה. ודא שיש לך מחסן בקרבת מקום.",
    "Tutorial — The First Tourists": "הדרכה — התיירים הראשונים",
    "The Tourist asks if she should explain how they work.": "התיירת שואלת אם עליה להסביר כיצד הם עובדים.",
    "Tutorial — Bus Trip to the Variety Theatre!": "הדרכה — נסיעת אוטובוס לתיאטרון הווראייטי!",
    "Tutorial — Bus Trip to the Restaurant!": "הדרכה — נסיעת אוטובוס למסעדה!",
    "TutorialHint Tourists": "רמז הדרכה לתיירים",
    "Now pick a fine location for your <b>very first Hotel</b>!": "כעת בחר מיקום מצוין עבור <b>המלון הראשון שלך בהחלט</b>!",
    "Sir Archibald thanks you for ensuring the Queen's safety.": "סר ארצ'יבלד מודה לך על הבטחת שלומה של המלכה.",
    "A Trifling Matter:<br />The Tower": "עניין של מה בכך:<br />המגדל",
    "At last, the moment of truth approaches! Our stratospheric saviour of burnished iron awaits! To the Inauguration!": "סוף סוף, רגע האמת מתקרב! מושיענו הסטרטוספרי מברזל ממורק ממתין! אל טקס החנוכה!",
    "The Queen informs you she is about to make her way to the inauguration.": "המלכה מודיעה לך שהיא עומדת לעשות את דרכה לטקס החנוכה.",
    "Await the Queen's arrival": "המתן להגעתה של המלכה",
    "Palace": "ארמון",
    "Reduces the consumption of [ItemAssetData([RefGuid]) GoodConsumptionAllProvidedNeedsFormatted] by [ItemAssetData([RefGuid]) GoodConsumptionAmountInPercent(0)]% for all surrounding Residences": "מפחית את צריכת [ItemAssetData([RefGuid]) GoodConsumptionAllProvidedNeedsFormatted] ב-[ItemAssetData([RefGuid]) GoodConsumptionAmountInPercent(0)]% עבור כל בתי המגורים שמסביב",
    "A Delicious Idea:<br />Goulash Deluxe": "רעיון טעים:<br />גולאש דלוקס",
    "Stockpile:<br/>[Conditions QuestCondition Amount(ObjectiveIndex)]t [AssetData([Conditions QuestCondition DeliveryObject(ObjectiveIndex)]) Text]": "אגור במלאי:<br/>[Conditions QuestCondition Amount(ObjectiveIndex)] טונות [AssetData([Conditions QuestCondition DeliveryObject(ObjectiveIndex)]) Text]",
    "A Tourist's concerns are two things: is the venue interesting, and can I get there without walking?": "דאגותיו של תייר הן שני דברים: האם המקום מעניין, והאם אני יכול להגיע לשם בלי ללכת?",
    "Well, enough lounging about! Let's see what the city's bus network has in store!": "ובכן, מספיק להתבטל! בואו נראה מה רשת האוטובוסים של העיר מכינה לנו!",
    "No transportation is hard enough, but no road?!": "חוסר בתחבורה זה קשה מספיק, אבל שום כביש?!",
    "I'm by no means an expert, but aren't roads essentials to, well, any industry?": "אני בשום אופן לא מומחה, אבל האם דרכים אינן חיוניות, ובכן, לכל תעשייה?",
    "Time to put the cutlery back in order!": "הגיע הזמן לעשות סדר בסכו\"ם!",
    "Set the tables, light the candles! We're coming in!": "ערכו את השולחנות, הדליקו את הנרות! אנחנו נכנסים!",
    "The Tourist proudly shares the product of her latest baking craze: the Eclair!": "התיירת משתפת בגאווה בתוצר של שיגעון האפייה האחרון שלה: האקלר!",
    "The Tourist shares fondly the story behind the creation of the Palmier Biscuit.": "התיירת משתפת בחיבה את הסיפור שמאחורי יצירתו של ביסקוויט הפאלמייה.",
    "The Tourist is eager to attempt the Lady Marmalade recipe.": "התיירת להוטה לנסות את מתכון 'ליידי מרמלד'.",
    "The Tourist is impressed at the scale and extravagance of the Trifle Tower.": "התיירת מתרשמת מהקנה המידה והראוותנות של מגדל הטריפל.",
    "Now I have it! The Eclair! After hours of baking practice. The memories of the cruise and that filling... Ah, I simply had to try it myself!": "עכשיו הצלחתי! האקלר! אחרי שעות של אימוני אפייה. הזיכרונות מהשייט והמילוי ההוא... אה, פשוט הייתי חייבת לנסות זאת בעצמי!",
    "Love hearts? Pish. The Palmier's inspiration is elephant ears, see? Supposed to remind one of the old country - story goes a girl came up with it for her ailing Enbesan grampa.": "לבות אוהבים? פחח. ההשראה לפאלמייה היא אוזני פיל, מבין? זה אמור להזכיר למישהו את המולדת הישנה - הסיפור מספר שנערה הגתה זאת עבור סבה האנבסני החולה.",
    "A recipe inspired by a cabaret revue? Well I certainly can't let that go untried and untasted!": "מתכון בהשראת מופע קברט? ובכן, אני בהחלט לא יכולה להשאיר זאת ללא ניסיון וללא טעימה!",
    "I was sceptical any dessert could truly convey the splendour of The Iron Tower, but this Trifle Tower dessert... A frightening extravagance worthy of a Queen!": "הייתי סקפטית שקינוח כלשהו יוכל באמת להעביר את הדרה של מגדל הברזל, אבל קינוח מגדל הטריפל הזה... ראוותנות מבהילה הראויה למלכה!",
    "Now if the two gentlemen at the back would let us resume…": "כעת, אם שני הג'נטלמנים מאחור יאפשרו לנו להמשיך...",
    "… where celebrated composer Erich Zann was last heard fiddling in the night.": "... שבו נשמע המלחין המפורסם אריך זאן מנגן בכינור לאחרונה בלילה.",
    "They say she was fleeing witch-hunts in her native Corona, and so came to this street quite destitute.": "אומרים שהיא ברחה מציד מכשפות במולדתה קורונה, וכך הגיעה לרחוב זה חסרת כל לחלוטין.",
    "When it was torn down they found ruins below the cellar, far older than…": "כשהוא נהרס, מצאו מתחת למרתף חורבות העתיקות בהרבה מ...",
    "That window, over there? It opens onto a room that doesn't exist. Can't be found from inside the building.": "החלון ההוא, שם? הוא נפתח אל חדר שאינו קיים. לא ניתן למצוא אותו מתוך המבנה.",
    "Beyond that wall there stretched Old Maggie's Garden. Now she was rumoured…": "מעבר לחומה ההיא השתרע גנה של מגי הזקנה. כעת נפוצו עליה שמועות...",
    "Scientists debate how the stones were brought from so far away, but legend goes…": "מדענים מתווכחים כיצד הובאו האבנים ממרחק כה רב, אך האגדה מספרת...",
    "And last but certainly not least, the notorious…": "ואחרון חביב, ללא ספק, הידוע לשמצה...",
    "This concludes our tour. If you enjoyed it please do remember your guide. I ain't doing this free you know.": "בכך מסתיים הסיור שלנו. אם נהניתם, אנא זכרו את המדריך שלכם. אני לא עושה זאת בחינם, אתם יודעים.",
    "Oh and here we are, could someone wake the two gentlemen at the back?": "הו והנה הגענו, האם מישהו יוכל להעיר את שני הג'נטלמנים מאחור?",
    "Hotspots": "מוקדי עניין",
    "Tourists are unhappy with the entertainment on the bus tour.": "התיירים אינם מרוצים מהבידור בסיור האוטובוס.",
    "Tourists are content with the entertainment on the bus tour.": "התיירים מרוצים מהבידור בסיור האוטובוס.",
    "Tourists appreciate the entertainment on the bus tour.": "התיירים מעריכים את הבידור בסיור האוטובוס.",
    "Invest in entertainment venues for Tourists, and keep the distances to them short.": "השקע במתחמי בידור לתיירים, ושמור על מרחקים קצרים אליהם.",
    "Attractiveness": "אטרקטיביות",
    "Tourists are unhappy with the attractiveness of the city.": "התיירים אינם מרוצים מהאטרקטיביות של העיר.",
    "Tourists are content with the attractiveness of the city.": "התיירים מרוצים מהאטרקטיביות של העיר.",
    "Tourists appreciate the attractiveness of the city.": "התיירים מעריכים את האטרקטיביות של העיר.",
    "Keep the attractiveness of the city high to match the city's size.": "שמור על אטרקטיביות העיר גבוהה כדי שתתאים לגודלה של העיר.",
    "Happiness Debuff": "הפחתת אושר",
    "Tourists are unhappy with the entertainment factor of the bus tour.": "התיירים אינם מרוצים מגורם הבידור של סיור האוטובוס.",
    "All Hotspots": "כל מוקדי העניין",
    "Invest in the entertainment programme, and keep the distances to them short.": "השקע בתוכנית הבידור, ושמור על מרחקים קצרים אליהם.",
    "All Needs": "כל הצרכים",
    "Needs": "צרכים",
    "Tourists are unhappy with the variety of luxury goods.": "התיירים אינם מרוצים ממגוון סחורות המותרות.",
    "Consumable Needs": "צרכים מתכלים",
    "Fulfil the demand for luxury needs.": "ספק את הדרישה לצורכי מותרות.",
    "War": "מלחמה",
    "Tourists are unhappy with their security on the island.": "התיירים אינם מרוצים מביטחונם באי.",
    "Ensure a lasting peace to attract more Tourists.": "הבטח שלום בר-קיימא כדי למשוך עוד תיירים.",
    "Newspaper": "עיתון",
    "Tourists are unhappy seeing negative articles in the newspaper.": "התיירים אינם מרוצים מלראות כתבות שליליות בעיתון.",
    "Restaurants": "מסעדות",
    "Ensure you get positive articles to attract more Tourists.": "ודא שאתה מקבל כתבות חיוביות כדי למשוך עוד תיירים.",
    "Debuff": "הפחתה",
    "The Tourist is very happy to have a Variety Theatre to visit.": "התייר שמח מאוד שיש תיאטרון וראייטי לבקר בו.",
    "The Tourist cannot wait to try out the newly-opened restaurant.": "התייר אינו יכול לחכות לנסות את המסעדה שנפתחה זה מקרוב.",
    "Need fulfillment limited by Tourist unhappiness.": "מילוי הצרכים מוגבל על ידי חוסר האושר של התיירים.",
    "We've not met before, have we? I am a Tourist - a holidaymaker, if you will - and I've plans to spend my vacation here!": "לא נפגשנו בעבר, נכון? אני תייר - נופש, אם תרצה - ויש לי תוכניות לבלות את החופשה שלי כאן!",
    "The tourist introduces herself.": "התיירת מציגה את עצמה.",
    "Finish Quest: [StaticData RecipeData GetRecipeUnlockQuest([RefGuid]) Text]": "סיים משימה: [StaticData RecipeData GetRecipeUnlockQuest([RefGuid]) Text]",
    "Upgrade Tourist Mooring": "שדרג את רציף העגינה לתיירים",
    "Invite Tourists to join your island and stay in Hotels.": "הזמן תיירים להצטרף לאי שלך ולהתארח במלונות.",
    "Build the police station within six tiles of the Iron Tower.": "בנה את תחנת המשטרה בטווח של עד שישה אריחים ממגדל הברזל.",
    "The gang leader questions whether you're sure about bringing them before Sir Archibald.": "מנהיג הכנופיה שואל אם אתה בטוח לגבי הבאתם בפני סר ארצ'יבלד.",
    "Research queue blocked": "תור המחקר חסום",
    "You failed to complete the Trifle Tower recipe with the tourist.": "נכשלת בהשלמת מתכון מגדל הטריפל עם התיירת.",
    "All Monument Restaurants": "כל מסעדות המונומנטים",
    "Find the following people in your city:": "מצא את האנשים הבאים בעירך:",
    "A benefit of an increasingly globalised world, is the joy of fusion. Take East Bohemian goulash— already a beloved dish among artisans— and regard how humble Señorita Maldonado elevated it with the mere addition of New World corn.": "יתרון של עולם גלובלי יותר ויותר הוא שמחת המיזוג. קחו למשל גולאש מזרח-בוהמי — מנה האהובה כבר על אומנים — וראו כיצד סניוריטה מלדונאדו הצנועה שדרגה אותה באמצעות תוספת פשוטה של תירס מהעולם החדש.",
    "A rather commonplace Friday evening delicacy in the territories, albeit with the potatoes often suffering the slings and arrows of far-too-astringent malt vinegar. To lighten the flavour profile, a citrus substitute would better appeal to continental tastes.": "מעדן די נפוץ של ערבי שישי בטריטוריות, אם כי תפוחי האדמה סובלים לעיתים קרובות מפגעי חומץ מאלט עפיץ מדי. כדי להקל על פרופיל הטעם, תחליף הדרים יתאים יותר לטעמים יבשתיים.",
    "The pastry exterior remains crisp thanks only to a thin pancake, acting as an absorbent buffer to the meat. The end effect is a celebratory pink, and not-at-all-rubbery, centrepiece to commemorate any <i>jaque</i>-booted cross-channel contretemps.": "מעטפת המאפה החיצונית נותרת פריכה אך ורק הודות לפנקייק דק, המשמש כחיץ סופג לבשר. התוצאה הסופית היא מנה מרכזית ורודה וחגיגית, ולא צמיגית כלל, לציון כל תקרית <i>ז'אק</i>-נועלת מגפיים מעבר לתעלה.",
    "It's that first dramatic reveal, as the <i>cloche</i> floats away, and a great plume of subtle smoke fills the nostrils. Then the eyes perceive a silhouette, an alien — a sunset exoskeleton, demanding to be prised open for the white meat within.": "זהו הגילוי הדרמטי הראשון, כאשר ה-<i>cloche</i> מורם, ותמרות עשן עדין ממלאות את הנחיריים. אז העיניים מבחינות בצללית, יצור זר — שלד חיצוני בצבעי שקיעה, התובע שייפתחו אותו עבור הבשר הלבן שבתוכו.",
    "A light lunch for café-goers. To some, eating raw meat is repugnant; to others it is the epitome of delicacy. After all, molecular gastronomers may argue that exposure to any form of heat can do nothing but damage the quintessential flavour of an ingredient.": "ארוחת צהריים קלה לבאי בתי הקפה. עבור חלק, אכילת בשר נא היא מעוררת סלידה; עבור אחרים היא התגלמות המעדן. אחרי הכל, גסטרונומים מולקולריים עשויים לטעון שחשיפה לכל סוג של חום יכולה רק לפגוע בטעם המהותי של המרכיב.",
    "The banana is a mysterious and exotic gift that this dish only desires to celebrate. Festooned with sprinkles of cinnamon, the real and genuine surprise here is the uncompromising hit of sour, goaty savour that comes with the goat milk.": "הבננה היא מתנה מסתורית ואקזוטית שמנה זו רק חפצה להלל. המנה מעוטרת בבזיקות של קינמון, וההפתעה האמיתית והכנה כאן היא המכה הבלתי מתפשרת של טעם חמוץ של עז שמגיעה עם חלב העיזים.",
    "The very definition of a stiff drink. The ice, they say, comes directly from the larch forests of the frozen north, where dark-bellied bears loom on their hind legs behind every towering timber.": "ההגדרה האמיתית של משקה חריף חזק. הקרח, כך אומרים, מגיע ישירות מיערות הלרק של הצפון הקפוא, שם דובים בעלי בטן כהה מזדקפים על רגליהם האחוריות מאחורי כל עץ נישא.",
    "Left bank, right bank, nobody's sure... either way, it's a drink for thinkers, or those that like others to think they're thinkers. Crisp and clean in its profile, this cool drink became a classic from the moment it was first shaken into being.": "גדה שמאלית, גדה ימנית, אף אחד לא בטוח... כך או כך, זהו משקה להוגים, או לאלה שאוהבים שאחרים יחשבו שהם הוגים. עם פרופיל פריך ונקי, המשקה הצונן הזה הפך לקלאסיקה מהרגע הראשון שבו נוער לחיים.",
    "Thick, oleaginous clouds swirl up through this magnetic polar blend. Some report having seen the aurora borealis shortly upon drinking; others merely sensations of comfort and warmth, as well as temporary immunity to the push and pull of the sea.": "עננים סמיכים ושומניים מתערבלים דרך התערובת הקוטבית המגנטית הזו. יש המדווחים כי ראו את הזוהר הצפוני זמן קצר לאחר השתייה; אחרים חשים רק תחושות של נוחות וחמימות, כמו גם חסינות זמנית לכוחות המשיכה והדחיפה של הים.",
    "Though rather a typical image of Enbesa, dawn is indeed a magical and dreamlike time there. You may even find the Elders in a good mood after their morning purge, filled with bright hope for the strictures of a day yet to come.": "למרות שזהו דימוי טיפוסי למדי של אנבסה, השחר הוא אכן זמן קסום ודמוי חלום שם. אתם עשויים אפילו למצוא את זקני השבט במצב רוח טוב לאחר התנקות הבוקר שלהם, מלאי תקווה בהירה לקראת תלאות היום שעוד יבוא.",
    "A conceptual dish whose inventor intended to celebrate hundreds of years of ocean-going exploration. The elements are gathered from the four points of the compass, deconstructed and then reconstructed to represent 'the journey' above all else.": "מנה רעיונית שממציאה התכוון לחגוג באמצעותה מאות שנים של מסעות חקירה ימיים. המרכיבים נאספים מארבע רוחות השמים, מפורקים ואז מורכבים מחדש כדי לייצג את 'המסע' מעל לכל דבר אחר.",
    "In an attempt to reconciliate with Sir Archibald Blake in strident mood, the cream of Enbesan chefs created this provocative marriage of surf and turf to represent the powers at play. Time will tell if these two elements can ever sit in harmony on the tongue.": "בניסיון להתפייס עם סר ארצ'יבלד בלייק במצב רוחו הסוער, מיטב השפים האנבסנים יצרו את השילוב המגרה הזה של פירות ים ובשר כדי לייצג את הכוחות הפועלים. ימים יגידו אם שני היסודות הללו יוכלו אי פעם לשכון בהרמוניה על הלשון.",
    "Fluffy, buttery brioche on both top and bottom can scarcely contain the West Atlantic strips of meat within. Is it fine dining? Well, it's a statement, that's for sure — and that can count for a lot at the high end.": "בריוש רך וחמאתני מלמעלה ומלמטה בקושי מצליח להכיל את רצועות הבשר מהאוקיינוס האטלנטי המערבי שבתוכו. האם זו סעודה יוקרתית? ובכן, זוהי הצהרה, זה בטוח — וזה יכול להשפיע רבות בקצה הגבוה של הקולינריה.",
    "A dish to really give people something to choux on, this narrow strip of morning ecstasy may disappear down the gullet in a flash. Forget all the pretenders — a filling of rich and velvety dark chocolate is the only way to go.": "מנה שבאמת נותנת לאנשים משהו ללעוס, רצועה צרה זו של אקסטזת בוקר עשויה להיעלם במורד הגרון כהרף עין. שכחו מכל המתחזים — מילוי של שוקולד מריר עשיר וקטיפתי הוא הדרך היחידה.",
    "Crack apart a palmier, and a whiff of all-too-buttery spice perfumes the air. It's easy to make a pig's ear of these delicate treats, but they're said to look like so many different things, it's become part of their appeal. A props game over coffee!": "חצו פאלמייה, וניחוח של תבלין חמאתי להפליא יבשם את האוויר. קל מאוד להרוס את המעדנים העדינים הללו, אך נאמר שהם נראים כמו כל כך הרבה דברים שונים, שזה הפך לחלק מהמשיכה שלהם. משחק של אסוציאציות על כוס קפה!",
    "A cabaret cocktail, this drink is a statement burlesque. It takes bottle to order one of these, and it ain't for everyone. But for those who can own it, this boudoir sip, jam-packed with colour and fantabulousness, is the night incarnate.": "קוקטייל קברט, המשקה הזה הוא מופע בורלסק הצהרתי. צריך אומץ כדי להזמין אחד כזה, והוא לא מתאים לכל אחד. אך עבור אלה שיכולים לעמוד מאחוריו, לגימת הבודואר הזו, הגדושה בצבע ובנפלאות, היא התגלמות הלילה.",
    "With a wobble intended to convey the quaking majesty of empire, this charming blob of a pudding represents all that is right and yet so dreadfully wrong about its island home. A showstopper, surely, for even the grandest of banquets.": "עם רטט שנועד להעביר את ההוד המרעיד של האימפריה, גוש הפודינג המקסים הזה מייצג את כל מה שנכון ועם זאת כל כך שגוי באופן נוראי בבית האי שלו. מופע מנצח, ללא ספק, אפילו למשתאות המפוארים ביותר.",
    "We must say the ariship has been entirely to our satisfaction when it comes to appliances and amenities.": "עלינו לומר שספינת האוויר הייתה לשביעות רצוננו המלאה בכל הנוגע למכשירים ולמתקנים.",
    "This book is a manuscript full of handwritten recipes. And it's signed... James Cook! The name of my sweetheart Chef. At least I am not leaving empty-handed!": "ספר זה הוא כתב יד מלא במתכונים בכתב יד. והוא חתום... ג'יימס קוק! שמו של השף האהוב שלי. לפחות אינני עוזבת בידיים ריקות!",
    "The tourist is glad to have retrieved the name of her beloved cook.": "התיירת שמחה שגילתה מחדש את שמו של הטבח האהוב עליה.",
    "These donuts are all about the filling! If you had had some other pastries I might have scoffed them too — like the little creamy and curvy ones aboard the cruise ship...delicious!": "הסופגניות האלה הן כולן עניין של מילוי! אם היו לכם מאפים אחרים, אולי הייתי זוללת גם אותם — כמו הקרמיים והמעוקלים הקטנים האלה שעל סיפון ספינת התענוגות... טעים!",
    "The tourist recalls there being some gorgeous pastries aboard her cruise ship.": "התיירת נזכרת שהיו כמה מאפים מדהימים על סיפון ספינת התענוגות שלה.",
    "Emma, the Tourist": "אמה, התיירת",
    "I fell overboard! It's ice-cold here, help me!": "נפלתי מהסיפון! קפוא כאן, עזרו לי!",
    "The chefs have talent, I must say the Archduke's Schnitzel is delectable. I presume other dishes are soon to follow?": "לשפים יש כישרון, עלי לומר שהשניצל של הארכידוכס מענג. אני מניחה שמנות אחרות יגיעו בקרוב?",
    "The tourist yearns for more variety at your restaurant.": "התייר משתוקק למגוון גדול יותר במסעדה שלך.",
    "The first thing I would do is attempt to transform those grotesque clothes Her Majesty always seems to wear...": "הדבר הראשון שהייתי עושה הוא לנסות לשנות את הבגדים הגרוטסקיים האלה שהוד מלכותה תמיד לובשת, כפי שזה נדמה...",
    "The Queen's Maid, my goodness, I can't wait to see my stupid friends' jealous faces.": "העוזרת של המלכה, אלוהים אדירים, אני לא יכולה לחכות לראות את פרצופיהם המקנאים של חבריי הטיפשים.",
    "It would be a great and humbling honour to be chosen to be Her Majesty's maid...": "זה יהיה כבוד גדול ומכובד להיבחר להיות העוזרת של הוד מלכותה...",
    "I think that you need to hear about it, but I have heard terrible whisperings from crows around the tower. As we well know, heads of state have frequently of late been targets for assassination.": "אני חושש שאתה צריך לשמוע על כך, אך שמעתי לחישות נוראיות מעורבים סביב המגדל. כפי שאנו יודעים היטב, ראשי מדינות היו לאחרונה לעיתים קרובות מטרות להתנקשות.",
    "Murmurs of the Queen and other terrors in the same sentence, I fear some rebels are preparing a coup d'etat or some other dreadful thing for the inauguration.": "לחישות על המלכה ואימים אחרים באותו משפט, אני חושש שחלק מהמורדים מכינים הפיכה או דבר איום אחר לטקס החנוכה.",
    "The Tourist has heard some worrying gossip.": "התייר שמע כמה שמועות מדאיגות.",
    "The Tourist mentions rumours of a plot to assassinate the Queen!": "התייר מזכיר שמועות על מזימה להתנקש בחיי המלכה!",
    "Sir Archibald demands that you hunt down any conspirators near the tower.": "סר ארצ'יבלד דורש שתצוד כל קושר מזימות ליד המגדל.",
    "Sir Archibald insists you bring the angry worker to him.": "סר ארצ'יבלד מתעקש שתביא אליו את הפועל הכועס.",
    "Sir Archibald demands that you find the terrorists, and bring them before him.": "סר ארצ'יבלד דורש שתמצא את הטרוריסטים ותביא אותם בפניו.",
    "Sir Archibald asks if you're ready to bring the would-be-assassins before him.": "סר ארצ'יבלד שואל אם אתה מוכן להביא בפניו את המתנקשים המיועדים.",
    "Oh, look yon to the horizon! The Royal Airship is approaching! Let us strike up the fanfare!": "הו, הביטו אל האופק! ספינת האוויר המלכותית מתקרבת! הבה נפתח בתרועת חצוצרות!",
    "The Tourist is thrilled to see the Queen's sky-rending royal vessel.": "התייר נרגש לראות את כלי השיט המלכותי של המלכה שקורע את השמיים.",
    "Wait for the parade to end.": "המתן לסיום התהלוכה.",
    "The Tourist is impressed by the colourful royal parade.": "התייר מתרשם מהתהלוכה המלכותית הצבעונית.",
    "What an occasion! The splendour, the pomp! The royal guards parading are so proud... and also attractive!": "איזה אירוע! הפאר, ההדר! המשמר המלכותי הצועד בתהלוכה כל כך גאה... וגם מושך!",
    "Sir Archibald hopes you'll get the worker to blow the whistle on his comrades.": "סר ארצ'יבלד מקווה שתגרום לפועל להלשין על חבריו.",
    "We're only waiting for you to come to the ceremony. Do you really want to make your Queen wait?": "אנחנו רק מחכים שתגיע לטקס. האם אתה באמת רוצה לגרום למלכה שלך להמתין?",
    "Now, count to 3! 1...2... and 3! Unveil the surprise, dear Subject!": "כעת, ספור עד 3! 1... 2... ו-3! חשוף את ההפתעה, נתין יקר!",
    "Select the Iron Tower to begin the inauguration": "בחר במגדל הברזל כדי להתחיל בטקס החנוכה",
    "The Queen expects you to commence the inauguration.": "המלכה מצפה ממך להתחיל בטקס החנוכה.",
    "The Queen asks that you reveal her surprise.": "המלכה מבקשת שתחשוף את ההפתעה שלה.",
    "Select the Iron Tower to discover the Queen's surprise": "בחר במגדל הברזל כדי לגלות את ההפתעה של המלכה",
    "Decorated Iron Tower": "מגדל ברזל מקושט",
    "An ornamented version of the Iron Tower. It was the Queen's gift for you for all your hard work on the Day of the Tower's Inauguration.": "גרסה מקושטת של מגדל הברזל. זו הייתה מתנת המלכה עבורך על כל עבודתך הקשה ביום חנוכת המגדל.",
    "Troublemaker": "עושה צרות",
    "Ah, excellent choice! Bente Jorgensen we have heard from the keeper of the scrolls, is a distant distant relation of mine, and there is such enthusiasm and brightness in these travel recollections, we may faint!": "אה, בחירה מצוינת! בנטה יורגנסן, כך שמענו משומר המגילות, היא קרובת משפחה רחוקה מאוד שלי, ויש התלהבות ובהירות כזו בזכרונות הנסיעה האלה, שאנו עלולים להתעלף!",
    "Do you like my airship? Splendid isn't it?": "האם אתה אוהב את ספינת האוויר שלי? נהדרת, לא כן?",
    "It has a special exterior design commissioned just for this occasion.": "יש לה עיצוב חיצוני מיוחד שהוזמן בדיוק עבור אירוע זה.",
    "Add to queue": "הוסף לתור",
    "Queue": "תור",
    "Popular with locals, this homely dish may underwhelm with the casualness of its presentation. Yet, for Tourists, it may well be the first choice on the menu — stating a commitment on their part to sample only the most authentic food of the region.": "מנה ביתית זו, הפופולרית בקרב המקומיים, עלולה לא להרשים בשל פשטות ההגשה שלה. עם זאת, עבור תיירים, היא עשויה בהחלט להיות הבחירה הראשונה בתפריט — המבטאת מחויבות מצדם לטעום רק את האוכל האותנטי ביותר של האזור.",
    "The Fourré is the sum of several scarcely-distinguishable 'solid donut' strains. Rarely does the absence of nothing cause such controversy as with a donut without a hole, yet when that centre is richly jammy, what fool could possibly complain?": "הפורה הוא סך כל כמה זנים של 'סופגניות מוצקות' שכמעט ולא ניתן להבדיל ביניהם. לעיתים נדירות היעדר של שום דבר גורם למחלוקת כה רבה כמו סופגנייה ללא חור, אך כאשר המרכז שלה עשיר בריבה, איזה טיפש יוכל להתלונן?",
    "Rum, Sugar, Bananas— not a foot put wrong across the white sand, between coconut husk, pink crab and driftwood, the sun plummeting towards cool night and the gentle sway of melody. Isabel Sarmento rarely has occasion, but if she did raise a glass...": "רום, סוכר, בננות — שום צעד לא מוטעה על פני החול הלבן, בין קליפות קוקוס, סרטן ורוד ועצי סחף, השמש צוללת אל עבר הלילה הקריר והתנודה העדינה של המנגינה. לאאיזבל סרמנטו יש לעיתים נדירות סיבה מיוחדת, אך לו הייתה מרימה כוסית...",
    "Missing Ingredient": "מרכיב חסר",
    "Drag and drop to change queue order": "גרור ושחרר כדי לשנות את סדר התור",
    "Right-click to remove from queue": "לחיצה ימנית כדי להסיר מהתור",
    "Beyond your current research point limit. Increase the limit by attracting more scholar residents.": "מעבר למגבלת נקודות המחקר הנוכחית שלך. הגדל את המגבלה על ידי משיכת תושבי מלומדים נוספים.",
    "Happy Hour!": "שעה שמחה!",
    "Fresh this Morning!": "טרי הבוקר!",
    "Current Cultivation": "גידול נוכחי",
    "The Active Formula!": "הנוסחה הפעילה!",
    "Special Offer!": "מבצע מיוחד!",
    "In Development": "בפיתוח",
    "Tourists": "תיירים",
    "Introduction": "הקדמה",
    "Tourist Mooring Upgrade": "שדרוג רציף עגינה לתיירים",
    "Select Recipe": "בחר מתכון",
    "Belle Epoque:<br />Marmalade Hall": "הבל אפוק:<br />אולם המרמלדה",
    "Plat du Jour": "מנת היום",
    "<b>Tourists</b> are a special resident type who stay in <b>Hotels</b> in your city, and have various basic and luxury needs. Rather than provide workforce like other residents, Tourists are customers who visit <b>Restaurants, Cafés, Bars</b> and other <b>Tourist Hotspots</b> in your city.<br /><br />Tourist customers are represented by the <b>suitcase icon</b>.": "<b>תיירים</b> הם סוג תושבים מיוחד השוהים ב<b>מלונות</b> בעירך, ויש להם צרכים בסיסיים וצורכי מותרות שונים. במקום לספק כוח עבודה כמו תושבים אחרים, תיירים הם לקוחות המבקרים ב<b>מסעדות, בתי קפה, ברים</b> ו<b>מוקדי עניין לתיירים</b> אחרים בעירך.<br /><br />לקוחות תיירים מיוצגים על ידי <b>סמל המזוודה</b>.",
    "Your existing <b>Public Mooring</b> will have to be upgraded to a <b>Tourist Mooring</b> before <b>Tourists</b> can visit your island. Click the upgrade button inside the <b>Public Mooring</b> building to upgrade.": "יהיה עליך לשדרג את <b>רציף העגינה הציבורי</b> הקיים שלך ל<b>רציף עגינה לתיירים</b> לפני ש<b>תיירים</b> יוכלו לבקר באי שלך. לחץ על כפתור השדרוג בתוך מבנה <b>רציף העגינה הציבורי</b> כדי לשדרג.",
}

# Add skips to skip.json
skip_file = "skip.json"
skips = []
if os.path.exists(skip_file):
    try:
        skips = json.load(open(skip_file, encoding="utf-8"))
    except Exception:
        skips = []

skips_set = set(skips)
for s in skips_to_add:
    skips_set.add(s)
new_skips = sorted(list(skips_set), key=lambda x: int(x))
json.dump(new_skips, open(skip_file, "w", encoding="utf-8"), ensure_ascii=False, indent=0)
print(f"Updated skip.json: {len(new_skips)} total skips")

# Clean up other trans_part_*.json files
for i in range(2, 6):
    p = f"trans_part_{i}.json"
    if os.path.exists(p):
        os.remove(p)
        print(f"Deleted old {p}")
for i in range(1, 6):
    p = f"skip_part_{i}.json"
    if os.path.exists(p):
        os.remove(p)
        print(f"Deleted old {p}")

# Translate the batch
translated = {}
missing = []
for guid, val in batch.items():
    if guid in skips_to_add:
        continue
    if val in mapping:
        translated[guid] = mapping[val]
    else:
        # Check if it was stripped by auto_skip or is in skips
        if guid in skips_set:
            continue
        missing.append((guid, val))

if missing:
    print(f"Error: {len(missing)} missing translations in batch!")
    for g, v in missing[:10]:
        print(f"  {g}: {v!r}")
else:
    # Save to trans_part_1.json
    json.dump(translated, open("trans_part_1.json", "w", encoding="utf-8"), ensure_ascii=False, indent=4)
    print(f"Successfully saved {len(translated)} translations to trans_part_1.json")
