import json
import os

batch = json.load(open("to_translate_batch.json", encoding="utf-8"))

skips_to_add = [
    "135012",
    "135013"
]

mapping = {
    "Hotels— Introduction & Needs": "מלונות — הקדמה וצרכים",
    "Hotels do not count as residences, and therefore <b>cannot be upgraded</b>.<br /><br />To keep Hotels full, you should strive to keep your Tourists happy. You can do this by <b>improving your city's attractiveness</b>, <b>fulfilling luxury needs</b>, and connecting them to <b>Tourist Hotspots</b> by bus. <b>Tourist Hotspots</b> are cultural attractions like the <b>Zoo</b> and the <b>Museum.</b><br /><br />Tourist happiness is also affected if the island is at war, or you receive bad press in the newspaper.": "מלונות אינם נחשבים לבתי מגורים, ולכן <b>אינם ניתנים לשדרוג</b>.<br /><br />כדי לשמור על מלונות מלאים, עליך לשאוף לשמור על התיירים שלך מרוצים. תוכל לעשות זאת על ידי <b>שיפור האטרקטיביות של העיר שלך</b>, <b>מילוי צורכי מותרות</b>, וחיבורם ל<b>מוקדי עניין לתיירים</b> באוטובוס. <b>מוקדי עניין לתיירים</b> הם אטרקציות תרבותיות כמו <b>גן החיות</b> ו<b>המוזיאון.</b><br /><br />אושר התיירים מושפע גם אם האי נמצא במלחמה, או אם אתה מקבל סיקור שלילי בעיתון.",
    "Impact of Happiness": "השפעת האושר",
    "Tourists are pretty picky and have five categories of <b>Happiness</b> for you to keep in check: <b>Attractiveness, Island Peace, Hotspots, Luxury Needs,</b> and <b>the News</b>. <br /><br />If an unhappy red face is visible on a needs meter, this will <b>limit</b> the maximum number of Tourists who can reside in the Hotel.<br /><br />Be sure to keep your Tourists happy, as they will be <b>quicker to leave</b> than other resident types.": "תיירים הם די בררנים ויש להם חמש קטגוריות של <b>אושר</b> שעליך לשמור עליהן: <b>אטרקטיביות, שלום באי, מוקדי עניין, צורכי מותרות</b> ו<b>החדשות</b>. <br /><br />אם פרצוף אדום אומלל נראה במד הצרכים, הדבר <b>יגביל</b> את מספר התיירים המרבי שיכולים להתגורר במלון.<br /><br />ודא שאתה שומר על התיירים שלך מאושרים, שכן הם <b>ימהרו לעזוב</b> מהר יותר מסוגי תושבים אחרים.",
    "Limited Needs": "צרכים מוגבלים",
    "Orchard: Camphor Wax": "מטע: שעוות קמפור",
    "Camphor Wax": "שעוות קמפור",
    "A versatile, natural product of the Camphor tree.": "מוצר טבעי ורב-תכליתי של עץ הקמפור.",
    "A flammable, transparent, solid wax with a strong aroma, steam distilled from the wood of the camphor tree.": "שעווה מוצקה, שקופה ודליקה בעלת ניחוח חזק, המופקת בזיקוק בקיטור מעץ הקמפור.",
    "Assembly Line": "פס ייצור",
    "Assembly Line Patent List": "רשימת פטנטים של פס ייצור",
    "Elevators": "מעליות",
    "Assembly Line: Elevators": "פס ייצור: מעליות",
    "Elevator": "מעלית",
    "Buses": "אוטובוסים",
    "Buses take Tourists from the <b>Tourist Mooring</b> to their <b>Hotels</b> and other places of interest. Plan your network of <b>Bus Stops</b> carefully so that Tourists don't have to travel too far. Tourists expect <b>Food & Drink Venues</b> and <b>Cultural buildings</b> to have nearby bus stops.": "אוטובוסים מסיעים תיירים מ<b>רציף העגינה לתיירים</b> אל ה<b>מלונות</b> שלהם ומקומות עניין אחרים. תכנן את רשת <b>תחנות האוטובוס</b> שלך בקפידה כדי שהתיירים לא יצטרכו לנסוע רחוק מדי. התיירים מצפים מ<b>מתחמי מזון ומשקאות</b> ו<b>מבני תרבות</b> שיהיו להם תחנות אוטובוס בקרבת מקום.",
    "Bus Networks": "רשתות אוטובוסים",
    "Select a <b>Bus Stop</b> to see the highlighted buildings which fall within its service radius.<br /><br />Other Bus Stops in the same network will also be highlighted, with the <b>green street overlay</b> showing if they're connected.<br /><br />The <b>Bus Stop building menu</b> indicates the level of access Tourists have to Hotspots in that Bus network. The further a Hotspot is from a Hotel, the less it will meet the Tourists' need.": "בחר <b>תחנת אוטובוס</b> כדי לראות את המבנים המודגשים הנופלים בתוך רדיוס השירות שלה.<br /><br />תחנות אוטובוס אחרות באותה רשת יודגשו אף הן, כאשר <b>הצבע הירוק ברחובות</b> יראה אם הן מחוברות.<br /><br /><b>תפריט מבנה תחנת האוטובוס</b> מציג את רמת הגישה שיש לתיירים למוקדי עניין באותה רשת אוטובוסים. ככל שמוקד העניין רחוק יותר מהמלון, כך הוא יספק פחות את צורכי התיירים.",
    "Drug Store": "בית מרקחת",
    "Drug Store: Toothpaste": "בית מרקחת: משחת שיניים",
    "Drug Store Patent List": "רשימת פטנטים של בית מרקחת",
    "Toothpaste": "משחת שיניים",
    "Next": "הבא",
    "Previous": "הקודם",
    "Return to Index": "חזור למפתח",
    "Jump to Active Recipe": "קפוץ למתכון הפעיל",
    "Places to Eat & Drink": "מקומות לאכול ולשתות",
    "Venue Types": "סוגי מתחמים",
    "<b>Restaurants, Cafés and Bars</b> are Tourist <b>Venues</b> that function like public services, but consume input goods! The input goods required depends on which <b>Recipe is currently active</b> at the venue. You can switch the current recipe in the building's menu, selecting new ones from the <b>Recipe Book</b>.<br /><br />Tourists will enjoy every dish, no matter which you pick — but each recipe has <b>different effects</b> on regular residents nearby.": "<b>מסעדות, בתי קפה וברים</b> הם <b>מתחמי תיירות</b> הפועלים כמו שירותים ציבוריים, אך צורכים סחורות תשומה! סחורות התשומה הנדרשות תלויות ב<b>מתכון הפעיל כרגע</b> במתחם. תוכל להחליף את המתכון הנוכחי בתפריט המבנה, ולבחור מתכונים חדשים מתוך <b>ספר המתכונים</b>.<br /><br />תיירים ייהנו מכל מנה, לא משנה באיזו תבחר — אך לכל מתכון יש <b>השפעות שונות</b> על תושבים רגילים בקרבת מקום.",
    "Sustained by Tourism": "נתמך על ידי תיירות",
    "Rather than workforce, each venue needs <b>Tourist Customers</b> in order to function. A lack of customers may mean Tourist needs are not being met, and in turn, recipes may have a <b>reduced effect</b> on regular residents living nearby. <br /><br />Select any <b>Food & Drink Venue</b> to check if a <b>Warehouse</b> is within reach to supply recipe ingredients. Some of the required goods will need to be imported from other regions.": "במקום כוח עבודה, כל מתחם זקוק ל<b>לקוחות תיירים</b> כדי לתפקד. מחסור בלקוחות עלול לגרום לכך שצורכי התיירים לא ייענו, ובתורו, למתכונים עשויה להיות <b>השפעה מופחתת</b> על תושבים רגילים המתגוררים בקרבת מקום. <br /><br />בחר <b>מתחם מזון ומשקאות</b> כלשהו כדי לבדוק אם יש <b>מחסן</b> בטווח השגה לאספקת מרכיבי המתכון. חלק מהסחורות הנדרשות יצטרכו להיות מיובאות מאזורים אחרים.",
    "Orchards": "מטעים",
    "Multifactory": "מפעל רב-תכליתי",
    "Different output goods can be produced in your <b>Orchards</b> by choosing from a variety of trees. Orchards work similarly to the lumberjack's hut, and can also be built in the New World.": "ניתן לייצר סחורות תוצרת שונות ב<b>מטעים</b> שלך על ידי בחירה מתוך מגוון עצים. מטעים פועלים בדומה לבקתת חוטבי העצים, וניתן לבנות אותם גם בעולם החדש.",
    "Choosing Output Goods": "בחירת סחורות תוצרת",
    "The <b>Orchard Catalogue</b> functions similarly to Recipe Books in Tourist Food & Drink Venues. Accessed from the <b>Orchard building menu</b>, it allows you to select your preferred output goods.<br /><br />No input goods are necessary — just make sure there's enough space to plant trees!": "<b>קטלוג המטעים</b> פועל באופן דומה לספרי מתכונים במתחמי מזון ומשקאות לתיירים. הגישה אליו מתבצעת מתוך <b>תפריט מבנה המטע</b>, והוא מאפשר לך לבחור את סחורות התוצר המועדפות עליך.<br /><br />אין צורך בסחורות תשומה — רק ודא שיש מספיק מקום לשתילת עצים!",
    "Chemical Plants": "מפעלים כימיים",
    "<b>Chemical Plants</b> allow you to choose from a variety of industrial products as output goods. Chemical Plants work similarly to factories.": "<b>מפעלים כימיים</b> מאפשרים לך לבחור מתוך מגוון מוצרים תעשייתיים כסחורות תוצרת. מפעלים כימיים פועלים בדומה למפעלים רגילים.",
    "The <b>Formula Codex</b> functions similarly to Recipe Books for Tourist Food & Drink Venues. Accessed from the <b>Chemical Plant building menu</b>, it allows you to select your preferred output goods.<br /><br />Make sure to have a <b>warehouse</b> in range to supply the required input goods.<br /><br />The building can be improved with <b>electricity</b>.": "<b>קודקס הנוסחאות</b> פועל באופן דומה לספרי מתכונים עבור מתחמי מזון ומשקאות לתיירים. הגישה אליו מתבצעת מתוך <b>תפריט מבנה המפעל הכימי</b>, והוא מאפשר לך לבחור את סחורות התוצר המועדפות עליך.<br /><br />ודא שיש לך <b>מחסן</b> בטווח כדי לספק את סחורות התשומה הנדרשות.<br /><br />ניתן לשפר את המבנה באמצעות <b>חשמל</b>.",
    "Effects": "השפעות",
    "<b>Recipe books</b> allow you to pick which goods you want Restaurants, Cafés and Bars to produce, from a selection. <b>Multifactories</b> such as <b>Orchards</b> and <b>Chemical Plants</b> have an <b>Orchard Catalogue</b> and <b>Formula Codex</b> that follow the same principle. <br /><br />They can be accessed from each buildings' respective menu.": "<b>ספרי מתכונים</b> מאפשרים לך לבחור אילו סחורות ברצונך שמסעדות, בתי קפה וברים ייצרו, מתוך מבחר זמין. ל<b>מפעלים רב-תכליתיים</b> כגון <b>מטעים</b> ו<b>מפעלים כימיים</b> יש <b>קטלוג מטעים</b> ו<b>קודקס נוסחאות</b> הפועלים לפי אותו עיקרון. <br /><br />ניתן לגשת אליהם מתפריט המבנה המקביל של כל אחד מהם.",
    "Navigating The Recipes": "ניווט במתכונים",
    "Monument - The Iron Tower": "מונומנט - מגדל הברזל",
    "Restaurant \"La Reine\"": "מסעדת \"לה ריין\"",
    "The acme of architecture in the industrial era, <b>The Iron Tower</b> is the final building introduced with Tourist Season. As with all <b>Monuments</b> there are several phases of construction, and only one Iron Tower can be built <b>per island</b>.": "פסגת האדריכלות בעידן התעשייתי, <b>מגדל הברזל</b> הוא המבנה האחרון שהוצג בעונת התיירות. כמו בכל <b>המונומנטים</b>, ישנם מספר שלבי בנייה, וניתן לבנות רק מגדל ברזל אחד <b>לכל אי</b>.",
    "On completion of the monument, a <b>special restaurant</b> will open known as Restaurant 'La Reine'. This functions like any other restaurant, but its extravagant recipes require <b>four input goods</b> rather than the usual three.<br /><br />As a result however, you can expect <b>stronger recipe effects</b>.<br /><br />You can assign surplus Tourist customers to further <b>increase the radius</b> of the recipe effects within the Monument building menu, but <b>all other</b> Restaurants, Cafés and Bars <b>have priority</b> over the Iron Tower.": "עם השלמת המונומנט, תיפתח <b>מסעדה מיוחדת</b> הידועה בשם מסעדת 'לה ריין'. היא פועלת כמו כל מסעדה אחרת, אך מתכוניה הראוותניים דורשים <b>ארבע סחורות תשומה</b> במקום השלוש הרגילות.<br /><br />כתוצאה מכך, עם זאת, תוכל לצפות ל<b>השפעות מתכון חזקות יותר</b>.<br /><br />תוכל להקצות לקוחות תיירים עודפים כדי <b>להגדיל עוד יותר את רדיוס</b> השפעות המתכון בתפריט מבנה המונומנט, אך ל<b>כל שאר</b> המסעדות, בתי הקפה והברים <b>יש עדיפות</b> על פני מגדל הברזל.",
    "Introduction": "הקדמה",
    "Tourist Hotspots": "מוקדי עניין לתיירים",
    "We can have an <b>Orchard</b>, too? Finally!<br />In an Orchard, you can <b>choose which trees you want to grow</b>. Here in the New World, as you call it, there are many more natural products possible.": "אנחנו יכולים לקבל גם <b>מטע</b>? סוף סוף!<br />במטע, תוכל <b>לבחור אילו עצים ברצונך לגדל</b>. כאן בעולם החדש, כפי שאתם מכנים אותו, ישנם מוצרים טבעיים רבים יותר שניתן להפיק.",
    "TutorialHint Tourists": "רמז הדרכה לתיירים",
    "Phew! This is a developing into a memorable holiday!": "פיו! זה מתפתח לחופשה בלתי נשכחת!",
    "The sharply-dressed maid asks if you're going to pick her.": "העוזרת הלבושה בהידור שואלת אם אתה מתכוון לבחור בה.",
    "The boastful maid asks when you're going to hurry up and pick her.": "העוזרת היהירה שואלת מתי תזדרז כבר ותבחר בה.",
    "If people in the Old World have access to more corn, there's a chance they might find a way to liven up Goulash!": "אם לאנשים בעולם הישן תהיה גישה ליותר תירס, יש סיכוי שהם ימצאו דרך לשדרג את הגולאש!",
    "Build an Orchard producing citrus, and you may be able to squeeze out a new recipe.": "בנה מטע המייצר פירות הדר, וייתכן שתוכל לסחוט מתכון חדש.",
    "Perhaps if you built another airship, you could fly in some recipes from the Arctic...": "אולי אם תבנה ספינת אוויר נוספת, תוכל להטיס כמה מתכונים מהאזור הארקטי...",
    "If you sustain tobacco pipes for Scholars on multiple islands for long enough, you may inspire some molecular cuisine!": "אם תספק מקטרות טבק למלומדים במספר איים למשך זמן רב מספיק, ייתכן שתעורר השראה למטבח מולקולרי!",
    "Build one additional post office in the Arctic, and the fresh north wind might deliver!": "בנה סניף דואר נוסף אחד באזור הארקטי, ורוח הצפון הרעננה עשויה להביא את המשלוח!",
    "Add at least a ton of bananas to one of your Enbesan warehouses, and unlock a whole world of surprises...": "הוסף לפחות טון אחד של בננות לאחד המחסנים האנבסניים שלך, ותפתח עולם שלם של הפתעות...",
    "A new elephant enclosure at the Zoo might inspire equally weird and wonderful cookery...": "מכלאת פילים חדשה בגן החיות עשויה לעורר השראה לבישול מוזר ונפלא באותה מידה...",
    "Sustain any café recipe long enough, and the Tourist may offer some alternatives...": "שמור על מתכון בית קפה כלשהו פעיל מספיק זמן, והתייר עשוי להציע כמה חלופות...",
    "If you build a new members' club, your Investors might dredge up some ideas of their own for once...": "אם תבנה מועדון חברים חדש, המשקיעים שלך עשויים להעלות כמה רעיונות משלהם לשם שינוי...",
    "Running a new exhibition at the World's Fair? The Tourist might be inspired...": "מנהל תערוכה חדשה ביריד העולמי? התייר עשוי לקבל השראה...",
    "Perhaps after a successful expedition to the Arctic region, your sailors will have good ideas for a hearty winter brew...": "אולי אחרי משלחת מוצלחת לאזור הארקטי, למלחים שלך יהיו רעיונות טובים למשקה חורפי מחמם...",
    "Keep Elders euphoric for long enough, and they might let you in on the closely-guarded secret of their confidence...": "שמור על זקני השבט באופוריה למשך זמן רב מספיק, והם עשויים לגלות לך את הסוד השמור היטב של ביטחונם העצמי...",
    "If an Iron Tower crowns your city for some time, a cook may create this to mark the occasion!": "אם מגדל ברזל יעטר את עירך למשך זמן מה, טבח עשוי ליצור זאת כדי לציין את האירוע!",
    "Discover the fate of the lost Captain in the Passage, and their harrowing tale may inspire an experimental gastronomic retelling.": "גלה את גורלו של הקפטן האבוד במעבר, וסיפורם המצמרר עשוי לעורר השראה לפרשנות גסטרונומית ניסיונית.",
    "Complete the main story in Land Of Lions, and you may learn the best-kept secrets of his courtly chefs...": "השלם את הסיפור הראשי בארץ האריות, וייתכן שתלמד את הסודות השמורים ביותר של שפי החצר שלו...",
    "Keep Restaurant '[Selection Object Nameable Name]' open and accessible to your Hotels long enough, and uncage this towering dessert...": "שמור על מסעדת '[Selection Object Nameable Name]' פתוחה ונגישה למלונות שלך למשך זמן רב מספיק, ושחרר את הקינוח הנישא הזה מהכלוב...",
    "Once the Iron Tower has crowned your city, build three new Variety Theatres and a produce lemonade to discover sweet success!": "לאחר שמגדל הברזל יעטר את עירך, בנה שלושה תיאטראות וראייטי חדשים וייצר לימונדה כדי לגלות הצלחה מתוקה!",
    "Progress through the Tourist's questlines to unlock": "התקדם בשרשראות המשימות של התייר כדי לפתוח",
    "Dolphins": "דולפינים",
    "Jellyfish": "מדוזות",
    "Preparation Quests for the Inauguration": "משימות הכנה לטקס החנוכה",
    "Progress through the preparations for the inauguration": "התקדם בהכנות לטקס החנוכה",
    "The Queen is thrilled to receive Bente's lively travel scribblings.": "המלכה נרגשת לקבל את רשימות המסע התוססות של בנטה.",
    "50 Shades of Gravy": "50 גוונים של רוטב",
    "Belonged to a Tourist friend. An extremely saucy volume, ideal for holiday reading.": "היה שייך לחבר תייר. כרך פיקנטי ביותר, אידיאלי לקריאה בחופשה.",
    "1801 Nights": "1801 לילות",
    "Recollections of various ancient tales from distant and sand-swept Kingdoms, sewn together with the thread of dusk. Infuriating checksum.": "זיכרונות של סיפורים עתיקים שונים מממלכות רחוקות ושטופות חול, התפורים יחדיו בחוט של בין הערביים. סכום ביקורת מרגיז.",
    "Madness of Grandeur:<br />Hotel Majestic": "שיגעון גדלות:<br />מלון מאז'סטיק",
    "Purple Flowerbed": "ערוגת פרחים סגולה",
    "Map with Awning": "מפה עם סככה",
    "Street Map": "מפת רחובות",
    "Souvenir Shop": "חנות מזכרות",
    "Postcard Vendor": "דוכן גלויות",
    "Iron Tower Kiosk": "קיוסק מגדל הברזל",
    "Lookout Point": "נקודת תצפית",
    "Photography Nook": "פינת צילום",
    "Wooden Pavilion": "ביתן עץ",
    "Ornate Pavilion": "ביתן מקושט",
    "Yellow Parasol": "שמשייה צהובה",
    "Blue Parasol": "שמשייה כחולה",
    "Red Parasol": "שמשייה אדומה",
    "Green Parasol": "שמשייה ירוקה",
    "Signpost": "עמוד שילוט",
    "Musician's Stage": "במת מוזיקאים",
    "Cherry Tree Seat": "ספסל תחת עץ דובדבן",
    "Luggage": "מטען",
    "Luggage Cart": "עגלת מזוודות",
    "Tourist Ornaments": "קישוטי תיירות",
    "Red Flowerbed": "ערוגת פרחים אדומה",
    "Yellow Flowerbed": "ערוגת פרחים צהובה",
    "A beautiful map of the city adorned with an awning, and therefore suitable for navigation in all weathers.": "מפה יפה של העיר המעוטרת בסככה, ולכן מתאימה לניווט בכל מזג אוויר.",
    "A beautiful map to help Tourists sightsee every part of the city without feeling lost, or fear of missing out.": "מפה יפה שתסייע לתיירים לסייר בכל חלקי העיר מבלי להרגיש אבודים, או לחשוש מהחמצה.",
    "A treasure trove of souvenirs varied enough to account for differences in taste and coin.": "אוצר של מזכרות מגוון מספיק כדי להתאים להבדלים בטעם ובכיס.",
    "Grab a postcard to send greetings to loved ones, or to brag about your travels to those who stayed at home.": "קח גלויה כדי לשלוח דרישת שלום ליקירייך, או כדי להשוויץ במסעותיך בפני אלה שנשארו בבית.",
    "If you're in a hurry to get a souvenir, stop on by and pick up a tiny version of a big marvel.": "אם אתה ממהר לקנות מזכרת, עצור כאן וקח גרסה קטנטנה של פלא גדול.",
    "For a handful of coins, enjoy a one-minute closeup view of the city’s sights — or perhaps become the protagonist in your own PI story.": "עבור קומץ מטבעות, תיהנה ממבט מקרוב של דקה אחת על נופי העיר — או אולי תהפוך לגיבור בסיפור בלשי משלך.",
    "Have your photograph taken to document your marvelous time in the city — for fond memories, and to prove you were really there.": "הצטלם כדי לתעד את הזמן הנפלא שלך בעיר — למזכרת נעימה, וכדי להוכיח שבאמת היית שם.",
    "A wooden pavilion perfect for sitting back, relaxing, and observing the hustle and bustle of the city.": "ביתן עץ המושלם לישיבה, להירגעות ולצפייה בהמולה ובסערה של העיר.",
    "This elevated, roofed pavilion offers respite from the sun and rain — if one is lucky enough to discover it vacant.": "ביתן מקורה ומוגבה זה מציע מפלט מהשמש ומהגשם — אם יתמזל מזלך למצוא אותו פנוי.",
    "A beautiful spot to enjoy a picnic — “dearest, shall we dine 'neath the stars tonight?”": "מקום יפהפה ליהנות מפיקניק — \"יקירתי, האם נסעד תחת הכוכבים הלילה?\"",
    "A respite for weary Tourists — \"Let's sit down, my love. My feet simply can't carry me any longer.\"": "מפלט לתיירים עייפים — \"בוא נשב, אהובי. הרגליים שלי פשוט לא יכולות לשאת אותי יותר.\"",
    "A coveted spot — \"Is this your napkin, or can I borrow this chair?\"": "מקום נחשק — \"האם זו המפית שלך, או שאוכל לשאול את הכיסא הזה?\"",
    "A moment to reminisce over the sights — “What could possibly top all that on our itinerary?”": "רגע להתרפק על המראות — \"מה כבר יכול להתעלות על כל זה במסלול הטיול שלנו?\"",
    "It's easy to lose yourself in the sights. This signpost ensures that Tourists can find their way back to their Hotel.": "קל ללכת לאיבוד בין המראות. עמוד שילוט זה מבטיח שהתיירים יוכלו למצוא את דרכם חזרה למלון שלהם.",
    "Various artists cut through the sound of the city with their music, the enjoyment of which is all up to taste.": "אמנים שונים מנעימים את קולות העיר במוזיקה שלהם, שההנאה ממנה היא עניין של טעם בלבד.",
    "Pink petals gently fall from the tree. It’s a sanctum from the rush of the city; a place to stop and take a deep breath.": "עלי כותרת ורודים נושרים בעדינות מהעץ. זהו מקלט משאון העיר; מקום לעצור ולקחת נשימה עמוקה.",
    "Suitcases filled with clothes, shoes and a few extra belongings — hopefully there’s space left over for the souvenirs!": "מזוודות מלאות בבגדים, נעליים וכמה חפצים נוספים — נקווה שנשאר מקום למזכרות!",
    "A porter will shortly collect your luggage — ideally before it rains.": "סבל יאסוף את המטען שלך בהקדם — רצוי לפני שיירד גשם.",
    "Purple flowers for a spot of colour in the city.": "פרחים סגולים לתוספת צבע בעיר.",
    "Red flowers — “Oh! How romantic, Stephen!”": "פרחים אדומים — \"הו! כמה רומנטי, סטיבן!\"",
    "Yellow flowers for a bit of sunlight even in bad weather — oh, and they attract precious bees!": "פרחים צהובים לקצת אור שמש גם במזג אוויר גרוע — אה, והם מושכים דבורים יקרות!",
    "Cherry Tree": "עץ דובדבן",
    "Hotspot Need": "צורך במוקד עניין",
    "Docklands": "דוקלנדס",
    "Queue limit reached": "הושגה מגבלת התור",
    "A Delicious Idea:<br />Goulash Deluxe": "רעיון טעים:<br />גולאש דלוקס",
    "The Tourist gives you her holiday reading by way of thanks.": "התיירת מעניקה לך את ספר קריאת החופשה שלה כאות תודה.",
    "Plate House": "פליט האוס",
    "The Bellbird": "דה בלבירד",
    "The Ballroom": "אולם הריקודים",
    "Secret Garden": "הגן הסודי",
    "Golden Goose": "אווז הזהב",
    "À La Carte": "א לה קארט",
    "Le Veau": "לה וו",
    "The Argent": "הארגנט",
    "White Rabbit": "הארנב הלבן",
    "The Rich Cut": "הנתח העשיר",
    "L’étable": "ל'אטאבל",
    "Seven Swans": "שבעה ברבורים",
    "Becco Fino": "בקו פינו",
    "The Villa": "הווילה",
    "Il Cortile": "איל קורטילה",
    "The\u00a0Monarch": "המונרך",
    "Truffe Noire": "טריף נואר",
    "Don Giovanni": "דון ג'ובאני",
    "La Tosca": "לה טוסקה",
    "Casa Nostra": "קאזה נוסטרה",
    "À la Rue Dorée": "א לה רו דורה",
    "The Atelier": "האטלייה",
    "The Pavillion": "הביתן",
    "Chez Moi": "שה מואה",
    "Bittersweet": "מתוק-מר",
    "Biscuitoire": "ביסקוויטואר",
    "A Royal Cuppa": "ספל תה מלכותי",
    "Flavour & Foam": "טעם וקצף",
    "Rose's Coffee": "הקפה של רוז",
    "Café Royal": "קפה רויאל",
    "Daily Grind": "הטחינה היומית",
    "The Early Bird": "המשכימים לקום",
    "Sweet Trade": "סחר מתוק",
    "Milk and Honey": "חלב ודבש",
    "Sugar Spoon": "כפית סוכר",
    "Steaming Mug": "ספל מהביל",
    "Singing Kettle": "קומקום שר",
    "Coffee Kingdom": "ממלכת הקפה",
    "Hen's Roost": "לול התרנגולות",
    "Sunny Side Up": "ביצת עין",
    "Café Momus": "קפה מומוס",
    "The Backroom": "החדר האחורי",
    "The Dim Lantern": "הפנס העמום",
    "Bar Neon": "בר ניאון",
    "The Aftershow": "לאחר ההופעה",
    "On the Rocks": "על הקרח",
    "Ambrosia": "אמברוזיה",
    "Green Fairy": "הפיה הירוקה",
    "The Cellar": "המרתף",
    "The Salon": "הסלון",
    "Bar Casanova": "בר קזנובה",
    "Gatsby's": "גטסבי",
    "The Lone Wolf": "הזאב הבודד",
    "The Sidecar": "הסיידקאר",
    "Velvet Rooms": "חדרי הקטיפה",
    "Moka Efti": "מוקה אפטי",
    "Mayflowers": "מייפלאוורס",
    "Cafe Vesuvio": "קפה וזוביו",
    "Tiger Bones": "עצמות טיגריס",
    "Upper Lip": "שפה עליונה",
    "The Ship": "הספינה",
    "Madam Claude's": "של מאדאם קלוד",
    "Tea For Two": "תה לשניים",
    "Cosies": "כיסויי קומקום",
    "Le Chat": "לה שא",
    "Covfefe": "קובפפה",
    "Daybreak": "דייברייק",
    "Cafè Casetta": "קפה קזטה",
    "Casa Bianca": "קאזה ביאנקה",
    "The Union": "האיחוד",
    "Golden Hours": "שעות הזהב",
    "Below Deck": "מתחת לסיפון",
    "Chameleon": "זיקית",
    "The Boudoir": "הבודואר",
    "Hush": "הס!",
    "Savannah Forest": "יער סוואנה",
    "Arctic Forest": "יער ארקטי",
    "Extra Tourists": "תיירים עודפים",
    "Assign extra Tourist Customers to the Iron Tower to increase its recipe effect range. All other Restaurants, Cafés and Bars have priority over the Iron Tower.": "הקצה לקוחות תיירים עודפים למגדל הברזל כדי להגדיל את טווח השפעת המתכון שלו. לכל שאר המסעדות, בתי הקפה והברים יש עדיפות על פני מגדל הברזל.",
    "Increased recipe effect range": "טווח השפעת מתכון מוגדל",
    "Tree Painter": "צייר עצים",
    "Creates natural patterns of individual trees or forests.": "יוצר דפוסים טבעיים של עצים בודדים או יערות.",
    "Select Recipe": "בחר מתכון",
    "Select Product": "בחר מוצר",
    "Confirm Recipe": "אשר מתכון",
    "Confirm Product": "אשר מוצר",
    "Tutorial — Zoos Make Happy Tourists": "הדרכה — גני חיות משמחים תיירים",
    "Equip: <br/>[Conditions QuestCondition CurrentAmount]/[Conditions QuestCondition Amount] Zoo animals": "צייד: <br/>[Conditions QuestCondition CurrentAmount]/[Conditions QuestCondition Amount] חיות גן חיות",
    "Build Bus Stops to connect the Hotel to the Zoo": "בנה תחנות אוטובוס כדי לחבר בין המלון לגן החיות",
    "Raise Zoo Hotspot Need Supply to 20% by equipping more animals": "העלה את אספקת הצורך במוקד העניין של גן החיות ל-20% על ידי הצטיידות בחיות נוספות",
    "The Tourist asks you to build a Zoo, complete with enclosures containing rare and impressive animals, and connect it to her Hotel by bus. In her own words, \"When one is able to relax happily in a new and undiscovered place for a long time, one finds oneself craving stimulation of one kind or another. In particular, anything with those jolly animals who are all on holiday from their homelands too.\"": "התיירת מבקשת ממך לבנות גן חיות, כולל מכלאות המכילות חיות נדירות ומרשימות, ולחבר אותו למלון שלה באוטובוס. כדבריה, \"כשמישהו יכול להירגע בשמחה במקום חדש ולא מוכר במשך זמן רב, הוא מוצא את עצמו משתוקק לגירוי מסוג זה או אחר. בפרט, כל דבר שקשור לחיות העליזות הללו, שנמצאות כולן בחופשה גם הן מארצות מולדתן.\"",
    "In order to equip Zoo animals, you must first find some! Purchase animals at Madame Kahina's trading post, find them in quests, or embark on Zoological Expeditions!": "כדי להצטייד בחיות גן חיות, עליך למצוא כמה תחילה! רכוש חיות בתחנת הסחר של מאדאם קהינה, מצא אותן במשימות, או צא למשלחות זואולוגיות!",
    "Place a Bus Stop near your Hotel, and a Bus Stop near your Zoo, with additional stops in-between if needed. Each Bus Stop only serves buildings within a certain radius.": "מקם תחנת אוטובוס ליד המלון שלך, ותחנת אוטובוס ליד גן החיות שלך, עם תחנות נוספות באמצע במידת הצורך. כל תחנת אוטובוס משרתת רק מבנים בתוך רדיוס מסוים.",
    "The more animals you equip, and the higher their rarity, the better the quality of your Zoo. A Tourist's 'Zoo need' supply depends on the quality of the nearest Zoo, and its distance by bus from their Hotel.": "ככל שתצטייד ביותר חיות, וככל שרמת הנדירות שלהן גבוהה יותר, כך איכות גן החיות שלך תהיה טובה יותר. אספקת 'צורך גן החיות' של תייר תלויה באיכות גן החיות הקרוב ביותר, ובמרחק שלו באוטובוס מהמלון שלו.",
    "The Tourist would like to visit a charming zoo.": "התיירת מעוניינת לבקר בגן חיות מקסים.",
    "The Tourist is happy to have visited such a fine zoo.": "התיירת שמחה לבקר בגן חיות כה משובח.",
    "So... I know it's wonderful that we can get to the Zoo. But there <b>aren't that many animals</b> to enjoy there. Can you add a few <b>more, or perhaps more exotic</b> animals? That would make us happier.": "אז... אני יודעת שזה נפלא שאנחנו יכולים להגיע לגן החיות. אבל <b>אין שם כל כך הרבה חיות</b> ליהנות מהן. האם תוכל להוסיף עוד <b>כמה, או אולי חיות אקזוטיות יותר</b>? זה יעשה אותנו מאושרים יותר.",
    "Hotels — Happiness & Hotspots": "מלונות — אושר ומוקדי עניין",
    "Buses — Step-by-Step": "אוטובוסים — שלב אחר שלב",
    "Jump to Recipe": "קפוץ למתכון",
    "Tourists are discouraged by bad news.": "התיירים מרגישים מדוכדכים בשל חדשות רעות.",
    "Tourists feel unconcerned about the news.": "התיירים אינם מוטרדים מהחדשות.",
    "Good news keeps Tourists in good spirits.": "חדשות טובות שומרות על מצב רוח טוב בקרב התיירים.",
    "Tourists feel afraid under attack.": "התיירים חשים פחד תחת מתקפה.",
    "Tourists feel unconcerned about the current state of affairs.": "התיירים אינם מוטרדים מהמצב הנוכחי.",
    "Tourists like feeling safe from the threat of invasions.": "תיירים אוהבים להרגיש בטוחים מפני איום של פלישות.",
    "Tourists dislike the austerity of your city.": "התיירים סולדים מהצנע בעירך.",
    "Tourists are content with the lifestyle in the city.": "התיירים מרוצים מאורח החיים בעיר.",
    "Tourists appreciate the nice city lifestyle.": "התיירים מעריכים את אורח החיים הנעים בעיר.",
    "Perfect Tourist Customer Balance": "איזון לקוחות תיירים מושלם",
    "Assigning this many extra Tourists will keep your Tourist customers balanced.": "הקצאת מספר זה של תיירים עודפים תשמור על איזון לקוחות התיירים שלך.",
    "Attract more Tourists to even out the Customer balance.": "משוך תיירים נוספים כדי לאזן את מאזן הלקוחות.",
    "There are too few Customers in total to add the chosen amount of extra Tourists to the Iron Tower. The number of Customers in Restaurants, Cafés and Bars is zero.": "יש מעט מדי לקוחות בסך הכל כדי להוסיף את כמות התיירים העודפים שנבחרה למגדל הברזל. מספר הלקוחות במסעדות, בתי קפה וברים הוא אפס.",
    "<font size=\"18\"><b>Entry Restricted</b></font><br /><i>(due to the Inauguration)</i><br /><br />Wait for the Royal Visit to end!": "<font size=\"18\"><b>הכניסה מוגבלת</b></font><br /><i>(עקב טקס החנוכה)</i><br /><br />המתן לסיום הביקור המלכותי!",
    "Residence Happiness": "אושר בתי המגורים",
    "Reduce Consumption": "הפחת צריכה",
    "Not enough free Customers": "אין מספיק לקוחות פנויים",
    "Not enough total Customers": "אין מספיק לקוחות בסך הכל",
    "Tourist Needs": "צורכי תיירים",
    "Since Tourists are very picky, their <b>basic needs</b> can be <b>limited by their Happiness</b>.<br /><br />If your Tourists are unhappy, a red sad face above the Needs bar will indicate <b>the maximum fulfilment currently possible.</b><br /><br />To discover what's limiting your Tourists' Happiness, you can <b>hover over the Needs bar</b>.": "מכיוון שתיירים הם מאוד בררנים, ה<b>צרכים הבסיסיים</b> שלהם יכולים להיות <b>מוגבלים על ידי האושר שלהם</b>.<br /><br />אם התיירים שלך אינם מרוצים, פרצוף עצוב אדום מעל בר הצרכים יצביע על <b>הסיפוק המרבי האפשרי כרגע.</b><br /><br />כדי לגלות מה מגביל את אושר התיירים שלך, תוכל <b>להציב את הסמן מעל בר הצרכים</b>.",
    "<b>Hotspots</b> are Tourist attractions in your city, like the <b>Zoo</b>. Hotspots must be <b>connected to Hotels by bus</b>. The further a Hotspot is from a Hotel, the less it will meet your Tourists' needs. Check the Happiness tab of your Hotels to see how well-connected they are to your Hotspots. <br /><br /><b>Unique buildings</b> like the <b>World's Fair</b> are exceptions, and are always well-connected, no matter the distance. The attractiveness of certain buildings, such as <b>Zoos</b> and <b>Museums</b>, also affects need fulfillment. Add modules to increase attractiveness, better fulfilling your Tourists' needs.": "<b>מוקדי עניין</b> הם אטרקציות תיירותיות בעירך, כמו <b>גן החיות</b>. מוקדי עניין חייבים להיות <b>מחוברים למלונות באוטובוס</b>. ככל שמוקד העניין רחוק יותר מהמלון, כך הוא יספק פחות את צורכי התיירים שלך. בדוק את לשונית האושר של המלונות שלך כדי לראות כמה טוב הם מחוברים למוקדי העניין שלך. <br /><br /><b>מבנים ייחודיים</b> כמו <b>היריד העולמי</b> הם חריגים, ותמיד מחוברים היטב, ללא קשר למרחק. האטרקטיביות של מבנים מסוימים, כגון <b>גני חיות</b> ו<b>מוזיאונים</b>, משפיעה גם היא על סיפוק הצרכים. הוסף מודולים כדי להגביר את האטרקטיביות, ולספק טוב יותר את צורכי התיירים שלך.",
    "First, build a <b>Bus Stop</b> near a <b>Tourist Mooring</b>, ensuring the Tourist Mooring is within the Bus Stop's <b>radius</b>.": "ראשית, בנה <b>תחנת אוטובוס</b> ליד <b>רציף עגינה לתיירים</b>, וודא שרציף העגינה לתיירים נמצא בתוך <b>הרדיוס</b> של תחנת האוטובוס.",
    "The <b>Index</b> displays all Recipes at a glance, as well as the active recipe. You can show or hide the required input goods and recipe effects, or jump to the recipe page to find further details.<br /><br />Some recipes may be <b>locked</b>, and require you to complete a <b>Quest</b> or fulfil certain conditions to unlock them.": "ה<b>מפתח</b> מציג את כל המתכונים במבט מהיר, כמו גם את המתכון הפעיל. תוכל להציג או להסתיר את סחורות התשומה הנדרשות והשפעות המתכון, או לקפוץ לדף המתכון כדי למצוא פרטים נוספים.<br /><br />חלק מהמתכונים עשויים להיות <b>נעולים</b>, וידרשו ממך להשלים <b>משימה</b> או לעמוד בתנאים מסוימים כדי לפתוח אותם.",
    "No bus stop nearby": "אין תחנת אוטובוס בקרבת מקום",
    "Neutral City State:": "מצב עיר ניטרלי:",
    "Reduced consumption of:": "צריכה מופחתת של:",
    "Age of Exploration Trigger": "טריגר עידן הגילויים",
    "Lodges Tourists temporarily, providing Customers": "מארח תיירים באופן זמני, ומספק לקוחות",
    "Tourist Lodgings": "מקומות לינה לתיירים",
    "Jump to Active Product": "קפוץ למוצר הפעיל",
    "Jump to Active Formula": "קפוץ לנוסחה הפעילה",
    "Jump to Product": "קפוץ למוצר",
    "Jump to Formula": "קפוץ לנוסחה",
    "Per Hotel": "לכל מלון",
    "The Tourist mentions that your zoo animals from the north have inspired a new dish.": "התייר מציין שחיות גן החיות שלך מהצפון היוו השראה למנה חדשה.",
    "The Tourist mentions that your lobster fisher from Enbesa has created a new, refined dish.": "התייר מציין שדייג הלובסטרים שלך מאנבסה יצר מנה חדשה ומעודנת.",
    "Customer Pool": "מאגר לקוחות",
    "Required by Food & Drink Venues": "נדרש על ידי מתחמי מזון ומשקאות",
    "Tourists don't have working conditions": "לתיירים אין תנאי עבודה",
    "All nearby Bus Stops are connected as one big network. Greater distances make hotspots less accessible to Tourists.": "כל תחנות האוטובוס הסמוכות מחוברות כרשת אחת גדולה. מרחקים גדולים יותר הופכים את מוקדי העניין לפחות נגישים לתיירים.",
    "Accessibility:": "נגישות:",
    "Oh do look mummy, the waters are chock-full of jellyfish!": "הו תראי אמא, המים מלאים לגמרי במדוזות!",
    "Ghastly spectres, they are, Percival. Menaces of the deep, and terribly chewy to eat.": "רוחות רפאים נוראות, הן אכן כאלה, פרסיבל. איומי המעמקים, וצמיגיים נורא לאכילה.",
    "Mother, can those really be dolphins flitting among the waves there?": "אמא, האם אלה באמת יכולים להיות דולפינים המקפצים שם בין הגלים?",
    "Yes... Bottlenose? Not sure... but very cheery-looking creatures indeed!": "כן... דולפינן? לא בטוחה... אבל אכן יצורים בעלי מראה עליז מאוד!",
    "Reach a population of [ToolOneHelper UnlockRequirements([RefGuid]) AT(0) Text] of [ToolOneHelper UnlockRequirements([RefGuid]) AT(0) CurrentAmount >> storagegood]/[ToolOneHelper UnlockRequirements([RefGuid]) AT(0) TargetAmount >> storagegood]": "הגע לאוכלוסייה של [ToolOneHelper UnlockRequirements([RefGuid]) AT(0) Text] של [ToolOneHelper UnlockRequirements([RefGuid]) AT(0) CurrentAmount >> storagegood]/[ToolOneHelper UnlockRequirements([RefGuid]) AT(0) TargetAmount >> storagegood]",
    "All Monument Events": "כל אירועי המונומנטים",
    "Once your Iron Tower has stood for some time, a chef may create this to celebrate!": "לאחר שמגדל הברזל שלך יעמוד במשך זמן מה, שף עשוי ליצור זאת כדי לחגוג!",
    "The Tourist shares the latest creation of a cook in homage to the Queen: the Brioche Royale.": "התיירת משתפת ביצירה האחרונה של טבח כמחווה למלכה: הבריוש המלכותי.",
    "Organise a grand, royal inauguration to unlock.": "ארגן טקס חנוכה מלכותי מפואר כדי לפתוח.",
    "Introduce all the Polar Circle animals to your residents and inspire an icy and exploratory dish!": "הצג את כל חיות החוג הארקטי לתושבים שלך ועורר השראה למנה קפואה של מגלי ארצות!",
    "If you hire a lobsterman in one of your Enbesan Harbour Offices, he may concoct a rather refined dish!": "אם תשכור צייד לובסטרים באחד ממשרדי הנמל האנבסניים שלך, הוא עשוי לרקוח מנה מעודנת למדי!",
    "Recipe unlock conditions have changed": "תנאי פתיחת המתכון השתנו",
    "Click to randomise building name.": "לחץ כדי להגריל שם מבנה.",
    "You need an upgraded Public Mooring to attract Tourists to your city": "עליך לשדרג את רציף העגינה הציבורי שלך כדי למשוך תיירים לעירך",
    "All Moderate Kontors": "כל משרדי המסחר הממוזגים",
    "All Restaurants": "כל המסעדות",
    "Next, build Bus Stops near each of your <b>Hotels</b>, ensuring the Hotels are within a Bus Stop's radius. Multiple Bus Stop radiuses may <b>freely overlap.</b>": "לאחר מכן, בנה תחנות אוטובוס ליד כל אחד מה<b>מלונות</b> שלך, וודא שהמלונות נמצאים בתוך רדיוס של תחנת אוטובוס. רדיוסים של תחנות אוטובוס מרובות עשויים <b>לחפוף באופן חופשי.</b>",
    "Lastly, build Bus Stops close to any <b>other buildings</b> you want Tourists to have access to — Restaurants, Variety Theatres, and Zoos, for example.": "לבסוף, בנה תחנות אוטובוס בקרבת כל <b>מבנה אחר</b> שברצונך להעניק לתיירים גישה אליו — מסעדות, תיאטראות וראייטי וגני חיות, למשל.",
    "Select any <b>bus stop</b> to see its reach via the <b>green street overlay</b>. Bus stops must have overlapping overlays for them to be considered <b>connected</b>. If you see <b>gaps in the overlay</b>, add new bus stops in those spots.": "בחר <b>תחנת אוטובוס</b> כלשהי כדי לראות את הטווח שלה באמצעות <b>הצבע הירוק ברחובות</b>. על תחנות האוטובוס להיות בעלות צבעים חופפים כדי להיחשב <b>מחוברות</b>. אם אתה רואה <b>מרווחים בצבע הירוק</b>, הוסף תחנות אוטובוס חדשות במיקומים אלה.",
    "Making this hotspot more attractive may help it better fulfill people's needs.": "הפיכת מוקד עניין זה לאטרקטיבי יותר עשויה לסייע לו לספק טוב יותר את צורכי האנשים.",
    "A lower quality cultural building nearby is affecting need fulfillment.": "מבנה תרבות באיכות נמוכה יותר בקרבת מקום משפיע על סיפוק הצרכים.",
    "A lower quality food and drink venue nearby is affecting need fulfillment.": "מתחם מזון ומשקאות באיכות נמוכה יותר בקרבת מקום משפיע על סיפוק הצרכים.",
    "Orchard: Resin": "מטע: שרף",
    "Resin": "שרף",
    "Cherry Wood": "עץ דובדבן",
    "Orchard: Cherry Wood": "מטע: עץ דובדבן",
    "Tree juice on tap! This viscous and versatile substance is harvested by cutting a groove into the bark of a tree and collecting the sap. The trick is to leave enough behind for the tree to heal itself and produce more.": "מיץ עצים מהחבית! חומר צמיגי ורב-תכליתי זה נאסף על ידי חריצת חריץ בקליפת העץ ואיסוף השרף. החוכמה היא להשאיר מספיק שרף מאחור כדי שהעץ ירפא את עצמו וייצר עוד.",
    "A coveted raw material for crafting beautiful furniture. With its rich colouration, it's sleek but sturdy to the touch — difficult to work with, but rewarding to a master. A carpenter’s delight!": "חומר גלם נחשק לייצור רהיטים יפים. עם צבעו העשיר, הוא חלק אך יציב למגע — קשה לעבודה, אך מתגמל עבור מומחים. תענוג לנגרים!",
    "Furniture Store": "חנות רהיטים",
    "Department Store": "חנות כלבו",
    "Furniture Store Patent List": "רשימת פטנטים של חנות רהיטים",
    "Department Store Patent List": "רשימת פטנטים של חנות כלבו",
    "Department Store: Toasters": "חנות כלבו: מצנמים",
    "Toaster": "מצנם",
    "Furniture Store: Banker's Lamps": "חנות רהיטים: מנורות בנקאים",
    "Banker's Lamp": "מנורת בנקאים",
    "Estimated Toaster Sales": "מכירות מצנמים מוערכות",
    "Estimated Banker's Lamp Sales": "מכירות מנורות בנקאים מוערכות",
    "Estimated Toothpaste Sales": "מכירות משחות שיניים מוערכות",
    "Furniture Store: Writing Desks": "חנות רהיטים: שולחנות כתיבה",
    "Furniture Store: Vanity Screens": "חנות רהיטים: פרגודים",
    "Furniture Store: Four-Poster Beds": "חנות רהיטים: מיטות אפריון",
    "Furniture Store: Lounge Seating": "חנות רהיטים: פינות ישיבה",
    "Vanity Screen": "פרגוד",
    "Writing Desk": "שולחן כתיבה",
    "Four-Poster Beds": "מיטות אפריון",
    "Lounge Seating": "פינת ישיבה",
    "Lacquer": "לכה",
    "Ethanol": "אתנול",
    "Chemical Plant: Lacquer": "מפעל כימי: לכה",
    "Chemical Plant: Ethanol": "מפעל כימי: אתנול",
    "This sticky gunk is just one in a long line of adhesive materials — whether it be birch-bark tar, pine resin, or beeswax, there has always been a need to stick one thing to another. So, apply, connect, leave to dry and... Oh no! I put the wrong sides together!": "החומר הדביק הזה הוא רק אחד משורה ארוכה של חומרים מדביקים — בין אם מדובר בזפת קליפת ליבנה, שרף אורן או שעוות דבורים, תמיד היה צורך להדביק דבר אחד למשנהו. אז יש למרוח, לחבר, להשאיר לייבוש ו... אוי לא! חיברתי את הצדדים הלא נכונים!",
    "The shiny finish of lacquer often comes in a wide array of colors. Applied to a surface like wood or metal, it provides a glossy or matt protective coating, adding more than a touch of quality and luxury.": "הגימור המבריק של הלכה מגיע לרוב במגוון רחב של צבעים. כשהיא נמרחת על משטח כמו עץ או מתכת, היא מספקת ציפוי מגן מבריק או מט, המוסיף יותר מקורטוב של איכות ויוקרה.",
    "A pure form of alcohol, ethanol is fermented, distilled, and stored by the barrel, and as a universal solvent, has a wide range of applications beyond recreation — as an antiseptic, or fuel for example.": "אתנול, בצורתו הטהורה ביותר של אלכוהול, מותסס, מזוקק ומאוחסן בחביות. כממס אוניברסלי, יש לו מגוון רחב של שימושים מעבר לפנאי — כחומר חיטוי או כדלק, למשל.",
    "An engineering marvel that makes every new feat of skyward construction possible— I say, imagine having to take the stairs fifty storeys! Here's hoping the bellboy isn't rude, the muzak is innocuous and you aren't trapped in there for three days with a dishcloth salesman...": "עבור קומץ מטבעות, תיהנה ממבט מקרוב של דקה אחת על נופי העיר — או אולי תהפוך לגיבור בסיפור בלשי משלך.",
    "This portable, click-clacking quill-and-ink-substitute stamps perfectly-formed pigmented letters onto crisp office paper. So, cheerio spidery scrawl, like hieroglyphs to decipher! — that handwriting business was so dreadfully 1800!": "תחליף נייד ומתקתק זה לדיו ונוצה מטביע אותיות צבעוניות ומושלמות על נייר משרדי פריך. אז להתראות לכתב היד העכבישי, שנראה כמו הירוגליפים לפענוח! — כל עניין כתיבת היד הזה היה כל כך שייך לשנת 1800 הנוראית!",
    "What an electrifying design! An elegant and well-made brass stand with that distinctive emerald glass shade we've all come to associate with serious work — simply tug the pull-chain switch, adjust your glasses, and pore over the case notes.": "איזה עיצוב מחשמל! מעמד פליז אלגנטי ועשוי היטב עם גוון זכוכית האזמרגד המובהק שכולנו למדנו לקשר עם עבודה רצינית — פשוט משוך בשרשרת ההפעלה, כוון את המשקפיים שלך, ועבור בעיון על הערות התיק.",
    "A divisive piece of furniture to compartmentalise sections of a room, ornament, act as a windbreak, or indeed, afford you the necessary privacy to change out of your trousers. Princess Qing swears by it! Simply fold and move as needed!": "רהיט מפלג המיועד לחלוקת קטעים בחדר, לקישוט, לחסימת רוח, או ליתר דיוק, להענקת הפרטיות הדרושה לך כדי להחליף מכנסיים. הנסיכה צ'ינג נשבעת בו! פשוט קפל והזז לפי הצורך!",
    "The centrepiece of any office is surely also the most important. Fashioned of wood that is rich, imposing and solid, it is adorned with fine brass knobs that give the desk a rather severe countenance overall — although they do say life's best friendships thrive on tough love...": "מרכזו של כל משרד הוא ללא ספק גם החלק החשוב ביותר שלו. הוא מעוצב מעץ עשיר, מרשים וחזק, ומעוטר בידיות פליז עדינות המעניקות לשולחן מראה קשוח למדי — אם כי אומרים שהחברויות הטובות ביותר בחיים משגשגות על בסיס קשיחות מסוימת...",
    "Capriciously soft and inviting, this regal restbunk's drapes are in fact a practical consideration: they keep out the cold in drafty towers, offer privacy in shared bedchambers, and shield late risers and vampires from the morning sun!": "וילונותיה של מיטת אפריון מלכותית זו, הרכה והמזמינה להפליא, הם למעשה שיקול מעשי: הם מונעים מהקור לחדור במגדלים מאווררים, מציעים פרטיות בחדרי שינה משותפים, ומגנים על מאחרים לקום ועל ערפדים מפני שמש הבוקר!",
    "These chic leather loungeables will enhance the look of any office or living space — your guests won't even need to sit on them to understand how important you are! But when you do sit, you'll feel every cent of the luxury they promised — whether it's a quick siesta, or that lengthy late-night business chat.": "רהיטי עור שיקיים אלה ישדרגו את המראה של כל משרד או חלל מגורים — האורחים שלך אפילו לא יצטרכו לשבת עליהם כדי להבין כמה אתה חשוב! אך כשתשב, תרגיש כל סנט מהיוקרה שהם הבטיחו — בין אם מדובר בסיאסטה קצרה, או בשיחת עסקים ארוכה בשעת לילה מאוחרת.",
    "Assembly Line: Typewriters": "פס ייצור: מכונות כתיבה",
    "Typewriters": "מכונות כתיבה",
    "Celluloid": "צלולואיד",
    "Estimated Vanity Screen Sales": "מכירות פרגודים מוערכות",
    "Estimated Writing Desk Sales": "מכירות שולחנות כתיבה מוערכות",
    "Estimated Four-Poster Bed Sales": "מכירות מיטות אפריון מוערכות",
    "Shopping Catalogue": "קטלוג קניות",
    "Total number of design patents acquired": "סך כל פטנטי העיצוב שהושגו",
    "Department Store Goods": "סחורות חנות כלבו",
    "Department Stores fulfill a myriad of everyday needs– A toasted slice for breakfast? A chill drink? A snazzy bag? There is pleasure for the customer merely in exploring such a miscellany.": "חנויות כלבו מספקות אינספור צרכים יומיומיים — פרוסה קלויה לארוחת הבוקר? משקה צונן? תיק אופנתי? יש עונג עבור הלקוח מעצם חקירת מגוון כזה.",
    "Bar": "בר",
    "All Monument Restaurants": "כל מסעדות המונומנטים"
}

# Add skips to skip.json
skip_file = "skip.json"
skips = []
if os.path.exists(skip_file):
    try:
        skips = json.load(open(skip_file, encoding="utf-8"))
    except Exception:
        skips = []

skips_set = set(skips)
for s in skips_to_add:
    skips_set.add(s)
new_skips = sorted(list(skips_set), key=lambda x: int(x))
json.dump(new_skips, open(skip_file, "w", encoding="utf-8"), ensure_ascii=False, indent=0)
print(f"Updated skip.json: {len(new_skips)} total skips")

# Clean up other trans_part_*.json files
for i in range(2, 6):
    p = f"trans_part_{i}.json"
    if os.path.exists(p):
        os.remove(p)
        print(f"Deleted old {p}")
for i in range(1, 6):
    p = f"skip_part_{i}.json"
    if os.path.exists(p):
        os.remove(p)
        print(f"Deleted old {p}")

# Translate the batch
translated = {}
missing = []
for guid, val in batch.items():
    if guid in skips_to_add:
        continue
    if val in mapping:
        translated[guid] = mapping[val]
    else:
        # Check if it was stripped by auto_skip or is in skips
        if guid in skips_set:
            continue
        missing.append((guid, val))

if missing:
    print(f"Error: {len(missing)} missing translations in batch!")
    for g, v in missing[:10]:
        print(f"  {g}: {v!r}")
else:
    # Save to trans_part_1.json
    json.dump(translated, open("trans_part_1.json", "w", encoding="utf-8"), ensure_ascii=False, indent=4)
    print(f"Successfully saved {len(translated)} translations to trans_part_1.json")
