import json
import os

batch = json.load(open("to_translate_batch.json", encoding="utf-8"))

skips_to_add = []

mapping = {
    "Estimated Crockery Sales": "",
    "Estimated Crockery Sales": "",
    "Estimated Vacuum Cleaner Sales": "",
    "Estimated Vacuum Cleaner Sales": "",
    "Estimated Refrigerator Sales": "",
    "Estimated Refrigerator Sales": "",
    "Estimated Detergent Sales": "",
    "Estimated Detergent Sales": "",
    "Estimated Lipstick Sales": "",
    "Estimated Lipstick Sales": "",
    "Estimated Face Cream Sales": "",
    "Estimated Face Cream Sales": "",
    "Buff already active!": "",
    "<i>Hint: Coconut oil can be produced in New World orchards</i>": "",
    "Both <b>Engineer</b> and <b>Investor</b> residences can be <b>upgraded to skyscrapers</b>. <br />This is only possible once they have <b>full population</b>, and all basic needs have been fulfilled. <br />Engineer skyscrapers can have up to <b>three levels</b>, while investor skyscrapers can have up to <b>five levels</b>. Each level brings with it <b>new needs</b> for their residents. <br /><br />Skyscrapers have significant <b>maintenance costs. Manage your income and expenditure</b> accordingly!": "",
    "Building Skyscrapers": "",
    "Select any Engineer or Investor residence and click on the button to <b>add a skyscraper level</b>. This will require <b>elevators</b>, which can be produced in the assembly line. <br /><br />You can also <b>remove skyscraper levels</b>, eventually turning the skyscraper back into a regular residence. <br /><br />Once built, you can <b>change the appearance</b> of each level by clicking the brush icon. <br /><br /><b>Tip:</b> Hold <custom-entity tag=\"DefaultKeyDark\"><custom-properties KeyText=\"Shift\"/></custom-entity> while having a skyscraper selected to see all skyscrapers at the same level.": "",
    "Panorama Effect — Benefits": "",
    "Skyscraper residents like to have an <b>unobstructed, panoramic view</b> when looking out of their windows. With this in mind, you can create <b>Panorama Effects </b>on skyscrapers. <br /><br />The Panorama Effect of a skyscraper <b>increases the population</b> that can live in it, and <b>reduces its maintenance cost</b>.": "",
    "Panorama Effect Strength": "",
    "There are, in total, <b>five different strengths</b> of Panorama Effect, all of which increase the population of a particular skyscraper.<br />The effect grows in strength based on the number of <b>smaller skyscrapers</b> around it.": "",
    "Note that you will not be punished for maintaining <b>no Panorama Effect</b>: the skyscraper will still have the regular population amount.": "",
    "Panorama Effect — Radius": "",
    "Skyscrapers in a Radius": "",
    "Each <b>individual</b> skyscraper counts other skyscrapers within a certain radius when calculating its Panorama Effect. The higher that skyscraper is, the <b>bigger its radius will be</b>. <br /><b>Regular residences</b> are <b>not</b> taken into account!": "",
    "Can never have a Panorama Effect": "",
    "Skyscraper Level 1": "",
    "Skyscraper Level 2": "",
    "Skyscraper Level 3": "",
    "Skyscraper Level 4": "",
    "Skyscraper Level 5": "",
    "Panorama Effect — Calculation": "",
    "Calculation of the Panorama Effect": "",
    "Select different skyscrapers to see how and which neighbours are tinted with colours.": "",
    "<b>Green:</b> <br />Smaller skyscraper, acts like a +1 modifier.": "",
    "<b>Brown:</b> <br />Taller skyscraper, acts like a -1 modifier. <br />Skyscraper of equal height, acts like a -1 modifier.": "",
    "<b>No colour:</b> <br />Is too far away, has no effect. <br />Is not a skyscraper, has no effect.": "",
    "The <b>sum of all modifiers</b> determines the Panorama Effect that the selected skyscraper will get. <br />This will never go below zero, or above five.": "",
    "Assembly Lines": "",
    "Changing the Output": "",
    "<b>Assembly Lines</b> are multifactories that can produce industrial patents.": "",
    "The <b>Parts Catalogue</b> allows you to switch the industrial patent that's being produced on the fly. It can be accessed from the building menu. Different input goods will be required based on the selected patent.": "",
    "Make sure you have a <b>Warehouse</b> in range to supply the required input goods.": "",
    "This building <b>requires electricity</b>.": "",
    "This building <b>can be improved with electricity</b>": "",
    "Artisan Workshops": "",
    "<b>Artisan Workshops</b> are Multifactories that allow you to produce artisanal wares.": "",
    "The <b>Craft Catalogue</b> allows you to switch the artisanal wares being produced on the fly. It can be accessed from the building menu. Different input goods will be required based on the selected patent.": "",
    "Make sure you have a <b>Warehouse</b> in range to receive the final products.": "",
    "Ensure there's enough space to plant trees.": "",
    "Orchards": "",
    "<b>Orchards</b> are Multifactories that allow you to produce natural products from trees, similar to the lumberjack's hut.": "",
    "The <b>Orchard Catalogue</b> allows you to switch the natural product that's being produced on the fly. It can be accessed from the building menu.": "",
    "Chemical Plants": "",
    "<b>Chemical Plants</b> are multifactories that allow you to produce chemical formulas.": "",
    "The <b>Formula Codex</b> allows you to switch the chemical formula that's being produced on the fly. It can be accessed from the building menu. Different input goods will be required based on the selected patent.": "",
    "Shopping Arcades": "",
    "<b>Shopping Arcades</b> function like public services, but consume input goods. The input goods required depend on which <b>design patent is currently active</b> in the arcade. You can switch the current design patent in the building menu, selecting new ones from the <b>Shopping Catalogue</b>.": "",
    "Impact on Residents": "",
    "All Skyscrapers within the <b>green street overlay</b> range of the Shopping Arcade have their need for it fulfilled. <br /><br />For Skyscraper residents, <b>any active design patent</b> will fulfill their need for the respective Shopping Arcade.<br />Depending on the <b>chosen design patent</b>, there are a variety of beneficial effects on residences <b>within a radius</b> of the Shopping Arcade.": "",
    "<b>Recipe books</b> allow you to pick a single active product for Shopping Arcades from a selection. <b>Multifactories</b> such as <b>Orchards</b> or <b>Assembly Lines</b> have catalogues that follow the same principle. <br /><br />They are accessed from the respective building's menu.": "",
    "Monument — The Skyline Tower": "",
    "Behold the modern <b>Skyline Tower</b> — the final building introduced with The High Life. As with all <b>Monuments</b> there are several phases to its construction, and only one Skyline Tower can be built <b>per island</b>. <br /><br />The Skyline Tower also has significant <b>maintenance costs. Manage your income and expenditure</b> accordingly!": "",
    "The Ultimate Luxury Residence": "",
    "The Skyline Tower is, in principle <b>a residence</b> just like other skyscrapers. Thus, an exorbitantly high number of investors can live in it. <br /><br />Skyline Tower residents simply cannot do enough shopping: <b>the wider variety of shopping arcade products</b> there are available, <b>anywhere on the island</b>, the more the tower’s population will increase. <br /><br />Take note though, that the Investors acquired from shopping arcades <b>do not consume any other goods</b>, so are essentially <b>\"free\"</b>.": "",
    "Skyscrapers": "",
    "You've already gifted zoo tickets recently!": "",
    "You've already organised a barbecue recently!": "",
    "You've already shared bonuses recently!": "",
    "Food & Drink Venues": "",
    "Bonus Population": "",
    "These residents are moving in thanks to the various shopping opportunities, and they consume no goods at all!": "",
    "Click to open the Bonus Population Screen": "",
    "Skyscraper Upkeep": "",
    "Skyline Tower": "",
    "TutorialHint Tourists": "",
    "New restaurant recipe unlocked": "",
    "New café recipe unlocked": "",
    "New bar recipe unlocked": "",
    "New Iron Tower recipe unlocked": "",
    "Pedestrian Bridge": "",
    "Lamp Archway": "",
    "Underpass": "",
    "Underground Toilet": "",
    "Pavilion": "",
    "Toilet House": "",
    "Pedestrian Zone Entrance": "",
    "Market Hall": "",
    "Canal Bridge Small": "",
    "Canal Bridge Medium": "",
    "Canal Bridge Large": "",
    "Enclosed Tree": "",
    "Groundplanes": "",
    "Fearless Volunteer": "",
    "Flag Archway": "",
    "Clock Archway": "",
    "Hire: [AssetData([RefGuid]) Text]": "",
    "Level Value:": "",
    "Smaller Neighboring Skyscrapers:": "",
    "Taller or Equal Neighboring Skyscrapers:": "",
    "Panorama:": "",
    "Blue Skies Delivery Service": "",
    "Blue Skies Maid": "",
    "Blue Skies Janitor": "",
    "Select different skyscrapers to see which of those around them are highlighted.": "",
    "<i>Example with Level 2 skyscraper: the starting value is 2, and the sum of all modifiers is 4.</i>": "",
    "Click on the \"?\" in the skyscraper menu to get more information about the Panorama Effect.": "",
    "Deliver to: [AssetData([RefGuid]) Text]": "",
    "Even new apartments have their little defects.": "",
    "With a little help, the place looks as good as new!": "",
    "For those who love their new sky abodes too much to leave em’ for too long.": "",
    "Donny is aghast that you lost the tower.": "",
    "Lose Monument": "",
    "Store Types": "",
    "Donny’s already considering new markets — something that could give the Engineers illuminating ideas.": "",
    "Donny’s loving the lamp sales. For his next hit, he’s considering asking his customers directly what they want.": "",
    "Donny’s sure the saboteur is a wannabe investor. He plans to make him all the more jealous with a bright smile.": "",
    "Donny’s suspicious. The toothpaste is a hit, but his financial reports don’t reflect its sales.": "",
    "Donny’s dream is to have the arcades filled with big spenders.": "",
    "Donny feels unseen among all the investors, and is contemplating how to change that.": "",
    "+x influence for skyscrapers": "",
    "Maintenance Upgrade": "",
    "Select your maintenance expenses per skyscraper": "",
    "Upkeep of skyscraper level 1 will cost:": "",
    "Escort: [AssetData([RefGuid]) Text]": "",
    "Look at: [AssetData([RefGuid]) Text]": "",
    "Discovered": "",
    "Talk to: [AssetData([RefGuid]) Text]": "",
    "Once your residents' needs are fulfilled and the residence is at its full capacity, you'll be able to upgrade to the next skyscraper level.": "",
    "Missing Research Points": "",
    "Lose Lab": "",
    "Lose Lab": "",
    "Lose Lab": "",
    "Leave the hustle and bustle down below.": "",
    "Relax, it's never fallen down before!": "",
    "Flamboyant flags fluttering in the wind add a touch of colour to the street.": "",
    "An unmissably large clock – since it’s so easy to lose track of time around here.": "",
    "Tired of dodging traffic? Take the subterranean route.": "",
    "Some things are best kept out of sight.": "",
    "A place to sit, rest, and enjoy the sights and sounds of a bustling city.": "",
    "A rather elegant structure for such an inelegant purpose.": "",
    "Welcome to the Pedestrian Zone! A city such as this is best enjoyed on foot, don’t you think?": "",
    "Stalls piled high with every kind of fruit, baskets overflowing with fresh vegetables, vendors barking out their prices…": "",
    "A short hop across the water.": "",
    "“Alright, everybody walk on the left hand side. The left, I said!”": "",
    "Plenty of space to stand and feed the numerous ducks down below.": "",
    "Our trees-to-residents ratio could always be improved...": "",
    "PEDESTRIAN ZONE PACK": "",
    "The Pedestrian Zone Pack gives you the chance to build beautiful canals throughout your city, and provide your pedestrians with all the amenities they could ever ask for, from pavilions to public toilets!": "",
    "You will find the Pedestrian Zone ornaments under this category in the construction menu:": "",
    "Set Sail": "",
    "Yaosca Rodriguez": "",
    "Jornalero": "",
    "Jornalero": "",
    "Obrera": "",
    "Obrera": "",
    "Old Nate": "",
    "Yaosca's Harbour": "",
    "Ruin": "",
    "La Xultuna": "",
    "The Settlement": "",
    "Here is the port — we made everything ready for you. Please, establish a settlement for the workers as soon as you can!": "",
    "Yaosca provides you with a harbour.": "",
    "Before work on the dam can begin, Yaosca needs you to establish a new settlement for the workers.": "",
    "<i>Isabel Sarmento travels to an ancient island still reeling from its recent Pyrphorian occupation. Her task: to build a hydroelectric dam, while maintaining the island's fragile ecosystem.</i>": "",
    "You play as Isabel Sarmento. Your task is to help the islanders generate electricity in a safer, greener way: by building a hydroelectric dam.": "",
    "Challenge your skills by embarking on this colossal construction project while maintaining the island’s ecological balance. Explore an ancient land scarred by the Pyrphorian occupation, find sustainable ways to build your town, and respond to crises caused by the collapsing ecosystem.": "",
    "Yaosca asks you to establish the settlement quickly.": "",
    "Please Isabel, waste no time in establishing the settlement.": "",
    "The Dam": "",
    "With our settlement established, work on the dam can begin.": "",
    "Yaosca asks that you start work on the dam right away.": "",
    "With the settlement constructed and the first workers accommodated, it's time to begin building the dam.": "",
    "The first phase of the project is complete. A promising start.": "",
    "The dam is ready for the final phase of its construction. No turning back now.": "",
    "The first phase of the dam is complete.": "",
    "The second phase of the dam is complete.": "",
    "Imagine what the ancestors could have built, if they had our tools.": "",
    "I know the schematics of the dam like the back of my hand.": "",
    "Technology may have got us into this mess, but it can help us out of it too.": "",
    "We tried to resist the Pyrphorians like you did, but... we were overcome.": "",
    "How I long to see the parrots returning to the trees.": "",
    "We are still healing after the Years of Fire.": "",
    "I have the utmost confidence in the design of the dam. It cannot fail.": "",
    "I must get back to work.": "",
    "All the prototypes we're developing at the village... they'll be worthless if we can't generate electricity.": "",
    "During the Years of Fire, Yaosca kept our spirits high. Such dignity under... such cruelty.": "",
    "Some worked with the Pyrphorians willingly, yes... But most of us, we had no choice!": "",
    "I don't think they care much for the dam, but the jornaleros care deeply for this land.": "",
    "The smoke... I can hardly breathe!": "",
    "Quick, save my notebooks!": "",
    "I never used to get sick this often.": "",
    "I can’t even think about the dam right now — this fever is too much!": "",
    "We can't get to the construction site without a road.": "",
    "I feel so disconnected.": "",
    "You managed to slip provisions to hundreds of underground resistance fighters — keeping us supplied should be easy!": "",
    "I really don’t think we’re asking for too much, Isabel.": "",
    "I expected more from a great leader like you.": "",
    "How can I concentrate on my work when I don’t have the bare necessities?": "",
    "Isabel, please don’t let us down.": "",
    "Asked to work without the most essential supplies... It's like the Years of Fire all over again.": "",
    "So much easier to concentrate when I’ve got everything I need.": "",
    "I’m glad Yaosca brought you to us.": "",
    "You truly are a great leader, Isabel!": "",
    "Keep us supplied, and we’ll keep building the dam!": "",
    "Bien! My shelves are full.": "",
    "During the Years of Fire, we could only dream of such quality of life.": "",
    "You won't heal the land without our help.": "",
    "Do you just want to chat, or are you going to get down in the soil and help us?": "",
    "I’ve been working this land since I first learned to walk.": "",
    "I’ve seen droughts, plagues, famines, blights – the Pyrphorians were nothing I couldn’t handle!": "",
    "I’ve always said that messing around with machines would lead to no good!": "",
    "Yaosca may trust you, but it takes more than a big reputation to convince me.": "",
    "I don't want my grandchildren to grow up in a blasted wasteland.": "",
    "Optimism is useless to me. You’ll get nothing done without hard work.": "",
    "Treat our island with care. This was home to my abuelo, and his abuelo before him, and his abuelo before him.": "",
    "Yaosca? Hmm, I'd rather a leader with a bit of dirt under their fingernails.": "",
    "Yes, we worked the land for the Pyrphorians - that way we could make sure it was protected!": "",
    "Some of those Obreras practically begged the Pyrphorians to come here. Blame them for this!": "",
    "Everything I have is going up in flames!": "",
    "Another fire! There is something very wrong on this island!": "",
    "I... I'll work on the dam later. Right now I need the doctor.": "",
    "Mi estómago... It hurts!": "",
    "Maybe build a road before you try to build a dam.": "",
    "Is a road really too much to ask?": "",
    "Good luck building that dam when you can’t even provide for our basic needs!": "",
    "Is this how you treat your own people?": "",
    "At least the Pyrphorians kept us fed and clothed!": "",
    "Life is hard enough – you just make it harder!": "",
    "I don't ask you for much, Isabel.": "",
    "All work and no reward... Some leader you are.": "",
    "We’ve got everything we need to get to work.": "",
    "I have everything I need – now focus on the island.": "",
    "You know how to keep us supplied, I'll give you that.": "",
    "Care for our island as well as you care for us, and I'll be happy.": "",
    "No complaints from me... For now!": "",
    "Me? Oh, I’m doing fine.": "",
    "I can't wait to see this place flooded.": "",
    "I never thought I'd be back working here...": "",
    "Anything to get rid of this Pyrphorian mess.": "",
    "It has to be thicker at the bottom than at the top - deeper water, more pressure, you see?": "",
    "It's going to be huge. And unsightly...": "",
    "The build-up of sediment could be an issue...": "",
    "There's still so much to do!": "",
    "I don't know how we're going to produce enough concrete.": "",
    "That electrical wiring looks a little frayed...": "",
    "It's enormous — I feel like a fire ant next to a ceiba tree!": "",
    "I said fifty bags of concrete, not fifteen!": "",
    "This thing is an eyesore.": "",
    "We're going to live downstream from this? Are we sure it's safe?": "",
    "We need this huge thing to power our little village?": "",
    "It's too late to stop now.": "",
    "All I'm saying is, how are the fish going to get through?": "",
    "The curvature will send some of the pressure to the rock walls.": "",
    "I didn't think we'd make it this far. We're so close.": "",
    "You're accusing me? Don't think I never saw you with that Pyrphorian guard!": "",
    "Manuel isn't hopeful about the harvest. I hope we'll have enough...": "",
    "You go to bed on time tonight, little one, or the Pyrphorians will get you.": "",
    "Go easy on her. Things have been hard since her husband disappeared.": "",
    "They say in the far north, the glaciers have been slowly melting for some time...": "",
    "So he filled the tube with different gases, and found that they massively increased the absorption of heat...": "",
    "I tried to tell him! You keep cutting down the trees, the soil erodes, you get landslides!": "",
    "It's real jade, this necklace. Been in the family for centuries.": "",
    "I've been studying Dr. Buendia's windfarm prototype — I think she might really be onto something!": "",
    "Five factories I sabotaged during the Years of Fire, five! Don't you question me!": "",
    "Come now, hopelessness is hardly an option.": "",
    "Nothing like ecological collapse to get you out of bed in the morning...": "",
    "I need those soil samples delivered, immediately.": "",
    "I made some adjustments to the Aquafarm design — the fish should be much healthier this way.": "",
    "Oh no no no, don't tell me that was one of the books the Pyrphorians burned!": "",
    "Ramon lived there... Before the Pyrphorians came for him.": "",
    "I think we need to consider what will happen downriver. We just don't know enough yet!": "",
    "The birds got covered in the oil... I couldn't bear to watch.": "",
    "Water. Earth. Fire. Air. Long ago, this island's ecosystem was well-balanced...": "",
    "He was feverish, kept saying he saw a polar bear in the jungle. I don't think he has long left.": "",
    "The new town is so far from the forest garden.": "",
    "...and then, all of a sudden, he was repaying his debts and buying his mistress a new dress. Must have found one of those Pyrphorian stashes!": "",
    "The dam can't be rushed. Imagine if it were to collapse!": "",
    "I need to get back to the library.": "",
    "I've been eating fish every day for 23 years!": "",
    "I never thought I'd get out of that Pyrphorian work camp alive.": "",
    "I think this time would be better spent praying.": "",
    "The Lord will judge us for what we've done to this land.": "",
    "When the Pyrphorians came for my nephew, I hid him under the floorboards.": "",
    "The Mesoans would clean the chultun with aquatic turtles. Now that's real ingenuity.": "",
    "It shouldn't be this hot, not at this time of year.": "",
    "Oh yes, tell me again about how brave you were during the Years of Fire.": "",
    "If we have to leave... well, I don't even want to think about it.": "",
    "Francisco says this is a test, a test from the Lord! We harmed his creation, and now we have to fix it.": "",
    "I went up to the ruins to look over the island. I can't believe what we did to this place.": "",
    "I can't sleep at night. Visions of fire...": "",
    "Then, everything changed when the Pyrphorians attacked.": "",
    "A little rum in my atole, to get me through the day.": "",
    "Red sky at night, jornalero's delight.": "",
    "Keep your head down, focus on your work, just like during the Years of Fire.": "",
    "I don't think Sarmento knows what she's gotten herself into.": "",
    "If we survive this, I'll ask her to marry me.": "",
    "Chorizo! Chorizo! Has anyone seen my dog?": "",
    "I'm glad I'm not the one who has to make the decisions here. It seems there's just one dilemma after another...": "",
    "It came out of the forest! Looking for food, I think.": "",
    "It's been a long time since I went swimming. The water here... I'm not touching it.": "",
    "Have the nightmares stopped for you yet?": "",
    "Before you go accusing me, why don't you explain all those extra rations the Pyrphorians would give you?": "",
    "Eavesdropping again? Old habits die hard for a Pyrphorian informant, I suppose.": "",
    "Make sure you boil the water, it isn't so safe these days...": "",
    "We never found his body. I think the Pyrphorians must have burned him.": "",
    "He told me he's given up the rum - only atole from now on.": "",
    "The chlorination experiments seem promising - we could really improve our water filtration.": "",
    "We need bold solutions! Think the unthinkable! Not you, obviously - you can't even deal with thinking the thinkable.": "",
    "She won't even talk to me any more. I think she's too ashamed.": "",
    "My son wants to study ancient history. I wish he'd choose a more practical subject.": "",
    "When the guano runs out, artificial fertilisers will be the way forward, I'm telling you...": "",
    "He doesn't comprehend the difference a few degrees can make. I tried to explain!": "",
    "Red next to black, jump way back; red next to yellow, cuddly fellow.": "",
    "I know I missed your birthday, I know - all I can think about is the dam right now.": "",
    "I need to get back to the forest garden.": "",
    "Yaosca looks so tired these days. No wonder she needed help...": "",
    "The wretched baby was howling all night. I would too, if my father was a Pyrphorian.": "",
    "It's called a kinkajou - it's like a cross between a monkey and a raccoon.": "",
    "Up close, Isabel looks nothing like what I expected.": "",
    "I never had the chance to tell her I love her. The Pyphorians came in the night, and...": "",
    "All this effort put into the dam... Wind power is the way forward, I'm certain.": "",
    "He begged me to forgive him. The dirty collaborationist rat...": "",
    "We need to be precise with these measurements - Isabel is counting on them.": "",
    "She works night and day on the encyclopaedia - trying to finish it before the birds disappear entirely...": "",
    "I don't talk about the Years of Fire. Especially not with busybodies like you.": "",
    "We should have started measuring the fish population sooner!": "",
    "Pile of Materials": "",
    "Nutrient Imbalance": "",
    "The soil is developing very high levels of nitrates, which are subsequently filtering into the water supply. Unless we do something, this is sure to impact the health of our residents.": "",
    "We must allow the soil to rest regularly.": "",
    "We'll lay mulch over the fields.": "",
    "If the water is drinkable, that’s good enough.": "",
    "Isabel, we really must address the way we treat the soil.": "",
    "Our farms will be less productive, but at least the soil can heal.": "",
    "Mulch — that could work, but we'll need to source the wood for it.": "",
    "Drinkable yes, but for how long?": "",
    "Fallow Land": "",
    "Due to the poor soil quality, nitrates are running into the water.": "",
    "As a measure to restore soil quality, some of your fields are lying fallow, reducing productivity.": "",
    "Unbalanced Nutrients": "",
    "Decide how to restore the balance of the soil.": "",
    "Cost": "",
    "Missing Resources": "",
    "Our overexploitation of the soil has left it lacking many of the nutrients our crops need to grow. Yields are decreasing at an alarming rate.": "",
    "We’ll use workers to bring animal manure to the fields.": "",
    "We'll use rotten fruit as fertilisers.": "",
    "We'll just have to plant more.": "",
    "Decide how to restore the health of the soil.": "",
    "Soil Impoverishment": "",
    "The soil yields so little now. We must do something to restore it!": "",
    "A sustainable solution — if a malodorous one!": "",
    "Better than letting it go to waste!": "",
    "So you're just going to let our soil become barren?": "",
    "Manure Management": "",
    "Impoverished Soil": "",
    "Yaosca is concerned by your carelessness.": "",
    "The entire food chain is suffering from the poor water quality — animals are growing sick and dying at unusually high rates.": "",
    "We'll use more animals per farm to compensate for the sick ones.": "",
    "We have more important problems than a few sick animals!": "",
    "We must clean the water supply.": "",
    "Decide how to deal with the dirty water our animals are forced to drink.": "",
    "Yaosca is disappointed.": "",
    "Our people’s drinking water is unclean and inadequately filtered. Who knows what illnesses they might contract from it!": "",
    "We will encourage the people to only consume processed drinks.": "",
    "We will provide a constant supply of antibiotics.": "",
    "I'm sure we'll develop a natural immunity.": "",
    "Decide how to deal with the contaminated water supply.": "",
    "The heavy smog is damaging our plants and trees — the soot accumulating on the leaves is seriously affecting their growth. Something must be done, or our reforestation efforts will be severely slowed.": "",
    "The foresters will have to double their work for a while.": "",
    "We need to increase the air quality.": "",
    "There are still plenty of trees left.": "",
    "Decide how to deal with the polluted air.": "",
    "The rising temperature is attracting invasive species which destroy our plants, and might wipe out some crops entirely!": "",
    "We'll have to plant more of each crop.": "",
    "We'll fight the invaders with pesticides.": "",
    "The farms will be less productive.": "",
    "Decide how to deal with plant-eating pests.": "",
    "Yaosca is surprised by your lack of action.": "",
    "Recent deforestation has destabilised the soil, causing a landslide! One of our ore deposits is now completely blocked.": "",
    "We’ll put half of our jornaleros to work on it, and give them specialised tools to do the job faster.": "",
    "We’ll put half of our jornaleros to work on it.": "",
    "Never mind, there are other ore deposits.": "",
    "Decide how to deal with the recent landslide.": "",
    "Yaosca is frustrated with your inaction.": "",
    "Many of the herbs used by our doctors are taken from the forest, but many are beginning to disappear. Something must be done to ensure the health of the people.": "",
    "We’ll gather what’s left in the forest, and make a herb garden in the village.": "",
    "Sugar cane juice makes for an excellent restorative.": "",
    "Herbs? We’ve got more important matters to deal with!": "",
    "Decide how to deal with the important flora disappearing from the forest.": "",
    "Yaosca approves of your initiative.": "",
    "Yaosca is shocked by your callousness.": "",
    "Deforestation is affecting the monkey population, which in turn is hindering the growth of the forest, as monkeys play a key role in seed dispersal. The forest will grow thinner and less abundant if we do not act.": "",
    "We must let the forest regenerate, so that the monkeys can return and thrive.": "",
    "We’ll supply the foresters with fertilisers to accelerate the regeneration of the trees.": "",
    "Monkeys are smart enough to take care of themselves.": "",
    "Decide how to deal with the dwindling monkey population.": "",
    "Animal Quarantine": "",
    "Contaminated Animals": "",
    "Contaminated Animals": "",
}

# Add skips to skip.json
skip_file = "skip.json"
skips = []
if os.path.exists(skip_file):
    try:
        skips = json.load(open(skip_file, encoding="utf-8"))
    except Exception:
        skips = []

skips_set = set(skips)
for s in skips_to_add:
    skips_set.add(s)
new_skips = sorted(list(skips_set), key=lambda x: int(x))
json.dump(new_skips, open(skip_file, "w", encoding="utf-8"), ensure_ascii=False, indent=0)
print(f"Updated skip.json: {len(new_skips)} total skips")

# Clean up other trans_part_*.json files
for i in range(2, 6):
    p = f"trans_part_{i}.json"
    if os.path.exists(p):
        os.remove(p)
        print(f"Deleted old {p}")
for i in range(1, 6):
    p = f"skip_part_{i}.json"
    if os.path.exists(p):
        os.remove(p)
        print(f"Deleted old {p}")

# Translate the batch
translated = {}
missing = []
for guid, val in batch.items():
    if guid in skips_to_add:
        continue
    if val in mapping:
        translated[guid] = mapping[val]
    else:
        # Check if it was stripped by auto_skip or is in skips
        if guid in skips_set:
            continue
        missing.append((guid, val))

if missing:
    print(f"Error: {len(missing)} missing translations in batch!")
    for g, v in missing[:10]:
        print(f"  {g}: {v!r}")
else:
    # Save to trans_part_1.json
    json.dump(translated, open("trans_part_1.json", encoding="utf-8"), ensure_ascii=False, indent=4)
    print(f"Successfully saved {len(translated)} translations to trans_part_1.json")