# -*- coding: utf-8 -*-
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
CB = os.path.join(HERE, "current_batch.json")
he = {
 "RootElements/Shazam": "Shazam",
 "RootElements/SoundCloud": "SoundCloud",
 "RootElements/Stems": "סטמס",
 "RootElements/Sunfly": "Sunfly - קריוקי מקצועי",
 "RootElements/TIDAL": "TIDAL",
 "RootElements/Traktor": "Traktor",
 "RootElements/VJPro": "VJ'Pro - וידאו מקצועי",
 "Search/Album": "אלבום",
 "Search/Author": "אמן",
 "Search/Bpm": "BPM",
 "Search/Comment": "הערה",
 "Search/Composer": "מלחין",
 "Search/FileName": "שם הקובץ",
 "Search/FilePath": "נתיב הקובץ",
 "Search/Genre": "סגנון",
 "Search/Grouping": "קיבוץ",
 "Search/Key": "סולם",
 "Search/Label": "לייבל",
 "Search/Remix": "רמיקס",
 "Search/Remixer": "רמיקסר",
 "Search/Title": "כותרת",
 "Search/User1": "שדה1",
 "Search/User2": "שדה2",
 "Search/Year": "שנה",
 "Settings/analyzeSongsOnView": "כשמופעל, קבצים שלא נסרקו נסרקים אוטומטית תוך כדי העיון בהם",
 "Settings/askTheDJFrequency": "התדירות (בשניות) שבה מתעדכן AskTheDJ",
 "Settings/askTheDJMonitoring": "בחר אם AskTheDJ ממשיך לבדוק בקשות כשהתיקייה אינה מוצגת",
 "Settings/audioAutoDetect": "המשך לבדוק אחר התקנים חדשים כדי לזהות מתי מחובר כרטיס קול מוכר",
 "Settings/autoBPMMatch": "משנה אוטומטית את הפיץ' כדי להתאים ל-BPM של הדק השני כשנטען שיר חדש (\"smart\" פועל רק כשה-BPM של השיר בטווח של 10% מהשיר בדק השני)",
 "Settings/autoBpmStabilizer": "מייצב אוטומטית את ה-BPM של טראקים משתנים במהלך מעברים",
 "Settings/autoBpmStabilizerKeepBpmOnExit": "אם autoBpmStabilizer נעל את ה-BPM במהלך מעבר, הזז את הפיץ' בסוף המעבר כדי לשמור על ה-BPM הזה גם לאחר שמייצב ה-BPM משתחרר",
 "Settings/autoBpmStabilizerMaxRange": "הפרש ה-BPM המרבי באחוזים שמייצב ה-BPM ייצב",
 "Settings/autoBpmTransitionLength": "אורך המעבר שמבצע auto_bpm_transition, ביחידות של פעימות",
 "Settings/autoCue": "עובר אוטומטית לקיו הראשון או לפעימה הראשונה כשנטען שיר",
 "Settings/autoDiscMarker": "מחזיר אוטומטית את סמן התקליט ל-0 מעלות בנקודות קיו",
 "Settings/autoGain": "מגדיר אוטומטית את הגיין כך שעוצמת הקול הכללית של השיר תהיה 0dbA כשנטען שיר (או זוכר כל שינוי ידני קודם של הגיין)",
 "Settings/autoHeadphones": "מעביר אוטומטית את האוזניות ואת הדק הנבחר לשיר שנטען או נגע בו זה עתה",
 "Settings/autoKey": "משנה אוטומטית את הסולם כשנטען שיר כדי להתאים לסולם של השיר בדק השני, כשהפרש הסולם הוא עד חצי טון",
 "Settings/automaticDatabaseBackupPeriod": "מספר הימים בין כל גיבוי אוטומטי של מסד הנתונים, או 0 לביטול הגיבוי האוטומטי",
 "Settings/automixAutoRemovePlayed": "קבצים יוסרו מרשימת ההשמעה של האוטומיקס כשהם מתנגנים במהלך האוטומיקס, או בכל פעם שהם מתנגנים",
 "Settings/autoMixBeatMatchOnFade": "כשמצב האוטומיקס מוגדר ל-fade והקצב של השירים קרוב זה לזה, הם יסונכרנו בפעימות",
 "Settings/automixDoubleClick": "כשהאוטומיקס פעיל, בחר מה קורה בלחיצה כפולה על שיר",
 "Settings/automixDualDeck": "השתמש בשני הדקים ובקרוספיידר לביצוע האוטומיקס, במקום לעשות הכול על דק בודד",
 "Settings/automixMaxLength": "הזמן המרבי (בשניות) שבו שיר יתנגן באוטומיקס לפני מעבר לשיר הבא",
 "Settings/automixMode": "אלץ את מנוע האוטומיקס להשתמש במצב מסוים אחד",
 "Settings/automixRepeat": "רשימת ההשמעה של האוטומיקס תחזור על עצמה מההתחלה כשתגיע לסופה",
 "Settings/automixSkipLength": "מספר הפעימות לעמעום כשמאלצים את האוטומיקס לדלג לשיר אחר (לחיצה כפולה או mix_now לדוגמה)",
 "Settings/automixTempoMode": "כשהאוטומיקס עובר לשיר הבא, הוא יכול לחזור ל-0% פיץ', לשמור על אותו פיץ', או לשמור על אותו BPM (כשאפשר, בטווח פיץ' של 10%±)",
 "Settings/autoPitchLock": "מפעיל אוטומטית את pitch_lock בכל פעם שה-BPM מותאמים, כך שהזזה ידנית של מחוון פיץ' אחד תזיז את השני כדי לשמר את ההתאמה",
 "Settings/autoPitchRange": "מכוונן אוטומטית את טווח הפיץ' כשהתאמת הפיץ' דורשת טווח רחב יותר",
 "Settings/autoRefreshDRM": "רענן אוטומטית את ה-DRM של השירים שהורדת מהקטלוגים המקוונים שלך כשהם קרובים לפקיעת התוקף",
 "Settings/autoSearchDB": "הוסף אוטומטית למסד נתוני החיפוש כל שיר ש-VirtualDJ נתקל בו בזמן העיון בתיקיות ובכוננים שלך",
 "Settings/autoSideview": "החלף את התצוגה הצדדית לדוגם כשמשתמשים בפעולה sampler_bank כדי להחליף בנק סמפלים",
 "Settings/autoSortCues": "מיין אוטומטית את נקודות הקיו לפי סדר כרונולוגי",
 "Settings/beatCounterRange": "קבע על פני כמה פעימות סופר מונה הפעימות בעיצוב (ברירת מחדל: 16)",
 "Settings/beatjump": "מספר הפעימות שסקריפט ה-beatjump ידלג",
 "Settings/boothMicrophone": "כניסת המיקרופון נשמעת גם ביציאת השמע של ה-booth",
 "Settings/broadcastDirectFormat": "פורמט הקובץ המשמש לשידור (\"ogg\" באיכות טובה יותר אך פועל רק ב-Chrome, \"mp3\" פועל בכל דפדפן)",
 "Settings/broadcastDirectMaxClients": "המספר המרבי של מאזינים שיכולים להתחבר למחשב שלך בו-זמנית בשידור ישיר (אל תגדיר ערך גבוה מדי אם אין לך רוחב פס גדול)",
 "Settings/broadcastDirectName": "שם השידור שלך",
 "Settings/broadcastDirectPort": "פורט האינטרנט המשמש לשידור ישיר",
 "Settings/broadcastDirectQuality": "איכות הקידוד (דחיסה) בעת שימוש בשידור ישיר",
 "Settings/broadcastMode": "מצב שידור (\"direct\" אם ברצונך לשדר ישירות מהמחשב שלך, \"server\" אם ברצונך לשדר לתחנת רדיו, \"podcast\" אם ברצונך לשמור את הפודקאסט שלך ב-virtualdj.com לשימוש מאוחר יותר)",
 "Settings/broadcastServer": "כתובת השרת שאליו לשדר",
 "Settings/broadcastSongInfo": "הגדר ל-no אם אינך רוצה שהמאזינים שלך יראו את שמות השירים שאתה מנגן",
 "Settings/broadcastSongInfoFormat": "קבע כיצד מעוצבת הכותרת הנשלחת לשרת השידור",
 "Settings/broadcastVideoKey": "מפתחות הזרמה עבור שידור הווידאו",
 "Settings/broadcastVideoProvider": "שרת שידור הווידאו",
 "Settings/broadcastVideoQuality": "מידת הדחיסה המשמשת בשידור וידאו (ככל שהאיכות נמוכה יותר, הדחיסה גדולה יותר)",
 "Settings/broadcastVideoQualityCustom": "איכות שידור וידאו מותאמת אישית \"resX x resY @ videokbps , audiokbps\"",
 "Settings/broadcastVideoURL": "כתובת ה-URL של שרתי שידור הווידאו",
 "Settings/browserAutoExportM3U": "שמור אוטומטית עותק .m3u ב-%AppData%/VirtualDJ/Playlists/ עבור כל רשימה ב-MyLists (למקרה שאתה משתמש בכלי חיצוני שקורא רק פורמט m3u)",
 "Settings/browserAutoOpenNewDrive": "בחר אוטומטית כונן חיצוני חדש או התקן USB עם חיבורו",
 "Settings/browserAutoZoom": "הגדל אוטומטית את הדפדפן במעבר העכבר",
 "Settings/browserBPMDigits": "כמה ספרות אחרי הנקודה יוצגו בדפדפן בעת הצגת BPM",
 "Settings/browserColumns": "העמודות המוצגות בחלונות הדפדפן השונים",
 "Settings/browserDaysSongsAreNew": "מספר הימים לאחר שקובץ נראה בפעם הראשונה שבהם הוא מקבל את סמל הקובץ החדש",
 "Settings/browserFontSizeButtons": "הצג בסרגל הכלים של הדפדפן כפתורים לכוונון עדין של גודל הגופן, במקום כפתור הגדול/קטן המהיר",
 "Settings/browserGridColumns": "העמודות המוצגות בחלונות הדפדפן השונים בתצוגת רשת",
 "Settings/browserPadding": "ריפוד סביב השורות בדפדפן",
}
b = json.load(open(CB, encoding="utf-8"))
miss = [k for k in b if k not in he]
assert not miss, miss
for k in b:
    b[k]["he"] = he[k]
json.dump(b, open(CB, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("filled", len(b))
