import json
import re
import os

# ── Translation Mapping (English keys to Hebrew) ──────────────────────────────
TRANSLATIONS = {
    "---Custom---": "---מותאם אישית---",
    "---Ready To Go---": "---מוכן להפעלה---",
    "Animal Riding (SP)": "רכיבה על בעלי חיים (שחקן יחיד)",
    "Animations": "אנימציות",
    "Apartment Interiors": "פנים דירות",
    "Arena War Locations (ALPHA)": "מיקומי זירת מלחמה (אלפא)",
    "Auto Drive": "נהיגה אוטומטית",
    "Auto-Clean": "ניקוי אוטומטי",
    "Auto-Flip": "היפוך אוטומטי",
    "Auto-Repair": "תיקון אוטומטי",
    "Auto-kill Enemies": "חיסול אויבים אוטומטי",
    "Basic Stats": "סטטיסטיקות בסיסיות",
    "Biker Businesses": "עסקי אופנוענים",
    "Biker Clubhouses": "מועדוני אופנוענים",
    "Blizzard": "סופת שלגים",
    "Breathe Stuff": "נשימת חומרים",
    "Bullet Gun": "רובה קליעים",
    "Bullet Time": "זמן קליע",
    "Bunkers": "בונקרים",
    "Burn Mode": "מצב בעירה",
    "Centre Breaks": "מרכז מפרידים",
    "Centre Options": "מרכז אפשרויות",
    "Centre Title": "מרכז כותרת",
    "Child Locks": "נעילת ילדים",
    "Clear": "בהיר",
    "Clear Area": "נקה אזור",
    "Clearing": "מתבהר",
    "Clock (System Time)": "שעון (זמן מערכת)",
    "Cloning Options": "אפשרויות שיבוט",
    "Clouds": "מעונן",
    "Collision": "התנגשות",
    "Company Warehouses": "מחסני חברה",
    "Cruise Control": "בקרת שיוט",
    "Custom Coordinates": "קואורדינטות מותאמות אישית",
    "Customisable Apartment Interiors": "עיצוב פנים דירות בהתאמה אישית",
    "Cutscene Player": "נגן סרטוני מעבר",
    "Damage & Defense": "נזק והגנה",
    "Decreased Ped Population": "הפחתת אוכלוסיית הולכי רגל",
    "Decreased Vehicle Population": "הפחתת תנועת רכבים",
    "Decreased Weapon Pickups": "הפחתת נשקים לאיסוף",
    "Delete All Cameras": "מחק את כל המצלמות",
    "Delete Vehicle": "מחק רכב",
    "Door Locks": "נעילת דלתות",
    "Drive On Water": "נהיגה על המים",
    "EMP Mode (For Night-time)": "מצב EMP (ללילה)",
    "Edit Multiple Entities Simultaneously": "ערוך מספר ישויות בו-זמנית",
    "English": "אנגלית",
    "Entity Removal Gun": "רובה להסרת ישויות",
    "Explosions At Waypoint": "פיצוצים בנקודת היעד",
    "Explosive Ammo": "תחמושת מתפוצצת",
    "Explosive Melee": "מתקפה פיזית מתפוצצת",
    "ExtraSunny": "שמשי מאוד",
    "Favourites": "מועדפים",
    "Fireworks Ahoy": "הפעלת זיקוקים",
    "Flamethrower Fire Extinguisher": "מטף להביור",
    "Flaming Bullets": "קליעים בוערים",
    "Fly Auto": "טיסה אוטומטית",
    "Fly Manual": "טיסה ידנית",
    "Fly Mode": "מצב טיסה",
    "Foggy": "ערפילי",
    "Forcefield": "שדה כוח",
    "Forge Gun": "רובה בנייה",
    "Forward": "קדימה",
    "FreeCam (No-Clip)": "מצלמה חופשית (ללא התנגשות)",
    "Freeze Vehicle": "הקפא רכב",
    "French": "צרפתית",
    "Game Camera Options": "אפשרויות מצלמת משחק",
    "Ghost Rider Mode": "מצב גוסט ריידר",
    "Give All Weapons": "תן את כל הנשקים",
    "Give Briefcase": "תן מזוודה",
    "Give Digiscanner": "תן סורק דיגיטלי",
    "Give Max Ammo": "תן מקסימום תחמושת",
    "Glue to Ground": "הצמד לקרקע",
    "Gradients": "מעברי צבע (גרדיאנטים)",
    "Gravity Gun": "רובה כבידה",
    "Gravity Level": "רמת כבידה",
    "HUD Options": "אפשרויות ממשק (HUD)",
    "Halloween": "ליל כל הקדושים",
    "Hangars": "האנגרים",
    "Height (Elongation)": "גובה (הארכה)",
    "Heist Facilities": "מתקני שוד",
    "High Altitude": "גובה רב",
    "Hour": "שעה",
    "Hydraulics": "הידראוליקה",
    "Ignored By Everyone": "התעלמות מצד כולם",
    "In-Game Mobile Phone": "טלפון נייד במשחק",
    "Increased Mass": "מסה מוגברת",
    "Individual Weapons & Customisation": "נשקים אישיים והתאמה אישית",
    "Infinite Ammo In Clip": "תחמושת אינסופית במחסנית",
    "Infinite Native Boost (for e.g. Oppressor)": "תאוצה אינסופית (למשל לאופרסור)",
    "Infinite Parachutes": "מצנחים אינסופיים",
    "Interiors": "עיצובי פנים",
    "Invincibility": "אל-מוות (חסינות)",
    "Invincibility (Looped)": "אל-מוות (בלולאה)",
    "Invisibility": "בלתי נראה",
    "Jump-Around Mode": "מצב קפיצות מטורף",
    "Kaboom Gun": "רובה פיצוצים",
    "Keep Engine & Lights On": "השאר מנוע ואורות דולקים",
    "Kill Engine": "כבה מנוע",
    "Landmarks": "נקודות ציון",
    "Language": "שפה",
    "Laser Sight": "כוונת לייזר",
    "Light Gun": "רובה תאורה",
    "Load": "טעינה",
    "Loadouts": "סטים של נשקים",
    "Locations": "מיקומים",
    "MOCs (ALPHA)": "מרכזי מבצעים ניידים (אלפא)",
    "Magnet Gun": "רובה מגנטי",
    "Manage Entity Database": "ניהול מסד נתונים של ישויות",
    "Manage Markers": "ניהול סמנים",
    "Manage Saved Files": "ניהול קבצים שמורים",
    "Manual Respawn": "החייאה ידנית",
    "Map Blips": "סמלים במפה",
    "Map Mods (Old)": "מודי מפה (ישנים)",
    "Massacre Mode": "מצב טבח",
    "Menu Colours": "צבעי תפריט",
    "Menu Fonts": "גופני תפריט",
    "Menu Position": "מיקום תפריט",
    "Menyoo Customs": "התאמות Menyoo",
    "Meteor Shower Mode": "מצב מטר מטאורים",
    "Minute": "דקה",
    "Misc Options": "אפשרויות שונות",
    "Mission Objective": "מטרת המשימה",
    "Model Changer": "מחליף דמויות",
    "Moods": "מצבי רוח",
    "Movement Speed (Alt)": "מהירות תנועה (חלופית)",
    "Movement Styles": "סגנונות הליכה ותנועה",
    "Multi-Platform Neons": "אורות ניאון רב-פלטפורמות",
    "Neutral": "נייטרלי",
    "Never Wanted": "לעולם לא מבוקש",
    "Nightclubs (ALPHA)": "מועדוני לילה (אלפא)",
    "No Gravity": "ללא כבידה",
    "No Ragdoll": "מניעת נפילות (ללא Ragdoll)",
    "Noise Level": "רמת רעש",
    "Not So Fun": "לא כל כך כיף",
    "Object & Vehicle Gun": "רובה אובייקטים ורכבים",
    "Object Spooner": "עורך אובייקטים (Spooner)",
    "Ocean Wave Strength": "עוצמת גלי האוקיינוס",
    "Off": "כבוי",
    "Office Garages": "מוסכי משרד",
    "Office Interiors": "עיצובי פנים של משרדים",
    "Online Related": "קשור למצב אונליין",
    "Opacity (Local)": "שקיפות (מקומית)",
    "Others": "אחרים",
    "Overcast": "מעונן",
    "PV Options": "אפשרויות רכב אישי",
    "Pause Clock Time": "הקפאת זמן שעון",
    "Ped Flags": "הגדרות הולכי רגל",
    "Ped Gun": "רובה הולכי רגל",
    "Ped Revival Gun": "רובה החייאת הולכי רגל",
    "Player Options": "אפשרויות שחקן",
    "Players": "שחקנים",
    "Quick Manual Placement (Legacy)": "מיקום ידני מהיר (מורשת)",
    "Race Boost On Horn": "תאוצת מרוץ בצפירה",
    "Radio": "רדיו",
    "Rain": "גשם",
    "Rain Puddles Multiplier": "מכפיל שלוליות גשם",
    "Rainbow Mode": "מצב קשת בענן",
    "Rapid Fire": "ירי מהיר",
    "Rectangle Draw Tool (Mouse) (ALPHA) [DEV]": "כלי לציור מלבנים (עכבר) (אלפא) [פיתוח]",
    "Refill Health When In Cover": "מילוי חיים בעת תפיסת מחסה",
    "Reload Language Files": "טען מחדש קבצי שפה",
    "Remove All Weapons": "הסר את כל הנשקים",
    "Replenish Player": "מילוי מדדי שחקן",
    "Reset Player Model Upon Death (SP)": "אפס דמות שחקן לאחר מוות (שחקן יחיד)",
    "Reset Toggles (Most Of Them)": "איפוס הגדרות (רובן)",
    "Reset Weather": "אפס מזג אוויר",
    "Restricted Area Access": "גישה לאזורים מוגבלים",
    "Rope Gun (Glitchy)": "רובה חבלים (לא יציב)",
    "Safehouses": "דירות מסתור",
    "Scenario Actions": "פעולות תרחיש (Scenario)",
    "Seatbelt": "חגורת בטיחות",
    "Set Waypoint To Player": "קבע נקודת יעד לשחקן",
    "Set on Fire": "הבער באש",
    "Settings": "הגדרות",
    "Shops": "חנויות",
    "Simple Blackout Mode (For Night-time)": "מצב האפלה פשוט (ללילה)",
    "Slam It (Increase downforce.)": "הצמד לכביש (הגברת כוח הצמדה)",
    "Slidy Tyres": "צמיגים מחליקים",
    "Smash Ability": "יכולת ריסוק",
    "Smog": "ערפיח",
    "Snow": "שלג",
    "Snow On Terrain": "שלג על הקרקע",
    "SnowLight": "שלג קל",
    "Soul-Switch Gun (SP)": "רובה החלפת נשמות (שחקן יחיד)",
    "Spawn Entity Into World": "צור ישות בעולם",
    "Spectate Player": "צפייה בשחקן",
    "Speech Player": "השמעת דיבור",
    "Speedometers": "מדי מהירות",
    "Spooner Mode": "מצב עורך (Spooner)",
    "Super Jump": "קפיצת על",
    "Super Run": "ריצת על",
    "SuprKar Mode": "מצב סופר-קאר (SuprKar)",
    "Sweat Level": "רמת זיעה",
    "Sync Menyoo With Config File": "סנכרון Menyoo עם קובץ ההגדרות",
    "Sync With System Time": "סנכרון עם זמן מערכת",
    "TV Player": "נגן טלוויזיה",
    "Teleport Gun": "רובה טלפורטציה",
    "Teleport Into Closest Vehicle": "שיגור לרכב הקרוב ביותר",
    "Teleport Options": "אפשרויות טלפורטציה",
    "Tenfold Bullets": "קליעים פי עשרה (עוצמה מוגברת)",
    "Themes": "ערכות נושא",
    "Thunder": "רעמים וברקים",
    "Time": "זמן",
    "Time Options": "אפשרויות זמן",
    "Titlebox Globe": "גלובוס בתיבת הכותרת",
    "Top-Down View": "מבט מלמעלה למטה",
    "Tow Mode (ALPHA)": "מצב גרירה (אלפא)",
    "TriggerFX": "אפקטים מותנים (TriggerFX)",
    "TriggerFX Gun": "רובה אפקטים מותנים",
    "Triggerbot": "ירי אוטומטי (Triggerbot)",
    "Underwater": "מתחת למים",
    "Unlimited Special Ability (SP)": "יכולת מיוחדת ללא הגבלה (שחקן יחיד)",
    "Vehicle Jump": "קפיצת רכב",
    "Vehicle Multipliers": "מכפילי רכב",
    "Vehicle Options": "אפשרויות רכב",
    "Vehicle Spawner": "יוצר רכבים",
    "Vehicle Warehouses": "מחסני רכבים",
    "Vehicle Weapons": "נשקי רכב",
    "Vision Hax": "שינוי ראייה (Hax)",
    "Voice Changer": "משנה קול",
    "Walk underwater": "הליכה מתחת למים",
    "Wanted Level": "דרגת מבוקש",
    "Wardrobe": "מלתחה (בגדים)",
    "Water Hack (For Waves At Beaches)": "עריכת מים (לגלים בחופים)",
    "Waypoint": "נקודת יעד (Waypoint)",
    "Weapon Damage": "נזק נשק",
    "Weapon Options": "אפשרויות נשק",
    "Weather": "מזג אוויר",
    "Weather Options": "אפשרויות מזג אוויר",
    "Wind Speed": "מהירות רוח",
    "World Speed": "מהירות עולם",
    "YSC Script [DEV]": "תסריט YSC [פיתוח]",
    "Yachts": "יאכטות",
}

# ── Visual Order Reversal Code ───────────────────────────────────────────────
HE = re.compile(r'[֐-׿]')

def _visual_line(s):
    # Splits into Hebrew tokens, spaces, and other tokens
    runs = re.findall(r'[֐-׿]+|\s+|[^֐-׿\s]+', s)
    # Reverse the order of the tokens, and reverse characters of Hebrew tokens
    return ''.join((r[::-1] if HE.match(r) else r) for r in reversed(runs))

def visual(s):
    # Splits by newline, preserving separators
    parts = re.split(r'(\n|\r)', s)
    return ''.join(p if p in ('\n', '\r') else _visual_line(p) for p in parts)

def main():
    print("Processing Menyoo translations...")
    
    # 1. Generate visual Hebrew JSON
    visual_translations = {}
    for k, v in TRANSLATIONS.items():
        visual_translations[k] = visual(v)
    
    target_path = r"F:\Games\Grand Theft Auto V Legacy\menyooStuff\Language\Hebrew.json"
    
    # Write visual translations to file
    with open(target_path, "w", encoding="utf-8") as f:
        json.dump(visual_translations, f, ensure_ascii=False, indent=2)
    print(f"Generated visual Hebrew language file at: {target_path}")

    # 2. Modify menyooConfig.ini to enable Hebrew language
    ini_path = r"F:\Games\Grand Theft Auto V Legacy\menyooStuff\menyooConfig.ini"
    if os.path.exists(ini_path):
        with open(ini_path, "r", encoding="utf-8") as f:
            ini_content = f.read()
        
        # Replace language line
        # Check if language line exists: language = ...
        updated_content = re.sub(r'^(language\s*=\s*).*$', r'\g<1>Hebrew', ini_content, flags=re.M)
        
        with open(ini_path, "w", encoding="utf-8") as f:
            f.write(updated_content)
        print("Updated menyooConfig.ini: language = Hebrew")
    else:
        print(f"menyooConfig.ini not found at: {ini_path}")

if __name__ == "__main__":
    main()
