#!/usr/bin/env python3
"""get_batch.py — next N strings to translate FROM ENGLISH ONLY (no draft shown).

The Google-Translate drafts were removed on purpose: the agent kept copying them
(98% identical = not translating). Now only the English is given, so every Hebrew
line must be GENERATED by the agent's own Gemini reasoning. "All done!" when empty.
"""
import json, os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.stdout.reconfigure(encoding="utf-8", errors="replace")
def load(n, d):
    p = os.path.join(HERE, n)
    return json.load(open(p, encoding="utf-8")) if os.path.exists(p) else d
def main():
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 250
    src = load("to_translate.json", {})
    done = load("hebrew.json", {})
    skip = set(load("skip.json", []))
    todo = [k for k in src if k not in done and k not in skip]
    if not todo:
        print("All done!"); return
    batch = {k: src[k] for k in todo[:n]}      # ENGLISH ONLY — translate it yourself
    # write a clean UTF-8 file the agent reads directly (no '>' redirect mojibake, no workaround)
    with open(os.path.join(HERE, "batch_en.json"), "w", encoding="utf-8") as f:
        json.dump(batch, f, ensure_ascii=False, indent=1)
    print(f"wrote {len(batch)} strings to batch_en.json — {len(todo)} remaining, {len(done)} done. "
          f"Read batch_en.json, translate all into batch_he.json, then run loop_merge.py.")
if __name__ == "__main__":
    main()
