# Generates icon-manager.html - the launcher icon inventory + a HUGE Flaticon
# UICONS "Interface icons - Regular Rounded" library (~3.9k), now CATEGORIZED
# (browse by category + search) PLUS a curated OFFLINE gaming/controller set
# (Xbox / PlayStation / Switch / D-pad / analog / face-buttons). Assign to any
# slot by drag OR click; exports icon-changes.json.
#
# It also REFLECTS THE APPLIED STATE: the picks in `icon-changes (4).json`
# (7 nav/tab replacements + 63 button/header/badge additions) are shown as the
# CURRENT icon of each slot, so re-picking exports only the NEW delta.
#
# TARGET groups: existing (15 real icons, REPLACE) · window (titlebar controls) ·
# notify (bell states) · controllers (big Settings silhouettes) · optional (72
# icon-LESS UI spots, ADD).
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))

uicons = json.load(open(os.path.join(HERE, 'uicons_map.json')))
UICONS = sorted(uicons.items())
print('uicons in library:', len(UICONS))

optional = json.load(open(os.path.join(HERE, 'iconless_slots.json'), encoding='utf-8'))
print('optional icon-less slots:', len(optional))

# ── group "app": EVERY other user-facing app icon (inline-svg + emoji glyphs that
# had NO customization option before) - generated by build_app_icons.py from the
# frontend inventory, so the manager now covers essentially every icon in the app.
try:
    APP_ICONS = json.load(open(os.path.join(HERE, 'app_icons.json'), encoding='utf-8'))
except Exception as e:
    APP_ICONS = []
    print('no app_icons.json (', e, ') - run build_app_icons.py first')
print('app icons (extra configurable slots):', len(APP_ICONS))

# ── APPLIED picks (reflect the live state) ──
APPLIED = {}       # id -> UICONS iconName
APPLIED_SVG = {}   # id -> raw svg-upload markup
_chg_path = os.path.join(HERE, 'applied_icon_changes.json')
try:
    for c in json.load(open(_chg_path, encoding='utf-8'))['changes']:
        if c.get('iconName'):
            APPLIED[c['id']] = c['iconName']
        elif c.get('newSvg'):
            APPLIED_SVG[c['id']] = c['newSvg']
    print('applied picks reflected:', len(APPLIED), '+', len(APPLIED_SVG), 'svg-upload')
except Exception as e:
    print('no applied_icon_changes.json (', e, ') - showing pristine current icons')

def cur_svg(target_id, fallback_svg):
    """The CURRENT icon shown in the slot - the applied UICONS glyph if the user
    picked one, else an applied svg-upload, else the pristine inline SVG."""
    name = APPLIED.get(target_id)
    if name:
        return '<i class="fi-rr-%s"></i>' % name
    return APPLIED_SVG.get(target_id) or fallback_svg

# ── group 1: the 15 existing launcher icons (current SVGs; 7 now applied) ──
EXISTING = [
  ("nav-home","דף הבית","פריט הניווט 'דף הבית' בסרגל הצד","components/NavIcons.tsx → HomeIcon",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>'),
  ("nav-games","משחקים","פריט הניווט 'משחקים' (בקר משחק)","components/NavIcons.tsx → LibraryIcon",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="6" y1="11" x2="10" y2="11"/><line x1="8" y1="9" x2="8" y2="13"/><line x1="15" y1="12" x2="15.01" y2="12"/><line x1="18" y1="10" x2="18.01" y2="10"/><path d="M17.32 5H6.68a4 4 0 0 0-3.978 3.59c-.006.052-.01.101-.017.152C2.604 9.416 2 14.456 2 16a3 3 0 0 0 3 3c1 0 1.5-.5 2-1l1.414-1.414A2 2 0 0 1 9.828 16h4.344a2 2 0 0 1 1.414.586L17 18c.5.5 1 1 2 1a3 3 0 0 0 3-3c0-1.544-.604-6.584-.685-7.258A4 4 0 0 0 17.32 5z"/></svg>'),
  ("nav-software","תוכנות","פריט הניווט 'תוכנות'","components/Sidebar.tsx → AppsIcon",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="7" height="7" rx="1.6"/><rect x="14" y="3" width="7" height="7" rx="1.6"/><rect x="3" y="14" width="7" height="7" rx="1.6"/><rect x="14" y="14" width="7" height="7" rx="1.6"/></svg>'),
  ("nav-downloads","הורדות ועדכונים","פריט הניווט 'הורדות ועדכונים'","components/NavIcons.tsx → DownloadsIcon",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v12"/><polyline points="7 10 12 15 17 10"/><path d="M4 19h16"/></svg>'),
  ("nav-plugins","תוספים","פריט הניווט 'תוספים'","components/Sidebar.tsx → PluginsIcon",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 3v3a2 2 0 0 0 4 0V3h4a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3v4a1 1 0 0 1-1 1h-4v-3a2 2 0 0 0-4 0v3H6a1 1 0 0 1-1-1v-4H2a2 2 0 0 0 0-4h3V4a1 1 0 0 1 1-1z"/></svg>'),
  ("nav-settings","הגדרות (סרגל צד)","כפתור ההגדרות בתחתית סרגל הצד","components/NavIcons.tsx → SettingsIcon",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"/><circle cx="12" cy="12" r="3"/></svg>'),
  ("avatar-user","אווטאר משתמש (ברירת מחדל)","אווטאר כשלא מחוברים / אין תמונה","components/NavIcons.tsx → UserIcon",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="8.5" r="3.75"/><path d="M4.5 20a7.5 7.5 0 0 1 15 0"/></svg>'),
  ("auth-lock","מנעול התחברות","תג המנעול על סלוט ההתחברות","components/Sidebar.tsx → LockIcon",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="4.5" y="10.5" width="15" height="10" rx="2.3"/><path d="M8 10.5V7a4 4 0 0 1 8 0v3.5"/></svg>'),
  ("misc-folder","תיקייה","אייקון תיקייה כללי","components/NavIcons.tsx → FolderIcon",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 7a2 2 0 0 1 2-2h4l2 2h8a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></svg>'),
  ("tab-general","טאב הגדרות · כללי","אייקון הטאב 'כללי'","views/SettingsView.tsx → IconGeneral",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.6 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.6a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg>'),
  ("tab-appearance","טאב הגדרות · מראה","אייקון הטאב 'מראה'","views/SettingsView.tsx → IconAppearance",
   '<svg viewBox="0 0 24 24" fill="currentColor" stroke="none"><path d="M12 2.5l1.9 5.1a3 3 0 0 0 1.8 1.8l5.1 1.9-5.1 1.9a3 3 0 0 0-1.8 1.8L12 20.1l-1.9-5.1a3 3 0 0 0-1.8-1.8L3.2 11.3l5.1-1.9a3 3 0 0 0 1.8-1.8z"/><path d="M18.5 2.5l.7 1.9a1.5 1.5 0 0 0 .9.9l1.9.7-1.9.7a1.5 1.5 0 0 0-.9.9l-.7 1.9-.7-1.9a1.5 1.5 0 0 0-.9-.9L15 6l1.9-.7a1.5 1.5 0 0 0 .9-.9z"/></svg>'),
  ("tab-controller","טאב הגדרות · שלט","אייקון הטאב 'שלט' (בקר)","views/SettingsView.tsx → IconController",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6 12h4M8 10v4"/><circle cx="15.5" cy="11" r="1"/><circle cx="18" cy="13.5" r="1"/><path d="M17.5 5.5h-11A4.5 4.5 0 0 0 2 10v0l1.2 6a2.5 2.5 0 0 0 4.5 1l.8-1.5h7l.8 1.5a2.5 2.5 0 0 0 4.5-1L22 10a4.5 4.5 0 0 0-4.5-4.5z"/></svg>'),
  ("tab-updates","טאב הגדרות · עדכונים","אייקון הטאב 'עדכונים' (רענון)","views/SettingsView.tsx → IconUpdates",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12a9 9 0 1 1-3.1-6.8"/><path d="M21 4v5h-5"/></svg>'),
  ("tab-privacy","טאב הגדרות · פרטיות","אייקון הטאב 'פרטיות'","views/SettingsView.tsx → IconPrivacy",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>'),
  ("tab-paths","טאב הגדרות · נתיבים","אייקון הטאב 'נתיבים'","views/SettingsView.tsx → IconPaths",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 7a2 2 0 0 1 2-2h4l2 2h8a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></svg>'),
]

WINDOW = [
  ("win-minimize","מזעור החלון","כפתור המזעור בפס הכותרת המותאם","components/TitleBar.tsx → minimize",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><line x1="5" y1="12" x2="19" y2="12"/></svg>'),
  ("win-maximize","הגדלה / שחזור","כפתור ההגדלה/שחזור בפס הכותרת המותאם","components/TitleBar.tsx → maximize",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="5" y="5" width="14" height="14" rx="2"/></svg>'),
  ("win-close","סגירת החלון","כפתור הסגירה (X) בפס הכותרת המותאם","components/TitleBar.tsx → close",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><line x1="6" y1="6" x2="18" y2="18"/><line x1="18" y1="6" x2="6" y2="18"/></svg>'),
]

NOTIFY = [
  ("notify-none","פעמון התראות · אין חדש","מצב 'אין התראות חדשות' של הפעמון מעל האווטאר","components/NotificationsBell.tsx → none",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg>'),
  ("notify-has","פעמון התראות · יש חדש","מצב 'יש התראה חדשה' (פעמון עם נקודה)","components/NotificationsBell.tsx → hasNew",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/><circle cx="18" cy="6" r="3.2" fill="currentColor" stroke="none"/></svg>'),
  ("notify-muted","פעמון התראות · מושתק","מצב 'התראות מושתקות' (פעמון עם קו)","components/NotificationsBell.tsx → muted",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 8a6 6 0 0 0-9.9-5.7"/><path d="M6 8c0 7-3 9-3 9h13"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/><line x1="3" y1="3" x2="21" y2="21"/></svg>'),
  ("notify-header","חלון התראות · אייקון כותרת (ימין-למעלה)","האייקון בפינה הימנית-עליונה בתוך חלון ההתראות","components/NotificationsBell.tsx → header",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg>'),
  ("notify-mute-btn","חלון התראות · כפתור השתקה (שמאל-למעלה)","האייקון של כפתור 'השתק' בפינה השמאלית-עליונה","components/NotificationsBell.tsx → muteButton",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M11 5 6 9H2v6h4l5 4z"/><line x1="22" y1="9" x2="16" y2="15"/><line x1="16" y1="9" x2="22" y2="15"/></svg>'),
  ("notify-empty","חלון התראות · מצב ריק (מרכז)","האייקון במרכז החלון כשאין התראות","components/NotificationsBell.tsx → emptyState",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M22 12h-6l-2 3h-4l-2-3H2"/><path d="M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"/></svg>'),
]

# ── group: the large realistic controller silhouettes (Settings → שלט) ──
_CBODY = "M14 8H34c6 0 9 3 10.6 10.2C46 26 44 32 39 32c-4.6 0-7.1-5-8.7-10-.5-1.6-1.5-2-2.9-2h-6.8c-1.4 0-2.4.4-2.9 2-1.6 5-4.1 10-8.7 10-5 0-7-6-5.6-13.8C4 11 7 8 14 8Z"
def _csvg(inner):
    return ('<svg viewBox="0 0 48 34" fill="none" stroke="currentColor" stroke-width="2" '
            'stroke-linecap="round" stroke-linejoin="round"><path d="%s"/>%s</svg>' % (_CBODY, inner))
def _fdot(cx, cy, r=1.05): return '<circle cx="%s" cy="%s" r="%s" fill="currentColor" stroke="none"/>' % (cx, cy, r)
def _dots(cx, cy, r=2.6, d=0.78):
    return (_fdot(cx, cy-r, d) + _fdot(cx, cy+r, d) + _fdot(cx-r, cy, d) + _fdot(cx+r, cy, d))

# PlayStation-style: touchpad, D-pad, ✕◯□△, twin sticks.
_PS_INNER = ('<rect x="19" y="7.4" width="10" height="4.6" rx="1"/><path d="M12.5 11v5.2M9.9 13.6h5.2"/>'
   + _fdot(34.6,11)+_fdot(34.6,15.6)+_fdot(32.3,13.3)+_fdot(36.9,13.3)+_fdot(24,15)
   + '<circle cx="20.4" cy="19.6" r="2.1"/><circle cx="27.6" cy="19.6" r="2.1"/><path d="M22.5 19.6h3"/>')
# Xbox-style: offset sticks, ABXY diamond, guide ring, grips.
_XB_INNER = ('<circle cx="14" cy="13.8" r="2.6"/><circle cx="17" cy="20.4" r="2.7"/><path d="M17 18.3v4.2M14.9 20.4h4.2"/>'
   + '<circle cx="29" cy="19.4" r="2.7"/>'+_fdot(29,19.4,0.75)
   + _fdot(33.4,11.4)+_fdot(33.4,15.6)+_fdot(31.3,13.5)+_fdot(35.5,13.5)
   + '<path d="M8 24.6q-.7 1.5 0 3M40 24.6q.7 1.5 0 3"/>')
_GEN_INNER = ('<circle cx="15" cy="16.2" r="5"/>'+_dots(15,16.2)+'<circle cx="33" cy="16.2" r="5"/>'+_dots(33,16.2)
   + '<rect x="20.9" y="17.6" width="2.7" height="2.7" rx="0.5"/><rect x="24.4" y="17.6" width="2.7" height="2.7" rx="0.5"/>')
# DualSense (PS5): large touchpad framed by the light strip + ✕◯□△ + separate sticks.
_DS5_INNER = ('<rect x="17.5" y="6.6" width="13" height="6.2" rx="1.6"/><path d="M16 7.8v3.8M32 7.8v3.8"/>'
   + '<path d="M12.5 12v5M10 14.5h5"/>'
   + '<path d="M32.8 11.4 34 9 35.2 11.4 Z"/><circle cx="37.2" cy="13.3" r="1.3"/>'
   + '<path d="M32.9 15.4 35.1 17.6M35.1 15.4 32.9 17.6"/><rect x="29.6" y="12.1" width="2.4" height="2.4" rx="0.3"/>'
   + '<circle cx="20" cy="19.9" r="2.2"/><circle cx="28" cy="19.9" r="2.2"/>')
# The 3 pad slots now render the USER'S OWN PNG artwork (build_assets/controllers,
# the same files embedded in frontend/src/lib/controllerIcons.ts). They are solid
# black, so we draw them as a CSS MASK filled with currentColor - otherwise they'd
# be black-on-black in the dark preview, exactly like in the launcher.
import base64
def _img_mask(name, w=30, h=22):
    uri = 'data:image/png;base64,' + base64.b64encode(
        open('build_assets/controllers/%s.png' % name, 'rb').read()).decode()
    return ('<span style="display:inline-block;width:%dpx;height:%dpx;background-color:currentColor;'
            '-webkit-mask-image:url(%s);mask-image:url(%s);'
            '-webkit-mask-repeat:no-repeat;mask-repeat:no-repeat;'
            '-webkit-mask-size:contain;mask-size:contain;'
            '-webkit-mask-position:center;mask-position:center"></span>' % (w, h, uri, uri))

CONTROLLERS = [
  ("pad-ps5","שלט PlayStation 5 (DualSense)","האייקון הגדול של שלט PS5 ב'שלט' (תמונת המשתמש)","components/ControllerSettings.tsx → DualSense5Icon", _img_mask('ps5')),
  ("pad-ps4","שלט PlayStation 4 (DualShock 4)","האייקון הגדול של שלט PS4 ב'שלט' (תמונת המשתמש)","components/ControllerSettings.tsx → PlayStationIcon", _img_mask('ps4')),
  ("pad-xbox","שלט Xbox","האייקון הגדול של שלט Xbox ב'שלט' (תמונת המשתמש)","components/ControllerSettings.tsx → XboxIcon", _img_mask('xbox')),
  ("pad-generic","שלט כללי","האייקון של שלט כללי ב'שלט' (בחירת המשתמש)","components/ControllerSettings.tsx → GamepadIcon", '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4"><circle cx="12" cy="4.6" r="3.4"/><path d="M10.6 3.2 12 5.9 13.4 3.2"/><circle cx="19.4" cy="12" r="3.4"/><circle cx="19.4" cy="12" r="1.2"/><circle cx="12" cy="19.4" r="3.4"/><path d="M10.7 18.1 13.3 20.7M13.3 18.1 10.7 20.7"/><circle cx="4.6" cy="12" r="3.4"/><rect x="3.2" y="10.6" width="2.8" height="2.8" rx="0.4"/></svg>'),
]

# ── CURATED GAMING/CONTROLLER LIBRARY (offline SVG - no CDN, currentColor) ──
# A LARGE set of recognizable brand controllers + input parts. Drawn on a WIDE
# 0 0 36 24 canvas (controller aspect) so they render big + detailed WITHOUT
# distortion (the library preserves aspect). They join the ~51 font gaming glyphs
# in the "בקרים ומשחק" category. A shared smooth pad body; per-brand internals.
# Pad body: grips at x~7 & x~29, spans y~7..21.
_PADBODY = ("M27 7H9Q5 7 3.4 11L2 16.2Q1.4 19.2 4 20.3Q6.6 21.4 8.2 19L10 16.4Q10.6 15.6 11.6 15.6"
            "H24.4Q25.4 15.6 26 16.4L27.8 19Q29.4 21.4 32 20.3Q34.6 19.2 33.2 16.2L31.8 11"
            "Q30.2 7 26.2 7Z")
def _pad(inner, sw=1.5):
    return ('<svg viewBox="0 0 36 24" fill="none" stroke="currentColor" stroke-width="%s" '
            'stroke-linecap="round" stroke-linejoin="round"><path d="%s"/>%s</svg>' % (sw, _PADBODY, inner))
def _dot(cx, cy, r=1.05): return '<circle cx="%s" cy="%s" r="%s" fill="currentColor" stroke="none"/>' % (cx, cy, r)
def _dpad(cx, cy, a=2.4):   # small + cross at (cx,cy)
    return '<path d="M%s %sv%s M%s %sh%s"/>' % (cx, cy-a, 2*a, cx-a, cy, 2*a)
def _diamond(cx, cy, r=2.2, d=0.95):  # 4 face-button dots in a diamond
    return _dot(cx, cy-r, d)+_dot(cx, cy+r, d)+_dot(cx-r, cy, d)+_dot(cx+r, cy, d)
def _psface(cx, cy, r=2.3, s=0.8):    # ✕ ◯ □ △ cluster (PlayStation face buttons)
    tri = '<path d="M%.1f %.1f %.1f %.1f %.1f %.1f Z"/>' % (cx-s, cy-r+s, cx, cy-r-s, cx+s, cy-r+s)  # △ top
    cir = '<circle cx="%.1f" cy="%.1f" r="%.1f"/>' % (cx+r, cy, s)                                    # ◯ right
    xx  = '<path d="M%.1f %.1f %.1f %.1f M%.1f %.1f %.1f %.1f"/>' % (cx-s, cy+r-s, cx+s, cy+r+s, cx+s, cy+r-s, cx-s, cy+r+s)  # ✕ bottom
    sq  = '<rect x="%.1f" y="%.1f" width="%.1f" height="%.1f"/>' % (cx-r-s, cy-s, 2*s, 2*s)           # □ left
    return tri+cir+xx+sq
GAMELIB = [
  # the launcher's OWN "משחקים" nav controller (Lucide gamepad-2), added so the
  # user can pick the exact same games icon for another area.
  ("g-gamepad-nav","בקר משחק (תפריט המשחקים)",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="6" y1="11" x2="10" y2="11"/><line x1="8" y1="9" x2="8" y2="13"/><line x1="15" y1="12" x2="15.01" y2="12"/><line x1="18" y1="10" x2="18.01" y2="10"/><path d="M17.32 5H6.68a4 4 0 0 0-3.978 3.59c-.006.052-.01.101-.017.152C2.604 9.416 2 14.456 2 16a3 3 0 0 0 3 3c1 0 1.5-.5 2-1l1.414-1.414A2 2 0 0 1 9.828 16h4.344a2 2 0 0 1 1.414.586L17 18c.5.5 1 1 2 1a3 3 0 0 0 3-3c0-1.544-.604-6.584-.685-7.258A4 4 0 0 0 17.32 5z"/></svg>'),
  # generic gamepad - solid silhouette
  ("g-gamepad-solid","בקר משחק (מלא)",
   '<svg viewBox="0 0 36 24" fill="currentColor"><path d="%s"/></svg>' % _PADBODY),
  # generic gamepad - D-pad + 4 buttons + twin sticks
  ("g-gamepad","בקר משחק",
   _pad(_dpad(11,12.5)+_diamond(25,12.5)+'<circle cx="15.2" cy="16.6" r="1.7"/><circle cx="20.8" cy="16.6" r="1.7"/>')),
  # Xbox (offset sticks + guide ring + ABXY diamond)
  ("g-xbox","שלט Xbox",
   _pad('<circle cx="11" cy="11.6" r="2"/><circle cx="17.4" cy="16.4" r="2"/>'+_dpad(12.6,16.4,1.9)
        +'<circle cx="18" cy="10" r="1.6"/>'+_dot(18,10,0.7)+_diamond(24.6,12.6,2,0.9))),
  # Xbox Series (share button under the guide)
  ("g-xbox-series","שלט Xbox Series",
   _pad('<circle cx="11" cy="11.4" r="2"/><circle cx="17.6" cy="16.2" r="2"/>'+_dpad(12.8,16.2,1.9)
        +'<circle cx="18" cy="9.6" r="1.5"/>'+_dot(18,9.6,0.65)+'<rect x="17.1" y="12.4" width="1.8" height="1.4" rx="0.5"/>'
        +_diamond(24.8,12.4,2,0.9))),
  # PlayStation 4 (DualShock 4) - front LIGHT BAR strip + small touchpad + ✕◯□△
  ("g-ps4","שלט PlayStation 4 (DualShock 4)",
   _pad('<path d="M14.5 7.3h7"/>'                              # light-bar strip on the top front
        +'<rect x="15" y="8.7" width="6" height="2.9" rx="0.7"/>'   # small touchpad
        +_dpad(11,12)                                          # D-pad left
        +_psface(24.6,12,2.3,0.8)                              # ✕◯□△ right
        +'<circle cx="14.6" cy="16.8" r="1.8"/><circle cx="21.4" cy="16.8" r="1.8"/>')),  # twin sticks
  # PlayStation 5 (DualSense) - LARGER touchpad framed by the light strip + ✕◯□△
  ("g-ps5","שלט PlayStation 5 (DualSense)",
   _pad('<rect x="14.4" y="8.2" width="7.2" height="3.6" rx="1"/>'   # larger touchpad
        +'<path d="M13.5 8.7v2.6M22.5 8.7v2.6"/>'              # light-strip framing the touchpad
        +_dpad(10.6,11.8,2.1)                                  # D-pad left
        +_psface(25.4,11.8,2.2,0.8)                            # ✕◯□△ right
        +'<circle cx="15" cy="16.9" r="1.8"/><circle cx="21" cy="16.9" r="1.8"/>')),  # twin sticks
  # Switch Pro (offset sticks + / -  + D-pad + ABXY)
  ("g-switch-pro","נינטנדו סוויץ' Pro",
   _pad('<circle cx="10.8" cy="11.4" r="1.9"/><circle cx="17.2" cy="16.2" r="1.9"/>'+_dpad(12.6,16.2,1.8)
        +'<path d="M14.4 9.6h1.4M23.4 9.6h1.4M24.1 8.9v1.4"/>'+_diamond(24.6,12.6,2,0.9))),
  # Nintendo Switch Joy-Con pair
  ("g-joycon","נינטנדו Joy-Con (זוג)",
   '<svg viewBox="0 0 36 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="5" y="4" width="10" height="16" rx="5"/><rect x="21" y="4" width="10" height="16" rx="5"/><circle cx="10" cy="8.5" r="1.5"/>'+_dpad(10,14.5,1.7)+_diamond(26,10.5,2,0.95)+'<circle cx="26" cy="15" r="1.4"/></svg>'),
  # Steam Deck / handheld
  ("g-steamdeck","קונסולת יד (Steam Deck)",
   '<svg viewBox="0 0 36 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"><rect x="2" y="4.5" width="32" height="15" rx="4"/><rect x="11" y="7" width="14" height="10" rx="1.5"/><circle cx="6.5" cy="8.5" r="1.6"/>'+_dpad(6.5,14,1.8)+_diamond(29.5,9,2,0.9)+'<circle cx="29.5" cy="14" r="1.5"/></svg>'),
  # Retro pad (rectangular - NES/SNES style)
  ("g-retro","שלט רטרו (NES/SNES)",
   '<svg viewBox="0 0 36 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"><rect x="4" y="6" width="28" height="12" rx="2"/>'+_dpad(11,12,2.4)+'<circle cx="22" cy="12.5" r="1.7"/><circle cx="26.5" cy="12.5" r="1.7"/><path d="M15.5 12.5h2.5"/></svg>'),
  # Arcade stick (fightstick)
  ("g-arcade","ג'ויסטיק ארקייד",
   '<svg viewBox="0 0 36 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="12" width="30" height="9" rx="2.5"/><circle cx="11" cy="6" r="3" fill="currentColor" stroke="none"/><path d="M11 9v3"/><circle cx="21" cy="16.5" r="1.3"/><circle cx="25" cy="16.5" r="1.3"/><circle cx="29" cy="16.5" r="1.3"/><circle cx="23" cy="19.5" r="1.3"/><circle cx="27" cy="19.5" r="1.3"/></svg>'),
  # Racing wheel
  ("g-wheel","הגה מירוצים",
   '<svg viewBox="0 0 36 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"><circle cx="18" cy="12" r="9.5"/><circle cx="18" cy="12" r="3.2"/><path d="M18 15.2V21.5M15 13.8 9.8 17.5M21 13.8 26.2 17.5"/></svg>'),
  # Flight / HOTAS stick
  ("g-flight","ג'ויסטיק טיסה (HOTAS)",
   '<svg viewBox="0 0 36 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M18 4c-2.2 0-2.6 2-2.6 4.5S16 13 18 13s2.6-1.8 2.6-4.5S20.2 4 18 4z"/><path d="M18 13v4"/><path d="M12 21c1-3 4-4 6-4s5 1 6 4z"/><path d="M15.6 8h4.8"/></svg>'),
  # VR controller (Quest Touch style)
  ("g-vr","בקר VR (Touch)",
   '<svg viewBox="0 0 36 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M14 3h8a3 3 0 0 1 3 3v6a4 4 0 0 1-8 0V8a1 1 0 0 0-2 0v3"/><ellipse cx="19" cy="18.5" rx="7" ry="2.5"/><circle cx="18" cy="6.5" r="1.1" fill="currentColor" stroke="none"/></svg>'),
  # Mobile gamepad clip
  ("g-mobile","בקר לנייד (קליפ)",
   '<svg viewBox="0 0 36 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"><rect x="12" y="3" width="12" height="18" rx="2"/><path d="M12 8H8a3 3 0 0 0-3 3v3a3 3 0 0 0 3 3h4M24 8h4a3 3 0 0 1 3 3v3a3 3 0 0 1-3 3h-4"/>'+_dpad(8.5,12.5,1.6)+_diamond(27.5,12.5,1.8,0.85)+'</svg>'),
  # D-pad
  ("g-dpad","כיוונים (D-pad)",
   '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M9.4 2h5.2a1 1 0 0 1 1 1v5.4H21a1 1 0 0 1 1 1v5.2a1 1 0 0 1-1 1h-5.4V21a1 1 0 0 1-1 1H9.4a1 1 0 0 1-1-1v-5.4H3a1 1 0 0 1-1-1V9.4a1 1 0 0 1 1-1h5.4V3a1 1 0 0 1 1-1z"/></svg>'),
  # Analog thumbstick
  ("g-analog","ג'ויסטיק אנלוגי",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"><circle cx="12" cy="9.5" r="6.2"/><circle cx="12" cy="9.5" r="2.5" fill="currentColor" stroke="none"/><path d="M7.6 15.2 6 21M16.4 15.2 18 21"/></svg>'),
  # PlayStation face buttons ✕ ◯ □ △
  ("g-face-ps","כפתורי פעולה ✕◯□△",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4"><circle cx="12" cy="4.6" r="3.4"/><path d="M10.6 3.2 12 5.9 13.4 3.2"/><circle cx="19.4" cy="12" r="3.4"/><circle cx="19.4" cy="12" r="1.2"/><circle cx="12" cy="19.4" r="3.4"/><path d="M10.7 18.1 13.3 20.7M13.3 18.1 10.7 20.7"/><circle cx="4.6" cy="12" r="3.4"/><rect x="3.2" y="10.6" width="2.8" height="2.8" rx="0.4"/></svg>'),
  # Shoulder bumper (L1/R1)
  ("g-bumper","כתף (L1/R1)",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"><path d="M3 14.5V13Q3 8 8 6.5Q10.5 5.8 12 5.8Q13.5 5.8 16 6.5Q21 8 21 13v1.5"/><rect x="2.5" y="14.5" width="19" height="4.5" rx="2"/><path d="M9 16.7h6" stroke-linecap="round"/></svg>'),
  # Gaming headset
  ("g-headset","אוזניות גיימינג",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M4 14v-2a8 8 0 0 1 16 0v2"/><rect x="2.5" y="13.5" width="4" height="7" rx="1.8"/><rect x="17.5" y="13.5" width="4" height="7" rx="1.8"/><path d="M20 20.5a3 3 0 0 1-3 3h-3"/></svg>'),
]

# ── CURATED SECURITY / LOCK / LOCK-AND-KEY LIBRARY (offline SVG, currentColor) ──
# A LARGE hand-authored set of padlocks, keys, lock+key combos, shields and
# keyholes - "many for choice" - joining the Flaticon lock/key font glyphs in the
# "אבטחה ופרטיות" category. viewBox 0 0 24 24, stroke = currentColor.
def _sec(inner, sw=1.9):
    return ('<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="%s" '
            'stroke-linecap="round" stroke-linejoin="round">%s</svg>' % (sw, inner))
_SHIELD = '<path d="M12 2.5 4.5 5.5V11q0 6 7.5 10 7.5-4 7.5-10V5.5z"/>'
SECURITYLIB = [
  # --- HD "reference" style (padlock_4428615.png the user shared): thick monoline,
  #     double-line shackle, keyhole (circle + tapered slot), key with a round grip
  #     + a hole and toothed bow. ---
  ("s-lockkey-hd","מנעול ומפתח מפורט (כמו בתמונה)",
   '<svg viewBox="0 0 30 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><rect x="1.6" y="10" width="13" height="12.4" rx="2.4"/><path d="M4 10V7.7a4.1 4.1 0 0 1 8.2 0V10"/><path d="M6.1 10V7.7a2 2 0 0 1 4 0V10"/><circle cx="8.1" cy="14.9" r="2"/><path d="M7 16.5 6.6 19.9a1.5 1.5 0 0 0 3 0L9.2 16.5"/><path d="M21.7 14.2V4.8"/><path d="M21.7 4.8h2.2l-1.2 1.5 1.2 1.5h-2.2"/><circle cx="21.7" cy="17.9" r="3.7"/><circle cx="21.7" cy="17.9" r="1.1"/></svg>'),
  ("s-lock-key-in-hd","מפתח בתוך מנעול (עבה)",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="8.5" width="16" height="11" rx="2.4"/><path d="M7 8.5V6a5 5 0 0 1 10 0v2.5"/><path d="M9.5 8.5V6a2.5 2.5 0 0 1 5 0v2.5"/><circle cx="12" cy="13" r="1.9"/><path d="M12 14.9V22"/><path d="M12 19.5h2.2M12 21.7h1.8"/></svg>'),
  ("s-padlock-hd","מנעול עם חור מנעול (עבה)",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="3.5" y="10" width="17" height="12" rx="2.6"/><path d="M6.5 10V6.8a5.5 5.5 0 0 1 11 0V10"/><path d="M9 10V6.8a3 3 0 0 1 6 0V10"/><circle cx="12" cy="14.8" r="2.2"/><path d="M10.6 16.6 10.1 20.4a1.9 1.9 0 0 0 3.8 0l-.5-3.8"/></svg>'),
  ("s-padlock-open-hd","מנעול פתוח (עבה)",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="3.5" y="10" width="17" height="12" rx="2.6"/><path d="M6.5 10V6.8a5.5 5.5 0 0 1 10.4-2.3"/><path d="M9 10V6.8a3 3 0 0 1 5.4-1.4"/><circle cx="12" cy="14.8" r="2.2"/><path d="M10.6 16.6 10.1 20.4a1.9 1.9 0 0 0 3.8 0l-.5-3.8"/></svg>'),
  ("s-key-hd","מפתח עם ראש עגול (עבה)",
   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 14.6V3.6"/><path d="M12 3.6h2.6l-1.4 1.7 1.4 1.7H12"/><circle cx="12" cy="18.2" r="4"/><circle cx="12" cy="18.2" r="1.2"/></svg>'),
  # --- padlocks ---
  ("s-lock","מנעול סגור", _sec('<rect x="5" y="10.5" width="14" height="10" rx="2.2"/><path d="M8 10.5V7a4 4 0 0 1 8 0v3.5"/>', 2)),
  ("s-lock-open","מנעול פתוח", _sec('<rect x="5" y="10.5" width="14" height="10" rx="2.2"/><path d="M8 10.5V7a4 4 0 0 1 7.6-1.8"/>', 2)),
  ("s-lock-keyhole","מנעול עם חור מנעול", _sec('<rect x="5" y="10.5" width="14" height="10" rx="2.2"/><path d="M8 10.5V7a4 4 0 0 1 8 0v3.5"/><circle cx="12" cy="14.4" r="1.4"/><path d="M12 15.8v2.1"/>')),
  ("s-lock-check","מנעול מאובטח (וי)", _sec('<rect x="5" y="10.5" width="14" height="10" rx="2.2"/><path d="M8 10.5V7a4 4 0 0 1 8 0v3.5"/><path d="m9.6 15.4 1.7 1.7 3.1-3.3"/>')),
  ("s-lock-dial","מנעול חוגה", _sec('<rect x="4.5" y="10.5" width="15" height="10.3" rx="2.4"/><path d="M7.5 10.5V7a4.5 4.5 0 0 1 9 0v3.5"/><circle cx="12" cy="15.5" r="2.3"/><path d="M12 13.2v-1M12 15.5l1.5-.7"/>')),
  ("s-unlock-keyhole","מנעול פתוח + חור", _sec('<rect x="5" y="10.5" width="14" height="10" rx="2.2"/><path d="M8 10.5V7a4 4 0 0 1 7.6-1.8"/><circle cx="12" cy="15.4" r="1.3"/>')),
  # --- keys ---
  ("s-key","מפתח", _sec('<circle cx="7.6" cy="7.6" r="4"/><path d="M10.4 10.4 19 19"/><path d="M16 19l2-2M18.4 16.6l1.6-1.6"/>', 2)),
  ("s-key-h","מפתח (אופקי)", _sec('<circle cx="6.5" cy="12" r="3.6"/><circle cx="6.5" cy="12" r="1"/><path d="M10.1 12H21"/><path d="M17 12v3M20 12v2.6"/>', 2)),
  ("s-keys","צרור מפתחות", _sec('<circle cx="12" cy="6" r="3"/><path d="M10.1 8.5 7.6 20M13.9 8.5 16.4 20"/><path d="M7 16h2M15.4 16h2"/>')),
  ("s-keyhole","חור מנעול עגול", _sec('<circle cx="12" cy="12" r="9"/><circle cx="12" cy="10" r="2.2"/><path d="M10.4 12.4 9.4 16.6h5.2l-1-4.2"/>')),
  # --- lock + key beside it (the user's specific ask) ---
  ("s-lock-key","מנעול ומפתח לידו", _sec('<rect x="2.5" y="10.5" width="10" height="9" rx="2"/><path d="M4.8 10.5V8a2.7 2.7 0 0 1 5.4 0v2.5"/><circle cx="18.6" cy="7.4" r="2.8"/><path d="M16.6 9.4 10.6 15.4"/><path d="M12.6 13.4l1.5 1.5M14.6 11.4l1.5 1.5"/>', 1.7)),
  ("s-lock-key-in","מפתח בתוך המנעול", _sec('<rect x="4" y="10.5" width="14" height="10" rx="2.2"/><path d="M7 10.5V7a4 4 0 0 1 8 0v3.5"/><circle cx="11" cy="14.4" r="1.4"/><path d="M11 15.8V21M11 18.2h2.6"/>', 1.8)),
  ("s-key-lock-pair","מפתח + מנעול (זוג)", _sec('<circle cx="6" cy="6" r="3"/><path d="M8.1 8.1 12 12"/><path d="M10 12l1.6-1.6M12 14l1.6-1.6"/><rect x="13.5" y="13.5" width="8" height="6.5" rx="1.6"/><path d="M15.2 13.5v-1.3a2.3 2.3 0 0 1 4.6 0v1.3"/>', 1.7)),
  # --- shields ---
  ("s-shield","מגן", _sec(_SHIELD, 2)),
  ("s-shield-check","מגן מאומת (וי)", _sec(_SHIELD + '<path d="m8.8 11.8 2.2 2.2 4.2-4.4"/>', 2)),
  ("s-shield-lock","מגן עם מנעול", _sec(_SHIELD + '<rect x="9.3" y="11.3" width="5.4" height="4.4" rx="1"/><path d="M10.3 11.3v-1a1.7 1.7 0 0 1 3.4 0v1"/>', 1.8)),
  ("s-shield-keyhole","מגן עם חור מנעול", _sec(_SHIELD + '<circle cx="12" cy="10.8" r="1.5"/><path d="M12 12.3v3.4"/>')),
  ("s-shield-key","מגן עם מפתח", _sec(_SHIELD + '<circle cx="12" cy="10.4" r="1.8"/><path d="M12 12.2v4.4M12 14.4h1.8"/>', 1.8)),
  # --- verification / privacy ---
  ("s-verified","תג מאובטח", _sec('<path d="M12 2.5l2.4 1.7 2.9-.2 1 2.8 2.4 1.6-.9 2.8.9 2.8-2.4 1.6-1 2.8-2.9-.2L12 21.5l-2.4-1.7-2.9.2-1-2.8-2.4-1.6.9-2.8-.9-2.8 2.4-1.6 1-2.8 2.9.2z"/><path d="m9 12 2 2 4-4"/>', 1.8)),
  ("s-fingerprint","טביעת אצבע", _sec('<path d="M6 11a6 6 0 0 1 12 0v1.5"/><path d="M8.5 11a3.5 3.5 0 0 1 7 0v2a9 9 0 0 0 .6 3"/><path d="M12 11v3a10 10 0 0 0 1.2 5"/><path d="M9.2 16.5A9 9 0 0 0 9.8 19"/><path d="M7 13.5a6 6 0 0 0 .3 4"/>', 1.7)),
  ("s-password","סיסמה (כוכביות)", _sec('<rect x="3.5" y="8.5" width="17" height="8" rx="2.2"/><path d="M8 12.5v.01M12 12.5v.01M16 12.5v.01"/>', 1.9)),
]

def js_target(group, id_, name, purpose, location, svg):
    def esc(s): return s.replace('\\','\\\\').replace('`','\\`').replace('$','\\$')
    return ('{group:"%s",id:%s,name:%s,purpose:%s,location:%s,svg:`%s`}'
            % (group, json.dumps(id_, ensure_ascii=False), json.dumps(name, ensure_ascii=False),
               json.dumps(purpose, ensure_ascii=False), json.dumps(location, ensure_ascii=False), esc(svg)))

targets = []
for id_, name, purpose, loc, svg in EXISTING:
    targets.append(js_target("existing", id_, name, purpose, loc, cur_svg(id_, svg)))
for t in WINDOW:      targets.append(js_target("window", *t))
for t in NOTIFY:      targets.append(js_target("notify", *t))
for t in CONTROLLERS: targets.append(js_target("controllers", *t))
for s in optional:
    loc = s.get('file','').replace('frontend/src/','')
    ctx = s.get('context','') + '  ·  [' + s.get('kind','') + ']'
    tid = 'opt-'+s['id']
    targets.append(js_target("optional", tid, s['labelHe'], ctx, loc, cur_svg(tid, '')))
for a in APP_ICONS:
    ctx = (a.get('purpose','') + '  ·  [' + a.get('kind','') + ']').strip()
    targets.append(js_target("app", a['id'], a['name'], ctx, a.get('location',''),
                             cur_svg(a['id'], a['svg'])))

TARGETS_JS = '[\n' + ',\n'.join(targets) + '\n]'

# ── CATEGORIES: assign every UICONS name to the FIRST matching bucket ──
CATS = [
  ("gaming",   "בקרים ומשחק", ["gamepad","joystick","console-controller","dice","chess","puzzle","trophy","medal","spade","card-spade","leaderboard","vr-","game-board","strategy","arcade"]),
  ("arrows",   "חצים וניווט", ["arrow","chevron","caret","angle","corner","direction","navigation","refresh","rotate","redo","undo","exit","enter","expand","compress","move","exchange","shuffle","sort","swap","turn"]),
  ("files",    "קבצים ותיקיות", ["file","folder","document","page","copy","paste","clipboard","archive","zip","disk","floppy","cloud","backup","import","export","attachment"]),
  ("transfer", "הורדה והעלאה", ["download","upload","transfer","sync"]),
  ("users",    "משתמשים", ["user","person","people","member","account","profile","avatar","id-badge","portrait","head","contact","team","group"]),
  ("comm",     "תקשורת והתראות", ["comment","message","chat","envelope","mail","bell","notification","phone","call-","at-","inbox","send","paper-plane","speech","megaphone","broadcast","rss","share"]),
  ("media",    "מדיה ובקרה", ["play","pause","stop","forward","rewind","volume","music","video","film","camera","image","photo","picture","microphone","headphones","speaker","record","podcast","playlist","album","clapperboard","gallery"]),
  ("commerce", "מסחר וכסף", ["credit-card","money","wallet","cart","shopping","bag","tag","price","coin","dollar","euro","pound","bank","receipt","invoice","payment","gift","sale","discount","percent","checkout","cash","budget","donate"]),
  ("devices",  "מכשירים וטכנולוגיה", ["mobile","laptop","desktop","computer","tablet","keyboard","mouse","tv","monitor","printer","server","database","chip","processor","cpu","plug","battery","wifi","bluetooth","usb","sd-card","hard-drive","router","microchip","circuit","robot","screen","cable"]),
  ("editing",  "עריכה וכלים", ["pencil","edit","brush","paint","palette","eraser","crop","scissors","ruler","magic-wand","wrench","screwdriver","hammer","tool","sliders","filter","adjust","layer","vector","bezier","pen-","marker","highlighter","format","bold","italic","underline","text","font"]),
  ("time",     "זמן ולוח שנה", ["clock","time","calendar","timer","stopwatch","hourglass","alarm","schedule","history","date","watch","duration","pending"]),
  ("location", "מיקום ומפות", ["map","marker","location","compass","globe","world","earth","route","road","directions","place","gps","navigation-"]),
  ("nature",   "טבע ומזג אוויר", ["sun","moon","cloud","rain","snow","storm","wind","weather","temperature","thermometer","leaf","tree","flower","plant","fire","water","drop","mountain","sparkles","rainbow","umbrella","meteor","star-"]),
  ("faces",    "פרצופים ורגשות", ["smile","sad","happy","angry","face","emoji","mood","laugh","wink","grin","expressionless","kiss","tongue","cry","surprise","confused"]),
  ("food",     "אוכל ומשקאות", ["coffee","food","pizza","burger","cake","drink","cup","mug","apple","fork","knife","restaurant","cook","egg","bread","fruit","meat","fish","ice-cream","beer","wine","bottle","salad","soup"]),
  ("transport","תחבורה", ["car","truck","bus","train","plane","ship","boat","bicycle","motorcycle","rocket","taxi","subway","traffic","scooter","helicopter","tram","vehicle","tire","fuel","gas-"]),
  ("health",   "בריאות ורפואה", ["pulse","medical","hospital","pill","medicine","doctor","health","first-aid","dna","virus","mask","syringe","stethoscope","bandage","tooth","brain","bone","wheelchair"]),
  ("sports",   "ספורט וכושר", ["ball","football","basketball","soccer","tennis","golf","dumbbell","gym","fitness","running","swim","whistle","boxing","skate","yoga","hockey","cricket","baseball","bowling","dart"]),
  ("security", "אבטחה ופרטיות", ["lock","unlock","key","shield","fingerprint","face-id","scan","secure","protect","password","encrypt","privacy","verified","guard"]),
  ("weather2", "מסמכים וגרפים", ["chart","graph","stats","analytics","dashboard","presentation","diagram","report","poll","survey","list","table","grid","kanban"]),
  ("shapes",   "צורות וסמלים", ["circle","square","triangle","hexagon","diamond","shape","heart","seal","stamp","symbol","badge","star","rhombus","octagon","pentagon","cross","plus","minus"]),
  ("ui",       "ממשק ופעולות", ["check","cross","times","close","menu","dots","ellipsis","ban","block","eye","search","zoom","magnifying","trash","delete","remove","add","bookmark","flag","pin","thumbtack","toggle","power","settings","gear","cog","apps","home","info","question","exclamation","help","link","attachment","cursor","hand","touch","grid","layout"]),
]
def categorize(name):
    n = name  # names are already stripped 'fi-rr-' prefix in uicons_map
    for key, _label, kws in CATS:
        for kw in kws:
            if kw in n:
                return key
    return "other"

CAT_LABELS = {k: lbl for k, lbl, _ in CATS}
CAT_LABELS["other"] = "אחר"
CAT_LABELS["gaming"] = "בקרים ומשחק"

# library entries: font icons {n:name,k:cat}  +  curated gaming svgs {s:id,l:label,v:svg,k:'gaming'}
lib_font = ['{n:"%s",k:"%s"}' % (n, categorize(n)) for n, _c in UICONS]
def esc_bt(s): return s.replace('\\','\\\\').replace('`','\\`').replace('$','\\$')
_CURATED = ([(sid, lbl, svg, "gaming") for sid, lbl, svg in GAMELIB]
          + [(sid, lbl, svg, "security") for sid, lbl, svg in SECURITYLIB])
lib_svg = ['{s:%s,l:%s,v:`%s`,k:"%s"}' % (json.dumps(sid), json.dumps(lbl, ensure_ascii=False), esc_bt(svg), cat)
           for sid, lbl, svg, cat in _CURATED]
LIB_JS = '[' + ',\n'.join(lib_svg + lib_font) + ']'

# ordered category chips (put gaming first so the controller set is easy to find)
CAT_ORDER = ["all","gaming","arrows","ui","files","transfer","users","comm","media","commerce",
             "devices","editing","time","location","nature","faces","food","transport","health",
             "sports","security","weather2","shapes","other"]
CAT_LABELS["all"] = "הכול"
CATS_JS = '[' + ','.join('{k:"%s",l:%s}' % (k, json.dumps(CAT_LABELS.get(k, k), ensure_ascii=False)) for k in CAT_ORDER) + ']'

code_map_js = '{' + ','.join('"%s":"%s"' % (n, c) for n, c in UICONS) + '}'

HTML = r'''<!doctype html>
<html lang="he" dir="rtl">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>מנהל האייקונים · מנהל התרגומים</title>
<link rel="stylesheet" href="https://cdn-uicons.flaticon.com/2.6.0/uicons-regular-rounded/css/uicons-regular-rounded.css" />
<style>
  :root{--bg:#05060f;--panel:#0c0e1c;--panel2:#11142a;--line:rgba(255,255,255,.08);--ink:#e9ecff;--muted:#9aa3c7;--cyan:#00ffe0;--yellow:#fff700;--violet:#a78bfa;--green:#22c55e;--danger:#ff5e7a}
  *{box-sizing:border-box}
  html,body{margin:0;height:100%}
  body{background:radial-gradient(60% 55% at 100% 0%,rgba(0,255,224,.06),transparent 60%),radial-gradient(50% 50% at 0% 100%,rgba(167,139,250,.06),transparent 60%),var(--bg);color:var(--ink);font-family:"Segoe UI",system-ui,Arial,sans-serif;display:flex;flex-direction:column}
  header{position:sticky;top:0;z-index:30;backdrop-filter:blur(10px);background:linear-gradient(180deg,rgba(5,6,15,.95),rgba(5,6,15,.72));border-bottom:1px solid var(--line);padding:13px 22px;display:flex;align-items:center;gap:16px;flex-wrap:wrap}
  .brand{display:flex;align-items:center;gap:12px;flex:1;min-width:230px}
  .logo{width:40px;height:40px;border-radius:11px;display:grid;place-items:center;background:radial-gradient(circle at 30% 30%,#1a0d40,#0a0a14);border:1.5px solid var(--cyan);box-shadow:0 0 22px rgba(0,255,224,.35);font-size:19px}
  h1{font-size:17px;margin:0;font-weight:800}
  .sub{color:var(--muted);font-size:12px;margin-top:2px}
  button{font-family:inherit;cursor:pointer;border:none;border-radius:11px;font-weight:700;transition:.15s}
  .btn-primary{background:linear-gradient(120deg,var(--cyan),#3ad0ff);color:#04121a;padding:9px 15px;font-size:14px;box-shadow:0 10px 26px -12px rgba(0,255,224,.7)}
  .btn-primary:hover{filter:brightness(1.08)}
  .btn-ghost{background:rgba(255,255,255,.05);color:var(--ink);border:1px solid var(--line);padding:8px 13px;font-size:13px}
  .btn-ghost:hover{background:rgba(255,255,255,.09)}
  .pill{background:rgba(0,255,224,.12);color:var(--cyan);border:1px solid rgba(0,255,224,.3);border-radius:999px;padding:3px 10px;font-size:12px;font-weight:800}
  .note{background:rgba(255,247,0,.06);border:1px solid rgba(255,247,0,.22);color:#f4ecc0;border-radius:12px;padding:10px 14px;font-size:12.5px;line-height:1.7;margin:12px 22px 0}
  .note b{color:var(--yellow)} .note code{background:rgba(255,255,255,.08);padding:1px 6px;border-radius:6px;direction:ltr;display:inline-block}
  .wrap{flex:1;display:grid;grid-template-columns:1fr 400px;gap:16px;padding:14px 22px;min-height:0}
  @media(max-width:960px){.wrap{grid-template-columns:1fr}}
  .libcol{display:flex;flex-direction:column;min-height:0;background:var(--panel);border:1px solid var(--line);border-radius:16px;overflow:hidden}
  .libhead{padding:12px 14px;border-bottom:1px solid var(--line);display:flex;gap:10px;align-items:center;flex-wrap:wrap}
  .libhead h2{font-size:14px;margin:0;font-weight:800}
  .search{flex:1;min-width:150px;background:var(--panel2);border:1px solid var(--line);color:var(--ink);border-radius:10px;padding:9px 12px;font-size:14px;font-family:inherit;direction:rtl}
  .search::placeholder{color:#6b7398}
  .cats{display:flex;gap:6px;overflow-x:auto;padding:9px 12px;border-bottom:1px solid var(--line);scrollbar-width:thin}
  .cat{white-space:nowrap;background:var(--panel2);border:1px solid var(--line);color:var(--muted);border-radius:999px;padding:5px 12px;font-size:12px;font-weight:700;flex:0 0 auto}
  .cat.on{background:rgba(0,255,224,.14);border-color:rgba(0,255,224,.4);color:var(--cyan)}
  .cat:hover{color:var(--ink)}
  .libscroll{flex:1;overflow:auto;padding:12px;min-height:200px}
  .libgrid{display:grid;grid-template-columns:repeat(auto-fill,minmax(48px,1fr));gap:8px}
  .li{aspect-ratio:1;border-radius:11px;display:grid;place-items:center;background:var(--panel2);border:1px solid var(--line);color:var(--ink);cursor:grab;transition:.12s;font-size:22px}
  .li:hover{border-color:var(--cyan);color:var(--cyan);transform:translateY(-2px);box-shadow:0 8px 18px -10px rgba(0,255,224,.5)}
  .li.pick{outline:2px solid var(--yellow);outline-offset:1px;color:var(--yellow)}
  /* SVG library icons (the curated controllers) render BIGGER + keep aspect
     (viewBox scales to fit, no squish) - they are wider/more detailed than glyphs. */
  .li svg{width:auto;height:auto;max-width:30px;max-height:26px}
  .noicon{background:rgba(255,94,122,.1);color:var(--danger);border:1px solid rgba(255,94,122,.35);border-radius:10px;padding:8px 12px;font-size:13px;font-weight:700;white-space:nowrap}
  .noicon.on{background:rgba(255,94,122,.22);box-shadow:0 0 0 2px rgba(255,94,122,.35)}
  .tprev.none,.tnew.none{color:var(--danger)}
  .empty{color:var(--muted);text-align:center;padding:40px;font-size:14px}
  .tgtcol{display:flex;flex-direction:column;min-height:0}
  .tgttabs{display:flex;gap:6px;margin-bottom:10px;flex-wrap:wrap}
  .tt{background:var(--panel);border:1px solid var(--line);color:var(--muted);border-radius:999px;padding:6px 12px;font-size:12px;font-weight:700}
  .tt.on{background:rgba(0,255,224,.14);border-color:rgba(0,255,224,.4);color:var(--cyan)}
  .tgtscroll{overflow:auto;display:flex;flex-direction:column;gap:8px;padding-inline-end:4px}
  .tgt{background:var(--panel);border:1px solid var(--line);border-radius:13px;padding:10px;display:flex;gap:10px;align-items:center;transition:.15s;cursor:pointer;position:relative}
  .tgt.sel{outline:2px solid var(--yellow);outline-offset:2px}
  .tgt.changed{border-color:rgba(34,197,94,.5)}
  .tgt.dragover{border-color:var(--cyan);background:var(--panel2);box-shadow:0 0 0 2px rgba(0,255,224,.4)}
  .tprev{width:44px;height:44px;flex:0 0 44px;border-radius:10px;display:grid;place-items:center;background:radial-gradient(circle at 40% 30%,#12162e,#090b16);border:1px solid var(--line);color:var(--cyan);position:relative}
  .tprev.empty{border-style:dashed;color:#5b638c;font-size:10px}
  .tprev svg{width:25px;height:25px} .tprev i{font-size:23px;line-height:1}
  .arrow{color:var(--muted);font-size:15px}
  .tnew{width:44px;height:44px;flex:0 0 44px;border-radius:10px;display:grid;place-items:center;background:rgba(34,197,94,.08);border:1px dashed rgba(34,197,94,.4);color:var(--green)}
  .tnew svg{width:25px;height:25px} .tnew i{font-size:23px;line-height:1}
  .tmeta{flex:1;min-width:0}
  .tmeta .nm{font-weight:700;font-size:13px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
  .tmeta .lc{font-size:10px;color:#7f88b0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:2px}
  .tbtns{display:flex;gap:5px;margin-top:5px}
  .tb{font-size:10px;padding:3px 7px;border-radius:7px}
  .tb.up{background:rgba(0,255,224,.12);color:var(--cyan);border:1px solid rgba(0,255,224,.3)}
  .tb.rev{background:rgba(255,94,122,.1);color:var(--danger);border:1px solid rgba(255,94,122,.3)}
  .foot{position:sticky;bottom:0;z-index:20;background:linear-gradient(0deg,rgba(5,6,15,.97),rgba(5,6,15,.75));border-top:1px solid var(--line);padding:10px 22px;display:flex;align-items:center;gap:14px;justify-content:center;backdrop-filter:blur(8px)}
  .foot .txt{color:var(--muted);font-size:13px} .foot b{color:var(--green)}
  #flash{position:fixed;top:70px;right:50%;transform:translateX(50%);z-index:60;background:#1a1030;border:1px solid rgba(0,255,224,.5);color:#cfeee9;padding:9px 15px;border-radius:11px;font-size:13px;box-shadow:0 12px 30px -12px rgba(0,0,0,.8);opacity:0;transition:opacity .3s;pointer-events:none}
</style>
</head>
<body>
<header>
  <div class="brand"><div class="logo">🎨</div>
    <div><h1>מנהל האייקונים <span class="pill" id="libCount">0</span></h1>
      <div class="sub">Flaticon · Interface icons · Regular - לפי קטגוריות + חיפוש. גרור אייקון אל שקע, או בחר שקע ואז אייקון.</div></div>
  </div>
  <button class="btn-ghost" id="revertAll">בטל הכול</button>
  <button class="btn-primary" id="exportBtn">⬇ ייצוא שינויים</button>
</header>

<div class="note">
  <b>הקובץ מעודכן:</b> האייקונים שכבר בחרת מוצגים כמצב <b>הנוכחי</b> של כל שקע - בחירה חדשה תייצא רק את ההבדל.
  <b>ספרייה לפי קטגוריות</b> (כולל <b>«בקרים ומשחק»</b> עם שלטי Xbox / PlayStation / Switch / Steam Deck / הגה / VR ועוד, גדולים וללא עיוות) + חיפוש.
  גרור אייקון אל שקע, או בחר שקע ואז אייקון; אפשר גם <b>«העלה SVG»</b> או <b>«🚫 ללא אייקון»</b> כדי <b>להסיר</b> אייקון משקע.
  בסיום <b>«ייצוא שינויים»</b> → <code>icon-changes.json</code>.
</div>

<div class="wrap">
  <div class="libcol">
    <div class="libhead"><h2>ספריית אייקונים</h2>
      <input class="search" id="search" placeholder="חיפוש… (xbox, home, user, play, download)" dir="ltr" />
      <button class="noicon" id="noIcon" title="הסר אייקון מהשקע - שיישאר ללא אייקון">🚫 ללא אייקון</button>
      <span class="pill" id="shownCount">0</span></div>
    <div class="cats" id="cats"></div>
    <div class="libscroll"><div class="libgrid" id="libgrid"></div><div class="empty" id="libEmpty" style="display:none">לא נמצאו אייקונים.</div></div>
  </div>
  <div class="tgtcol">
    <div class="tgttabs">
      <button class="tt on" data-g="existing">קיימים <span id="c-existing"></span></button>
      <button class="tt" data-g="window">פס חלון <span id="c-window"></span></button>
      <button class="tt" data-g="notify">התראות <span id="c-notify"></span></button>
      <button class="tt" data-g="controllers">שלטים <span id="c-controllers"></span></button>
      <button class="tt" data-g="optional">ללא אייקון <span id="c-optional"></span></button>
      <button class="tt" data-g="app">כל האייקונים <span id="c-app"></span></button>
    </div>
    <div class="tgtscroll" id="targets"></div>
  </div>
</div>

<div class="foot"><span class="txt">שונו/נבחרו: <b id="changedCount">0</b></span><button class="btn-primary" id="exportBtn2">⬇ ייצוא שינויים</button></div>
<div id="flash"></div>

<script>
const TARGETS = __TARGETS__;
const LIB = __LIB__;          // [{n,k} font | {s,l,v,k} svg]
const CATS = __CATS__;        // [{k,l}]
const UICODE = __UICODE__;
const GROUP_LABEL = {existing:'קיים', window:'פס חלון', notify:'התראות', controllers:'שלטים', optional:'ללא אייקון', app:'אייקון'};

const state = {};          // targetId -> {type:'uicons',name} | {type:'svg',svg}
let selTarget=null, pickIcon=null, curGroup='existing', curCat='all', query='';
const $ = s => document.querySelector(s);
const libgrid=$('#libgrid'), targets=$('#targets');
function isSvg(t){ return typeof t==='string' && /<svg[\s>]/i.test(t) && /<\/svg>/i.test(t); }
function noneGlyph(){ return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><circle cx="12" cy="12" r="9"/><line x1="5.6" y1="5.6" x2="18.4" y2="18.4"/></svg>'; }
function newHTML(ch){ if(!ch) return ''; if(ch.type==='none') return noneGlyph(); return ch.type==='svg'?ch.svg:'<i class="fi-rr-'+ch.name+'"></i>'; }
// A library entry renders as a font <i> (font icons) or inline svg (curated gaming).
function libHTML(e){ return e.n ? ('<i class="fi-rr-'+e.n+'"></i>') : e.v; }
function libKey(e){ return e.n || e.s; }               // stable id
function libLabel(e){ return e.n || e.l; }             // searchable text
function libAssign(e){ return e.n ? {type:'uicons',name:e.n} : {type:'svg',svg:e.v}; }

function renderTargets(){
  targets.innerHTML='';
  for(const t of TARGETS.filter(x=>x.group===curGroup)){
    const ch=state[t.id];
    const cur = t.svg ? ('<div class="tprev">'+t.svg+'</div>') : '<div class="tprev empty">ריק</div>';
    const d=document.createElement('div');
    d.className='tgt'+(ch?' changed':'')+(selTarget===t.id?' sel':''); d.dataset.id=t.id;
    d.innerHTML = cur + (ch?'<span class="arrow">←</span><div class="tnew'+(ch.type==='none'?' none':'')+'">'+newHTML(ch)+'</div>':'') +
      '<div class="tmeta"><div class="nm">'+t.name+'</div><div class="lc">'+t.location+'</div>'+
      '<div class="tbtns"><button class="tb up" data-up="'+t.id+'">⬆ SVG</button>'+(ch?'<button class="tb rev" data-rev="'+t.id+'">בטל</button>':'')+'</div></div>';
    d.addEventListener('click',e=>{ if(e.target.closest('button'))return;
      if(pickIcon){ assign(t.id,pickIcon); pickIcon=null; renderLib(); return; }
      selTarget=selTarget===t.id?null:t.id; renderTargets(); });
    d.addEventListener('dragover',e=>{e.preventDefault();d.classList.add('dragover');});
    d.addEventListener('dragleave',()=>d.classList.remove('dragover'));
    d.addEventListener('drop',async e=>{ e.preventDefault();d.classList.remove('dragover');
      const nm=e.dataTransfer.getData('text/uicon'); if(nm){ assign(t.id,{type:'uicons',name:nm}); return; }
      const sv=e.dataTransfer.getData('text/svgicon'); if(sv){ assign(t.id,{type:'svg',svg:sv}); return; }
      const f=e.dataTransfer.files&&e.dataTransfer.files[0]; if(f){ const x=await f.text(); if(isSvg(x)) assign(t.id,{type:'svg',svg:x.trim()}); else flash('SVG לא תקין'); } });
    targets.appendChild(d);
  }
  targets.querySelectorAll('[data-up]').forEach(b=>b.addEventListener('click',()=>pickFile(b.getAttribute('data-up'))));
  targets.querySelectorAll('[data-rev]').forEach(b=>b.addEventListener('click',()=>{delete state[b.getAttribute('data-rev')];renderTargets();counts();}));
  counts();
}
function assign(id,ch){ state[id]=ch; selTarget=null; renderTargets(); counts(); const t=TARGETS.find(x=>x.id===id); flash('הוקצה: '+t.name); }
function pickFile(id){ const i=document.createElement('input'); i.type='file'; i.accept='.svg,image/svg+xml';
  i.onchange=async()=>{ const f=i.files[0]; if(!f)return; const x=await f.text(); if(isSvg(x)) assign(id,{type:'svg',svg:x.trim()}); else flash('SVG לא תקין'); }; i.click(); }

function currentList(){
  let a = LIB;
  if(curCat!=='all') a = a.filter(e=>e.k===curCat);
  if(query) a = a.filter(e=>libLabel(e).toLowerCase().includes(query));
  return a;
}
function renderLib(){
  const shown=currentList();
  const frag=document.createDocumentFragment();
  for(const e of shown){ const key=libKey(e); const b=document.createElement('button');
    b.className='li'+(pickIcon&&pickIcon.__k===key?' pick':''); b.title=libLabel(e); b.draggable=true; b.innerHTML=libHTML(e);
    b.addEventListener('dragstart',ev=>{ if(e.n){ev.dataTransfer.setData('text/uicon',e.n);} else {ev.dataTransfer.setData('text/svgicon',e.v);} ev.dataTransfer.effectAllowed='copy';});
    b.addEventListener('click',()=>{ const ch=libAssign(e); ch.__k=key;
      if(selTarget){ assign(selTarget,libAssign(e)); } else { pickIcon=(pickIcon&&pickIcon.__k===key)?null:ch; renderLib(); flash(pickIcon?('נבחר: '+libLabel(e)+' - לחץ על שקע'):''); } });
    frag.appendChild(b); }
  libgrid.innerHTML=''; libgrid.appendChild(frag);
  $('#libEmpty').style.display=shown.length?'none':'block'; $('#shownCount').textContent=shown.length;
  syncNoIcon();
}
function syncNoIcon(){ const b=$('#noIcon'); if(b) b.classList.toggle('on', !!(pickIcon && pickIcon.type==='none')); }
$('#noIcon').addEventListener('click',()=>{
  if(selTarget){ assign(selTarget,{type:'none'}); return; }   // slot already chosen → remove now
  pickIcon = (pickIcon && pickIcon.type==='none') ? null : {type:'none',__k:'__none__'};
  renderLib(); flash(pickIcon?'ללא אייקון נבחר - לחץ על שקע כדי להסיר את האייקון שלו':'');
});
// category chips
const catsEl=$('#cats');
for(const c of CATS){ const b=document.createElement('button'); b.className='cat'+(c.k==='all'?' on':''); b.textContent=c.l; b.dataset.k=c.k;
  b.addEventListener('click',()=>{ curCat=c.k; catsEl.querySelectorAll('.cat').forEach(x=>x.classList.toggle('on',x===b)); renderLib(); });
  catsEl.appendChild(b); }
let ft; $('#search').addEventListener('input',e=>{ clearTimeout(ft); const q=e.target.value.trim().toLowerCase();
  ft=setTimeout(()=>{ query=q; renderLib(); },110); });
document.querySelectorAll('.tt').forEach(b=>b.addEventListener('click',()=>{ curGroup=b.getAttribute('data-g');
  document.querySelectorAll('.tt').forEach(x=>x.classList.toggle('on',x===b)); selTarget=null; renderTargets(); }));

function counts(){ $('#changedCount').textContent=Object.keys(state).length;
  for(const g of ['existing','window','notify','controllers','optional','app']){ const tot=TARGETS.filter(t=>t.group===g).length;
    const ch=TARGETS.filter(t=>t.group===g&&state[t.id]).length; $('#c-'+g).textContent=ch?('('+ch+'/'+tot+')'):('('+tot+')'); } }
function flash(m){ const n=$('#flash'); if(!m){n.style.opacity='0';return;} n.textContent=m; n.style.opacity='1'; clearTimeout(n._t); n._t=setTimeout(()=>n.style.opacity='0',2000); }

function exportChanges(){
  const changes=Object.keys(state).map(id=>{ const t=TARGETS.find(x=>x.id===id), ch=state[id];
    const base={id,group:t.group,name:t.name,location:t.location,action:(t.group==='optional'?'add':'replace')};
    if(ch.type==='none') return {...base,action:'remove',iconType:'none'};
    if(ch.type==='uicons') return {...base,iconType:'flaticon-uicons-regular-rounded',iconName:ch.name,unicode:UICODE[ch.name]||null};
    return {...base,iconType:'svg-upload',newSvg:ch.svg}; });
  if(!changes.length){ flash('אין שינויים לייצא'); return; }
  const blob=new Blob([JSON.stringify({generatedAt:new Date().toISOString(),changes},null,2)],{type:'application/json'});
  const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='icon-changes.json'; a.click(); URL.revokeObjectURL(a.href);
  flash('הורד icon-changes.json - שלח אליי');
}
$('#exportBtn').onclick=exportChanges; $('#exportBtn2').onclick=exportChanges;
$('#revertAll').onclick=()=>{ for(const k in state)delete state[k]; selTarget=null;pickIcon=null; renderTargets(); renderLib(); };
$('#libCount').textContent=LIB.length;
renderTargets(); renderLib();
</script>
</body>
</html>'''

HTML = (HTML.replace('__TARGETS__', TARGETS_JS)
            .replace('__LIB__', LIB_JS)
            .replace('__CATS__', CATS_JS)
            .replace('__UICODE__', code_map_js))
open(os.path.join(HERE, 'icon-manager.html'), 'w', encoding='utf-8').write(HTML)
# category coverage report
from collections import Counter
cnt = Counter(categorize(n) for n, _ in UICONS)
print('wrote icon-manager.html (', len(HTML), 'bytes ) - library:', len(UICONS), 'font +', len(GAMELIB), 'curated gaming svgs')
print('categories:', {CAT_LABELS.get(k, k): v for k, v in cnt.most_common()})
